-- 对齐 AIOps 凭据 nonce 的二进制长度约束。
-- 仅调整约束表达式，不读取或修改任何凭据数据。

SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

DECLARE
    l_count PLS_INTEGER;
BEGIN
    SELECT COUNT(*) INTO l_count
      FROM user_constraints
     WHERE constraint_name = 'CK_OPS_CREDENTIAL_NONCE'
       AND table_name = 'KBOT_OPS_CREDENTIAL';
    IF l_count = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE KBOT_OPS_CREDENTIAL DROP CONSTRAINT CK_OPS_CREDENTIAL_NONCE';
    END IF;
    EXECUTE IMMEDIATE q'[
        ALTER TABLE KBOT_OPS_CREDENTIAL
        ADD CONSTRAINT CK_OPS_CREDENTIAL_NONCE
        CHECK (
            LENGTH(RAWTOHEX(USERNAME_NONCE)) = 24
            AND LENGTH(RAWTOHEX(PASSWORD_NONCE)) = 24
        )
    ]';
END;
/
