-- 一次性创建或重置受保护的平台 ADMIN，不授予任何业务 App 权限。
-- SQL Developer 使用 Run Script（F5）执行，不需要输入变量。

SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
    c_user_id       CONSTANT VARCHAR2(256 CHAR) := 'ADMIN';
    c_display_name  CONSTANT VARCHAR2(256 CHAR) := 'KBot 全局管理员';
    c_password_hash CONSTANT VARCHAR2(128 CHAR) :=
        '$2b$12$5WDXCasJPPANzr/QGlwbA.WOQxDa5Jq.RGGuFupPG1oossZZYKS3W';
BEGIN
    MERGE INTO KBOT_PLATFORM_USER target
    USING (SELECT c_user_id USER_ID, c_display_name DISPLAY_NAME FROM DUAL) source
    ON (target.USER_ID = source.USER_ID)
    WHEN MATCHED THEN UPDATE SET
        target.DISPLAY_NAME = source.DISPLAY_NAME,
        target.ACCOUNT_ORIGIN = 'PLATFORM', target.OWNER_APP_ID = NULL,
        target.IS_PROTECTED = 'Y', target.MAX_SECURITY_LEVEL = 3,
        target.STATUS = 'ACTIVE', target.UPDATED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
        USER_ID, DISPLAY_NAME, ACCOUNT_ORIGIN, OWNER_APP_ID, IS_PROTECTED,
        MAX_SECURITY_LEVEL, STATUS, CREATED_AT, UPDATED_AT
    ) VALUES (
        source.USER_ID, source.DISPLAY_NAME, 'PLATFORM', NULL, 'Y',
        3, 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP
    );

    MERGE INTO KBOT_PLATFORM_USER_CREDENTIAL target
    USING (SELECT c_user_id USER_ID, c_password_hash PASSWORD_HASH FROM DUAL) source
    ON (target.USER_ID = source.USER_ID)
    WHEN MATCHED THEN UPDATE SET
        target.PASSWORD_HASH = source.PASSWORD_HASH,
        target.MUST_CHANGE_PASSWORD = 'N',
        target.PASSWORD_UPDATED_AT = SYSTIMESTAMP,
        target.UPDATED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
        USER_ID, PASSWORD_HASH, MUST_CHANGE_PASSWORD,
        PASSWORD_UPDATED_AT, CREATED_AT, UPDATED_AT
    ) VALUES (
        source.USER_ID, source.PASSWORD_HASH, 'N',
        SYSTIMESTAMP, SYSTIMESTAMP, SYSTIMESTAMP
    );

    MERGE INTO KBOT_PLATFORM_USER_ROLE target
    USING (SELECT c_user_id USER_ID, 'platform_admin' ROLE_CODE FROM DUAL) source
    ON (target.USER_ID = source.USER_ID AND target.ROLE_CODE = source.ROLE_CODE)
    WHEN MATCHED THEN UPDATE SET target.STATUS = 'ACTIVE'
    WHEN NOT MATCHED THEN INSERT (
        USER_ID, ROLE_CODE, STATUS, CREATED_BY, CREATED_AT
    ) VALUES (
        source.USER_ID, source.ROLE_CODE, 'ACTIVE',
        'bootstrap:global_admin', SYSTIMESTAMP
    );

    DELETE FROM KBOT_APP_MEMBER_ROLE_SCOPE WHERE USER_ID = c_user_id;
    DELETE FROM KBOT_APP_MEMBER_ROLE WHERE USER_ID = c_user_id;
    DELETE FROM KBOT_APP_MEMBER WHERE USER_ID = c_user_id;
    COMMIT;
    dbms_output.put_line('平台 ADMIN 初始化完成，未授予任何业务 App 权限。');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        dbms_output.put_line('平台 ADMIN 初始化失败：' || SQLERRM);
        RAISE;
END;
/

SELECT USER_ID, ACCOUNT_ORIGIN, OWNER_APP_ID, IS_PROTECTED,
       MAX_SECURITY_LEVEL, STATUS
  FROM KBOT_PLATFORM_USER
 WHERE USER_ID = 'ADMIN';

SELECT USER_ID, ROLE_CODE, STATUS
  FROM KBOT_PLATFORM_USER_ROLE
 WHERE USER_ID = 'ADMIN';
