-- 在旧权限模型升级前，将小写 admin 一次性规范为大写 ADMIN。
-- 仅当 KBOT_APP_MEMBER_ROLE 仍含 DOMAIN_ID 时执行；SQL Developer 使用 F5。

SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
    l_old_model_count PLS_INTEGER;
    l_lower_count     PLS_INTEGER;
    l_upper_count     PLS_INTEGER;
BEGIN
    SELECT COUNT(*) INTO l_old_model_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'KBOT_APP_MEMBER_ROLE'
       AND COLUMN_NAME = 'DOMAIN_ID';
    IF l_old_model_count <> 1 THEN
        raise_application_error(-20001, '该脚本只允许在旧权限模型迁移前执行。');
    END IF;

    SELECT COUNT(*) INTO l_lower_count
      FROM KBOT_PLATFORM_USER WHERE USER_ID = 'admin';
    SELECT COUNT(*) INTO l_upper_count
      FROM KBOT_PLATFORM_USER WHERE USER_ID = 'ADMIN';

    IF l_lower_count = 0 AND l_upper_count = 1 THEN
        dbms_output.put_line('ADMIN 已规范，无需迁移。');
        RETURN;
    END IF;
    IF l_lower_count <> 1 OR l_upper_count <> 0 THEN
        raise_application_error(-20002, '无法确定唯一的小写 admin，拒绝修改。');
    END IF;

    INSERT INTO KBOT_PLATFORM_USER (
        USER_ID, DISPLAY_NAME, MAX_SECURITY_LEVEL,
        STATUS, CREATED_AT, UPDATED_AT
    )
    SELECT 'ADMIN', DISPLAY_NAME, 3, STATUS, CREATED_AT, SYSTIMESTAMP
      FROM KBOT_PLATFORM_USER WHERE USER_ID = 'admin';

    INSERT INTO KBOT_PLATFORM_USER_CREDENTIAL (
        USER_ID, PASSWORD_HASH, MUST_CHANGE_PASSWORD,
        PASSWORD_UPDATED_AT, CREATED_AT, UPDATED_AT
    )
    SELECT 'ADMIN', PASSWORD_HASH, MUST_CHANGE_PASSWORD,
           PASSWORD_UPDATED_AT, CREATED_AT, SYSTIMESTAMP
      FROM KBOT_PLATFORM_USER_CREDENTIAL WHERE USER_ID = 'admin';

    INSERT INTO KBOT_APP_MEMBER_ROLE (
        APP_ID, DOMAIN_ID, USER_ID, ROLE_CODE,
        STATUS, CREATED_BY, CREATED_AT
    )
    SELECT APP_ID, DOMAIN_ID, 'ADMIN', ROLE_CODE,
           STATUS, CREATED_BY, CREATED_AT
      FROM KBOT_APP_MEMBER_ROLE WHERE USER_ID = 'admin';

    DELETE FROM KBOT_APP_MEMBER_ROLE WHERE USER_ID = 'admin';
    DELETE FROM KBOT_PLATFORM_USER_CREDENTIAL WHERE USER_ID = 'admin';
    DELETE FROM KBOT_PLATFORM_USER WHERE USER_ID = 'admin';
    COMMIT;
    dbms_output.put_line('全局管理员已规范为 ADMIN。');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        dbms_output.put_line('管理员规范化失败：' || SQLERRM);
        RAISE;
END;
/

SELECT USER_ID, DISPLAY_NAME, MAX_SECURITY_LEVEL, STATUS
  FROM KBOT_PLATFORM_USER
 WHERE USER_ID IN ('admin', 'ADMIN')
 ORDER BY USER_ID;
