-- 将既有 KBot 4.0 用户授权一次性切换为平台/App/Domain 分层模型。
-- SQL Developer 使用 Run Script（F5）执行；执行前必须完成数据库备份。
-- 本脚本不创建初始 App 管理员，迁移后由平台 ADMIN 调用专用接口创建。
-- 旧业务 system_admin 会转换为普通 App Grant/App 用户的 app_admin 角色，
-- 不会被标记为受保护的唯一初始管理员。

SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

DECLARE
    l_old_column_count PLS_INTEGER;
    l_new_table_count  PLS_INTEGER;
    l_admin_count      PLS_INTEGER;
BEGIN
    SELECT COUNT(*) INTO l_old_column_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'KBOT_APP_MEMBER_ROLE'
       AND COLUMN_NAME = 'DOMAIN_ID';

    SELECT COUNT(*) INTO l_new_table_count
      FROM USER_TABLES
     WHERE TABLE_NAME IN (
        'KBOT_PLATFORM_APP', 'KBOT_APP_MEMBER',
        'KBOT_APP_MEMBER_ROLE_SCOPE'
     );

    SELECT COUNT(*) INTO l_admin_count
      FROM KBOT_PLATFORM_USER user_row
      JOIN KBOT_PLATFORM_USER_CREDENTIAL credential
        ON credential.USER_ID = user_row.USER_ID
     WHERE user_row.USER_ID = 'ADMIN';

    IF l_old_column_count <> 1 OR l_new_table_count <> 0 THEN
        raise_application_error(
            -20001,
            '当前 Schema 不是可迁移的旧权限模型，或迁移已经执行。'
        );
    END IF;
    IF l_admin_count <> 1 THEN
        raise_application_error(
            -20002,
            '未找到大写 ADMIN 及其凭据，请先完成管理员账号规范化。'
        );
    END IF;
END;
/

CREATE TABLE KBOT_PLATFORM_APP (
    APP_ID VARCHAR2(64 CHAR) PRIMARY KEY,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    MEMBER_ASSIGNABLE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_PLATFORM_APP_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_PLATFORM_APP_MEMBER CHECK (MEMBER_ASSIGNABLE IN ('Y', 'N'))
);

INSERT INTO KBOT_PLATFORM_APP (APP_ID, DISPLAY_NAME, STATUS, MEMBER_ASSIGNABLE)
SELECT APP_ID,
       CASE APP_ID
           WHEN 'platform' THEN '平台管理'
           WHEN 'knowledge_retrieval' THEN '知识检索'
           WHEN 'aiops' THEN 'AIOps'
           WHEN 'km_asset' THEN 'KM Asset'
           ELSE APP_ID
       END,
       'ACTIVE',
       CASE WHEN APP_ID = 'platform' THEN 'N' ELSE 'Y' END
  FROM (
      SELECT DISTINCT APP_ID FROM KBOT_PERMISSION
      UNION SELECT 'platform' FROM DUAL
      UNION SELECT 'knowledge_retrieval' FROM DUAL
      UNION SELECT 'aiops' FROM DUAL
      UNION SELECT 'km_asset' FROM DUAL
  );

ALTER TABLE KBOT_PLATFORM_USER ADD (
    ACCOUNT_ORIGIN VARCHAR2(16 CHAR) DEFAULT 'PLATFORM' NOT NULL,
    OWNER_APP_ID VARCHAR2(64 CHAR),
    IS_PROTECTED CHAR(1 CHAR) DEFAULT 'N' NOT NULL
);

UPDATE KBOT_PLATFORM_USER user_row
   SET ACCOUNT_ORIGIN = 'APP',
       OWNER_APP_ID = (
           SELECT MIN(member_role.APP_ID)
             FROM KBOT_APP_MEMBER_ROLE member_role
            WHERE member_role.USER_ID = user_row.USER_ID
              AND member_role.APP_ID <> 'platform'
       )
 WHERE user_row.USER_ID <> 'ADMIN'
   AND NOT EXISTS (
       SELECT 1 FROM KBOT_APP_MEMBER_ROLE platform_role
        WHERE platform_role.USER_ID = user_row.USER_ID
          AND platform_role.APP_ID = 'platform'
   )
   AND 1 = (
       SELECT COUNT(DISTINCT member_role.APP_ID)
         FROM KBOT_APP_MEMBER_ROLE member_role
        WHERE member_role.USER_ID = user_row.USER_ID
          AND member_role.APP_ID <> 'platform'
   );

UPDATE KBOT_PLATFORM_USER
   SET ACCOUNT_ORIGIN = 'PLATFORM',
       OWNER_APP_ID = NULL,
       IS_PROTECTED = CASE WHEN USER_ID = 'ADMIN' THEN 'Y' ELSE 'N' END,
       MAX_SECURITY_LEVEL = CASE WHEN USER_ID = 'ADMIN' THEN 3 ELSE MAX_SECURITY_LEVEL END,
       STATUS = CASE WHEN USER_ID = 'ADMIN' THEN 'ACTIVE' ELSE STATUS END,
       UPDATED_AT = SYSTIMESTAMP
 WHERE ACCOUNT_ORIGIN = 'PLATFORM' OR USER_ID = 'ADMIN';

ALTER TABLE KBOT_PLATFORM_USER ADD CONSTRAINT FK_PLATFORM_USER_OWNER_APP
    FOREIGN KEY (OWNER_APP_ID) REFERENCES KBOT_PLATFORM_APP (APP_ID);
ALTER TABLE KBOT_PLATFORM_USER ADD CONSTRAINT CK_PLATFORM_USER_ORIGIN
    CHECK (ACCOUNT_ORIGIN IN ('PLATFORM', 'APP'));
ALTER TABLE KBOT_PLATFORM_USER ADD CONSTRAINT CK_PLATFORM_USER_OWNER CHECK (
    (ACCOUNT_ORIGIN = 'PLATFORM' AND OWNER_APP_ID IS NULL)
    OR (ACCOUNT_ORIGIN = 'APP' AND OWNER_APP_ID IS NOT NULL)
);
ALTER TABLE KBOT_PLATFORM_USER ADD CONSTRAINT CK_PLATFORM_USER_PROTECTED
    CHECK (IS_PROTECTED IN ('Y', 'N'));
CREATE INDEX IX_PLATFORM_USER_OWNER ON KBOT_PLATFORM_USER
    (ACCOUNT_ORIGIN, OWNER_APP_ID, STATUS);

ALTER TABLE KBOT_PERMISSION ADD CONSTRAINT FK_PERMISSION_APP
    FOREIGN KEY (APP_ID) REFERENCES KBOT_PLATFORM_APP (APP_ID);

ALTER TABLE KBOT_APP_ROLE ADD (
    IS_SYSTEM CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    SCOPE_POLICY VARCHAR2(32 CHAR) DEFAULT 'SELECTABLE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL
);
ALTER TABLE KBOT_APP_ROLE ADD CONSTRAINT FK_APP_ROLE_APP
    FOREIGN KEY (APP_ID) REFERENCES KBOT_PLATFORM_APP (APP_ID);
ALTER TABLE KBOT_APP_ROLE ADD CONSTRAINT CK_APP_ROLE_SYSTEM
    CHECK (IS_SYSTEM IN ('Y', 'N'));
ALTER TABLE KBOT_APP_ROLE ADD CONSTRAINT CK_APP_ROLE_SCOPE
    CHECK (SCOPE_POLICY IN ('PLATFORM', 'SELECTABLE', 'ALL_APP_DOMAINS'));

ALTER TABLE KBOT_PERMISSION ADD CONSTRAINT UK_PERMISSION_APP_CODE
    UNIQUE (APP_ID, PERMISSION_CODE);
ALTER TABLE KBOT_APP_ROLE_PERMISSION DROP CONSTRAINT FK_APP_ROLE_PERM_PERMISSION;
ALTER TABLE KBOT_APP_ROLE_PERMISSION ADD CONSTRAINT FK_APP_ROLE_PERM_PERMISSION
    FOREIGN KEY (APP_ID, PERMISSION_CODE)
    REFERENCES KBOT_PERMISSION (APP_ID, PERMISSION_CODE);

ALTER TABLE KBOT_APP_MEMBER_ROLE RENAME TO KBOT_APP_MEMBER_ROLE_OLD;
ALTER TABLE KBOT_APP_MEMBER_ROLE_OLD DROP PRIMARY KEY DROP INDEX;
ALTER TABLE KBOT_APP_MEMBER_ROLE_OLD DROP CONSTRAINT FK_APP_MEMBER_ROLE_ROLE;
ALTER TABLE KBOT_APP_MEMBER_ROLE_OLD DROP CONSTRAINT FK_APP_MEMBER_ROLE_DOMAIN;
ALTER TABLE KBOT_APP_MEMBER_ROLE_OLD DROP CONSTRAINT FK_APP_MEMBER_ROLE_USER;
ALTER TABLE KBOT_APP_MEMBER_ROLE_OLD DROP CONSTRAINT CK_APP_MEMBER_ROLE_STATUS;

CREATE TABLE KBOT_PLATFORM_USER_ROLE (
    USER_ID VARCHAR2(256 CHAR) NOT NULL,
    ROLE_CODE VARCHAR2(64 CHAR) NOT NULL,
    APP_ID VARCHAR2(64 CHAR) DEFAULT 'platform' NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PLATFORM_USER_ROLE PRIMARY KEY (USER_ID, ROLE_CODE),
    CONSTRAINT FK_PLATFORM_USER_ROLE_USER FOREIGN KEY (USER_ID)
        REFERENCES KBOT_PLATFORM_USER (USER_ID),
    CONSTRAINT FK_PLATFORM_USER_ROLE_ROLE FOREIGN KEY (APP_ID, ROLE_CODE)
        REFERENCES KBOT_APP_ROLE (APP_ID, ROLE_CODE),
    CONSTRAINT CK_PLATFORM_USER_ROLE_APP CHECK (APP_ID = 'platform'),
    CONSTRAINT CK_PLATFORM_USER_ROLE_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE KBOT_APP_DOMAIN (
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_APP_DOMAIN PRIMARY KEY (APP_ID, DOMAIN_ID),
    CONSTRAINT FK_APP_DOMAIN_APP FOREIGN KEY (APP_ID) REFERENCES KBOT_PLATFORM_APP (APP_ID),
    CONSTRAINT FK_APP_DOMAIN_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_APP_DOMAIN_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE KBOT_APP_MEMBER (
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    USER_ID VARCHAR2(256 CHAR) NOT NULL,
    MEMBER_SOURCE VARCHAR2(32 CHAR) NOT NULL,
    IS_INITIAL_ADMIN CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    GRANTED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_APP_MEMBER PRIMARY KEY (APP_ID, USER_ID),
    CONSTRAINT FK_APP_MEMBER_APP FOREIGN KEY (APP_ID) REFERENCES KBOT_PLATFORM_APP (APP_ID),
    CONSTRAINT FK_APP_MEMBER_USER FOREIGN KEY (USER_ID) REFERENCES KBOT_PLATFORM_USER (USER_ID),
    CONSTRAINT CK_APP_MEMBER_SOURCE CHECK (MEMBER_SOURCE IN ('APP_CREATED', 'PLATFORM_GRANT', 'APP_INITIAL_ADMIN')),
    CONSTRAINT CK_APP_MEMBER_INITIAL CHECK (IS_INITIAL_ADMIN IN ('Y', 'N')),
    CONSTRAINT CK_APP_MEMBER_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_APP_INITIAL_ACTIVE CHECK (IS_INITIAL_ADMIN = 'N' OR STATUS = 'ACTIVE')
);

CREATE UNIQUE INDEX UK_APP_INITIAL_ADMIN ON KBOT_APP_MEMBER (
    CASE WHEN IS_INITIAL_ADMIN = 'Y' THEN APP_ID END
);
CREATE INDEX IX_APP_MEMBER_USER ON KBOT_APP_MEMBER (USER_ID, STATUS, APP_ID);

CREATE TABLE KBOT_APP_MEMBER_ROLE (
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    USER_ID VARCHAR2(256 CHAR) NOT NULL,
    ROLE_CODE VARCHAR2(64 CHAR) NOT NULL,
    SCOPE_MODE VARCHAR2(32 CHAR) DEFAULT 'SELECTED_DOMAINS' NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_APP_MEMBER_ROLE PRIMARY KEY (APP_ID, USER_ID, ROLE_CODE),
    CONSTRAINT FK_APP_MEMBER_ROLE_ROLE FOREIGN KEY (APP_ID, ROLE_CODE)
        REFERENCES KBOT_APP_ROLE (APP_ID, ROLE_CODE),
    CONSTRAINT FK_APP_MEMBER_ROLE_MEMBER FOREIGN KEY (APP_ID, USER_ID)
        REFERENCES KBOT_APP_MEMBER (APP_ID, USER_ID),
    CONSTRAINT CK_APP_MEMBER_ROLE_SCOPE CHECK (SCOPE_MODE IN ('ALL_APP_DOMAINS', 'SELECTED_DOMAINS')),
    CONSTRAINT CK_APP_MEMBER_ROLE_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE KBOT_APP_MEMBER_ROLE_SCOPE (
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    USER_ID VARCHAR2(256 CHAR) NOT NULL,
    ROLE_CODE VARCHAR2(64 CHAR) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    CONSTRAINT PK_APP_MEMBER_ROLE_SCOPE PRIMARY KEY (APP_ID, USER_ID, ROLE_CODE, DOMAIN_ID),
    CONSTRAINT FK_APP_MEMBER_SCOPE_BINDING FOREIGN KEY (APP_ID, USER_ID, ROLE_CODE)
        REFERENCES KBOT_APP_MEMBER_ROLE (APP_ID, USER_ID, ROLE_CODE),
    CONSTRAINT FK_APP_MEMBER_SCOPE_DOMAIN FOREIGN KEY (APP_ID, DOMAIN_ID)
        REFERENCES KBOT_APP_DOMAIN (APP_ID, DOMAIN_ID)
);

MERGE INTO KBOT_APP_ROLE target
USING (
    SELECT APP_ID, 'app_admin' ROLE_CODE,
           DISPLAY_NAME || ' 初始管理员' DISPLAY_NAME
      FROM KBOT_PLATFORM_APP
     WHERE APP_ID <> 'platform' AND MEMBER_ASSIGNABLE = 'Y'
) source
ON (target.APP_ID = source.APP_ID AND target.ROLE_CODE = source.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (
    APP_ID, ROLE_CODE, DISPLAY_NAME, IS_SYSTEM,
    SCOPE_POLICY, STATUS, ROW_VERSION
) VALUES (
    source.APP_ID, source.ROLE_CODE, source.DISPLAY_NAME,
    'Y', 'ALL_APP_DOMAINS', 'ACTIVE', 1
);

INSERT INTO KBOT_APP_DOMAIN (APP_ID, DOMAIN_ID, STATUS, CREATED_BY, CREATED_AT)
SELECT APP_ID, DOMAIN_ID,
       CASE WHEN MAX(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END) = 1 THEN 'ACTIVE' ELSE 'DISABLED' END,
       'migration:access_scope', SYSTIMESTAMP
  FROM KBOT_APP_MEMBER_ROLE_OLD
 WHERE APP_ID <> 'platform'
 GROUP BY APP_ID, DOMAIN_ID;

INSERT INTO KBOT_APP_MEMBER (
    APP_ID, USER_ID, MEMBER_SOURCE, IS_INITIAL_ADMIN,
    STATUS, GRANTED_BY, CREATED_AT, UPDATED_AT
)
SELECT old_role.APP_ID, old_role.USER_ID,
       CASE WHEN user_row.ACCOUNT_ORIGIN = 'PLATFORM' THEN 'PLATFORM_GRANT' ELSE 'APP_CREATED' END,
       'N',
       CASE WHEN MAX(CASE WHEN old_role.STATUS = 'ACTIVE' THEN 1 ELSE 0 END) = 1 THEN 'ACTIVE' ELSE 'DISABLED' END,
       'migration:access_scope', MIN(old_role.CREATED_AT), SYSTIMESTAMP
  FROM KBOT_APP_MEMBER_ROLE_OLD old_role
  JOIN KBOT_PLATFORM_USER user_row ON user_row.USER_ID = old_role.USER_ID
 WHERE old_role.APP_ID <> 'platform'
   AND old_role.USER_ID <> 'ADMIN'
 GROUP BY old_role.APP_ID, old_role.USER_ID, user_row.ACCOUNT_ORIGIN;

INSERT INTO KBOT_APP_MEMBER_ROLE (
    APP_ID, USER_ID, ROLE_CODE, SCOPE_MODE, STATUS, CREATED_BY, CREATED_AT
)
SELECT APP_ID, USER_ID,
       CASE WHEN ROLE_CODE = 'system_admin' THEN 'app_admin' ELSE ROLE_CODE END,
       'SELECTED_DOMAINS',
       CASE WHEN MAX(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END) = 1 THEN 'ACTIVE' ELSE 'DISABLED' END,
       'migration:access_scope', MIN(CREATED_AT)
  FROM KBOT_APP_MEMBER_ROLE_OLD
 WHERE APP_ID <> 'platform'
   AND USER_ID <> 'ADMIN'
 GROUP BY APP_ID, USER_ID,
          CASE WHEN ROLE_CODE = 'system_admin' THEN 'app_admin' ELSE ROLE_CODE END;

INSERT INTO KBOT_APP_MEMBER_ROLE_SCOPE (APP_ID, USER_ID, ROLE_CODE, DOMAIN_ID)
SELECT DISTINCT APP_ID, USER_ID,
       CASE WHEN ROLE_CODE = 'system_admin' THEN 'app_admin' ELSE ROLE_CODE END,
       DOMAIN_ID
  FROM KBOT_APP_MEMBER_ROLE_OLD
 WHERE APP_ID <> 'platform'
   AND USER_ID <> 'ADMIN';

MERGE INTO KBOT_PERMISSION target
USING (
    SELECT 'platform:domain_manage' PERMISSION_CODE, 'platform' APP_ID, '管理平台 Domain' DISPLAY_NAME FROM DUAL
    UNION ALL SELECT 'platform:app_manage', 'platform', '管理 App 生命周期和初始管理员' FROM DUAL
    UNION ALL SELECT 'platform:app_grant_manage', 'platform', '显式授予平台用户 App 权限' FROM DUAL
    UNION ALL SELECT 'knowledge_retrieval:role_manage', 'knowledge_retrieval', '管理应用角色' FROM DUAL
    UNION ALL SELECT 'aiops:role_manage', 'aiops', '管理 AIOps 角色' FROM DUAL
    UNION ALL SELECT 'km_asset:role_manage', 'km_asset', '管理 KM Asset 角色' FROM DUAL
) source
ON (target.PERMISSION_CODE = source.PERMISSION_CODE)
WHEN NOT MATCHED THEN INSERT (PERMISSION_CODE, APP_ID, DISPLAY_NAME)
VALUES (source.PERMISSION_CODE, source.APP_ID, source.DISPLAY_NAME);

MERGE INTO KBOT_APP_ROLE target
USING (
    SELECT 'platform' APP_ID, 'platform_admin' ROLE_CODE,
           '平台管理员' DISPLAY_NAME FROM DUAL
) source
ON (target.APP_ID = source.APP_ID AND target.ROLE_CODE = source.ROLE_CODE)
WHEN MATCHED THEN UPDATE SET
    target.IS_SYSTEM = 'Y', target.SCOPE_POLICY = 'PLATFORM', target.STATUS = 'ACTIVE'
WHEN NOT MATCHED THEN INSERT (
    APP_ID, ROLE_CODE, DISPLAY_NAME, IS_SYSTEM,
    SCOPE_POLICY, STATUS, ROW_VERSION
) VALUES (
    source.APP_ID, source.ROLE_CODE, source.DISPLAY_NAME,
    'Y', 'PLATFORM', 'ACTIVE', 1
);

UPDATE KBOT_APP_ROLE
   SET IS_SYSTEM = 'Y',
       SCOPE_POLICY = CASE WHEN APP_ID = 'platform' THEN 'PLATFORM' ELSE SCOPE_POLICY END
 WHERE ROLE_CODE IN ('platform_admin', 'user', 'contributor', 'reviewer', 'operator', 'approver');

MERGE INTO KBOT_APP_ROLE target
USING (
    SELECT APP_ID, 'app_admin' ROLE_CODE,
           DISPLAY_NAME || ' 初始管理员' DISPLAY_NAME
      FROM KBOT_PLATFORM_APP
     WHERE APP_ID <> 'platform' AND MEMBER_ASSIGNABLE = 'Y'
) source
ON (target.APP_ID = source.APP_ID AND target.ROLE_CODE = source.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (
    APP_ID, ROLE_CODE, DISPLAY_NAME, IS_SYSTEM,
    SCOPE_POLICY, STATUS, ROW_VERSION
) VALUES (
    source.APP_ID, source.ROLE_CODE, source.DISPLAY_NAME,
    'Y', 'ALL_APP_DOMAINS', 'ACTIVE', 1
);

MERGE INTO KBOT_APP_ROLE_PERMISSION target
USING (
    SELECT permission.APP_ID, 'app_admin' ROLE_CODE, permission.PERMISSION_CODE
      FROM KBOT_PERMISSION permission
     WHERE permission.APP_ID <> 'platform'
) source
ON (
    target.APP_ID = source.APP_ID
    AND target.ROLE_CODE = source.ROLE_CODE
    AND target.PERMISSION_CODE = source.PERMISSION_CODE
)
WHEN NOT MATCHED THEN INSERT (APP_ID, ROLE_CODE, PERMISSION_CODE)
VALUES (source.APP_ID, source.ROLE_CODE, source.PERMISSION_CODE);

MERGE INTO KBOT_APP_ROLE_PERMISSION target
USING (
    SELECT 'platform' APP_ID, 'platform_admin' ROLE_CODE, PERMISSION_CODE
      FROM KBOT_PERMISSION WHERE APP_ID = 'platform'
) source
ON (
    target.APP_ID = source.APP_ID
    AND target.ROLE_CODE = source.ROLE_CODE
    AND target.PERMISSION_CODE = source.PERMISSION_CODE
)
WHEN NOT MATCHED THEN INSERT (APP_ID, ROLE_CODE, PERMISSION_CODE)
VALUES (source.APP_ID, source.ROLE_CODE, source.PERMISSION_CODE);

INSERT INTO KBOT_PLATFORM_USER_ROLE (
    USER_ID, ROLE_CODE, STATUS, CREATED_BY, CREATED_AT
)
SELECT DISTINCT old_role.USER_ID, 'platform_admin', 'ACTIVE',
       'migration:access_scope', SYSTIMESTAMP
  FROM KBOT_APP_MEMBER_ROLE_OLD old_role
  JOIN KBOT_PLATFORM_USER user_row ON user_row.USER_ID = old_role.USER_ID
 WHERE old_role.APP_ID = 'platform'
   AND user_row.ACCOUNT_ORIGIN = 'PLATFORM';

MERGE INTO KBOT_PLATFORM_USER_ROLE target
USING (SELECT 'ADMIN' USER_ID, 'platform_admin' ROLE_CODE FROM DUAL) source
ON (target.USER_ID = source.USER_ID AND target.ROLE_CODE = source.ROLE_CODE)
WHEN MATCHED THEN UPDATE SET target.STATUS = 'ACTIVE'
WHEN NOT MATCHED THEN INSERT (
    USER_ID, ROLE_CODE, STATUS, CREATED_BY, CREATED_AT
) VALUES (
    source.USER_ID, source.ROLE_CODE, 'ACTIVE',
    'migration:access_scope', SYSTIMESTAMP
);

DROP TABLE KBOT_APP_MEMBER_ROLE_OLD PURGE;

DELETE FROM KBOT_APP_ROLE_PERMISSION WHERE ROLE_CODE = 'system_admin';
DELETE FROM KBOT_APP_ROLE WHERE ROLE_CODE = 'system_admin';

COMMIT;

PROMPT === 迁移检查 ===

SELECT ACCOUNT_ORIGIN, OWNER_APP_ID, COUNT(*) USER_COUNT
  FROM KBOT_PLATFORM_USER
 GROUP BY ACCOUNT_ORIGIN, OWNER_APP_ID
 ORDER BY ACCOUNT_ORIGIN, OWNER_APP_ID;

SELECT APP_ID, MEMBER_SOURCE, COUNT(*) MEMBER_COUNT
  FROM KBOT_APP_MEMBER
 GROUP BY APP_ID, MEMBER_SOURCE
 ORDER BY APP_ID, MEMBER_SOURCE;

SELECT APP_ID, COUNT(*) INITIAL_ADMIN_COUNT
  FROM KBOT_APP_MEMBER
 WHERE IS_INITIAL_ADMIN = 'Y'
 GROUP BY APP_ID
 ORDER BY APP_ID;
