-- KBot 4.0 Agent Runtime：用户可选择的 Root Agent 定义。
-- Specialist 与 Skill 是代码级固定能力，不在本表创建伪 Agent 记录。

CREATE TABLE KBOT_AGENT_DEFINITION (
    AGENT_ID RAW(16) PRIMARY KEY,
    APP_ID NUMBER(38) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    AGENT_KEY VARCHAR2(128 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    ENABLED_CAPABILITIES_JSON JSON NOT NULL,
    ROUTER_LLM_MODEL_NAME VARCHAR2(128 CHAR),
    CONTEXT_LLM_MODEL_NAME VARCHAR2(128 CHAR) NOT NULL,
    COMPOSER_LLM_MODEL_NAME VARCHAR2(128 CHAR) NOT NULL,
    MEMORY_LLM_MODEL_NAME VARCHAR2(128 CHAR) NOT NULL,
    QUERY_VLM_MODEL_NAME VARCHAR2(128 CHAR),
    CHART_LLM_MODEL_NAME VARCHAR2(128 CHAR),
    MEMORY_EMBEDDING_MODEL_NAME VARCHAR2(128 CHAR) NOT NULL,
    DO_RERANK NUMBER(1) DEFAULT 0 NOT NULL,
    DATA_PROFILE_NAME VARCHAR2(256 CHAR),
    INSTRUCTION CLOB,
    CONFIG_JSON JSON NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_DEF_KEY UNIQUE (APP_ID, DOMAIN_ID, AGENT_KEY),
    CONSTRAINT UK_AGENT_DEF_SCOPE UNIQUE
        (AGENT_ID, APP_ID, DOMAIN_ID),
    CONSTRAINT FK_AGENT_DEF_DOMAIN
        FOREIGN KEY (DOMAIN_ID, APP_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID, APP_ID),
    CONSTRAINT CK_AGENT_DEF_KEY CHECK (
        REGEXP_LIKE(AGENT_KEY, '^[a-z][a-z0-9._-]{0,127}$')
    ),
    CONSTRAINT CK_AGENT_DEF_STATUS CHECK (
        STATUS IN ('DRAFT', 'ACTIVE', 'INACTIVE')
    ),
    CONSTRAINT CK_AGENT_DEF_RERANK CHECK (DO_RERANK IN (0, 1)),
    CONSTRAINT CK_AGENT_DEF_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_AGENT_DEF_DOMAIN_STATUS
    ON KBOT_AGENT_DEFINITION (APP_ID, DOMAIN_ID, STATUS, DISPLAY_NAME);

COMMENT ON COLUMN KBOT_AGENT_DEFINITION.AGENT_ID IS
    'UUIDv7；公开 API、KC Collection Binding 和 Run 共用的 Agent 标识';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.AGENT_KEY IS
    'Domain 内稳定技术名称，不作为主键或模型 API Key';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.ENABLED_CAPABILITIES_JSON IS
    '允许 Root Router 使用的固定能力集合，例如 document、conversation';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.COMPOSER_LLM_MODEL_NAME IS
    'Model Serving OpenAI 兼容接口使用的 served_model_name';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.CHART_LLM_MODEL_NAME IS
    'ECharts 配置生成使用的 served_model_name；为空时使用 Composer 模型';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.DATA_PROFILE_NAME IS
    'SelectAI/AIReport 问数服务使用的 Profile 名称';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.MEMORY_EMBEDDING_MODEL_NAME IS
    'Agent 记忆专用 Embedding served_model_name；创建后永久不可修改';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.DO_RERANK IS
    '问文时是否启用 Collection Retrieval LLM 对象级和 Evidence Group 重排';
