-- KBot 4.0 Agent Runtime：用户可选择的 Root Agent 定义。
-- Specialist 与 Skill 是代码级固定能力，不在本表创建伪 Agent 记录。

CREATE TABLE KBOT_AGENT_DEFINITION (
    AGENT_ID RAW(16) PRIMARY KEY,
    APP_ID NUMBER(38) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    AGENT_KEY VARCHAR2(128 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    ENABLED_CAPABILITIES_JSON CLOB NOT NULL,
    ROUTER_MODEL_NAME VARCHAR2(128 CHAR),
    COMPOSER_MODEL_NAME VARCHAR2(128 CHAR) NOT NULL,
    INSTRUCTION CLOB,
    CONFIG_JSON CLOB NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_DEF_KEY UNIQUE (APP_ID, DOMAIN_ID, AGENT_KEY),
    CONSTRAINT UK_AGENT_DEF_SCOPE UNIQUE
        (AGENT_ID, APP_ID, DOMAIN_ID),
    CONSTRAINT FK_AGENT_DEF_DOMAIN
        FOREIGN KEY (DOMAIN_ID, APP_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID, APP_ID),
    CONSTRAINT CK_AGENT_DEF_KEY CHECK (
        REGEXP_LIKE(AGENT_KEY, '^[a-z][a-z0-9._-]{0,127}$')
    ),
    CONSTRAINT CK_AGENT_DEF_STATUS CHECK (
        STATUS IN ('DRAFT', 'ACTIVE', 'INACTIVE')
    ),
    CONSTRAINT CK_AGENT_DEF_CAPABILITIES_JSON CHECK
        (ENABLED_CAPABILITIES_JSON IS JSON),
    CONSTRAINT CK_AGENT_DEF_CONFIG_JSON CHECK (CONFIG_JSON IS JSON),
    CONSTRAINT CK_AGENT_DEF_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_AGENT_DEF_DOMAIN_STATUS
    ON KBOT_AGENT_DEFINITION (APP_ID, DOMAIN_ID, STATUS, DISPLAY_NAME);

COMMENT ON COLUMN KBOT_AGENT_DEFINITION.AGENT_ID IS
    'UUIDv7；公开 API、KC Collection Binding 和 Run 共用的 Agent 标识';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.AGENT_KEY IS
    'Domain 内稳定技术名称，不作为主键或模型 API Key';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.ENABLED_CAPABILITIES_JSON IS
    '允许 Root Router 使用的固定能力集合，例如 document、conversation';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.COMPOSER_MODEL_NAME IS
    'Model Serving OpenAI 兼容接口使用的 served_model_name';
