-- KBot 4.0 Agent Runtime：用户可选择的 Root Agent 定义。
-- Specialist 与 Skill 是代码级固定能力，不在本表创建伪 Agent 记录。

CREATE TABLE KBOT_AGENT_DEFINITION (
    AGENT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    ENABLED_CAPABILITIES_JSON JSON NOT NULL,
    MODELS_JSON JSON NOT NULL,
    DO_RERANK NUMBER(1) DEFAULT 0 NOT NULL,
    DATA_QUERY_MODE VARCHAR2(16 CHAR),
    DATA_PROFILE_NAME VARCHAR2(256 CHAR),
    INSTRUCTION CLOB,
    CONFIG_JSON JSON NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_DEF_SCOPE UNIQUE
        (AGENT_ID, DOMAIN_ID),
    CONSTRAINT FK_AGENT_DEF_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_AGENT_DEF_STATUS CHECK (
        STATUS IN ('DRAFT', 'ACTIVE', 'INACTIVE')
    ),
    CONSTRAINT CK_AGENT_DEF_RERANK CHECK (DO_RERANK IN (0, 1)),
    CONSTRAINT CK_AGENT_DEF_DQ_MODE CHECK (
        DATA_QUERY_MODE IN ('MCP', 'SEMANTIC') OR DATA_QUERY_MODE IS NULL
    ),
    CONSTRAINT CK_AGENT_DEF_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_AGENT_DEF_DOMAIN_STATUS
    ON KBOT_AGENT_DEFINITION (DOMAIN_ID, STATUS, DISPLAY_NAME);

COMMENT ON COLUMN KBOT_AGENT_DEFINITION.AGENT_ID IS
    'UUIDv7；公开 API、KC Collection Binding 和 Run 共用的 Agent 标识';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.ENABLED_CAPABILITIES_JSON IS
    '允许 Root Router 使用的固定能力集合，例如 document、conversation';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.MODELS_JSON IS
    '功能角色到 AI_MODEL_ID(UUIDv7) 的映射；运行时解析并冻结调用快照';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.DATA_PROFILE_NAME IS
    'SelectAI/AIReport 问数服务使用的 Profile 名称';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.DATA_QUERY_MODE IS
    'data_query 能力的固定 Provider；只能由 Agent 配置选择 MCP 或 SEMANTIC';
COMMENT ON COLUMN KBOT_AGENT_DEFINITION.DO_RERANK IS
    '问文时是否启用 Collection Retrieval LLM 对象级和 Evidence Group 重排';
