-- KBot 4.0 Agent Runtime：不可变 Artifact 与追加式 Run Event。

CREATE TABLE KBOT_AGENT_ARTIFACT (
    ARTIFACT_ID RAW(16) PRIMARY KEY,
    RUN_ID RAW(16) NOT NULL,
    TASK_ID RAW(16),
    ARTIFACT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PRODUCER VARCHAR2(128 CHAR) NOT NULL,
    PRODUCER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PAYLOAD_JSON JSON,
    STORAGE_URI VARCHAR2(2048 CHAR),
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    PROVENANCE_JSON JSON NOT NULL,
    SECURITY_LEVEL NUMBER(3) DEFAULT 0 NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_ARTIFACT_RUN UNIQUE (ARTIFACT_ID, RUN_ID),
    CONSTRAINT FK_AGENT_ARTIFACT_RUN FOREIGN KEY (RUN_ID)
        REFERENCES KBOT_AGENT_RUN (RUN_ID),
    CONSTRAINT FK_AGENT_ARTIFACT_TASK FOREIGN KEY (TASK_ID, RUN_ID)
        REFERENCES KBOT_AGENT_TASK (TASK_ID, RUN_ID),
    CONSTRAINT CK_AGENT_ARTIFACT_CONTENT CHECK (
        PAYLOAD_JSON IS NOT NULL OR STORAGE_URI IS NOT NULL
    ),
    CONSTRAINT CK_AGENT_ARTIFACT_SECURITY CHECK (SECURITY_LEVEL >= 0)
);

CREATE INDEX IX_AGENT_ARTIFACT_RUN_TYPE
    ON KBOT_AGENT_ARTIFACT (RUN_ID, ARTIFACT_TYPE, CREATED_AT);
CREATE INDEX IX_AGENT_ARTIFACT_TASK
    ON KBOT_AGENT_ARTIFACT (TASK_ID, CREATED_AT);

ALTER TABLE KBOT_AGENT_RUN ADD CONSTRAINT FK_AGENT_RUN_RESULT
    FOREIGN KEY (RESULT_ARTIFACT_ID, RUN_ID)
    REFERENCES KBOT_AGENT_ARTIFACT (ARTIFACT_ID, RUN_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE KBOT_AGENT_TASK ADD CONSTRAINT FK_AGENT_TASK_OUTPUT
    FOREIGN KEY (OUTPUT_ARTIFACT_ID, RUN_ID)
    REFERENCES KBOT_AGENT_ARTIFACT (ARTIFACT_ID, RUN_ID)
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE KBOT_AGENT_RUN_EVENT (
    RUN_ID RAW(16) NOT NULL,
    SEQUENCE_NO NUMBER(19) NOT NULL,
    TASK_ID RAW(16),
    EVENT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    EVENT_KEY VARCHAR2(256 CHAR),
    ARTIFACT_ID RAW(16),
    EVENT_PAYLOAD_JSON JSON NOT NULL,
    ACTOR_TYPE VARCHAR2(32 CHAR) NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_AGENT_RUN_EVENT PRIMARY KEY (RUN_ID, SEQUENCE_NO),
    CONSTRAINT UK_AGENT_EVENT_KEY UNIQUE (RUN_ID, EVENT_KEY),
    CONSTRAINT FK_AGENT_EVENT_RUN FOREIGN KEY (RUN_ID)
        REFERENCES KBOT_AGENT_RUN (RUN_ID),
    CONSTRAINT FK_AGENT_EVENT_TASK FOREIGN KEY (TASK_ID, RUN_ID)
        REFERENCES KBOT_AGENT_TASK (TASK_ID, RUN_ID),
    CONSTRAINT FK_AGENT_EVENT_ARTIFACT FOREIGN KEY (ARTIFACT_ID, RUN_ID)
        REFERENCES KBOT_AGENT_ARTIFACT (ARTIFACT_ID, RUN_ID),
    CONSTRAINT CK_AGENT_EVENT_SEQUENCE CHECK (SEQUENCE_NO >= 1)
);

CREATE INDEX IX_AGENT_EVENT_TASK
    ON KBOT_AGENT_RUN_EVENT (TASK_ID, SEQUENCE_NO);
