-- KBot 4.0 Agent Runtime：Run 与可租约 Task。
-- 本脚本只用于创建全新的 4.0 Schema，不读取任何 3.x Agent 数据。

CREATE TABLE KBOT_AGENT_RUN (
    RUN_ID RAW(16) PRIMARY KEY,
    APP_ID NUMBER(38) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    PARENT_RUN_ID RAW(16),
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    REQUEST_ID VARCHAR2(128 CHAR) NOT NULL,
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    REQUEST_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
    ORIGINAL_INPUT CLOB NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'CREATED' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    POLICY_SNAPSHOT_JSON CLOB NOT NULL,
    CONFIG_SNAPSHOT_JSON CLOB NOT NULL,
    BUDGET_JSON CLOB NOT NULL,
    DEADLINE_AT TIMESTAMP(6) WITH TIME ZONE,
    FINAL_TASK_ID RAW(16),
    RESULT_ARTIFACT_ID RAW(16),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_RUN_IDEMP UNIQUE
        (APP_ID, DOMAIN_ID, ACTOR_ID, IDEMPOTENCY_KEY),
    CONSTRAINT UK_AGENT_RUN_SCOPE UNIQUE (RUN_ID, APP_ID, DOMAIN_ID),
    CONSTRAINT FK_AGENT_RUN_PARENT
        FOREIGN KEY (PARENT_RUN_ID, APP_ID, DOMAIN_ID)
        REFERENCES KBOT_AGENT_RUN (RUN_ID, APP_ID, DOMAIN_ID),
    CONSTRAINT FK_AGENT_RUN_DEFINITION
        FOREIGN KEY (AGENT_ID, APP_ID, DOMAIN_ID)
        REFERENCES KBOT_AGENT_DEFINITION (AGENT_ID, APP_ID, DOMAIN_ID),
    CONSTRAINT CK_AGENT_RUN_STATUS CHECK (STATUS IN (
        'CREATED', 'RUNNING', 'WAITING_INPUT', 'WAITING_APPROVAL',
        'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED'
    )),
    CONSTRAINT CK_AGENT_RUN_VERSION CHECK (ROW_VERSION >= 1),
    CONSTRAINT CK_AGENT_RUN_POLICY_JSON CHECK
        (POLICY_SNAPSHOT_JSON IS JSON),
    CONSTRAINT CK_AGENT_RUN_CONFIG_JSON CHECK
        (CONFIG_SNAPSHOT_JSON IS JSON),
    CONSTRAINT CK_AGENT_RUN_BUDGET_JSON CHECK (BUDGET_JSON IS JSON)
);

CREATE INDEX IX_AGENT_RUN_DOMAIN_TIME
    ON KBOT_AGENT_RUN (APP_ID, DOMAIN_ID, CREATED_AT);
CREATE INDEX IX_AGENT_RUN_STATUS_TIME
    ON KBOT_AGENT_RUN (STATUS, CREATED_AT);
CREATE INDEX IX_AGENT_RUN_AGENT_TIME
    ON KBOT_AGENT_RUN (AGENT_ID, CREATED_AT);

CREATE TABLE KBOT_AGENT_TASK (
    TASK_ID RAW(16) PRIMARY KEY,
    RUN_ID RAW(16) NOT NULL,
    PARENT_TASK_ID RAW(16),
    TASK_KEY VARCHAR2(64 CHAR) NOT NULL,
    TASK_TYPE VARCHAR2(64 CHAR) NOT NULL,
    EXECUTION_KIND VARCHAR2(24 CHAR) NOT NULL,
    SPECIALIST VARCHAR2(64 CHAR),
    SKILL_ID VARCHAR2(128 CHAR),
    SKILL_VERSION VARCHAR2(64 CHAR),
    DELEGATE_SERVICE VARCHAR2(128 CHAR),
    DELEGATE_CAPABILITY VARCHAR2(128 CHAR),
    EXECUTION_MODE VARCHAR2(16 CHAR) NOT NULL,
    COMPLETION_REQUIREMENT VARCHAR2(16 CHAR) DEFAULT 'REQUIRED' NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'PENDING' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    DEPENDS_ON_JSON CLOB NOT NULL,
    INPUT_ARTIFACTS_JSON CLOB NOT NULL,
    EXPECTED_OUTPUTS_JSON CLOB NOT NULL,
    REQUIRED_SCOPES_JSON CLOB NOT NULL,
    OUTPUT_ARTIFACT_ID RAW(16),
    ATTEMPT NUMBER(10) DEFAULT 0 NOT NULL,
    MAX_ATTEMPTS NUMBER(10) DEFAULT 1 NOT NULL,
    TIMEOUT_SECONDS NUMBER(10) NOT NULL,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    NEXT_RETRY_AT TIMESTAMP(6) WITH TIME ZONE,
    CANCEL_REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_TASK_KEY UNIQUE (RUN_ID, TASK_KEY),
    CONSTRAINT UK_AGENT_TASK_RUN UNIQUE (TASK_ID, RUN_ID),
    CONSTRAINT FK_AGENT_TASK_RUN FOREIGN KEY (RUN_ID)
        REFERENCES KBOT_AGENT_RUN (RUN_ID),
    CONSTRAINT FK_AGENT_TASK_PARENT
        FOREIGN KEY (PARENT_TASK_ID, RUN_ID)
        REFERENCES KBOT_AGENT_TASK (TASK_ID, RUN_ID),
    CONSTRAINT CK_AGENT_TASK_KIND CHECK
        (EXECUTION_KIND IN ('LOCAL_SKILL', 'DELEGATION')),
    CONSTRAINT CK_AGENT_TASK_MODE CHECK
        (EXECUTION_MODE IN ('read_only', 'mutation', 'delegated')),
    CONSTRAINT CK_AGENT_TASK_REQUIREMENT CHECK
        (COMPLETION_REQUIREMENT IN ('REQUIRED', 'OPTIONAL')),
    CONSTRAINT CK_AGENT_TASK_STATUS CHECK (STATUS IN (
        'PENDING', 'READY', 'RUNNING', 'WAITING_EXTERNAL', 'RETRY_WAIT',
        'BLOCKED', 'SUCCEEDED', 'FAILED', 'CANCELLED'
    )),
    CONSTRAINT CK_AGENT_TASK_VERSION CHECK (ROW_VERSION >= 1),
    CONSTRAINT CK_AGENT_TASK_ATTEMPTS CHECK (
        ATTEMPT >= 0 AND MAX_ATTEMPTS >= 1 AND ATTEMPT <= MAX_ATTEMPTS
    ),
    CONSTRAINT CK_AGENT_TASK_TIMEOUT CHECK (TIMEOUT_SECONDS > 0),
    CONSTRAINT CK_AGENT_TASK_EXECUTOR CHECK (
        (EXECUTION_KIND = 'LOCAL_SKILL'
            AND SKILL_ID IS NOT NULL AND SKILL_VERSION IS NOT NULL
            AND DELEGATE_SERVICE IS NULL AND DELEGATE_CAPABILITY IS NULL
            AND EXECUTION_MODE <> 'delegated')
        OR
        (EXECUTION_KIND = 'DELEGATION'
            AND SKILL_ID IS NULL AND SKILL_VERSION IS NULL
            AND DELEGATE_SERVICE IS NOT NULL
            AND DELEGATE_CAPABILITY IS NOT NULL
            AND EXECUTION_MODE = 'delegated')
    ),
    CONSTRAINT CK_AGENT_TASK_DEPENDS_JSON CHECK (DEPENDS_ON_JSON IS JSON),
    CONSTRAINT CK_AGENT_TASK_INPUT_JSON CHECK
        (INPUT_ARTIFACTS_JSON IS JSON),
    CONSTRAINT CK_AGENT_TASK_OUTPUT_JSON CHECK
        (EXPECTED_OUTPUTS_JSON IS JSON),
    CONSTRAINT CK_AGENT_TASK_SCOPES_JSON CHECK
        (REQUIRED_SCOPES_JSON IS JSON)
);

CREATE INDEX IX_AGENT_TASK_CLAIM
    ON KBOT_AGENT_TASK (STATUS, NEXT_RETRY_AT, CREATED_AT);
CREATE INDEX IX_AGENT_TASK_LEASE
    ON KBOT_AGENT_TASK (STATUS, LEASE_UNTIL);
CREATE INDEX IX_AGENT_TASK_RUN_STATUS
    ON KBOT_AGENT_TASK (RUN_ID, STATUS, CREATED_AT);

ALTER TABLE KBOT_AGENT_RUN ADD CONSTRAINT FK_AGENT_RUN_FINAL_TASK
    FOREIGN KEY (FINAL_TASK_ID, RUN_ID)
    REFERENCES KBOT_AGENT_TASK (TASK_ID, RUN_ID)
    DEFERRABLE INITIALLY DEFERRED;
