-- KBot 4.0 Agent Runtime：跨服务子 Agent Delegation。

CREATE TABLE KBOT_AGENT_DELEGATION (
    DELEGATION_ID RAW(16) PRIMARY KEY,
    PARENT_RUN_ID RAW(16) NOT NULL,
    PARENT_TASK_ID RAW(16) NOT NULL,
    TARGET_SERVICE VARCHAR2(128 CHAR) NOT NULL,
    TARGET_CAPABILITY VARCHAR2(128 CHAR) NOT NULL,
    CHILD_RUN_ID RAW(16),
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'CREATED' NOT NULL,
    LAST_CHILD_EVENT_SEQUENCE NUMBER(19) DEFAULT 0 NOT NULL,
    NEXT_POLL_AT TIMESTAMP(6) WITH TIME ZONE,
    RESULT_ARTIFACT_ID RAW(16),
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    MAX_ATTEMPTS NUMBER(10) DEFAULT 3 NOT NULL,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT UK_AGENT_DELEGATION_TASK UNIQUE (PARENT_TASK_ID),
    CONSTRAINT UK_AGENT_DELEGATION_IDEMP UNIQUE
        (TARGET_SERVICE, IDEMPOTENCY_KEY),
    CONSTRAINT UK_AGENT_DELEGATION_CHILD UNIQUE
        (TARGET_SERVICE, CHILD_RUN_ID),
    CONSTRAINT FK_AGENT_DELEGATION_TASK
        FOREIGN KEY (PARENT_TASK_ID, PARENT_RUN_ID)
        REFERENCES KBOT_AGENT_TASK (TASK_ID, RUN_ID),
    CONSTRAINT FK_AGENT_DELEGATION_RESULT
        FOREIGN KEY (RESULT_ARTIFACT_ID, PARENT_RUN_ID)
        REFERENCES KBOT_AGENT_ARTIFACT (ARTIFACT_ID, RUN_ID),
    CONSTRAINT CK_AGENT_DELEGATION_STATUS CHECK (STATUS IN (
        'CREATED', 'SUBMITTING', 'RUNNING', 'WAITING_INPUT',
        'WAITING_APPROVAL', 'COMPLETED', 'DEGRADED', 'FAILED',
        'CANCEL_REQUESTED', 'CANCELLED', 'EXPIRED'
    )),
    CONSTRAINT CK_AGENT_DELEGATION_EVENT CHECK
        (LAST_CHILD_EVENT_SEQUENCE >= 0),
    CONSTRAINT CK_AGENT_DELEGATION_TRIES CHECK (
        ATTEMPT_COUNT >= 0 AND MAX_ATTEMPTS >= 1
        AND ATTEMPT_COUNT <= MAX_ATTEMPTS
    ),
    CONSTRAINT CK_AGENT_DELEGATION_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_AGENT_DELEGATION_POLL
    ON KBOT_AGENT_DELEGATION (STATUS, NEXT_POLL_AT);
CREATE INDEX IX_AGENT_DELEGATION_LEASE
    ON KBOT_AGENT_DELEGATION (STATUS, LEASE_UNTIL);
CREATE INDEX IX_AGENT_DELEGATION_RUN
    ON KBOT_AGENT_DELEGATION (PARENT_RUN_ID, STATUS);
