-- KBot 4.0 Conversation、Turn 与不可变用户可见条目。

CREATE TABLE KBOT_AGENT_CONVERSATION (
    CONVERSATION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    TITLE VARCHAR2(512 CHAR),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    LAST_TURN_SEQUENCE NUMBER(19) DEFAULT 0 NOT NULL,
    LAST_ITEM_SEQUENCE NUMBER(19) DEFAULT 0 NOT NULL,
    RETENTION_POLICY VARCHAR2(32 CHAR) DEFAULT 'DEFAULT' NOT NULL,
    PURGE_AFTER TIMESTAMP(6) WITH TIME ZONE,
    LAST_ACTIVE_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_CONVERSATION_SCOPE UNIQUE
        (CONVERSATION_ID, DOMAIN_ID),
    CONSTRAINT FK_AGENT_CONVERSATION_DEF
        FOREIGN KEY (AGENT_ID, DOMAIN_ID)
        REFERENCES KBOT_AGENT_DEFINITION (AGENT_ID, DOMAIN_ID),
    CONSTRAINT CK_AGENT_CONVERSATION_STATUS CHECK
        (STATUS IN ('ACTIVE', 'ARCHIVED', 'DELETED')),
    CONSTRAINT CK_AGENT_CONV_RETENTION CHECK (
        RETENTION_POLICY IN (
            'DEFAULT', 'KEEP_FOREVER', 'DAYS_30', 'DAYS_90', 'DAYS_365'
        )
    ),
    CONSTRAINT CK_AGENT_CONVERSATION_VERSION CHECK (ROW_VERSION >= 1),
    CONSTRAINT CK_AGENT_CONVERSATION_SEQUENCE CHECK
        (LAST_TURN_SEQUENCE >= 0 AND LAST_ITEM_SEQUENCE >= 0)
);

CREATE INDEX IX_AGENT_CONVERSATION_ACTOR
    ON KBOT_AGENT_CONVERSATION
        (DOMAIN_ID, ACTOR_ID, LAST_ACTIVE_AT);
CREATE INDEX IX_AGENT_CONVERSATION_AGENT
    ON KBOT_AGENT_CONVERSATION (AGENT_ID, LAST_ACTIVE_AT);

CREATE TABLE KBOT_AGENT_CONVERSATION_TURN (
    TURN_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    TURN_SEQUENCE NUMBER(19) NOT NULL,
    USER_ITEM_ID RAW(16),
    ROOT_RUN_ID RAW(16),
    ASSISTANT_ITEM_ID RAW(16),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACCEPTED' NOT NULL,
    RAW_INPUT_HASH VARCHAR2(64 CHAR) NOT NULL,
    CONTEXT_SNAPSHOT_JSON JSON NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT UK_AGENT_TURN_SEQUENCE UNIQUE
        (CONVERSATION_ID, TURN_SEQUENCE),
    CONSTRAINT UK_AGENT_TURN_IDEMPOTENCY UNIQUE
        (CONVERSATION_ID, IDEMPOTENCY_KEY),
    CONSTRAINT UK_AGENT_TURN_RUN UNIQUE (ROOT_RUN_ID),
    CONSTRAINT UK_AGENT_TURN_SCOPE UNIQUE (TURN_ID, CONVERSATION_ID),
    CONSTRAINT FK_AGENT_TURN_CONVERSATION FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_AGENT_CONVERSATION (CONVERSATION_ID),
    CONSTRAINT FK_AGENT_TURN_RUN FOREIGN KEY (ROOT_RUN_ID)
        REFERENCES KBOT_AGENT_RUN (RUN_ID),
    CONSTRAINT CK_AGENT_TURN_STATUS CHECK (STATUS IN (
        'ACCEPTED', 'RUNNING', 'WAITING', 'COMPLETED',
        'FAILED', 'CANCELLED'
    )),
    CONSTRAINT CK_AGENT_TURN_SEQUENCE CHECK (TURN_SEQUENCE >= 1),
    CONSTRAINT CK_AGENT_TURN_HASH CHECK (LENGTH(RAW_INPUT_HASH) = 64)
);

CREATE INDEX IX_AGENT_TURN_CONVERSATION
    ON KBOT_AGENT_CONVERSATION_TURN
        (CONVERSATION_ID, TURN_SEQUENCE, STATUS);
CREATE INDEX IX_AGENT_TURN_STATUS
    ON KBOT_AGENT_CONVERSATION_TURN (STATUS, CREATED_AT);

CREATE TABLE KBOT_AGENT_CONVERSATION_ITEM (
    ITEM_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    ITEM_SEQUENCE NUMBER(19) NOT NULL,
    TURN_ID RAW(16) NOT NULL,
    ITEM_TYPE VARCHAR2(24 CHAR) NOT NULL,
    ROLE VARCHAR2(16 CHAR) NOT NULL,
    CONTENT_JSON JSON NOT NULL,
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    RUN_ID RAW(16),
    ARTIFACT_ID RAW(16),
    VISIBILITY VARCHAR2(16 CHAR) DEFAULT 'USER' NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_ITEM_SEQUENCE UNIQUE
        (CONVERSATION_ID, ITEM_SEQUENCE),
    CONSTRAINT UK_AGENT_ITEM_SCOPE UNIQUE (ITEM_ID, CONVERSATION_ID),
    CONSTRAINT FK_AGENT_ITEM_CONVERSATION FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_AGENT_CONVERSATION (CONVERSATION_ID),
    CONSTRAINT FK_AGENT_ITEM_TURN
        FOREIGN KEY (TURN_ID, CONVERSATION_ID)
        REFERENCES KBOT_AGENT_CONVERSATION_TURN
            (TURN_ID, CONVERSATION_ID),
    CONSTRAINT FK_AGENT_ITEM_RUN FOREIGN KEY (RUN_ID)
        REFERENCES KBOT_AGENT_RUN (RUN_ID),
    CONSTRAINT FK_AGENT_ITEM_ARTIFACT FOREIGN KEY (ARTIFACT_ID, RUN_ID)
        REFERENCES KBOT_AGENT_ARTIFACT (ARTIFACT_ID, RUN_ID),
    CONSTRAINT CK_AGENT_ITEM_TYPE CHECK
        (ITEM_TYPE IN ('MESSAGE', 'ATTACHMENT_REF', 'NOTICE')),
    CONSTRAINT CK_AGENT_ITEM_ROLE CHECK
        (ROLE IN ('USER', 'ASSISTANT', 'SYSTEM')),
    CONSTRAINT CK_AGENT_ITEM_VISIBILITY CHECK
        (VISIBILITY IN ('USER', 'INTERNAL')),
    CONSTRAINT CK_AGENT_ITEM_HASH CHECK (LENGTH(CONTENT_HASH) = 64)
);

CREATE INDEX IX_AGENT_ITEM_TURN
    ON KBOT_AGENT_CONVERSATION_ITEM (TURN_ID, ITEM_SEQUENCE);

ALTER TABLE KBOT_AGENT_CONVERSATION_TURN
    ADD CONSTRAINT FK_AGENT_TURN_USER_ITEM
    FOREIGN KEY (USER_ITEM_ID, CONVERSATION_ID)
    REFERENCES KBOT_AGENT_CONVERSATION_ITEM (ITEM_ID, CONVERSATION_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE KBOT_AGENT_CONVERSATION_TURN
    ADD CONSTRAINT FK_AGENT_TURN_ASSISTANT_ITEM
    FOREIGN KEY (ASSISTANT_ITEM_ID, CONVERSATION_ID)
    REFERENCES KBOT_AGENT_CONVERSATION_ITEM (ITEM_ID, CONVERSATION_ID)
    DEFERRABLE INITIALLY DEFERRED;
