-- KBot 4.0 会话摘要、长期记忆和可追踪来源。

CREATE TABLE KBOT_AGENT_MEMORY_SNAPSHOT (
    SNAPSHOT_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    COVERED_TURN_SEQUENCE NUMBER(19) NOT NULL,
    SUMMARY_JSON JSON NOT NULL,
    SOURCE_HASH VARCHAR2(64 CHAR) NOT NULL,
    MODEL_NAME VARCHAR2(128 CHAR),
    PROMPT_KEY VARCHAR2(256 CHAR) NOT NULL,
    PROMPT_VERSION VARCHAR2(32 CHAR) NOT NULL,
    PROMPT_SHA256 VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_SNAPSHOT_COVERAGE UNIQUE
        (CONVERSATION_ID, COVERED_TURN_SEQUENCE),
    CONSTRAINT FK_AGENT_SNAPSHOT_CONVERSATION FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_AGENT_CONVERSATION (CONVERSATION_ID),
    CONSTRAINT CK_AGENT_SNAPSHOT_STATUS CHECK
        (STATUS IN ('BUILDING', 'ACTIVE', 'SUPERSEDED', 'FAILED')),
    CONSTRAINT CK_AGENT_SNAPSHOT_SEQUENCE CHECK
        (COVERED_TURN_SEQUENCE >= 1),
    CONSTRAINT CK_AGENT_SNAPSHOT_HASH CHECK (
        LENGTH(SOURCE_HASH) = 64 AND LENGTH(PROMPT_SHA256) = 64
    )
);

CREATE UNIQUE INDEX UX_AGENT_SNAPSHOT_ACTIVE
    ON KBOT_AGENT_MEMORY_SNAPSHOT (
        CASE WHEN STATUS = 'ACTIVE' THEN CONVERSATION_ID END
    );

CREATE TABLE KBOT_AGENT_MEMORY_INDEX_PROFILE (
    INDEX_PROFILE_ID RAW(16) PRIMARY KEY,
    APP_ID NUMBER(38) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    EMBEDDING_MODEL_NAME VARCHAR2(128 CHAR) NOT NULL,
    EMBEDDING_DIMENSION NUMBER(10) NOT NULL,
    NORMALIZATION VARCHAR2(16 CHAR) NOT NULL,
    CONFIG_SHA256 VARCHAR2(64 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_MEM_PROFILE_AGENT UNIQUE
        (APP_ID, DOMAIN_ID, AGENT_ID),
    CONSTRAINT FK_AGENT_MEM_PROFILE_DEF
        FOREIGN KEY (AGENT_ID, APP_ID, DOMAIN_ID)
        REFERENCES KBOT_AGENT_DEFINITION (AGENT_ID, APP_ID, DOMAIN_ID),
    CONSTRAINT CK_AGENT_MEM_PROFILE_DIM CHECK (EMBEDDING_DIMENSION > 0),
    CONSTRAINT CK_AGENT_MEM_PROFILE_NORM CHECK
        (NORMALIZATION IN ('NONE', 'L2')),
    CONSTRAINT CK_AGENT_MEM_PROFILE_HASH CHECK
        (LENGTH(CONFIG_SHA256) = 64)
);

CREATE TABLE KBOT_AGENT_MEMORY_ITEM (
    MEMORY_ID RAW(16) PRIMARY KEY,
    APP_ID NUMBER(38) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    AGENT_ID RAW(16),
    MEMORY_TYPE VARCHAR2(24 CHAR) NOT NULL,
    SCOPE_TYPE VARCHAR2(24 CHAR) NOT NULL,
    CANONICAL_KEY VARCHAR2(256 CHAR) NOT NULL,
    VALUE_JSON JSON NOT NULL,
    SEARCH_TEXT CLOB NOT NULL,
    CONFIDENCE NUMBER(5,4) NOT NULL,
    SALIENCE NUMBER(5,4) NOT NULL,
    VALID_FROM TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    VALID_TO TIMESTAMP(6) WITH TIME ZONE,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    SENSITIVITY_LEVEL NUMBER(3) DEFAULT 0 NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    INDEX_PROFILE_ID RAW(16),
    EMBEDDING VECTOR,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_AGENT_MEMORY_DEFINITION
        FOREIGN KEY (AGENT_ID, APP_ID, DOMAIN_ID)
        REFERENCES KBOT_AGENT_DEFINITION (AGENT_ID, APP_ID, DOMAIN_ID),
    CONSTRAINT FK_AGENT_MEMORY_PROFILE
        FOREIGN KEY (INDEX_PROFILE_ID)
        REFERENCES KBOT_AGENT_MEMORY_INDEX_PROFILE (INDEX_PROFILE_ID),
    CONSTRAINT CK_AGENT_MEMORY_TYPE CHECK
        (MEMORY_TYPE IN ('USER_FACT', 'USER_PREFERENCE', 'EPISODIC')),
    CONSTRAINT CK_AGENT_MEMORY_SCOPE CHECK
        (SCOPE_TYPE IN ('USER_AGENT', 'USER_SHARED')),
    CONSTRAINT CK_AGENT_MEMORY_SCOPE_AGENT CHECK (
        (SCOPE_TYPE = 'USER_AGENT' AND AGENT_ID IS NOT NULL)
        OR (SCOPE_TYPE = 'USER_SHARED' AND AGENT_ID IS NULL)
    ),
    CONSTRAINT CK_AGENT_MEMORY_STATUS CHECK
        (STATUS IN ('ACTIVE', 'SUPERSEDED', 'DISPUTED', 'DELETED')),
    CONSTRAINT CK_AGENT_MEMORY_SCORE CHECK (
        CONFIDENCE BETWEEN 0 AND 1 AND SALIENCE BETWEEN 0 AND 1
    ),
    CONSTRAINT CK_AGENT_MEMORY_VALIDITY CHECK
        (VALID_TO IS NULL OR VALID_TO >= VALID_FROM),
    CONSTRAINT CK_AGENT_MEMORY_VERSION CHECK (ROW_VERSION >= 1),
    CONSTRAINT CK_AGENT_MEMORY_SECURITY CHECK (SENSITIVITY_LEVEL >= 0)
);

CREATE INDEX IX_AGENT_MEMORY_SCOPE
    ON KBOT_AGENT_MEMORY_ITEM (
        APP_ID, DOMAIN_ID, ACTOR_ID, AGENT_ID, STATUS, CANONICAL_KEY
    );
CREATE INDEX IX_AGENT_MEMORY_EXPIRY
    ON KBOT_AGENT_MEMORY_ITEM (STATUS, EXPIRES_AT);

CREATE UNIQUE INDEX UX_AGENT_MEMORY_ACTIVE_KEY
    ON KBOT_AGENT_MEMORY_ITEM (
        CASE WHEN STATUS = 'ACTIVE' THEN APP_ID END,
        CASE WHEN STATUS = 'ACTIVE' THEN DOMAIN_ID END,
        CASE WHEN STATUS = 'ACTIVE' THEN ACTOR_ID END,
        CASE WHEN STATUS = 'ACTIVE' THEN NVL(AGENT_ID, HEXTORAW(
            '00000000000000000000000000000000')) END,
        CASE WHEN STATUS = 'ACTIVE' THEN MEMORY_TYPE END,
        CASE WHEN STATUS = 'ACTIVE' THEN CANONICAL_KEY END
    );

CREATE TABLE KBOT_AGENT_MEMORY_SOURCE (
    MEMORY_SOURCE_ID RAW(16) PRIMARY KEY,
    MEMORY_ID RAW(16) NOT NULL,
    CONVERSATION_ID RAW(16) NOT NULL,
    TURN_ID RAW(16) NOT NULL,
    ITEM_ID RAW(16) NOT NULL,
    EXCERPT_HASH VARCHAR2(64 CHAR) NOT NULL,
    EXTRACTOR VARCHAR2(128 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_MEMORY_SOURCE UNIQUE (MEMORY_ID, ITEM_ID),
    CONSTRAINT FK_AGENT_MEMORY_SOURCE_MEMORY FOREIGN KEY (MEMORY_ID)
        REFERENCES KBOT_AGENT_MEMORY_ITEM (MEMORY_ID),
    CONSTRAINT FK_AG_MEM_SRC_CONV
        FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_AGENT_CONVERSATION (CONVERSATION_ID),
    CONSTRAINT FK_AGENT_MEMORY_SOURCE_TURN
        FOREIGN KEY (TURN_ID, CONVERSATION_ID)
        REFERENCES KBOT_AGENT_CONVERSATION_TURN
            (TURN_ID, CONVERSATION_ID),
    CONSTRAINT FK_AGENT_MEMORY_SOURCE_ITEM
        FOREIGN KEY (ITEM_ID, CONVERSATION_ID)
        REFERENCES KBOT_AGENT_CONVERSATION_ITEM
            (ITEM_ID, CONVERSATION_ID),
    CONSTRAINT CK_AGENT_MEMORY_SOURCE_HASH CHECK
        (LENGTH(EXCERPT_HASH) = 64)
);

CREATE INDEX IX_AGENT_MEMORY_SOURCE_MEMORY
    ON KBOT_AGENT_MEMORY_SOURCE (MEMORY_ID, CREATED_AT);

CREATE TABLE KBOT_AGENT_MEMORY_JOB (
    MEMORY_JOB_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    TURN_ID RAW(16) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    MAX_ATTEMPTS NUMBER(10) DEFAULT 3 NOT NULL,
    NEXT_ATTEMPT_AT TIMESTAMP(6) WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    RESULT_JSON JSON,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AGENT_MEMORY_JOB_TURN UNIQUE (TURN_ID),
    CONSTRAINT FK_AG_MEM_JOB_CONV
        FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_AGENT_CONVERSATION (CONVERSATION_ID),
    CONSTRAINT FK_AGENT_MEMORY_JOB_TURN
        FOREIGN KEY (TURN_ID, CONVERSATION_ID)
        REFERENCES KBOT_AGENT_CONVERSATION_TURN
            (TURN_ID, CONVERSATION_ID),
    CONSTRAINT CK_AGENT_MEMORY_JOB_STATUS CHECK (
        STATUS IN ('PENDING', 'PROCESSING', 'RETRY_WAIT', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT CK_AGENT_MEMORY_JOB_ATTEMPT CHECK (
        ATTEMPT_COUNT >= 0 AND MAX_ATTEMPTS BETWEEN 1 AND 20
    ),
    CONSTRAINT CK_AGENT_MEMORY_JOB_LEASE CHECK (
        (STATUS = 'PROCESSING' AND LEASE_OWNER IS NOT NULL
            AND LEASE_TOKEN IS NOT NULL AND LEASE_UNTIL IS NOT NULL)
        OR
        (STATUS <> 'PROCESSING' AND LEASE_OWNER IS NULL
            AND LEASE_TOKEN IS NULL AND LEASE_UNTIL IS NULL)
    )
);

CREATE INDEX IX_AGENT_MEMORY_JOB_CLAIM
    ON KBOT_AGENT_MEMORY_JOB (STATUS, NEXT_ATTEMPT_AT, LEASE_UNTIL);
