"""AIOps 领域状态枚举；Wire 与 Persistence 通过 Mapper 显式转换。"""

from enum import StrEnum


class DomainOpsRunStatus(StrEnum):
    CREATED = "CREATED"
    SCOPING = "SCOPING"
    OBSERVING = "OBSERVING"
    DIAGNOSING = "DIAGNOSING"
    WAITING_INPUT = "WAITING_INPUT"
    DIAGNOSED = "DIAGNOSED"
    PROPOSING = "PROPOSING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    ROLLBACK_PENDING = "ROLLBACK_PENDING"
    COMPLETED = "COMPLETED"
    DEGRADED = "DEGRADED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class DomainOpsTaskStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    BLOCKED = "BLOCKED"
    RUNNING = "RUNNING"
    WAITING_INPUT = "WAITING_INPUT"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    RETRY_WAIT = "RETRY_WAIT"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class DomainHitlStatus(StrEnum):
    PENDING = "PENDING"
    ANSWERED = "ANSWERED"
    SKIPPED = "SKIPPED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class DomainProposalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class DomainExecutionStatus(StrEnum):
    CREATED = "CREATED"
    CLAIMED = "CLAIMED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"
