"""V2 KM Asset intake contract independent of FastAPI and storage adapters."""
import hashlib
import json
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class IntakeValidationError(ValueError):
    """A stable, client-correctable intake contract violation."""


class BundleDeclaration(BaseModel):
    model_config = ConfigDict(extra="forbid")

    source_id: str = Field(min_length=1, max_length=256)
    source_revision: str = Field(min_length=1, max_length=256)
    title: str = Field(min_length=1, max_length=512)
    canonical_url: str | None = Field(default=None, max_length=2048)
    security_level: int = Field(ge=0, le=999)
    facet: dict[str, Any] = Field(default_factory=dict)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("source_id", "source_revision", "title")
    @classmethod
    def strip_required(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("value must not be blank")
        return value


class DocumentDeclaration(BaseModel):
    model_config = ConfigDict(extra="forbid")

    part_name: str = Field(min_length=1, max_length=128)
    external_document_id: str = Field(min_length=1, max_length=256)
    role: str = "ATTACHMENT"
    source_url: str | None = Field(default=None, max_length=2048)
    declared_name: str | None = Field(default=None, max_length=512)
    declared_mime_type: str = Field(min_length=1, max_length=255)
    ordinal: int = Field(ge=0)
    required_flag: bool = False
    byte_size: int = Field(ge=0)
    content_sha256: str = Field(pattern=r"^[a-fA-F0-9]{64}$")


class DocumentFailureDeclaration(BaseModel):
    model_config = ConfigDict(extra="forbid")

    external_document_id: str = Field(min_length=1, max_length=256)
    source_url: str | None = Field(default=None, max_length=2048)
    declared_name: str | None = Field(default=None, max_length=512)
    ordinal: int = Field(ge=0)
    failure_code: str = Field(min_length=1, max_length=128)
    failure_message: str | None = Field(default=None, max_length=1000)


class KmAssetIntakeManifest(BaseModel):
    """Validated V2 request metadata; file bytes remain outside this object."""
    bundle: BundleDeclaration
    documents: list[DocumentDeclaration] = Field(default_factory=list)
    document_failures: list[DocumentFailureDeclaration] = Field(default_factory=list)

    def validate_declarations(self, file_part_names: set[str], *, allowed_roles: set[str] | None = None) -> None:
        document_ids = [document.external_document_id for document in self.documents]
        failure_ids = [failure.external_document_id for failure in self.document_failures]
        part_names = [document.part_name for document in self.documents]

        if "__manifest__" in document_ids or "__manifest__" in failure_ids:
            raise IntakeValidationError("__manifest__ is generated by Knowledge Core")
        if len(document_ids) != len(set(document_ids)):
            raise IntakeValidationError("external_document_id is duplicated in documents")
        if len(failure_ids) != len(set(failure_ids)):
            raise IntakeValidationError("external_document_id is duplicated in document_failures")
        if set(document_ids).intersection(failure_ids):
            raise IntakeValidationError("a document cannot be both uploaded and failed")
        if len(part_names) != len(set(part_names)):
            raise IntakeValidationError("part_name is duplicated")
        allowed_roles = allowed_roles or {"ATTACHMENT"}
        if any(document.role not in allowed_roles for document in self.documents):
            raise IntakeValidationError(f"documents may only declare roles: {sorted(allowed_roles)}")
        if set(part_names) != file_part_names:
            raise IntakeValidationError("uploaded file parts do not match document declarations")

    def fingerprint(self) -> str:
        """Hash semantic request shape, excluding multipart boundary and byte stream."""
        raw = self.model_dump(mode="json")
        canonical = json.dumps(raw, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()
