[development]
app.name = "KBOT_DEV"
app.description = "The KBOT backend application provides API services for KBOT and is currently in the development environment."
app.version = "0.3.0"
app.debug = true

# database connection pool configuration
database.echo = true
database.pool_size = 5
database.max_overflow = 10
database.pool_pre_ping = false
database.pool_recycle = 3600

# logging configuration
logging.level = "DEBUG"
logging.path = "backend/logs/app.log"
logging.rotation = "100 MB"
logging.retention = "10 days"