[production]
app.name = "KBOT3_PROD"
app.description = "The KBOT backend application provides API services for KBOT and is currently in the production environment."
app.version = "3.0.0"
app.debug = false

# database connection pool configuration
database.echo = false
database.pool_size = 20
database.max_overflow = 40
database.pool_pre_ping = false
database.pool_recycle = 3600

# logging configuration
logging.level = "INFO"
logging.path = "backend/logs/app.log"
logging.rotation = "100 MB"
logging.retention = "10 days"