[default]
## this is for download url prefix
http_prefix = 'http://150.230.37.250:8093/'
DOC_VIEWER_FLAG='N' ##Y|N,If config `Y`, it will use the http_doc_viewer to view the document, otherwise it will http_prefix to download the file.
http_doc_viewer = "http://150.230.37.250/HysunDocuViewer/?src=http://150.230.37.250:8080/"

GenAIEndpoint = "https://inference.generativeai.us-chicago-1.oci.oraclecloud.com"
compartment_id = "ocid1.compartment.oc1..aaaaaaaapw7vdtp4sakhe7zs7tybhtapgc26ga472v62ykdboxxbuo2cad6q"


VECTOR_STORE_DICT = [
    'faiss',
    'oracle',
    'adb',
    'opensearch',
    'heatwave'
]

#######  Vector Store setting    #######################################
score_threshold =  0.6
vector_store_limit= 10

auth_type= "INSTANCE_PRINCIPAL"
KB_ROOT_PATH="/home/ubuntu/knnn"


#######  Embedding model setting    #######################################
CHUNK_SIZE = 500
CHUNK_OVERLAP = 50

BGE_RERANKER="BAAI/bge-reranker-v2-m3"
# disableReranker, ociCohereReranker,cohereReranker
rerankerModel = 'ociCohereReranker'
reranker_topk= 2

#######  the memory window for chat history   #####################
history_k = 5


SUMMARY_MODEL ="OCI-cohere.command-r-plus082024"

######## Select AI ########
selectai_pool = ""
