[default]
app.name = "KBot_dev"
app.description = "KBot API Service"
app.version = "3.0.0"
app.debug = true

# database connection pool configuration
database.echo = true
database.pool_size = 5
database.max_overflow = 10
database.pool_pre_ping = false
database.pool_recycle = 3600

# logging configuration
logging.level = "DEBUG"
logging.path = "backend/logs/app.log"
logging.rotation = "100 MB"
logging.retention = "10 days"

# chunk configuration
chunk.size = 1000
chunk.overlap = 100

# knowledge base configuration
kbot.file_root_path = "/home/chris/kbot/knowledge_base"
kbot.parallel_workers = 10