-- 知识检索应用 Agent 与不可变版本。

CREATE TABLE KBOT_KR_AGENT (
    AGENT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    CURRENT_VERSION_ID RAW(16),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_KR_AGENT_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_KR_AGENT_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT CK_KR_AGENT_STATUS
        CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED')),
    CONSTRAINT CK_KR_AGENT_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_KR_AGENT_SCOPE_STATUS ON KBOT_KR_AGENT (DOMAIN_ID, STATUS);

CREATE TABLE KBOT_KR_AGENT_VERSION (
    AGENT_VERSION_ID RAW(16) PRIMARY KEY,
    AGENT_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    ENABLED_CAPABILITIES_JSON JSON NOT NULL,
    MODELS_JSON JSON NOT NULL,
    INSTRUCTION CLOB,
    CONFIG_JSON JSON NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_KR_AGENT_VERSION_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES KBOT_KR_AGENT (AGENT_ID) ON DELETE CASCADE,
    CONSTRAINT UK_KR_AGENT_VERSION UNIQUE (AGENT_ID, VERSION_NO)
);

CREATE INDEX IX_KR_AGENT_VERSION_AGENT ON KBOT_KR_AGENT_VERSION (AGENT_ID);

ALTER TABLE KBOT_KR_AGENT ADD CONSTRAINT FK_KR_AGENT_CURRENT_VERSION
    FOREIGN KEY (CURRENT_VERSION_ID) REFERENCES KBOT_KR_AGENT_VERSION (AGENT_VERSION_ID);
