-- X Search 只作为外部知识来源，不自动写入 Knowledge Core。

CREATE TABLE KBOT_KR_RESEARCH_RUN (
    RUN_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    KIND VARCHAR2(32 CHAR) NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'ACCEPTED' NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    REQUEST_ID VARCHAR2(128 CHAR) NOT NULL,
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    MODEL_ID RAW(16) NOT NULL,
    MODEL_SNAPSHOT_JSON JSON NOT NULL,
    REQUEST_JSON JSON NOT NULL,
    RESULT_JSON JSON,
    USAGE_JSON JSON,
    PROVIDER_REQUEST_ID VARCHAR2(256 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KR_RESEARCH_IDEMP UNIQUE (DOMAIN_ID, ACTOR_ID, IDEMPOTENCY_KEY),
    CONSTRAINT UK_KR_RESEARCH_SCOPE UNIQUE (RUN_ID, DOMAIN_ID),
    CONSTRAINT FK_KR_RESEARCH_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_KR_RESEARCH_KIND CHECK (KIND = 'X_SEARCH'),
    CONSTRAINT CK_KR_RESEARCH_STATUS CHECK (STATUS IN ('ACCEPTED', 'SEARCHING', 'ORGANIZING_SOURCES', 'COMPOSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT CK_KR_RESEARCH_VERSION CHECK (ROW_VERSION > 0)
);
CREATE INDEX IX_KR_RESEARCH_DOMAIN_TIME ON KBOT_KR_RESEARCH_RUN (DOMAIN_ID, CREATED_AT);
CREATE INDEX IX_KR_RESEARCH_CLAIM ON KBOT_KR_RESEARCH_RUN (STATUS, LEASE_UNTIL);

CREATE TABLE KBOT_KR_RESEARCH_EVENT (
    EVENT_ID RAW(16) PRIMARY KEY,
    RUN_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    SEQUENCE_NO NUMBER(10) NOT NULL,
    STAGE VARCHAR2(32 CHAR) NOT NULL,
    MESSAGE VARCHAR2(1000 CHAR),
    PAYLOAD_JSON JSON,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KR_RESEARCH_EVENT_SEQ UNIQUE (RUN_ID, SEQUENCE_NO),
    CONSTRAINT FK_KR_RESEARCH_EVENT_RUN FOREIGN KEY (RUN_ID, DOMAIN_ID) REFERENCES KBOT_KR_RESEARCH_RUN (RUN_ID, DOMAIN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_KR_RESEARCH_EVENT_STAGE CHECK (STAGE IN ('ACCEPTED', 'SEARCHING', 'ORGANIZING_SOURCES', 'COMPOSING', 'COMPLETED', 'FAILED'))
);

CREATE TABLE KBOT_KR_X_SOURCE (
    SOURCE_ID RAW(16) PRIMARY KEY,
    RUN_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_ORDER NUMBER(10) NOT NULL,
    CITATION_LABEL VARCHAR2(16 CHAR) NOT NULL,
    PROVIDER_CITATION_ID VARCHAR2(256 CHAR) NOT NULL,
    CANONICAL_URL VARCHAR2(2048 CHAR) NOT NULL,
    TITLE VARCHAR2(512 CHAR),
    EXCERPT VARCHAR2(4000 CHAR),
    AUTHOR_HANDLE VARCHAR2(128 CHAR),
    PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE,
    RETRIEVED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KR_X_SOURCE_LABEL UNIQUE (RUN_ID, CITATION_LABEL),
    CONSTRAINT FK_KR_X_SOURCE_RUN FOREIGN KEY (RUN_ID, DOMAIN_ID) REFERENCES KBOT_KR_RESEARCH_RUN (RUN_ID, DOMAIN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_KR_X_SOURCE_ORDER CHECK (DISPLAY_ORDER > 0)
);
CREATE INDEX IX_KR_X_SOURCE_RUN ON KBOT_KR_X_SOURCE (RUN_ID, DISPLAY_ORDER);
