-- Assistant App 问数 Demo：外部 Oracle CRM 基础表和问数视图。
--
-- 本脚本只创建 Demo 数据对象，不创建用户、权限或 KBot 内部对象。
-- 请使用外部 Oracle 的只读/写入初始化账号执行；接入 Data Query 时只授予
-- 查询这些表和视图的权限。客户沟通正文不放在这里，后续作为文档上传 KC。

CREATE TABLE DEMO_CRM_CUSTOMER (
    CUSTOMER_ID RAW(16) PRIMARY KEY,
    CUSTOMER_CODE VARCHAR2(64 CHAR) NOT NULL,
    CUSTOMER_NAME VARCHAR2(256 CHAR) NOT NULL,
    INDUSTRY VARCHAR2(128 CHAR) NOT NULL,
    REGION VARCHAR2(64 CHAR) NOT NULL,
    CUSTOMER_LEVEL VARCHAR2(32 CHAR) NOT NULL,
    OWNER_NAME VARCHAR2(128 CHAR) NOT NULL,
    LIFECYCLE_STATUS VARCHAR2(32 CHAR) NOT NULL,
    ANNUAL_REVENUE NUMBER(18,2),
    CONTRACT_VALUE NUMBER(18,2),
    FIRST_CONTACT_DATE DATE,
    LAST_CONTACT_DATE DATE,
    NEXT_FOLLOW_UP_DATE DATE,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_DEMO_CRM_CUSTOMER_CODE UNIQUE (CUSTOMER_CODE),
    CONSTRAINT CK_DEMO_CRM_CUSTOMER_LEVEL CHECK (CUSTOMER_LEVEL IN ('STANDARD', 'IMPORTANT', 'KEY')),
    CONSTRAINT CK_DEMO_CRM_CUSTOMER_STATUS CHECK (LIFECYCLE_STATUS IN ('PROSPECT', 'QUALIFIED', 'ACTIVE', 'AT_RISK', 'CHURNED'))
);

CREATE TABLE DEMO_CRM_CONTACT (
    CONTACT_ID RAW(16) PRIMARY KEY,
    CUSTOMER_ID RAW(16) NOT NULL,
    CONTACT_NAME VARCHAR2(128 CHAR) NOT NULL,
    JOB_TITLE VARCHAR2(128 CHAR),
    EMAIL VARCHAR2(256 CHAR),
    PHONE VARCHAR2(64 CHAR),
    IS_PRIMARY NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_DEMO_CRM_CONTACT_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DEMO_CRM_CUSTOMER (CUSTOMER_ID),
    CONSTRAINT CK_DEMO_CRM_CONTACT_PRIMARY CHECK (IS_PRIMARY IN (0, 1))
);

CREATE TABLE DEMO_CRM_OPPORTUNITY (
    OPPORTUNITY_ID RAW(16) PRIMARY KEY,
    CUSTOMER_ID RAW(16) NOT NULL,
    OPPORTUNITY_NAME VARCHAR2(256 CHAR) NOT NULL,
    STAGE VARCHAR2(32 CHAR) NOT NULL,
    OPPORTUNITY_STATUS VARCHAR2(32 CHAR) NOT NULL,
    AMOUNT NUMBER(18,2) NOT NULL,
    WIN_PROBABILITY NUMBER(5,2),
    EXPECTED_CLOSE_DATE DATE,
    OWNER_NAME VARCHAR2(128 CHAR) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    UPDATED_DATE DATE NOT NULL,
    CONSTRAINT FK_DEMO_CRM_OPPORTUNITY_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DEMO_CRM_CUSTOMER (CUSTOMER_ID),
    CONSTRAINT CK_DEMO_CRM_OPPORTUNITY_STAGE CHECK (STAGE IN ('LEAD', 'QUALIFICATION', 'PROPOSAL', 'NEGOTIATION', 'CLOSED_WON', 'CLOSED_LOST')),
    CONSTRAINT CK_DEMO_CRM_OPPORTUNITY_STATUS CHECK (OPPORTUNITY_STATUS IN ('OPEN', 'WON', 'LOST', 'PAUSED')),
    CONSTRAINT CK_DEMO_CRM_OPPORTUNITY_AMOUNT CHECK (AMOUNT >= 0),
    CONSTRAINT CK_DEMO_CRM_OPPORTUNITY_PROBABILITY CHECK (WIN_PROBABILITY IS NULL OR (WIN_PROBABILITY >= 0 AND WIN_PROBABILITY <= 100))
);

CREATE TABLE DEMO_CRM_ACTIVITY (
    ACTIVITY_ID RAW(16) PRIMARY KEY,
    CUSTOMER_ID RAW(16) NOT NULL,
    CONTACT_ID RAW(16),
    ACTIVITY_TYPE VARCHAR2(32 CHAR) NOT NULL,
    ACTIVITY_DATE DATE NOT NULL,
    SUBJECT VARCHAR2(256 CHAR) NOT NULL,
    OUTCOME_CODE VARCHAR2(32 CHAR) NOT NULL,
    NEXT_ACTION_DATE DATE,
    OWNER_NAME VARCHAR2(128 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_DEMO_CRM_ACTIVITY_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DEMO_CRM_CUSTOMER (CUSTOMER_ID),
    CONSTRAINT FK_DEMO_CRM_ACTIVITY_CONTACT FOREIGN KEY (CONTACT_ID)
        REFERENCES DEMO_CRM_CONTACT (CONTACT_ID),
    CONSTRAINT CK_DEMO_CRM_ACTIVITY_TYPE CHECK (ACTIVITY_TYPE IN ('CALL', 'EMAIL', 'MEETING', 'VISIT', 'DEMO')),
    CONSTRAINT CK_DEMO_CRM_ACTIVITY_OUTCOME CHECK (OUTCOME_CODE IN ('POSITIVE', 'NEUTRAL', 'FOLLOW_UP', 'RISK', 'NO_RESPONSE'))
);

CREATE INDEX IX_DEMO_CRM_CONTACT_CUSTOMER ON DEMO_CRM_CONTACT (CUSTOMER_ID);
CREATE INDEX IX_DEMO_CRM_OPPORTUNITY_CUSTOMER ON DEMO_CRM_OPPORTUNITY (CUSTOMER_ID);
CREATE INDEX IX_DEMO_CRM_OPPORTUNITY_STAGE ON DEMO_CRM_OPPORTUNITY (STAGE, EXPECTED_CLOSE_DATE);
CREATE INDEX IX_DEMO_CRM_ACTIVITY_CUSTOMER_DATE ON DEMO_CRM_ACTIVITY (CUSTOMER_ID, ACTIVITY_DATE DESC);
CREATE INDEX IX_DEMO_CRM_ACTIVITY_OUTCOME ON DEMO_CRM_ACTIVITY (OUTCOME_CODE, ACTIVITY_DATE DESC);

-- 客户经营总览：一行一个客户，适合客户数量、客户分布、机会金额和跟进情况查询。
CREATE OR REPLACE VIEW DEMO_CRM_CUSTOMER_OVERVIEW AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_CODE,
    c.CUSTOMER_NAME,
    c.INDUSTRY,
    c.REGION,
    c.CUSTOMER_LEVEL,
    c.OWNER_NAME,
    c.LIFECYCLE_STATUS,
    c.ANNUAL_REVENUE,
    c.CONTRACT_VALUE,
    c.FIRST_CONTACT_DATE,
    c.LAST_CONTACT_DATE,
    c.NEXT_FOLLOW_UP_DATE,
    NVL(o.OPPORTUNITY_COUNT, 0) AS OPPORTUNITY_COUNT,
    NVL(o.OPEN_PIPELINE_AMOUNT, 0) AS OPEN_PIPELINE_AMOUNT,
    NVL(o.WON_AMOUNT, 0) AS WON_AMOUNT,
    NVL(a.ACTIVITY_COUNT, 0) AS ACTIVITY_COUNT,
    a.LAST_ACTIVITY_DATE,
    NVL(a.RISK_ACTIVITY_COUNT, 0) AS RISK_ACTIVITY_COUNT
FROM DEMO_CRM_CUSTOMER c
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS OPPORTUNITY_COUNT,
        SUM(CASE WHEN OPPORTUNITY_STATUS IN ('OPEN', 'PAUSED') THEN AMOUNT ELSE 0 END) AS OPEN_PIPELINE_AMOUNT,
        SUM(CASE WHEN OPPORTUNITY_STATUS = 'WON' THEN AMOUNT ELSE 0 END) AS WON_AMOUNT
    FROM DEMO_CRM_OPPORTUNITY
    GROUP BY CUSTOMER_ID
) o ON o.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS ACTIVITY_COUNT,
        MAX(ACTIVITY_DATE) AS LAST_ACTIVITY_DATE,
        SUM(CASE WHEN OUTCOME_CODE = 'RISK' THEN 1 ELSE 0 END) AS RISK_ACTIVITY_COUNT
    FROM DEMO_CRM_ACTIVITY
    GROUP BY CUSTOMER_ID
) a ON a.CUSTOMER_ID = c.CUSTOMER_ID;

-- 销售机会明细：一行一个机会，适合阶段、区域、负责人和金额分析。
CREATE OR REPLACE VIEW DEMO_CRM_PIPELINE AS
SELECT
    o.OPPORTUNITY_ID,
    o.CUSTOMER_ID,
    c.CUSTOMER_CODE,
    c.CUSTOMER_NAME,
    c.INDUSTRY,
    c.REGION,
    c.CUSTOMER_LEVEL,
    c.LIFECYCLE_STATUS,
    o.OPPORTUNITY_NAME,
    o.STAGE,
    o.OPPORTUNITY_STATUS,
    o.AMOUNT,
    o.WIN_PROBABILITY,
    o.EXPECTED_CLOSE_DATE,
    o.OWNER_NAME,
    o.CREATED_DATE,
    o.UPDATED_DATE
FROM DEMO_CRM_OPPORTUNITY o
JOIN DEMO_CRM_CUSTOMER c ON c.CUSTOMER_ID = o.CUSTOMER_ID;

-- 沟通活动明细：只保留可统计的活动事实，沟通正文由 KC 文档承载。
CREATE OR REPLACE VIEW DEMO_CRM_ACTIVITY_LOG AS
SELECT
    a.ACTIVITY_ID,
    a.CUSTOMER_ID,
    c.CUSTOMER_CODE,
    c.CUSTOMER_NAME,
    c.INDUSTRY,
    c.REGION,
    c.CUSTOMER_LEVEL,
    c.LIFECYCLE_STATUS,
    a.CONTACT_ID,
    a.ACTIVITY_TYPE,
    a.ACTIVITY_DATE,
    a.SUBJECT,
    a.OUTCOME_CODE,
    a.NEXT_ACTION_DATE,
    a.OWNER_NAME
FROM DEMO_CRM_ACTIVITY a
JOIN DEMO_CRM_CUSTOMER c ON c.CUSTOMER_ID = a.CUSTOMER_ID;

COMMENT ON TABLE DEMO_CRM_CUSTOMER IS 'Assistant App 问数 Demo 客户主数据';
COMMENT ON TABLE DEMO_CRM_CONTACT IS 'Assistant App 问数 Demo 客户联系人';
COMMENT ON TABLE DEMO_CRM_OPPORTUNITY IS 'Assistant App 问数 Demo 销售机会';
COMMENT ON TABLE DEMO_CRM_ACTIVITY IS 'Assistant App 问数 Demo 沟通活动摘要，不保存沟通正文';
COMMENT ON TABLE DEMO_CRM_CUSTOMER_OVERVIEW IS '面向问数语义模型的客户经营总览';
COMMENT ON TABLE DEMO_CRM_PIPELINE IS '面向问数语义模型的销售机会明细';
COMMENT ON TABLE DEMO_CRM_ACTIVITY_LOG IS '面向问数语义模型的沟通活动明细';
