-- KC retrieval index columns.  Parser never writes these fields; INDEX does.
-- The VECTOR dimension is supplied by the deployment's base.toml dimension.
ALTER TABLE KBOT_KC_EVIDENCE ADD (
    EMBEDDING VECTOR,
    EMBEDDING_MODEL_ID NUMBER(38),
    EMBEDDING_MODEL_KEY VARCHAR2(256 CHAR),
    EMBEDDING_CONFIG_FINGERPRINT VARCHAR2(64 CHAR),
    EMBEDDING_INPUT_HASH VARCHAR2(64 CHAR),
    INDEXED_AT TIMESTAMP(6) WITH TIME ZONE
);

CREATE INDEX IX_KC_EVIDENCE_EMBED_MODEL
    ON KBOT_KC_EVIDENCE (COLLECTION_ID, EMBEDDING_MODEL_ID, STATUS);

COMMENT ON COLUMN KBOT_KC_EVIDENCE.EMBEDDING_MODEL_ID IS
    'Collection-bound text embedding model used by INDEX';
COMMENT ON COLUMN KBOT_KC_EVIDENCE.EMBEDDING_INPUT_HASH IS
    'SHA-256 of retrieval_text; changes force re-indexing';
