services:
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos
    restart: unless-stopped
    ports:
      - "8848:8848"
    environment:
      - MODE=standalone
    volumes:
      - ~/nacos/data:/home/nacos/data
      - ~/nacos/logs:/home/nacos/logs