-- 多媒体创作工作台图片生成运行时；后续图生图继续复用媒体 Run 和资产模型。

CREATE TABLE KBOT_MEDIA_MODEL_BINDING (
    BINDING_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    ROLE VARCHAR2(32 CHAR) NOT NULL,
    MODEL_ID RAW(16) NOT NULL,
    MODEL_SNAPSHOT_JSON JSON NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MEDIA_BINDING_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_MEDIA_BINDING_ROLE UNIQUE (DOMAIN_ID, ROLE),
    CONSTRAINT CK_MEDIA_BINDING_ROLE CHECK (ROLE = 'IMAGE_GENERATION'),
    CONSTRAINT CK_MEDIA_BINDING_VERSION CHECK (ROW_VERSION > 0)
);
CREATE INDEX IX_MEDIA_BINDING_MODEL ON KBOT_MEDIA_MODEL_BINDING (MODEL_ID);

CREATE TABLE KBOT_MEDIA_RUN (
    RUN_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    KIND VARCHAR2(32 CHAR) NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'ACCEPTED' NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    REQUEST_ID VARCHAR2(128 CHAR) NOT NULL,
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    MODEL_ID RAW(16) NOT NULL,
    MODEL_SNAPSHOT_JSON JSON NOT NULL,
    REQUEST_JSON JSON NOT NULL,
    RESULT_JSON JSON,
    USAGE_JSON JSON,
    PROVIDER_REQUEST_ID VARCHAR2(256 CHAR),
    PROMPT_REVISION_ID RAW(16),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_MEDIA_RUN_IDEMP UNIQUE (DOMAIN_ID, ACTOR_ID, IDEMPOTENCY_KEY),
    CONSTRAINT UK_MEDIA_RUN_SCOPE UNIQUE (RUN_ID, DOMAIN_ID),
    CONSTRAINT FK_MEDIA_RUN_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_MEDIA_RUN_KIND CHECK (KIND IN ('IMAGE_GENERATION', 'IMAGE_EDIT')),
    CONSTRAINT CK_MEDIA_RUN_STATUS CHECK (STATUS IN ('ACCEPTED', 'GENERATING', 'COMPLETED', 'REJECTED', 'FAILED')),
    CONSTRAINT CK_MEDIA_RUN_VERSION CHECK (ROW_VERSION > 0)
);
CREATE INDEX IX_MEDIA_RUN_DOMAIN_TIME ON KBOT_MEDIA_RUN (DOMAIN_ID, CREATED_AT);
CREATE INDEX IX_MEDIA_RUN_CLAIM ON KBOT_MEDIA_RUN (STATUS, LEASE_UNTIL);

CREATE TABLE KBOT_MEDIA_RUN_EVENT (
    EVENT_ID RAW(16) PRIMARY KEY,
    RUN_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    SEQUENCE_NO NUMBER(10) NOT NULL,
    STAGE VARCHAR2(32 CHAR) NOT NULL,
    MESSAGE VARCHAR2(1000 CHAR),
    PAYLOAD_JSON JSON,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_MEDIA_EVENT_SEQ UNIQUE (RUN_ID, SEQUENCE_NO),
    CONSTRAINT FK_MEDIA_EVENT_RUN FOREIGN KEY (RUN_ID, DOMAIN_ID) REFERENCES KBOT_MEDIA_RUN (RUN_ID, DOMAIN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MEDIA_EVENT_STAGE CHECK (STAGE IN ('ACCEPTED', 'GENERATING', 'COMPLETED', 'REJECTED', 'FAILED'))
);

CREATE TABLE KBOT_MEDIA_PROMPT_REVISION (
    PROMPT_REVISION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    RUN_ID RAW(16),
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    PROMPT CLOB NOT NULL,
    ASPECT_RATIO VARCHAR2(16 CHAR) NOT NULL,
    IMAGE_COUNT NUMBER(2) DEFAULT 1 NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MEDIA_PROMPT_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_MEDIA_PROMPT_RUN FOREIGN KEY (RUN_ID) REFERENCES KBOT_MEDIA_RUN (RUN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MEDIA_PROMPT_COUNT CHECK (IMAGE_COUNT BETWEEN 1 AND 4),
    CONSTRAINT CK_MEDIA_PROMPT_VERSION CHECK (VERSION_NO > 0)
);
CREATE INDEX IX_MEDIA_PROMPT_RUN ON KBOT_MEDIA_PROMPT_REVISION (RUN_ID);

CREATE TABLE KBOT_MEDIA_ASSET (
    ASSET_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    RUN_ID RAW(16) NOT NULL,
    PROMPT_REVISION_ID RAW(16),
    OBJECT_KEY VARCHAR2(1024 CHAR) NOT NULL,
    MIME_TYPE VARCHAR2(64 CHAR) NOT NULL,
    BYTE_SIZE NUMBER(19) NOT NULL,
    CONTENT_SHA256 VARCHAR2(64 CHAR) NOT NULL,
    WIDTH NUMBER(10),
    HEIGHT NUMBER(10),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'READY' NOT NULL,
    PROVIDER_ARTIFACT_ID VARCHAR2(256 CHAR),
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MEDIA_ASSET_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_MEDIA_ASSET_RUN FOREIGN KEY (RUN_ID, DOMAIN_ID) REFERENCES KBOT_MEDIA_RUN (RUN_ID, DOMAIN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MEDIA_ASSET_STATUS CHECK (STATUS IN ('READY', 'REJECTED', 'FAILED')),
    CONSTRAINT CK_MEDIA_ASSET_SIZE CHECK (BYTE_SIZE > 0)
);
CREATE INDEX IX_MEDIA_ASSET_DOMAIN ON KBOT_MEDIA_ASSET (DOMAIN_ID, CREATED_AT);
CREATE INDEX IX_MEDIA_ASSET_RUN ON KBOT_MEDIA_ASSET (RUN_ID);
