-- KBot 4.0 Model Serving：模型目录。
-- UUIDv7 由应用生成并以 RAW(16) 保存；本脚本不读取或转换任何 3.x 数据。

CREATE TABLE KBOT_AI_MODEL (
    MODEL_ID RAW(16) PRIMARY KEY,
    APP_ID NUMBER(38) NOT NULL,
    SERVED_MODEL_NAME VARCHAR2(128 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    PROVIDER_MODEL_NAME VARCHAR2(256 CHAR) NOT NULL,
    CATEGORY NUMBER(2) NOT NULL,
    PROVIDER VARCHAR2(64 CHAR) NOT NULL,
    API_ENDPOINT VARCHAR2(1024 CHAR),
    API_KEY CLOB,
    STATUS NUMBER(1) DEFAULT 0 NOT NULL,
    EMBEDDING_DIMENSION NUMBER(10),
    MODEL_PARAMS CLOB,
    DESCS VARCHAR2(512 CHAR),
    CREATED_BY VARCHAR2(256 CHAR),
    UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_AI_MODEL_SERVED_NAME UNIQUE (SERVED_MODEL_NAME),
    CONSTRAINT CK_AI_MODEL_SERVED_NAME CHECK (
        REGEXP_LIKE(SERVED_MODEL_NAME, '^[a-z0-9][a-z0-9._-]{0,127}$')
    ),
    CONSTRAINT CK_AI_MODEL_STATUS CHECK (STATUS IN (0, 1, 2)),
    CONSTRAINT CK_AI_MODEL_CATEGORY CHECK (CATEGORY IN (1, 2, 3, 4, 5)),
    CONSTRAINT CK_AI_MODEL_EMBED_DIM CHECK (
        (CATEGORY = 2 AND EMBEDDING_DIMENSION IS NOT NULL AND EMBEDDING_DIMENSION > 0)
        OR (CATEGORY <> 2 AND EMBEDDING_DIMENSION IS NULL)
    ),
    CONSTRAINT CK_AI_MODEL_PARAMS_JSON CHECK (MODEL_PARAMS IS JSON)
);

CREATE INDEX IX_AI_MODEL_APP_CATEGORY_STATUS
    ON KBOT_AI_MODEL (APP_ID, CATEGORY, STATUS);

COMMENT ON COLUMN KBOT_AI_MODEL.MODEL_ID IS
    '应用生成的 UUIDv7；仅用于内部管理和跨服务持久化引用';
COMMENT ON COLUMN KBOT_AI_MODEL.SERVED_MODEL_NAME IS
    '推理 API 的 model 参数以及模型池缓存键';
COMMENT ON COLUMN KBOT_AI_MODEL.PROVIDER_MODEL_NAME IS
    '发送给上游模型厂商或本地引擎的真实模型名称';
COMMENT ON COLUMN KBOT_AI_MODEL.API_KEY IS
    '过渡期上游凭据；后续迁移为 Secret Store 引用';
