"""AIOps 跨服务 Wire 契约。"""

from .errors import AIOpsErrorCode, ProblemDetails
from .events import AIOpsEvent, SafeAIOpsEvent, UnknownEvent
from .executor import (
    ExecutionResultRef,
    ExecutionStatusEvent,
    MutationClaimGrant,
    MutationExecutionRequest,
    ReadDiagnosticRequest,
    ReadDiagnosticResult,
)
from .internal import (
    CreateOpsRunCommand,
    DelegationEventPage,
    EventReceipt,
    OpsCommand,
    RootDelegationRequest,
    RootDelegationResult,
)
from .public import (
    AgentBindingCreate,
    AgentBindingPatch,
    AgentBindingView,
    ApprovalCommand,
    HitlResponse,
    InspectionPlanCreate,
    InspectionPlanPatch,
    InspectionPlanView,
    ManualResultCommand,
    MonitorBindingCreate,
    MonitorBindingPatch,
    MonitorBindingView,
    MonitorSourceCreate,
    MonitorSourcePatch,
    MonitorSourceView,
    OpsRunCreate,
    OpsRunReceipt,
    OpsRunSummary,
    PendingInputView,
    ProposalView,
    RejectionCommand,
    ReportSummary,
    ReportView,
    TargetCreate,
    TargetPage,
    TargetPatch,
    TargetView,
    UploadSession,
)

__all__ = [
    "AIOpsErrorCode",
    "AIOpsEvent",
    "SafeAIOpsEvent",
    "AgentBindingCreate",
    "AgentBindingPatch",
    "AgentBindingView",
    "ApprovalCommand",
    "CreateOpsRunCommand",
    "DelegationEventPage",
    "EventReceipt",
    "ExecutionResultRef",
    "ExecutionStatusEvent",
    "HitlResponse",
    "InspectionPlanCreate",
    "InspectionPlanPatch",
    "InspectionPlanView",
    "ManualResultCommand",
    "MonitorBindingCreate",
    "MonitorBindingPatch",
    "MonitorBindingView",
    "MonitorSourceCreate",
    "MonitorSourcePatch",
    "MonitorSourceView",
    "MutationClaimGrant",
    "MutationExecutionRequest",
    "OpsCommand",
    "OpsRunCreate",
    "OpsRunReceipt",
    "OpsRunSummary",
    "PendingInputView",
    "ProblemDetails",
    "ProposalView",
    "ReadDiagnosticRequest",
    "ReadDiagnosticResult",
    "RejectionCommand",
    "ReportSummary",
    "ReportView",
    "RootDelegationRequest",
    "RootDelegationResult",
    "TargetCreate",
    "TargetPage",
    "TargetPatch",
    "TargetView",
    "UploadSession",
    "UnknownEvent",
]
