CREATE TABLE KBOT_PLATFORM_APP (
    APP_ID VARCHAR2(64 CHAR) PRIMARY KEY,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    MEMBER_ASSIGNABLE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_PLATFORM_APP_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_PLATFORM_APP_MEMBER CHECK (MEMBER_ASSIGNABLE IN ('Y', 'N'))
);

CREATE TABLE KBOT_PLATFORM_USER (
    USER_ID VARCHAR2(256 CHAR) PRIMARY KEY,
    DISPLAY_NAME VARCHAR2(256 CHAR),
    ACCOUNT_ORIGIN VARCHAR2(16 CHAR) DEFAULT 'PLATFORM' NOT NULL,
    OWNER_APP_ID VARCHAR2(64 CHAR),
    IS_PROTECTED CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    MAX_SECURITY_LEVEL NUMBER(3) DEFAULT 1 NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PLATFORM_USER_OWNER_APP FOREIGN KEY (OWNER_APP_ID)
        REFERENCES KBOT_PLATFORM_APP (APP_ID),
    CONSTRAINT CK_PLATFORM_USER_ORIGIN CHECK (ACCOUNT_ORIGIN IN ('PLATFORM', 'APP')),
    CONSTRAINT CK_PLATFORM_USER_OWNER CHECK (
        (ACCOUNT_ORIGIN = 'PLATFORM' AND OWNER_APP_ID IS NULL)
        OR (ACCOUNT_ORIGIN = 'APP' AND OWNER_APP_ID IS NOT NULL)
    ),
    CONSTRAINT CK_PLATFORM_USER_PROTECTED CHECK (IS_PROTECTED IN ('Y', 'N')),
    CONSTRAINT CK_PLATFORM_USER_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_PLATFORM_USER_SECURITY CHECK (MAX_SECURITY_LEVEL BETWEEN 0 AND 3)
);

CREATE INDEX IX_PLATFORM_USER_OWNER ON KBOT_PLATFORM_USER
    (ACCOUNT_ORIGIN, OWNER_APP_ID, STATUS);

CREATE TABLE KBOT_PLATFORM_USER_CREDENTIAL (
    USER_ID VARCHAR2(256 CHAR) PRIMARY KEY,
    PASSWORD_HASH VARCHAR2(128 CHAR) NOT NULL,
    MUST_CHANGE_PASSWORD CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    PASSWORD_UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PLATFORM_USER_CRED_USER FOREIGN KEY (USER_ID)
        REFERENCES KBOT_PLATFORM_USER (USER_ID),
    CONSTRAINT CK_PLATFORM_USER_CRED_CHANGE CHECK (MUST_CHANGE_PASSWORD IN ('Y', 'N'))
);

CREATE TABLE KBOT_PERMISSION (
    PERMISSION_CODE VARCHAR2(128 CHAR) PRIMARY KEY,
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    CONSTRAINT UK_PERMISSION_APP_CODE UNIQUE (APP_ID, PERMISSION_CODE),
    CONSTRAINT FK_PERMISSION_APP FOREIGN KEY (APP_ID)
        REFERENCES KBOT_PLATFORM_APP (APP_ID)
);

CREATE TABLE KBOT_APP_ROLE (
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    ROLE_CODE VARCHAR2(64 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    IS_SYSTEM CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    SCOPE_POLICY VARCHAR2(32 CHAR) DEFAULT 'SELECTABLE' NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_APP_ROLE PRIMARY KEY (APP_ID, ROLE_CODE),
    CONSTRAINT FK_APP_ROLE_APP FOREIGN KEY (APP_ID)
        REFERENCES KBOT_PLATFORM_APP (APP_ID),
    CONSTRAINT CK_APP_ROLE_SYSTEM CHECK (IS_SYSTEM IN ('Y', 'N')),
    CONSTRAINT CK_APP_ROLE_SCOPE CHECK (SCOPE_POLICY IN ('PLATFORM', 'SELECTABLE', 'ALL_APP_DOMAINS')),
    CONSTRAINT CK_APP_ROLE_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE KBOT_APP_ROLE_PERMISSION (
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    ROLE_CODE VARCHAR2(64 CHAR) NOT NULL,
    PERMISSION_CODE VARCHAR2(128 CHAR) NOT NULL,
    CONSTRAINT PK_APP_ROLE_PERMISSION PRIMARY KEY (APP_ID, ROLE_CODE, PERMISSION_CODE),
    CONSTRAINT FK_APP_ROLE_PERMISSION_ROLE FOREIGN KEY (APP_ID, ROLE_CODE)
        REFERENCES KBOT_APP_ROLE (APP_ID, ROLE_CODE),
    CONSTRAINT FK_APP_ROLE_PERM_PERMISSION FOREIGN KEY (APP_ID, PERMISSION_CODE)
        REFERENCES KBOT_PERMISSION (APP_ID, PERMISSION_CODE)
);

CREATE TABLE KBOT_PLATFORM_USER_ROLE (
    USER_ID VARCHAR2(256 CHAR) NOT NULL,
    ROLE_CODE VARCHAR2(64 CHAR) NOT NULL,
    APP_ID VARCHAR2(64 CHAR) DEFAULT 'platform' NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PLATFORM_USER_ROLE PRIMARY KEY (USER_ID, ROLE_CODE),
    CONSTRAINT FK_PLATFORM_USER_ROLE_USER FOREIGN KEY (USER_ID)
        REFERENCES KBOT_PLATFORM_USER (USER_ID),
    CONSTRAINT FK_PLATFORM_USER_ROLE_ROLE FOREIGN KEY (APP_ID, ROLE_CODE)
        REFERENCES KBOT_APP_ROLE (APP_ID, ROLE_CODE),
    CONSTRAINT CK_PLATFORM_USER_ROLE_APP CHECK (APP_ID = 'platform'),
    CONSTRAINT CK_PLATFORM_USER_ROLE_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE KBOT_APP_DOMAIN (
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_APP_DOMAIN PRIMARY KEY (APP_ID, DOMAIN_ID),
    CONSTRAINT FK_APP_DOMAIN_APP FOREIGN KEY (APP_ID)
        REFERENCES KBOT_PLATFORM_APP (APP_ID),
    CONSTRAINT FK_APP_DOMAIN_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_APP_DOMAIN_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE KBOT_APP_MEMBER (
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    USER_ID VARCHAR2(256 CHAR) NOT NULL,
    MEMBER_SOURCE VARCHAR2(32 CHAR) NOT NULL,
    IS_INITIAL_ADMIN CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    GRANTED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_APP_MEMBER PRIMARY KEY (APP_ID, USER_ID),
    CONSTRAINT FK_APP_MEMBER_APP FOREIGN KEY (APP_ID)
        REFERENCES KBOT_PLATFORM_APP (APP_ID),
    CONSTRAINT FK_APP_MEMBER_USER FOREIGN KEY (USER_ID)
        REFERENCES KBOT_PLATFORM_USER (USER_ID),
    CONSTRAINT CK_APP_MEMBER_SOURCE CHECK (MEMBER_SOURCE IN ('APP_CREATED', 'PLATFORM_GRANT', 'APP_INITIAL_ADMIN')),
    CONSTRAINT CK_APP_MEMBER_INITIAL CHECK (IS_INITIAL_ADMIN IN ('Y', 'N')),
    CONSTRAINT CK_APP_MEMBER_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_APP_INITIAL_ACTIVE CHECK (IS_INITIAL_ADMIN = 'N' OR STATUS = 'ACTIVE')
);

CREATE UNIQUE INDEX UK_APP_INITIAL_ADMIN ON KBOT_APP_MEMBER (
    CASE WHEN IS_INITIAL_ADMIN = 'Y' THEN APP_ID END
);

CREATE INDEX IX_APP_MEMBER_USER ON KBOT_APP_MEMBER (USER_ID, STATUS, APP_ID);

CREATE TABLE KBOT_APP_MEMBER_ROLE (
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    USER_ID VARCHAR2(256 CHAR) NOT NULL,
    ROLE_CODE VARCHAR2(64 CHAR) NOT NULL,
    SCOPE_MODE VARCHAR2(32 CHAR) DEFAULT 'SELECTED_DOMAINS' NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_APP_MEMBER_ROLE PRIMARY KEY (APP_ID, USER_ID, ROLE_CODE),
    CONSTRAINT FK_APP_MEMBER_ROLE_ROLE FOREIGN KEY (APP_ID, ROLE_CODE)
        REFERENCES KBOT_APP_ROLE (APP_ID, ROLE_CODE),
    CONSTRAINT FK_APP_MEMBER_ROLE_MEMBER FOREIGN KEY (APP_ID, USER_ID)
        REFERENCES KBOT_APP_MEMBER (APP_ID, USER_ID),
    CONSTRAINT CK_APP_MEMBER_ROLE_SCOPE CHECK (SCOPE_MODE IN ('ALL_APP_DOMAINS', 'SELECTED_DOMAINS')),
    CONSTRAINT CK_APP_MEMBER_ROLE_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE KBOT_APP_MEMBER_ROLE_SCOPE (
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    USER_ID VARCHAR2(256 CHAR) NOT NULL,
    ROLE_CODE VARCHAR2(64 CHAR) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    CONSTRAINT PK_APP_MEMBER_ROLE_SCOPE PRIMARY KEY (APP_ID, USER_ID, ROLE_CODE, DOMAIN_ID),
    CONSTRAINT FK_APP_MEMBER_SCOPE_BINDING FOREIGN KEY (APP_ID, USER_ID, ROLE_CODE)
        REFERENCES KBOT_APP_MEMBER_ROLE (APP_ID, USER_ID, ROLE_CODE),
    CONSTRAINT FK_APP_MEMBER_SCOPE_DOMAIN FOREIGN KEY (APP_ID, DOMAIN_ID)
        REFERENCES KBOT_APP_DOMAIN (APP_ID, DOMAIN_ID)
);

INSERT ALL
    INTO KBOT_PLATFORM_APP (APP_ID, DISPLAY_NAME, STATUS, MEMBER_ASSIGNABLE) VALUES ('platform', '平台管理', 'ACTIVE', 'N')
    INTO KBOT_PLATFORM_APP (APP_ID, DISPLAY_NAME, STATUS, MEMBER_ASSIGNABLE) VALUES ('knowledge_retrieval', '知识检索', 'ACTIVE', 'Y')
    INTO KBOT_PLATFORM_APP (APP_ID, DISPLAY_NAME, STATUS, MEMBER_ASSIGNABLE) VALUES ('aiops', 'AIOps', 'ACTIVE', 'Y')
    INTO KBOT_PLATFORM_APP (APP_ID, DISPLAY_NAME, STATUS, MEMBER_ASSIGNABLE) VALUES ('km_asset', 'KM Asset', 'ACTIVE', 'Y')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO KBOT_PERMISSION VALUES ('platform:user_manage', 'platform', '管理平台用户')
    INTO KBOT_PERMISSION VALUES ('platform:role_manage', 'platform', '管理平台角色')
    INTO KBOT_PERMISSION VALUES ('platform:domain_manage', 'platform', '管理平台 Domain')
    INTO KBOT_PERMISSION VALUES ('platform:app_manage', 'platform', '管理 App 生命周期和初始管理员')
    INTO KBOT_PERMISSION VALUES ('platform:app_grant_manage', 'platform', '显式授予平台用户 App 权限')
    INTO KBOT_PERMISSION VALUES ('knowledge_retrieval:use', 'knowledge_retrieval', '使用知识检索')
    INTO KBOT_PERMISSION VALUES ('knowledge_retrieval:upload', 'knowledge_retrieval', '上传知识文件')
    INTO KBOT_PERMISSION VALUES ('knowledge_retrieval:review', 'knowledge_retrieval', '审核知识文件')
    INTO KBOT_PERMISSION VALUES ('knowledge_retrieval:member_manage', 'knowledge_retrieval', '管理应用成员')
    INTO KBOT_PERMISSION VALUES ('knowledge_retrieval:role_manage', 'knowledge_retrieval', '管理应用角色')
    INTO KBOT_PERMISSION VALUES ('knowledge_retrieval:knowledge_manage', 'knowledge_retrieval', '管理知识库')
    INTO KBOT_PERMISSION VALUES ('knowledge_retrieval:data_manage', 'knowledge_retrieval', '管理问数资源')
    INTO KBOT_PERMISSION VALUES ('knowledge_retrieval:agent_manage', 'knowledge_retrieval', '管理知识检索 Agent')
    INTO KBOT_PERMISSION VALUES ('knowledge_retrieval:operations_manage', 'knowledge_retrieval', '管理知识检索运行')
    INTO KBOT_PERMISSION VALUES ('km_asset:use', 'km_asset', '使用 KM Asset')
    INTO KBOT_PERMISSION VALUES ('km_asset:source_manage', 'km_asset', '管理 KM Asset 来源')
    INTO KBOT_PERMISSION VALUES ('km_asset:knowledge_manage', 'km_asset', '管理 KM Portal Knowledge Core')
    INTO KBOT_PERMISSION VALUES ('km_asset:data_manage', 'km_asset', '管理 KM Asset 问数模型')
    INTO KBOT_PERMISSION VALUES ('km_asset:agent_manage', 'km_asset', '管理 KM Asset Agent')
    INTO KBOT_PERMISSION VALUES ('km_asset:operations_manage', 'km_asset', '管理 KM Asset 同步运行')
    INTO KBOT_PERMISSION VALUES ('km_asset:member_manage', 'km_asset', '管理 KM Asset 成员')
    INTO KBOT_PERMISSION VALUES ('km_asset:role_manage', 'km_asset', '管理 KM Asset 角色')
    INTO KBOT_PERMISSION VALUES ('aiops:use', 'aiops', '使用 AIOps')
    INTO KBOT_PERMISSION VALUES ('aiops:domain_manage', 'aiops', '管理 AIOps Domain 配置')
    INTO KBOT_PERMISSION VALUES ('aiops:member_manage', 'aiops', '管理 AIOps 成员')
    INTO KBOT_PERMISSION VALUES ('aiops:role_manage', 'aiops', '管理 AIOps 角色')
    INTO KBOT_PERMISSION VALUES ('aiops:operations_manage', 'aiops', '管理 AIOps 运行')
    INTO KBOT_PERMISSION VALUES ('aiops:target_manage', 'aiops', '管理诊断目标')
    INTO KBOT_PERMISSION VALUES ('aiops:diagnostic_source_manage', 'aiops', '管理诊断源')
    INTO KBOT_PERMISSION VALUES ('aiops:policy_manage', 'aiops', '管理诊断策略')
    INTO KBOT_PERMISSION VALUES ('aiops:plan_manage', 'aiops', '管理变更计划')
    INTO KBOT_PERMISSION VALUES ('aiops:agent_manage', 'aiops', '管理 AIOps Agent')
    INTO KBOT_PERMISSION VALUES ('aiops:knowledge_manage', 'aiops', '管理 AIOps Knowledge Core')
    INTO KBOT_PERMISSION VALUES ('aiops:api_key_manage', 'aiops', '管理 AIOps API Client')
    INTO KBOT_PERMISSION VALUES ('aiops:proposal:approve', 'aiops', '审批执行提案')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO KBOT_APP_ROLE VALUES ('platform', 'platform_admin', '平台管理员', 'Y', 'PLATFORM', 'ACTIVE', 1)
    INTO KBOT_APP_ROLE VALUES ('knowledge_retrieval', 'app_admin', '知识检索初始管理员', 'Y', 'ALL_APP_DOMAINS', 'ACTIVE', 1)
    INTO KBOT_APP_ROLE VALUES ('knowledge_retrieval', 'user', '用户', 'Y', 'SELECTABLE', 'ACTIVE', 1)
    INTO KBOT_APP_ROLE VALUES ('knowledge_retrieval', 'contributor', '贡献者', 'Y', 'SELECTABLE', 'ACTIVE', 1)
    INTO KBOT_APP_ROLE VALUES ('knowledge_retrieval', 'reviewer', '审核人', 'Y', 'SELECTABLE', 'ACTIVE', 1)
    INTO KBOT_APP_ROLE VALUES ('km_asset', 'app_admin', 'KM Asset 初始管理员', 'Y', 'ALL_APP_DOMAINS', 'ACTIVE', 1)
    INTO KBOT_APP_ROLE VALUES ('km_asset', 'user', '用户', 'Y', 'SELECTABLE', 'ACTIVE', 1)
    INTO KBOT_APP_ROLE VALUES ('aiops', 'app_admin', 'AIOps 初始管理员', 'Y', 'ALL_APP_DOMAINS', 'ACTIVE', 1)
    INTO KBOT_APP_ROLE VALUES ('aiops', 'operator', '运维操作员', 'Y', 'SELECTABLE', 'ACTIVE', 1)
    INTO KBOT_APP_ROLE VALUES ('aiops', 'approver', '审批人', 'Y', 'SELECTABLE', 'ACTIVE', 1)
SELECT 1 FROM DUAL;

INSERT INTO KBOT_APP_ROLE_PERMISSION
SELECT 'platform', 'platform_admin', PERMISSION_CODE FROM KBOT_PERMISSION WHERE APP_ID = 'platform';

INSERT INTO KBOT_APP_ROLE_PERMISSION
SELECT 'knowledge_retrieval', 'app_admin', PERMISSION_CODE FROM KBOT_PERMISSION WHERE APP_ID = 'knowledge_retrieval';

INSERT INTO KBOT_APP_ROLE_PERMISSION
SELECT 'knowledge_retrieval', 'user', PERMISSION_CODE FROM KBOT_PERMISSION WHERE PERMISSION_CODE = 'knowledge_retrieval:use';

INSERT INTO KBOT_APP_ROLE_PERMISSION
SELECT 'knowledge_retrieval', 'contributor', PERMISSION_CODE FROM KBOT_PERMISSION
WHERE PERMISSION_CODE IN ('knowledge_retrieval:use', 'knowledge_retrieval:upload');

INSERT INTO KBOT_APP_ROLE_PERMISSION
SELECT 'knowledge_retrieval', 'reviewer', PERMISSION_CODE FROM KBOT_PERMISSION
WHERE PERMISSION_CODE IN ('knowledge_retrieval:use', 'knowledge_retrieval:upload', 'knowledge_retrieval:review');

INSERT INTO KBOT_APP_ROLE_PERMISSION
SELECT 'km_asset', 'app_admin', PERMISSION_CODE FROM KBOT_PERMISSION WHERE APP_ID = 'km_asset';

INSERT INTO KBOT_APP_ROLE_PERMISSION
SELECT 'km_asset', 'user', PERMISSION_CODE FROM KBOT_PERMISSION WHERE PERMISSION_CODE = 'km_asset:use';

INSERT INTO KBOT_APP_ROLE_PERMISSION
SELECT 'aiops', 'app_admin', PERMISSION_CODE FROM KBOT_PERMISSION WHERE APP_ID = 'aiops';

INSERT INTO KBOT_APP_ROLE_PERMISSION
SELECT 'aiops', 'operator', PERMISSION_CODE FROM KBOT_PERMISSION
WHERE PERMISSION_CODE IN ('aiops:use', 'aiops:operations_manage', 'aiops:target_manage', 'aiops:diagnostic_source_manage', 'aiops:policy_manage', 'aiops:plan_manage');

INSERT INTO KBOT_APP_ROLE_PERMISSION
SELECT 'aiops', 'approver', PERMISSION_CODE FROM KBOT_PERMISSION
WHERE PERMISSION_CODE IN ('aiops:use', 'aiops:operations_manage', 'aiops:proposal:approve');
