CREATE TABLE KBOT_APP_API_CLIENT (
    CLIENT_ID RAW(16) PRIMARY KEY,
    APP_ID VARCHAR2(64 CHAR) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    SUBJECT_USER_ID VARCHAR2(256 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    RATE_LIMIT_PER_MINUTE NUMBER(10) DEFAULT 60 NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_APP_API_CLIENT_DOMAIN FOREIGN KEY (APP_ID, DOMAIN_ID)
        REFERENCES KBOT_APP_DOMAIN (APP_ID, DOMAIN_ID),
    CONSTRAINT FK_APP_API_CLIENT_MEMBER FOREIGN KEY (APP_ID, SUBJECT_USER_ID)
        REFERENCES KBOT_APP_MEMBER (APP_ID, USER_ID),
    CONSTRAINT CK_APP_API_CLIENT_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_APP_API_CLIENT_RATE CHECK (RATE_LIMIT_PER_MINUTE BETWEEN 1 AND 10000)
);

CREATE INDEX IX_APP_API_CLIENT_APP ON KBOT_APP_API_CLIENT
    (APP_ID, DOMAIN_ID, STATUS);

CREATE TABLE KBOT_APP_API_CREDENTIAL (
    CREDENTIAL_ID RAW(16) PRIMARY KEY,
    CLIENT_ID RAW(16) NOT NULL,
    PUBLIC_KEY_ID VARCHAR2(64 CHAR) NOT NULL,
    KEY_DIGEST VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    LAST_USED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    REVOKED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT FK_APP_API_CRED_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES KBOT_APP_API_CLIENT (CLIENT_ID),
    CONSTRAINT UK_APP_API_CRED_PUBLIC UNIQUE (PUBLIC_KEY_ID),
    CONSTRAINT CK_APP_API_CRED_STATUS CHECK (STATUS IN ('ACTIVE', 'REVOKED', 'EXPIRED')),
    CONSTRAINT CK_APP_API_CRED_DIGEST CHECK (REGEXP_LIKE(KEY_DIGEST, '^[0-9a-f]{64}$'))
);

CREATE INDEX IX_APP_API_CRED_CLIENT ON KBOT_APP_API_CREDENTIAL
    (CLIENT_ID, STATUS, EXPIRES_AT);

CREATE UNIQUE INDEX UX_APP_API_CRED_ACTIVE ON KBOT_APP_API_CREDENTIAL (
    CASE WHEN STATUS = 'ACTIVE' THEN CLIENT_ID END
);

CREATE TABLE KBOT_APP_API_CLIENT_SCOPE (
    CLIENT_ID RAW(16) NOT NULL,
    SCOPE_CODE VARCHAR2(128 CHAR) NOT NULL,
    CONSTRAINT PK_APP_API_CLIENT_SCOPE PRIMARY KEY (CLIENT_ID, SCOPE_CODE),
    CONSTRAINT FK_APP_API_SCOPE_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES KBOT_APP_API_CLIENT (CLIENT_ID)
);

CREATE TABLE KBOT_APP_API_CLIENT_AGENT (
    CLIENT_ID RAW(16) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    CONSTRAINT PK_APP_API_CLIENT_AGENT PRIMARY KEY (CLIENT_ID, AGENT_ID),
    CONSTRAINT FK_APP_API_AGENT_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES KBOT_APP_API_CLIENT (CLIENT_ID)
);

INSERT INTO KBOT_PERMISSION (PERMISSION_CODE, APP_ID, DISPLAY_NAME)
VALUES ('knowledge_retrieval:api_key_manage', 'knowledge_retrieval',
        '管理知识检索 API Client');

INSERT INTO KBOT_PERMISSION (PERMISSION_CODE, APP_ID, DISPLAY_NAME)
VALUES ('km_asset:api_key_manage', 'km_asset', '管理 KM Asset API Client');

INSERT INTO KBOT_PERMISSION (PERMISSION_CODE, APP_ID, DISPLAY_NAME)
VALUES ('aiops:api_key_manage', 'aiops', '管理 AIOps API Client');

INSERT INTO KBOT_APP_ROLE_PERMISSION (APP_ID, ROLE_CODE, PERMISSION_CODE)
VALUES ('knowledge_retrieval', 'app_admin',
        'knowledge_retrieval:api_key_manage');

INSERT INTO KBOT_APP_ROLE_PERMISSION (APP_ID, ROLE_CODE, PERMISSION_CODE)
VALUES ('km_asset', 'app_admin', 'km_asset:api_key_manage');

INSERT INTO KBOT_APP_ROLE_PERMISSION (APP_ID, ROLE_CODE, PERMISSION_CODE)
VALUES ('aiops', 'app_admin', 'aiops:api_key_manage');
