-- KBot 4.0 AIOps：目标、策略、Agent 绑定和诊断源根聚合。
-- 本脚本只用于空 Schema 初始化；UUIDv7 由应用生成。

CREATE TABLE KBOT_OPS_TARGET (
    TARGET_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DB_TYPE VARCHAR2(32 CHAR) NOT NULL,
    VERSION_CODE VARCHAR2(64 CHAR),
    ENVIRONMENT VARCHAR2(16 CHAR) NOT NULL,
    DB_ROLE VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    ORACLE_CONTAINER_SCOPE VARCHAR2(16 CHAR),
    ORACLE_PDB_NAME VARCHAR2(128 CHAR),
    OBSERVED_ORACLE_CONTAINER_SCOPE VARCHAR2(16 CHAR),
    OBSERVED_ORACLE_CONTAINER_NAME VARCHAR2(128 CHAR),
    OBSERVED_ORACLE_CONTAINER_NUMBER NUMBER(10),
    OBSERVED_ORACLE_DATABASE_NAME VARCHAR2(128 CHAR),
    ENDPOINT_JSON JSON,
    READONLY_CONNECTION_ENABLED NUMBER(1) DEFAULT 0 NOT NULL,
    CONTROLLED_CHANGE_ENABLED NUMBER(1) DEFAULT 0 NOT NULL,
    DIAGNOSTIC_CREDENTIAL_ID RAW(16),
    EXECUTION_CREDENTIAL_ID RAW(16),
    SECURITY_LEVEL NUMBER(3) DEFAULT 1 NOT NULL,
    CAPABILITIES_JSON JSON,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DISABLED' NOT NULL,
    CONNECTIVITY_STATUS VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    OBSERVED_STATUS VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    LAST_OBSERVED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONNECTIVITY_CHECK_REQUEST_ID RAW(16),
    CONNECTIVITY_CHECK_REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_CONNECTIVITY_CHECK_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_CONNECTIVITY_SUCCESS_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_ERROR_CODE VARCHAR2(128 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONNECTIVITY_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_TARGET_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_OPS_TARGET_OWNER UNIQUE (TARGET_ID, DOMAIN_ID));

CREATE INDEX IX_OPS_TARGET_SCOPE
    ON KBOT_OPS_TARGET (DOMAIN_ID, STATUS, DISPLAY_NAME);
CREATE INDEX IX_OPS_TARGET_DOMAIN
    ON KBOT_OPS_TARGET (DOMAIN_ID);
CREATE INDEX IX_OPS_TARGET_TYPE
    ON KBOT_OPS_TARGET (DB_TYPE, STATUS);

CREATE TABLE KBOT_OPS_TARGET_FACT (
    TARGET_FACT_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    FACT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    FACT_KEY VARCHAR2(256 CHAR) NOT NULL,
    FACT_VALUE JSON NOT NULL,
    SOURCE VARCHAR2(32 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CONFIRMED_BY VARCHAR2(256 CHAR),
    CONFIRMED_AT TIMESTAMP(6) WITH TIME ZONE,
    RETIRED_BY VARCHAR2(256 CHAR),
    RETIRED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_TARGET_FACT_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_TARGET_FACT_OWNER
        FOREIGN KEY (TARGET_ID, DOMAIN_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID, DOMAIN_ID),
    CONSTRAINT FK_OPS_TARGET_FACT_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID));

CREATE INDEX IX_OPS_TARGET_FACT_TARGET
    ON KBOT_OPS_TARGET_FACT (TARGET_ID, STATUS);
CREATE INDEX IX_OPS_TARGET_FACT_DOMAIN
    ON KBOT_OPS_TARGET_FACT (DOMAIN_ID);
COMMENT ON COLUMN KBOT_OPS_TARGET_FACT.FACT_VALUE IS
    '已确认的运维事实值；仅保存白名单字段，不保存可执行 SQL';

CREATE TABLE KBOT_OPS_POLICY (
    POLICY_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    POLICY_KEY VARCHAR2(128 CHAR) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    RULES_JSON JSON NOT NULL,
    POLICY_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    EFFECTIVE_AT TIMESTAMP(6) WITH TIME ZONE,
    RETIRED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_POLICY_VERSION
        UNIQUE (DOMAIN_ID, POLICY_KEY, VERSION_NO),
    CONSTRAINT FK_OPS_POLICY_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID));

CREATE TABLE KBOT_OPS_TARGET_BINDING (
    BINDING_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    ALLOW_MUTATION NUMBER(1) DEFAULT 0 NOT NULL,
    POLICY_ID RAW(16),
    ALLOWED_ACTIONS_JSON JSON,
    CHANGE_WINDOW_JSON JSON,
    MAX_DAILY_EXECUTIONS NUMBER(10),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_BINDING_TARGET_AGENT UNIQUE (TARGET_ID, AGENT_ID),
    CONSTRAINT FK_OPS_BINDING_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_BINDING_POLICY
        FOREIGN KEY (POLICY_ID) REFERENCES KBOT_OPS_POLICY (POLICY_ID));

CREATE INDEX IX_OPS_POLICY_DOMAIN
    ON KBOT_OPS_POLICY (DOMAIN_ID);
CREATE INDEX IX_OPS_BINDING_AGENT
    ON KBOT_OPS_TARGET_BINDING (AGENT_ID, STATUS, ALLOW_MUTATION);
CREATE INDEX IX_OPS_BINDING_TARGET
    ON KBOT_OPS_TARGET_BINDING (TARGET_ID, STATUS);
CREATE INDEX IX_OPS_BINDING_POLICY
    ON KBOT_OPS_TARGET_BINDING (POLICY_ID);

CREATE TABLE KBOT_OPS_NOTIFICATION_SUBSCRIPTION (
    SUBSCRIPTION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    RECIPIENT_ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    CHANNEL VARCHAR2(16 CHAR) DEFAULT 'IN_APP' NOT NULL,
    MINIMUM_SEVERITY VARCHAR2(16 CHAR) DEFAULT 'HIGH' NOT NULL,
    STAGES_JSON JSON NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_NOTIFY_SUB_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_NOTIFY_SUB_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT UK_OPS_NOTIFY_SUB_RECIPIENT UNIQUE (
        DOMAIN_ID, TARGET_ID, RECIPIENT_ACTOR_ID, CHANNEL
    ));

CREATE INDEX IX_OPS_NOTIFY_SUB_ROUTE ON KBOT_OPS_NOTIFICATION_SUBSCRIPTION
    (TARGET_ID, STATUS, MINIMUM_SEVERITY);

CREATE TABLE KBOT_OPS_DIAGNOSTIC_SOURCE (
    DIAGNOSTIC_SOURCE_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    SOURCE_TYPE VARCHAR2(64 CHAR) NOT NULL,
    ADAPTER_ID VARCHAR2(128 CHAR) NOT NULL,
    ADAPTER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    ENDPOINT VARCHAR2(2048 CHAR),
    AUTH_CREDENTIAL_ID RAW(16),
    WEBHOOK_CREDENTIAL_ID RAW(16),
    TLS_PROFILE_REF VARCHAR2(1024 CHAR),
    WEBHOOK_KEY_HASH VARCHAR2(64 CHAR),
    PREVIOUS_WEBHOOK_KEY_HASH VARCHAR2(64 CHAR),
    PREVIOUS_WEBHOOK_KEY_EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    DECLARED_CAPABILITIES_JSON JSON NOT NULL,
    DISCOVERED_CAPABILITIES_JSON JSON,
    CONFIG_JSON JSON NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DISABLED' NOT NULL,
    CONNECTIVITY_STATUS VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    CONNECTIVITY_CHECK_REQUEST_ID RAW(16),
    CONNECTIVITY_CHECK_REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_CONNECTIVITY_CHECK_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_CONNECTIVITY_SUCCESS_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_ERROR_CODE VARCHAR2(128 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONNECTIVITY_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_SOURCE_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID));

CREATE UNIQUE INDEX UX_OPS_SOURCE_WEBHOOK
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (WEBHOOK_KEY_HASH);
CREATE UNIQUE INDEX UX_OPS_SOURCE_PREV_WEBHOOK
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (PREVIOUS_WEBHOOK_KEY_HASH);
CREATE INDEX IX_OPS_SOURCE_SCOPE
    ON KBOT_OPS_DIAGNOSTIC_SOURCE
       (DOMAIN_ID, SOURCE_TYPE, STATUS);
CREATE INDEX IX_OPS_SOURCE_DOMAIN
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (DOMAIN_ID);
CREATE INDEX IX_OPS_SOURCE_CONNECTIVITY
    ON KBOT_OPS_DIAGNOSTIC_SOURCE
       (CONNECTIVITY_STATUS, LAST_CONNECTIVITY_CHECK_AT);
CREATE INDEX IX_OPS_SOURCE_CONNECTIVITY_REQ
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (CONNECTIVITY_CHECK_REQUEST_ID);

CREATE TABLE KBOT_OPS_TARGET_SOURCE_BINDING (
    TARGET_SOURCE_BINDING_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    DIAGNOSTIC_SOURCE_ID RAW(16) NOT NULL,
    SOURCE_LOCATOR_KEY VARCHAR2(512 CHAR) NOT NULL,
    SOURCE_LOCATOR_JSON JSON NOT NULL,
    ROLE VARCHAR2(16 CHAR) DEFAULT 'PRIMARY' NOT NULL,
    PRIORITY NUMBER(8) DEFAULT 100 NOT NULL,
    CAPABILITY_SCOPE_JSON JSON,
    MAPPING_OVERRIDES_JSON JSON,
    QUERY_BUDGET_JSON JSON,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    HEALTH_STATUS VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    LAST_HEALTH_CHECK_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_ERROR_CODE VARCHAR2(128 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    HEALTH_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_TSRC_LOCATOR
        UNIQUE (DIAGNOSTIC_SOURCE_ID, SOURCE_LOCATOR_KEY),
    CONSTRAINT FK_OPS_TSRC_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_TSRC_MONITOR
        FOREIGN KEY (DIAGNOSTIC_SOURCE_ID)
        REFERENCES KBOT_OPS_DIAGNOSTIC_SOURCE (DIAGNOSTIC_SOURCE_ID));

CREATE INDEX IX_OPS_TSRC_TARGET
    ON KBOT_OPS_TARGET_SOURCE_BINDING (TARGET_ID, STATUS, PRIORITY);
CREATE INDEX IX_OPS_TSRC_MONITOR
    ON KBOT_OPS_TARGET_SOURCE_BINDING (DIAGNOSTIC_SOURCE_ID, STATUS);

COMMENT ON COLUMN KBOT_OPS_TARGET.TARGET_ID IS
    '应用生成的 UUIDv7；API 使用规范 UUID 字符串';
COMMENT ON COLUMN KBOT_OPS_TARGET.ENDPOINT_JSON IS
    '仅保存连接端点元数据，不保存用户名、密码或 Token';
COMMENT ON COLUMN KBOT_OPS_DIAGNOSTIC_SOURCE.WEBHOOK_KEY_HASH IS
    '外部 Webhook 不透明路由键的 SHA-256，不保存明文';
