-- KBot 4.0 AIOps：目标、策略、Agent 绑定和监控源根聚合。
-- 本脚本只用于空 Schema 初始化；UUIDv7 由应用生成。

CREATE TABLE KBOT_OPS_TARGET (
    TARGET_ID RAW(16) PRIMARY KEY,
    APP_ID NUMBER(38) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_KEY VARCHAR2(128 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DB_TYPE VARCHAR2(32 CHAR) NOT NULL,
    VERSION_CODE VARCHAR2(64 CHAR),
    ENVIRONMENT VARCHAR2(16 CHAR) NOT NULL,
    DB_ROLE VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    ENDPOINT_JSON CLOB,
    DIAGNOSTIC_SECRET_REF VARCHAR2(1024 CHAR),
    EXECUTION_SECRET_REF VARCHAR2(1024 CHAR),
    EXECUTION_MODE VARCHAR2(16 CHAR) DEFAULT 'ADVISORY' NOT NULL,
    SECURITY_LEVEL NUMBER(3) DEFAULT 1 NOT NULL,
    CAPABILITIES_JSON CLOB,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'MAINTENANCE' NOT NULL,
    HEALTH_STATUS VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    LAST_HEALTH_CHECK_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_ERROR_CODE VARCHAR2(128 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    HEALTH_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_TARGET_KEY
        UNIQUE (APP_ID, DOMAIN_ID, TARGET_KEY),
    CONSTRAINT FK_OPS_TARGET_DOMAIN
        FOREIGN KEY (DOMAIN_ID, APP_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID, APP_ID),
    CONSTRAINT CK_OPS_TARGET_ENV
        CHECK (ENVIRONMENT IN ('PROD', 'STG', 'DEV')),
    CONSTRAINT CK_OPS_TARGET_ROLE
        CHECK (DB_ROLE IN ('PRIMARY', 'STANDBY', 'UNKNOWN')),
    CONSTRAINT CK_OPS_TARGET_EXEC_MODE
        CHECK (EXECUTION_MODE IN ('ADVISORY', 'AGENT_EXECUTE')),
    CONSTRAINT CK_OPS_TARGET_STATUS
        CHECK (STATUS IN ('ACTIVE', 'MAINTENANCE', 'DISABLED')),
    CONSTRAINT CK_OPS_TARGET_HEALTH
        CHECK (HEALTH_STATUS IN (
            'UNKNOWN', 'HEALTHY', 'DEGRADED', 'UNREACHABLE'
        )),
    CONSTRAINT CK_OPS_TARGET_SECURITY CHECK (SECURITY_LEVEL >= 0),
    CONSTRAINT CK_OPS_TARGET_VERSION
        CHECK (ROW_VERSION >= 1 AND HEALTH_VERSION >= 1),
    CONSTRAINT CK_OPS_TARGET_ENDPOINT_JSON CHECK (ENDPOINT_JSON IS JSON),
    CONSTRAINT CK_OPS_TARGET_CAPS_JSON CHECK (CAPABILITIES_JSON IS JSON)
);

CREATE INDEX IX_OPS_TARGET_SCOPE
    ON KBOT_OPS_TARGET (APP_ID, DOMAIN_ID, STATUS, DISPLAY_NAME);
CREATE INDEX IX_OPS_TARGET_DOMAIN
    ON KBOT_OPS_TARGET (DOMAIN_ID, APP_ID);
CREATE INDEX IX_OPS_TARGET_TYPE
    ON KBOT_OPS_TARGET (DB_TYPE, STATUS);

CREATE TABLE KBOT_OPS_POLICY (
    POLICY_ID RAW(16) PRIMARY KEY,
    APP_ID NUMBER(38) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    POLICY_KEY VARCHAR2(128 CHAR) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    RULES_JSON CLOB NOT NULL,
    POLICY_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    EFFECTIVE_AT TIMESTAMP(6) WITH TIME ZONE,
    RETIRED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_POLICY_VERSION
        UNIQUE (APP_ID, DOMAIN_ID, POLICY_KEY, VERSION_NO),
    CONSTRAINT FK_OPS_POLICY_DOMAIN
        FOREIGN KEY (DOMAIN_ID, APP_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID, APP_ID),
    CONSTRAINT CK_OPS_POLICY_STATUS
        CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT CK_OPS_POLICY_VERSION
        CHECK (VERSION_NO >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_POLICY_RULES_JSON CHECK (RULES_JSON IS JSON),
    CONSTRAINT CK_OPS_POLICY_HASH CHECK (LENGTH(POLICY_HASH) = 64)
);

CREATE TABLE KBOT_OPS_TARGET_BINDING (
    BINDING_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    ACCESS_MODE VARCHAR2(16 CHAR) NOT NULL,
    POLICY_ID RAW(16),
    ALLOWED_ACTIONS_JSON CLOB,
    CHANGE_WINDOW_JSON CLOB,
    MAX_DAILY_EXECUTIONS NUMBER(10),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_BINDING_TARGET_AGENT UNIQUE (TARGET_ID, AGENT_ID),
    CONSTRAINT FK_OPS_BINDING_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_BINDING_POLICY
        FOREIGN KEY (POLICY_ID) REFERENCES KBOT_OPS_POLICY (POLICY_ID),
    CONSTRAINT CK_OPS_BINDING_ACCESS CHECK (
        ACCESS_MODE IN ('OBSERVE', 'DIAGNOSE', 'PROPOSE', 'EXECUTE')
    ),
    CONSTRAINT CK_OPS_BINDING_STATUS
        CHECK (STATUS IN ('ACTIVE', 'REVOKED')),
    CONSTRAINT CK_OPS_BINDING_MAX_DAILY
        CHECK (MAX_DAILY_EXECUTIONS IS NULL OR MAX_DAILY_EXECUTIONS >= 0),
    CONSTRAINT CK_OPS_BINDING_VERSION CHECK (ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_BINDING_ACTION_JSON
        CHECK (ALLOWED_ACTIONS_JSON IS JSON),
    CONSTRAINT CK_OPS_BINDING_WINDOW_JSON CHECK (CHANGE_WINDOW_JSON IS JSON)
);

CREATE INDEX IX_OPS_POLICY_DOMAIN
    ON KBOT_OPS_POLICY (DOMAIN_ID, APP_ID);
CREATE INDEX IX_OPS_BINDING_AGENT
    ON KBOT_OPS_TARGET_BINDING (AGENT_ID, STATUS, ACCESS_MODE);
CREATE INDEX IX_OPS_BINDING_TARGET
    ON KBOT_OPS_TARGET_BINDING (TARGET_ID, STATUS);
CREATE INDEX IX_OPS_BINDING_POLICY
    ON KBOT_OPS_TARGET_BINDING (POLICY_ID);

CREATE TABLE KBOT_OPS_MONITOR_SOURCE (
    MONITOR_SOURCE_ID RAW(16) PRIMARY KEY,
    APP_ID NUMBER(38) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    SOURCE_KEY VARCHAR2(128 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    SOURCE_TYPE VARCHAR2(32 CHAR) NOT NULL,
    ENDPOINT VARCHAR2(2048 CHAR),
    SECRET_REF VARCHAR2(1024 CHAR),
    WEBHOOK_SECRET_REF VARCHAR2(1024 CHAR),
    TLS_PROFILE_REF VARCHAR2(1024 CHAR),
    WEBHOOK_KEY_HASH VARCHAR2(64 CHAR),
    PREVIOUS_WEBHOOK_KEY_HASH VARCHAR2(64 CHAR),
    PREVIOUS_WEBHOOK_KEY_EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    CAPABILITIES_JSON CLOB,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DISABLED' NOT NULL,
    HEALTH_STATUS VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    HEALTH_CHECK_REQUEST_ID RAW(16),
    HEALTH_CHECK_REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_HEALTH_CHECK_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_ERROR_CODE VARCHAR2(128 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    HEALTH_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_MONITOR_SOURCE_KEY
        UNIQUE (APP_ID, DOMAIN_ID, SOURCE_KEY),
    CONSTRAINT FK_OPS_MONITOR_DOMAIN
        FOREIGN KEY (DOMAIN_ID, APP_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID, APP_ID),
    CONSTRAINT CK_OPS_MONITOR_ROUTE
        CHECK (ENDPOINT IS NOT NULL OR WEBHOOK_KEY_HASH IS NOT NULL),
    CONSTRAINT CK_OPS_MONITOR_PREV_KEY CHECK (
        (PREVIOUS_WEBHOOK_KEY_HASH IS NULL
         AND PREVIOUS_WEBHOOK_KEY_EXPIRES_AT IS NULL)
        OR
        (PREVIOUS_WEBHOOK_KEY_HASH IS NOT NULL
         AND PREVIOUS_WEBHOOK_KEY_EXPIRES_AT IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_MONITOR_HEALTH_REQ CHECK (
        (HEALTH_CHECK_REQUEST_ID IS NULL
         AND HEALTH_CHECK_REQUESTED_AT IS NULL)
        OR
        (HEALTH_CHECK_REQUEST_ID IS NOT NULL
         AND HEALTH_CHECK_REQUESTED_AT IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_MONITOR_STATUS
        CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_OPS_MONITOR_HEALTH CHECK (
        HEALTH_STATUS IN ('UNKNOWN', 'HEALTHY', 'DEGRADED', 'UNREACHABLE')
    ),
    CONSTRAINT CK_OPS_MONITOR_VERSION
        CHECK (ROW_VERSION >= 1 AND HEALTH_VERSION >= 1),
    CONSTRAINT CK_OPS_MONITOR_CAPS_JSON CHECK (CAPABILITIES_JSON IS JSON)
);

CREATE UNIQUE INDEX UX_OPS_MONITOR_WEBHOOK
    ON KBOT_OPS_MONITOR_SOURCE (WEBHOOK_KEY_HASH);
CREATE UNIQUE INDEX UX_OPS_MONITOR_PREV_WEBHOOK
    ON KBOT_OPS_MONITOR_SOURCE (PREVIOUS_WEBHOOK_KEY_HASH);
CREATE INDEX IX_OPS_MONITOR_SCOPE
    ON KBOT_OPS_MONITOR_SOURCE
       (APP_ID, DOMAIN_ID, SOURCE_TYPE, STATUS);
CREATE INDEX IX_OPS_MONITOR_DOMAIN
    ON KBOT_OPS_MONITOR_SOURCE (DOMAIN_ID, APP_ID);
CREATE INDEX IX_OPS_MONITOR_HEALTH
    ON KBOT_OPS_MONITOR_SOURCE (HEALTH_STATUS, LAST_HEALTH_CHECK_AT);
CREATE INDEX IX_OPS_MONITOR_HEALTH_REQ
    ON KBOT_OPS_MONITOR_SOURCE (HEALTH_CHECK_REQUEST_ID);

CREATE TABLE KBOT_OPS_TARGET_MONITOR (
    TARGET_MONITOR_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    MONITOR_SOURCE_ID RAW(16) NOT NULL,
    EXTERNAL_TARGET_KEY VARCHAR2(256 CHAR) NOT NULL,
    ROLE VARCHAR2(16 CHAR) DEFAULT 'PRIMARY' NOT NULL,
    PRIORITY NUMBER(8) DEFAULT 100 NOT NULL,
    METRIC_SCOPE_JSON CLOB,
    MAPPING_OVERRIDES_JSON CLOB,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    HEALTH_STATUS VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    LAST_HEALTH_CHECK_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_ERROR_CODE VARCHAR2(128 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    HEALTH_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_TARGET_MONITOR_EXT
        UNIQUE (MONITOR_SOURCE_ID, EXTERNAL_TARGET_KEY),
    CONSTRAINT FK_OPS_TMON_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_TMON_MONITOR
        FOREIGN KEY (MONITOR_SOURCE_ID)
        REFERENCES KBOT_OPS_MONITOR_SOURCE (MONITOR_SOURCE_ID),
    CONSTRAINT CK_OPS_TMON_ROLE
        CHECK (ROLE IN ('PRIMARY', 'SUPPLEMENTARY')),
    CONSTRAINT CK_OPS_TMON_PRIORITY CHECK (PRIORITY >= 0),
    CONSTRAINT CK_OPS_TMON_STATUS
        CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_OPS_TMON_HEALTH CHECK (
        HEALTH_STATUS IN ('UNKNOWN', 'HEALTHY', 'DEGRADED', 'UNREACHABLE')
    ),
    CONSTRAINT CK_OPS_TMON_VERSION
        CHECK (ROW_VERSION >= 1 AND HEALTH_VERSION >= 1),
    CONSTRAINT CK_OPS_TMON_METRIC_JSON CHECK (METRIC_SCOPE_JSON IS JSON),
    CONSTRAINT CK_OPS_TMON_MAPPING_JSON
        CHECK (MAPPING_OVERRIDES_JSON IS JSON)
);

CREATE INDEX IX_OPS_TMON_TARGET
    ON KBOT_OPS_TARGET_MONITOR (TARGET_ID, STATUS, PRIORITY);
CREATE INDEX IX_OPS_TMON_MONITOR
    ON KBOT_OPS_TARGET_MONITOR (MONITOR_SOURCE_ID, STATUS);

COMMENT ON COLUMN KBOT_OPS_TARGET.TARGET_ID IS
    '应用生成的 UUIDv7；API 使用规范 UUID 字符串';
COMMENT ON COLUMN KBOT_OPS_TARGET.ENDPOINT_JSON IS
    '仅保存连接端点元数据，不保存用户名、密码或 Token';
COMMENT ON COLUMN KBOT_OPS_MONITOR_SOURCE.WEBHOOK_KEY_HASH IS
    '外部 Webhook 不透明路由键的 SHA-256，不保存明文';
