-- KBot 4.0 AIOps：信号事件、故障情境、Run、Task、Artifact 与用户事件流。

CREATE TABLE KBOT_OPS_SIGNAL_EVENT (
    SIGNAL_EVENT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16),
    DIAGNOSTIC_SOURCE_ID RAW(16) NOT NULL,
    SOURCE_BINDING_ID RAW(16),
    SOURCE_INBOX_ID RAW(16),
    SOURCE_EVENT_KEY VARCHAR2(512 CHAR) NOT NULL,
    SIGNAL_KIND VARCHAR2(32 CHAR) NOT NULL,
    EVENT_CLASS VARCHAR2(128 CHAR) NOT NULL,
    SEVERITY VARCHAR2(16 CHAR) NOT NULL,
    NORMALIZED_STATUS VARCHAR2(16 CHAR) NOT NULL,
    SOURCE_STATUS VARCHAR2(128 CHAR),
    SUMMARY VARCHAR2(1000 CHAR),
    OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    RECEIVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP(6) WITH TIME ZONE,
    DEDUP_HASH VARCHAR2(64 CHAR) NOT NULL,
    PAYLOAD_JSON JSON,
    PAYLOAD_URI VARCHAR2(2048 CHAR),
    PAYLOAD_HASH VARCHAR2(64 CHAR) NOT NULL,
    EVIDENCE_LOCATOR_JSON JSON,
    NORMALIZER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PROCESSING_STATUS VARCHAR2(16 CHAR) DEFAULT 'RECEIVED' NOT NULL,
    TRACE_ID VARCHAR2(128 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_SIG_SOURCE
        UNIQUE (DIAGNOSTIC_SOURCE_ID, SOURCE_EVENT_KEY),
    CONSTRAINT FK_OPS_SIG_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_SIG_DOMAIN
        FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_SIG_SOURCE
        FOREIGN KEY (DIAGNOSTIC_SOURCE_ID)
        REFERENCES KBOT_OPS_DIAGNOSTIC_SOURCE (DIAGNOSTIC_SOURCE_ID),
    CONSTRAINT FK_OPS_SIG_BINDING
        FOREIGN KEY (SOURCE_BINDING_ID)
        REFERENCES KBOT_OPS_TARGET_SOURCE_BINDING (TARGET_SOURCE_BINDING_ID),
    CONSTRAINT CK_OPS_SIG_SEVERITY
        CHECK (SEVERITY IN ('INFO', 'WARNING', 'HIGH', 'CRITICAL')),
    CONSTRAINT CK_OPS_SIG_KIND CHECK (
        SIGNAL_KIND IN ('FAULT', 'RECOVERY', 'RISK', 'CHANGE', 'INFORMATIONAL')
    ),
    CONSTRAINT CK_OPS_SIG_STATUS CHECK (
        NORMALIZED_STATUS IN ('OPEN', 'UPDATED', 'RESOLVED', 'INFORMATIONAL')
    ),
    CONSTRAINT CK_OPS_SIG_PROCESSING CHECK (
        PROCESSING_STATUS IN ('RECEIVED', 'CORRELATED', 'IGNORED', 'FAILED')
    ),
    CONSTRAINT CK_OPS_SIG_PAYLOAD
        CHECK (PAYLOAD_JSON IS NOT NULL OR PAYLOAD_URI IS NOT NULL),
    CONSTRAINT CK_OPS_SIG_HASHES CHECK (
        LENGTH(DEDUP_HASH) = 64 AND LENGTH(PAYLOAD_HASH) = 64
    )
);

CREATE INDEX IX_OPS_SIG_TARGET_TIME
    ON KBOT_OPS_SIGNAL_EVENT (TARGET_ID, OCCURRED_AT);
CREATE INDEX IX_OPS_SIG_PROCESSING
    ON KBOT_OPS_SIGNAL_EVENT (PROCESSING_STATUS, RECEIVED_AT);
CREATE INDEX IX_OPS_SIG_CORRELATE
    ON KBOT_OPS_SIGNAL_EVENT (TARGET_ID, DEDUP_HASH, NORMALIZED_STATUS);
CREATE INDEX IX_OPS_SIG_INBOX
    ON KBOT_OPS_SIGNAL_EVENT (SOURCE_INBOX_ID);

CREATE TABLE KBOT_OPS_SITUATION (
    SITUATION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    SITUATION_TYPE VARCHAR2(128 CHAR) NOT NULL,
    TITLE VARCHAR2(512 CHAR) NOT NULL,
    SUMMARY VARCHAR2(2000 CHAR),
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    SEVERITY VARCHAR2(16 CHAR) NOT NULL,
    CORRELATION_KEY VARCHAR2(256 CHAR) NOT NULL,
    CORRELATION_HASH VARCHAR2(64 CHAR) NOT NULL,
    CORRELATION_VERSION VARCHAR2(64 CHAR) NOT NULL,
    CORRELATION_JSON JSON,
    FIRST_OBSERVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    LAST_OBSERVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ACKNOWLEDGED_AT TIMESTAMP(6) WITH TIME ZONE,
    ACKNOWLEDGED_BY VARCHAR2(256 CHAR),
    RESOLVED_AT TIMESTAMP(6) WITH TIME ZONE,
    CLOSED_AT TIMESTAMP(6) WITH TIME ZONE,
    EVENT_COUNT NUMBER(19) DEFAULT 1 NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_SITUATION_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_SITUATION_DOMAIN
        FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_OPS_SITUATION_STATUS CHECK (
        STATUS IN (
            'OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'DIAGNOSED', 'MITIGATING',
            'OBSERVING', 'RESOLVED', 'CLOSED', 'SUPPRESSED'
        )
    ),
    CONSTRAINT CK_OPS_SITUATION_SEVERITY
        CHECK (SEVERITY IN ('INFO', 'WARNING', 'HIGH', 'CRITICAL')),
    CONSTRAINT CK_OPS_SITUATION_COUNTER
        CHECK (EVENT_COUNT >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_SITUATION_HASH CHECK (LENGTH(CORRELATION_HASH) = 64)
);

CREATE INDEX IX_OPS_SITUATION_QUERY
    ON KBOT_OPS_SITUATION (TARGET_ID, STATUS, SEVERITY, LAST_OBSERVED_AT);

CREATE TABLE KBOT_OPS_SITUATION_EVENT (
    SITUATION_EVENT_ID RAW(16) PRIMARY KEY,
    SITUATION_ID RAW(16) NOT NULL,
    SIGNAL_EVENT_ID RAW(16) NOT NULL,
    RELATION_TYPE VARCHAR2(16 CHAR) NOT NULL,
    CORRELATION_METHOD VARCHAR2(32 CHAR) NOT NULL,
    CORRELATION_SCORE NUMBER(8,6),
    CORRELATION_DETAIL_JSON JSON,
    ATTACHED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATTACHED_BY VARCHAR2(256 CHAR) NOT NULL,
    CONSTRAINT UK_OPS_SITUATION_EVENT UNIQUE (SITUATION_ID, SIGNAL_EVENT_ID),
    CONSTRAINT FK_OPS_SITEVT_SITUATION FOREIGN KEY (SITUATION_ID)
        REFERENCES KBOT_OPS_SITUATION (SITUATION_ID),
    CONSTRAINT FK_OPS_SITEVT_SIGNAL FOREIGN KEY (SIGNAL_EVENT_ID)
        REFERENCES KBOT_OPS_SIGNAL_EVENT (SIGNAL_EVENT_ID),
    CONSTRAINT CK_OPS_SITEVT_RELATION CHECK (
        RELATION_TYPE IN ('TRIGGER', 'RELATED', 'RECOVERY', 'CHANGE')
    ),
    CONSTRAINT CK_OPS_SITEVT_METHOD CHECK (
        CORRELATION_METHOD IN ('EXACT', 'RULE', 'TOPOLOGY', 'MODEL', 'MANUAL')
    )
);
CREATE INDEX IX_OPS_SITEVT_SIGNAL ON KBOT_OPS_SITUATION_EVENT (SIGNAL_EVENT_ID);

CREATE TABLE KBOT_OPS_RUN (
    OPS_RUN_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    AGENT_VERSION_ID RAW(16) NOT NULL,
    PARENT_AGENT_RUN_ID RAW(16),
    PARENT_DELEGATION_ID RAW(16),
    TRIGGER_TYPE VARCHAR2(16 CHAR) NOT NULL,
    TRIGGER_SIGNAL_EVENT_ID RAW(16),
    SITUATION_ID RAW(16),
    INTERACTION_MODE VARCHAR2(16 CHAR) NOT NULL,
    WORKFLOW_KIND VARCHAR2(24 CHAR) NOT NULL,
    INSPECTION_FIRE_ID RAW(16),
    SOURCE_PROPOSAL_ID RAW(16),
    SOURCE_RESULT_ARTIFACT_ID RAW(16),
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    ORIGINAL_REQUEST CLOB,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    PLAN_SNAPSHOT_JSON JSON,
    POLICY_SNAPSHOT_JSON JSON,
    FINAL_ARTIFACT_ID RAW(16),
    DEADLINE_AT TIMESTAMP(6) WITH TIME ZONE,
    CANCEL_REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE,
    CANCEL_REQUESTED_BY VARCHAR2(256 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_RUN_IDEMP UNIQUE (
        TARGET_ID, TRIGGER_TYPE, ACTOR_ID, IDEMPOTENCY_KEY
    ),
    CONSTRAINT UK_OPS_RUN_DELEGATION UNIQUE (PARENT_DELEGATION_ID),
    CONSTRAINT FK_OPS_RUN_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_RUN_SIGNAL
        FOREIGN KEY (TRIGGER_SIGNAL_EVENT_ID)
        REFERENCES KBOT_OPS_SIGNAL_EVENT (SIGNAL_EVENT_ID),
    CONSTRAINT FK_OPS_RUN_SITUATION
        FOREIGN KEY (SITUATION_ID) REFERENCES KBOT_OPS_SITUATION (SITUATION_ID),
    CONSTRAINT CK_OPS_RUN_PARENT CHECK (
        (PARENT_AGENT_RUN_ID IS NULL AND PARENT_DELEGATION_ID IS NULL)
        OR
        (PARENT_AGENT_RUN_ID IS NOT NULL AND PARENT_DELEGATION_ID IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_RUN_TRIGGER CHECK (
        TRIGGER_TYPE IN (
            'CHAT', 'API', 'ROOT', 'ALERT', 'SCHEDULE', 'IM', 'EMAIL'
        )
    ),
    CONSTRAINT CK_OPS_RUN_INTERACTION CHECK (
        INTERACTION_MODE IN ('INTERACTIVE', 'AUTONOMOUS')
    ),
    CONSTRAINT CK_OPS_RUN_WORKFLOW CHECK (
        WORKFLOW_KIND IN (
            'ALERT_DIAGNOSIS', 'INSPECTION', 'CHAT_TURN',
            'CHANGE', 'VERIFICATION'
        )
    ),
    CONSTRAINT CK_OPS_RUN_STATUS CHECK (
        STATUS IN (
            'CREATED', 'QUEUED', 'RUNNING', 'WAITING_INPUT',
            'WAITING_APPROVAL', 'COMPLETED', 'PARTIAL',
            'FAILED', 'CANCELLED', 'EXPIRED'
        )
    ),
    CONSTRAINT CK_OPS_RUN_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_OPS_RUN_TARGET
    ON KBOT_OPS_RUN (TARGET_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_RUN_AGENT
    ON KBOT_OPS_RUN (AGENT_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_RUN_AGENT_VERSION
    ON KBOT_OPS_RUN (AGENT_VERSION_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_RUN_PARENT
    ON KBOT_OPS_RUN (PARENT_AGENT_RUN_ID);
CREATE INDEX IX_OPS_RUN_SOURCE_PROPOSAL
    ON KBOT_OPS_RUN (SOURCE_PROPOSAL_ID);
CREATE INDEX IX_OPS_RUN_SITUATION
    ON KBOT_OPS_RUN (SITUATION_ID, STATUS);
CREATE INDEX IX_OPS_RUN_FIRE
    ON KBOT_OPS_RUN (INSPECTION_FIRE_ID, STATUS);
CREATE INDEX IX_OPS_RUN_SIGNAL
    ON KBOT_OPS_RUN (TRIGGER_SIGNAL_EVENT_ID);

CREATE UNIQUE INDEX UX_OPS_RUN_FIRE_TARGET ON KBOT_OPS_RUN (
    CASE WHEN INSPECTION_FIRE_ID IS NOT NULL THEN INSPECTION_FIRE_ID END,
    CASE WHEN INSPECTION_FIRE_ID IS NOT NULL THEN TARGET_ID END
);

CREATE TABLE KBOT_OPS_TASK (
    OPS_TASK_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    PARENT_TASK_ID RAW(16),
    TASK_KEY VARCHAR2(128 CHAR) NOT NULL,
    TASK_TYPE VARCHAR2(24 CHAR) NOT NULL,
    HANDLER_ID VARCHAR2(128 CHAR) NOT NULL,
    HANDLER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    INPUT_SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    OUTPUT_SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    DEPENDS_ON_JSON JSON,
    INPUT_ARTIFACTS_JSON JSON,
    OUTPUT_ARTIFACT_ID RAW(16),
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    PRIORITY NUMBER(8) DEFAULT 100 NOT NULL,
    AVAILABLE_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATTEMPT_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    MAX_ATTEMPTS NUMBER(8) DEFAULT 3 NOT NULL,
    TIMEOUT_SECONDS NUMBER(10) NOT NULL,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    HEARTBEAT_AT TIMESTAMP(6) WITH TIME ZONE,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_TASK_KEY UNIQUE (OPS_RUN_ID, TASK_KEY),
    CONSTRAINT FK_OPS_TASK_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_TASK_PARENT
        FOREIGN KEY (PARENT_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT CK_OPS_TASK_TYPE CHECK (
        TASK_TYPE IN (
            'CONTEXT_BUILD', 'PLAYBOOK_INVOKE', 'TOOL_INVOKE',
            'EVIDENCE_ASSESS', 'ACTION_PLAN', 'PROPOSAL',
            'ANSWER', 'REQUEST_INPUT', 'APPROVE', 'EXECUTE',
            'VERIFY', 'ROLLBACK', 'REPORT'
        )
    ),
    CONSTRAINT CK_OPS_TASK_STATUS CHECK (
        STATUS IN (
            'PENDING', 'READY', 'BLOCKED', 'RUNNING', 'WAITING_INPUT',
            'WAITING_APPROVAL', 'RETRY_WAIT', 'SUCCEEDED',
            'FAILED', 'CANCELLED', 'EXPIRED'
        )
    ),
    CONSTRAINT CK_OPS_TASK_NUMBERS CHECK (
        PRIORITY >= 0 AND ATTEMPT_COUNT >= 0 AND MAX_ATTEMPTS >= 1
        AND ATTEMPT_COUNT <= MAX_ATTEMPTS AND TIMEOUT_SECONDS >= 1
        AND ROW_VERSION >= 1
    ),
    CONSTRAINT CK_OPS_TASK_LEASE CHECK (
        (STATUS = 'RUNNING' AND LEASE_OWNER IS NOT NULL
         AND LEASE_TOKEN IS NOT NULL AND LEASE_UNTIL IS NOT NULL)
        OR
        (STATUS <> 'RUNNING' AND LEASE_OWNER IS NULL
         AND LEASE_TOKEN IS NULL AND LEASE_UNTIL IS NULL)
    )
);

CREATE INDEX IX_OPS_TASK_CLAIM
    ON KBOT_OPS_TASK (STATUS, AVAILABLE_AT, PRIORITY);
CREATE INDEX IX_OPS_TASK_LEASE
    ON KBOT_OPS_TASK (STATUS, LEASE_UNTIL);
CREATE INDEX IX_OPS_TASK_RUN
    ON KBOT_OPS_TASK (OPS_RUN_ID, STATUS);
CREATE INDEX IX_OPS_TASK_PARENT
    ON KBOT_OPS_TASK (PARENT_TASK_ID);

CREATE TABLE KBOT_OPS_ARTIFACT (
    ARTIFACT_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16),
    ARTIFACT_KEY VARCHAR2(256 CHAR) NOT NULL,
    ARTIFACT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PAYLOAD_JSON JSON,
    PAYLOAD_URI VARCHAR2(2048 CHAR),
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    BYTE_SIZE NUMBER(19) NOT NULL,
    PROVENANCE_JSON JSON NOT NULL,
    TRUST_LEVEL VARCHAR2(24 CHAR) NOT NULL,
    SECURITY_LEVEL NUMBER(3) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_ARTIFACT_KEY UNIQUE (OPS_RUN_ID, ARTIFACT_KEY),
    CONSTRAINT FK_OPS_ARTIFACT_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_ARTIFACT_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT CK_OPS_ARTIFACT_PAYLOAD
        CHECK (PAYLOAD_JSON IS NOT NULL OR PAYLOAD_URI IS NOT NULL),
    CONSTRAINT CK_OPS_ARTIFACT_TRUST CHECK (
        TRUST_LEVEL IN (
            'SOURCE_VERIFIED', 'USER_PROVIDED',
            'KNOWLEDGE_CITATION', 'MODEL_INFERENCE'
        )
    ),
    CONSTRAINT CK_OPS_ARTIFACT_SIZE
        CHECK (BYTE_SIZE >= 0 AND SECURITY_LEVEL >= 0),
    CONSTRAINT CK_OPS_ARTIFACT_HASH CHECK (LENGTH(CONTENT_HASH) = 64)
);

CREATE INDEX IX_OPS_ARTIFACT_RUN_TYPE
    ON KBOT_OPS_ARTIFACT (OPS_RUN_ID, ARTIFACT_TYPE, CREATED_AT);
CREATE INDEX IX_OPS_ARTIFACT_TASK
    ON KBOT_OPS_ARTIFACT (OPS_TASK_ID);
CREATE INDEX IX_OPS_ARTIFACT_HASH
    ON KBOT_OPS_ARTIFACT (CONTENT_HASH);

CREATE TABLE KBOT_OPS_RUN_EVENT (
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16),
    SEQUENCE_NO NUMBER(19) NOT NULL,
    EVENT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    EVENT_KEY VARCHAR2(128 CHAR),
    VISIBILITY VARCHAR2(16 CHAR) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_OPS_RUN_EVENT PRIMARY KEY (OPS_RUN_ID, SEQUENCE_NO),
    CONSTRAINT FK_OPS_RUN_EVENT_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_RUN_EVENT_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT CK_OPS_RUN_EVENT_SEQ CHECK (SEQUENCE_NO >= 1),
    CONSTRAINT CK_OPS_RUN_EVENT_VISIBLE
        CHECK (VISIBILITY IN ('INTERNAL', 'USER'))
);

CREATE UNIQUE INDEX UX_OPS_RUN_EVENT_KEY ON KBOT_OPS_RUN_EVENT (
    CASE WHEN EVENT_KEY IS NOT NULL THEN OPS_RUN_ID END,
    CASE WHEN EVENT_KEY IS NOT NULL THEN EVENT_KEY END
);
CREATE INDEX IX_OPS_RUN_EVENT_SSE
    ON KBOT_OPS_RUN_EVENT (OPS_RUN_ID, VISIBILITY, SEQUENCE_NO);
CREATE INDEX IX_OPS_RUN_EVENT_TASK
    ON KBOT_OPS_RUN_EVENT (OPS_TASK_ID);

COMMENT ON COLUMN KBOT_OPS_SIGNAL_EVENT.SOURCE_INBOX_ID IS
    '可靠消息 Inbox 的软审计引用；Inbox 可先于历史事件清理';
COMMENT ON COLUMN KBOT_OPS_RUN.AGENT_ID IS
    'Agent Runtime 的跨服务 UUID；不创建跨服务数据库外键';
COMMENT ON COLUMN KBOT_OPS_RUN_EVENT.VISIBILITY IS
    '仅 USER 事件可进入面向用户的 SSE 流';
