-- KBot 4.0 AIOps：外部事件、告警、Run、Task、Artifact 与用户事件流。

CREATE TABLE KBOT_OPS_EVENT (
    EVENT_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    MONITOR_SOURCE_ID RAW(16) NOT NULL,
    ALERT_ID RAW(16),
    SOURCE_INBOX_ID RAW(16),
    SOURCE_EVENT_KEY VARCHAR2(256 CHAR) NOT NULL,
    EVENT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    SEVERITY VARCHAR2(16 CHAR) NOT NULL,
    EVENT_STATUS VARCHAR2(16 CHAR) NOT NULL,
    OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    RECEIVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
    PAYLOAD_JSON CLOB,
    PAYLOAD_URI VARCHAR2(2048 CHAR),
    PAYLOAD_HASH VARCHAR2(64 CHAR) NOT NULL,
    NORMALIZER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PROCESSING_STATUS VARCHAR2(16 CHAR) DEFAULT 'RECEIVED' NOT NULL,
    TRACE_ID VARCHAR2(128 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_EVENT_SOURCE
        UNIQUE (MONITOR_SOURCE_ID, SOURCE_EVENT_KEY),
    CONSTRAINT FK_OPS_EVENT_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_EVENT_MONITOR
        FOREIGN KEY (MONITOR_SOURCE_ID)
        REFERENCES KBOT_OPS_MONITOR_SOURCE (MONITOR_SOURCE_ID),
    CONSTRAINT CK_OPS_EVENT_SEVERITY
        CHECK (SEVERITY IN ('INFO', 'WARNING', 'HIGH', 'CRITICAL')),
    CONSTRAINT CK_OPS_EVENT_STATUS
        CHECK (EVENT_STATUS IN ('FIRING', 'RESOLVED', 'INFORMATIONAL')),
    CONSTRAINT CK_OPS_EVENT_PROCESSING CHECK (
        PROCESSING_STATUS IN ('RECEIVED', 'CORRELATED', 'IGNORED', 'FAILED')
    ),
    CONSTRAINT CK_OPS_EVENT_PAYLOAD
        CHECK (PAYLOAD_JSON IS NOT NULL OR PAYLOAD_URI IS NOT NULL),
    CONSTRAINT CK_OPS_EVENT_PAYLOAD_JSON CHECK (PAYLOAD_JSON IS JSON),
    CONSTRAINT CK_OPS_EVENT_HASHES CHECK (
        LENGTH(FINGERPRINT) = 64 AND LENGTH(PAYLOAD_HASH) = 64
    )
);

CREATE INDEX IX_OPS_EVENT_TARGET_TIME
    ON KBOT_OPS_EVENT (TARGET_ID, OCCURRED_AT);
CREATE INDEX IX_OPS_EVENT_PROCESSING
    ON KBOT_OPS_EVENT (PROCESSING_STATUS, RECEIVED_AT);
CREATE INDEX IX_OPS_EVENT_CORRELATE
    ON KBOT_OPS_EVENT (TARGET_ID, FINGERPRINT, EVENT_STATUS);
CREATE INDEX IX_OPS_EVENT_INBOX
    ON KBOT_OPS_EVENT (SOURCE_INBOX_ID);

CREATE TABLE KBOT_OPS_ALERT (
    ALERT_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    SEVERITY VARCHAR2(16 CHAR) NOT NULL,
    SUMMARY VARCHAR2(1000 CHAR) NOT NULL,
    CORRELATION_JSON CLOB,
    FIRST_SEEN_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    LAST_SEEN_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    RESOLVED_AT TIMESTAMP(6) WITH TIME ZONE,
    EVENT_COUNT NUMBER(19) DEFAULT 1 NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_ALERT_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT CK_OPS_ALERT_STATUS CHECK (
        STATUS IN (
            'OPEN', 'ACKNOWLEDGED', 'SUPPRESSED', 'RESOLVED', 'CLOSED'
        )
    ),
    CONSTRAINT CK_OPS_ALERT_SEVERITY
        CHECK (SEVERITY IN ('INFO', 'WARNING', 'HIGH', 'CRITICAL')),
    CONSTRAINT CK_OPS_ALERT_COUNTER
        CHECK (EVENT_COUNT >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_ALERT_HASH CHECK (LENGTH(FINGERPRINT) = 64),
    CONSTRAINT CK_OPS_ALERT_CORR_JSON CHECK (CORRELATION_JSON IS JSON)
);

CREATE INDEX IX_OPS_ALERT_QUERY
    ON KBOT_OPS_ALERT (TARGET_ID, STATUS, SEVERITY, LAST_SEEN_AT);

CREATE TABLE KBOT_OPS_RUN (
    OPS_RUN_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    PARENT_AGENT_RUN_ID RAW(16),
    PARENT_DELEGATION_ID RAW(16),
    TRIGGER_TYPE VARCHAR2(16 CHAR) NOT NULL,
    TRIGGER_EVENT_ID RAW(16),
    TRIGGER_ALERT_ID RAW(16),
    INSPECTION_FIRE_ID RAW(16),
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    ORIGINAL_REQUEST CLOB,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    PLAN_SNAPSHOT_JSON CLOB,
    POLICY_SNAPSHOT_JSON CLOB,
    ROOT_CAUSE_LEVEL VARCHAR2(16 CHAR),
    FINAL_ARTIFACT_ID RAW(16),
    DEADLINE_AT TIMESTAMP(6) WITH TIME ZONE,
    CANCEL_REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE,
    CANCEL_REQUESTED_BY VARCHAR2(256 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_RUN_IDEMP UNIQUE (
        TARGET_ID, TRIGGER_TYPE, ACTOR_ID, IDEMPOTENCY_KEY
    ),
    CONSTRAINT UK_OPS_RUN_DELEGATION UNIQUE (PARENT_DELEGATION_ID),
    CONSTRAINT FK_OPS_RUN_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_RUN_EVENT
        FOREIGN KEY (TRIGGER_EVENT_ID) REFERENCES KBOT_OPS_EVENT (EVENT_ID),
    CONSTRAINT FK_OPS_RUN_ALERT
        FOREIGN KEY (TRIGGER_ALERT_ID) REFERENCES KBOT_OPS_ALERT (ALERT_ID),
    CONSTRAINT CK_OPS_RUN_PARENT CHECK (
        (PARENT_AGENT_RUN_ID IS NULL AND PARENT_DELEGATION_ID IS NULL)
        OR
        (PARENT_AGENT_RUN_ID IS NOT NULL AND PARENT_DELEGATION_ID IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_RUN_TRIGGER CHECK (
        TRIGGER_TYPE IN (
            'CHAT', 'API', 'ROOT', 'ALERT', 'SCHEDULE', 'IM', 'EMAIL'
        )
    ),
    CONSTRAINT CK_OPS_RUN_STATUS CHECK (
        STATUS IN (
            'CREATED', 'SCOPING', 'OBSERVING', 'DIAGNOSING',
            'WAITING_INPUT', 'DIAGNOSED', 'PROPOSING',
            'WAITING_APPROVAL', 'EXECUTING', 'VERIFYING',
            'ROLLBACK_PENDING', 'COMPLETED', 'DEGRADED', 'REJECTED',
            'FAILED', 'CANCELLED', 'EXPIRED'
        )
    ),
    CONSTRAINT CK_OPS_RUN_CAUSE CHECK (
        ROOT_CAUSE_LEVEL IS NULL OR ROOT_CAUSE_LEVEL IN (
            'CONFIRMED', 'PROBABLE', 'POSSIBLE', 'INCONCLUSIVE'
        )
    ),
    CONSTRAINT CK_OPS_RUN_VERSION CHECK (ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_RUN_PLAN_JSON CHECK (PLAN_SNAPSHOT_JSON IS JSON),
    CONSTRAINT CK_OPS_RUN_POLICY_JSON CHECK (POLICY_SNAPSHOT_JSON IS JSON)
);

CREATE INDEX IX_OPS_RUN_TARGET
    ON KBOT_OPS_RUN (TARGET_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_RUN_AGENT
    ON KBOT_OPS_RUN (AGENT_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_RUN_PARENT
    ON KBOT_OPS_RUN (PARENT_AGENT_RUN_ID);
CREATE INDEX IX_OPS_RUN_ALERT
    ON KBOT_OPS_RUN (TRIGGER_ALERT_ID, STATUS);
CREATE INDEX IX_OPS_RUN_FIRE
    ON KBOT_OPS_RUN (INSPECTION_FIRE_ID, STATUS);
CREATE INDEX IX_OPS_RUN_EVENT
    ON KBOT_OPS_RUN (TRIGGER_EVENT_ID);

CREATE UNIQUE INDEX UX_OPS_RUN_FIRE_TARGET ON KBOT_OPS_RUN (
    CASE WHEN INSPECTION_FIRE_ID IS NOT NULL THEN INSPECTION_FIRE_ID END,
    CASE WHEN INSPECTION_FIRE_ID IS NOT NULL THEN TARGET_ID END
);

CREATE TABLE KBOT_OPS_TASK (
    OPS_TASK_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    PARENT_TASK_ID RAW(16),
    TASK_KEY VARCHAR2(128 CHAR) NOT NULL,
    TASK_TYPE VARCHAR2(24 CHAR) NOT NULL,
    HANDLER_ID VARCHAR2(128 CHAR) NOT NULL,
    HANDLER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    INPUT_SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    OUTPUT_SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    DEPENDS_ON_JSON CLOB,
    INPUT_ARTIFACTS_JSON CLOB,
    OUTPUT_ARTIFACT_ID RAW(16),
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    PRIORITY NUMBER(8) DEFAULT 100 NOT NULL,
    AVAILABLE_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATTEMPT_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    MAX_ATTEMPTS NUMBER(8) DEFAULT 3 NOT NULL,
    TIMEOUT_SECONDS NUMBER(10) NOT NULL,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    HEARTBEAT_AT TIMESTAMP(6) WITH TIME ZONE,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_TASK_KEY UNIQUE (OPS_RUN_ID, TASK_KEY),
    CONSTRAINT FK_OPS_TASK_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_TASK_PARENT
        FOREIGN KEY (PARENT_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT CK_OPS_TASK_TYPE CHECK (
        TASK_TYPE IN (
            'SCOPE', 'OBSERVE', 'DIAGNOSE', 'REQUEST_INPUT',
            'PROPOSE', 'APPROVE', 'EXECUTE', 'VERIFY',
            'ROLLBACK', 'COMPARE', 'REPORT'
        )
    ),
    CONSTRAINT CK_OPS_TASK_STATUS CHECK (
        STATUS IN (
            'PENDING', 'READY', 'BLOCKED', 'RUNNING', 'WAITING_INPUT',
            'WAITING_APPROVAL', 'RETRY_WAIT', 'SUCCEEDED',
            'FAILED', 'CANCELLED', 'EXPIRED'
        )
    ),
    CONSTRAINT CK_OPS_TASK_NUMBERS CHECK (
        PRIORITY >= 0 AND ATTEMPT_COUNT >= 0 AND MAX_ATTEMPTS >= 1
        AND ATTEMPT_COUNT <= MAX_ATTEMPTS AND TIMEOUT_SECONDS >= 1
        AND ROW_VERSION >= 1
    ),
    CONSTRAINT CK_OPS_TASK_LEASE CHECK (
        (STATUS = 'RUNNING' AND LEASE_OWNER IS NOT NULL
         AND LEASE_TOKEN IS NOT NULL AND LEASE_UNTIL IS NOT NULL)
        OR
        (STATUS <> 'RUNNING' AND LEASE_OWNER IS NULL
         AND LEASE_TOKEN IS NULL AND LEASE_UNTIL IS NULL)
    ),
    CONSTRAINT CK_OPS_TASK_DEPENDS_JSON CHECK (DEPENDS_ON_JSON IS JSON),
    CONSTRAINT CK_OPS_TASK_INPUT_JSON CHECK (INPUT_ARTIFACTS_JSON IS JSON)
);

CREATE INDEX IX_OPS_TASK_CLAIM
    ON KBOT_OPS_TASK (STATUS, AVAILABLE_AT, PRIORITY);
CREATE INDEX IX_OPS_TASK_LEASE
    ON KBOT_OPS_TASK (STATUS, LEASE_UNTIL);
CREATE INDEX IX_OPS_TASK_RUN
    ON KBOT_OPS_TASK (OPS_RUN_ID, STATUS);
CREATE INDEX IX_OPS_TASK_PARENT
    ON KBOT_OPS_TASK (PARENT_TASK_ID);

CREATE TABLE KBOT_OPS_ARTIFACT (
    ARTIFACT_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16),
    ARTIFACT_KEY VARCHAR2(256 CHAR) NOT NULL,
    ARTIFACT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PAYLOAD_JSON CLOB,
    PAYLOAD_URI VARCHAR2(2048 CHAR),
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    BYTE_SIZE NUMBER(19) NOT NULL,
    PROVENANCE_JSON CLOB NOT NULL,
    TRUST_LEVEL VARCHAR2(24 CHAR) NOT NULL,
    SECURITY_LEVEL NUMBER(3) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_ARTIFACT_KEY UNIQUE (OPS_RUN_ID, ARTIFACT_KEY),
    CONSTRAINT FK_OPS_ARTIFACT_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_ARTIFACT_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT CK_OPS_ARTIFACT_PAYLOAD
        CHECK (PAYLOAD_JSON IS NOT NULL OR PAYLOAD_URI IS NOT NULL),
    CONSTRAINT CK_OPS_ARTIFACT_PAYLOAD_JSON CHECK (PAYLOAD_JSON IS JSON),
    CONSTRAINT CK_OPS_ARTIFACT_PROV_JSON CHECK (PROVENANCE_JSON IS JSON),
    CONSTRAINT CK_OPS_ARTIFACT_TRUST CHECK (
        TRUST_LEVEL IN (
            'SOURCE_VERIFIED', 'USER_PROVIDED',
            'KNOWLEDGE_CITATION', 'MODEL_INFERENCE'
        )
    ),
    CONSTRAINT CK_OPS_ARTIFACT_SIZE
        CHECK (BYTE_SIZE >= 0 AND SECURITY_LEVEL >= 0),
    CONSTRAINT CK_OPS_ARTIFACT_HASH CHECK (LENGTH(CONTENT_HASH) = 64)
);

CREATE INDEX IX_OPS_ARTIFACT_RUN_TYPE
    ON KBOT_OPS_ARTIFACT (OPS_RUN_ID, ARTIFACT_TYPE, CREATED_AT);
CREATE INDEX IX_OPS_ARTIFACT_TASK
    ON KBOT_OPS_ARTIFACT (OPS_TASK_ID);
CREATE INDEX IX_OPS_ARTIFACT_HASH
    ON KBOT_OPS_ARTIFACT (CONTENT_HASH);

CREATE TABLE KBOT_OPS_RUN_EVENT (
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16),
    SEQUENCE_NO NUMBER(19) NOT NULL,
    EVENT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    EVENT_KEY VARCHAR2(128 CHAR),
    VISIBILITY VARCHAR2(16 CHAR) NOT NULL,
    PAYLOAD_JSON CLOB NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_OPS_RUN_EVENT PRIMARY KEY (OPS_RUN_ID, SEQUENCE_NO),
    CONSTRAINT FK_OPS_RUN_EVENT_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_RUN_EVENT_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT CK_OPS_RUN_EVENT_SEQ CHECK (SEQUENCE_NO >= 1),
    CONSTRAINT CK_OPS_RUN_EVENT_VISIBLE
        CHECK (VISIBILITY IN ('INTERNAL', 'USER')),
    CONSTRAINT CK_OPS_RUN_EVENT_JSON CHECK (PAYLOAD_JSON IS JSON)
);

CREATE UNIQUE INDEX UX_OPS_RUN_EVENT_KEY ON KBOT_OPS_RUN_EVENT (
    CASE WHEN EVENT_KEY IS NOT NULL THEN OPS_RUN_ID END,
    CASE WHEN EVENT_KEY IS NOT NULL THEN EVENT_KEY END
);
CREATE INDEX IX_OPS_RUN_EVENT_SSE
    ON KBOT_OPS_RUN_EVENT (OPS_RUN_ID, VISIBILITY, SEQUENCE_NO);
CREATE INDEX IX_OPS_RUN_EVENT_TASK
    ON KBOT_OPS_RUN_EVENT (OPS_TASK_ID);

COMMENT ON COLUMN KBOT_OPS_EVENT.SOURCE_INBOX_ID IS
    '可靠消息 Inbox 的软审计引用；Inbox 可先于历史事件清理';
COMMENT ON COLUMN KBOT_OPS_RUN.AGENT_ID IS
    'Agent Runtime 的跨服务 UUID；不创建跨服务数据库外键';
COMMENT ON COLUMN KBOT_OPS_RUN_EVENT.VISIBILITY IS
    '仅 USER 事件可进入面向用户的 SSE 流';
