-- KBot 4.0 AIOps：不可变变更建议、人工节点、审批授权和执行事实。

CREATE TABLE KBOT_OPS_CHANGE_PROPOSAL (
    PROPOSAL_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    SOLUTION_GROUP_KEY VARCHAR2(128 CHAR) NOT NULL,
    COMMAND_ORDINAL NUMBER(19) NOT NULL,
    PROPOSAL_VERSION NUMBER(19) NOT NULL,
    ACTION_TYPE VARCHAR2(32 CHAR) NOT NULL,
    ACTION_TEMPLATE_ID VARCHAR2(128 CHAR) NOT NULL,
    ACTION_TEMPLATE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    ACTION_TEMPLATE_HASH VARCHAR2(64 CHAR) NOT NULL,
    RENDERER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    COMMAND_HASH VARCHAR2(64 CHAR) NOT NULL,
    PARAMETERS_JSON CLOB NOT NULL,
    PARAMETERS_HASH VARCHAR2(64 CHAR) NOT NULL,
    RATIONALE CLOB NOT NULL,
    IMPACT_SCOPE_JSON CLOB,
    RISK_LEVEL VARCHAR2(16 CHAR) NOT NULL,
    PRECONDITIONS_JSON CLOB,
    ROLLBACK_PLAN_JSON CLOB,
    VERIFICATION_PLAN_JSON CLOB,
    EVIDENCE_ARTIFACTS_JSON CLOB,
    POLICY_DECISION_HASH VARCHAR2(64 CHAR) NOT NULL,
    PROPOSAL_HASH VARCHAR2(64 CHAR) NOT NULL,
    SNAPSHOT_ARTIFACT_ID RAW(16) NOT NULL,
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_BY_TASK_ID RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_PROPOSAL_VERSION UNIQUE (
        OPS_RUN_ID, SOLUTION_GROUP_KEY, COMMAND_ORDINAL, PROPOSAL_VERSION
    ),
    CONSTRAINT FK_OPS_PROPOSAL_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_PROPOSAL_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_PROPOSAL_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_PROPOSAL_CREATED_TASK
        FOREIGN KEY (CREATED_BY_TASK_ID)
        REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT CK_OPS_PROPOSAL_ORDINAL CHECK (
        COMMAND_ORDINAL >= 1 AND PROPOSAL_VERSION >= 1
    ),
    CONSTRAINT CK_OPS_PROPOSAL_RISK
        CHECK (RISK_LEVEL IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT CK_OPS_PROPOSAL_STATUS CHECK (
        STATUS IN (
            'DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED',
            'EXPIRED', 'SUPERSEDED', 'CONSUMED', 'ADVISORY_READY'
        )
    ),
    CONSTRAINT CK_OPS_PROPOSAL_PARAMS_JSON CHECK (PARAMETERS_JSON IS JSON),
    CONSTRAINT CK_OPS_PROPOSAL_IMPACT_JSON CHECK (IMPACT_SCOPE_JSON IS JSON),
    CONSTRAINT CK_OPS_PROPOSAL_PRECOND_JSON
        CHECK (PRECONDITIONS_JSON IS JSON),
    CONSTRAINT CK_OPS_PROPOSAL_ROLLBACK_JSON
        CHECK (ROLLBACK_PLAN_JSON IS JSON),
    CONSTRAINT CK_OPS_PROPOSAL_VERIFY_JSON
        CHECK (VERIFICATION_PLAN_JSON IS JSON),
    CONSTRAINT CK_OPS_PROPOSAL_EVIDENCE_JSON
        CHECK (EVIDENCE_ARTIFACTS_JSON IS JSON),
    CONSTRAINT CK_OPS_PROPOSAL_HASHES CHECK (
        LENGTH(ACTION_TEMPLATE_HASH) = 64
        AND LENGTH(COMMAND_HASH) = 64
        AND LENGTH(PARAMETERS_HASH) = 64
        AND LENGTH(POLICY_DECISION_HASH) = 64
        AND LENGTH(PROPOSAL_HASH) = 64
    )
);

CREATE INDEX IX_OPS_PROPOSAL_HASH
    ON KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_HASH);
CREATE INDEX IX_OPS_PROPOSAL_COMMAND
    ON KBOT_OPS_CHANGE_PROPOSAL (COMMAND_HASH);
CREATE INDEX IX_OPS_PROPOSAL_TARGET
    ON KBOT_OPS_CHANGE_PROPOSAL (TARGET_ID, STATUS, EXPIRES_AT);
CREATE INDEX IX_OPS_PROPOSAL_GROUP
    ON KBOT_OPS_CHANGE_PROPOSAL
       (OPS_RUN_ID, SOLUTION_GROUP_KEY, COMMAND_ORDINAL);
CREATE INDEX IX_OPS_PROPOSAL_TASK
    ON KBOT_OPS_CHANGE_PROPOSAL (OPS_TASK_ID);
CREATE INDEX IX_OPS_PROPOSAL_CREATED
    ON KBOT_OPS_CHANGE_PROPOSAL (CREATED_BY_TASK_ID);
CREATE INDEX IX_OPS_PROPOSAL_SNAPSHOT
    ON KBOT_OPS_CHANGE_PROPOSAL (SNAPSHOT_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_HITL (
    HITL_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16) NOT NULL,
    PROPOSAL_ID RAW(16),
    REQUEST_TYPE VARCHAR2(32 CHAR) NOT NULL,
    ASSIGNEE_USER_ID VARCHAR2(256 CHAR) NOT NULL,
    PROMPT_TEXT CLOB NOT NULL,
    RESPONSE_SCHEMA_JSON CLOB,
    INPUT_ARTIFACTS_JSON CLOB,
    RESPONSE_JSON CLOB,
    RESPONSE_URI VARCHAR2(2048 CHAR),
    RESPONSE_HASH VARCHAR2(64 CHAR),
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    REQUESTED_BY VARCHAR2(256 CHAR) NOT NULL,
    RESPONDED_BY VARCHAR2(256 CHAR),
    REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    RESPONDED_AT TIMESTAMP(6) WITH TIME ZONE,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT UK_OPS_HITL_IDEMP UNIQUE (OPS_RUN_ID, IDEMPOTENCY_KEY),
    CONSTRAINT FK_OPS_HITL_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_HITL_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_HITL_PROPOSAL
        FOREIGN KEY (PROPOSAL_ID)
        REFERENCES KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_ID),
    CONSTRAINT CK_OPS_HITL_REQUEST CHECK (
        REQUEST_TYPE IN (
            'DATA_REQUIRED', 'MANUAL_DIAGNOSTIC_SQL',
            'MANUAL_ACTION_RESULT', 'CHANGE_APPROVAL'
        )
    ),
    CONSTRAINT CK_OPS_HITL_STATUS CHECK (
        STATUS IN (
            'PENDING', 'ANSWERED', 'APPROVED', 'REJECTED',
            'EXPIRED', 'CANCELLED'
        )
    ),
    CONSTRAINT CK_OPS_HITL_VERSION CHECK (ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_HITL_SCHEMA_JSON CHECK (RESPONSE_SCHEMA_JSON IS JSON),
    CONSTRAINT CK_OPS_HITL_INPUT_JSON CHECK (INPUT_ARTIFACTS_JSON IS JSON),
    CONSTRAINT CK_OPS_HITL_RESPONSE_JSON CHECK (RESPONSE_JSON IS JSON),
    CONSTRAINT CK_OPS_HITL_RESPONSE_HASH CHECK (
        RESPONSE_HASH IS NULL OR LENGTH(RESPONSE_HASH) = 64
    )
);

CREATE INDEX IX_OPS_HITL_ASSIGNEE
    ON KBOT_OPS_HITL (ASSIGNEE_USER_ID, STATUS, EXPIRES_AT);
CREATE INDEX IX_OPS_HITL_TASK
    ON KBOT_OPS_HITL (OPS_TASK_ID);
CREATE INDEX IX_OPS_HITL_PROPOSAL
    ON KBOT_OPS_HITL (PROPOSAL_ID);

CREATE TABLE KBOT_OPS_APPROVAL_TOKEN (
    APPROVAL_TOKEN_ID RAW(16) PRIMARY KEY,
    PROPOSAL_ID RAW(16) NOT NULL,
    HITL_ID RAW(16) NOT NULL,
    TOKEN_HASH VARCHAR2(64 CHAR) NOT NULL,
    NONCE_HASH VARCHAR2(64 CHAR) NOT NULL,
    APPROVER_ID VARCHAR2(256 CHAR) NOT NULL,
    POLICY_DECISION_HASH VARCHAR2(64 CHAR) NOT NULL,
    TARGET_VERSION NUMBER(19) NOT NULL,
    PARAMETERS_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    ISSUED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSUMED_AT TIMESTAMP(6) WITH TIME ZONE,
    REVOKED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT UK_OPS_APPROVAL_TOKEN UNIQUE (TOKEN_HASH),
    CONSTRAINT UK_OPS_APPROVAL_NONCE UNIQUE (NONCE_HASH),
    CONSTRAINT UK_OPS_APPROVAL_PROPOSAL UNIQUE (PROPOSAL_ID),
    CONSTRAINT FK_OPS_APPROVAL_PROPOSAL
        FOREIGN KEY (PROPOSAL_ID)
        REFERENCES KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_ID),
    CONSTRAINT FK_OPS_APPROVAL_HITL
        FOREIGN KEY (HITL_ID) REFERENCES KBOT_OPS_HITL (HITL_ID),
    CONSTRAINT CK_OPS_APPROVAL_STATUS
        CHECK (STATUS IN ('ISSUED', 'CONSUMED', 'REVOKED', 'EXPIRED')),
    CONSTRAINT CK_OPS_APPROVAL_VERSION
        CHECK (TARGET_VERSION >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_APPROVAL_HASHES CHECK (
        LENGTH(TOKEN_HASH) = 64 AND LENGTH(NONCE_HASH) = 64
        AND LENGTH(POLICY_DECISION_HASH) = 64
        AND LENGTH(PARAMETERS_HASH) = 64
    )
);

CREATE INDEX IX_OPS_APPROVAL_EXPIRY
    ON KBOT_OPS_APPROVAL_TOKEN (STATUS, EXPIRES_AT);
CREATE INDEX IX_OPS_APPROVAL_HITL
    ON KBOT_OPS_APPROVAL_TOKEN (HITL_ID);

CREATE TABLE KBOT_OPS_EXECUTION (
    EXECUTION_ID RAW(16) PRIMARY KEY,
    PROPOSAL_ID RAW(16) NOT NULL,
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    EXECUTOR_REQUEST_ID VARCHAR2(128 CHAR) NOT NULL,
    PROPOSAL_HASH VARCHAR2(64 CHAR) NOT NULL,
    ACTION_TYPE VARCHAR2(32 CHAR) NOT NULL,
    ACTION_TEMPLATE_ID VARCHAR2(128 CHAR) NOT NULL,
    ACTION_TEMPLATE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    ACTION_TEMPLATE_HASH VARCHAR2(64 CHAR) NOT NULL,
    PARAMETERS_HASH VARCHAR2(64 CHAR) NOT NULL,
    COMMAND_HASH VARCHAR2(64 CHAR) NOT NULL,
    EXECUTION_KIND VARCHAR2(16 CHAR) NOT NULL,
    APPROVAL_TOKEN_ID RAW(16) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    EXECUTOR_INSTANCE_ID VARCHAR2(128 CHAR),
    CLAIMED_AT TIMESTAMP(6) WITH TIME ZONE,
    GRANT_JTI_HASH VARCHAR2(64 CHAR),
    STATUS_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    RESULT_ARTIFACT_ID RAW(16),
    RESULT_HASH VARCHAR2(64 CHAR),
    ROLLBACK_OF_EXECUTION_ID RAW(16),
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_EXECUTION_IDEMP UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT UK_OPS_EXECUTION_REQUEST UNIQUE (EXECUTOR_REQUEST_ID),
    CONSTRAINT UK_OPS_EXECUTION_PROPOSAL UNIQUE (PROPOSAL_ID),
    CONSTRAINT FK_OPS_EXEC_PROPOSAL
        FOREIGN KEY (PROPOSAL_ID)
        REFERENCES KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_ID),
    CONSTRAINT FK_OPS_EXEC_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_EXEC_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_EXEC_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_EXEC_APPROVAL
        FOREIGN KEY (APPROVAL_TOKEN_ID)
        REFERENCES KBOT_OPS_APPROVAL_TOKEN (APPROVAL_TOKEN_ID),
    CONSTRAINT FK_OPS_EXEC_ROLLBACK
        FOREIGN KEY (ROLLBACK_OF_EXECUTION_ID)
        REFERENCES KBOT_OPS_EXECUTION (EXECUTION_ID),
    CONSTRAINT CK_OPS_EXEC_KIND
        CHECK (EXECUTION_KIND IN ('MUTATION', 'ROLLBACK')),
    CONSTRAINT CK_OPS_EXEC_STATUS CHECK (
        STATUS IN (
            'CREATED', 'SUBMITTED', 'RUNNING', 'SUCCEEDED',
            'FAILED', 'TIMED_OUT', 'CANCELLED', 'UNKNOWN'
        )
    ),
    CONSTRAINT CK_OPS_EXEC_CLAIM CHECK (
        (STATUS = 'CREATED' AND EXECUTOR_INSTANCE_ID IS NULL
         AND CLAIMED_AT IS NULL AND GRANT_JTI_HASH IS NULL)
        OR
        (STATUS <> 'CREATED' AND EXECUTOR_INSTANCE_ID IS NOT NULL
         AND CLAIMED_AT IS NOT NULL AND GRANT_JTI_HASH IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_EXEC_VERSION
        CHECK (STATUS_VERSION >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_EXEC_HASHES CHECK (
        LENGTH(PROPOSAL_HASH) = 64
        AND LENGTH(ACTION_TEMPLATE_HASH) = 64
        AND LENGTH(PARAMETERS_HASH) = 64
        AND LENGTH(COMMAND_HASH) = 64
        AND (GRANT_JTI_HASH IS NULL OR LENGTH(GRANT_JTI_HASH) = 64)
        AND (RESULT_HASH IS NULL OR LENGTH(RESULT_HASH) = 64)
    )
);

CREATE INDEX IX_OPS_EXEC_TARGET
    ON KBOT_OPS_EXECUTION (TARGET_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_EXEC_RUN
    ON KBOT_OPS_EXECUTION (OPS_RUN_ID, STATUS);
CREATE INDEX IX_OPS_EXEC_TASK
    ON KBOT_OPS_EXECUTION (OPS_TASK_ID);
CREATE INDEX IX_OPS_EXEC_INSTANCE
    ON KBOT_OPS_EXECUTION (EXECUTOR_INSTANCE_ID, STATUS);
CREATE INDEX IX_OPS_EXEC_APPROVAL
    ON KBOT_OPS_EXECUTION (APPROVAL_TOKEN_ID);
CREATE INDEX IX_OPS_EXEC_ROLLBACK
    ON KBOT_OPS_EXECUTION (ROLLBACK_OF_EXECUTION_ID);
CREATE INDEX IX_OPS_EXEC_RESULT
    ON KBOT_OPS_EXECUTION (RESULT_ARTIFACT_ID);

COMMENT ON COLUMN KBOT_OPS_HITL.PROMPT_TEXT IS
    '仅保存安全说明；完整 SQL 或用户上传正文必须进入受控 Artifact';
COMMENT ON COLUMN KBOT_OPS_APPROVAL_TOKEN.TOKEN_HASH IS
    '规范化 Approval Claims 的 Hash，不是可执行 Bearer Token';
COMMENT ON COLUMN KBOT_OPS_EXECUTION.COMMAND_HASH IS
    'Executor 必须重新计算并与审批快照逐项比对';
