-- KBot 4.0 AIOps：巡检计划、调度 Fire 和版本化报告投影。

CREATE TABLE KBOT_OPS_INSPECTION_PLAN (
    INSPECTION_PLAN_ID RAW(16) PRIMARY KEY,
    APP_ID NUMBER(38) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    PLAN_KEY VARCHAR2(128 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    SCHEDULE_TYPE VARCHAR2(16 CHAR) NOT NULL,
    CRON_EXPRESSION VARCHAR2(256 CHAR) NOT NULL,
    TIMEZONE VARCHAR2(64 CHAR) NOT NULL,
    TEMPLATE_ID VARCHAR2(128 CHAR) NOT NULL,
    TEMPLATE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    TIMEOUT_SECONDS NUMBER(10) NOT NULL,
    OVERLAP_POLICY VARCHAR2(16 CHAR) NOT NULL,
    MISFIRE_POLICY VARCHAR2(16 CHAR) NOT NULL,
    SCHEDULE_RESOLVER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'PAUSED' NOT NULL,
    NEXT_RUN_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_RUN_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_SCHEDULED_FOR TIMESTAMP(6) WITH TIME ZONE,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_INSPECTION_PLAN
        UNIQUE (APP_ID, DOMAIN_ID, PLAN_KEY),
    CONSTRAINT FK_OPS_INSP_PLAN_DOMAIN
        FOREIGN KEY (DOMAIN_ID, APP_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID, APP_ID),
    CONSTRAINT CK_OPS_INSP_PLAN_SCHEDULE
        CHECK (SCHEDULE_TYPE IN ('DAILY', 'WEEKLY', 'CRON')),
    CONSTRAINT CK_OPS_INSP_PLAN_OVERLAP
        CHECK (OVERLAP_POLICY IN ('SKIP', 'QUEUE')),
    CONSTRAINT CK_OPS_INSP_PLAN_MISFIRE
        CHECK (MISFIRE_POLICY IN ('SKIP', 'LATEST_ONLY')),
    CONSTRAINT CK_OPS_INSP_PLAN_STATUS
        CHECK (STATUS IN ('ACTIVE', 'PAUSED', 'DISABLED')),
    CONSTRAINT CK_OPS_INSP_PLAN_NUMBERS
        CHECK (TIMEOUT_SECONDS >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_INSP_PLAN_LEASE CHECK (
        (LEASE_OWNER IS NULL AND LEASE_TOKEN IS NULL AND LEASE_UNTIL IS NULL)
        OR
        (LEASE_OWNER IS NOT NULL
         AND LEASE_TOKEN IS NOT NULL AND LEASE_UNTIL IS NOT NULL)
    )
);

CREATE INDEX IX_OPS_INSP_PLAN_DUE
    ON KBOT_OPS_INSPECTION_PLAN (STATUS, NEXT_RUN_AT);
CREATE INDEX IX_OPS_INSP_PLAN_LEASE
    ON KBOT_OPS_INSPECTION_PLAN (STATUS, LEASE_UNTIL);
CREATE INDEX IX_OPS_INSP_PLAN_DOMAIN
    ON KBOT_OPS_INSPECTION_PLAN (DOMAIN_ID, APP_ID);

CREATE TABLE KBOT_OPS_INSPECTION_TARGET (
    INSPECTION_TARGET_ID RAW(16) PRIMARY KEY,
    INSPECTION_PLAN_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    TEMPLATE_OVERRIDES_JSON JSON,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_INSP_TARGET
        UNIQUE (INSPECTION_PLAN_ID, TARGET_ID),
    CONSTRAINT FK_OPS_INSP_TARGET_PLAN
        FOREIGN KEY (INSPECTION_PLAN_ID)
        REFERENCES KBOT_OPS_INSPECTION_PLAN (INSPECTION_PLAN_ID),
    CONSTRAINT FK_OPS_INSP_TARGET_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT CK_OPS_INSP_TARGET_STATUS
        CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE INDEX IX_OPS_INSP_TARGET_TARGET
    ON KBOT_OPS_INSPECTION_TARGET (TARGET_ID, STATUS);

CREATE TABLE KBOT_OPS_INSPECTION_FIRE (
    INSPECTION_FIRE_ID RAW(16) PRIMARY KEY,
    INSPECTION_PLAN_ID RAW(16) NOT NULL,
    SCHEDULED_FOR TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    SCHEDULED_FOR_UTC TIMESTAMP(6)
        GENERATED ALWAYS AS (SYS_EXTRACT_UTC(SCHEDULED_FOR)) VIRTUAL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    PLAN_ROW_VERSION NUMBER(19) NOT NULL,
    TEMPLATE_ID VARCHAR2(128 CHAR) NOT NULL,
    TEMPLATE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    SCHEDULE_RESOLVER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PLAN_SNAPSHOT_JSON JSON NOT NULL,
    RESOLUTION_JSON JSON,
    TARGET_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    RUN_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    COMPLETED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    FAILED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    SKIP_REASON VARCHAR2(256 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT UK_OPS_INSP_FIRE
        UNIQUE (INSPECTION_PLAN_ID, SCHEDULED_FOR_UTC),
    CONSTRAINT FK_OPS_INSP_FIRE_PLAN
        FOREIGN KEY (INSPECTION_PLAN_ID)
        REFERENCES KBOT_OPS_INSPECTION_PLAN (INSPECTION_PLAN_ID),
    CONSTRAINT CK_OPS_INSP_FIRE_STATUS CHECK (
        STATUS IN (
            'QUEUED', 'RUNNING', 'COMPLETED', 'PARTIAL',
            'FAILED', 'SKIPPED', 'CANCELLED'
        )
    ),
    CONSTRAINT CK_OPS_INSP_FIRE_COUNTS CHECK (
        PLAN_ROW_VERSION >= 1 AND ROW_VERSION >= 1
        AND TARGET_COUNT >= 0 AND RUN_COUNT >= 0
        AND COMPLETED_COUNT >= 0 AND FAILED_COUNT >= 0
        AND RUN_COUNT <= TARGET_COUNT
        AND COMPLETED_COUNT <= RUN_COUNT
        AND COMPLETED_COUNT + FAILED_COUNT <= TARGET_COUNT
    )
);

CREATE INDEX IX_OPS_INSP_FIRE_PLAN
    ON KBOT_OPS_INSPECTION_FIRE
       (INSPECTION_PLAN_ID, STATUS, SCHEDULED_FOR);
CREATE INDEX IX_OPS_INSP_FIRE_STATUS
    ON KBOT_OPS_INSPECTION_FIRE (STATUS, UPDATED_AT);

CREATE TABLE KBOT_OPS_REPORT (
    REPORT_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    REPORT_KEY VARCHAR2(128 CHAR) NOT NULL,
    REPORT_VERSION NUMBER(19) NOT NULL,
    SUPERSEDES_REPORT_ID RAW(16),
    IS_CURRENT NUMBER(1) DEFAULT 0 NOT NULL,
    REPORT_TYPE VARCHAR2(32 CHAR) NOT NULL,
    TITLE VARCHAR2(512 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    PERIOD_START TIMESTAMP(6) WITH TIME ZONE,
    PERIOD_END TIMESTAMP(6) WITH TIME ZONE,
    BASELINE_START TIMESTAMP(6) WITH TIME ZONE,
    BASELINE_END TIMESTAMP(6) WITH TIME ZONE,
    AFTER_START TIMESTAMP(6) WITH TIME ZONE,
    AFTER_END TIMESTAMP(6) WITH TIME ZONE,
    RESULT VARCHAR2(16 CHAR),
    TEMPLATE_ID VARCHAR2(128 CHAR) NOT NULL,
    TEMPLATE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    GENERATED_BY_TASK_ID RAW(16) NOT NULL,
    CONTENT_ARTIFACT_ID RAW(16),
    CONTENT_HASH VARCHAR2(64 CHAR),
    SUMMARY VARCHAR2(2000 CHAR),
    SECURITY_LEVEL NUMBER(3) NOT NULL,
    SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_REPORT_VERSION
        UNIQUE (OPS_RUN_ID, REPORT_KEY, REPORT_VERSION),
    CONSTRAINT FK_OPS_REPORT_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_REPORT_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_REPORT_TASK
        FOREIGN KEY (GENERATED_BY_TASK_ID)
        REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_REPORT_SUPERSEDES
        FOREIGN KEY (SUPERSEDES_REPORT_ID)
        REFERENCES KBOT_OPS_REPORT (REPORT_ID),
    CONSTRAINT CK_OPS_REPORT_TYPE CHECK (
        REPORT_TYPE IN (
            'INCIDENT', 'PERFORMANCE', 'INSPECTION_DAILY',
            'INSPECTION_WEEKLY', 'COMPARISON'
        )
    ),
    CONSTRAINT CK_OPS_REPORT_STATUS
        CHECK (STATUS IN ('GENERATING', 'READY', 'PARTIAL', 'FAILED')),
    CONSTRAINT CK_OPS_REPORT_RESULT CHECK (
        RESULT IS NULL OR RESULT IN (
            'IMPROVED', 'UNCHANGED', 'DEGRADED', 'INCONCLUSIVE'
        )
    ),
    CONSTRAINT CK_OPS_REPORT_NUMBERS CHECK (
        REPORT_VERSION >= 1 AND IS_CURRENT IN (0, 1)
        AND SECURITY_LEVEL >= 0
    ),
    CONSTRAINT CK_OPS_REPORT_CURRENT CHECK (
        IS_CURRENT = 0
        OR
        (STATUS IN ('READY', 'PARTIAL')
         AND CONTENT_ARTIFACT_ID IS NOT NULL AND CONTENT_HASH IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_REPORT_HASH CHECK (
        CONTENT_HASH IS NULL OR LENGTH(CONTENT_HASH) = 64
    )
);

CREATE INDEX IX_OPS_REPORT_TARGET
    ON KBOT_OPS_REPORT
       (TARGET_ID, REPORT_TYPE, IS_CURRENT, CREATED_AT);
CREATE INDEX IX_OPS_REPORT_STATUS
    ON KBOT_OPS_REPORT (STATUS, CREATED_AT);
CREATE INDEX IX_OPS_REPORT_TASK
    ON KBOT_OPS_REPORT (GENERATED_BY_TASK_ID);
CREATE INDEX IX_OPS_REPORT_SUPERSEDES
    ON KBOT_OPS_REPORT (SUPERSEDES_REPORT_ID);
CREATE INDEX IX_OPS_REPORT_CONTENT
    ON KBOT_OPS_REPORT (CONTENT_ARTIFACT_ID);

COMMENT ON COLUMN KBOT_OPS_INSPECTION_PLAN.CRON_EXPRESSION IS
    '规范五段 Cron；应用按 IANA 时区预计算 NEXT_RUN_AT';
COMMENT ON COLUMN KBOT_OPS_INSPECTION_FIRE.PLAN_SNAPSHOT_JSON IS
    'Fire 创建时冻结的计划配置，后续修改 Plan 不影响本次执行';
COMMENT ON COLUMN KBOT_OPS_INSPECTION_FIRE.SCHEDULED_FOR_UTC IS
    '由 SCHEDULED_FOR 生成的 UTC 虚拟列，仅用于 Oracle 唯一约束';
COMMENT ON COLUMN KBOT_OPS_REPORT.CONTENT_ARTIFACT_ID IS
    '完整报告的不可变 Artifact；本表只承担可查询的发布投影';
