-- KBot 4.0 AIOps：巡检模板、计划、调度 Fire 和版本化报告投影。

CREATE TABLE KBOT_OPS_INSPECTION_TEMPLATE (
    INSPECTION_TEMPLATE_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CURRENT_VERSION_ID RAW(16) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_INSP_TPL_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID));

CREATE INDEX IX_OPS_INSP_TEMPLATE_SCOPE
    ON KBOT_OPS_INSPECTION_TEMPLATE (DOMAIN_ID, STATUS);

CREATE TABLE KBOT_OPS_INSPECTION_TEMPLATE_VER (
    INSPECTION_TEMPLATE_VERSION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    INSPECTION_TEMPLATE_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    DEFINITION_JSON JSON NOT NULL,
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_INSP_TPL_VER_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_INSP_TPL_VER_TEMPLATE
        FOREIGN KEY (INSPECTION_TEMPLATE_ID)
        REFERENCES KBOT_OPS_INSPECTION_TEMPLATE (INSPECTION_TEMPLATE_ID)
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED);

CREATE INDEX IX_OPS_INSP_TPL_VER_TEMPLATE
    ON KBOT_OPS_INSPECTION_TEMPLATE_VER (INSPECTION_TEMPLATE_ID);
CREATE INDEX IX_OPS_INSP_TPL_VER_DOMAIN
    ON KBOT_OPS_INSPECTION_TEMPLATE_VER (DOMAIN_ID);

ALTER TABLE KBOT_OPS_INSPECTION_TEMPLATE
    ADD CONSTRAINT FK_OPS_INSP_TPL_CURRENT_VER
    FOREIGN KEY (CURRENT_VERSION_ID)
    REFERENCES KBOT_OPS_INSPECTION_TEMPLATE_VER
        (INSPECTION_TEMPLATE_VERSION_ID)
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IX_OPS_INSP_TPL_CURRENT_VER
    ON KBOT_OPS_INSPECTION_TEMPLATE (CURRENT_VERSION_ID);

CREATE TABLE KBOT_OPS_INSPECTION_PLAN (
    INSPECTION_PLAN_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    SCHEDULE_TYPE VARCHAR2(16 CHAR) NOT NULL,
    CRON_EXPRESSION VARCHAR2(256 CHAR) NOT NULL,
    TIMEZONE VARCHAR2(64 CHAR) NOT NULL,
    INSPECTION_TEMPLATE_ID RAW(16) NOT NULL,
    INSPECTION_TEMPLATE_VERSION_ID RAW(16) NOT NULL,
    TIMEOUT_SECONDS NUMBER(10) NOT NULL,
    OVERLAP_POLICY VARCHAR2(16 CHAR) NOT NULL,
    MISFIRE_POLICY VARCHAR2(16 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    NEXT_RUN_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_RUN_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_SCHEDULED_FOR TIMESTAMP(6) WITH TIME ZONE,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_INSP_PLAN_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_INSP_PLAN_TEMPLATE
        FOREIGN KEY (INSPECTION_TEMPLATE_ID)
        REFERENCES KBOT_OPS_INSPECTION_TEMPLATE (INSPECTION_TEMPLATE_ID),
    CONSTRAINT FK_OPS_INSP_PLAN_TEMPLATE_VER
        FOREIGN KEY (INSPECTION_TEMPLATE_VERSION_ID)
        REFERENCES KBOT_OPS_INSPECTION_TEMPLATE_VER
            (INSPECTION_TEMPLATE_VERSION_ID));

CREATE INDEX IX_OPS_INSP_PLAN_DUE
    ON KBOT_OPS_INSPECTION_PLAN (STATUS, NEXT_RUN_AT);
CREATE INDEX IX_OPS_INSP_PLAN_LEASE
    ON KBOT_OPS_INSPECTION_PLAN (STATUS, LEASE_UNTIL);
CREATE INDEX IX_OPS_INSP_PLAN_DOMAIN
    ON KBOT_OPS_INSPECTION_PLAN (DOMAIN_ID);
CREATE INDEX IX_OPS_INSP_PLAN_AGENT
    ON KBOT_OPS_INSPECTION_PLAN (AGENT_ID, DOMAIN_ID, STATUS);
CREATE INDEX IX_OPS_INSP_PLAN_TEMPLATE
    ON KBOT_OPS_INSPECTION_PLAN (INSPECTION_TEMPLATE_ID);
CREATE INDEX IX_OPS_INSP_PLAN_TEMPLATE_VER
    ON KBOT_OPS_INSPECTION_PLAN (INSPECTION_TEMPLATE_VERSION_ID);

CREATE TABLE KBOT_OPS_INSPECTION_FIRE (
    INSPECTION_FIRE_ID RAW(16) PRIMARY KEY,
    INSPECTION_PLAN_ID RAW(16) NOT NULL,
    SCHEDULED_FOR TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    PLAN_ROW_VERSION NUMBER(19) NOT NULL,
    INSPECTION_TEMPLATE_ID RAW(16) NOT NULL,
    INSPECTION_TEMPLATE_VERSION_ID RAW(16) NOT NULL,
    SCHEDULE_RESOLVER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PLAN_SNAPSHOT_JSON JSON NOT NULL,
    RESOLUTION_JSON JSON,
    TARGET_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    RUN_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    COMPLETED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    FAILED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    SKIP_REASON VARCHAR2(256 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_OPS_INSP_FIRE_PLAN
        FOREIGN KEY (INSPECTION_PLAN_ID)
        REFERENCES KBOT_OPS_INSPECTION_PLAN (INSPECTION_PLAN_ID),
    CONSTRAINT FK_OPS_INSP_FIRE_TEMPLATE
        FOREIGN KEY (INSPECTION_TEMPLATE_ID)
        REFERENCES KBOT_OPS_INSPECTION_TEMPLATE (INSPECTION_TEMPLATE_ID),
    CONSTRAINT FK_OPS_INSP_FIRE_TEMPLATE_VER
        FOREIGN KEY (INSPECTION_TEMPLATE_VERSION_ID)
        REFERENCES KBOT_OPS_INSPECTION_TEMPLATE_VER
            (INSPECTION_TEMPLATE_VERSION_ID));

CREATE INDEX IX_OPS_INSP_FIRE_PLAN
    ON KBOT_OPS_INSPECTION_FIRE
       (INSPECTION_PLAN_ID, STATUS, SCHEDULED_FOR);
CREATE INDEX IX_OPS_INSP_FIRE_STATUS
    ON KBOT_OPS_INSPECTION_FIRE (STATUS, UPDATED_AT);
CREATE INDEX IX_OPS_INSP_FIRE_TEMPLATE
    ON KBOT_OPS_INSPECTION_FIRE (INSPECTION_TEMPLATE_ID);
CREATE INDEX IX_OPS_INSP_FIRE_TEMPLATE_VER
    ON KBOT_OPS_INSPECTION_FIRE (INSPECTION_TEMPLATE_VERSION_ID);

CREATE TABLE KBOT_OPS_REPORT (
    REPORT_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    REPORT_KEY VARCHAR2(128 CHAR) NOT NULL,
    REPORT_VERSION NUMBER(19) NOT NULL,
    SUPERSEDES_REPORT_ID RAW(16),
    IS_CURRENT NUMBER(1) DEFAULT 0 NOT NULL,
    REPORT_TYPE VARCHAR2(32 CHAR) NOT NULL,
    TITLE VARCHAR2(512 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    PERIOD_START TIMESTAMP(6) WITH TIME ZONE,
    PERIOD_END TIMESTAMP(6) WITH TIME ZONE,
    BASELINE_START TIMESTAMP(6) WITH TIME ZONE,
    BASELINE_END TIMESTAMP(6) WITH TIME ZONE,
    AFTER_START TIMESTAMP(6) WITH TIME ZONE,
    AFTER_END TIMESTAMP(6) WITH TIME ZONE,
    RESULT VARCHAR2(16 CHAR),
    TEMPLATE_ID VARCHAR2(128 CHAR) NOT NULL,
    TEMPLATE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    GENERATED_BY_TASK_ID RAW(16) NOT NULL,
    CONTENT_ARTIFACT_ID RAW(16),
    CONTENT_HASH VARCHAR2(64 CHAR),
    SUMMARY CLOB,
    SECURITY_LEVEL NUMBER(3) NOT NULL,
    SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_REPORT_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_REPORT_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_REPORT_TASK
        FOREIGN KEY (GENERATED_BY_TASK_ID)
        REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_REPORT_SUPERSEDES
        FOREIGN KEY (SUPERSEDES_REPORT_ID)
        REFERENCES KBOT_OPS_REPORT (REPORT_ID));

CREATE INDEX IX_OPS_REPORT_TARGET
    ON KBOT_OPS_REPORT
       (TARGET_ID, REPORT_TYPE, IS_CURRENT, CREATED_AT);
CREATE INDEX IX_OPS_REPORT_STATUS
    ON KBOT_OPS_REPORT (STATUS, CREATED_AT);
CREATE INDEX IX_OPS_REPORT_TASK
    ON KBOT_OPS_REPORT (GENERATED_BY_TASK_ID);
CREATE INDEX IX_OPS_REPORT_SUPERSEDES
    ON KBOT_OPS_REPORT (SUPERSEDES_REPORT_ID);
CREATE INDEX IX_OPS_REPORT_CONTENT
    ON KBOT_OPS_REPORT (CONTENT_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_REPORT_SOURCE (
    REPORT_ID RAW(16) NOT NULL,
    OPS_RUN_ID RAW(16) NOT NULL,
    SOURCE_ARTIFACT_ID RAW(16) NOT NULL,
    SOURCE_KIND VARCHAR2(16 CHAR) NOT NULL,
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    OBSERVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_OPS_REPORT_SOURCE PRIMARY KEY (REPORT_ID, OPS_RUN_ID),
    CONSTRAINT FK_OPS_RPT_SOURCE_REPORT FOREIGN KEY (REPORT_ID)
        REFERENCES KBOT_OPS_REPORT (REPORT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_RPT_SOURCE_RUN FOREIGN KEY (OPS_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_RPT_SOURCE_ART FOREIGN KEY (SOURCE_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID));

CREATE INDEX IX_OPS_RPT_SOURCE_RUN
    ON KBOT_OPS_REPORT_SOURCE (OPS_RUN_ID);
CREATE INDEX IX_OPS_RPT_SOURCE_ART
    ON KBOT_OPS_REPORT_SOURCE (SOURCE_ARTIFACT_ID);

COMMENT ON COLUMN KBOT_OPS_INSPECTION_PLAN.CRON_EXPRESSION IS
    '规范五段 Cron；应用按 IANA 时区预计算 NEXT_RUN_AT';
COMMENT ON COLUMN KBOT_OPS_INSPECTION_PLAN.AGENT_ID IS
    '负责执行巡检的 DBA Agent；Target、模型、监控源和策略均由 Agent 当前版本提供';
COMMENT ON COLUMN KBOT_OPS_INSPECTION_TEMPLATE_VER.DEFINITION_JSON IS
    '冻结的检查项、Check Catalog 哈希和固定取证步骤；计划运行时不得重新编译当前目录';
COMMENT ON COLUMN KBOT_OPS_INSPECTION_FIRE.PLAN_SNAPSHOT_JSON IS
    'Fire 创建时冻结的计划配置，后续修改 Plan 不影响本次执行';
COMMENT ON COLUMN KBOT_OPS_REPORT.CONTENT_ARTIFACT_ID IS
    '完整报告的不可变 Artifact；本表只承担可查询的发布投影';
