-- KBot 4.0 AIOps：外部交付去重 Inbox 与事务消息 Outbox。

CREATE TABLE KBOT_OPS_INBOX (
    INBOX_ID RAW(16) PRIMARY KEY,
    SOURCE_SYSTEM VARCHAR2(64 CHAR) NOT NULL,
    MESSAGE_KEY VARCHAR2(256 CHAR) NOT NULL,
    MESSAGE_TYPE VARCHAR2(64 CHAR) NOT NULL,
    PAYLOAD_JSON CLOB,
    PAYLOAD_URI VARCHAR2(2048 CHAR),
    PAYLOAD_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'RECEIVED' NOT NULL,
    RECEIVED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    PROCESSED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT UK_OPS_INBOX_MESSAGE UNIQUE (SOURCE_SYSTEM, MESSAGE_KEY),
    CONSTRAINT CK_OPS_INBOX_PAYLOAD
        CHECK (PAYLOAD_JSON IS NOT NULL OR PAYLOAD_URI IS NOT NULL),
    CONSTRAINT CK_OPS_INBOX_PAYLOAD_JSON CHECK (PAYLOAD_JSON IS JSON),
    CONSTRAINT CK_OPS_INBOX_STATUS CHECK (
        STATUS IN ('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED', 'IGNORED')
    ),
    CONSTRAINT CK_OPS_INBOX_HASH CHECK (LENGTH(PAYLOAD_HASH) = 64),
    CONSTRAINT CK_OPS_INBOX_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_OPS_INBOX_CLAIM
    ON KBOT_OPS_INBOX (STATUS, RECEIVED_AT);

CREATE TABLE KBOT_OPS_OUTBOX (
    OUTBOX_ID RAW(16) PRIMARY KEY,
    AGGREGATE_TYPE VARCHAR2(64 CHAR) NOT NULL,
    AGGREGATE_ID RAW(16) NOT NULL,
    EVENT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(256 CHAR) NOT NULL,
    PAYLOAD_JSON CLOB,
    PAYLOAD_URI VARCHAR2(2048 CHAR),
    PAYLOAD_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'PENDING' NOT NULL,
    AVAILABLE_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    ATTEMPT_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    MAX_ATTEMPTS NUMBER(8) DEFAULT 3 NOT NULL,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_OUTBOX_IDEMP UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT CK_OPS_OUTBOX_PAYLOAD
        CHECK (PAYLOAD_JSON IS NOT NULL OR PAYLOAD_URI IS NOT NULL),
    CONSTRAINT CK_OPS_OUTBOX_PAYLOAD_JSON CHECK (PAYLOAD_JSON IS JSON),
    CONSTRAINT CK_OPS_OUTBOX_STATUS CHECK (
        STATUS IN (
            'PENDING', 'PUBLISHING', 'PUBLISHED', 'RETRY_WAIT', 'FAILED'
        )
    ),
    CONSTRAINT CK_OPS_OUTBOX_ATTEMPTS CHECK (
        ATTEMPT_COUNT >= 0 AND MAX_ATTEMPTS >= 1
        AND ATTEMPT_COUNT <= MAX_ATTEMPTS
    ),
    CONSTRAINT CK_OPS_OUTBOX_LEASE CHECK (
        (STATUS = 'PUBLISHING' AND LEASE_OWNER IS NOT NULL
         AND LEASE_TOKEN IS NOT NULL AND LEASE_UNTIL IS NOT NULL)
        OR
        (STATUS <> 'PUBLISHING' AND LEASE_OWNER IS NULL
         AND LEASE_TOKEN IS NULL AND LEASE_UNTIL IS NULL)
    ),
    CONSTRAINT CK_OPS_OUTBOX_HASH CHECK (LENGTH(PAYLOAD_HASH) = 64)
);

CREATE INDEX IX_OPS_OUTBOX_CLAIM
    ON KBOT_OPS_OUTBOX (STATUS, AVAILABLE_AT);
CREATE INDEX IX_OPS_OUTBOX_LEASE
    ON KBOT_OPS_OUTBOX (STATUS, LEASE_UNTIL);
CREATE INDEX IX_OPS_OUTBOX_AGGREGATE
    ON KBOT_OPS_OUTBOX (AGGREGATE_TYPE, AGGREGATE_ID);

COMMENT ON COLUMN KBOT_OPS_INBOX.PAYLOAD_HASH IS
    '验签后原始交付内容的 SHA-256，用于审计和重复内容识别';
COMMENT ON COLUMN KBOT_OPS_OUTBOX.AGGREGATE_ID IS
    '多态领域聚合 UUID；不创建无法成立的跨表外键';
