-- KBot 4.0 AIOps：循环外键、函数唯一索引和 APEX 只读投影。

ALTER TABLE KBOT_OPS_TARGET ADD CONSTRAINT FK_OPS_TARGET_DIAG_CRED
    FOREIGN KEY (DIAGNOSTIC_CREDENTIAL_ID, DOMAIN_ID)
    REFERENCES KBOT_MANAGED_CREDENTIAL (CREDENTIAL_ID, DOMAIN_ID);
ALTER TABLE KBOT_OPS_TARGET ADD CONSTRAINT FK_OPS_TARGET_EXEC_CRED
    FOREIGN KEY (EXECUTION_CREDENTIAL_ID, DOMAIN_ID)
    REFERENCES KBOT_MANAGED_CREDENTIAL (CREDENTIAL_ID, DOMAIN_ID);
CREATE INDEX IX_OPS_TARGET_DIAG_CRED
    ON KBOT_OPS_TARGET (DIAGNOSTIC_CREDENTIAL_ID, DOMAIN_ID);
CREATE INDEX IX_OPS_TARGET_EXEC_CRED
    ON KBOT_OPS_TARGET (EXECUTION_CREDENTIAL_ID, DOMAIN_ID);
ALTER TABLE KBOT_OPS_DIAGNOSTIC_SOURCE
    ADD CONSTRAINT FK_OPS_SOURCE_AUTH_CRED
    FOREIGN KEY (AUTH_CREDENTIAL_ID, DOMAIN_ID)
    REFERENCES KBOT_MANAGED_CREDENTIAL (CREDENTIAL_ID, DOMAIN_ID);
ALTER TABLE KBOT_OPS_DIAGNOSTIC_SOURCE
    ADD CONSTRAINT FK_OPS_SOURCE_WEBHOOK_CRED
    FOREIGN KEY (WEBHOOK_CREDENTIAL_ID, DOMAIN_ID)
    REFERENCES KBOT_MANAGED_CREDENTIAL (CREDENTIAL_ID, DOMAIN_ID);
CREATE INDEX IX_OPS_SOURCE_AUTH_CRED
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (AUTH_CREDENTIAL_ID, DOMAIN_ID);
CREATE INDEX IX_OPS_SOURCE_WEBHOOK_CRED
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (WEBHOOK_CREDENTIAL_ID, DOMAIN_ID);
-- RAW(16) 在视图中显式格式化，避免 APEX/驱动依赖 Oracle UUID 类型映射。

ALTER TABLE KBOT_OPS_RUN ADD CONSTRAINT FK_OPS_RUN_INSP_FIRE
    FOREIGN KEY (INSPECTION_FIRE_ID)
    REFERENCES KBOT_OPS_INSPECTION_FIRE (INSPECTION_FIRE_ID);

ALTER TABLE KBOT_OPS_RUN ADD CONSTRAINT FK_OPS_RUN_FINAL_ART
    FOREIGN KEY (FINAL_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE KBOT_OPS_RUN ADD CONSTRAINT FK_OPS_RUN_SOURCE_PROPOSAL
    FOREIGN KEY (SOURCE_PROPOSAL_ID)
    REFERENCES KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_ID);

ALTER TABLE KBOT_OPS_RUN ADD CONSTRAINT FK_OPS_RUN_SOURCE_RESULT
    FOREIGN KEY (SOURCE_RESULT_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID);

ALTER TABLE KBOT_OPS_TASK ADD CONSTRAINT FK_OPS_TASK_OUTPUT_ART
    FOREIGN KEY (OUTPUT_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE KBOT_OPS_CHANGE_PROPOSAL
    ADD CONSTRAINT FK_OPS_PROP_SNAPSHOT_ART
    FOREIGN KEY (SNAPSHOT_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE KBOT_OPS_EXECUTION ADD CONSTRAINT FK_OPS_EXEC_RESULT_ART
    FOREIGN KEY (RESULT_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE KBOT_OPS_REPORT ADD CONSTRAINT FK_OPS_REPORT_CONTENT_ART
    FOREIGN KEY (CONTENT_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX IX_OPS_RUN_FINAL_ART ON KBOT_OPS_RUN (FINAL_ARTIFACT_ID);
CREATE INDEX IX_OPS_RUN_SOURCE_RESULT
    ON KBOT_OPS_RUN (SOURCE_RESULT_ARTIFACT_ID);
CREATE INDEX IX_OPS_TASK_OUTPUT_ART
    ON KBOT_OPS_TASK (OUTPUT_ARTIFACT_ID);

CREATE UNIQUE INDEX UX_OPS_POLICY_ACTIVE ON KBOT_OPS_POLICY (
    CASE WHEN STATUS = 'ACTIVE' THEN DOMAIN_ID END,
    CASE WHEN STATUS = 'ACTIVE' THEN POLICY_KEY END
);

CREATE UNIQUE INDEX UX_OPS_SITUATION_ACTIVE ON KBOT_OPS_SITUATION (
    CASE
        WHEN STATUS IN (
            'OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'DIAGNOSED',
            'MITIGATING', 'OBSERVING', 'SUPPRESSED'
        )
        THEN TARGET_ID
    END,
    CASE
        WHEN STATUS IN (
            'OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'DIAGNOSED',
            'MITIGATING', 'OBSERVING', 'SUPPRESSED'
        )
        THEN CORRELATION_HASH
    END
);

CREATE UNIQUE INDEX UX_OPS_HITL_PENDING ON KBOT_OPS_HITL (
    CASE WHEN STATUS = 'PENDING' THEN OPS_TASK_ID END,
    CASE WHEN STATUS = 'PENDING' THEN REQUEST_TYPE END
);

CREATE UNIQUE INDEX UX_OPS_REPORT_CURRENT ON KBOT_OPS_REPORT (
    CASE WHEN IS_CURRENT = 1 THEN OPS_RUN_ID END,
    CASE WHEN IS_CURRENT = 1 THEN REPORT_KEY END
);

CREATE OR REPLACE VIEW KBOT_V_OPS_TARGET AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(t.TARGET_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 21, 12)
    ) AS TARGET_ID,
    t.DOMAIN_ID,
    t.DISPLAY_NAME,
    t.DB_TYPE,
    t.VERSION_CODE,
    t.ENVIRONMENT,
    t.DB_ROLE,
    t.SECURITY_LEVEL,
    t.STATUS,
    t.CONNECTIVITY_STATUS,
    t.OBSERVED_STATUS,
    t.LAST_OBSERVED_AT,
    t.LAST_CONNECTIVITY_CHECK_AT,
    t.LAST_ERROR_CODE,
    t.ROW_VERSION,
    t.CREATED_AT,
    t.UPDATED_AT,
    COUNT(tm.TARGET_SOURCE_BINDING_ID) AS SOURCE_BINDING_COUNT,
    SUM(CASE WHEN tm.HEALTH_STATUS = 'HEALTHY' THEN 1 ELSE 0 END)
        AS HEALTHY_SOURCE_BINDING_COUNT,
    SUM(CASE WHEN tm.HEALTH_STATUS IN ('DEGRADED', 'UNREACHABLE')
             THEN 1 ELSE 0 END) AS UNHEALTHY_SOURCE_BINDING_COUNT
FROM KBOT_OPS_TARGET t
LEFT JOIN KBOT_OPS_TARGET_SOURCE_BINDING tm
    ON tm.TARGET_ID = t.TARGET_ID
   AND tm.STATUS = 'ACTIVE'
GROUP BY
    t.TARGET_ID, t.DOMAIN_ID, t.DISPLAY_NAME,
    t.DB_TYPE, t.VERSION_CODE, t.ENVIRONMENT, t.DB_ROLE,
    t.SECURITY_LEVEL, t.STATUS, t.CONNECTIVITY_STATUS, t.OBSERVED_STATUS,
    t.LAST_OBSERVED_AT,
    t.LAST_CONNECTIVITY_CHECK_AT, t.LAST_ERROR_CODE, t.ROW_VERSION,
    t.CREATED_AT, t.UPDATED_AT;

CREATE OR REPLACE VIEW KBOT_V_OPS_DIAGNOSTIC_SOURCE AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(m.DIAGNOSTIC_SOURCE_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(m.DIAGNOSTIC_SOURCE_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(m.DIAGNOSTIC_SOURCE_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(m.DIAGNOSTIC_SOURCE_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(m.DIAGNOSTIC_SOURCE_ID), 21, 12)
    ) AS DIAGNOSTIC_SOURCE_ID,
    m.DOMAIN_ID,
    m.DISPLAY_NAME,
    m.SOURCE_TYPE,
    m.STATUS,
    m.CONNECTIVITY_STATUS,
    m.LAST_CONNECTIVITY_CHECK_AT,
    m.LAST_ERROR_CODE,
    m.ROW_VERSION,
    m.CREATED_AT,
    m.UPDATED_AT,
    COUNT(tm.TARGET_SOURCE_BINDING_ID) AS ACTIVE_TARGET_COUNT
FROM KBOT_OPS_DIAGNOSTIC_SOURCE m
LEFT JOIN KBOT_OPS_TARGET_SOURCE_BINDING tm
    ON tm.DIAGNOSTIC_SOURCE_ID = m.DIAGNOSTIC_SOURCE_ID
   AND tm.STATUS = 'ACTIVE'
GROUP BY
    m.DIAGNOSTIC_SOURCE_ID, m.DOMAIN_ID,
    m.DISPLAY_NAME, m.SOURCE_TYPE, m.STATUS, m.CONNECTIVITY_STATUS,
    m.LAST_CONNECTIVITY_CHECK_AT, m.LAST_ERROR_CODE, m.ROW_VERSION,
    m.CREATED_AT, m.UPDATED_AT;

CREATE OR REPLACE VIEW KBOT_V_OPS_POLICY AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(p.POLICY_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(p.POLICY_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.POLICY_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.POLICY_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.POLICY_ID), 21, 12)
    ) AS POLICY_ID,
    p.DOMAIN_ID,
    p.POLICY_KEY,
    p.VERSION_NO,
    p.DISPLAY_NAME,
    p.POLICY_HASH,
    p.STATUS,
    p.EFFECTIVE_AT,
    p.RETIRED_AT,
    p.ROW_VERSION,
    p.CREATED_AT,
    p.UPDATED_AT
FROM KBOT_OPS_POLICY p;

CREATE OR REPLACE VIEW KBOT_V_OPS_INSPECTION_PLAN AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(p.INSPECTION_PLAN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(p.INSPECTION_PLAN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.INSPECTION_PLAN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.INSPECTION_PLAN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.INSPECTION_PLAN_ID), 21, 12)
    ) AS INSPECTION_PLAN_ID,
    p.DOMAIN_ID,
    p.DISPLAY_NAME,
    p.SCHEDULE_TYPE,
    p.CRON_EXPRESSION,
    p.TIMEZONE,
    p.TEMPLATE_ID,
    p.TEMPLATE_VERSION,
    p.STATUS,
    p.NEXT_RUN_AT,
    p.LAST_RUN_AT,
    p.LAST_SCHEDULED_FOR,
    p.ROW_VERSION,
    p.CREATED_AT,
    p.UPDATED_AT
FROM KBOT_OPS_INSPECTION_PLAN p;

CREATE OR REPLACE VIEW KBOT_V_OPS_INSPECTION_FIRE AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(f.INSPECTION_FIRE_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_FIRE_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_FIRE_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_FIRE_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_FIRE_ID), 21, 12)
    ) AS INSPECTION_FIRE_ID,
    LOWER(
        SUBSTR(RAWTOHEX(f.INSPECTION_PLAN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_PLAN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_PLAN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_PLAN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_PLAN_ID), 21, 12)
    ) AS INSPECTION_PLAN_ID,
    p.DOMAIN_ID,
    f.SCHEDULED_FOR,
    f.STATUS,
    f.TARGET_COUNT,
    f.RUN_COUNT,
    f.COMPLETED_COUNT,
    f.FAILED_COUNT,
    f.SKIP_REASON,
    f.STARTED_AT,
    f.COMPLETED_AT,
    f.CREATED_AT,
    f.UPDATED_AT
FROM KBOT_OPS_INSPECTION_FIRE f
JOIN KBOT_OPS_INSPECTION_PLAN p
    ON p.INSPECTION_PLAN_ID = f.INSPECTION_PLAN_ID;

CREATE OR REPLACE VIEW KBOT_V_OPS_RUN AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 21, 12)
    ) AS OPS_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.TARGET_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 21, 12)
    ) AS TARGET_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.SOURCE_PROPOSAL_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_PROPOSAL_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_PROPOSAL_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_PROPOSAL_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_PROPOSAL_ID), 21, 12)
    ) AS SOURCE_PROPOSAL_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.SOURCE_RESULT_ARTIFACT_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_RESULT_ARTIFACT_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_RESULT_ARTIFACT_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_RESULT_ARTIFACT_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_RESULT_ARTIFACT_ID), 21, 12)
    ) AS SOURCE_RESULT_ARTIFACT_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 21, 12)
    ) AS PARENT_AGENT_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 21, 12)
    ) AS PARENT_DELEGATION_ID,
    t.DOMAIN_ID,
    t.DISPLAY_NAME AS TARGET_NAME,
    r.TRIGGER_TYPE,
    r.ACTOR_ID,
    r.STATUS,
    r.ROOT_CAUSE_LEVEL,
    r.ERROR_CODE,
    r.TRACE_ID,
    r.CREATED_AT,
    r.STARTED_AT,
    r.COMPLETED_AT,
    report_info.REPORT_COUNT,
    report_info.LATEST_REPORT_SUMMARY
FROM KBOT_OPS_RUN r
JOIN KBOT_OPS_TARGET t ON t.TARGET_ID = r.TARGET_ID
LEFT JOIN (
    SELECT
        OPS_RUN_ID,
        COUNT(*) AS REPORT_COUNT,
        MAX(SUMMARY) KEEP (DENSE_RANK LAST ORDER BY UPDATED_AT)
            AS LATEST_REPORT_SUMMARY
    FROM KBOT_OPS_REPORT
    WHERE IS_CURRENT = 1
    GROUP BY OPS_RUN_ID
) report_info ON report_info.OPS_RUN_ID = r.OPS_RUN_ID;

CREATE OR REPLACE VIEW KBOT_V_OPS_PENDING_APPROVAL AS
SELECT
    t.DOMAIN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(p.PROPOSAL_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(p.PROPOSAL_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.PROPOSAL_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.PROPOSAL_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.PROPOSAL_ID), 21, 12)
    ) AS PROPOSAL_ID,
    LOWER(
        SUBSTR(RAWTOHEX(h.HITL_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 21, 12)
    ) AS HITL_ID,
    LOWER(
        SUBSTR(RAWTOHEX(p.OPS_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(p.OPS_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.OPS_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.OPS_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.OPS_RUN_ID), 21, 12)
    ) AS OPS_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(p.TARGET_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(p.TARGET_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.TARGET_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.TARGET_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.TARGET_ID), 21, 12)
    ) AS TARGET_ID,
    t.DISPLAY_NAME AS TARGET_NAME,
    h.ASSIGNEE_USER_ID,
    p.ACTION_TYPE,
    p.ACTION_TEMPLATE_ID,
    p.ACTION_TEMPLATE_VERSION,
    p.RISK_LEVEL,
    p.RATIONALE,
    p.STATUS AS PROPOSAL_STATUS,
    h.STATUS AS HITL_STATUS,
    h.EXPIRES_AT
FROM KBOT_OPS_CHANGE_PROPOSAL p
JOIN KBOT_OPS_HITL h ON h.PROPOSAL_ID = p.PROPOSAL_ID
JOIN KBOT_OPS_TARGET t ON t.TARGET_ID = p.TARGET_ID
WHERE p.STATUS = 'PENDING_APPROVAL'
  AND h.STATUS = 'PENDING'
  AND h.REQUEST_TYPE = 'CHANGE_APPROVAL';

CREATE OR REPLACE VIEW KBOT_V_OPS_REPORT AS
SELECT
    t.DOMAIN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.REPORT_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.REPORT_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.REPORT_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.REPORT_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.REPORT_ID), 21, 12)
    ) AS REPORT_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 21, 12)
    ) AS OPS_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.TARGET_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 21, 12)
    ) AS TARGET_ID,
    t.DISPLAY_NAME AS TARGET_NAME,
    r.REPORT_KEY,
    r.REPORT_VERSION,
    r.REPORT_TYPE,
    r.TITLE,
    r.STATUS,
    r.PERIOD_START,
    r.PERIOD_END,
    r.BASELINE_START,
    r.BASELINE_END,
    r.AFTER_START,
    r.AFTER_END,
    r.RESULT,
    r.SUMMARY,
    r.SECURITY_LEVEL,
    r.CREATED_AT,
    r.UPDATED_AT
FROM KBOT_OPS_REPORT r
JOIN KBOT_OPS_TARGET t ON t.TARGET_ID = r.TARGET_ID
WHERE r.IS_CURRENT = 1;

CREATE OR REPLACE VIEW KBOT_V_OPS_CHAT_PENDING AS
SELECT
    t.DOMAIN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 21, 12)
    ) AS OPS_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 21, 12)
    ) AS PARENT_AGENT_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 21, 12)
    ) AS PARENT_DELEGATION_ID,
    LOWER(
        SUBSTR(RAWTOHEX(h.HITL_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 21, 12)
    ) AS HITL_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.TARGET_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 21, 12)
    ) AS TARGET_ID,
    t.DISPLAY_NAME AS TARGET_NAME,
    h.ASSIGNEE_USER_ID,
    h.REQUEST_TYPE,
    h.PROMPT_TEXT,
    h.REQUESTED_AT,
    h.EXPIRES_AT
FROM KBOT_OPS_HITL h
JOIN KBOT_OPS_RUN r ON r.OPS_RUN_ID = h.OPS_RUN_ID
JOIN KBOT_OPS_TARGET t ON t.TARGET_ID = r.TARGET_ID
WHERE r.TRIGGER_TYPE IN ('CHAT', 'ROOT')
  AND h.STATUS = 'PENDING';

CREATE OR REPLACE VIEW KBOT_V_OPS_SCHEMA_VERSION AS
SELECT
    'AIOPS' AS COMPONENT,
    11 AS SCHEMA_VERSION,
    'aiops-oracle-v2' AS CONTRACT_VERSION
FROM DUAL;

COMMENT ON COLUMN KBOT_OPS_RUN.FINAL_ARTIFACT_ID IS
    'Run 最终不可变产物；延后外键支持同一事务建立循环引用';
COMMENT ON COLUMN KBOT_OPS_TASK.OUTPUT_ARTIFACT_ID IS
    'Task 当前输出指针；Artifact 本身只追加且不可变';
