-- AIOps 应用私有 Agent、不可变版本和用户/角色授权。

CREATE TABLE KBOT_OPS_AGENT (
    AGENT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    CURRENT_VERSION_ID RAW(16),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_AGENT_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_OPS_AGENT_OWNER UNIQUE (AGENT_ID, DOMAIN_ID),
    CONSTRAINT UK_OPS_AGENT_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT CK_OPS_AGENT_STATUS
        CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED')),
    CONSTRAINT CK_OPS_AGENT_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_AGENT_SCOPE_STATUS ON KBOT_OPS_AGENT (DOMAIN_ID, STATUS);

CREATE TABLE KBOT_OPS_AGENT_VERSION (
    AGENT_VERSION_ID RAW(16) PRIMARY KEY,
    AGENT_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    POLICY_ID RAW(16) NOT NULL,
    MODELS_JSON JSON NOT NULL,
    IMAGE_CAPABILITIES_JSON JSON NOT NULL,
    INSTRUCTION CLOB,
    CONFIG_JSON JSON NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_AGENT_VERSION_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES KBOT_OPS_AGENT (AGENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_AGENT_VERSION_POLICY FOREIGN KEY (POLICY_ID)
        REFERENCES KBOT_OPS_POLICY (POLICY_ID),
    CONSTRAINT UK_OPS_AGENT_VERSION UNIQUE (AGENT_ID, VERSION_NO),
    CONSTRAINT UK_OPS_AGENT_VER_OWNER UNIQUE (AGENT_VERSION_ID, AGENT_ID)
);

CREATE INDEX IX_OPS_AGENT_VERSION_AGENT ON KBOT_OPS_AGENT_VERSION (AGENT_ID);
CREATE INDEX IX_OPS_AGENT_VERSION_POLICY
    ON KBOT_OPS_AGENT_VERSION (POLICY_ID);
CREATE TABLE KBOT_OPS_AGENT_VERSION_SOURCE (
    AGENT_VERSION_ID RAW(16) NOT NULL,
    DIAGNOSTIC_SOURCE_ID RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_OPS_AGENT_VERSION_SOURCE
        PRIMARY KEY (AGENT_VERSION_ID, DIAGNOSTIC_SOURCE_ID),
    CONSTRAINT FK_OPS_AGENT_VER_SOURCE_VER FOREIGN KEY (AGENT_VERSION_ID)
        REFERENCES KBOT_OPS_AGENT_VERSION (AGENT_VERSION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_AGENT_VER_SOURCE_SRC FOREIGN KEY (DIAGNOSTIC_SOURCE_ID)
        REFERENCES KBOT_OPS_DIAGNOSTIC_SOURCE (DIAGNOSTIC_SOURCE_ID)
);

CREATE INDEX IX_OPS_AGENT_VER_SOURCE_SRC
    ON KBOT_OPS_AGENT_VERSION_SOURCE (DIAGNOSTIC_SOURCE_ID);

CREATE TABLE KBOT_OPS_AGENT_VERSION_TARGET (
    AGENT_VERSION_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_OPS_AGENT_VERSION_TARGET
        PRIMARY KEY (AGENT_VERSION_ID, TARGET_ID),
    CONSTRAINT FK_OPS_AGENT_VER_TARGET_VER FOREIGN KEY (AGENT_VERSION_ID)
        REFERENCES KBOT_OPS_AGENT_VERSION (AGENT_VERSION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_AGENT_VER_TARGET_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID)
);

CREATE INDEX IX_OPS_AGENT_VER_TARGET_TARGET
    ON KBOT_OPS_AGENT_VERSION_TARGET (TARGET_ID);

ALTER TABLE KBOT_OPS_AGENT ADD CONSTRAINT FK_OPS_AGENT_CURRENT_VERSION
    FOREIGN KEY (CURRENT_VERSION_ID) REFERENCES KBOT_OPS_AGENT_VERSION (AGENT_VERSION_ID);
CREATE INDEX IX_OPS_AGENT_CURRENT_VERSION
    ON KBOT_OPS_AGENT (CURRENT_VERSION_ID);

ALTER TABLE KBOT_OPS_INSPECTION_PLAN
    ADD CONSTRAINT FK_OPS_INSP_PLAN_AGENT
    FOREIGN KEY (AGENT_ID, DOMAIN_ID)
    REFERENCES KBOT_OPS_AGENT (AGENT_ID, DOMAIN_ID);

ALTER TABLE KBOT_OPS_TARGET_BINDING
    ADD CONSTRAINT FK_OPS_BINDING_AGENT
    FOREIGN KEY (AGENT_ID) REFERENCES KBOT_OPS_AGENT (AGENT_ID);

CREATE TABLE KBOT_OPS_AGENT_GRANT (
    AGENT_GRANT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    SUBJECT_TYPE VARCHAR2(16 CHAR) NOT NULL,
    SUBJECT_ID VARCHAR2(256 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_AGENT_GRANT_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_AGENT_GRANT_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES KBOT_OPS_AGENT (AGENT_ID) ON DELETE CASCADE,
    CONSTRAINT UK_OPS_AGENT_GRANT_SUBJECT
        UNIQUE (AGENT_ID, SUBJECT_TYPE, SUBJECT_ID),
    CONSTRAINT CK_OPS_AGENT_GRANT_SUBJECT CHECK (SUBJECT_TYPE IN ('USER', 'ROLE')),
    CONSTRAINT CK_OPS_AGENT_GRANT_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_OPS_AGENT_GRANT_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_AGENT_GRANT_SCOPE ON KBOT_OPS_AGENT_GRANT
    (DOMAIN_ID, SUBJECT_TYPE, SUBJECT_ID, STATUS);
