-- AIOps 专业 DBA 对话、Turn、证据、回答块和报告模板。

CREATE TABLE KBOT_OPS_REPORT_TEMPLATE (
    TEMPLATE_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CURRENT_VERSION_ID RAW(16) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_RPT_TPL_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_OPS_REPORT_TEMPLATE_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT CK_OPS_RPT_TPL_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_OPS_RPT_TPL_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_REPORT_TEMPLATE_SCOPE
    ON KBOT_OPS_REPORT_TEMPLATE (DOMAIN_ID, STATUS);

CREATE TABLE KBOT_OPS_REPORT_TEMPLATE_VER (
    TEMPLATE_VERSION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TEMPLATE_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    DEFINITION_JSON JSON NOT NULL,
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_RPT_TPL_VER_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_RPT_TPL_VER_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
        REFERENCES KBOT_OPS_REPORT_TEMPLATE (TEMPLATE_ID) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT UK_OPS_REPORT_TEMPLATE_VER UNIQUE (TEMPLATE_ID, VERSION_NO),
    CONSTRAINT UK_OPS_REPORT_TEMPLATE_HASH UNIQUE (TEMPLATE_ID, CONTENT_HASH),
    CONSTRAINT CK_OPS_RPT_TPL_VER_NO CHECK (VERSION_NO > 0)
);

CREATE INDEX IX_OPS_RPT_TPL_VER_TEMPLATE
    ON KBOT_OPS_REPORT_TEMPLATE_VER (TEMPLATE_ID);
CREATE INDEX IX_OPS_RPT_TPL_VER_DOMAIN
    ON KBOT_OPS_REPORT_TEMPLATE_VER (DOMAIN_ID);

ALTER TABLE KBOT_OPS_REPORT_TEMPLATE
    ADD CONSTRAINT FK_OPS_RPT_TPL_CURRENT_VERSION
    FOREIGN KEY (CURRENT_VERSION_ID)
    REFERENCES KBOT_OPS_REPORT_TEMPLATE_VER (TEMPLATE_VERSION_ID)
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IX_OPS_RPT_TPL_CURRENT_VERSION
    ON KBOT_OPS_REPORT_TEMPLATE (CURRENT_VERSION_ID);

CREATE TABLE KBOT_OPS_CONVERSATION (
    CONVERSATION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    AGENT_VERSION_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    TITLE VARCHAR2(256 CHAR),
    STATUS VARCHAR2(32 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    SOURCE_TYPE VARCHAR2(24 CHAR) DEFAULT 'CHAT' NOT NULL,
    SOURCE_SITUATION_ID RAW(16),
    SOURCE_RUN_ID RAW(16),
    SOURCE_REPORT_ID RAW(16),
    LAST_TURN_NO NUMBER(19) DEFAULT 0 NOT NULL,
    LAST_MESSAGE_NO NUMBER(19) DEFAULT 0 NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_CONV_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_CONV_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES KBOT_OPS_AGENT (AGENT_ID),
    CONSTRAINT FK_OPS_CONV_AGENT_VER_OWNER
        FOREIGN KEY (AGENT_VERSION_ID, AGENT_ID)
        REFERENCES KBOT_OPS_AGENT_VERSION (AGENT_VERSION_ID, AGENT_ID),
    CONSTRAINT FK_OPS_CONV_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_CONV_SOURCE_SITUATION FOREIGN KEY (SOURCE_SITUATION_ID)
        REFERENCES KBOT_OPS_SITUATION (SITUATION_ID),
    CONSTRAINT FK_OPS_CONV_SOURCE_RUN FOREIGN KEY (SOURCE_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_CONV_SOURCE_REPORT FOREIGN KEY (SOURCE_REPORT_ID)
        REFERENCES KBOT_OPS_REPORT (REPORT_ID),
    CONSTRAINT UK_OPS_CONVERSATION_OWNER UNIQUE (CONVERSATION_ID, DOMAIN_ID),
    CONSTRAINT CK_OPS_CONV_STATUS
        CHECK (STATUS IN ('ACTIVE', 'RESOLVED', 'ARCHIVED')),
    CONSTRAINT CK_OPS_CONV_SOURCE CHECK (SOURCE_TYPE IN ('CHAT', 'SITUATION', 'RUN', 'REPORT')),
    CONSTRAINT CK_OPS_CONV_SOURCE_REF CHECK (
        (SOURCE_TYPE = 'CHAT' AND SOURCE_SITUATION_ID IS NULL
         AND SOURCE_RUN_ID IS NULL AND SOURCE_REPORT_ID IS NULL)
        OR
        (SOURCE_TYPE = 'SITUATION' AND SOURCE_SITUATION_ID IS NOT NULL
         AND SOURCE_RUN_ID IS NULL AND SOURCE_REPORT_ID IS NULL)
        OR
        (SOURCE_TYPE = 'RUN' AND SOURCE_SITUATION_ID IS NULL
         AND SOURCE_RUN_ID IS NOT NULL AND SOURCE_REPORT_ID IS NULL)
        OR
        (SOURCE_TYPE = 'REPORT' AND SOURCE_SITUATION_ID IS NULL
         AND SOURCE_RUN_ID IS NULL AND SOURCE_REPORT_ID IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_CONV_COUNTERS CHECK (
        LAST_TURN_NO >= 0 AND LAST_MESSAGE_NO >= 0 AND ROW_VERSION > 0
    )
);

CREATE INDEX IX_OPS_CONVERSATION_SCOPE
    ON KBOT_OPS_CONVERSATION (DOMAIN_ID, STATUS, UPDATED_AT);
CREATE INDEX IX_OPS_CONV_AGENT ON KBOT_OPS_CONVERSATION (AGENT_ID);
CREATE INDEX IX_OPS_CONV_AGENT_VER
    ON KBOT_OPS_CONVERSATION (AGENT_VERSION_ID, AGENT_ID);
CREATE INDEX IX_OPS_CONV_TARGET
    ON KBOT_OPS_CONVERSATION (TARGET_ID);
CREATE INDEX IX_OPS_CONV_SOURCE_SITUATION
    ON KBOT_OPS_CONVERSATION (SOURCE_SITUATION_ID);
CREATE INDEX IX_OPS_CONV_SOURCE_RUN
    ON KBOT_OPS_CONVERSATION (SOURCE_RUN_ID);
CREATE INDEX IX_OPS_CONV_SOURCE_REPORT
    ON KBOT_OPS_CONVERSATION (SOURCE_REPORT_ID);

CREATE TABLE KBOT_OPS_CONVERSATION_TURN (
    TURN_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    CONVERSATION_ID RAW(16) NOT NULL,
    TURN_NO NUMBER(19) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'QUEUED' NOT NULL,
    RESOLVED_TARGET_ID RAW(16),
    INPUT_ANALYSIS_ARTIFACT_ID RAW(16),
    TASK_FRAME_ARTIFACT_ID RAW(16),
    CURRENT_PLAN_ARTIFACT_ID RAW(16),
    ASSESSMENT_ARTIFACT_ID RAW(16),
    CURRENT_PLAN_REVISION NUMBER(10) DEFAULT 0 NOT NULL,
    INVESTIGATION_ROUND NUMBER(10) DEFAULT 0 NOT NULL,
    TOOL_CALL_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    NO_PROGRESS_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    SUFFICIENCY_STATUS VARCHAR2(32 CHAR),
    SUFFICIENCY_JSON JSON,
    SUFFICIENCY_ARTIFACT_ID RAW(16),
    EVENT_CURSOR NUMBER(19) DEFAULT 0 NOT NULL,
    ERROR_DOMAIN VARCHAR2(32 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CANCEL_REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE,
    CANCEL_REQUESTED_BY VARCHAR2(256 CHAR),
    CONSTRAINT UK_OPS_TURN_NO UNIQUE (CONVERSATION_ID, TURN_NO),
    CONSTRAINT UK_OPS_TURN_IDEMP UNIQUE (CONVERSATION_ID, IDEMPOTENCY_KEY),
    CONSTRAINT UK_OPS_TURN_CONVERSATION UNIQUE (TURN_ID, CONVERSATION_ID),
    CONSTRAINT FK_OPS_TURN_CONVERSATION
        FOREIGN KEY (CONVERSATION_ID, DOMAIN_ID)
        REFERENCES KBOT_OPS_CONVERSATION (CONVERSATION_ID, DOMAIN_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_OPS_TURN_TARGET
        FOREIGN KEY (RESOLVED_TARGET_ID, DOMAIN_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID, DOMAIN_ID),
    CONSTRAINT FK_OPS_TURN_INPUT_ART FOREIGN KEY (INPUT_ANALYSIS_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_TURN_FRAME_ART FOREIGN KEY (TASK_FRAME_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_TURN_PLAN_ART FOREIGN KEY (CURRENT_PLAN_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_TURN_ASSESS_ART FOREIGN KEY (ASSESSMENT_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_TURN_SUFF_ART FOREIGN KEY (SUFFICIENCY_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT CK_OPS_TURN_STATUS CHECK (STATUS IN (
        'QUEUED', 'ACCEPTED', 'UNDERSTANDING', 'PLANNING', 'COLLECTING',
        'ASSESSING', 'REPLANNING', 'ANSWERING', 'WAITING_USER',
        'PROPOSAL_PENDING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED'
    )),
    CONSTRAINT CK_OPS_TURN_SUFFICIENCY CHECK (
        SUFFICIENCY_STATUS IS NULL OR SUFFICIENCY_STATUS IN (
            'ANSWERABLE', 'PARTIAL', 'NEEDS_CLARIFICATION',
            'NEEDS_EVIDENCE', 'CAPABILITY_UNAVAILABLE', 'UNSAFE'
        )
    ),
    CONSTRAINT CK_OPS_TURN_NUMBERS CHECK (
        TURN_NO > 0 AND EVENT_CURSOR >= 0 AND ROW_VERSION > 0
        AND CURRENT_PLAN_REVISION >= 0 AND INVESTIGATION_ROUND >= 0
        AND TOOL_CALL_COUNT >= 0 AND NO_PROGRESS_COUNT >= 0
    ),
    CONSTRAINT CK_OPS_TURN_CANCEL CHECK (
        (CANCEL_REQUESTED_AT IS NULL AND CANCEL_REQUESTED_BY IS NULL)
        OR
        (CANCEL_REQUESTED_AT IS NOT NULL AND CANCEL_REQUESTED_BY IS NOT NULL)
    )
);

CREATE UNIQUE INDEX UX_OPS_TURN_ACTIVE
    ON KBOT_OPS_CONVERSATION_TURN (
        CASE WHEN STATUS IN (
            'UNDERSTANDING', 'PLANNING', 'COLLECTING', 'ASSESSING',
            'REPLANNING', 'ANSWERING'
        ) THEN CONVERSATION_ID END
    );
CREATE INDEX IX_OPS_TURN_SCOPE
    ON KBOT_OPS_CONVERSATION_TURN (DOMAIN_ID, STATUS, UPDATED_AT);
CREATE INDEX IX_OPS_TURN_CONV_STATUS
    ON KBOT_OPS_CONVERSATION_TURN (CONVERSATION_ID, STATUS, TURN_NO);
CREATE INDEX IX_OPS_TURN_CONV_OWNER
    ON KBOT_OPS_CONVERSATION_TURN (CONVERSATION_ID, DOMAIN_ID);
CREATE INDEX IX_OPS_TURN_TARGET
    ON KBOT_OPS_CONVERSATION_TURN (RESOLVED_TARGET_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_TURN_TARGET_OWNER
    ON KBOT_OPS_CONVERSATION_TURN (RESOLVED_TARGET_ID, DOMAIN_ID);
CREATE INDEX IX_OPS_TURN_INPUT_ART
    ON KBOT_OPS_CONVERSATION_TURN (INPUT_ANALYSIS_ARTIFACT_ID);
CREATE INDEX IX_OPS_TURN_FRAME_ART
    ON KBOT_OPS_CONVERSATION_TURN (TASK_FRAME_ARTIFACT_ID);
CREATE INDEX IX_OPS_TURN_PLAN_ART
    ON KBOT_OPS_CONVERSATION_TURN (CURRENT_PLAN_ARTIFACT_ID);
CREATE INDEX IX_OPS_TURN_ASSESS_ART
    ON KBOT_OPS_CONVERSATION_TURN (ASSESSMENT_ARTIFACT_ID);
CREATE INDEX IX_OPS_TURN_SUFF_ART
    ON KBOT_OPS_CONVERSATION_TURN (SUFFICIENCY_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_CONVERSATION_MESSAGE (
    MESSAGE_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    TURN_ID RAW(16) NOT NULL,
    SEQUENCE_NO NUMBER(19) NOT NULL,
    ROLE VARCHAR2(16 CHAR) NOT NULL,
    MESSAGE_TYPE VARCHAR2(32 CHAR) NOT NULL,
    PAYLOAD_SCHEMA VARCHAR2(64 CHAR) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    ARTIFACT_ID RAW(16),
    CREATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_CONV_MSG_TURN
        FOREIGN KEY (TURN_ID, CONVERSATION_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID, CONVERSATION_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_OPS_CONV_MSG_ARTIFACT FOREIGN KEY (ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_CONV_MSG_SEQ UNIQUE (CONVERSATION_ID, SEQUENCE_NO),
    CONSTRAINT UK_OPS_CONV_MSG_OWNER UNIQUE (MESSAGE_ID, TURN_ID),
    CONSTRAINT CK_OPS_CONV_MSG_ROLE CHECK (ROLE IN ('USER', 'AGENT', 'SYSTEM')),
    CONSTRAINT CK_OPS_CONV_MSG_TYPE CHECK (MESSAGE_TYPE IN (
        'USER_MESSAGE', 'ASSISTANT_MESSAGE', 'USER_EVIDENCE', 'SYSTEM_CONTEXT'
    )),
    CONSTRAINT CK_OPS_CONV_MSG_SEQ CHECK (SEQUENCE_NO > 0)
);

CREATE UNIQUE INDEX UX_OPS_TURN_USER_MESSAGE
    ON KBOT_OPS_CONVERSATION_MESSAGE (
        CASE WHEN MESSAGE_TYPE = 'USER_MESSAGE' THEN TURN_ID END
    );
CREATE INDEX IX_OPS_CONV_MSG_TURN
    ON KBOT_OPS_CONVERSATION_MESSAGE (TURN_ID, CREATED_AT);
CREATE INDEX IX_OPS_CONV_MSG_TURN_OWNER
    ON KBOT_OPS_CONVERSATION_MESSAGE (TURN_ID, CONVERSATION_ID);
CREATE INDEX IX_OPS_CONV_MSG_ARTIFACT
    ON KBOT_OPS_CONVERSATION_MESSAGE (ARTIFACT_ID);

CREATE TABLE KBOT_OPS_TURN_INPUT_ITEM (
    INPUT_ITEM_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    MESSAGE_ID RAW(16) NOT NULL,
    ITEM_NO NUMBER(10) NOT NULL,
    CONTENT_TYPE VARCHAR2(24 CHAR) NOT NULL,
    MEDIA_TYPE VARCHAR2(128 CHAR),
    CONTENT_TEXT CLOB,
    SOURCE_ARTIFACT_ID RAW(16),
    EXTRACTED_ARTIFACT_ID RAW(16),
    DETECTED_KIND VARCHAR2(32 CHAR),
    DETECTION_CONFIDENCE NUMBER(5,4),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_INPUT_ITEM_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_INPUT_ITEM_MSG FOREIGN KEY (MESSAGE_ID, TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_MESSAGE (MESSAGE_ID, TURN_ID),
    CONSTRAINT FK_OPS_INPUT_ITEM_SOURCE FOREIGN KEY (SOURCE_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_INPUT_ITEM_EXTRACT FOREIGN KEY (EXTRACTED_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_INPUT_ITEM_NO UNIQUE (TURN_ID, ITEM_NO),
    CONSTRAINT CK_OPS_INPUT_ITEM_TYPE CHECK (CONTENT_TYPE IN (
        'TEXT', 'IMAGE', 'FILE', 'SQL_OUTPUT', 'COMMAND_OUTPUT', 'LOG'
    )),
    CONSTRAINT CK_OPS_INPUT_ITEM_VALUE CHECK (
        CONTENT_TEXT IS NOT NULL OR SOURCE_ARTIFACT_ID IS NOT NULL
    ),
    CONSTRAINT CK_OPS_INPUT_ITEM_NUM CHECK (
        ITEM_NO > 0 AND (
            DETECTION_CONFIDENCE IS NULL
            OR (DETECTION_CONFIDENCE >= 0 AND DETECTION_CONFIDENCE <= 1)
        )
    )
);

CREATE INDEX IX_OPS_INPUT_ITEM_MSG
    ON KBOT_OPS_TURN_INPUT_ITEM (MESSAGE_ID, TURN_ID);
CREATE INDEX IX_OPS_INPUT_ITEM_SOURCE
    ON KBOT_OPS_TURN_INPUT_ITEM (SOURCE_ARTIFACT_ID);
CREATE INDEX IX_OPS_INPUT_ITEM_EXTRACT
    ON KBOT_OPS_TURN_INPUT_ITEM (EXTRACTED_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_TURN_RUN (
    TURN_RUN_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    OPS_RUN_ID RAW(16) NOT NULL,
    PURPOSE VARCHAR2(32 CHAR) NOT NULL,
    SEQUENCE_NO NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_TURN_RUN_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_TURN_RUN_RUNTIME FOREIGN KEY (OPS_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT UK_OPS_TURN_RUN UNIQUE (OPS_RUN_ID),
    CONSTRAINT UK_OPS_TURN_RUN_SEQ UNIQUE (TURN_ID, SEQUENCE_NO),
    CONSTRAINT CK_OPS_TURN_RUN_PURPOSE CHECK (PURPOSE IN (
        'PRIMARY', 'EVIDENCE_BRANCH', 'CHANGE', 'VERIFICATION',
        'MEDIA_PROCESSING'
    )),
    CONSTRAINT CK_OPS_TURN_RUN_SEQ CHECK (SEQUENCE_NO > 0)
);

CREATE UNIQUE INDEX UX_OPS_TURN_PRIMARY_RUN
    ON KBOT_OPS_TURN_RUN (
        CASE WHEN PURPOSE = 'PRIMARY' THEN TURN_ID END
    );
CREATE TABLE KBOT_OPS_INVESTIGATION_REVISION (
    REVISION_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    REVISION_NO NUMBER(10) NOT NULL,
    REVISION_TYPE VARCHAR2(24 CHAR) NOT NULL,
    TRIGGER_REASON VARCHAR2(1000 CHAR) NOT NULL,
    TASK_FRAME_ARTIFACT_ID RAW(16),
    PLAN_ARTIFACT_ID RAW(16) NOT NULL,
    ASSESSMENT_ARTIFACT_ID RAW(16),
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_INV_REV_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_INV_REV_FRAME FOREIGN KEY (TASK_FRAME_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_INV_REV_PLAN FOREIGN KEY (PLAN_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_INV_REV_ASSESS FOREIGN KEY (ASSESSMENT_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_INV_REV_NO UNIQUE (TURN_ID, REVISION_NO),
    CONSTRAINT CK_OPS_INV_REV_TYPE CHECK (REVISION_TYPE IN (
        'INITIAL', 'EVIDENCE_DRIVEN', 'USER_CLARIFICATION', 'RECOVERY'
    )),
    CONSTRAINT CK_OPS_INV_REV_NO CHECK (REVISION_NO > 0)
);

CREATE INDEX IX_OPS_INV_REV_FRAME
    ON KBOT_OPS_INVESTIGATION_REVISION (TASK_FRAME_ARTIFACT_ID);
CREATE INDEX IX_OPS_INV_REV_PLAN
    ON KBOT_OPS_INVESTIGATION_REVISION (PLAN_ARTIFACT_ID);
CREATE INDEX IX_OPS_INV_REV_ASSESS
    ON KBOT_OPS_INVESTIGATION_REVISION (ASSESSMENT_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_PLAYBOOK_INVOCATION (
    PLAYBOOK_INVOCATION_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    REVISION_ID RAW(16) NOT NULL,
    PARENT_INVOCATION_ID RAW(16),
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16),
    ORDINAL NUMBER(10) NOT NULL,
    PLAYBOOK_ID VARCHAR2(128 CHAR) NOT NULL,
    PLAYBOOK_VERSION VARCHAR2(64 CHAR) NOT NULL,
    MANIFEST_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    INPUT_SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    INPUT_JSON JSON NOT NULL,
    OUTPUT_ARTIFACT_ID RAW(16),
    ATTEMPT_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    ERROR_DOMAIN VARCHAR2(32 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_OPS_PLAY_INV_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_PLAY_INV_REV FOREIGN KEY (REVISION_ID)
        REFERENCES KBOT_OPS_INVESTIGATION_REVISION (REVISION_ID),
    CONSTRAINT FK_OPS_PLAY_INV_PARENT FOREIGN KEY (PARENT_INVOCATION_ID)
        REFERENCES KBOT_OPS_PLAYBOOK_INVOCATION (PLAYBOOK_INVOCATION_ID),
    CONSTRAINT FK_OPS_PLAY_INV_RUN FOREIGN KEY (OPS_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_PLAY_INV_TASK FOREIGN KEY (OPS_TASK_ID)
        REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_PLAY_INV_OUTPUT FOREIGN KEY (OUTPUT_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_PLAY_INV_ORD UNIQUE (REVISION_ID, ORDINAL),
    CONSTRAINT CK_OPS_PLAY_INV_STATUS CHECK (STATUS IN (
        'PLANNED', 'READY', 'RUNNING', 'SUCCEEDED', 'PARTIAL',
        'FAILED', 'SKIPPED', 'CANCELLED'
    )),
    CONSTRAINT CK_OPS_PLAY_INV_NUMBERS CHECK (
        ORDINAL > 0 AND ATTEMPT_COUNT >= 0 AND ROW_VERSION > 0
    ),
    CONSTRAINT CK_OPS_PLAY_INV_HASH CHECK (LENGTH(MANIFEST_HASH) = 64)
);

CREATE INDEX IX_OPS_PLAY_INV_TURN
    ON KBOT_OPS_PLAYBOOK_INVOCATION (TURN_ID, STATUS, ORDINAL);
CREATE INDEX IX_OPS_PLAY_INV_CATALOG
    ON KBOT_OPS_PLAYBOOK_INVOCATION (PLAYBOOK_ID, PLAYBOOK_VERSION, CREATED_AT);
CREATE INDEX IX_OPS_PLAY_INV_TASK
    ON KBOT_OPS_PLAYBOOK_INVOCATION (OPS_TASK_ID);
CREATE INDEX IX_OPS_PLAY_INV_PARENT
    ON KBOT_OPS_PLAYBOOK_INVOCATION (PARENT_INVOCATION_ID);
CREATE INDEX IX_OPS_PLAY_INV_OUTPUT
    ON KBOT_OPS_PLAYBOOK_INVOCATION (OUTPUT_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_TOOL_INVOCATION (
    TOOL_INVOCATION_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    REVISION_ID RAW(16) NOT NULL,
    PLAYBOOK_INVOCATION_ID RAW(16),
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16),
    ORDINAL NUMBER(10) NOT NULL,
    ACTION_ID VARCHAR2(32 CHAR) NOT NULL,
    TOOL_ID VARCHAR2(128 CHAR) NOT NULL,
    TOOL_VERSION VARCHAR2(64 CHAR) NOT NULL,
    TOOL_CLASS VARCHAR2(32 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    INPUT_JSON JSON NOT NULL,
    POLICY_HASH VARCHAR2(64 CHAR) NOT NULL,
    OUTPUT_ARTIFACT_ID RAW(16),
    ATTEMPT_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    ERROR_DOMAIN VARCHAR2(32 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_OPS_TOOL_INV_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_TOOL_INV_REV FOREIGN KEY (REVISION_ID)
        REFERENCES KBOT_OPS_INVESTIGATION_REVISION (REVISION_ID),
    CONSTRAINT FK_OPS_TOOL_INV_PLAY FOREIGN KEY (PLAYBOOK_INVOCATION_ID)
        REFERENCES KBOT_OPS_PLAYBOOK_INVOCATION (PLAYBOOK_INVOCATION_ID),
    CONSTRAINT FK_OPS_TOOL_INV_RUN FOREIGN KEY (OPS_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_TOOL_INV_TASK FOREIGN KEY (OPS_TASK_ID)
        REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_TOOL_INV_OUTPUT FOREIGN KEY (OUTPUT_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_TOOL_INV_ORD UNIQUE (REVISION_ID, ORDINAL),
    CONSTRAINT UK_OPS_TOOL_INV_ACTION UNIQUE (REVISION_ID, ACTION_ID),
    CONSTRAINT CK_OPS_TOOL_INV_CLASS CHECK (TOOL_CLASS IN (
        'PROMETHEUS', 'LOKI', 'ORACLE_SQL', 'HOST', 'MEDIA', 'REASONING'
    )),
    CONSTRAINT CK_OPS_TOOL_INV_STATUS CHECK (STATUS IN (
        'PLANNED', 'READY', 'RUNNING', 'SUCCEEDED', 'NO_DATA',
        'FAILED', 'SKIPPED', 'CANCELLED'
    )),
    CONSTRAINT CK_OPS_TOOL_INV_NUMBERS CHECK (
        ORDINAL > 0 AND ATTEMPT_COUNT >= 0 AND ROW_VERSION > 0
    ),
    CONSTRAINT CK_OPS_TOOL_INV_POLICY_HASH CHECK (
        REGEXP_LIKE(POLICY_HASH, '^[0-9a-f]{64}$')
    )
);

CREATE INDEX IX_OPS_TOOL_INV_TURN
    ON KBOT_OPS_TOOL_INVOCATION (TURN_ID, STATUS, ORDINAL);
CREATE INDEX IX_OPS_TOOL_INV_REV
    ON KBOT_OPS_TOOL_INVOCATION (REVISION_ID, STATUS);
CREATE INDEX IX_OPS_TOOL_INV_PLAY
    ON KBOT_OPS_TOOL_INVOCATION (PLAYBOOK_INVOCATION_ID);
CREATE INDEX IX_OPS_TOOL_INV_TASK
    ON KBOT_OPS_TOOL_INVOCATION (OPS_TASK_ID);
CREATE INDEX IX_OPS_TOOL_INV_OUTPUT
    ON KBOT_OPS_TOOL_INVOCATION (OUTPUT_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_TURN_EVIDENCE (
    TURN_EVIDENCE_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    ARTIFACT_ID RAW(16) NOT NULL,
    TOOL_INVOCATION_ID RAW(16),
    SOURCE_KIND VARCHAR2(32 CHAR) NOT NULL,
    EVIDENCE_KIND VARCHAR2(32 CHAR) NOT NULL,
    CONFIDENCE NUMBER(5,4),
    EXTRACTION_ARTIFACT_ID RAW(16),
    EVIDENCE_ROLE VARCHAR2(24 CHAR) NOT NULL,
    MEASUREMENT_SEMANTICS VARCHAR2(32 CHAR) NOT NULL,
    OBSERVED_AT TIMESTAMP(6) WITH TIME ZONE,
    WINDOW_START_AT TIMESTAMP(6) WITH TIME ZONE,
    WINDOW_END_AT TIMESTAMP(6) WITH TIME ZONE,
    FRESHNESS_STATUS VARCHAR2(16 CHAR) NOT NULL,
    USAGE_REASON VARCHAR2(1000 CHAR) NOT NULL,
    LINKED_BY VARCHAR2(256 CHAR) NOT NULL,
    LINKED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_TURN_EVID_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_TURN_EVID_ART FOREIGN KEY (ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_TURN_EVID_TOOL FOREIGN KEY (TOOL_INVOCATION_ID)
        REFERENCES KBOT_OPS_TOOL_INVOCATION (TOOL_INVOCATION_ID),
    CONSTRAINT FK_OPS_TURN_EVID_EXTRACT FOREIGN KEY (EXTRACTION_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_TURN_EVIDENCE
        UNIQUE (TURN_ID, ARTIFACT_ID, EVIDENCE_ROLE),
    CONSTRAINT CK_OPS_TURN_EVID_ROLE CHECK (EVIDENCE_ROLE IN (
        'SUPPORTS', 'CONTRADICTS', 'CONTEXT', 'USER_PROVIDED'
    )),
    CONSTRAINT CK_OPS_TURN_EVID_SEMANTICS CHECK (MEASUREMENT_SEMANTICS IN (
        'CURRENT_ACTIVITY', 'CUMULATIVE_SINCE_LOAD', 'SNAPSHOT_DELTA',
        'HISTORICAL_SAMPLES', 'NOT_APPLICABLE'
    )),
    CONSTRAINT CK_OPS_TURN_EVID_FRESH CHECK (
        FRESHNESS_STATUS IN ('FRESH', 'STALE', 'UNKNOWN')
    ),
    CONSTRAINT CK_OPS_TURN_EVID_CONF CHECK (
        CONFIDENCE IS NULL OR (CONFIDENCE >= 0 AND CONFIDENCE <= 1)
    ),
    CONSTRAINT CK_OPS_TURN_EVID_WINDOW CHECK (
        (WINDOW_START_AT IS NULL AND WINDOW_END_AT IS NULL)
        OR
        (WINDOW_START_AT IS NOT NULL AND WINDOW_END_AT IS NOT NULL
         AND WINDOW_END_AT > WINDOW_START_AT)
    )
);

CREATE INDEX IX_OPS_TURN_EVID_TURN
    ON KBOT_OPS_TURN_EVIDENCE (TURN_ID, EVIDENCE_ROLE, LINKED_AT);
CREATE INDEX IX_OPS_TURN_EVID_ART
    ON KBOT_OPS_TURN_EVIDENCE (ARTIFACT_ID);
CREATE INDEX IX_OPS_TURN_EVID_TOOL
    ON KBOT_OPS_TURN_EVIDENCE (TOOL_INVOCATION_ID);
CREATE INDEX IX_OPS_TURN_EVID_EXTRACT
    ON KBOT_OPS_TURN_EVIDENCE (EXTRACTION_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_ANSWER_BLOCK (
    ANSWER_BLOCK_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    MESSAGE_ID RAW(16) NOT NULL,
    BLOCK_NO NUMBER(10) NOT NULL,
    BLOCK_TYPE VARCHAR2(32 CHAR) NOT NULL,
    SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    SUPERSEDES_ID RAW(16),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_ANSWER_BLOCK_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_ANSWER_BLOCK_MESSAGE
        FOREIGN KEY (MESSAGE_ID, TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_MESSAGE (MESSAGE_ID, TURN_ID),
    CONSTRAINT FK_OPS_ANSWER_BLOCK_SUPERSEDES FOREIGN KEY (SUPERSEDES_ID)
        REFERENCES KBOT_OPS_ANSWER_BLOCK (ANSWER_BLOCK_ID),
    CONSTRAINT UK_OPS_ANSWER_BLOCK_NO UNIQUE (MESSAGE_ID, BLOCK_NO),
    CONSTRAINT CK_OPS_ANSWER_BLOCK_TYPE CHECK (BLOCK_TYPE IN (
        'MARKDOWN', 'TABLE', 'CHART', 'EVIDENCE_REFERENCES',
        'CLARIFICATION', 'EVIDENCE_REQUEST', 'PROPOSAL_SUMMARY',
        'VERIFICATION_COMPARISON'
    )),
    CONSTRAINT CK_OPS_ANSWER_BLOCK_STATUS
        CHECK (STATUS IN ('ACTIVE', 'SUPERSEDED')),
    CONSTRAINT CK_OPS_ANSWER_BLOCK_NO CHECK (BLOCK_NO > 0),
    CONSTRAINT CK_OPS_ANSWER_BLOCK_HASH CHECK (LENGTH(CONTENT_HASH) = 64)
);

CREATE INDEX IX_OPS_ANSWER_BLOCK_TURN
    ON KBOT_OPS_ANSWER_BLOCK (TURN_ID, STATUS, BLOCK_NO);
CREATE INDEX IX_OPS_ANSWER_BLOCK_MSG_OWNER
    ON KBOT_OPS_ANSWER_BLOCK (MESSAGE_ID, TURN_ID);
CREATE INDEX IX_OPS_ANSWER_BLOCK_SUPERSEDES
    ON KBOT_OPS_ANSWER_BLOCK (SUPERSEDES_ID);

CREATE TABLE KBOT_OPS_ANSWER_CITATION (
    ANSWER_BLOCK_ID RAW(16) NOT NULL,
    CITATION_NO NUMBER(10) NOT NULL,
    TURN_EVIDENCE_ID RAW(16) NOT NULL,
    LABEL VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_OPS_ANSWER_CITATION PRIMARY KEY (ANSWER_BLOCK_ID, CITATION_NO),
    CONSTRAINT FK_OPS_ANSWER_CIT_BLOCK FOREIGN KEY (ANSWER_BLOCK_ID)
        REFERENCES KBOT_OPS_ANSWER_BLOCK (ANSWER_BLOCK_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_ANSWER_CIT_EVID FOREIGN KEY (TURN_EVIDENCE_ID)
        REFERENCES KBOT_OPS_TURN_EVIDENCE (TURN_EVIDENCE_ID),
    CONSTRAINT UK_OPS_ANSWER_CIT_EVID
        UNIQUE (ANSWER_BLOCK_ID, TURN_EVIDENCE_ID),
    CONSTRAINT CK_OPS_ANSWER_CIT_NO CHECK (CITATION_NO > 0)
);

CREATE INDEX IX_OPS_ANSWER_CIT_EVID
    ON KBOT_OPS_ANSWER_CITATION (TURN_EVIDENCE_ID);

CREATE TABLE KBOT_OPS_TURN_EVENT (
    TURN_ID RAW(16) NOT NULL,
    SEQUENCE_NO NUMBER(19) NOT NULL,
    EVENT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    EVENT_KEY VARCHAR2(128 CHAR),
    VISIBILITY VARCHAR2(16 CHAR) NOT NULL,
    PLAYBOOK_INVOCATION_ID RAW(16),
    TOOL_INVOCATION_ID RAW(16),
    ANSWER_BLOCK_ID RAW(16),
    PAYLOAD_JSON JSON NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_OPS_TURN_EVENT PRIMARY KEY (TURN_ID, SEQUENCE_NO),
    CONSTRAINT FK_OPS_TURN_EVENT_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_TURN_EVENT_PLAY FOREIGN KEY (PLAYBOOK_INVOCATION_ID)
        REFERENCES KBOT_OPS_PLAYBOOK_INVOCATION (PLAYBOOK_INVOCATION_ID),
    CONSTRAINT FK_OPS_TURN_EVENT_TOOL FOREIGN KEY (TOOL_INVOCATION_ID)
        REFERENCES KBOT_OPS_TOOL_INVOCATION (TOOL_INVOCATION_ID),
    CONSTRAINT FK_OPS_TURN_EVENT_BLOCK FOREIGN KEY (ANSWER_BLOCK_ID)
        REFERENCES KBOT_OPS_ANSWER_BLOCK (ANSWER_BLOCK_ID),
    CONSTRAINT CK_OPS_TURN_EVENT_VISIBILITY
        CHECK (VISIBILITY IN ('INTERNAL', 'USER')),
    CONSTRAINT CK_OPS_TURN_EVENT_SEQ CHECK (SEQUENCE_NO > 0)
);

CREATE UNIQUE INDEX UX_OPS_TURN_EVENT_KEY
    ON KBOT_OPS_TURN_EVENT (
        TURN_ID,
        CASE WHEN EVENT_KEY IS NOT NULL THEN EVENT_KEY END
    );
CREATE INDEX IX_OPS_TURN_EVENT_PLAY
    ON KBOT_OPS_TURN_EVENT (PLAYBOOK_INVOCATION_ID);
CREATE INDEX IX_OPS_TURN_EVENT_TOOL
    ON KBOT_OPS_TURN_EVENT (TOOL_INVOCATION_ID);
CREATE INDEX IX_OPS_TURN_EVENT_BLOCK
    ON KBOT_OPS_TURN_EVENT (ANSWER_BLOCK_ID);

CREATE TABLE KBOT_OPS_EVIDENCE_REQUEST (
    REQUEST_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    PARENT_REQUEST_ID RAW(16),
    REQUEST_TYPE VARCHAR2(24 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'OPEN' NOT NULL,
    INSTRUCTION_TEXT CLOB NOT NULL,
    REQUEST_SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    REQUEST_JSON JSON NOT NULL,
    QUERY_ARTIFACT_ID RAW(16),
    RESPONSE_ARTIFACT_ID RAW(16),
    FAILURE_CLASS VARCHAR2(48 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    REQUESTED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_OPS_EVID_REQ_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_EVID_REQ_PARENT FOREIGN KEY (PARENT_REQUEST_ID)
        REFERENCES KBOT_OPS_EVIDENCE_REQUEST (REQUEST_ID),
    CONSTRAINT FK_OPS_EVID_REQ_QUERY FOREIGN KEY (QUERY_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_EVID_REQ_RESPONSE FOREIGN KEY (RESPONSE_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT CK_OPS_EVID_REQ_TYPE CHECK (REQUEST_TYPE IN (
        'TEXT', 'SQL_OUTPUT', 'COMMAND_OUTPUT', 'SCREENSHOT', 'FILE'
    )),
    CONSTRAINT CK_OPS_EVID_REQ_STATUS CHECK (STATUS IN (
        'OPEN', 'RECEIVED', 'SKIPPED', 'FAILED',
        'EXPIRED', 'CANCELLED'
    )),
    CONSTRAINT CK_OPS_EVID_REQ_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_EVID_REQ_TURN
    ON KBOT_OPS_EVIDENCE_REQUEST (TURN_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_EVID_REQ_PARENT
    ON KBOT_OPS_EVIDENCE_REQUEST (PARENT_REQUEST_ID);
CREATE INDEX IX_OPS_EVID_REQ_QUERY
    ON KBOT_OPS_EVIDENCE_REQUEST (QUERY_ARTIFACT_ID);
CREATE INDEX IX_OPS_EVID_REQ_RESPONSE
    ON KBOT_OPS_EVIDENCE_REQUEST (RESPONSE_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_IMAGE_EVIDENCE (
    PROCESSING_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    EVIDENCE_REQUEST_ID RAW(16) NOT NULL,
    SOURCE_ARTIFACT_ID RAW(16) NOT NULL,
    PROCESSING_MODE VARCHAR2(8 CHAR) NOT NULL,
    MODEL_ID RAW(16) NOT NULL,
    MODEL_REVISION VARCHAR2(128 CHAR) NOT NULL,
    INPUT_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'PENDING' NOT NULL,
    OUTPUT_ARTIFACT_ID RAW(16),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_IMG_EVID_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_IMG_EVID_REQ FOREIGN KEY (EVIDENCE_REQUEST_ID)
        REFERENCES KBOT_OPS_EVIDENCE_REQUEST (REQUEST_ID),
    CONSTRAINT FK_OPS_IMG_EVID_SOURCE FOREIGN KEY (SOURCE_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_IMG_EVID_OUTPUT FOREIGN KEY (OUTPUT_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT CK_OPS_IMG_EVID_MODE CHECK (PROCESSING_MODE IN ('OCR', 'VLM')),
    CONSTRAINT CK_OPS_IMG_EVID_STATUS CHECK (
        STATUS IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED')
    ),
    CONSTRAINT CK_OPS_IMG_EVID_HASH CHECK (LENGTH(INPUT_HASH) = 64)
);

CREATE INDEX IX_OPS_IMG_EVID_TURN
    ON KBOT_OPS_IMAGE_EVIDENCE (TURN_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_IMG_EVID_REQ
    ON KBOT_OPS_IMAGE_EVIDENCE (EVIDENCE_REQUEST_ID);
CREATE INDEX IX_OPS_IMG_EVID_SOURCE
    ON KBOT_OPS_IMAGE_EVIDENCE (SOURCE_ARTIFACT_ID);
CREATE INDEX IX_OPS_IMG_EVID_OUTPUT
    ON KBOT_OPS_IMAGE_EVIDENCE (OUTPUT_ARTIFACT_ID);

ALTER TABLE KBOT_OPS_RUN
    ADD CONSTRAINT FK_OPS_RUN_AGENT_VERSION
    FOREIGN KEY (AGENT_VERSION_ID)
    REFERENCES KBOT_OPS_AGENT_VERSION (AGENT_VERSION_ID);

ALTER TABLE KBOT_OPS_CHANGE_PROPOSAL
    ADD CONSTRAINT FK_OPS_PROPOSAL_TURN
    FOREIGN KEY (TURN_ID)
    REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID);
