-- AIOps 对话、人工证据、逐条动作和报告模板。

CREATE TABLE KBOT_OPS_REPORT_TEMPLATE (
    TEMPLATE_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CURRENT_VERSION_ID RAW(16) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_RPT_TPL_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_OPS_REPORT_TEMPLATE_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT CK_OPS_RPT_TPL_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_OPS_RPT_TPL_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_REPORT_TEMPLATE_SCOPE
    ON KBOT_OPS_REPORT_TEMPLATE (DOMAIN_ID, STATUS);

CREATE TABLE KBOT_OPS_REPORT_TEMPLATE_VER (
    TEMPLATE_VERSION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TEMPLATE_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    DEFINITION_JSON JSON NOT NULL,
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_RPT_TPL_VER_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_RPT_TPL_VER_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
        REFERENCES KBOT_OPS_REPORT_TEMPLATE (TEMPLATE_ID) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT UK_OPS_REPORT_TEMPLATE_VER UNIQUE (TEMPLATE_ID, VERSION_NO),
    CONSTRAINT UK_OPS_REPORT_TEMPLATE_HASH UNIQUE (TEMPLATE_ID, CONTENT_HASH),
    CONSTRAINT CK_OPS_RPT_TPL_VER_NO CHECK (VERSION_NO > 0)
);

CREATE INDEX IX_OPS_RPT_TPL_VER_TEMPLATE
    ON KBOT_OPS_REPORT_TEMPLATE_VER (TEMPLATE_ID);
CREATE INDEX IX_OPS_RPT_TPL_VER_DOMAIN
    ON KBOT_OPS_REPORT_TEMPLATE_VER (DOMAIN_ID);

ALTER TABLE KBOT_OPS_REPORT_TEMPLATE
    ADD CONSTRAINT FK_OPS_RPT_TPL_CURRENT_VERSION
    FOREIGN KEY (CURRENT_VERSION_ID)
    REFERENCES KBOT_OPS_REPORT_TEMPLATE_VER (TEMPLATE_VERSION_ID)
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IX_OPS_RPT_TPL_CURRENT_VERSION
    ON KBOT_OPS_REPORT_TEMPLATE (CURRENT_VERSION_ID);

CREATE TABLE KBOT_OPS_CONVERSATION (
    CONVERSATION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    AGENT_VERSION_ID RAW(16) NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    SOURCE_TYPE VARCHAR2(24 CHAR) DEFAULT 'CHAT' NOT NULL,
    SOURCE_ALERT_ID RAW(16),
    SOURCE_RUN_ID RAW(16),
    SOURCE_REPORT_ID RAW(16),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_CONV_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_CONV_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES KBOT_OPS_AGENT (AGENT_ID),
    CONSTRAINT FK_OPS_CONV_AGENT_VER FOREIGN KEY (AGENT_VERSION_ID)
        REFERENCES KBOT_OPS_AGENT_VERSION (AGENT_VERSION_ID),
    CONSTRAINT FK_OPS_CONV_SOURCE_ALERT FOREIGN KEY (SOURCE_ALERT_ID)
        REFERENCES KBOT_OPS_ALERT (ALERT_ID),
    CONSTRAINT FK_OPS_CONV_SOURCE_RUN FOREIGN KEY (SOURCE_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_CONV_SOURCE_REPORT FOREIGN KEY (SOURCE_REPORT_ID)
        REFERENCES KBOT_OPS_REPORT (REPORT_ID),
    CONSTRAINT CK_OPS_CONV_STATUS CHECK (STATUS IN ('ACTIVE', 'WAITING_EVIDENCE', 'RESOLVED', 'ARCHIVED')),
    CONSTRAINT CK_OPS_CONV_SOURCE CHECK (SOURCE_TYPE IN ('CHAT', 'ALERT', 'RUN', 'REPORT')),
    CONSTRAINT CK_OPS_CONV_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_CONVERSATION_SCOPE
    ON KBOT_OPS_CONVERSATION (DOMAIN_ID, STATUS, UPDATED_AT);
CREATE INDEX IX_OPS_CONV_AGENT ON KBOT_OPS_CONVERSATION (AGENT_ID);
CREATE INDEX IX_OPS_CONV_AGENT_VER
    ON KBOT_OPS_CONVERSATION (AGENT_VERSION_ID);
CREATE INDEX IX_OPS_CONV_SOURCE_ALERT
    ON KBOT_OPS_CONVERSATION (SOURCE_ALERT_ID);
CREATE INDEX IX_OPS_CONV_SOURCE_RUN
    ON KBOT_OPS_CONVERSATION (SOURCE_RUN_ID);
CREATE INDEX IX_OPS_CONV_SOURCE_REPORT
    ON KBOT_OPS_CONVERSATION (SOURCE_REPORT_ID);

CREATE TABLE KBOT_OPS_CONVERSATION_MESSAGE (
    MESSAGE_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    SEQUENCE_NO NUMBER(19) NOT NULL,
    ROLE VARCHAR2(16 CHAR) NOT NULL,
    MESSAGE_TYPE VARCHAR2(48 CHAR) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    ARTIFACT_ID RAW(16),
    CREATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_CONV_MSG_CONV FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_OPS_CONVERSATION (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_CONV_MSG_ARTIFACT FOREIGN KEY (ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_CONV_MSG_SEQ UNIQUE (CONVERSATION_ID, SEQUENCE_NO),
    CONSTRAINT CK_OPS_CONV_MSG_ROLE CHECK (ROLE IN ('USER', 'AGENT', 'SYSTEM')),
    CONSTRAINT CK_OPS_CONV_MSG_SEQ CHECK (SEQUENCE_NO > 0)
);

CREATE INDEX IX_OPS_CONV_MSG_CONV
    ON KBOT_OPS_CONVERSATION_MESSAGE (CONVERSATION_ID, CREATED_AT);
CREATE INDEX IX_OPS_CONV_MSG_ARTIFACT
    ON KBOT_OPS_CONVERSATION_MESSAGE (ARTIFACT_ID);

CREATE TABLE KBOT_OPS_CONVERSATION_RUN (
    CONVERSATION_RUN_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    OPS_RUN_ID RAW(16) NOT NULL,
    PURPOSE VARCHAR2(48 CHAR) NOT NULL,
    SEQUENCE_NO NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_CONV_RUN_CONV FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_OPS_CONVERSATION (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_CONV_RUN_RUNTIME FOREIGN KEY (OPS_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT UK_OPS_CONV_RUN UNIQUE (OPS_RUN_ID),
    CONSTRAINT UK_OPS_CONV_RUN_SEQ UNIQUE (CONVERSATION_ID, SEQUENCE_NO),
    CONSTRAINT CK_OPS_CONV_RUN_SEQ CHECK (SEQUENCE_NO > 0)
);

CREATE INDEX IX_OPS_CONV_RUN_CONV
    ON KBOT_OPS_CONVERSATION_RUN (CONVERSATION_ID, CREATED_AT);

CREATE TABLE KBOT_OPS_EVIDENCE_REQUEST (
    REQUEST_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    PARENT_REQUEST_ID RAW(16),
    STATUS VARCHAR2(24 CHAR) DEFAULT 'OPEN' NOT NULL,
    PURPOSE CLOB NOT NULL,
    SUGGESTED_SQL CLOB,
    SQL_HASH VARCHAR2(64 CHAR),
    FAILURE_CLASS VARCHAR2(48 CHAR),
    REQUESTED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_EVID_REQ_CONV FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_OPS_CONVERSATION (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_EVID_REQ_PARENT FOREIGN KEY (PARENT_REQUEST_ID)
        REFERENCES KBOT_OPS_EVIDENCE_REQUEST (REQUEST_ID),
    CONSTRAINT CK_OPS_EVID_REQ_STATUS
        CHECK (STATUS IN ('OPEN', 'RECEIVED', 'SKIPPED', 'FAILED'))
);

CREATE INDEX IX_OPS_EVID_REQ_CONV
    ON KBOT_OPS_EVIDENCE_REQUEST (CONVERSATION_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_EVID_REQ_PARENT
    ON KBOT_OPS_EVIDENCE_REQUEST (PARENT_REQUEST_ID);

CREATE TABLE KBOT_OPS_ACTION_STEP (
    ACTION_STEP_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    PROPOSAL_ID RAW(16),
    ORDINAL NUMBER(10) NOT NULL,
    SQL_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'DRAFT' NOT NULL,
    SUPERSEDES_STEP_ID RAW(16),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_ACTION_STEP_CONV FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_OPS_CONVERSATION (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_ACTION_STEP_PROP FOREIGN KEY (PROPOSAL_ID)
        REFERENCES KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_ID),
    CONSTRAINT FK_OPS_ACTION_STEP_SUPERSEDES FOREIGN KEY (SUPERSEDES_STEP_ID)
        REFERENCES KBOT_OPS_ACTION_STEP (ACTION_STEP_ID),
    CONSTRAINT UK_OPS_ACTION_STEP_ORD UNIQUE (CONVERSATION_ID, ORDINAL),
    CONSTRAINT CK_OPS_ACTION_STEP_ORD CHECK (ORDINAL > 0),
    CONSTRAINT CK_OPS_ACTION_STEP_STATUS
        CHECK (STATUS IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'EXECUTED', 'REJECTED', 'FAILED', 'SUPERSEDED')),
    CONSTRAINT CK_OPS_ACTION_STEP_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_ACTION_STEP_CONV
    ON KBOT_OPS_ACTION_STEP (CONVERSATION_ID, STATUS, ORDINAL);
CREATE INDEX IX_OPS_ACTION_STEP_PROP
    ON KBOT_OPS_ACTION_STEP (PROPOSAL_ID);
CREATE INDEX IX_OPS_ACTION_STEP_SUPERSEDES
    ON KBOT_OPS_ACTION_STEP (SUPERSEDES_STEP_ID);

CREATE TABLE KBOT_OPS_IMAGE_EVIDENCE (
    PROCESSING_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    EVIDENCE_REQUEST_ID RAW(16) NOT NULL,
    SOURCE_ARTIFACT_ID RAW(16) NOT NULL,
    PROCESSING_MODE VARCHAR2(8 CHAR) NOT NULL,
    MODEL_ID RAW(16) NOT NULL,
    MODEL_REVISION VARCHAR2(128 CHAR) NOT NULL,
    INPUT_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'PENDING' NOT NULL,
    OUTPUT_ARTIFACT_ID RAW(16),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_IMG_EVID_CONV FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_OPS_CONVERSATION (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_IMG_EVID_REQ FOREIGN KEY (EVIDENCE_REQUEST_ID)
        REFERENCES KBOT_OPS_EVIDENCE_REQUEST (REQUEST_ID),
    CONSTRAINT FK_OPS_IMG_EVID_SOURCE FOREIGN KEY (SOURCE_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_IMG_EVID_OUTPUT FOREIGN KEY (OUTPUT_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT CK_OPS_IMG_EVID_MODE
        CHECK (PROCESSING_MODE IN ('OCR', 'VLM')),
    CONSTRAINT CK_OPS_IMG_EVID_STATUS
        CHECK (STATUS IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED'))
);

CREATE INDEX IX_OPS_IMG_EVID_CONV
    ON KBOT_OPS_IMAGE_EVIDENCE (CONVERSATION_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_IMG_EVID_REQ
    ON KBOT_OPS_IMAGE_EVIDENCE (EVIDENCE_REQUEST_ID);
CREATE INDEX IX_OPS_IMG_EVID_SOURCE
    ON KBOT_OPS_IMAGE_EVIDENCE (SOURCE_ARTIFACT_ID);
CREATE INDEX IX_OPS_IMG_EVID_OUTPUT
    ON KBOT_OPS_IMAGE_EVIDENCE (OUTPUT_ARTIFACT_ID);
