-- KBot 4.0 AIOps：MySQL/PostgreSQL 工作负载快照和活动采样。
-- 业务幂等、枚举和值域由应用事务负责；表只声明主键、外键和NOT NULL。

CREATE TABLE KBOT_OPS_WORKLOAD_SNAPSHOT (
    WORKLOAD_SNAPSHOT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    SCHEDULED_FOR TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    COLLECTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    WINDOW_SECONDS NUMBER(10) NOT NULL,
    DATABASE_TYPE VARCHAR2(16 CHAR) NOT NULL,
    INSTANCE_IDENTITY_JSON JSON NOT NULL,
    INSTANCE_STARTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    DATABASE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    CAPABILITY_PROBE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    CATALOG_VERSION VARCHAR2(64 CHAR) NOT NULL,
    SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    CONTINUITY_JSON JSON NOT NULL,
    COVERAGE_JSON JSON NOT NULL,
    INSTANCE_METRICS_JSON JSON NOT NULL,
    REPLICATION_METRICS_JSON JSON NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    ERROR_CODE VARCHAR2(128 CHAR),
    BYTE_SIZE NUMBER(19) NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_WORKLOAD_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_WORKLOAD_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID)
);

CREATE INDEX IX_OPS_WORKLOAD_SCOPE_TIME ON KBOT_OPS_WORKLOAD_SNAPSHOT
    (DOMAIN_ID, TARGET_ID, COLLECTED_AT, WORKLOAD_SNAPSHOT_ID);
CREATE INDEX IX_OPS_WORKLOAD_EXPIRY ON KBOT_OPS_WORKLOAD_SNAPSHOT
    (EXPIRES_AT, WORKLOAD_SNAPSHOT_ID);
CREATE INDEX IX_OPS_WORKLOAD_SCHEDULE ON KBOT_OPS_WORKLOAD_SNAPSHOT
    (TARGET_ID, SCHEDULED_FOR);

CREATE TABLE KBOT_OPS_WORKLOAD_STATEMENT (
    WORKLOAD_STATEMENT_ID RAW(16) PRIMARY KEY,
    WORKLOAD_SNAPSHOT_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    STATEMENT_IDENTITY_TYPE VARCHAR2(32 CHAR) NOT NULL,
    STATEMENT_IDENTITY_VALUE VARCHAR2(128 CHAR) NOT NULL,
    DATABASE_NAME VARCHAR2(128 CHAR) DEFAULT '__UNKNOWN__' NOT NULL,
    USER_IDENTIFIER VARCHAR2(128 CHAR) DEFAULT '__UNKNOWN__' NOT NULL,
    TOP_LEVEL NUMBER(2) DEFAULT -1 NOT NULL,
    NORMALIZED_STATEMENT CLOB,
    EXECUTION_COUNT NUMBER(19) NOT NULL,
    TOTAL_DURATION_MICROSECONDS NUMBER(19) NOT NULL,
    MEAN_DURATION_MICROSECONDS NUMBER(19) NOT NULL,
    MAX_DURATION_MICROSECONDS NUMBER(19) NOT NULL,
    ROWS_PROCESSED NUMBER(19) NOT NULL,
    DATABASE_METRICS_JSON JSON NOT NULL,
    RANK_DIMENSION VARCHAR2(32 CHAR) NOT NULL,
    RANK_NO NUMBER(10) NOT NULL,
    QUALITY_STATUS VARCHAR2(16 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_WORKLOAD_STMT_SNAPSHOT FOREIGN KEY (WORKLOAD_SNAPSHOT_ID)
        REFERENCES KBOT_OPS_WORKLOAD_SNAPSHOT (WORKLOAD_SNAPSHOT_ID),
    CONSTRAINT FK_OPS_WORKLOAD_STMT_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_WORKLOAD_STMT_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID)
);

CREATE INDEX IX_OPS_WORKLOAD_STMT_SNAPSHOT ON KBOT_OPS_WORKLOAD_STATEMENT
    (WORKLOAD_SNAPSHOT_ID);
CREATE INDEX IX_OPS_WORKLOAD_STMT_TARGET ON KBOT_OPS_WORKLOAD_STATEMENT
    (TARGET_ID);
CREATE INDEX IX_OPS_WORKLOAD_STMT_SUBJECT ON KBOT_OPS_WORKLOAD_STATEMENT
    (DOMAIN_ID, TARGET_ID, STATEMENT_IDENTITY_TYPE,
     STATEMENT_IDENTITY_VALUE, WORKLOAD_STATEMENT_ID);

CREATE TABLE KBOT_OPS_WORKLOAD_METRIC (
    WORKLOAD_METRIC_ID RAW(16) PRIMARY KEY,
    WORKLOAD_SNAPSHOT_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    METRIC_FAMILY VARCHAR2(32 CHAR) NOT NULL,
    METRIC_CODE VARCHAR2(128 CHAR) NOT NULL,
    DIMENSION_KEY VARCHAR2(256 CHAR) NOT NULL,
    DIMENSION_JSON JSON NOT NULL,
    COUNTER_VALUE NUMBER(30,6),
    GAUGE_VALUE NUMBER(30,6),
    UNIT VARCHAR2(32 CHAR) NOT NULL,
    QUALITY_STATUS VARCHAR2(16 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_WL_METRIC_SNAPSHOT FOREIGN KEY (WORKLOAD_SNAPSHOT_ID)
        REFERENCES KBOT_OPS_WORKLOAD_SNAPSHOT (WORKLOAD_SNAPSHOT_ID),
    CONSTRAINT FK_OPS_WORKLOAD_METRIC_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_WORKLOAD_METRIC_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID)
);

CREATE INDEX IX_OPS_WORKLOAD_METRIC_SNAP ON KBOT_OPS_WORKLOAD_METRIC
    (WORKLOAD_SNAPSHOT_ID);
CREATE INDEX IX_OPS_WORKLOAD_METRIC_TARGET ON KBOT_OPS_WORKLOAD_METRIC
    (TARGET_ID);
CREATE INDEX IX_OPS_WORKLOAD_METRIC_FAMILY ON KBOT_OPS_WORKLOAD_METRIC
    (DOMAIN_ID, TARGET_ID, METRIC_FAMILY, WORKLOAD_METRIC_ID);

CREATE TABLE KBOT_OPS_ACTIVITY_SAMPLE (
    ACTIVITY_SAMPLE_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    DATABASE_TYPE VARCHAR2(16 CHAR) NOT NULL,
    SAMPLED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    INSTANCE_IDENTITY_JSON JSON NOT NULL,
    SESSION_IDENTIFIER VARCHAR2(128 CHAR),
    WORKER_IDENTIFIER VARCHAR2(128 CHAR),
    STATEMENT_IDENTITY_TYPE VARCHAR2(32 CHAR),
    STATEMENT_IDENTITY_VALUE VARCHAR2(128 CHAR),
    DATABASE_NAME VARCHAR2(128 CHAR),
    SCHEMA_NAME VARCHAR2(128 CHAR),
    USERNAME_HASH VARCHAR2(64 CHAR),
    CLIENT_HASH VARCHAR2(64 CHAR),
    COMMAND_NAME VARCHAR2(64 CHAR),
    SESSION_STATE VARCHAR2(256 CHAR),
    STAGE_NAME VARCHAR2(256 CHAR),
    WAIT_NAME VARCHAR2(256 CHAR),
    DATABASE_SAMPLE_JSON JSON NOT NULL,
    TRANSACTION_ACTIVE NUMBER(1) DEFAULT 0 NOT NULL,
    LOCK_WAITING NUMBER(1) DEFAULT 0 NOT NULL,
    SAMPLE_WEIGHT NUMBER(10) DEFAULT 1 NOT NULL,
    QUALITY_STATUS VARCHAR2(16 CHAR) NOT NULL,
    BYTE_SIZE NUMBER(19) DEFAULT 0 NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_ACTIVITY_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_ACTIVITY_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID)
);

CREATE INDEX IX_OPS_ACTIVITY_SCOPE_TIME ON KBOT_OPS_ACTIVITY_SAMPLE
    (DOMAIN_ID, TARGET_ID, SAMPLED_AT, ACTIVITY_SAMPLE_ID);
CREATE INDEX IX_OPS_ACTIVITY_EXPIRY ON KBOT_OPS_ACTIVITY_SAMPLE
    (EXPIRES_AT, ACTIVITY_SAMPLE_ID);
CREATE INDEX IX_OPS_ACTIVITY_TARGET ON KBOT_OPS_ACTIVITY_SAMPLE
    (TARGET_ID);
