-- KBot 4.0 AIOps：运维知识资产、版本、范围、来源、索引和审核。
-- 业务枚举、状态迁移、幂等和唯一性由应用事务负责；表只声明主键、外键和NOT NULL。

CREATE TABLE KBOT_OPS_KNOWLEDGE_ASSET (
    ASSET_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    ASSET_KIND VARCHAR2(32 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    STATUS VARCHAR2(32 CHAR) NOT NULL,
    CURRENT_VERSION_ID RAW(16),
    SECURITY_LEVEL NUMBER(10) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_OPS_KNOW_ASSET_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID)
);

CREATE INDEX IX_OPS_KNOW_ASSET_SCOPE ON KBOT_OPS_KNOWLEDGE_ASSET
    (DOMAIN_ID, ASSET_KIND, STATUS, UPDATED_AT);

CREATE TABLE KBOT_OPS_KNOWLEDGE_VERSION (
    ASSET_VERSION_ID RAW(16) PRIMARY KEY,
    ASSET_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    STATUS VARCHAR2(32 CHAR) NOT NULL,
    SOURCE_HASH VARCHAR2(64 CHAR) NOT NULL,
    PROFILE_SCHEMA_VERSION VARCHAR2(64 CHAR),
    PROFILE_JSON JSON,
    EXTRACTION_WARNINGS_JSON JSON NOT NULL,
    PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE,
    RETIRED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_OPS_KNOW_VER_ASSET FOREIGN KEY (ASSET_ID)
        REFERENCES KBOT_OPS_KNOWLEDGE_ASSET (ASSET_ID)
);

CREATE INDEX IX_OPS_KNOW_VER_ASSET ON KBOT_OPS_KNOWLEDGE_VERSION
    (ASSET_ID, VERSION_NO);
CREATE INDEX IX_OPS_KNOW_VER_STATUS ON KBOT_OPS_KNOWLEDGE_VERSION
    (STATUS, CREATED_AT);

ALTER TABLE KBOT_OPS_KNOWLEDGE_ASSET ADD CONSTRAINT FK_OPS_KNOW_ASSET_CUR_VER
    FOREIGN KEY (CURRENT_VERSION_ID)
    REFERENCES KBOT_OPS_KNOWLEDGE_VERSION (ASSET_VERSION_ID);

CREATE TABLE KBOT_OPS_KNOWLEDGE_SCOPE (
    SCOPE_ID RAW(16) PRIMARY KEY,
    ASSET_VERSION_ID RAW(16) NOT NULL,
    SCOPE_KIND VARCHAR2(64 CHAR) NOT NULL,
    SCOPE_VALUE VARCHAR2(512 CHAR) NOT NULL,
    NORMALIZED_VALUE VARCHAR2(512 CHAR) NOT NULL,
    SOURCE_KIND VARCHAR2(32 CHAR) NOT NULL,
    SOURCE_LOCATOR_JSON JSON,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_KNOW_SCOPE_VER FOREIGN KEY (ASSET_VERSION_ID)
        REFERENCES KBOT_OPS_KNOWLEDGE_VERSION (ASSET_VERSION_ID)
);

CREATE INDEX IX_OPS_KNOW_SCOPE_LOOKUP ON KBOT_OPS_KNOWLEDGE_SCOPE
    (SCOPE_KIND, NORMALIZED_VALUE, ASSET_VERSION_ID);
CREATE INDEX IX_OPS_KNOW_SCOPE_VER ON KBOT_OPS_KNOWLEDGE_SCOPE
    (ASSET_VERSION_ID);

CREATE TABLE KBOT_OPS_KNOWLEDGE_SOURCE (
    SOURCE_ID RAW(16) PRIMARY KEY,
    ASSET_VERSION_ID RAW(16) NOT NULL,
    SOURCE_KIND VARCHAR2(32 CHAR) NOT NULL,
    SOURCE_REPORT_ID RAW(16),
    SOURCE_RUN_ID RAW(16),
    SOURCE_ARTIFACT_ID RAW(16),
    SOURCE_EXTERNAL_ID VARCHAR2(512 CHAR),
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    SOURCE_LOCATOR_JSON JSON,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_KNOW_SOURCE_VER FOREIGN KEY (ASSET_VERSION_ID)
        REFERENCES KBOT_OPS_KNOWLEDGE_VERSION (ASSET_VERSION_ID),
    CONSTRAINT FK_OPS_KNOW_SOURCE_REPORT FOREIGN KEY (SOURCE_REPORT_ID)
        REFERENCES KBOT_OPS_REPORT (REPORT_ID),
    CONSTRAINT FK_OPS_KNOW_SOURCE_RUN FOREIGN KEY (SOURCE_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_KNOW_SOURCE_ART FOREIGN KEY (SOURCE_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
);

CREATE INDEX IX_OPS_KNOW_SOURCE_VER ON KBOT_OPS_KNOWLEDGE_SOURCE
    (ASSET_VERSION_ID);
CREATE INDEX IX_OPS_KNOW_SOURCE_REPORT ON KBOT_OPS_KNOWLEDGE_SOURCE
    (SOURCE_REPORT_ID);
CREATE INDEX IX_OPS_KNOW_SOURCE_RUN ON KBOT_OPS_KNOWLEDGE_SOURCE
    (SOURCE_RUN_ID);
CREATE INDEX IX_OPS_KNOW_SOURCE_ART ON KBOT_OPS_KNOWLEDGE_SOURCE
    (SOURCE_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_KNOWLEDGE_INDEX (
    INDEX_REF_ID RAW(16) PRIMARY KEY,
    ASSET_VERSION_ID RAW(16) NOT NULL,
    COLLECTION_ID RAW(16) NOT NULL,
    BUNDLE_ID RAW(16) NOT NULL,
    BUNDLE_REVISION_ID RAW(16) NOT NULL,
    INDEX_STATUS VARCHAR2(32 CHAR) NOT NULL,
    EXPECTED_ROW_VERSION NUMBER(19),
    LAST_CHECKED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_SUMMARY VARCHAR2(2000 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_KNOW_INDEX_VER FOREIGN KEY (ASSET_VERSION_ID)
        REFERENCES KBOT_OPS_KNOWLEDGE_VERSION (ASSET_VERSION_ID)
);

CREATE INDEX IX_OPS_KNOW_INDEX_VER ON KBOT_OPS_KNOWLEDGE_INDEX
    (ASSET_VERSION_ID);
CREATE INDEX IX_OPS_KNOW_INDEX_STATUS ON KBOT_OPS_KNOWLEDGE_INDEX
    (INDEX_STATUS, UPDATED_AT);

CREATE TABLE KBOT_OPS_KNOWLEDGE_REVIEW (
    REVIEW_ID RAW(16) PRIMARY KEY,
    ASSET_VERSION_ID RAW(16) NOT NULL,
    DECISION VARCHAR2(32 CHAR) NOT NULL,
    REVIEWER_ID VARCHAR2(256 CHAR) NOT NULL,
    COMMENT_TEXT VARCHAR2(2000 CHAR),
    BEFORE_STATUS VARCHAR2(32 CHAR) NOT NULL,
    AFTER_STATUS VARCHAR2(32 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_KNOW_REVIEW_VER FOREIGN KEY (ASSET_VERSION_ID)
        REFERENCES KBOT_OPS_KNOWLEDGE_VERSION (ASSET_VERSION_ID)
);

CREATE INDEX IX_OPS_KNOW_REVIEW_QUEUE ON KBOT_OPS_KNOWLEDGE_REVIEW
    (AFTER_STATUS, CREATED_AT);
CREATE INDEX IX_OPS_KNOW_REVIEW_VER ON KBOT_OPS_KNOWLEDGE_REVIEW
    (ASSET_VERSION_ID);
