-- KBot 4.0 AIOps：Target恢复目标和人工恢复演练证据。
-- 业务枚举、版本单活、状态迁移和唯一性由应用事务负责。

CREATE TABLE KBOT_OPS_RECOVERY_PROFILE (
    RECOVERY_PROFILE_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    RPO_SECONDS NUMBER(19) NOT NULL,
    RTO_SECONDS NUMBER(19) NOT NULL,
    REQUIRED_DRILL_INTERVAL_DAYS NUMBER(10) NOT NULL,
    REQUIRED_ASSURANCE_LEVEL VARCHAR2(32 CHAR) NOT NULL,
    REQUIRED_BACKUP_SOURCE_TYPES_JSON JSON NOT NULL,
    RTO_CLOCK_BASIS VARCHAR2(64 CHAR) NOT NULL,
    SOURCE_NOTE VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    EFFECTIVE_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    RETIRED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONFIRMED_BY VARCHAR2(256 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_REC_PROFILE_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_REC_PROFILE_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID)
);

CREATE INDEX IX_OPS_REC_PROFILE_TARGET ON KBOT_OPS_RECOVERY_PROFILE
    (TARGET_ID, STATUS, VERSION_NO);
CREATE INDEX IX_OPS_REC_PROFILE_SCOPE ON KBOT_OPS_RECOVERY_PROFILE
    (DOMAIN_ID, TARGET_ID, STATUS);

CREATE TABLE KBOT_OPS_RECOVERY_DRILL (
    DRILL_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    RECOVERY_PROFILE_ID RAW(16),
    RECOVERY_PROFILE_VERSION NUMBER(19),
    DB_TYPE VARCHAR2(32 CHAR) NOT NULL,
    SCENARIO VARCHAR2(32 CHAR) NOT NULL,
    ASSURANCE_LEVEL VARCHAR2(32 CHAR) NOT NULL,
    BACKUP_SOURCE_TYPE VARCHAR2(48 CHAR) NOT NULL,
    ENVIRONMENT VARCHAR2(16 CHAR) NOT NULL,
    RESULT VARCHAR2(16 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    SIMULATED_FAILURE_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    RECOVERED_THROUGH_AT TIMESTAMP(6) WITH TIME ZONE,
    SERVICE_VALIDATED_AT TIMESTAMP(6) WITH TIME ZONE,
    ACHIEVED_RPO_SECONDS NUMBER(19),
    ACHIEVED_RTO_SECONDS NUMBER(19),
    RECOVERY_MARKER_JSON JSON NOT NULL,
    EVIDENCE_JSON JSON NOT NULL,
    SOURCE_TRUST_LEVEL VARCHAR2(32 CHAR) NOT NULL,
    SOURCE_OPS_RUN_ID RAW(16),
    REVIEWED_BY VARCHAR2(256 CHAR),
    REVIEWED_AT TIMESTAMP(6) WITH TIME ZONE,
    REVIEW_NOTE VARCHAR2(2000 CHAR),
    NOTES CLOB,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_REC_DRILL_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_REC_DRILL_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_REC_DRILL_PROFILE FOREIGN KEY (RECOVERY_PROFILE_ID)
        REFERENCES KBOT_OPS_RECOVERY_PROFILE (RECOVERY_PROFILE_ID),
    CONSTRAINT FK_OPS_REC_DRILL_RUN FOREIGN KEY (SOURCE_OPS_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID)
);

CREATE INDEX IX_OPS_REC_DRILL_TARGET ON KBOT_OPS_RECOVERY_DRILL
    (TARGET_ID, SIMULATED_FAILURE_AT, CREATED_AT);
CREATE INDEX IX_OPS_REC_DRILL_STATUS ON KBOT_OPS_RECOVERY_DRILL
    (DOMAIN_ID, STATUS, RESULT, SIMULATED_FAILURE_AT);
CREATE INDEX IX_OPS_REC_DRILL_PROFILE ON KBOT_OPS_RECOVERY_DRILL
    (RECOVERY_PROFILE_ID);
CREATE INDEX IX_OPS_REC_DRILL_RUN ON KBOT_OPS_RECOVERY_DRILL
    (SOURCE_OPS_RUN_ID);
