-- KBot 4.0 AIOps Schema 全量重建脚本。
-- 本文件可直接粘贴到 SQL Developer 后以 Run Script（F5）执行。
-- 此脚本永久删除当前 Schema 内全部 KBOT_OPS_% 表、KBOT_V_OPS_% 视图及其数据。
-- 仅可使用 KBot Schema 所有者执行；执行前必须停止 AIOps API、Worker、Scheduler。
-- 脚本拒绝删除被非 AIOps 表引用的对象，避免破坏其他服务的外键。
-- 重建后按当前规范 DDL 创建 AIOps Schema Version 10。

WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SET SERVEROUTPUT ON
SET VERIFY OFF

PROMPT === AIOps Schema 重建预检 ===

DECLARE
    l_schema_name VARCHAR2(128);
    l_table_count PLS_INTEGER := 0;
    l_view_count PLS_INTEGER := 0;
    l_row_count NUMBER;
    l_external_fk_count PLS_INTEGER := 0;
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
      INTO l_schema_name
      FROM dual;

    dbms_output.put_line('当前 Schema：' || l_schema_name);
    dbms_output.put_line('将永久删除以下 AIOps 表及其数据：');
    FOR table_row IN (
        SELECT table_name
        FROM user_tables
        WHERE table_name LIKE 'KBOT\_OPS\_%' ESCAPE '\'
        ORDER BY table_name
    ) LOOP
        EXECUTE IMMEDIATE
            'SELECT COUNT(*) FROM '
            || dbms_assert.enquote_name(table_row.table_name, FALSE)
            INTO l_row_count;
        l_table_count := l_table_count + 1;
        dbms_output.put_line('  ' || table_row.table_name || ': ' || l_row_count || ' 行');
    END LOOP;

    FOR view_row IN (
        SELECT view_name
        FROM user_views
        WHERE view_name LIKE 'KBOT\_V\_OPS\_%' ESCAPE '\'
        ORDER BY view_name
    ) LOOP
        l_view_count := l_view_count + 1;
        dbms_output.put_line('  视图 ' || view_row.view_name);
    END LOOP;

    SELECT COUNT(*)
      INTO l_external_fk_count
      FROM user_constraints child_constraint
      JOIN user_constraints parent_constraint
        ON parent_constraint.constraint_name = child_constraint.r_constraint_name
       AND parent_constraint.owner = child_constraint.r_owner
     WHERE child_constraint.constraint_type = 'R'
       AND parent_constraint.table_name LIKE 'KBOT\_OPS\_%' ESCAPE '\'
       AND child_constraint.table_name NOT LIKE 'KBOT\_OPS\_%' ESCAPE '\';

    IF l_external_fk_count > 0 THEN
        raise_application_error(
            -20001,
            '检测到 ' || l_external_fk_count
            || ' 个非 AIOps 表外键引用 KBOT_OPS_% 表；拒绝重建。'
        );
    END IF;

    dbms_output.put_line(
        '预检通过：将删除 ' || l_table_count || ' 张表、'
        || l_view_count || ' 个视图。'
    );
END;
/

ACCEPT rebuild_confirmation CHAR PROMPT '输入 REBUILD_AIOPS 以永久删除上述 AIOps 数据并重建： '

DECLARE
BEGIN
    IF UPPER(TRIM('&rebuild_confirmation')) <> 'REBUILD_AIOPS' THEN
        raise_application_error(-20002, '未收到 REBUILD_AIOPS 确认，已终止。');
    END IF;
END;
/

PROMPT === 正在删除 AIOps 视图和表 ===

DECLARE
BEGIN
    FOR view_row IN (
        SELECT view_name
        FROM user_views
        WHERE view_name LIKE 'KBOT\_V\_OPS\_%' ESCAPE '\'
        ORDER BY view_name
    ) LOOP
        EXECUTE IMMEDIATE
            'DROP VIEW ' || dbms_assert.enquote_name(view_row.view_name, FALSE);
        dbms_output.put_line('已删除视图 ' || view_row.view_name);
    END LOOP;

    FOR table_row IN (
        SELECT table_name
        FROM user_tables
        WHERE table_name LIKE 'KBOT\_OPS\_%' ESCAPE '\'
        ORDER BY table_name
    ) LOOP
        EXECUTE IMMEDIATE
            'DROP TABLE '
            || dbms_assert.enquote_name(table_row.table_name, FALSE)
            || ' CASCADE CONSTRAINTS PURGE';
        dbms_output.put_line('已删除表 ' || table_row.table_name);
    END LOOP;
END;
/

-- KBot 4.0 AIOps：目标、策略、Agent 绑定和诊断源根聚合。
-- 本脚本只用于空 Schema 初始化；UUIDv7 由应用生成。

CREATE TABLE KBOT_OPS_TARGET (
    TARGET_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DB_TYPE VARCHAR2(32 CHAR) NOT NULL,
    VERSION_CODE VARCHAR2(64 CHAR),
    ENVIRONMENT VARCHAR2(16 CHAR) NOT NULL,
    DB_ROLE VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    ENDPOINT_JSON JSON,
    DIAGNOSTIC_CREDENTIAL_ID RAW(16),
    EXECUTION_CREDENTIAL_ID RAW(16),
    SECURITY_LEVEL NUMBER(3) DEFAULT 1 NOT NULL,
    CAPABILITIES_JSON JSON,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'MAINTENANCE' NOT NULL,
    HEALTH_STATUS VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    LAST_HEALTH_CHECK_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_ERROR_CODE VARCHAR2(128 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    HEALTH_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_TARGET_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_OPS_TARGET_ENV
        CHECK (ENVIRONMENT IN ('PROD', 'STG', 'DEV')),
    CONSTRAINT CK_OPS_TARGET_ROLE
        CHECK (DB_ROLE IN ('PRIMARY', 'STANDBY', 'UNKNOWN')),
    CONSTRAINT CK_OPS_TARGET_STATUS
        CHECK (STATUS IN ('ACTIVE', 'MAINTENANCE', 'DISABLED')),
    CONSTRAINT CK_OPS_TARGET_HEALTH
        CHECK (HEALTH_STATUS IN (
            'UNKNOWN', 'HEALTHY', 'DEGRADED', 'UNREACHABLE'
        )),
    CONSTRAINT CK_OPS_TARGET_SECURITY CHECK (SECURITY_LEVEL >= 0),
    CONSTRAINT CK_OPS_TARGET_VERSION
        CHECK (ROW_VERSION >= 1 AND HEALTH_VERSION >= 1)
);

CREATE INDEX IX_OPS_TARGET_SCOPE
    ON KBOT_OPS_TARGET (DOMAIN_ID, STATUS, DISPLAY_NAME);
CREATE INDEX IX_OPS_TARGET_DOMAIN
    ON KBOT_OPS_TARGET (DOMAIN_ID);
CREATE INDEX IX_OPS_TARGET_TYPE
    ON KBOT_OPS_TARGET (DB_TYPE, STATUS);

CREATE TABLE KBOT_OPS_POLICY (
    POLICY_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    POLICY_KEY VARCHAR2(128 CHAR) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    RULES_JSON JSON NOT NULL,
    POLICY_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    EFFECTIVE_AT TIMESTAMP(6) WITH TIME ZONE,
    RETIRED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_POLICY_VERSION
        UNIQUE (DOMAIN_ID, POLICY_KEY, VERSION_NO),
    CONSTRAINT FK_OPS_POLICY_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_OPS_POLICY_STATUS
        CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT CK_OPS_POLICY_VERSION
        CHECK (VERSION_NO >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_POLICY_HASH CHECK (LENGTH(POLICY_HASH) = 64)
);

CREATE TABLE KBOT_OPS_TARGET_BINDING (
    BINDING_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    ALLOW_MUTATION NUMBER(1) DEFAULT 0 NOT NULL,
    POLICY_ID RAW(16),
    ALLOWED_ACTIONS_JSON JSON,
    CHANGE_WINDOW_JSON JSON,
    MAX_DAILY_EXECUTIONS NUMBER(10),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_BINDING_TARGET_AGENT UNIQUE (TARGET_ID, AGENT_ID),
    CONSTRAINT FK_OPS_BINDING_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_BINDING_POLICY
        FOREIGN KEY (POLICY_ID) REFERENCES KBOT_OPS_POLICY (POLICY_ID),
    CONSTRAINT CK_OPS_BINDING_MUTATION
        CHECK (ALLOW_MUTATION IN (0, 1)),
    CONSTRAINT CK_OPS_BINDING_STATUS
        CHECK (STATUS IN ('ACTIVE', 'REVOKED')),
    CONSTRAINT CK_OPS_BINDING_MAX_DAILY
        CHECK (MAX_DAILY_EXECUTIONS IS NULL OR MAX_DAILY_EXECUTIONS >= 0),
    CONSTRAINT CK_OPS_BINDING_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_OPS_POLICY_DOMAIN
    ON KBOT_OPS_POLICY (DOMAIN_ID);
CREATE INDEX IX_OPS_BINDING_AGENT
    ON KBOT_OPS_TARGET_BINDING (AGENT_ID, STATUS, ALLOW_MUTATION);
CREATE INDEX IX_OPS_BINDING_TARGET
    ON KBOT_OPS_TARGET_BINDING (TARGET_ID, STATUS);
CREATE INDEX IX_OPS_BINDING_POLICY
    ON KBOT_OPS_TARGET_BINDING (POLICY_ID);

CREATE TABLE KBOT_OPS_NOTIFICATION_SUBSCRIPTION (
    SUBSCRIPTION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    RECIPIENT_ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    CHANNEL VARCHAR2(16 CHAR) DEFAULT 'IN_APP' NOT NULL,
    MINIMUM_SEVERITY VARCHAR2(16 CHAR) DEFAULT 'HIGH' NOT NULL,
    STAGES_JSON JSON NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_NOTIFY_SUB_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_NOTIFY_SUB_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT UK_OPS_NOTIFY_SUB_RECIPIENT UNIQUE (
        DOMAIN_ID, TARGET_ID, RECIPIENT_ACTOR_ID, CHANNEL
    ),
    CONSTRAINT CK_OPS_NOTIFY_SUB_CHANNEL CHECK (CHANNEL IN ('IN_APP')),
    CONSTRAINT CK_OPS_NOTIFY_SUB_SEVERITY CHECK (
        MINIMUM_SEVERITY IN ('INFO', 'WARNING', 'HIGH', 'CRITICAL')
    ),
    CONSTRAINT CK_OPS_NOTIFY_SUB_STATUS CHECK (
        STATUS IN ('ACTIVE', 'DISABLED')
    ),
    CONSTRAINT CK_OPS_NOTIFY_SUB_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_OPS_NOTIFY_SUB_ROUTE ON KBOT_OPS_NOTIFICATION_SUBSCRIPTION
    (TARGET_ID, STATUS, MINIMUM_SEVERITY);

CREATE TABLE KBOT_OPS_DIAGNOSTIC_SOURCE (
    DIAGNOSTIC_SOURCE_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    SOURCE_TYPE VARCHAR2(64 CHAR) NOT NULL,
    ADAPTER_ID VARCHAR2(128 CHAR) NOT NULL,
    ADAPTER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    ENDPOINT VARCHAR2(2048 CHAR),
    AUTH_CREDENTIAL_ID RAW(16),
    WEBHOOK_CREDENTIAL_ID RAW(16),
    TLS_PROFILE_REF VARCHAR2(1024 CHAR),
    WEBHOOK_KEY_HASH VARCHAR2(64 CHAR),
    PREVIOUS_WEBHOOK_KEY_HASH VARCHAR2(64 CHAR),
    PREVIOUS_WEBHOOK_KEY_EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    DECLARED_CAPABILITIES_JSON JSON NOT NULL,
    DISCOVERED_CAPABILITIES_JSON JSON,
    CONFIG_JSON JSON NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DISABLED' NOT NULL,
    HEALTH_STATUS VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    HEALTH_CHECK_REQUEST_ID RAW(16),
    HEALTH_CHECK_REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_HEALTH_CHECK_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_SUCCESS_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_ERROR_CODE VARCHAR2(128 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    HEALTH_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_SOURCE_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_OPS_SOURCE_ROUTE
        CHECK (ENDPOINT IS NOT NULL OR WEBHOOK_CREDENTIAL_ID IS NOT NULL),
    CONSTRAINT CK_OPS_SOURCE_PREV_KEY CHECK (
        (PREVIOUS_WEBHOOK_KEY_HASH IS NULL
         AND PREVIOUS_WEBHOOK_KEY_EXPIRES_AT IS NULL)
        OR
        (PREVIOUS_WEBHOOK_KEY_HASH IS NOT NULL
         AND PREVIOUS_WEBHOOK_KEY_EXPIRES_AT IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_SOURCE_HEALTH_REQ CHECK (
        (HEALTH_CHECK_REQUEST_ID IS NULL
         AND HEALTH_CHECK_REQUESTED_AT IS NULL)
        OR
        (HEALTH_CHECK_REQUEST_ID IS NOT NULL
         AND HEALTH_CHECK_REQUESTED_AT IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_SOURCE_STATUS
        CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_OPS_SOURCE_HEALTH CHECK (
        HEALTH_STATUS IN ('UNKNOWN', 'HEALTHY', 'DEGRADED', 'UNREACHABLE')
    ),
    CONSTRAINT CK_OPS_SOURCE_VERSION
        CHECK (ROW_VERSION >= 1 AND HEALTH_VERSION >= 1)
);

CREATE UNIQUE INDEX UX_OPS_SOURCE_WEBHOOK
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (WEBHOOK_KEY_HASH);
CREATE UNIQUE INDEX UX_OPS_SOURCE_PREV_WEBHOOK
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (PREVIOUS_WEBHOOK_KEY_HASH);
CREATE INDEX IX_OPS_SOURCE_SCOPE
    ON KBOT_OPS_DIAGNOSTIC_SOURCE
       (DOMAIN_ID, SOURCE_TYPE, STATUS);
CREATE INDEX IX_OPS_SOURCE_DOMAIN
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (DOMAIN_ID);
CREATE INDEX IX_OPS_SOURCE_HEALTH
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (HEALTH_STATUS, LAST_HEALTH_CHECK_AT);
CREATE INDEX IX_OPS_SOURCE_HEALTH_REQ
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (HEALTH_CHECK_REQUEST_ID);

CREATE TABLE KBOT_OPS_TARGET_SOURCE_BINDING (
    TARGET_SOURCE_BINDING_ID RAW(16) PRIMARY KEY,
    TARGET_ID RAW(16) NOT NULL,
    DIAGNOSTIC_SOURCE_ID RAW(16) NOT NULL,
    SOURCE_LOCATOR_KEY VARCHAR2(512 CHAR) NOT NULL,
    SOURCE_LOCATOR_JSON JSON NOT NULL,
    ROLE VARCHAR2(16 CHAR) DEFAULT 'PRIMARY' NOT NULL,
    PRIORITY NUMBER(8) DEFAULT 100 NOT NULL,
    CAPABILITY_SCOPE_JSON JSON,
    MAPPING_OVERRIDES_JSON JSON,
    QUERY_BUDGET_JSON JSON,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    HEALTH_STATUS VARCHAR2(16 CHAR) DEFAULT 'UNKNOWN' NOT NULL,
    LAST_HEALTH_CHECK_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_ERROR_CODE VARCHAR2(128 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    HEALTH_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_TSRC_LOCATOR
        UNIQUE (DIAGNOSTIC_SOURCE_ID, SOURCE_LOCATOR_KEY),
    CONSTRAINT FK_OPS_TSRC_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_TSRC_MONITOR
        FOREIGN KEY (DIAGNOSTIC_SOURCE_ID)
        REFERENCES KBOT_OPS_DIAGNOSTIC_SOURCE (DIAGNOSTIC_SOURCE_ID),
    CONSTRAINT CK_OPS_TSRC_ROLE
        CHECK (ROLE IN ('PRIMARY', 'SUPPLEMENTARY', 'FALLBACK')),
    CONSTRAINT CK_OPS_TSRC_PRIORITY CHECK (PRIORITY >= 0),
    CONSTRAINT CK_OPS_TSRC_STATUS
        CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_OPS_TSRC_HEALTH CHECK (
        HEALTH_STATUS IN ('UNKNOWN', 'HEALTHY', 'DEGRADED', 'UNREACHABLE')
    ),
    CONSTRAINT CK_OPS_TSRC_VERSION
        CHECK (ROW_VERSION >= 1 AND HEALTH_VERSION >= 1)
);

CREATE INDEX IX_OPS_TSRC_TARGET
    ON KBOT_OPS_TARGET_SOURCE_BINDING (TARGET_ID, STATUS, PRIORITY);
CREATE INDEX IX_OPS_TSRC_MONITOR
    ON KBOT_OPS_TARGET_SOURCE_BINDING (DIAGNOSTIC_SOURCE_ID, STATUS);

COMMENT ON COLUMN KBOT_OPS_TARGET.TARGET_ID IS
    '应用生成的 UUIDv7；API 使用规范 UUID 字符串';
COMMENT ON COLUMN KBOT_OPS_TARGET.ENDPOINT_JSON IS
    '仅保存连接端点元数据，不保存用户名、密码或 Token';
COMMENT ON COLUMN KBOT_OPS_DIAGNOSTIC_SOURCE.WEBHOOK_KEY_HASH IS
    '外部 Webhook 不透明路由键的 SHA-256，不保存明文';
-- KBot 4.0 AIOps：信号事件、故障情境、Run、Task、Artifact 与用户事件流。

CREATE TABLE KBOT_OPS_SIGNAL_EVENT (
    SIGNAL_EVENT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16),
    DIAGNOSTIC_SOURCE_ID RAW(16) NOT NULL,
    SOURCE_BINDING_ID RAW(16),
    SOURCE_INBOX_ID RAW(16),
    SOURCE_EVENT_KEY VARCHAR2(512 CHAR) NOT NULL,
    SIGNAL_KIND VARCHAR2(32 CHAR) NOT NULL,
    EVENT_CLASS VARCHAR2(128 CHAR) NOT NULL,
    SEVERITY VARCHAR2(16 CHAR) NOT NULL,
    NORMALIZED_STATUS VARCHAR2(16 CHAR) NOT NULL,
    SOURCE_STATUS VARCHAR2(128 CHAR),
    SUMMARY VARCHAR2(1000 CHAR),
    OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    RECEIVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP(6) WITH TIME ZONE,
    DEDUP_HASH VARCHAR2(64 CHAR) NOT NULL,
    PAYLOAD_JSON JSON,
    PAYLOAD_URI VARCHAR2(2048 CHAR),
    PAYLOAD_HASH VARCHAR2(64 CHAR) NOT NULL,
    EVIDENCE_LOCATOR_JSON JSON,
    NORMALIZER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PROCESSING_STATUS VARCHAR2(16 CHAR) DEFAULT 'RECEIVED' NOT NULL,
    TRACE_ID VARCHAR2(128 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_SIG_SOURCE
        UNIQUE (DIAGNOSTIC_SOURCE_ID, SOURCE_EVENT_KEY),
    CONSTRAINT FK_OPS_SIG_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_SIG_DOMAIN
        FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_SIG_SOURCE
        FOREIGN KEY (DIAGNOSTIC_SOURCE_ID)
        REFERENCES KBOT_OPS_DIAGNOSTIC_SOURCE (DIAGNOSTIC_SOURCE_ID),
    CONSTRAINT FK_OPS_SIG_BINDING
        FOREIGN KEY (SOURCE_BINDING_ID)
        REFERENCES KBOT_OPS_TARGET_SOURCE_BINDING (TARGET_SOURCE_BINDING_ID),
    CONSTRAINT CK_OPS_SIG_SEVERITY
        CHECK (SEVERITY IN ('INFO', 'WARNING', 'HIGH', 'CRITICAL')),
    CONSTRAINT CK_OPS_SIG_KIND CHECK (
        SIGNAL_KIND IN ('FAULT', 'RECOVERY', 'RISK', 'CHANGE', 'INFORMATIONAL')
    ),
    CONSTRAINT CK_OPS_SIG_STATUS CHECK (
        NORMALIZED_STATUS IN ('OPEN', 'UPDATED', 'RESOLVED', 'INFORMATIONAL')
    ),
    CONSTRAINT CK_OPS_SIG_PROCESSING CHECK (
        PROCESSING_STATUS IN ('RECEIVED', 'CORRELATED', 'IGNORED', 'FAILED')
    ),
    CONSTRAINT CK_OPS_SIG_PAYLOAD
        CHECK (PAYLOAD_JSON IS NOT NULL OR PAYLOAD_URI IS NOT NULL),
    CONSTRAINT CK_OPS_SIG_HASHES CHECK (
        LENGTH(DEDUP_HASH) = 64 AND LENGTH(PAYLOAD_HASH) = 64
    )
);

CREATE INDEX IX_OPS_SIG_TARGET_TIME
    ON KBOT_OPS_SIGNAL_EVENT (TARGET_ID, OCCURRED_AT);
CREATE INDEX IX_OPS_SIG_PROCESSING
    ON KBOT_OPS_SIGNAL_EVENT (PROCESSING_STATUS, RECEIVED_AT);
CREATE INDEX IX_OPS_SIG_CORRELATE
    ON KBOT_OPS_SIGNAL_EVENT (TARGET_ID, DEDUP_HASH, NORMALIZED_STATUS);
CREATE INDEX IX_OPS_SIG_INBOX
    ON KBOT_OPS_SIGNAL_EVENT (SOURCE_INBOX_ID);

CREATE TABLE KBOT_OPS_SITUATION (
    SITUATION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    SITUATION_TYPE VARCHAR2(128 CHAR) NOT NULL,
    TITLE VARCHAR2(512 CHAR) NOT NULL,
    SUMMARY VARCHAR2(2000 CHAR),
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    SEVERITY VARCHAR2(16 CHAR) NOT NULL,
    CORRELATION_KEY VARCHAR2(256 CHAR) NOT NULL,
    CORRELATION_HASH VARCHAR2(64 CHAR) NOT NULL,
    CORRELATION_VERSION VARCHAR2(64 CHAR) NOT NULL,
    CORRELATION_JSON JSON,
    FIRST_OBSERVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    LAST_OBSERVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ACKNOWLEDGED_AT TIMESTAMP(6) WITH TIME ZONE,
    ACKNOWLEDGED_BY VARCHAR2(256 CHAR),
    RESOLVED_AT TIMESTAMP(6) WITH TIME ZONE,
    CLOSED_AT TIMESTAMP(6) WITH TIME ZONE,
    EVENT_COUNT NUMBER(19) DEFAULT 1 NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_SITUATION_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_SITUATION_DOMAIN
        FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_OPS_SITUATION_STATUS CHECK (
        STATUS IN (
            'OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'DIAGNOSED', 'MITIGATING',
            'OBSERVING', 'RESOLVED', 'CLOSED', 'SUPPRESSED'
        )
    ),
    CONSTRAINT CK_OPS_SITUATION_SEVERITY
        CHECK (SEVERITY IN ('INFO', 'WARNING', 'HIGH', 'CRITICAL')),
    CONSTRAINT CK_OPS_SITUATION_COUNTER
        CHECK (EVENT_COUNT >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_SITUATION_HASH CHECK (LENGTH(CORRELATION_HASH) = 64)
);

CREATE INDEX IX_OPS_SITUATION_QUERY
    ON KBOT_OPS_SITUATION (TARGET_ID, STATUS, SEVERITY, LAST_OBSERVED_AT);

CREATE TABLE KBOT_OPS_SITUATION_EVENT (
    SITUATION_EVENT_ID RAW(16) PRIMARY KEY,
    SITUATION_ID RAW(16) NOT NULL,
    SIGNAL_EVENT_ID RAW(16) NOT NULL,
    RELATION_TYPE VARCHAR2(16 CHAR) NOT NULL,
    CORRELATION_METHOD VARCHAR2(32 CHAR) NOT NULL,
    CORRELATION_SCORE NUMBER(8,6),
    CORRELATION_DETAIL_JSON JSON,
    ATTACHED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATTACHED_BY VARCHAR2(256 CHAR) NOT NULL,
    CONSTRAINT UK_OPS_SITUATION_EVENT UNIQUE (SITUATION_ID, SIGNAL_EVENT_ID),
    CONSTRAINT FK_OPS_SITEVT_SITUATION FOREIGN KEY (SITUATION_ID)
        REFERENCES KBOT_OPS_SITUATION (SITUATION_ID),
    CONSTRAINT FK_OPS_SITEVT_SIGNAL FOREIGN KEY (SIGNAL_EVENT_ID)
        REFERENCES KBOT_OPS_SIGNAL_EVENT (SIGNAL_EVENT_ID),
    CONSTRAINT CK_OPS_SITEVT_RELATION CHECK (
        RELATION_TYPE IN ('TRIGGER', 'RELATED', 'RECOVERY', 'CHANGE')
    ),
    CONSTRAINT CK_OPS_SITEVT_METHOD CHECK (
        CORRELATION_METHOD IN ('EXACT', 'RULE', 'TOPOLOGY', 'MODEL', 'MANUAL')
    )
);
CREATE INDEX IX_OPS_SITEVT_SIGNAL ON KBOT_OPS_SITUATION_EVENT (SIGNAL_EVENT_ID);

CREATE TABLE KBOT_OPS_RUN (
    OPS_RUN_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    PARENT_AGENT_RUN_ID RAW(16),
    PARENT_DELEGATION_ID RAW(16),
    TRIGGER_TYPE VARCHAR2(16 CHAR) NOT NULL,
    TRIGGER_SIGNAL_EVENT_ID RAW(16),
    SITUATION_ID RAW(16),
    INTERACTION_MODE VARCHAR2(16 CHAR) NOT NULL,
    INVESTIGATION_MODE VARCHAR2(16 CHAR) NOT NULL,
    INSPECTION_FIRE_ID RAW(16),
    SOURCE_PROPOSAL_ID RAW(16),
    SOURCE_RESULT_ARTIFACT_ID RAW(16),
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    ORIGINAL_REQUEST CLOB,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    PLAN_SNAPSHOT_JSON JSON,
    POLICY_SNAPSHOT_JSON JSON,
    ROOT_CAUSE_LEVEL VARCHAR2(16 CHAR),
    FINAL_ARTIFACT_ID RAW(16),
    DEADLINE_AT TIMESTAMP(6) WITH TIME ZONE,
    CANCEL_REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE,
    CANCEL_REQUESTED_BY VARCHAR2(256 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_RUN_IDEMP UNIQUE (
        TARGET_ID, TRIGGER_TYPE, ACTOR_ID, IDEMPOTENCY_KEY
    ),
    CONSTRAINT UK_OPS_RUN_DELEGATION UNIQUE (PARENT_DELEGATION_ID),
    CONSTRAINT FK_OPS_RUN_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_RUN_SIGNAL
        FOREIGN KEY (TRIGGER_SIGNAL_EVENT_ID)
        REFERENCES KBOT_OPS_SIGNAL_EVENT (SIGNAL_EVENT_ID),
    CONSTRAINT FK_OPS_RUN_SITUATION
        FOREIGN KEY (SITUATION_ID) REFERENCES KBOT_OPS_SITUATION (SITUATION_ID),
    CONSTRAINT CK_OPS_RUN_PARENT CHECK (
        (PARENT_AGENT_RUN_ID IS NULL AND PARENT_DELEGATION_ID IS NULL)
        OR
        (PARENT_AGENT_RUN_ID IS NOT NULL AND PARENT_DELEGATION_ID IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_RUN_TRIGGER CHECK (
        TRIGGER_TYPE IN (
            'CHAT', 'API', 'ROOT', 'ALERT', 'SCHEDULE', 'IM', 'EMAIL'
        )
    ),
    CONSTRAINT CK_OPS_RUN_INTERACTION CHECK (
        INTERACTION_MODE IN ('INTERACTIVE', 'AUTONOMOUS')
    ),
    CONSTRAINT CK_OPS_RUN_INVESTIGATION CHECK (
        INVESTIGATION_MODE IN ('INCIDENT', 'ON_DEMAND', 'INSPECTION', 'VERIFICATION')
    ),
    CONSTRAINT CK_OPS_RUN_STATUS CHECK (
        STATUS IN (
            'CREATED', 'SCOPING', 'OBSERVING', 'DIAGNOSING',
            'WAITING_INPUT', 'DIAGNOSED', 'PROPOSING',
            'WAITING_APPROVAL', 'EXECUTING', 'VERIFYING',
            'ROLLBACK_PENDING', 'COMPLETED', 'DEGRADED', 'REJECTED',
            'FAILED', 'CANCELLED', 'EXPIRED'
        )
    ),
    CONSTRAINT CK_OPS_RUN_CAUSE CHECK (
        ROOT_CAUSE_LEVEL IS NULL OR ROOT_CAUSE_LEVEL IN (
            'CONFIRMED', 'PROBABLE', 'POSSIBLE', 'INCONCLUSIVE'
        )
    ),
    CONSTRAINT CK_OPS_RUN_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_OPS_RUN_TARGET
    ON KBOT_OPS_RUN (TARGET_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_RUN_AGENT
    ON KBOT_OPS_RUN (AGENT_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_RUN_PARENT
    ON KBOT_OPS_RUN (PARENT_AGENT_RUN_ID);
CREATE INDEX IX_OPS_RUN_SOURCE_PROPOSAL
    ON KBOT_OPS_RUN (SOURCE_PROPOSAL_ID);
CREATE INDEX IX_OPS_RUN_SITUATION
    ON KBOT_OPS_RUN (SITUATION_ID, STATUS);
CREATE INDEX IX_OPS_RUN_FIRE
    ON KBOT_OPS_RUN (INSPECTION_FIRE_ID, STATUS);
CREATE INDEX IX_OPS_RUN_SIGNAL
    ON KBOT_OPS_RUN (TRIGGER_SIGNAL_EVENT_ID);

CREATE UNIQUE INDEX UX_OPS_RUN_FIRE_TARGET ON KBOT_OPS_RUN (
    CASE WHEN INSPECTION_FIRE_ID IS NOT NULL THEN INSPECTION_FIRE_ID END,
    CASE WHEN INSPECTION_FIRE_ID IS NOT NULL THEN TARGET_ID END
);

CREATE TABLE KBOT_OPS_TASK (
    OPS_TASK_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    PARENT_TASK_ID RAW(16),
    TASK_KEY VARCHAR2(128 CHAR) NOT NULL,
    TASK_TYPE VARCHAR2(24 CHAR) NOT NULL,
    HANDLER_ID VARCHAR2(128 CHAR) NOT NULL,
    HANDLER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    INPUT_SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    OUTPUT_SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    DEPENDS_ON_JSON JSON,
    INPUT_ARTIFACTS_JSON JSON,
    OUTPUT_ARTIFACT_ID RAW(16),
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    PRIORITY NUMBER(8) DEFAULT 100 NOT NULL,
    AVAILABLE_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATTEMPT_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    MAX_ATTEMPTS NUMBER(8) DEFAULT 3 NOT NULL,
    TIMEOUT_SECONDS NUMBER(10) NOT NULL,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    HEARTBEAT_AT TIMESTAMP(6) WITH TIME ZONE,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_TASK_KEY UNIQUE (OPS_RUN_ID, TASK_KEY),
    CONSTRAINT FK_OPS_TASK_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_TASK_PARENT
        FOREIGN KEY (PARENT_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT CK_OPS_TASK_TYPE CHECK (
        TASK_TYPE IN (
            'SCOPE', 'OBSERVE', 'DIAGNOSE', 'REQUEST_INPUT',
            'PROPOSE', 'APPROVE', 'EXECUTE', 'VERIFY',
            'ROLLBACK', 'COMPARE', 'REPORT'
        )
    ),
    CONSTRAINT CK_OPS_TASK_STATUS CHECK (
        STATUS IN (
            'PENDING', 'READY', 'BLOCKED', 'RUNNING', 'WAITING_INPUT',
            'WAITING_APPROVAL', 'RETRY_WAIT', 'SUCCEEDED',
            'FAILED', 'CANCELLED', 'EXPIRED'
        )
    ),
    CONSTRAINT CK_OPS_TASK_NUMBERS CHECK (
        PRIORITY >= 0 AND ATTEMPT_COUNT >= 0 AND MAX_ATTEMPTS >= 1
        AND ATTEMPT_COUNT <= MAX_ATTEMPTS AND TIMEOUT_SECONDS >= 1
        AND ROW_VERSION >= 1
    ),
    CONSTRAINT CK_OPS_TASK_LEASE CHECK (
        (STATUS = 'RUNNING' AND LEASE_OWNER IS NOT NULL
         AND LEASE_TOKEN IS NOT NULL AND LEASE_UNTIL IS NOT NULL)
        OR
        (STATUS <> 'RUNNING' AND LEASE_OWNER IS NULL
         AND LEASE_TOKEN IS NULL AND LEASE_UNTIL IS NULL)
    )
);

CREATE INDEX IX_OPS_TASK_CLAIM
    ON KBOT_OPS_TASK (STATUS, AVAILABLE_AT, PRIORITY);
CREATE INDEX IX_OPS_TASK_LEASE
    ON KBOT_OPS_TASK (STATUS, LEASE_UNTIL);
CREATE INDEX IX_OPS_TASK_RUN
    ON KBOT_OPS_TASK (OPS_RUN_ID, STATUS);
CREATE INDEX IX_OPS_TASK_PARENT
    ON KBOT_OPS_TASK (PARENT_TASK_ID);

CREATE TABLE KBOT_OPS_ARTIFACT (
    ARTIFACT_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16),
    ARTIFACT_KEY VARCHAR2(256 CHAR) NOT NULL,
    ARTIFACT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PAYLOAD_JSON JSON,
    PAYLOAD_URI VARCHAR2(2048 CHAR),
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    BYTE_SIZE NUMBER(19) NOT NULL,
    PROVENANCE_JSON JSON NOT NULL,
    TRUST_LEVEL VARCHAR2(24 CHAR) NOT NULL,
    SECURITY_LEVEL NUMBER(3) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_ARTIFACT_KEY UNIQUE (OPS_RUN_ID, ARTIFACT_KEY),
    CONSTRAINT FK_OPS_ARTIFACT_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_ARTIFACT_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT CK_OPS_ARTIFACT_PAYLOAD
        CHECK (PAYLOAD_JSON IS NOT NULL OR PAYLOAD_URI IS NOT NULL),
    CONSTRAINT CK_OPS_ARTIFACT_TRUST CHECK (
        TRUST_LEVEL IN (
            'SOURCE_VERIFIED', 'USER_PROVIDED',
            'KNOWLEDGE_CITATION', 'MODEL_INFERENCE'
        )
    ),
    CONSTRAINT CK_OPS_ARTIFACT_SIZE
        CHECK (BYTE_SIZE >= 0 AND SECURITY_LEVEL >= 0),
    CONSTRAINT CK_OPS_ARTIFACT_HASH CHECK (LENGTH(CONTENT_HASH) = 64)
);

CREATE INDEX IX_OPS_ARTIFACT_RUN_TYPE
    ON KBOT_OPS_ARTIFACT (OPS_RUN_ID, ARTIFACT_TYPE, CREATED_AT);
CREATE INDEX IX_OPS_ARTIFACT_TASK
    ON KBOT_OPS_ARTIFACT (OPS_TASK_ID);
CREATE INDEX IX_OPS_ARTIFACT_HASH
    ON KBOT_OPS_ARTIFACT (CONTENT_HASH);

CREATE TABLE KBOT_OPS_RUN_EVENT (
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16),
    SEQUENCE_NO NUMBER(19) NOT NULL,
    EVENT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    EVENT_KEY VARCHAR2(128 CHAR),
    VISIBILITY VARCHAR2(16 CHAR) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_OPS_RUN_EVENT PRIMARY KEY (OPS_RUN_ID, SEQUENCE_NO),
    CONSTRAINT FK_OPS_RUN_EVENT_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_RUN_EVENT_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT CK_OPS_RUN_EVENT_SEQ CHECK (SEQUENCE_NO >= 1),
    CONSTRAINT CK_OPS_RUN_EVENT_VISIBLE
        CHECK (VISIBILITY IN ('INTERNAL', 'USER'))
);

CREATE UNIQUE INDEX UX_OPS_RUN_EVENT_KEY ON KBOT_OPS_RUN_EVENT (
    CASE WHEN EVENT_KEY IS NOT NULL THEN OPS_RUN_ID END,
    CASE WHEN EVENT_KEY IS NOT NULL THEN EVENT_KEY END
);
CREATE INDEX IX_OPS_RUN_EVENT_SSE
    ON KBOT_OPS_RUN_EVENT (OPS_RUN_ID, VISIBILITY, SEQUENCE_NO);
CREATE INDEX IX_OPS_RUN_EVENT_TASK
    ON KBOT_OPS_RUN_EVENT (OPS_TASK_ID);

COMMENT ON COLUMN KBOT_OPS_SIGNAL_EVENT.SOURCE_INBOX_ID IS
    '可靠消息 Inbox 的软审计引用；Inbox 可先于历史事件清理';
COMMENT ON COLUMN KBOT_OPS_RUN.AGENT_ID IS
    'Agent Runtime 的跨服务 UUID；不创建跨服务数据库外键';
COMMENT ON COLUMN KBOT_OPS_RUN_EVENT.VISIBILITY IS
    '仅 USER 事件可进入面向用户的 SSE 流';
-- KBot 4.0 AIOps：不可变变更建议、人工节点、审批授权和执行事实。

CREATE TABLE KBOT_OPS_CHANGE_PROPOSAL (
    PROPOSAL_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    SOLUTION_GROUP_KEY VARCHAR2(128 CHAR) NOT NULL,
    COMMAND_ORDINAL NUMBER(19) NOT NULL,
    PROPOSAL_VERSION NUMBER(19) NOT NULL,
    ACTION_TYPE VARCHAR2(32 CHAR) NOT NULL,
    ACTION_TEMPLATE_ID VARCHAR2(128 CHAR) NOT NULL,
    ACTION_TEMPLATE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    ACTION_TEMPLATE_HASH VARCHAR2(64 CHAR) NOT NULL,
    RENDERER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    COMMAND_HASH VARCHAR2(64 CHAR) NOT NULL,
    PARAMETERS_JSON JSON NOT NULL,
    PARAMETERS_HASH VARCHAR2(64 CHAR) NOT NULL,
    RATIONALE CLOB NOT NULL,
    IMPACT_SCOPE_JSON JSON,
    RISK_LEVEL VARCHAR2(16 CHAR) NOT NULL,
    PRECONDITIONS_JSON JSON,
    ROLLBACK_PLAN_JSON JSON,
    VERIFICATION_PLAN_JSON JSON,
    EVIDENCE_ARTIFACTS_JSON JSON,
    POLICY_DECISION_HASH VARCHAR2(64 CHAR) NOT NULL,
    PROPOSAL_HASH VARCHAR2(64 CHAR) NOT NULL,
    SNAPSHOT_ARTIFACT_ID RAW(16) NOT NULL,
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_BY_TASK_ID RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT UK_OPS_PROPOSAL_VERSION UNIQUE (
        OPS_RUN_ID, SOLUTION_GROUP_KEY, COMMAND_ORDINAL, PROPOSAL_VERSION
    ),
    CONSTRAINT FK_OPS_PROPOSAL_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_PROPOSAL_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_PROPOSAL_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_PROPOSAL_CREATED_TASK
        FOREIGN KEY (CREATED_BY_TASK_ID)
        REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT CK_OPS_PROPOSAL_ORDINAL CHECK (
        COMMAND_ORDINAL >= 1 AND PROPOSAL_VERSION >= 1
        AND ROW_VERSION >= 1
    ),
    CONSTRAINT CK_OPS_PROPOSAL_RISK
        CHECK (RISK_LEVEL IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT CK_OPS_PROPOSAL_STATUS CHECK (
        STATUS IN (
            'DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED',
            'EXPIRED', 'SUPERSEDED', 'CONSUMED', 'ADVISORY_READY'
        )
    ),
    CONSTRAINT CK_OPS_PROPOSAL_HASHES CHECK (
        LENGTH(ACTION_TEMPLATE_HASH) = 64
        AND LENGTH(COMMAND_HASH) = 64
        AND LENGTH(PARAMETERS_HASH) = 64
        AND LENGTH(POLICY_DECISION_HASH) = 64
        AND LENGTH(PROPOSAL_HASH) = 64
    )
);

CREATE INDEX IX_OPS_PROPOSAL_HASH
    ON KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_HASH);
CREATE INDEX IX_OPS_PROPOSAL_COMMAND
    ON KBOT_OPS_CHANGE_PROPOSAL (COMMAND_HASH);
CREATE INDEX IX_OPS_PROPOSAL_TARGET
    ON KBOT_OPS_CHANGE_PROPOSAL (TARGET_ID, STATUS, EXPIRES_AT);
CREATE INDEX IX_OPS_PROPOSAL_GROUP
    ON KBOT_OPS_CHANGE_PROPOSAL
       (OPS_RUN_ID, SOLUTION_GROUP_KEY, COMMAND_ORDINAL);
CREATE INDEX IX_OPS_PROPOSAL_TASK
    ON KBOT_OPS_CHANGE_PROPOSAL (OPS_TASK_ID);
CREATE INDEX IX_OPS_PROPOSAL_CREATED
    ON KBOT_OPS_CHANGE_PROPOSAL (CREATED_BY_TASK_ID);
CREATE INDEX IX_OPS_PROPOSAL_SNAPSHOT
    ON KBOT_OPS_CHANGE_PROPOSAL (SNAPSHOT_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_HITL (
    HITL_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16) NOT NULL,
    PROPOSAL_ID RAW(16),
    REQUEST_TYPE VARCHAR2(32 CHAR) NOT NULL,
    ASSIGNEE_USER_ID VARCHAR2(256 CHAR) NOT NULL,
    PROMPT_TEXT CLOB NOT NULL,
    RESPONSE_SCHEMA_JSON JSON,
    INPUT_ARTIFACTS_JSON JSON,
    RESPONSE_JSON JSON,
    RESPONSE_URI VARCHAR2(2048 CHAR),
    RESPONSE_HASH VARCHAR2(64 CHAR),
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    REQUESTED_BY VARCHAR2(256 CHAR) NOT NULL,
    RESPONDED_BY VARCHAR2(256 CHAR),
    REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    RESPONDED_AT TIMESTAMP(6) WITH TIME ZONE,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT UK_OPS_HITL_IDEMP UNIQUE (OPS_RUN_ID, IDEMPOTENCY_KEY),
    CONSTRAINT FK_OPS_HITL_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_HITL_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_HITL_PROPOSAL
        FOREIGN KEY (PROPOSAL_ID)
        REFERENCES KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_ID),
    CONSTRAINT CK_OPS_HITL_REQUEST CHECK (
        REQUEST_TYPE IN (
            'DATA_REQUIRED', 'MANUAL_DIAGNOSTIC_SQL',
            'MANUAL_ACTION_RESULT', 'CHANGE_APPROVAL'
        )
    ),
    CONSTRAINT CK_OPS_HITL_STATUS CHECK (
        STATUS IN (
            'PENDING', 'ANSWERED', 'APPROVED', 'REJECTED',
            'SKIPPED', 'EXPIRED', 'CANCELLED'
        )
    ),
    CONSTRAINT CK_OPS_HITL_VERSION CHECK (ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_HITL_RESPONSE_HASH CHECK (
        RESPONSE_HASH IS NULL OR LENGTH(RESPONSE_HASH) = 64
    )
);

CREATE INDEX IX_OPS_HITL_ASSIGNEE
    ON KBOT_OPS_HITL (ASSIGNEE_USER_ID, STATUS, EXPIRES_AT);
CREATE INDEX IX_OPS_HITL_TASK
    ON KBOT_OPS_HITL (OPS_TASK_ID);
CREATE INDEX IX_OPS_HITL_PROPOSAL
    ON KBOT_OPS_HITL (PROPOSAL_ID);

CREATE TABLE KBOT_OPS_APPROVAL_TOKEN (
    APPROVAL_TOKEN_ID RAW(16) PRIMARY KEY,
    PROPOSAL_ID RAW(16) NOT NULL,
    HITL_ID RAW(16) NOT NULL,
    TOKEN_HASH VARCHAR2(64 CHAR) NOT NULL,
    NONCE_HASH VARCHAR2(64 CHAR) NOT NULL,
    APPROVER_ID VARCHAR2(256 CHAR) NOT NULL,
    POLICY_DECISION_HASH VARCHAR2(64 CHAR) NOT NULL,
    TARGET_VERSION NUMBER(19) NOT NULL,
    PARAMETERS_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    ISSUED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSUMED_AT TIMESTAMP(6) WITH TIME ZONE,
    REVOKED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT UK_OPS_APPROVAL_TOKEN UNIQUE (TOKEN_HASH),
    CONSTRAINT UK_OPS_APPROVAL_NONCE UNIQUE (NONCE_HASH),
    CONSTRAINT UK_OPS_APPROVAL_PROPOSAL UNIQUE (PROPOSAL_ID),
    CONSTRAINT FK_OPS_APPROVAL_PROPOSAL
        FOREIGN KEY (PROPOSAL_ID)
        REFERENCES KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_ID),
    CONSTRAINT FK_OPS_APPROVAL_HITL
        FOREIGN KEY (HITL_ID) REFERENCES KBOT_OPS_HITL (HITL_ID),
    CONSTRAINT CK_OPS_APPROVAL_STATUS
        CHECK (STATUS IN ('ISSUED', 'CONSUMED', 'REVOKED', 'EXPIRED')),
    CONSTRAINT CK_OPS_APPROVAL_VERSION
        CHECK (TARGET_VERSION >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_APPROVAL_HASHES CHECK (
        LENGTH(TOKEN_HASH) = 64 AND LENGTH(NONCE_HASH) = 64
        AND LENGTH(POLICY_DECISION_HASH) = 64
        AND LENGTH(PARAMETERS_HASH) = 64
    )
);

CREATE INDEX IX_OPS_APPROVAL_EXPIRY
    ON KBOT_OPS_APPROVAL_TOKEN (STATUS, EXPIRES_AT);
CREATE INDEX IX_OPS_APPROVAL_HITL
    ON KBOT_OPS_APPROVAL_TOKEN (HITL_ID);

CREATE TABLE KBOT_OPS_EXECUTION (
    EXECUTION_ID RAW(16) PRIMARY KEY,
    PROPOSAL_ID RAW(16) NOT NULL,
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    EXECUTOR_REQUEST_ID VARCHAR2(128 CHAR) NOT NULL,
    PROPOSAL_HASH VARCHAR2(64 CHAR) NOT NULL,
    ACTION_TYPE VARCHAR2(32 CHAR) NOT NULL,
    ACTION_TEMPLATE_ID VARCHAR2(128 CHAR) NOT NULL,
    ACTION_TEMPLATE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    ACTION_TEMPLATE_HASH VARCHAR2(64 CHAR) NOT NULL,
    PARAMETERS_HASH VARCHAR2(64 CHAR) NOT NULL,
    COMMAND_HASH VARCHAR2(64 CHAR) NOT NULL,
    EXECUTION_KIND VARCHAR2(16 CHAR) NOT NULL,
    APPROVAL_TOKEN_ID RAW(16) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    EXECUTOR_INSTANCE_ID VARCHAR2(128 CHAR),
    CLAIMED_AT TIMESTAMP(6) WITH TIME ZONE,
    DEADLINE_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    GRANT_JTI_HASH VARCHAR2(64 CHAR),
    STATUS_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    RESULT_ARTIFACT_ID RAW(16),
    RESULT_HASH VARCHAR2(64 CHAR),
    ROLLBACK_OF_EXECUTION_ID RAW(16),
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_EXECUTION_IDEMP UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT UK_OPS_EXECUTION_REQUEST UNIQUE (EXECUTOR_REQUEST_ID),
    CONSTRAINT UK_OPS_EXECUTION_PROPOSAL UNIQUE (PROPOSAL_ID),
    CONSTRAINT FK_OPS_EXEC_PROPOSAL
        FOREIGN KEY (PROPOSAL_ID)
        REFERENCES KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_ID),
    CONSTRAINT FK_OPS_EXEC_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_EXEC_TASK
        FOREIGN KEY (OPS_TASK_ID) REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_EXEC_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_EXEC_APPROVAL
        FOREIGN KEY (APPROVAL_TOKEN_ID)
        REFERENCES KBOT_OPS_APPROVAL_TOKEN (APPROVAL_TOKEN_ID),
    CONSTRAINT FK_OPS_EXEC_ROLLBACK
        FOREIGN KEY (ROLLBACK_OF_EXECUTION_ID)
        REFERENCES KBOT_OPS_EXECUTION (EXECUTION_ID),
    CONSTRAINT CK_OPS_EXEC_KIND
        CHECK (EXECUTION_KIND IN ('MUTATION', 'ROLLBACK')),
    CONSTRAINT CK_OPS_EXEC_STATUS CHECK (
        STATUS IN (
            'CREATED', 'SUBMITTED', 'RUNNING', 'SUCCEEDED',
            'FAILED', 'TIMED_OUT', 'CANCELLED', 'UNKNOWN'
        )
    ),
    CONSTRAINT CK_OPS_EXEC_CLAIM CHECK (
        (STATUS IN ('CREATED', 'TIMED_OUT', 'CANCELLED')
         AND EXECUTOR_INSTANCE_ID IS NULL
         AND CLAIMED_AT IS NULL AND GRANT_JTI_HASH IS NULL)
        OR
        (STATUS <> 'CREATED' AND EXECUTOR_INSTANCE_ID IS NOT NULL
         AND CLAIMED_AT IS NOT NULL AND GRANT_JTI_HASH IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_EXEC_VERSION
        CHECK (STATUS_VERSION >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_EXEC_HASHES CHECK (
        LENGTH(PROPOSAL_HASH) = 64
        AND LENGTH(ACTION_TEMPLATE_HASH) = 64
        AND LENGTH(PARAMETERS_HASH) = 64
        AND LENGTH(COMMAND_HASH) = 64
        AND (GRANT_JTI_HASH IS NULL OR LENGTH(GRANT_JTI_HASH) = 64)
        AND (RESULT_HASH IS NULL OR LENGTH(RESULT_HASH) = 64)
    )
);

CREATE INDEX IX_OPS_EXEC_TARGET
    ON KBOT_OPS_EXECUTION (TARGET_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_EXEC_DEADLINE
    ON KBOT_OPS_EXECUTION (STATUS, DEADLINE_AT);
CREATE INDEX IX_OPS_EXEC_RUN
    ON KBOT_OPS_EXECUTION (OPS_RUN_ID, STATUS);
CREATE INDEX IX_OPS_EXEC_TASK
    ON KBOT_OPS_EXECUTION (OPS_TASK_ID);
CREATE INDEX IX_OPS_EXEC_INSTANCE
    ON KBOT_OPS_EXECUTION (EXECUTOR_INSTANCE_ID, STATUS);
CREATE INDEX IX_OPS_EXEC_APPROVAL
    ON KBOT_OPS_EXECUTION (APPROVAL_TOKEN_ID);
CREATE INDEX IX_OPS_EXEC_ROLLBACK
    ON KBOT_OPS_EXECUTION (ROLLBACK_OF_EXECUTION_ID);
CREATE INDEX IX_OPS_EXEC_RESULT
    ON KBOT_OPS_EXECUTION (RESULT_ARTIFACT_ID);

COMMENT ON COLUMN KBOT_OPS_HITL.PROMPT_TEXT IS
    '仅保存安全说明；完整 SQL 或用户上传正文必须进入受控 Artifact';
COMMENT ON COLUMN KBOT_OPS_APPROVAL_TOKEN.TOKEN_HASH IS
    '规范化 Approval Claims 的 Hash，不是可执行 Bearer Token';
COMMENT ON COLUMN KBOT_OPS_EXECUTION.COMMAND_HASH IS
    'Executor 必须重新计算并与审批快照逐项比对';
-- KBot 4.0 AIOps：巡检计划、调度 Fire 和版本化报告投影。

CREATE TABLE KBOT_OPS_INSPECTION_PLAN (
    INSPECTION_PLAN_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    SCHEDULE_TYPE VARCHAR2(16 CHAR) NOT NULL,
    CRON_EXPRESSION VARCHAR2(256 CHAR) NOT NULL,
    TIMEZONE VARCHAR2(64 CHAR) NOT NULL,
    TEMPLATE_ID VARCHAR2(128 CHAR) NOT NULL,
    TEMPLATE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    TIMEOUT_SECONDS NUMBER(10) NOT NULL,
    OVERLAP_POLICY VARCHAR2(16 CHAR) NOT NULL,
    MISFIRE_POLICY VARCHAR2(16 CHAR) NOT NULL,
    SCHEDULE_RESOLVER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'PAUSED' NOT NULL,
    NEXT_RUN_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_RUN_AT TIMESTAMP(6) WITH TIME ZONE,
    LAST_SCHEDULED_FOR TIMESTAMP(6) WITH TIME ZONE,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_INSP_PLAN_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_OPS_INSP_PLAN_SCHEDULE
        CHECK (SCHEDULE_TYPE IN ('DAILY', 'WEEKLY', 'CRON')),
    CONSTRAINT CK_OPS_INSP_PLAN_OVERLAP
        CHECK (OVERLAP_POLICY IN ('SKIP', 'QUEUE')),
    CONSTRAINT CK_OPS_INSP_PLAN_MISFIRE
        CHECK (MISFIRE_POLICY IN ('SKIP', 'LATEST_ONLY')),
    CONSTRAINT CK_OPS_INSP_PLAN_STATUS
        CHECK (STATUS IN ('ACTIVE', 'PAUSED', 'DISABLED')),
    CONSTRAINT CK_OPS_INSP_PLAN_NUMBERS
        CHECK (TIMEOUT_SECONDS >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_OPS_INSP_PLAN_LEASE CHECK (
        (LEASE_OWNER IS NULL AND LEASE_TOKEN IS NULL AND LEASE_UNTIL IS NULL)
        OR
        (LEASE_OWNER IS NOT NULL
         AND LEASE_TOKEN IS NOT NULL AND LEASE_UNTIL IS NOT NULL)
    )
);

CREATE INDEX IX_OPS_INSP_PLAN_DUE
    ON KBOT_OPS_INSPECTION_PLAN (STATUS, NEXT_RUN_AT);
CREATE INDEX IX_OPS_INSP_PLAN_LEASE
    ON KBOT_OPS_INSPECTION_PLAN (STATUS, LEASE_UNTIL);
CREATE INDEX IX_OPS_INSP_PLAN_DOMAIN
    ON KBOT_OPS_INSPECTION_PLAN (DOMAIN_ID);

CREATE TABLE KBOT_OPS_INSPECTION_TARGET (
    INSPECTION_TARGET_ID RAW(16) PRIMARY KEY,
    INSPECTION_PLAN_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    TEMPLATE_OVERRIDES_JSON JSON,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_INSP_TARGET
        UNIQUE (INSPECTION_PLAN_ID, TARGET_ID),
    CONSTRAINT FK_OPS_INSP_TARGET_PLAN
        FOREIGN KEY (INSPECTION_PLAN_ID)
        REFERENCES KBOT_OPS_INSPECTION_PLAN (INSPECTION_PLAN_ID),
    CONSTRAINT FK_OPS_INSP_TARGET_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT CK_OPS_INSP_TARGET_STATUS
        CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE INDEX IX_OPS_INSP_TARGET_TARGET
    ON KBOT_OPS_INSPECTION_TARGET (TARGET_ID, STATUS);

CREATE TABLE KBOT_OPS_INSPECTION_FIRE (
    INSPECTION_FIRE_ID RAW(16) PRIMARY KEY,
    INSPECTION_PLAN_ID RAW(16) NOT NULL,
    SCHEDULED_FOR TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    SCHEDULED_FOR_UTC TIMESTAMP(6)
        GENERATED ALWAYS AS (SYS_EXTRACT_UTC(SCHEDULED_FOR)) VIRTUAL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    PLAN_ROW_VERSION NUMBER(19) NOT NULL,
    TEMPLATE_ID VARCHAR2(128 CHAR) NOT NULL,
    TEMPLATE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    SCHEDULE_RESOLVER_VERSION VARCHAR2(64 CHAR) NOT NULL,
    PLAN_SNAPSHOT_JSON JSON NOT NULL,
    RESOLUTION_JSON JSON,
    TARGET_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    RUN_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    COMPLETED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    FAILED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    SKIP_REASON VARCHAR2(256 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT UK_OPS_INSP_FIRE
        UNIQUE (INSPECTION_PLAN_ID, SCHEDULED_FOR_UTC),
    CONSTRAINT FK_OPS_INSP_FIRE_PLAN
        FOREIGN KEY (INSPECTION_PLAN_ID)
        REFERENCES KBOT_OPS_INSPECTION_PLAN (INSPECTION_PLAN_ID),
    CONSTRAINT CK_OPS_INSP_FIRE_STATUS CHECK (
        STATUS IN (
            'QUEUED', 'RUNNING', 'COMPLETED', 'PARTIAL',
            'FAILED', 'SKIPPED', 'CANCELLED'
        )
    ),
    CONSTRAINT CK_OPS_INSP_FIRE_COUNTS CHECK (
        PLAN_ROW_VERSION >= 1 AND ROW_VERSION >= 1
        AND TARGET_COUNT >= 0 AND RUN_COUNT >= 0
        AND COMPLETED_COUNT >= 0 AND FAILED_COUNT >= 0
        AND RUN_COUNT <= TARGET_COUNT
        AND COMPLETED_COUNT <= RUN_COUNT
        AND COMPLETED_COUNT + FAILED_COUNT <= TARGET_COUNT
    )
);

CREATE INDEX IX_OPS_INSP_FIRE_PLAN
    ON KBOT_OPS_INSPECTION_FIRE
       (INSPECTION_PLAN_ID, STATUS, SCHEDULED_FOR);
CREATE INDEX IX_OPS_INSP_FIRE_STATUS
    ON KBOT_OPS_INSPECTION_FIRE (STATUS, UPDATED_AT);

CREATE TABLE KBOT_OPS_REPORT (
    REPORT_ID RAW(16) PRIMARY KEY,
    OPS_RUN_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    REPORT_KEY VARCHAR2(128 CHAR) NOT NULL,
    REPORT_VERSION NUMBER(19) NOT NULL,
    SUPERSEDES_REPORT_ID RAW(16),
    IS_CURRENT NUMBER(1) DEFAULT 0 NOT NULL,
    REPORT_TYPE VARCHAR2(32 CHAR) NOT NULL,
    TITLE VARCHAR2(512 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    PERIOD_START TIMESTAMP(6) WITH TIME ZONE,
    PERIOD_END TIMESTAMP(6) WITH TIME ZONE,
    BASELINE_START TIMESTAMP(6) WITH TIME ZONE,
    BASELINE_END TIMESTAMP(6) WITH TIME ZONE,
    AFTER_START TIMESTAMP(6) WITH TIME ZONE,
    AFTER_END TIMESTAMP(6) WITH TIME ZONE,
    RESULT VARCHAR2(16 CHAR),
    TEMPLATE_ID VARCHAR2(128 CHAR) NOT NULL,
    TEMPLATE_VERSION VARCHAR2(64 CHAR) NOT NULL,
    GENERATED_BY_TASK_ID RAW(16) NOT NULL,
    CONTENT_ARTIFACT_ID RAW(16),
    CONTENT_HASH VARCHAR2(64 CHAR),
    SUMMARY VARCHAR2(2000 CHAR),
    SECURITY_LEVEL NUMBER(3) NOT NULL,
    SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_REPORT_VERSION
        UNIQUE (OPS_RUN_ID, REPORT_KEY, REPORT_VERSION),
    CONSTRAINT FK_OPS_REPORT_RUN
        FOREIGN KEY (OPS_RUN_ID) REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_REPORT_TARGET
        FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID),
    CONSTRAINT FK_OPS_REPORT_TASK
        FOREIGN KEY (GENERATED_BY_TASK_ID)
        REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_REPORT_SUPERSEDES
        FOREIGN KEY (SUPERSEDES_REPORT_ID)
        REFERENCES KBOT_OPS_REPORT (REPORT_ID),
    CONSTRAINT CK_OPS_REPORT_TYPE CHECK (
        REPORT_TYPE IN (
            'INCIDENT', 'PERFORMANCE', 'INSPECTION_DAILY',
            'INSPECTION_WEEKLY', 'COMPARISON'
        )
    ),
    CONSTRAINT CK_OPS_REPORT_STATUS
        CHECK (STATUS IN ('GENERATING', 'READY', 'PARTIAL', 'FAILED')),
    CONSTRAINT CK_OPS_REPORT_RESULT CHECK (
        RESULT IS NULL OR RESULT IN (
            'RESOLVED', 'IMPROVED', 'UNCHANGED', 'DEGRADED',
            'INCONCLUSIVE'
        )
    ),
    CONSTRAINT CK_OPS_REPORT_NUMBERS CHECK (
        REPORT_VERSION >= 1 AND IS_CURRENT IN (0, 1)
        AND SECURITY_LEVEL >= 0
    ),
    CONSTRAINT CK_OPS_REPORT_CURRENT CHECK (
        IS_CURRENT = 0
        OR
        (STATUS IN ('READY', 'PARTIAL')
         AND CONTENT_ARTIFACT_ID IS NOT NULL AND CONTENT_HASH IS NOT NULL)
    ),
    CONSTRAINT CK_OPS_REPORT_HASH CHECK (
        CONTENT_HASH IS NULL OR LENGTH(CONTENT_HASH) = 64
    )
);

CREATE INDEX IX_OPS_REPORT_TARGET
    ON KBOT_OPS_REPORT
       (TARGET_ID, REPORT_TYPE, IS_CURRENT, CREATED_AT);
CREATE INDEX IX_OPS_REPORT_STATUS
    ON KBOT_OPS_REPORT (STATUS, CREATED_AT);
CREATE INDEX IX_OPS_REPORT_TASK
    ON KBOT_OPS_REPORT (GENERATED_BY_TASK_ID);
CREATE INDEX IX_OPS_REPORT_SUPERSEDES
    ON KBOT_OPS_REPORT (SUPERSEDES_REPORT_ID);
CREATE INDEX IX_OPS_REPORT_CONTENT
    ON KBOT_OPS_REPORT (CONTENT_ARTIFACT_ID);

COMMENT ON COLUMN KBOT_OPS_INSPECTION_PLAN.CRON_EXPRESSION IS
    '规范五段 Cron；应用按 IANA 时区预计算 NEXT_RUN_AT';
COMMENT ON COLUMN KBOT_OPS_INSPECTION_FIRE.PLAN_SNAPSHOT_JSON IS
    'Fire 创建时冻结的计划配置，后续修改 Plan 不影响本次执行';
COMMENT ON COLUMN KBOT_OPS_INSPECTION_FIRE.SCHEDULED_FOR_UTC IS
    '由 SCHEDULED_FOR 生成的 UTC 虚拟列，仅用于 Oracle 唯一约束';
COMMENT ON COLUMN KBOT_OPS_REPORT.CONTENT_ARTIFACT_ID IS
    '完整报告的不可变 Artifact；本表只承担可查询的发布投影';
-- KBot 4.0 AIOps：外部交付去重 Inbox 与事务消息 Outbox。

CREATE TABLE KBOT_OPS_INBOX (
    INBOX_ID RAW(16) PRIMARY KEY,
    SOURCE_SYSTEM VARCHAR2(64 CHAR) NOT NULL,
    MESSAGE_KEY VARCHAR2(256 CHAR) NOT NULL,
    MESSAGE_TYPE VARCHAR2(64 CHAR) NOT NULL,
    PAYLOAD_JSON JSON,
    PAYLOAD_URI VARCHAR2(2048 CHAR),
    PAYLOAD_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'RECEIVED' NOT NULL,
    RECEIVED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PROCESSED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT UK_OPS_INBOX_MESSAGE UNIQUE (SOURCE_SYSTEM, MESSAGE_KEY),
    CONSTRAINT CK_OPS_INBOX_PAYLOAD
        CHECK (PAYLOAD_JSON IS NOT NULL OR PAYLOAD_URI IS NOT NULL),
    CONSTRAINT CK_OPS_INBOX_STATUS CHECK (
        STATUS IN ('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED', 'IGNORED')
    ),
    CONSTRAINT CK_OPS_INBOX_HASH CHECK (LENGTH(PAYLOAD_HASH) = 64),
    CONSTRAINT CK_OPS_INBOX_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_OPS_INBOX_CLAIM
    ON KBOT_OPS_INBOX (STATUS, RECEIVED_AT);

CREATE TABLE KBOT_OPS_OUTBOX (
    OUTBOX_ID RAW(16) PRIMARY KEY,
    AGGREGATE_TYPE VARCHAR2(64 CHAR) NOT NULL,
    AGGREGATE_ID RAW(16) NOT NULL,
    EVENT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(256 CHAR) NOT NULL,
    PAYLOAD_JSON JSON,
    PAYLOAD_URI VARCHAR2(2048 CHAR),
    PAYLOAD_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'PENDING' NOT NULL,
    AVAILABLE_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATTEMPT_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    MAX_ATTEMPTS NUMBER(8) DEFAULT 3 NOT NULL,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_OPS_OUTBOX_IDEMP UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT CK_OPS_OUTBOX_PAYLOAD
        CHECK (PAYLOAD_JSON IS NOT NULL OR PAYLOAD_URI IS NOT NULL),
    CONSTRAINT CK_OPS_OUTBOX_STATUS CHECK (
        STATUS IN (
            'PENDING', 'PUBLISHING', 'PUBLISHED', 'RETRY_WAIT', 'FAILED'
        )
    ),
    CONSTRAINT CK_OPS_OUTBOX_ATTEMPTS CHECK (
        ATTEMPT_COUNT >= 0 AND MAX_ATTEMPTS >= 1
        AND ATTEMPT_COUNT <= MAX_ATTEMPTS
    ),
    CONSTRAINT CK_OPS_OUTBOX_LEASE CHECK (
        (STATUS = 'PUBLISHING' AND LEASE_OWNER IS NOT NULL
         AND LEASE_TOKEN IS NOT NULL AND LEASE_UNTIL IS NOT NULL)
        OR
        (STATUS <> 'PUBLISHING' AND LEASE_OWNER IS NULL
         AND LEASE_TOKEN IS NULL AND LEASE_UNTIL IS NULL)
    ),
    CONSTRAINT CK_OPS_OUTBOX_HASH CHECK (LENGTH(PAYLOAD_HASH) = 64)
);

CREATE INDEX IX_OPS_OUTBOX_CLAIM
    ON KBOT_OPS_OUTBOX (STATUS, AVAILABLE_AT);
CREATE INDEX IX_OPS_OUTBOX_LEASE
    ON KBOT_OPS_OUTBOX (STATUS, LEASE_UNTIL);
CREATE INDEX IX_OPS_OUTBOX_AGGREGATE
    ON KBOT_OPS_OUTBOX (AGGREGATE_TYPE, AGGREGATE_ID);

COMMENT ON COLUMN KBOT_OPS_INBOX.PAYLOAD_HASH IS
    '验签后原始交付内容的 SHA-256，用于审计和重复内容识别';
COMMENT ON COLUMN KBOT_OPS_OUTBOX.AGGREGATE_ID IS
    '多态领域聚合 UUID；不创建无法成立的跨表外键';
-- KBot 4.0 AIOps：循环外键、函数唯一索引和 APEX 只读投影。

ALTER TABLE KBOT_OPS_TARGET ADD CONSTRAINT FK_OPS_TARGET_DIAG_CRED
    FOREIGN KEY (DIAGNOSTIC_CREDENTIAL_ID, DOMAIN_ID)
    REFERENCES KBOT_MANAGED_CREDENTIAL (CREDENTIAL_ID, DOMAIN_ID);
ALTER TABLE KBOT_OPS_TARGET ADD CONSTRAINT FK_OPS_TARGET_EXEC_CRED
    FOREIGN KEY (EXECUTION_CREDENTIAL_ID, DOMAIN_ID)
    REFERENCES KBOT_MANAGED_CREDENTIAL (CREDENTIAL_ID, DOMAIN_ID);
CREATE INDEX IX_OPS_TARGET_DIAG_CRED
    ON KBOT_OPS_TARGET (DIAGNOSTIC_CREDENTIAL_ID, DOMAIN_ID);
CREATE INDEX IX_OPS_TARGET_EXEC_CRED
    ON KBOT_OPS_TARGET (EXECUTION_CREDENTIAL_ID, DOMAIN_ID);
ALTER TABLE KBOT_OPS_DIAGNOSTIC_SOURCE
    ADD CONSTRAINT FK_OPS_SOURCE_AUTH_CRED
    FOREIGN KEY (AUTH_CREDENTIAL_ID, DOMAIN_ID)
    REFERENCES KBOT_MANAGED_CREDENTIAL (CREDENTIAL_ID, DOMAIN_ID);
ALTER TABLE KBOT_OPS_DIAGNOSTIC_SOURCE
    ADD CONSTRAINT FK_OPS_SOURCE_WEBHOOK_CRED
    FOREIGN KEY (WEBHOOK_CREDENTIAL_ID, DOMAIN_ID)
    REFERENCES KBOT_MANAGED_CREDENTIAL (CREDENTIAL_ID, DOMAIN_ID);
CREATE INDEX IX_OPS_SOURCE_AUTH_CRED
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (AUTH_CREDENTIAL_ID, DOMAIN_ID);
CREATE INDEX IX_OPS_SOURCE_WEBHOOK_CRED
    ON KBOT_OPS_DIAGNOSTIC_SOURCE (WEBHOOK_CREDENTIAL_ID, DOMAIN_ID);
-- RAW(16) 在视图中显式格式化，避免 APEX/驱动依赖 Oracle UUID 类型映射。

ALTER TABLE KBOT_OPS_RUN ADD CONSTRAINT FK_OPS_RUN_INSP_FIRE
    FOREIGN KEY (INSPECTION_FIRE_ID)
    REFERENCES KBOT_OPS_INSPECTION_FIRE (INSPECTION_FIRE_ID);

ALTER TABLE KBOT_OPS_RUN ADD CONSTRAINT FK_OPS_RUN_FINAL_ART
    FOREIGN KEY (FINAL_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE KBOT_OPS_RUN ADD CONSTRAINT FK_OPS_RUN_SOURCE_PROPOSAL
    FOREIGN KEY (SOURCE_PROPOSAL_ID)
    REFERENCES KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_ID);

ALTER TABLE KBOT_OPS_RUN ADD CONSTRAINT FK_OPS_RUN_SOURCE_RESULT
    FOREIGN KEY (SOURCE_RESULT_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID);

ALTER TABLE KBOT_OPS_TASK ADD CONSTRAINT FK_OPS_TASK_OUTPUT_ART
    FOREIGN KEY (OUTPUT_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE KBOT_OPS_CHANGE_PROPOSAL
    ADD CONSTRAINT FK_OPS_PROP_SNAPSHOT_ART
    FOREIGN KEY (SNAPSHOT_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE KBOT_OPS_EXECUTION ADD CONSTRAINT FK_OPS_EXEC_RESULT_ART
    FOREIGN KEY (RESULT_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE KBOT_OPS_REPORT ADD CONSTRAINT FK_OPS_REPORT_CONTENT_ART
    FOREIGN KEY (CONTENT_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX IX_OPS_RUN_FINAL_ART ON KBOT_OPS_RUN (FINAL_ARTIFACT_ID);
CREATE INDEX IX_OPS_RUN_SOURCE_RESULT
    ON KBOT_OPS_RUN (SOURCE_RESULT_ARTIFACT_ID);
CREATE INDEX IX_OPS_TASK_OUTPUT_ART
    ON KBOT_OPS_TASK (OUTPUT_ARTIFACT_ID);

CREATE UNIQUE INDEX UX_OPS_POLICY_ACTIVE ON KBOT_OPS_POLICY (
    CASE WHEN STATUS = 'ACTIVE' THEN DOMAIN_ID END,
    CASE WHEN STATUS = 'ACTIVE' THEN POLICY_KEY END
);

CREATE UNIQUE INDEX UX_OPS_SITUATION_ACTIVE ON KBOT_OPS_SITUATION (
    CASE
        WHEN STATUS IN (
            'OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'DIAGNOSED',
            'MITIGATING', 'OBSERVING', 'SUPPRESSED'
        )
        THEN TARGET_ID
    END,
    CASE
        WHEN STATUS IN (
            'OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'DIAGNOSED',
            'MITIGATING', 'OBSERVING', 'SUPPRESSED'
        )
        THEN CORRELATION_HASH
    END
);

CREATE UNIQUE INDEX UX_OPS_HITL_PENDING ON KBOT_OPS_HITL (
    CASE WHEN STATUS = 'PENDING' THEN OPS_TASK_ID END,
    CASE WHEN STATUS = 'PENDING' THEN REQUEST_TYPE END
);

CREATE UNIQUE INDEX UX_OPS_REPORT_CURRENT ON KBOT_OPS_REPORT (
    CASE WHEN IS_CURRENT = 1 THEN OPS_RUN_ID END,
    CASE WHEN IS_CURRENT = 1 THEN REPORT_KEY END
);

CREATE OR REPLACE VIEW KBOT_V_OPS_TARGET AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(t.TARGET_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 21, 12)
    ) AS TARGET_ID,
    t.DOMAIN_ID,
    t.DISPLAY_NAME,
    t.DB_TYPE,
    t.VERSION_CODE,
    t.ENVIRONMENT,
    t.DB_ROLE,
    t.SECURITY_LEVEL,
    t.STATUS,
    t.HEALTH_STATUS,
    t.LAST_HEALTH_CHECK_AT,
    t.LAST_ERROR_CODE,
    t.ROW_VERSION,
    t.CREATED_AT,
    t.UPDATED_AT,
    COUNT(tm.TARGET_SOURCE_BINDING_ID) AS SOURCE_BINDING_COUNT,
    SUM(CASE WHEN tm.HEALTH_STATUS = 'HEALTHY' THEN 1 ELSE 0 END)
        AS HEALTHY_SOURCE_BINDING_COUNT,
    SUM(CASE WHEN tm.HEALTH_STATUS IN ('DEGRADED', 'UNREACHABLE')
             THEN 1 ELSE 0 END) AS UNHEALTHY_SOURCE_BINDING_COUNT
FROM KBOT_OPS_TARGET t
LEFT JOIN KBOT_OPS_TARGET_SOURCE_BINDING tm
    ON tm.TARGET_ID = t.TARGET_ID
   AND tm.STATUS = 'ACTIVE'
GROUP BY
    t.TARGET_ID, t.DOMAIN_ID, t.DISPLAY_NAME,
    t.DB_TYPE, t.VERSION_CODE, t.ENVIRONMENT, t.DB_ROLE,
    t.SECURITY_LEVEL, t.STATUS, t.HEALTH_STATUS,
    t.LAST_HEALTH_CHECK_AT, t.LAST_ERROR_CODE, t.ROW_VERSION,
    t.CREATED_AT, t.UPDATED_AT;

CREATE OR REPLACE VIEW KBOT_V_OPS_DIAGNOSTIC_SOURCE AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(m.DIAGNOSTIC_SOURCE_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(m.DIAGNOSTIC_SOURCE_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(m.DIAGNOSTIC_SOURCE_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(m.DIAGNOSTIC_SOURCE_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(m.DIAGNOSTIC_SOURCE_ID), 21, 12)
    ) AS DIAGNOSTIC_SOURCE_ID,
    m.DOMAIN_ID,
    m.DISPLAY_NAME,
    m.SOURCE_TYPE,
    m.STATUS,
    m.HEALTH_STATUS,
    m.LAST_HEALTH_CHECK_AT,
    m.LAST_ERROR_CODE,
    m.ROW_VERSION,
    m.CREATED_AT,
    m.UPDATED_AT,
    COUNT(tm.TARGET_SOURCE_BINDING_ID) AS ACTIVE_TARGET_COUNT
FROM KBOT_OPS_DIAGNOSTIC_SOURCE m
LEFT JOIN KBOT_OPS_TARGET_SOURCE_BINDING tm
    ON tm.DIAGNOSTIC_SOURCE_ID = m.DIAGNOSTIC_SOURCE_ID
   AND tm.STATUS = 'ACTIVE'
GROUP BY
    m.DIAGNOSTIC_SOURCE_ID, m.DOMAIN_ID,
    m.DISPLAY_NAME, m.SOURCE_TYPE, m.STATUS, m.HEALTH_STATUS,
    m.LAST_HEALTH_CHECK_AT, m.LAST_ERROR_CODE, m.ROW_VERSION,
    m.CREATED_AT, m.UPDATED_AT;

CREATE OR REPLACE VIEW KBOT_V_OPS_POLICY AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(p.POLICY_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(p.POLICY_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.POLICY_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.POLICY_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.POLICY_ID), 21, 12)
    ) AS POLICY_ID,
    p.DOMAIN_ID,
    p.POLICY_KEY,
    p.VERSION_NO,
    p.DISPLAY_NAME,
    p.POLICY_HASH,
    p.STATUS,
    p.EFFECTIVE_AT,
    p.RETIRED_AT,
    p.ROW_VERSION,
    p.CREATED_AT,
    p.UPDATED_AT
FROM KBOT_OPS_POLICY p;

CREATE OR REPLACE VIEW KBOT_V_OPS_INSPECTION_PLAN AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(p.INSPECTION_PLAN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(p.INSPECTION_PLAN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.INSPECTION_PLAN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.INSPECTION_PLAN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.INSPECTION_PLAN_ID), 21, 12)
    ) AS INSPECTION_PLAN_ID,
    p.DOMAIN_ID,
    p.DISPLAY_NAME,
    p.SCHEDULE_TYPE,
    p.CRON_EXPRESSION,
    p.TIMEZONE,
    p.TEMPLATE_ID,
    p.TEMPLATE_VERSION,
    p.STATUS,
    p.NEXT_RUN_AT,
    p.LAST_RUN_AT,
    p.LAST_SCHEDULED_FOR,
    p.ROW_VERSION,
    p.CREATED_AT,
    p.UPDATED_AT
FROM KBOT_OPS_INSPECTION_PLAN p;

CREATE OR REPLACE VIEW KBOT_V_OPS_INSPECTION_FIRE AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(f.INSPECTION_FIRE_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_FIRE_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_FIRE_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_FIRE_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_FIRE_ID), 21, 12)
    ) AS INSPECTION_FIRE_ID,
    LOWER(
        SUBSTR(RAWTOHEX(f.INSPECTION_PLAN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_PLAN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_PLAN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_PLAN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(f.INSPECTION_PLAN_ID), 21, 12)
    ) AS INSPECTION_PLAN_ID,
    p.DOMAIN_ID,
    f.SCHEDULED_FOR,
    f.STATUS,
    f.TARGET_COUNT,
    f.RUN_COUNT,
    f.COMPLETED_COUNT,
    f.FAILED_COUNT,
    f.SKIP_REASON,
    f.STARTED_AT,
    f.COMPLETED_AT,
    f.CREATED_AT,
    f.UPDATED_AT
FROM KBOT_OPS_INSPECTION_FIRE f
JOIN KBOT_OPS_INSPECTION_PLAN p
    ON p.INSPECTION_PLAN_ID = f.INSPECTION_PLAN_ID;

CREATE OR REPLACE VIEW KBOT_V_OPS_RUN AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 21, 12)
    ) AS OPS_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.TARGET_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 21, 12)
    ) AS TARGET_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.SOURCE_PROPOSAL_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_PROPOSAL_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_PROPOSAL_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_PROPOSAL_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_PROPOSAL_ID), 21, 12)
    ) AS SOURCE_PROPOSAL_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.SOURCE_RESULT_ARTIFACT_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_RESULT_ARTIFACT_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_RESULT_ARTIFACT_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_RESULT_ARTIFACT_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.SOURCE_RESULT_ARTIFACT_ID), 21, 12)
    ) AS SOURCE_RESULT_ARTIFACT_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 21, 12)
    ) AS PARENT_AGENT_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 21, 12)
    ) AS PARENT_DELEGATION_ID,
    t.DOMAIN_ID,
    t.DISPLAY_NAME AS TARGET_NAME,
    r.TRIGGER_TYPE,
    r.ACTOR_ID,
    r.STATUS,
    r.ROOT_CAUSE_LEVEL,
    r.ERROR_CODE,
    r.TRACE_ID,
    r.CREATED_AT,
    r.STARTED_AT,
    r.COMPLETED_AT,
    report_info.REPORT_COUNT,
    report_info.LATEST_REPORT_SUMMARY
FROM KBOT_OPS_RUN r
JOIN KBOT_OPS_TARGET t ON t.TARGET_ID = r.TARGET_ID
LEFT JOIN (
    SELECT
        OPS_RUN_ID,
        COUNT(*) AS REPORT_COUNT,
        MAX(SUMMARY) KEEP (DENSE_RANK LAST ORDER BY UPDATED_AT)
            AS LATEST_REPORT_SUMMARY
    FROM KBOT_OPS_REPORT
    WHERE IS_CURRENT = 1
    GROUP BY OPS_RUN_ID
) report_info ON report_info.OPS_RUN_ID = r.OPS_RUN_ID;

CREATE OR REPLACE VIEW KBOT_V_OPS_PENDING_APPROVAL AS
SELECT
    t.DOMAIN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(p.PROPOSAL_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(p.PROPOSAL_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.PROPOSAL_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.PROPOSAL_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.PROPOSAL_ID), 21, 12)
    ) AS PROPOSAL_ID,
    LOWER(
        SUBSTR(RAWTOHEX(h.HITL_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 21, 12)
    ) AS HITL_ID,
    LOWER(
        SUBSTR(RAWTOHEX(p.OPS_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(p.OPS_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.OPS_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.OPS_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.OPS_RUN_ID), 21, 12)
    ) AS OPS_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(p.TARGET_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(p.TARGET_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.TARGET_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.TARGET_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(p.TARGET_ID), 21, 12)
    ) AS TARGET_ID,
    t.DISPLAY_NAME AS TARGET_NAME,
    h.ASSIGNEE_USER_ID,
    p.ACTION_TYPE,
    p.ACTION_TEMPLATE_ID,
    p.ACTION_TEMPLATE_VERSION,
    p.RISK_LEVEL,
    p.RATIONALE,
    p.STATUS AS PROPOSAL_STATUS,
    h.STATUS AS HITL_STATUS,
    h.EXPIRES_AT
FROM KBOT_OPS_CHANGE_PROPOSAL p
JOIN KBOT_OPS_HITL h ON h.PROPOSAL_ID = p.PROPOSAL_ID
JOIN KBOT_OPS_TARGET t ON t.TARGET_ID = p.TARGET_ID
WHERE p.STATUS = 'PENDING_APPROVAL'
  AND h.STATUS = 'PENDING'
  AND h.REQUEST_TYPE = 'CHANGE_APPROVAL';

CREATE OR REPLACE VIEW KBOT_V_OPS_REPORT AS
SELECT
    t.DOMAIN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.REPORT_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.REPORT_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.REPORT_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.REPORT_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.REPORT_ID), 21, 12)
    ) AS REPORT_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 21, 12)
    ) AS OPS_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.TARGET_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 21, 12)
    ) AS TARGET_ID,
    t.DISPLAY_NAME AS TARGET_NAME,
    r.REPORT_KEY,
    r.REPORT_VERSION,
    r.REPORT_TYPE,
    r.TITLE,
    r.STATUS,
    r.PERIOD_START,
    r.PERIOD_END,
    r.BASELINE_START,
    r.BASELINE_END,
    r.AFTER_START,
    r.AFTER_END,
    r.RESULT,
    r.SUMMARY,
    r.SECURITY_LEVEL,
    r.CREATED_AT,
    r.UPDATED_AT
FROM KBOT_OPS_REPORT r
JOIN KBOT_OPS_TARGET t ON t.TARGET_ID = r.TARGET_ID
WHERE r.IS_CURRENT = 1;

CREATE OR REPLACE VIEW KBOT_V_OPS_CHAT_PENDING AS
SELECT
    t.DOMAIN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.OPS_RUN_ID), 21, 12)
    ) AS OPS_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_AGENT_RUN_ID), 21, 12)
    ) AS PARENT_AGENT_RUN_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.PARENT_DELEGATION_ID), 21, 12)
    ) AS PARENT_DELEGATION_ID,
    LOWER(
        SUBSTR(RAWTOHEX(h.HITL_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(h.HITL_ID), 21, 12)
    ) AS HITL_ID,
    LOWER(
        SUBSTR(RAWTOHEX(r.TARGET_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(r.TARGET_ID), 21, 12)
    ) AS TARGET_ID,
    t.DISPLAY_NAME AS TARGET_NAME,
    h.ASSIGNEE_USER_ID,
    h.REQUEST_TYPE,
    h.PROMPT_TEXT,
    h.REQUESTED_AT,
    h.EXPIRES_AT
FROM KBOT_OPS_HITL h
JOIN KBOT_OPS_RUN r ON r.OPS_RUN_ID = h.OPS_RUN_ID
JOIN KBOT_OPS_TARGET t ON t.TARGET_ID = r.TARGET_ID
WHERE r.TRIGGER_TYPE IN ('CHAT', 'ROOT')
  AND h.STATUS = 'PENDING';

CREATE OR REPLACE VIEW KBOT_V_OPS_SCHEMA_VERSION AS
SELECT
    'AIOPS' AS COMPONENT,
    10 AS SCHEMA_VERSION,
    'aiops-oracle-v2' AS CONTRACT_VERSION
FROM DUAL;

COMMENT ON COLUMN KBOT_OPS_RUN.FINAL_ARTIFACT_ID IS
    'Run 最终不可变产物；延后外键支持同一事务建立循环引用';
COMMENT ON COLUMN KBOT_OPS_TASK.OUTPUT_ARTIFACT_ID IS
    'Task 当前输出指针；Artifact 本身只追加且不可变';
-- AIOps 应用私有 Agent、不可变版本和用户/角色授权。

CREATE TABLE KBOT_OPS_AGENT (
    AGENT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    CURRENT_VERSION_ID RAW(16),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_AGENT_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_OPS_AGENT_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT CK_OPS_AGENT_STATUS
        CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED')),
    CONSTRAINT CK_OPS_AGENT_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_AGENT_SCOPE_STATUS ON KBOT_OPS_AGENT (DOMAIN_ID, STATUS);

CREATE TABLE KBOT_OPS_AGENT_VERSION (
    AGENT_VERSION_ID RAW(16) PRIMARY KEY,
    AGENT_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    POLICY_ID RAW(16) NOT NULL,
    MODELS_JSON JSON NOT NULL,
    IMAGE_CAPABILITIES_JSON JSON NOT NULL,
    INSTRUCTION CLOB,
    CONFIG_JSON JSON NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_AGENT_VERSION_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES KBOT_OPS_AGENT (AGENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_AGENT_VERSION_POLICY FOREIGN KEY (POLICY_ID)
        REFERENCES KBOT_OPS_POLICY (POLICY_ID),
    CONSTRAINT UK_OPS_AGENT_VERSION UNIQUE (AGENT_ID, VERSION_NO)
);

CREATE INDEX IX_OPS_AGENT_VERSION_AGENT ON KBOT_OPS_AGENT_VERSION (AGENT_ID);
CREATE INDEX IX_OPS_AGENT_VERSION_POLICY
    ON KBOT_OPS_AGENT_VERSION (POLICY_ID);

ALTER TABLE KBOT_OPS_AGENT ADD CONSTRAINT FK_OPS_AGENT_CURRENT_VERSION
    FOREIGN KEY (CURRENT_VERSION_ID) REFERENCES KBOT_OPS_AGENT_VERSION (AGENT_VERSION_ID);
CREATE INDEX IX_OPS_AGENT_CURRENT_VERSION
    ON KBOT_OPS_AGENT (CURRENT_VERSION_ID);

ALTER TABLE KBOT_OPS_TARGET_BINDING
    ADD CONSTRAINT FK_OPS_BINDING_AGENT
    FOREIGN KEY (AGENT_ID) REFERENCES KBOT_OPS_AGENT (AGENT_ID);

CREATE TABLE KBOT_OPS_AGENT_GRANT (
    AGENT_GRANT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    SUBJECT_TYPE VARCHAR2(16 CHAR) NOT NULL,
    SUBJECT_ID VARCHAR2(256 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_AGENT_GRANT_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_AGENT_GRANT_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES KBOT_OPS_AGENT (AGENT_ID) ON DELETE CASCADE,
    CONSTRAINT UK_OPS_AGENT_GRANT_SUBJECT
        UNIQUE (AGENT_ID, SUBJECT_TYPE, SUBJECT_ID),
    CONSTRAINT CK_OPS_AGENT_GRANT_SUBJECT CHECK (SUBJECT_TYPE IN ('USER', 'ROLE')),
    CONSTRAINT CK_OPS_AGENT_GRANT_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_OPS_AGENT_GRANT_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_AGENT_GRANT_SCOPE ON KBOT_OPS_AGENT_GRANT
    (DOMAIN_ID, SUBJECT_TYPE, SUBJECT_ID, STATUS);
-- AIOps 对话、人工证据、逐条动作和报告模板。

CREATE TABLE KBOT_OPS_REPORT_TEMPLATE (
    TEMPLATE_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CURRENT_VERSION_ID RAW(16) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_RPT_TPL_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_OPS_REPORT_TEMPLATE_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT CK_OPS_RPT_TPL_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_OPS_RPT_TPL_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_REPORT_TEMPLATE_SCOPE
    ON KBOT_OPS_REPORT_TEMPLATE (DOMAIN_ID, STATUS);

CREATE TABLE KBOT_OPS_REPORT_TEMPLATE_VER (
    TEMPLATE_VERSION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    TEMPLATE_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    DEFINITION_JSON JSON NOT NULL,
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_RPT_TPL_VER_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_RPT_TPL_VER_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
        REFERENCES KBOT_OPS_REPORT_TEMPLATE (TEMPLATE_ID) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT UK_OPS_REPORT_TEMPLATE_VER UNIQUE (TEMPLATE_ID, VERSION_NO),
    CONSTRAINT UK_OPS_REPORT_TEMPLATE_HASH UNIQUE (TEMPLATE_ID, CONTENT_HASH),
    CONSTRAINT CK_OPS_RPT_TPL_VER_NO CHECK (VERSION_NO > 0)
);

CREATE INDEX IX_OPS_RPT_TPL_VER_TEMPLATE
    ON KBOT_OPS_REPORT_TEMPLATE_VER (TEMPLATE_ID);
CREATE INDEX IX_OPS_RPT_TPL_VER_DOMAIN
    ON KBOT_OPS_REPORT_TEMPLATE_VER (DOMAIN_ID);

ALTER TABLE KBOT_OPS_REPORT_TEMPLATE
    ADD CONSTRAINT FK_OPS_RPT_TPL_CURRENT_VERSION
    FOREIGN KEY (CURRENT_VERSION_ID)
    REFERENCES KBOT_OPS_REPORT_TEMPLATE_VER (TEMPLATE_VERSION_ID)
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IX_OPS_RPT_TPL_CURRENT_VERSION
    ON KBOT_OPS_REPORT_TEMPLATE (CURRENT_VERSION_ID);

CREATE TABLE KBOT_OPS_CONVERSATION (
    CONVERSATION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    AGENT_VERSION_ID RAW(16) NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    SOURCE_TYPE VARCHAR2(24 CHAR) DEFAULT 'CHAT' NOT NULL,
    SOURCE_SITUATION_ID RAW(16),
    SOURCE_RUN_ID RAW(16),
    SOURCE_REPORT_ID RAW(16),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_CONV_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_CONV_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES KBOT_OPS_AGENT (AGENT_ID),
    CONSTRAINT FK_OPS_CONV_AGENT_VER FOREIGN KEY (AGENT_VERSION_ID)
        REFERENCES KBOT_OPS_AGENT_VERSION (AGENT_VERSION_ID),
    CONSTRAINT FK_OPS_CONV_SOURCE_SITUATION FOREIGN KEY (SOURCE_SITUATION_ID)
        REFERENCES KBOT_OPS_SITUATION (SITUATION_ID),
    CONSTRAINT FK_OPS_CONV_SOURCE_RUN FOREIGN KEY (SOURCE_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_CONV_SOURCE_REPORT FOREIGN KEY (SOURCE_REPORT_ID)
        REFERENCES KBOT_OPS_REPORT (REPORT_ID),
    CONSTRAINT CK_OPS_CONV_STATUS CHECK (STATUS IN ('ACTIVE', 'WAITING_EVIDENCE', 'RESOLVED', 'ARCHIVED')),
    CONSTRAINT CK_OPS_CONV_SOURCE CHECK (SOURCE_TYPE IN ('CHAT', 'SITUATION', 'RUN', 'REPORT')),
    CONSTRAINT CK_OPS_CONV_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_CONVERSATION_SCOPE
    ON KBOT_OPS_CONVERSATION (DOMAIN_ID, STATUS, UPDATED_AT);
CREATE INDEX IX_OPS_CONV_AGENT ON KBOT_OPS_CONVERSATION (AGENT_ID);
CREATE INDEX IX_OPS_CONV_AGENT_VER
    ON KBOT_OPS_CONVERSATION (AGENT_VERSION_ID);
CREATE INDEX IX_OPS_CONV_SOURCE_SITUATION
    ON KBOT_OPS_CONVERSATION (SOURCE_SITUATION_ID);
CREATE INDEX IX_OPS_CONV_SOURCE_RUN
    ON KBOT_OPS_CONVERSATION (SOURCE_RUN_ID);
CREATE INDEX IX_OPS_CONV_SOURCE_REPORT
    ON KBOT_OPS_CONVERSATION (SOURCE_REPORT_ID);

CREATE TABLE KBOT_OPS_CONVERSATION_MESSAGE (
    MESSAGE_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    SEQUENCE_NO NUMBER(19) NOT NULL,
    ROLE VARCHAR2(16 CHAR) NOT NULL,
    MESSAGE_TYPE VARCHAR2(48 CHAR) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    ARTIFACT_ID RAW(16),
    CREATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_CONV_MSG_CONV FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_OPS_CONVERSATION (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_CONV_MSG_ARTIFACT FOREIGN KEY (ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_CONV_MSG_SEQ UNIQUE (CONVERSATION_ID, SEQUENCE_NO),
    CONSTRAINT CK_OPS_CONV_MSG_ROLE CHECK (ROLE IN ('USER', 'AGENT', 'SYSTEM')),
    CONSTRAINT CK_OPS_CONV_MSG_SEQ CHECK (SEQUENCE_NO > 0)
);

CREATE INDEX IX_OPS_CONV_MSG_CONV
    ON KBOT_OPS_CONVERSATION_MESSAGE (CONVERSATION_ID, CREATED_AT);
CREATE INDEX IX_OPS_CONV_MSG_ARTIFACT
    ON KBOT_OPS_CONVERSATION_MESSAGE (ARTIFACT_ID);

CREATE TABLE KBOT_OPS_CONVERSATION_RUN (
    CONVERSATION_RUN_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    OPS_RUN_ID RAW(16) NOT NULL,
    PURPOSE VARCHAR2(48 CHAR) NOT NULL,
    SEQUENCE_NO NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_CONV_RUN_CONV FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_OPS_CONVERSATION (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_CONV_RUN_RUNTIME FOREIGN KEY (OPS_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT UK_OPS_CONV_RUN UNIQUE (OPS_RUN_ID),
    CONSTRAINT UK_OPS_CONV_RUN_SEQ UNIQUE (CONVERSATION_ID, SEQUENCE_NO),
    CONSTRAINT CK_OPS_CONV_RUN_SEQ CHECK (SEQUENCE_NO > 0)
);

CREATE INDEX IX_OPS_CONV_RUN_CONV
    ON KBOT_OPS_CONVERSATION_RUN (CONVERSATION_ID, CREATED_AT);

CREATE TABLE KBOT_OPS_EVIDENCE_REQUEST (
    REQUEST_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    PARENT_REQUEST_ID RAW(16),
    STATUS VARCHAR2(24 CHAR) DEFAULT 'OPEN' NOT NULL,
    PURPOSE CLOB NOT NULL,
    SUGGESTED_SQL CLOB,
    SQL_HASH VARCHAR2(64 CHAR),
    FAILURE_CLASS VARCHAR2(48 CHAR),
    REQUESTED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_EVID_REQ_CONV FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_OPS_CONVERSATION (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_EVID_REQ_PARENT FOREIGN KEY (PARENT_REQUEST_ID)
        REFERENCES KBOT_OPS_EVIDENCE_REQUEST (REQUEST_ID),
    CONSTRAINT CK_OPS_EVID_REQ_STATUS
        CHECK (STATUS IN ('OPEN', 'RECEIVED', 'SKIPPED', 'FAILED'))
);

CREATE INDEX IX_OPS_EVID_REQ_CONV
    ON KBOT_OPS_EVIDENCE_REQUEST (CONVERSATION_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_EVID_REQ_PARENT
    ON KBOT_OPS_EVIDENCE_REQUEST (PARENT_REQUEST_ID);

CREATE TABLE KBOT_OPS_ACTION_STEP (
    ACTION_STEP_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    PROPOSAL_ID RAW(16),
    ORDINAL NUMBER(10) NOT NULL,
    SQL_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'DRAFT' NOT NULL,
    SUPERSEDES_STEP_ID RAW(16),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_ACTION_STEP_CONV FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_OPS_CONVERSATION (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_ACTION_STEP_PROP FOREIGN KEY (PROPOSAL_ID)
        REFERENCES KBOT_OPS_CHANGE_PROPOSAL (PROPOSAL_ID),
    CONSTRAINT FK_OPS_ACTION_STEP_SUPERSEDES FOREIGN KEY (SUPERSEDES_STEP_ID)
        REFERENCES KBOT_OPS_ACTION_STEP (ACTION_STEP_ID),
    CONSTRAINT UK_OPS_ACTION_STEP_ORD UNIQUE (CONVERSATION_ID, ORDINAL),
    CONSTRAINT CK_OPS_ACTION_STEP_ORD CHECK (ORDINAL > 0),
    CONSTRAINT CK_OPS_ACTION_STEP_STATUS
        CHECK (STATUS IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'EXECUTED', 'REJECTED', 'FAILED', 'SUPERSEDED')),
    CONSTRAINT CK_OPS_ACTION_STEP_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_OPS_ACTION_STEP_CONV
    ON KBOT_OPS_ACTION_STEP (CONVERSATION_ID, STATUS, ORDINAL);
CREATE INDEX IX_OPS_ACTION_STEP_PROP
    ON KBOT_OPS_ACTION_STEP (PROPOSAL_ID);
CREATE INDEX IX_OPS_ACTION_STEP_SUPERSEDES
    ON KBOT_OPS_ACTION_STEP (SUPERSEDES_STEP_ID);

CREATE TABLE KBOT_OPS_IMAGE_EVIDENCE (
    PROCESSING_ID RAW(16) PRIMARY KEY,
    CONVERSATION_ID RAW(16) NOT NULL,
    EVIDENCE_REQUEST_ID RAW(16) NOT NULL,
    SOURCE_ARTIFACT_ID RAW(16) NOT NULL,
    PROCESSING_MODE VARCHAR2(8 CHAR) NOT NULL,
    MODEL_ID RAW(16) NOT NULL,
    MODEL_REVISION VARCHAR2(128 CHAR) NOT NULL,
    INPUT_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'PENDING' NOT NULL,
    OUTPUT_ARTIFACT_ID RAW(16),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_IMG_EVID_CONV FOREIGN KEY (CONVERSATION_ID)
        REFERENCES KBOT_OPS_CONVERSATION (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_IMG_EVID_REQ FOREIGN KEY (EVIDENCE_REQUEST_ID)
        REFERENCES KBOT_OPS_EVIDENCE_REQUEST (REQUEST_ID),
    CONSTRAINT FK_OPS_IMG_EVID_SOURCE FOREIGN KEY (SOURCE_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_IMG_EVID_OUTPUT FOREIGN KEY (OUTPUT_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT CK_OPS_IMG_EVID_MODE
        CHECK (PROCESSING_MODE IN ('OCR', 'VLM')),
    CONSTRAINT CK_OPS_IMG_EVID_STATUS
        CHECK (STATUS IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED'))
);

CREATE INDEX IX_OPS_IMG_EVID_CONV
    ON KBOT_OPS_IMAGE_EVIDENCE (CONVERSATION_ID, STATUS, CREATED_AT);
CREATE INDEX IX_OPS_IMG_EVID_REQ
    ON KBOT_OPS_IMAGE_EVIDENCE (EVIDENCE_REQUEST_ID);
CREATE INDEX IX_OPS_IMG_EVID_SOURCE
    ON KBOT_OPS_IMAGE_EVIDENCE (SOURCE_ARTIFACT_ID);
CREATE INDEX IX_OPS_IMG_EVID_OUTPUT
    ON KBOT_OPS_IMAGE_EVIDENCE (OUTPUT_ARTIFACT_ID);
PROMPT === 正在验证 AIOps Schema 版本 ===

SELECT component, schema_version, contract_version
FROM KBOT_V_OPS_SCHEMA_VERSION;

SELECT table_name
FROM user_tables
WHERE table_name LIKE 'KBOT\_OPS\_%' ESCAPE '\'
ORDER BY table_name;

PROMPT === AIOps Schema 重建完成 ===
