-- AIOps Schema 13 -> 15 原位升级脚本。
--
-- 保留 Target、Agent、监控源、Webhook 凭据、会话及诊断数据，完成
-- “逻辑 Target + 多 Target Agent + 单 Target 会话”结构升级。
--
-- 执行要求：
-- 1. 仅允许在 KBOT_V_OPS_SCHEMA_VERSION=AIOPS/13/aiops-oracle-v3 时执行一次；
-- 2. 执行前停止 AIOps API、Worker 和 Scheduler，并完成 Schema 备份；
-- 3. 使用 KBot Schema Owner 在 SQL Developer 中以 Run Script（F5）执行；
-- 4. 本脚本不修改监控源、托管凭据、Target Source Binding 的业务数据或密钥。

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT [1/11] 校验当前 Schema 版本与可迁移数据

DECLARE
    v_component        VARCHAR2(32 CHAR);
    v_schema_version   NUMBER;
    v_contract_version VARCHAR2(64 CHAR);
    v_unresolved       NUMBER;
BEGIN
    SELECT COMPONENT, SCHEMA_VERSION, CONTRACT_VERSION
      INTO v_component, v_schema_version, v_contract_version
      FROM KBOT_V_OPS_SCHEMA_VERSION;

    IF v_component <> 'AIOPS'
       OR v_schema_version <> 13
       OR v_contract_version <> 'aiops-oracle-v3' THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            '仅允许从 AIOPS/13/aiops-oracle-v3 升级，当前为 '
            || v_component || '/' || v_schema_version || '/'
            || v_contract_version
        );
    END IF;

    -- 当前 Agent 版本必须能够由旧 TARGET_ID、旧 Agent Binding，或唯一的
    -- Source Binding 推导出至少一个逻辑 Target。
    SELECT COUNT(*)
      INTO v_unresolved
      FROM KBOT_OPS_AGENT a
      JOIN KBOT_OPS_AGENT_VERSION av
        ON av.AGENT_VERSION_ID = a.CURRENT_VERSION_ID
     WHERE av.TARGET_ID IS NULL
       AND NOT EXISTS (
            SELECT 1
              FROM KBOT_OPS_TARGET_BINDING tb
             WHERE tb.AGENT_ID = a.AGENT_ID
               AND tb.STATUS = 'ACTIVE'
       )
       AND 1 <> (
            SELECT COUNT(DISTINCT tsb.TARGET_ID)
              FROM KBOT_OPS_AGENT_VERSION_SOURCE avs
              JOIN KBOT_OPS_TARGET_SOURCE_BINDING tsb
                ON tsb.DIAGNOSTIC_SOURCE_ID = avs.DIAGNOSTIC_SOURCE_ID
               AND tsb.STATUS = 'ACTIVE'
             WHERE avs.AGENT_VERSION_ID = av.AGENT_VERSION_ID
       );

    IF v_unresolved > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            '存在 ' || v_unresolved
            || ' 个当前 Agent 版本无法唯一推导 Target；请先补齐旧 Agent Target 或 Target Source Binding'
        );
    END IF;

    -- 会话必须能够在升级前唯一确定 Target。来源 Run/Situation/Report、Turn
    -- 证据和旧 Agent 版本依次作为事实来源；最后才使用唯一绑定候选。
    WITH resolved_conversation AS (
        SELECT c.CONVERSATION_ID,
               COALESCE(
                   (SELECT r.TARGET_ID
                      FROM KBOT_OPS_RUN r
                     WHERE r.OPS_RUN_ID = c.SOURCE_RUN_ID),
                   (SELECT s.TARGET_ID
                      FROM KBOT_OPS_SITUATION s
                     WHERE s.SITUATION_ID = c.SOURCE_SITUATION_ID),
                   (SELECT rp.TARGET_ID
                      FROM KBOT_OPS_REPORT rp
                     WHERE rp.REPORT_ID = c.SOURCE_REPORT_ID),
                   (SELECT HEXTORAW(MIN(RAWTOHEX(ct.RESOLVED_TARGET_ID)))
                      FROM KBOT_OPS_CONVERSATION_TURN ct
                     WHERE ct.CONVERSATION_ID = c.CONVERSATION_ID
                       AND ct.RESOLVED_TARGET_ID IS NOT NULL
                    HAVING COUNT(DISTINCT ct.RESOLVED_TARGET_ID) = 1),
                   av.TARGET_ID,
                   (SELECT HEXTORAW(MIN(RAWTOHEX(tb.TARGET_ID)))
                      FROM KBOT_OPS_TARGET_BINDING tb
                     WHERE tb.AGENT_ID = c.AGENT_ID
                       AND tb.STATUS = 'ACTIVE'
                    HAVING COUNT(DISTINCT tb.TARGET_ID) = 1),
                   (SELECT HEXTORAW(MIN(RAWTOHEX(tsb.TARGET_ID)))
                      FROM KBOT_OPS_AGENT_VERSION_SOURCE avs
                      JOIN KBOT_OPS_TARGET_SOURCE_BINDING tsb
                        ON tsb.DIAGNOSTIC_SOURCE_ID = avs.DIAGNOSTIC_SOURCE_ID
                       AND tsb.STATUS = 'ACTIVE'
                     WHERE avs.AGENT_VERSION_ID = c.AGENT_VERSION_ID
                    HAVING COUNT(DISTINCT tsb.TARGET_ID) = 1)
               ) AS TARGET_ID
          FROM KBOT_OPS_CONVERSATION c
          JOIN KBOT_OPS_AGENT_VERSION av
            ON av.AGENT_VERSION_ID = c.AGENT_VERSION_ID
    )
    SELECT COUNT(*)
      INTO v_unresolved
      FROM resolved_conversation
     WHERE TARGET_ID IS NULL;

    IF v_unresolved > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20003,
            '存在 ' || v_unresolved
            || ' 条历史会话无法唯一推导 Target；升级未开始，请先人工补齐关联'
        );
    END IF;

    -- 每条旧 Skill Invocation 都必须有一个可复用的冻结计划 Artifact，才能
    -- 在不伪造诊断内容的前提下迁移为 Investigation Revision。
    SELECT COUNT(*)
      INTO v_unresolved
      FROM KBOT_OPS_SKILL_INVOCATION si
      JOIN KBOT_OPS_CONVERSATION_TURN ct
        ON ct.TURN_ID = si.TURN_ID
     WHERE COALESCE(
               ct.SKILL_PLAN_ARTIFACT_ID,
               ct.INTENT_PLAN_ARTIFACT_ID,
               ct.SUFFICIENCY_ARTIFACT_ID,
               si.OUTPUT_ARTIFACT_ID
           ) IS NULL;

    IF v_unresolved > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20004,
            '存在 ' || v_unresolved
            || ' 条旧 Skill Invocation 缺少可迁移的计划 Artifact；升级未开始'
        );
    END IF;

    SELECT COUNT(*)
      INTO v_unresolved
      FROM KBOT_OPS_SKILL_INVOCATION
     WHERE NOT REGEXP_LIKE(MANIFEST_HASH, '^[0-9A-Fa-f]{64}$');

    IF v_unresolved > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20005,
            '存在 ' || v_unresolved
            || ' 条旧 Skill Invocation 的 Manifest Hash 无效；升级未开始'
        );
    END IF;

    DBMS_OUTPUT.PUT_LINE('升级前置校验通过');
END;
/

PROMPT [2/11] 将 Schema 13 Turn 升级为调查循环结构

ALTER TABLE KBOT_OPS_CONVERSATION_TURN ADD (
    INPUT_ANALYSIS_ARTIFACT_ID RAW(16),
    TASK_FRAME_ARTIFACT_ID RAW(16),
    CURRENT_PLAN_ARTIFACT_ID RAW(16),
    ASSESSMENT_ARTIFACT_ID RAW(16),
    CURRENT_PLAN_REVISION NUMBER(10) DEFAULT 0 NOT NULL,
    INVESTIGATION_ROUND NUMBER(10) DEFAULT 0 NOT NULL,
    TOOL_CALL_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    NO_PROGRESS_COUNT NUMBER(10) DEFAULT 0 NOT NULL
);

UPDATE KBOT_OPS_CONVERSATION_TURN ct
   SET INPUT_ANALYSIS_ARTIFACT_ID = ct.INTENT_PLAN_ARTIFACT_ID,
       TASK_FRAME_ARTIFACT_ID = ct.INTENT_PLAN_ARTIFACT_ID,
       CURRENT_PLAN_ARTIFACT_ID = COALESCE(
           ct.SKILL_PLAN_ARTIFACT_ID,
           (SELECT HEXTORAW(MIN(RAWTOHEX(si.OUTPUT_ARTIFACT_ID)))
              FROM KBOT_OPS_SKILL_INVOCATION si
             WHERE si.TURN_ID = ct.TURN_ID)
       ),
       ASSESSMENT_ARTIFACT_ID = ct.SUFFICIENCY_ARTIFACT_ID,
       CURRENT_PLAN_REVISION = CASE
           WHEN COALESCE(
                    ct.SKILL_PLAN_ARTIFACT_ID,
                    ct.INTENT_PLAN_ARTIFACT_ID,
                    ct.SUFFICIENCY_ARTIFACT_ID,
                    (SELECT HEXTORAW(MIN(RAWTOHEX(si.OUTPUT_ARTIFACT_ID)))
                       FROM KBOT_OPS_SKILL_INVOCATION si
                      WHERE si.TURN_ID = ct.TURN_ID)
                ) IS NOT NULL THEN 1
           ELSE 0
       END,
       INVESTIGATION_ROUND = CASE
           WHEN EXISTS (
                SELECT 1
                  FROM KBOT_OPS_SKILL_INVOCATION si
                 WHERE si.TURN_ID = ct.TURN_ID
           ) THEN 1
           ELSE 0
       END,
       TOOL_CALL_COUNT = (
           SELECT COUNT(*)
             FROM KBOT_OPS_SKILL_INVOCATION si
            WHERE si.TURN_ID = ct.TURN_ID
       ),
       NO_PROGRESS_COUNT = 0;

ALTER TABLE KBOT_OPS_CONVERSATION_TURN
    ADD CONSTRAINT FK_OPS_TURN_INPUT_ART
    FOREIGN KEY (INPUT_ANALYSIS_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID);
ALTER TABLE KBOT_OPS_CONVERSATION_TURN
    ADD CONSTRAINT FK_OPS_TURN_FRAME_ART
    FOREIGN KEY (TASK_FRAME_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID);
ALTER TABLE KBOT_OPS_CONVERSATION_TURN
    ADD CONSTRAINT FK_OPS_TURN_PLAN_ART
    FOREIGN KEY (CURRENT_PLAN_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID);
ALTER TABLE KBOT_OPS_CONVERSATION_TURN
    ADD CONSTRAINT FK_OPS_TURN_ASSESS_ART
    FOREIGN KEY (ASSESSMENT_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID);

ALTER TABLE KBOT_OPS_CONVERSATION_TURN
    DROP CONSTRAINT CK_OPS_TURN_STATUS;
ALTER TABLE KBOT_OPS_CONVERSATION_TURN
    ADD CONSTRAINT CK_OPS_TURN_STATUS CHECK (STATUS IN (
        'QUEUED', 'ACCEPTED', 'UNDERSTANDING', 'PLANNING', 'COLLECTING',
        'ASSESSING', 'REPLANNING', 'ANSWERING', 'WAITING_USER',
        'PROPOSAL_PENDING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED'
    ));
ALTER TABLE KBOT_OPS_CONVERSATION_TURN
    DROP CONSTRAINT CK_OPS_TURN_NUMBERS;
ALTER TABLE KBOT_OPS_CONVERSATION_TURN
    ADD CONSTRAINT CK_OPS_TURN_NUMBERS CHECK (
        TURN_NO > 0 AND EVENT_CURSOR >= 0 AND ROW_VERSION > 0
        AND CURRENT_PLAN_REVISION >= 0 AND INVESTIGATION_ROUND >= 0
        AND TOOL_CALL_COUNT >= 0 AND NO_PROGRESS_COUNT >= 0
    );

DROP INDEX UX_OPS_TURN_ACTIVE;
CREATE UNIQUE INDEX UX_OPS_TURN_ACTIVE
    ON KBOT_OPS_CONVERSATION_TURN (
        CASE WHEN STATUS IN (
            'UNDERSTANDING', 'PLANNING', 'COLLECTING', 'ASSESSING',
            'REPLANNING', 'ANSWERING'
        ) THEN CONVERSATION_ID END
    );

CREATE INDEX IX_OPS_TURN_INPUT_ART
    ON KBOT_OPS_CONVERSATION_TURN (INPUT_ANALYSIS_ARTIFACT_ID);
CREATE INDEX IX_OPS_TURN_FRAME_ART
    ON KBOT_OPS_CONVERSATION_TURN (TASK_FRAME_ARTIFACT_ID);
CREATE INDEX IX_OPS_TURN_PLAN_ART
    ON KBOT_OPS_CONVERSATION_TURN (CURRENT_PLAN_ARTIFACT_ID);
CREATE INDEX IX_OPS_TURN_ASSESS_ART
    ON KBOT_OPS_CONVERSATION_TURN (ASSESSMENT_ARTIFACT_ID);

CREATE TABLE KBOT_OPS_TURN_INPUT_ITEM (
    INPUT_ITEM_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    MESSAGE_ID RAW(16) NOT NULL,
    ITEM_NO NUMBER(10) NOT NULL,
    CONTENT_TYPE VARCHAR2(24 CHAR) NOT NULL,
    MEDIA_TYPE VARCHAR2(128 CHAR),
    CONTENT_TEXT CLOB,
    SOURCE_ARTIFACT_ID RAW(16),
    EXTRACTED_ARTIFACT_ID RAW(16),
    DETECTED_KIND VARCHAR2(32 CHAR),
    DETECTION_CONFIDENCE NUMBER(5,4),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_INPUT_ITEM_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_INPUT_ITEM_MSG FOREIGN KEY (MESSAGE_ID, TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_MESSAGE (MESSAGE_ID, TURN_ID),
    CONSTRAINT FK_OPS_INPUT_ITEM_SOURCE FOREIGN KEY (SOURCE_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_INPUT_ITEM_EXTRACT FOREIGN KEY (EXTRACTED_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_INPUT_ITEM_NO UNIQUE (TURN_ID, ITEM_NO),
    CONSTRAINT CK_OPS_INPUT_ITEM_TYPE CHECK (CONTENT_TYPE IN (
        'TEXT', 'IMAGE', 'FILE', 'SQL_OUTPUT', 'COMMAND_OUTPUT', 'LOG'
    )),
    CONSTRAINT CK_OPS_INPUT_ITEM_VALUE CHECK (
        CONTENT_TEXT IS NOT NULL OR SOURCE_ARTIFACT_ID IS NOT NULL
    ),
    CONSTRAINT CK_OPS_INPUT_ITEM_NUM CHECK (
        ITEM_NO > 0 AND (
            DETECTION_CONFIDENCE IS NULL
            OR (DETECTION_CONFIDENCE >= 0 AND DETECTION_CONFIDENCE <= 1)
        )
    )
);

CREATE INDEX IX_OPS_INPUT_ITEM_MSG
    ON KBOT_OPS_TURN_INPUT_ITEM (MESSAGE_ID, TURN_ID);
CREATE INDEX IX_OPS_INPUT_ITEM_SOURCE
    ON KBOT_OPS_TURN_INPUT_ITEM (SOURCE_ARTIFACT_ID);
CREATE INDEX IX_OPS_INPUT_ITEM_EXTRACT
    ON KBOT_OPS_TURN_INPUT_ITEM (EXTRACTED_ARTIFACT_ID);

PROMPT [3/11] 迁移旧 Skill、Evidence 和 Event 审计数据

CREATE TABLE KBOT_OPS_INVESTIGATION_REVISION (
    REVISION_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    REVISION_NO NUMBER(10) NOT NULL,
    REVISION_TYPE VARCHAR2(24 CHAR) NOT NULL,
    TRIGGER_REASON VARCHAR2(1000 CHAR) NOT NULL,
    TASK_FRAME_ARTIFACT_ID RAW(16),
    PLAN_ARTIFACT_ID RAW(16) NOT NULL,
    ASSESSMENT_ARTIFACT_ID RAW(16),
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_INV_REV_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_INV_REV_FRAME FOREIGN KEY (TASK_FRAME_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_INV_REV_PLAN FOREIGN KEY (PLAN_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT FK_OPS_INV_REV_ASSESS FOREIGN KEY (ASSESSMENT_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_INV_REV_NO UNIQUE (TURN_ID, REVISION_NO),
    CONSTRAINT CK_OPS_INV_REV_TYPE CHECK (REVISION_TYPE IN (
        'INITIAL', 'EVIDENCE_DRIVEN', 'USER_CLARIFICATION', 'RECOVERY'
    )),
    CONSTRAINT CK_OPS_INV_REV_NO CHECK (REVISION_NO > 0)
);

CREATE INDEX IX_OPS_INV_REV_FRAME
    ON KBOT_OPS_INVESTIGATION_REVISION (TASK_FRAME_ARTIFACT_ID);
CREATE INDEX IX_OPS_INV_REV_PLAN
    ON KBOT_OPS_INVESTIGATION_REVISION (PLAN_ARTIFACT_ID);
CREATE INDEX IX_OPS_INV_REV_ASSESS
    ON KBOT_OPS_INVESTIGATION_REVISION (ASSESSMENT_ARTIFACT_ID);

INSERT INTO KBOT_OPS_INVESTIGATION_REVISION (
    REVISION_ID, TURN_ID, REVISION_NO, REVISION_TYPE, TRIGGER_REASON,
    TASK_FRAME_ARTIFACT_ID, PLAN_ARTIFACT_ID, ASSESSMENT_ARTIFACT_ID,
    CREATED_BY, CREATED_AT
)
SELECT ct.TURN_ID,
       ct.TURN_ID,
       1,
       'INITIAL',
       'Schema 13 历史诊断计划迁移',
       ct.TASK_FRAME_ARTIFACT_ID,
       COALESCE(
           ct.CURRENT_PLAN_ARTIFACT_ID,
           ct.TASK_FRAME_ARTIFACT_ID,
           ct.ASSESSMENT_ARTIFACT_ID,
           (SELECT HEXTORAW(MIN(RAWTOHEX(si.OUTPUT_ARTIFACT_ID)))
              FROM KBOT_OPS_SKILL_INVOCATION si
             WHERE si.TURN_ID = ct.TURN_ID)
       ),
       ct.ASSESSMENT_ARTIFACT_ID,
       ct.CREATED_BY,
       ct.CREATED_AT
  FROM KBOT_OPS_CONVERSATION_TURN ct
 WHERE COALESCE(
           ct.CURRENT_PLAN_ARTIFACT_ID,
           ct.TASK_FRAME_ARTIFACT_ID,
           ct.ASSESSMENT_ARTIFACT_ID,
           (SELECT HEXTORAW(MIN(RAWTOHEX(si.OUTPUT_ARTIFACT_ID)))
              FROM KBOT_OPS_SKILL_INVOCATION si
             WHERE si.TURN_ID = ct.TURN_ID)
       ) IS NOT NULL;

CREATE TABLE KBOT_OPS_PLAYBOOK_INVOCATION (
    PLAYBOOK_INVOCATION_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    REVISION_ID RAW(16) NOT NULL,
    PARENT_INVOCATION_ID RAW(16),
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16),
    ORDINAL NUMBER(10) NOT NULL,
    PLAYBOOK_ID VARCHAR2(128 CHAR) NOT NULL,
    PLAYBOOK_VERSION VARCHAR2(64 CHAR) NOT NULL,
    MANIFEST_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    INPUT_SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL,
    INPUT_JSON JSON NOT NULL,
    OUTPUT_ARTIFACT_ID RAW(16),
    ATTEMPT_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    ERROR_DOMAIN VARCHAR2(32 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_OPS_PLAY_INV_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_PLAY_INV_REV FOREIGN KEY (REVISION_ID)
        REFERENCES KBOT_OPS_INVESTIGATION_REVISION (REVISION_ID),
    CONSTRAINT FK_OPS_PLAY_INV_PARENT FOREIGN KEY (PARENT_INVOCATION_ID)
        REFERENCES KBOT_OPS_PLAYBOOK_INVOCATION (PLAYBOOK_INVOCATION_ID),
    CONSTRAINT FK_OPS_PLAY_INV_RUN FOREIGN KEY (OPS_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_PLAY_INV_TASK FOREIGN KEY (OPS_TASK_ID)
        REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_PLAY_INV_OUTPUT FOREIGN KEY (OUTPUT_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_PLAY_INV_ORD UNIQUE (REVISION_ID, ORDINAL),
    CONSTRAINT CK_OPS_PLAY_INV_STATUS CHECK (STATUS IN (
        'PLANNED', 'READY', 'RUNNING', 'SUCCEEDED', 'PARTIAL',
        'FAILED', 'SKIPPED', 'CANCELLED'
    )),
    CONSTRAINT CK_OPS_PLAY_INV_NUMBERS CHECK (
        ORDINAL > 0 AND ATTEMPT_COUNT >= 0 AND ROW_VERSION > 0
    ),
    CONSTRAINT CK_OPS_PLAY_INV_HASH CHECK (LENGTH(MANIFEST_HASH) = 64)
);

CREATE INDEX IX_OPS_PLAY_INV_TURN
    ON KBOT_OPS_PLAYBOOK_INVOCATION (TURN_ID, STATUS, ORDINAL);
CREATE INDEX IX_OPS_PLAY_INV_CATALOG
    ON KBOT_OPS_PLAYBOOK_INVOCATION (PLAYBOOK_ID, PLAYBOOK_VERSION, CREATED_AT);
CREATE INDEX IX_OPS_PLAY_INV_TASK
    ON KBOT_OPS_PLAYBOOK_INVOCATION (OPS_TASK_ID);
CREATE INDEX IX_OPS_PLAY_INV_PARENT
    ON KBOT_OPS_PLAYBOOK_INVOCATION (PARENT_INVOCATION_ID);
CREATE INDEX IX_OPS_PLAY_INV_OUTPUT
    ON KBOT_OPS_PLAYBOOK_INVOCATION (OUTPUT_ARTIFACT_ID);

INSERT INTO KBOT_OPS_PLAYBOOK_INVOCATION (
    PLAYBOOK_INVOCATION_ID, TURN_ID, REVISION_ID, PARENT_INVOCATION_ID,
    OPS_RUN_ID, OPS_TASK_ID, ORDINAL, PLAYBOOK_ID, PLAYBOOK_VERSION,
    MANIFEST_HASH, STATUS, INPUT_SCHEMA_VERSION, INPUT_JSON,
    OUTPUT_ARTIFACT_ID, ATTEMPT_COUNT, ERROR_DOMAIN, ERROR_CODE,
    ERROR_MESSAGE, STARTED_AT, COMPLETED_AT, CREATED_AT, UPDATED_AT,
    ROW_VERSION
)
SELECT si.SKILL_INVOCATION_ID,
       si.TURN_ID,
       si.TURN_ID,
       si.PARENT_INVOCATION_ID,
       si.OPS_RUN_ID,
       si.OPS_TASK_ID,
       si.ORDINAL,
       si.SKILL_ID,
       si.SKILL_VERSION,
       si.MANIFEST_HASH,
       si.STATUS,
       si.INPUT_SCHEMA_VERSION,
       si.INPUT_JSON,
       si.OUTPUT_ARTIFACT_ID,
       si.ATTEMPT_COUNT,
       si.ERROR_DOMAIN,
       si.ERROR_CODE,
       si.ERROR_MESSAGE,
       si.STARTED_AT,
       si.COMPLETED_AT,
       si.CREATED_AT,
       si.UPDATED_AT,
       si.ROW_VERSION
  FROM KBOT_OPS_SKILL_INVOCATION si;

CREATE TABLE KBOT_OPS_TOOL_INVOCATION (
    TOOL_INVOCATION_ID RAW(16) PRIMARY KEY,
    TURN_ID RAW(16) NOT NULL,
    REVISION_ID RAW(16) NOT NULL,
    PLAYBOOK_INVOCATION_ID RAW(16),
    OPS_RUN_ID RAW(16) NOT NULL,
    OPS_TASK_ID RAW(16),
    ORDINAL NUMBER(10) NOT NULL,
    ACTION_ID VARCHAR2(32 CHAR) NOT NULL,
    TOOL_ID VARCHAR2(128 CHAR) NOT NULL,
    TOOL_VERSION VARCHAR2(64 CHAR) NOT NULL,
    TOOL_CLASS VARCHAR2(32 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    INPUT_JSON JSON NOT NULL,
    POLICY_HASH VARCHAR2(64 CHAR) NOT NULL,
    OUTPUT_ARTIFACT_ID RAW(16),
    ATTEMPT_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    ERROR_DOMAIN VARCHAR2(32 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_OPS_TOOL_INV_TURN FOREIGN KEY (TURN_ID)
        REFERENCES KBOT_OPS_CONVERSATION_TURN (TURN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_TOOL_INV_REV FOREIGN KEY (REVISION_ID)
        REFERENCES KBOT_OPS_INVESTIGATION_REVISION (REVISION_ID),
    CONSTRAINT FK_OPS_TOOL_INV_PLAY FOREIGN KEY (PLAYBOOK_INVOCATION_ID)
        REFERENCES KBOT_OPS_PLAYBOOK_INVOCATION (PLAYBOOK_INVOCATION_ID),
    CONSTRAINT FK_OPS_TOOL_INV_RUN FOREIGN KEY (OPS_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_TOOL_INV_TASK FOREIGN KEY (OPS_TASK_ID)
        REFERENCES KBOT_OPS_TASK (OPS_TASK_ID),
    CONSTRAINT FK_OPS_TOOL_INV_OUTPUT FOREIGN KEY (OUTPUT_ARTIFACT_ID)
        REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID),
    CONSTRAINT UK_OPS_TOOL_INV_ORD UNIQUE (REVISION_ID, ORDINAL),
    CONSTRAINT UK_OPS_TOOL_INV_ACTION UNIQUE (REVISION_ID, ACTION_ID),
    CONSTRAINT CK_OPS_TOOL_INV_CLASS CHECK (TOOL_CLASS IN (
        'PROMETHEUS', 'LOKI', 'ORACLE_SQL', 'HOST', 'MEDIA', 'REASONING'
    )),
    CONSTRAINT CK_OPS_TOOL_INV_STATUS CHECK (STATUS IN (
        'PLANNED', 'READY', 'RUNNING', 'SUCCEEDED', 'NO_DATA',
        'FAILED', 'SKIPPED', 'CANCELLED'
    )),
    CONSTRAINT CK_OPS_TOOL_INV_NUMBERS CHECK (
        ORDINAL > 0 AND ATTEMPT_COUNT >= 0 AND ROW_VERSION > 0
    ),
    CONSTRAINT CK_OPS_TOOL_INV_POLICY_HASH CHECK (
        REGEXP_LIKE(POLICY_HASH, '^[0-9a-f]{64}$')
    )
);

CREATE INDEX IX_OPS_TOOL_INV_TURN
    ON KBOT_OPS_TOOL_INVOCATION (TURN_ID, STATUS, ORDINAL);
CREATE INDEX IX_OPS_TOOL_INV_REV
    ON KBOT_OPS_TOOL_INVOCATION (REVISION_ID, STATUS);
CREATE INDEX IX_OPS_TOOL_INV_PLAY
    ON KBOT_OPS_TOOL_INVOCATION (PLAYBOOK_INVOCATION_ID);
CREATE INDEX IX_OPS_TOOL_INV_TASK
    ON KBOT_OPS_TOOL_INVOCATION (OPS_TASK_ID);
CREATE INDEX IX_OPS_TOOL_INV_OUTPUT
    ON KBOT_OPS_TOOL_INVOCATION (OUTPUT_ARTIFACT_ID);

INSERT INTO KBOT_OPS_TOOL_INVOCATION (
    TOOL_INVOCATION_ID, TURN_ID, REVISION_ID, PLAYBOOK_INVOCATION_ID,
    OPS_RUN_ID, OPS_TASK_ID, ORDINAL, ACTION_ID, TOOL_ID, TOOL_VERSION,
    TOOL_CLASS, STATUS, INPUT_JSON, POLICY_HASH, OUTPUT_ARTIFACT_ID,
    ATTEMPT_COUNT, ERROR_DOMAIN, ERROR_CODE, ERROR_MESSAGE, STARTED_AT,
    COMPLETED_AT, CREATED_AT, UPDATED_AT, ROW_VERSION
)
SELECT si.SKILL_INVOCATION_ID,
       si.TURN_ID,
       si.TURN_ID,
       si.SKILL_INVOCATION_ID,
       si.OPS_RUN_ID,
       si.OPS_TASK_ID,
       si.ORDINAL,
       'legacy.' || TO_CHAR(si.ORDINAL),
       si.SKILL_ID,
       si.SKILL_VERSION,
       CASE
           WHEN LOWER(si.SKILL_ID) LIKE '%prometheus%' THEN 'PROMETHEUS'
           WHEN LOWER(si.SKILL_ID) LIKE '%loki%' THEN 'LOKI'
           WHEN LOWER(si.SKILL_ID) LIKE '%oracle%'
             OR LOWER(si.SKILL_ID) LIKE '%sql%' THEN 'ORACLE_SQL'
           WHEN LOWER(si.SKILL_ID) LIKE '%host%'
             OR LOWER(si.SKILL_ID) LIKE '%node%' THEN 'HOST'
           ELSE 'REASONING'
       END,
       CASE WHEN si.STATUS = 'PARTIAL' THEN 'SUCCEEDED' ELSE si.STATUS END,
       si.INPUT_JSON,
       LOWER(si.MANIFEST_HASH),
       si.OUTPUT_ARTIFACT_ID,
       si.ATTEMPT_COUNT,
       si.ERROR_DOMAIN,
       si.ERROR_CODE,
       si.ERROR_MESSAGE,
       si.STARTED_AT,
       si.COMPLETED_AT,
       si.CREATED_AT,
       si.UPDATED_AT,
       si.ROW_VERSION
  FROM KBOT_OPS_SKILL_INVOCATION si;

ALTER TABLE KBOT_OPS_TURN_EVIDENCE ADD (
    TOOL_INVOCATION_ID RAW(16),
    SOURCE_KIND VARCHAR2(32 CHAR),
    EVIDENCE_KIND VARCHAR2(32 CHAR),
    CONFIDENCE NUMBER(5,4),
    EXTRACTION_ARTIFACT_ID RAW(16)
);

UPDATE KBOT_OPS_TURN_EVIDENCE
   SET TOOL_INVOCATION_ID = SKILL_INVOCATION_ID,
       SOURCE_KIND = CASE
           WHEN EVIDENCE_ROLE = 'USER_PROVIDED' THEN 'USER'
           ELSE 'LEGACY_SKILL'
       END,
       EVIDENCE_KIND = CASE
           WHEN EVIDENCE_ROLE = 'USER_PROVIDED' THEN 'USER_PROVIDED'
           ELSE 'OBSERVATION'
       END;

ALTER TABLE KBOT_OPS_TURN_EVIDENCE MODIFY (
    SOURCE_KIND NOT NULL,
    EVIDENCE_KIND NOT NULL
);
ALTER TABLE KBOT_OPS_TURN_EVIDENCE
    ADD CONSTRAINT FK_OPS_TURN_EVID_TOOL
    FOREIGN KEY (TOOL_INVOCATION_ID)
    REFERENCES KBOT_OPS_TOOL_INVOCATION (TOOL_INVOCATION_ID);
ALTER TABLE KBOT_OPS_TURN_EVIDENCE
    ADD CONSTRAINT FK_OPS_TURN_EVID_EXTRACT
    FOREIGN KEY (EXTRACTION_ARTIFACT_ID)
    REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID);
ALTER TABLE KBOT_OPS_TURN_EVIDENCE
    ADD CONSTRAINT CK_OPS_TURN_EVID_CONF CHECK (
        CONFIDENCE IS NULL OR (CONFIDENCE >= 0 AND CONFIDENCE <= 1)
    );
CREATE INDEX IX_OPS_TURN_EVID_TOOL
    ON KBOT_OPS_TURN_EVIDENCE (TOOL_INVOCATION_ID);
CREATE INDEX IX_OPS_TURN_EVID_EXTRACT
    ON KBOT_OPS_TURN_EVIDENCE (EXTRACTION_ARTIFACT_ID);

ALTER TABLE KBOT_OPS_TURN_EVENT ADD (
    PLAYBOOK_INVOCATION_ID RAW(16),
    TOOL_INVOCATION_ID RAW(16)
);
UPDATE KBOT_OPS_TURN_EVENT
   SET PLAYBOOK_INVOCATION_ID = SKILL_INVOCATION_ID,
       TOOL_INVOCATION_ID = SKILL_INVOCATION_ID;
ALTER TABLE KBOT_OPS_TURN_EVENT
    ADD CONSTRAINT FK_OPS_TURN_EVENT_PLAY
    FOREIGN KEY (PLAYBOOK_INVOCATION_ID)
    REFERENCES KBOT_OPS_PLAYBOOK_INVOCATION (PLAYBOOK_INVOCATION_ID);
ALTER TABLE KBOT_OPS_TURN_EVENT
    ADD CONSTRAINT FK_OPS_TURN_EVENT_TOOL
    FOREIGN KEY (TOOL_INVOCATION_ID)
    REFERENCES KBOT_OPS_TOOL_INVOCATION (TOOL_INVOCATION_ID);
CREATE INDEX IX_OPS_TURN_EVENT_PLAY
    ON KBOT_OPS_TURN_EVENT (PLAYBOOK_INVOCATION_ID);
CREATE INDEX IX_OPS_TURN_EVENT_TOOL
    ON KBOT_OPS_TURN_EVENT (TOOL_INVOCATION_ID);

-- 新结构已完整承接旧审计数据，移除不再被应用读取的 Schema 13 字段和表。
DECLARE
    v_skill_count    NUMBER;
    v_playbook_count NUMBER;
    v_tool_count     NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_skill_count FROM KBOT_OPS_SKILL_INVOCATION;
    SELECT COUNT(*) INTO v_playbook_count FROM KBOT_OPS_PLAYBOOK_INVOCATION;
    SELECT COUNT(*) INTO v_tool_count FROM KBOT_OPS_TOOL_INVOCATION;
    IF v_skill_count <> v_playbook_count OR v_skill_count <> v_tool_count THEN
        RAISE_APPLICATION_ERROR(
            -20006,
            '旧 Skill 审计数据未被完整迁移：skill=' || v_skill_count
            || ', playbook=' || v_playbook_count || ', tool=' || v_tool_count
        );
    END IF;
END;
/

ALTER TABLE KBOT_OPS_TURN_EVIDENCE
    DROP CONSTRAINT FK_OPS_TURN_EVID_SKILL;
DROP INDEX IX_OPS_TURN_EVID_SKILL;
ALTER TABLE KBOT_OPS_TURN_EVIDENCE DROP COLUMN SKILL_INVOCATION_ID;

ALTER TABLE KBOT_OPS_TURN_EVENT
    DROP CONSTRAINT FK_OPS_TURN_EVENT_SKILL;
DROP INDEX IX_OPS_TURN_EVENT_SKILL;
ALTER TABLE KBOT_OPS_TURN_EVENT DROP COLUMN SKILL_INVOCATION_ID;

ALTER TABLE KBOT_OPS_CONVERSATION_TURN
    DROP CONSTRAINT FK_OPS_TURN_INTENT_ART;
ALTER TABLE KBOT_OPS_CONVERSATION_TURN
    DROP CONSTRAINT FK_OPS_TURN_SKILL_ART;
ALTER TABLE KBOT_OPS_CONVERSATION_TURN
    DROP CONSTRAINT CK_OPS_TURN_INTENT;
DROP INDEX IX_OPS_TURN_INTENT_ART;
DROP INDEX IX_OPS_TURN_SKILL_ART;
ALTER TABLE KBOT_OPS_CONVERSATION_TURN DROP (
    PRIMARY_INTENT,
    PRIMARY_DOMAIN,
    SUBJECT,
    INTENT_SCHEMA_VERSION,
    INTENT_PLAN_JSON,
    INTENT_PLAN_ARTIFACT_ID,
    SKILL_PLAN_SCHEMA_VERSION,
    SKILL_PLAN_JSON,
    SKILL_PLAN_ARTIFACT_ID
);

DROP TABLE KBOT_OPS_SKILL_INVOCATION;

PROMPT [4/11] 增加 Target 连接与受控变更开关

ALTER TABLE KBOT_OPS_TARGET ADD (
    READONLY_CONNECTION_ENABLED NUMBER(1) DEFAULT 0 NOT NULL,
    CONTROLLED_CHANGE_ENABLED NUMBER(1) DEFAULT 0 NOT NULL
);

UPDATE KBOT_OPS_TARGET t
   SET READONLY_CONNECTION_ENABLED = CASE
           WHEN t.ENDPOINT_JSON IS NOT NULL
            AND t.DIAGNOSTIC_CREDENTIAL_ID IS NOT NULL THEN 1
           ELSE 0
       END,
       CONTROLLED_CHANGE_ENABLED = CASE
           WHEN t.ENDPOINT_JSON IS NOT NULL
            AND t.DIAGNOSTIC_CREDENTIAL_ID IS NOT NULL
            AND t.EXECUTION_CREDENTIAL_ID IS NOT NULL
            AND (
                EXISTS (
                    SELECT 1
                      FROM KBOT_OPS_AGENT_VERSION av
                      JOIN KBOT_OPS_POLICY p
                        ON p.POLICY_ID = av.POLICY_ID
                     WHERE av.TARGET_ID = t.TARGET_ID
                       AND JSON_VALUE(
                               p.RULES_JSON,
                               '$.allow_agent_execution'
                           ) = 'true'
                )
                OR EXISTS (
                    SELECT 1
                      FROM KBOT_OPS_TARGET_BINDING tb
                     WHERE tb.TARGET_ID = t.TARGET_ID
                       AND tb.ALLOW_MUTATION = 1
                       AND tb.STATUS = 'ACTIVE'
                )
            ) THEN 1
           ELSE 0
       END;

ALTER TABLE KBOT_OPS_TARGET ADD CONSTRAINT CK_OPS_TARGET_ACCESS CHECK (
    READONLY_CONNECTION_ENABLED IN (0, 1)
    AND CONTROLLED_CHANGE_ENABLED IN (0, 1)
    AND (CONTROLLED_CHANGE_ENABLED = 0 OR READONLY_CONNECTION_ENABLED = 1)
);

PROMPT [5/11] 创建 Agent 版本与逻辑 Target 多对多关系

CREATE TABLE KBOT_OPS_AGENT_VERSION_TARGET (
    AGENT_VERSION_ID RAW(16) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_OPS_AGENT_VERSION_TARGET
        PRIMARY KEY (AGENT_VERSION_ID, TARGET_ID),
    CONSTRAINT FK_OPS_AGENT_VER_TARGET_VER FOREIGN KEY (AGENT_VERSION_ID)
        REFERENCES KBOT_OPS_AGENT_VERSION (AGENT_VERSION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_AGENT_VER_TARGET_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID)
);

CREATE INDEX IX_OPS_AGENT_VER_TARGET_TARGET
    ON KBOT_OPS_AGENT_VERSION_TARGET (TARGET_ID);

PROMPT [6/11] 回填 Agent 版本 Target 集合

-- 首选旧版本直接绑定的 Target，保持原有行为不变。
INSERT INTO KBOT_OPS_AGENT_VERSION_TARGET (
    AGENT_VERSION_ID, TARGET_ID, CREATED_AT
)
SELECT AGENT_VERSION_ID, TARGET_ID, CURRENT_TIMESTAMP
  FROM KBOT_OPS_AGENT_VERSION
 WHERE TARGET_ID IS NOT NULL;

-- 兼容早期由 KBOT_OPS_TARGET_BINDING 表达的明确 Agent-Target 关系。
INSERT INTO KBOT_OPS_AGENT_VERSION_TARGET (
    AGENT_VERSION_ID, TARGET_ID, CREATED_AT
)
SELECT av.AGENT_VERSION_ID, tb.TARGET_ID, CURRENT_TIMESTAMP
  FROM KBOT_OPS_AGENT_VERSION av
  JOIN KBOT_OPS_TARGET_BINDING tb
    ON tb.AGENT_ID = av.AGENT_ID
   AND tb.STATUS = 'ACTIVE'
 WHERE NOT EXISTS (
       SELECT 1
         FROM KBOT_OPS_AGENT_VERSION_TARGET avt
        WHERE avt.AGENT_VERSION_ID = av.AGENT_VERSION_ID
          AND avt.TARGET_ID = tb.TARGET_ID
 );

-- 仅当一个旧 Agent 版本的全部启用 Source Binding 只指向一个 Target 时才推导，
-- 不把共享 Prometheus 中的多个数据库错误地全部绑定给 Agent。
INSERT INTO KBOT_OPS_AGENT_VERSION_TARGET (
    AGENT_VERSION_ID, TARGET_ID, CREATED_AT
)
SELECT avs.AGENT_VERSION_ID,
       HEXTORAW(MIN(RAWTOHEX(tsb.TARGET_ID))),
       CURRENT_TIMESTAMP
  FROM KBOT_OPS_AGENT_VERSION_SOURCE avs
  JOIN KBOT_OPS_TARGET_SOURCE_BINDING tsb
    ON tsb.DIAGNOSTIC_SOURCE_ID = avs.DIAGNOSTIC_SOURCE_ID
   AND tsb.STATUS = 'ACTIVE'
 WHERE NOT EXISTS (
       SELECT 1
         FROM KBOT_OPS_AGENT_VERSION_TARGET avt
        WHERE avt.AGENT_VERSION_ID = avs.AGENT_VERSION_ID
 )
 GROUP BY avs.AGENT_VERSION_ID
HAVING COUNT(DISTINCT tsb.TARGET_ID) = 1;

PROMPT [7/11] 为历史会话回填冻结 Target

ALTER TABLE KBOT_OPS_CONVERSATION ADD (TARGET_ID RAW(16));

UPDATE KBOT_OPS_CONVERSATION c
   SET TARGET_ID = COALESCE(
       (SELECT r.TARGET_ID
          FROM KBOT_OPS_RUN r
         WHERE r.OPS_RUN_ID = c.SOURCE_RUN_ID),
       (SELECT s.TARGET_ID
          FROM KBOT_OPS_SITUATION s
         WHERE s.SITUATION_ID = c.SOURCE_SITUATION_ID),
       (SELECT rp.TARGET_ID
          FROM KBOT_OPS_REPORT rp
         WHERE rp.REPORT_ID = c.SOURCE_REPORT_ID),
       (SELECT HEXTORAW(MIN(RAWTOHEX(ct.RESOLVED_TARGET_ID)))
          FROM KBOT_OPS_CONVERSATION_TURN ct
         WHERE ct.CONVERSATION_ID = c.CONVERSATION_ID
           AND ct.RESOLVED_TARGET_ID IS NOT NULL
        HAVING COUNT(DISTINCT ct.RESOLVED_TARGET_ID) = 1),
       (SELECT av.TARGET_ID
          FROM KBOT_OPS_AGENT_VERSION av
         WHERE av.AGENT_VERSION_ID = c.AGENT_VERSION_ID),
       (SELECT HEXTORAW(MIN(RAWTOHEX(avt.TARGET_ID)))
          FROM KBOT_OPS_AGENT_VERSION_TARGET avt
         WHERE avt.AGENT_VERSION_ID = c.AGENT_VERSION_ID
        HAVING COUNT(DISTINCT avt.TARGET_ID) = 1)
   );

DECLARE
    v_unresolved NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_unresolved
      FROM KBOT_OPS_CONVERSATION
     WHERE TARGET_ID IS NULL;
    IF v_unresolved > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20004,
            '回填后仍有 ' || v_unresolved || ' 条会话缺少 Target'
        );
    END IF;
END;
/

ALTER TABLE KBOT_OPS_CONVERSATION MODIFY (TARGET_ID NOT NULL);
ALTER TABLE KBOT_OPS_CONVERSATION ADD CONSTRAINT FK_OPS_CONV_TARGET
    FOREIGN KEY (TARGET_ID) REFERENCES KBOT_OPS_TARGET (TARGET_ID);
CREATE INDEX IX_OPS_CONV_TARGET ON KBOT_OPS_CONVERSATION (TARGET_ID);

-- 确保由历史会话确定的 Target 也属于对应的冻结 Agent 版本。
INSERT INTO KBOT_OPS_AGENT_VERSION_TARGET (
    AGENT_VERSION_ID, TARGET_ID, CREATED_AT
)
SELECT DISTINCT c.AGENT_VERSION_ID, c.TARGET_ID, CURRENT_TIMESTAMP
  FROM KBOT_OPS_CONVERSATION c
 WHERE NOT EXISTS (
       SELECT 1
         FROM KBOT_OPS_AGENT_VERSION_TARGET avt
        WHERE avt.AGENT_VERSION_ID = c.AGENT_VERSION_ID
          AND avt.TARGET_ID = c.TARGET_ID
 );

PROMPT [8/11] 删除 Agent 版本旧单 Target 列

ALTER TABLE KBOT_OPS_AGENT_VERSION DROP CONSTRAINT FK_OPS_AGENT_VERSION_TARGET;
DROP INDEX IX_OPS_AGENT_VERSION_TARGET;
ALTER TABLE KBOT_OPS_AGENT_VERSION DROP COLUMN TARGET_ID;

PROMPT [9/11] 更新 Schema 版本投影

CREATE OR REPLACE VIEW KBOT_V_OPS_SCHEMA_VERSION AS
SELECT
    'AIOPS' AS COMPONENT,
    15 AS SCHEMA_VERSION,
    'aiops-oracle-v5' AS CONTRACT_VERSION
FROM DUAL;

PROMPT [10/11] 提交升级

COMMIT;

PROMPT [11/11] 输出升级结果

SELECT COMPONENT, SCHEMA_VERSION, CONTRACT_VERSION
  FROM KBOT_V_OPS_SCHEMA_VERSION;

SELECT
    (SELECT COUNT(*) FROM KBOT_OPS_TARGET) AS TARGET_COUNT,
    (SELECT COUNT(*) FROM KBOT_OPS_AGENT) AS AGENT_COUNT,
    (SELECT COUNT(*) FROM KBOT_OPS_AGENT_VERSION_TARGET)
        AS AGENT_TARGET_COUNT,
    (SELECT COUNT(*) FROM KBOT_OPS_DIAGNOSTIC_SOURCE) AS SOURCE_COUNT,
    (SELECT COUNT(*) FROM KBOT_OPS_CONVERSATION) AS CONVERSATION_COUNT,
    (SELECT COUNT(*) FROM KBOT_MANAGED_CREDENTIAL) AS CREDENTIAL_COUNT
FROM DUAL;

PROMPT AIOps Schema 13 -> 15 原位升级完成；监控源及 Webhook 凭据数据未重建。

WHENEVER SQLERROR CONTINUE
