services:
  kbot-kibana:
    image: elastic/kibana:${ELASTIC_STACK_VERSION:-9.1.5}
    container_name: kbot-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://kbot-eslog:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=${KIBANA_SERVICE_ACCOUNT_TOKEN}
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    networks:
      - elk-network
    restart: unless-stopped

  kbot-filebeat:
    image: elastic/filebeat:${ELASTIC_STACK_VERSION:-9.1.5}
    container_name: kbot-filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - kblogs:/usr/share/filebeat/logs/kb/:ro
      - filebeat-data:/usr/share/filebeat/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ELASTICSEARCH_HOSTS=http://kbot-eslog:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - elk-network
    restart: unless-stopped

volumes:
  filebeat-data:
    driver: local
    driver_opts:
      type: none
      device: ${FILEBEAT_DATA}
      o: bind
  kblogs:
    driver: local
    driver_opts:
      type: none
      device: ${KB_LOGS}
      o: bind

networks:
  elk-network:
    external: true
    name: elk-log-container_elk-network