filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /usr/share/filebeat/logs/kb/*.log
  fields:
    log_type: "kb"
  fields_under_root: true
  multiline.pattern: '^[[:space:]]+(at|File|#)|\b(Traceback|Error|Exception):'
  multiline.negate: false
  multiline.match: after

processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~
  
setup.ilm.enabled: false
setup.template.enabled: true

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  indices:
    - index: "filebeat-kblogs-%{+yyyy.MM.dd}"
      when.equals:
        log_type: "kb"

setup.kibana:
  host: "kbot-kibana:5601"

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: kbot-filebeat
  keepfiles: 7


filebeat.autodiscover:
  providers:
    - type: filestream
      templates:
        # 模板 1：匹配标签为 nginx-frontend 的容器
        - condition:
            equals:
              docker.container.labels.app.type: "nginx-frontend"
          config:
            - type: container
              # 将此容器的日志发送到名为 filebeat-nginx-* 的索引
              index: "filebeat-nginx-%{+yyyy.MM.dd}"

        # 模板 2：匹配标签为 mysql-database 的容器
        - condition:
            equals:
              docker.container.labels.app.type: "mysql-database"
          config:
            - type: container
              index: "filebeat-mysql-%{+yyyy.MM.dd}"

        # 模板 3：一个更通用的模板，收集所有其他容器日志
        - condition:
            # 例如，可以匹配所有不包含 filebeat 自身日志的容器
            not:
              contains:
                docker.container.name: "kbot-filebeat"
          config:
            - type: container
              index: "filebeat-other-%{+yyyy.MM.dd}"