from loguru import logger
from sqlalchemy import select, delete, and_
from core.exceptions import DatabaseException, DataNotFoundException
from dao.entities import PromptEntity
from .base_repo import BaseRepository
from core.config import get_app_config
from core.dictionary import PromptCategory


class PromptRepository(BaseRepository[PromptEntity]):
    """Repository for KBOT_MD_PROMPT table operations."""
    
    async def get_prompt_by_id(self, prompt_id: int) -> str:
        """
        Get prompt content by ID.
        Fix type annotation: return str instead of Sequence[str] (single template string)
        :param prompt_id: Prompt ID to query
        :return: Prompt template string
        """
        try:
            stmt = select(PromptEntity.template).where(PromptEntity.prompt_id == prompt_id)
            result = await self.session.execute(stmt)
            prompt_template = result.scalar_one_or_none()
            
            if prompt_template is None:
                raise DataNotFoundException(f"Prompt with ID {prompt_id} not found")
            
            logger.debug(f"Retrieved prompt template for ID {prompt_id}: {prompt_template[:50]}...")
            return prompt_template
        except DataNotFoundException as e:
            raise e
        except Exception as e:
            raise DatabaseException(f"Failed to get prompt by ID {prompt_id}", original_error=e)
        
    async def get_prompt_by_unique_name(self, prompt_unique_name: str) -> str:
        """
        Get prompt content by unique name.
        :param prompt_unique_name: Prompt unique name to query
        :return: Prompt template string
        """
        try:
            stmt = select(PromptEntity.template).where(
                PromptEntity.prompt_unique_name == prompt_unique_name
            )
            result = await self.session.execute(stmt)
            prompt_template = result.scalar_one_or_none()
            
            if prompt_template is None:
                raise DataNotFoundException(f"Prompt with unique name '{prompt_unique_name}' not found")
            
            logger.debug(f"Retrieved prompt template for '{prompt_unique_name}': {prompt_template[:50]}...")
            return prompt_template
        except DataNotFoundException as e:
            raise e
        except Exception as e:
            raise DatabaseException(
                f"Failed to get prompt by unique name '{prompt_unique_name}'",
                original_error=e
            )
        
    async def delete(self, prompt_id: int):
        """
        Delete prompt by ID.
        :param prompt_id: Prompt ID to delete
        """
        try:
            stmt = delete(PromptEntity).where(PromptEntity.prompt_id == prompt_id)
            await self.session.execute(stmt)

        except Exception as e:
            raise DatabaseException(f"Failed to delete prompt by ID {prompt_id}", original_error=e)
        
    async def reset_sys_prompt(self) -> None:
        """重置系统提示词"""
        try:
            await self.session.execute(
                delete(PromptEntity)
                .where(
                    and_(
                        PromptEntity.domain_id == 0,
                        PromptEntity.category == PromptCategory.SYSTEM_PROMPT.value
                    )
                )
            )
            from agent.prompt.default_prompt import default_prompt
            for name, prompt_text in default_prompt._prompts.items():
                # prompt_text 中可能以 \n 开头，strip 掉前后空白
                clean_text = prompt_text.strip()
                entity = PromptEntity(
                    app_id=get_app_config().app_id,
                    domain_id=0,
                    name=name,
                    prompt_unique_name=name,
                    prompt_category=PromptCategory.SYSTEM_PROMPT.value,
                    template=clean_text,
                    status=1,
                    descs="Automatically generated by system, do not delete.",
                    created_by="System",
                )
                self.session.add(entity)
            await self.session.flush()
        except Exception as e:
            if isinstance(e, (DataNotFoundException)):
                raise
            raise DatabaseException(f"Failed to reset system prompt", original_error=e)
