# LLM 服务基础配置
service_name=llm-service
service_version=1.0.0
service_host=0.0.0.0
service_port=9202

# LLM 模型基础配置
# timeout 单位：秒
max_tokens=8192
temperature = 0.7
top_p = 1.0
top_k = 0
timeout=30
frequency_penalty=0.0
presence_penalty=0.0