"""静态检查 KBot 4.0 按服务拆分的 Oracle 全量建库脚本。"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_ROOT = ROOT / "database" / "oracle"
SERVICE_TABLES = {
    "platform_core": {"KBOT_PLATFORM_DOMAIN"},
    "model_serving": {"KBOT_AI_MODEL"},
    "knowledge_core": {
        "KBOT_KC_COLLECTION",
        "KBOT_KC_COLLECTION_BINDING",
        "KBOT_KC_INGESTION_RECEIPT",
        "KBOT_KC_BUNDLE",
        "KBOT_KC_BUNDLE_REVISION",
        "KBOT_KC_DOCUMENT",
        "KBOT_KC_DOCUMENT_VERSION",
        "KBOT_KC_BUNDLE_REVISION_DOCUMENT",
        "KBOT_KC_PARSE_VIEW",
        "KBOT_KC_INGESTION_JOB",
        "KBOT_KC_EVIDENCE",
        "KBOT_KC_DISCOVERY_OBJECT",
        "KBOT_KC_RELATION",
    },
    "agent_runtime": {
        "KBOT_AGENT_DEFINITION",
        "KBOT_AGENT_RUN",
        "KBOT_AGENT_TASK",
        "KBOT_AGENT_ARTIFACT",
        "KBOT_AGENT_RUN_EVENT",
        "KBOT_AGENT_DELEGATION",
    },
}
FORBIDDEN_TOKENS = (
    "KBOT_MD_",
    "KBOT_BIZ_",
    "TXTCHUNK",
    "INSERT INTO",
    "MERGE INTO",
    "CREATE TABLE AS SELECT",
    "DATABASE LINK",
)
KC_UUID_COLUMNS = (
    "COLLECTION_ID",
    "BINDING_ID",
    "INGESTION_RECEIPT_ID",
    "BUNDLE_ID",
    "CURRENT_REVISION_ID",
    "BUNDLE_REVISION_ID",
    "DOCUMENT_ID",
    "DOCUMENT_VERSION_ID",
    "BUNDLE_REVISION_DOCUMENT_ID",
    "PARSE_VIEW_ID",
    "INGESTION_JOB_ID",
    "EVIDENCE_ID",
    "DISCOVERY_OBJECT_ID",
    "RELATION_ID",
    "SUBJECT_ID",
    "OBJECT_ID",
)
AGENT_UUID_COLUMNS = (
    "AGENT_ID",
    "RUN_ID",
    "PARENT_RUN_ID",
    "TASK_ID",
    "PARENT_TASK_ID",
    "OUTPUT_ARTIFACT_ID",
    "ARTIFACT_ID",
    "DELEGATION_ID",
    "CHILD_RUN_ID",
    "RESULT_ARTIFACT_ID",
)


def _ordered_scripts(service_dir: Path, errors: list[str]) -> list[Path]:
    scripts = sorted(service_dir.glob("[0-9][0-9][0-9]_*.sql"))
    numbers = [
        int(re.match(r"(\d+)_", script.name).group(1))
        for script in scripts
    ]
    expected = list(range(1, len(scripts) + 1))
    if not scripts:
        errors.append(f"{service_dir.name} 缺少建库脚本")
    elif numbers != expected:
        errors.append(
            f"{service_dir.name} 建库顺序为 {numbers}，预期为 {expected}"
        )
    return scripts


def main() -> int:
    errors: list[str] = []
    if (ROOT / "migrations").exists():
        errors.append("4.0 禁止保留 migrations/；请维护规范全量建库脚本")

    all_tables: dict[str, str] = {}
    service_sql: dict[str, str] = {}
    for service, expected_tables in SERVICE_TABLES.items():
        service_dir = SCHEMA_ROOT / service
        scripts = _ordered_scripts(service_dir, errors)
        combined = "\n".join(
            script.read_text(encoding="utf-8").upper()
            for script in scripts
        )
        service_sql[service] = combined
        for token in FORBIDDEN_TOKENS:
            if token in combined:
                errors.append(f"{service} 禁止出现 3.x 或数据导入语句：{token}")
        if re.search(r"\bDROP\s+(TABLE|VIEW|INDEX)\b", combined):
            errors.append(f"{service} 全量建库脚本禁止包含 DROP")

        created_tables = set(
            re.findall(r"\bCREATE\s+TABLE\s+([A-Z][A-Z0-9_]*)", combined)
        )
        missing = expected_tables - created_tables
        unexpected = created_tables - expected_tables
        if missing:
            errors.append(f"{service} 缺少表：{sorted(missing)}")
        if unexpected:
            errors.append(f"{service} 出现未登记表：{sorted(unexpected)}")
        for table in created_tables:
            owner = all_tables.setdefault(table, service)
            if owner != service:
                errors.append(f"{table} 被 {owner} 和 {service} 重复拥有")

        constraints = re.findall(
            r"\bCONSTRAINT\s+([A-Z][A-Z0-9_]*)",
            combined,
        )
        for constraint in constraints:
            if len(constraint) > 30:
                errors.append(
                    f"{service} 的 Oracle Constraint 超过 30 字符：{constraint}"
                )

    kc_sql = service_sql.get("knowledge_core", "")
    if "GENERATED BY DEFAULT ON NULL AS IDENTITY" in kc_sql:
        errors.append("Knowledge Core UUID 主键禁止使用数据库自增 Identity")
    for column in KC_UUID_COLUMNS:
        if not re.search(rf"\b{column}\s+RAW\s*\(\s*16\s*\)", kc_sql):
            errors.append(f"{column} 必须至少声明一次为 UUIDv7 RAW(16)")
        if re.search(rf"\b{column}\s+NUMBER\s*\(", kc_sql):
            errors.append(f"{column} 禁止声明为 NUMBER")

    model_sql = service_sql.get("model_serving", "")
    if not re.search(r"\bMODEL_ID\s+RAW\s*\(\s*16\s*\)", model_sql):
        errors.append("Model Serving 的 MODEL_ID 必须为 UUIDv7 RAW(16)")

    agent_sql = service_sql.get("agent_runtime", "")
    for column in AGENT_UUID_COLUMNS:
        if not re.search(rf"\b{column}\s+RAW\s*\(\s*16\s*\)", agent_sql):
            errors.append(f"Agent Runtime 的 {column} 必须为 UUIDv7 RAW(16)")
        if re.search(rf"\b{column}\s+NUMBER\s*\(", agent_sql):
            errors.append(f"Agent Runtime 的 {column} 禁止声明为 NUMBER")
    if not re.search(r"\bLEASE_TOKEN\s+RAW\s*\(\s*16\s*\)", agent_sql):
        errors.append("Agent Runtime 的 LEASE_TOKEN 必须为 128-bit RAW(16)")

    if errors:
        print("Oracle 全量建库脚本检查失败：")
        print("\n".join(errors))
        return 1
    script_count = sum(
        len(list((SCHEMA_ROOT / service).glob("*.sql")))
        for service in SERVICE_TABLES
    )
    print(
        f"Oracle 全量建库脚本检查通过："
        f"{len(SERVICE_TABLES)} 个服务，{script_count} 个脚本"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
