"""部署前静态检查 Knowledge Core Migration。"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MIGRATION_DIR = ROOT / "migrations" / "kc"
V1_TOKENS = ("KBOT_MD_KB", "KBOT_MD_FILE", "KBOT_MD_TXT_CHUNK", "TXTCHUNK")
UUID_ID_COLUMNS = (
    "COLLECTION_ID",
    "BINDING_ID",
    "INGESTION_RECEIPT_ID",
    "BUNDLE_ID",
    "CURRENT_REVISION_ID",
    "BUNDLE_REVISION_ID",
    "DOCUMENT_ID",
    "DOCUMENT_VERSION_ID",
    "BUNDLE_REVISION_DOCUMENT_ID",
    "PARSE_VIEW_ID",
    "INGESTION_JOB_ID",
    "EVIDENCE_ID",
    "DISCOVERY_OBJECT_ID",
    "RELATION_ID",
    "SUBJECT_ID",
    "OBJECT_ID",
)


def main() -> int:
    files = sorted(MIGRATION_DIR.glob("[0-9][0-9][0-9]_*.sql"))
    numbers = [int(re.match(r"(\d+)_", path.name).group(1)) for path in files]
    expected = list(range(1, len(files) + 1))
    errors: list[str] = []
    if numbers != expected:
        errors.append(f"Migration 序号为 {numbers}，预期为 {expected}")
    combined_sql = ""
    for path in files:
        text = path.read_text(encoding="utf-8").upper()
        combined_sql += f"\n{text}"
        for token in V1_TOKENS:
            if token in text:
                errors.append(f"{path.name} 禁止引用 V1 对象 {token}")
    if "GENERATED BY DEFAULT ON NULL AS IDENTITY" in combined_sql:
        errors.append("KC 领域主键禁止继续使用数据库自增 Identity")
    for column in UUID_ID_COLUMNS:
        if not re.search(rf"\b{column}\s+RAW\s*\(\s*16\s*\)", combined_sql):
            errors.append(f"{column} 必须至少声明一次为 UUIDv7 RAW(16)")
        if re.search(rf"\b{column}\s+NUMBER\s*\(", combined_sql):
            errors.append(f"{column} 禁止声明为 NUMBER")
    constraint_names = re.findall(
        r"\bCONSTRAINT\s+([A-Z][A-Z0-9_]*)",
        combined_sql,
    )
    for name in constraint_names:
        if len(name) > 30:
            errors.append(f"Oracle Constraint 名称超过 30 字符：{name}")
    required_foreign_keys = (
        "FK_KC_BINDING_COLLECTION",
        "FK_KC_BUNDLE_COLLECTION",
        "FK_KC_REVISION_BUNDLE",
        "FK_KC_DOCUMENT_BUNDLE",
        "FK_KC_DOC_VERSION_DOCUMENT",
        "FK_KC_MEMBER_REVISION",
        "FK_KC_PARSE_VIEW_VERSION",
        "FK_KC_JOB_COLLECTION",
        "FK_KC_EVIDENCE_PARSE_VIEW",
        "FK_KC_DISCOVERY_REVISION",
        "FK_KC_RELATION_REVISION",
    )
    for name in required_foreign_keys:
        if name not in constraint_names:
            errors.append(f"缺少 KC 范围完整性约束：{name}")
    if errors:
        print("KC Migration 检查失败：")
        print("\n".join(errors))
        return 1
    print(f"KC Migration 检查通过（{len(files)} 个脚本）")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
