-- ============================================================================
-- kbot3 数据库 DDL 变更脚本
-- 移植日期: 2026-07-14
-- 基准: NexusCube (PostgreSQL) → kbot3 (Oracle 23ai)
-- ============================================================================
-- 
-- 使用说明:
--   1. 以 DBA 用户登录 Oracle
--   2. 按顺序执行本脚本
--   3. 验证所有 ALTER TABLE 和新表创建成功
--
-- ============================================================================

-- ============================================================================
-- 1. KBOT_OPS_DB_INSTANCE — 追加 zabbix_host_name
-- ============================================================================
-- NexusCube 对应表: ops_db_instance
-- PG 字段: zabbix_host_name VARCHAR(256)

ALTER TABLE KBOT_OPS_DB_INSTANCE ADD (
    ZABBIX_HOST_NAME VARCHAR2(256)
);

COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.ZABBIX_HOST_NAME IS 'Zabbix 监控主机名称，用于 host.get 解析 hostid';


-- ============================================================================
-- 2. KBOT_BIZ_TXT_EMBEDDING — 追加字段 + 修改默认值
-- ============================================================================
-- NexusCube 对应表: txt_chunk (PARTITION BY LIST kb_id)
-- PG 追加字段: hierarchy_path TEXT[], hierarchy_depth INT, heading_level INT,
--               parent_chunk_id UUID, section_id TEXT, created_at TIMESTAMPTZ
-- PG 默认值:   chunk_num DEFAULT 0, chunk_type DEFAULT 'text',
--              header DEFAULT '', security_level DEFAULT 0

-- 2.1 追加缺失字段
ALTER TABLE KBOT_BIZ_TXT_EMBEDDING ADD (
    HIERARCHY_PATH    VARCHAR2(4000) DEFAULT '[]',        -- 文档层级路径（JSON 数组）
    HIERARCHY_DEPTH   NUMBER DEFAULT 0 NOT NULL,           -- 层级深度
    HEADING_LEVEL     NUMBER DEFAULT 0 NOT NULL,           -- 标题级别
    PARENT_CHUNK_ID   VARCHAR2(256),                       -- 父块 ID
    SECTION_ID        VARCHAR2(256),                       -- 所属 section ID
    CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- 创建时间
);

-- 2.2 已有字段补充 NOT NULL + DEFAULT
ALTER TABLE KBOT_BIZ_TXT_EMBEDDING MODIFY (
    CHUNK_NUM       NUMBER DEFAULT 0 NOT NULL,
    CHUNK_TYPE      VARCHAR2(20) DEFAULT 'text',
    HEADER          VARCHAR2(256) DEFAULT '',
    SECURITY_LEVEL  NUMBER DEFAULT 0 NOT NULL
);

-- 2.3 大文本字段类型调整（如 VARCHAR2(4000) 不够用，改为 CLOB）
-- 根据实际数据量决定是否执行:
-- ALTER TABLE KBOT_BIZ_TXT_EMBEDDING MODIFY (DOC_SUMMARY CLOB);
-- ALTER TABLE KBOT_BIZ_TXT_EMBEDDING MODIFY (SEARCH_HELPER CLOB);

COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.HIERARCHY_PATH IS '文档层级路径（JSON 数组，如 ["章1","节1.1"]）';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.HIERARCHY_DEPTH IS '层级深度';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.HEADING_LEVEL IS '标题级别（0=正文, 1=一级标题, 2=二级标题...）';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.PARENT_CHUNK_ID IS '父块 ID';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.SECTION_ID IS '所属 section ID';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.CREATED_AT IS '创建时间';


-- ============================================================================
-- 3. KBOT_DOC_METADATA — 新建表（文档元数据）
-- ============================================================================
-- NexusCube 对应表: doc_metadata
-- 用途: 存储文档的元数据信息（文档名、类型、编号、页码、关键词等）

CREATE TABLE KBOT_DOC_METADATA (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    KB_ID           NUMBER NOT NULL REFERENCES KBOT_MD_KB(KB_ID) ON DELETE CASCADE,
    FILE_ID         VARCHAR2(256) NOT NULL UNIQUE REFERENCES KBOT_MD_KB_FILES(FILE_ID) ON DELETE CASCADE,
    DOC_NAME        VARCHAR2(1000),
    DOC_TYPE        VARCHAR2(64),
    DOC_NUMBER      VARCHAR2(256),
    DOC_VERSION     VARCHAR2(64),
    DOC_DATE        DATE,
    PAGE_COUNT      NUMBER,
    CHUNK_COUNT     NUMBER,
    DOC_ABSTRACT    CLOB,
    DOC_KEYWORDS    JSON DEFAULT '[]',
    DOC_REFERENCES  JSON DEFAULT '[]',
    BIZ_METADATA    JSON DEFAULT '{}',
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE KBOT_DOC_METADATA IS '文档元数据表 - 记录知识库中文档的名称、类型、编号、版本、页码等元信息';
COMMENT ON COLUMN KBOT_DOC_METADATA.ID IS '主键，自增';
COMMENT ON COLUMN KBOT_DOC_METADATA.KB_ID IS '关联知识库 ID';
COMMENT ON COLUMN KBOT_DOC_METADATA.FILE_ID IS '关联文件 ID（唯一）';
COMMENT ON COLUMN KBOT_DOC_METADATA.DOC_NAME IS '文档正式名称';
COMMENT ON COLUMN KBOT_DOC_METADATA.DOC_TYPE IS '文档类型: standard/report/contract/manual/other';
COMMENT ON COLUMN KBOT_DOC_METADATA.DOC_NUMBER IS '标准号/编号';
COMMENT ON COLUMN KBOT_DOC_METADATA.DOC_VERSION IS '版本号';
COMMENT ON COLUMN KBOT_DOC_METADATA.DOC_DATE IS '文档日期';
COMMENT ON COLUMN KBOT_DOC_METADATA.PAGE_COUNT IS '文档总页数';
COMMENT ON COLUMN KBOT_DOC_METADATA.CHUNK_COUNT IS '解析产生的块数';
COMMENT ON COLUMN KBOT_DOC_METADATA.DOC_ABSTRACT IS '文档摘要';
COMMENT ON COLUMN KBOT_DOC_METADATA.DOC_KEYWORDS IS '关键词列表（JSON）';
COMMENT ON COLUMN KBOT_DOC_METADATA.DOC_REFERENCES IS '引用列表（JSON）';
COMMENT ON COLUMN KBOT_DOC_METADATA.BIZ_METADATA IS '业务元数据扩展字段（JSON）';
COMMENT ON COLUMN KBOT_DOC_METADATA.CREATED_AT IS '创建时间';
COMMENT ON COLUMN KBOT_DOC_METADATA.UPDATED_AT IS '更新时间';

-- 索引
CREATE INDEX IDX_DOC_META_KB ON KBOT_DOC_METADATA(KB_ID);


-- ============================================================================
-- 4. KBOT_DOC_RELATION — 新建表（文档引用关系）
-- ============================================================================
-- NexusCube 对应表: doc_relation
-- 用途: 存储文档之间的引用关系

CREATE TABLE KBOT_DOC_RELATION (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    KB_ID           NUMBER NOT NULL REFERENCES KBOT_MD_KB(KB_ID) ON DELETE CASCADE,
    SOURCE_FILE_ID  VARCHAR2(256) NOT NULL REFERENCES KBOT_MD_KB_FILES(FILE_ID) ON DELETE CASCADE,
    TARGET_FILE_ID  VARCHAR2(256) REFERENCES KBOT_MD_KB_FILES(FILE_ID) ON DELETE CASCADE,
    TARGET_DOC_NAME VARCHAR2(1000),
    TARGET_CHAPTER  VARCHAR2(500),
    TARGET_SECTION  VARCHAR2(500),
    RELATION_TYPE   VARCHAR2(64) DEFAULT 'reference',
    CONTEXT_SNIPPET CLOB,
    CONFIDENCE      NUMBER(3,2) DEFAULT 1.0,
    BIZ_METADATA    JSON DEFAULT '{}',
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE KBOT_DOC_RELATION IS '文档引用关系表 - 记录文档之间的引用/依赖/替换关系';
COMMENT ON COLUMN KBOT_DOC_RELATION.ID IS '主键，自增';
COMMENT ON COLUMN KBOT_DOC_RELATION.KB_ID IS '所属知识库 ID';
COMMENT ON COLUMN KBOT_DOC_RELATION.SOURCE_FILE_ID IS '引用方文件 ID';
COMMENT ON COLUMN KBOT_DOC_RELATION.TARGET_FILE_ID IS '被引用方文件 ID';
COMMENT ON COLUMN KBOT_DOC_RELATION.TARGET_DOC_NAME IS '被引用文档名称';
COMMENT ON COLUMN KBOT_DOC_RELATION.TARGET_CHAPTER IS '被引用章节号';
COMMENT ON COLUMN KBOT_DOC_RELATION.TARGET_SECTION IS '被引用节号';
COMMENT ON COLUMN KBOT_DOC_RELATION.RELATION_TYPE IS '关系类型: reference/dependency/replace';
COMMENT ON COLUMN KBOT_DOC_RELATION.CONTEXT_SNIPPET IS '引用处原文上下文';
COMMENT ON COLUMN KBOT_DOC_RELATION.CONFIDENCE IS 'LLM 提取置信度 0~1';
COMMENT ON COLUMN KBOT_DOC_RELATION.BIZ_METADATA IS '业务扩展字段（JSON）';
COMMENT ON COLUMN KBOT_DOC_RELATION.CREATED_AT IS '创建时间';

-- 索引
CREATE INDEX IDX_DOC_REL_SOURCE ON KBOT_DOC_RELATION(SOURCE_FILE_ID);
CREATE INDEX IDX_DOC_REL_TARGET ON KBOT_DOC_RELATION(TARGET_FILE_ID);


-- ============================================================================
-- 5. KBOT_AGENT_WORKFLOW — 新建表（SOP 工作流）
-- ============================================================================
-- NexusCube 对应表: workflow
-- 用途: 存储用户自定义的 SOP 自动化编排流程

CREATE TABLE KBOT_AGENT_WORKFLOW (
    ID              VARCHAR2(36) PRIMARY KEY,
    AGENT_ID        VARCHAR2(36) NOT NULL,
    NAME            VARCHAR2(255) NOT NULL,
    DESCRIPTION     VARCHAR2(1024) NOT NULL,
    EMBEDDING       VECTOR,
    NODES           JSON,
    EDGES           JSON,
    CONFIG          JSON,
    EXEC_MODE       VARCHAR2(20) DEFAULT 'guided' NOT NULL,
    IS_ACTIVE       VARCHAR2(1) DEFAULT '1' NOT NULL,
    CREATED_BY      VARCHAR2(50),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      VARCHAR2(50),
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE KBOT_AGENT_WORKFLOW IS 'SOP 工作流表 - 存储用户自定义的任务执行蓝图';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.ID IS 'UUID, 主键';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.AGENT_ID IS '所属 Agent ID';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.NAME IS '流程名称';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.DESCRIPTION IS '流程语义描述';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.EMBEDDING IS 'Oracle 23ai 语义向量';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.NODES IS '节点信息（JSON）';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.EDGES IS '连接信息（JSON）';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.CONFIG IS '全局配置（JSON）';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.EXEC_MODE IS 'SOP 强制执行模式: strict/guided/suggested';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.IS_ACTIVE IS '是否启用: 1=启用, 0=禁用';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.CREATED_BY IS '创建人';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.CREATED_AT IS '创建时间';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.UPDATED_BY IS '最后修改人';
COMMENT ON COLUMN KBOT_AGENT_WORKFLOW.UPDATED_AT IS '更新时间';

-- 索引
CREATE INDEX IDX_WORKFLOW_AGENT ON KBOT_AGENT_WORKFLOW(AGENT_ID);


-- ============================================================================
-- 6. EXTRACTED_IMAGES — 新建表（提取图片记录）
-- ============================================================================
-- NexusCube 对应表: extracted_images
-- 用途: 存储从文档中提取的图片及其视觉 embedding

CREATE TABLE EXTRACTED_IMAGES (
    ID              VARCHAR2(36) PRIMARY KEY,
    FILE_ID         VARCHAR2(256) NOT NULL,
    KB_ID           VARCHAR2(256) NOT NULL,
    PAGE_NO         NUMBER(38,0) NOT NULL,
    IMAGE_PATH      VARCHAR2(1000) NOT NULL,
    EMBEDDING       VECTOR,
    DESCRIPTION     CLOB,
    IMAGE_TYPE      VARCHAR2(32) DEFAULT 'figure' NOT NULL,
    BBOX            JSON DEFAULT '{}',
    CHUNK_ID        VARCHAR2(256),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE EXTRACTED_IMAGES IS '提取图片记录表 - 文档中提取的图片及其视觉特征';
COMMENT ON COLUMN EXTRACTED_IMAGES.ID IS '主键，UUID';
COMMENT ON COLUMN EXTRACTED_IMAGES.FILE_ID IS '关联的文件 ID';
COMMENT ON COLUMN EXTRACTED_IMAGES.KB_ID IS '关联的知识库 ID';
COMMENT ON COLUMN EXTRACTED_IMAGES.PAGE_NO IS '图片所在页码编号';
COMMENT ON COLUMN EXTRACTED_IMAGES.IMAGE_PATH IS '图片存储路径';
COMMENT ON COLUMN EXTRACTED_IMAGES.EMBEDDING IS 'ColQwen2 视觉 embedding（Oracle VECTOR）';
COMMENT ON COLUMN EXTRACTED_IMAGES.DESCRIPTION IS 'VLM 图片描述文本';
COMMENT ON COLUMN EXTRACTED_IMAGES.IMAGE_TYPE IS '图片类型: figure/table/chart/photo';
COMMENT ON COLUMN EXTRACTED_IMAGES.BBOX IS '图片边界框坐标（JSON）';
COMMENT ON COLUMN EXTRACTED_IMAGES.CHUNK_ID IS '关联的文本 chunk ID';
COMMENT ON COLUMN EXTRACTED_IMAGES.CREATED_AT IS '创建时间';

CREATE INDEX IDX_EXTRACTED_IMG_FILE ON EXTRACTED_IMAGES(FILE_ID);
CREATE INDEX IDX_EXTRACTED_IMG_KB ON EXTRACTED_IMAGES(KB_ID);


-- ============================================================================
-- 7. PAGE_VISUAL_INDEX — 新建表（页面视觉索引）
-- ============================================================================
-- NexusCube 对应表: page_visual_index
-- 用途: 存储文档页面的视觉索引（截图+embedding），支持以图搜图

CREATE TABLE PAGE_VISUAL_INDEX (
    ID              VARCHAR2(36) PRIMARY KEY,
    FILE_ID         VARCHAR2(256) NOT NULL,
    KB_ID           VARCHAR2(256) NOT NULL,
    PAGE_NO         NUMBER(38,0) NOT NULL,
    IMAGE_PATH      VARCHAR2(1000) NOT NULL,
    EMBEDDING       VECTOR,
    CAPTION         CLOB,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE PAGE_VISUAL_INDEX IS '页面视觉索引表 - 文档页面截图及其视觉特征';
COMMENT ON COLUMN PAGE_VISUAL_INDEX.ID IS '主键，UUID';
COMMENT ON COLUMN PAGE_VISUAL_INDEX.FILE_ID IS '关联的文件 ID';
COMMENT ON COLUMN PAGE_VISUAL_INDEX.KB_ID IS '关联的知识库 ID';
COMMENT ON COLUMN PAGE_VISUAL_INDEX.PAGE_NO IS '页码编号';
COMMENT ON COLUMN PAGE_VISUAL_INDEX.IMAGE_PATH IS '页面截图存储路径';
COMMENT ON COLUMN PAGE_VISUAL_INDEX.EMBEDDING IS '页面视觉 embedding（Oracle VECTOR）';
COMMENT ON COLUMN PAGE_VISUAL_INDEX.CAPTION IS 'VLM 生成的页面摘要描述';
COMMENT ON COLUMN PAGE_VISUAL_INDEX.CREATED_AT IS '创建时间';

CREATE INDEX IDX_VISUAL_INDEX_FILE ON PAGE_VISUAL_INDEX(FILE_ID);
CREATE INDEX IDX_VISUAL_INDEX_KB ON PAGE_VISUAL_INDEX(KB_ID);


-- ============================================================================
-- 8. DDL 执行验证
-- ============================================================================
-- 执行后通过以下查询验证:
--
-- SELECT table_name, column_name, data_type, nullable
-- FROM user_tab_columns
-- WHERE table_name IN ('KBOT_OPS_DB_INSTANCE', 'KBOT_BIZ_TXT_EMBEDDING',
--                       'KBOT_DOC_METADATA', 'KBOT_DOC_RELATION',
--                       'KBOT_AGENT_WORKFLOW', 'EXTRACTED_IMAGES',
--                       'PAGE_VISUAL_INDEX')
-- ORDER BY table_name, column_id;


-- ============================================================================
-- 附录: KBOT_MD_KB_FILES 确认清单（无需 DDL 修改）
-- ============================================================================
-- 
-- kbot3 的 KBOT_MD_KB_FILES 表已有全部必要字段，无需 ALTER TABLE。
-- 代码层注意以下字段名差异:
--
--   NexusCube (PG)      → kbot3 (Oracle)
--   ---------------------------------------------------------------
--   parser_params       → CHUNK_PARSER (JSON)
--   biz_metadata        → BIZ_METADATA (JSON)
--   created_at          → CREATED_TIME (DATE)
--   updated_at          → UPDATED_TIME (DATE)
--   approved_comments   → APPROVE_COMMENTS (VARCHAR2)
--   app_id              → 无对应字段（kbot3 独有，保留）
--


-- ============================================================================
-- 回滚脚本（如需回退）
-- ============================================================================
/*
-- 回退 KBOT_OPS_DB_INSTANCE
ALTER TABLE KBOT_OPS_DB_INSTANCE DROP COLUMN ZABBIX_HOST_NAME;

-- 回退 KBOT_BIZ_TXT_EMBEDDING
ALTER TABLE KBOT_BIZ_TXT_EMBEDDING DROP COLUMN HIERARCHY_PATH;
ALTER TABLE KBOT_BIZ_TXT_EMBEDDING DROP COLUMN HIERARCHY_DEPTH;
ALTER TABLE KBOT_BIZ_TXT_EMBEDDING DROP COLUMN HEADING_LEVEL;
ALTER TABLE KBOT_BIZ_TXT_EMBEDDING DROP COLUMN PARENT_CHUNK_ID;
ALTER TABLE KBOT_BIZ_TXT_EMBEDDING DROP COLUMN SECTION_ID;
ALTER TABLE KBOT_BIZ_TXT_EMBEDDING DROP COLUMN CREATED_AT;
-- 默认值回退（需手动记录原值）

-- 删除新建表
DROP TABLE KBOT_DOC_RELATION CASCADE CONSTRAINTS;
DROP TABLE KBOT_DOC_METADATA CASCADE CONSTRAINTS;
DROP TABLE KBOT_AGENT_WORKFLOW CASCADE CONSTRAINTS;
*/
