
-- ###########################################################################
-- 1 KBOT_MD_DOMAIN (Business Domain Information Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_DOMAIN (
    DOMAIN_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID       NUMBER NOT NULL ENABLE,
    NAME         VARCHAR2(256),
    STATUS       NUMBER(1) DEFAULT 0,
    DESCS        VARCHAR2(512),
    CREATED_BY   VARCHAR2(512),
    CREATED_TIME DATE DEFAULT CURRENT_DATE,
    UPDATED_BY   VARCHAR2(512),
    UPDATED_TIME DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (DOMAIN_ID) USING INDEX ENABLE,
    -- Unique constraint for (NAME, APP_ID)
    CONSTRAINT KBOT_MD_DOMAIN_CON UNIQUE (NAME, APP_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_DOMAIN IS 'Business Domain Information Table - Stores business domain configuration';
-- Column comments
COMMENT ON COLUMN KBOT_MD_DOMAIN.DOMAIN_ID IS 'Business domain ID, primary key';
COMMENT ON COLUMN KBOT_MD_DOMAIN.APP_ID IS 'Associated APP ID (composes unique index with NAME)';
COMMENT ON COLUMN KBOT_MD_DOMAIN.NAME IS 'Business domain name';
COMMENT ON COLUMN KBOT_MD_DOMAIN.STATUS IS 'Status: 1 - Enabled, 0 - Disabled (mislabeled as prompt status in original)';
COMMENT ON COLUMN KBOT_MD_DOMAIN.DESCS IS 'Business domain description';
COMMENT ON COLUMN KBOT_MD_DOMAIN.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_DOMAIN.CREATED_TIME IS 'Creation time (default: current date)';
COMMENT ON COLUMN KBOT_MD_DOMAIN.UPDATED_BY IS 'Last updater user';
COMMENT ON COLUMN KBOT_MD_DOMAIN.UPDATED_TIME IS 'Last update time (default: current date)';

-- ###########################################################################
-- 2 KBOT_MD_KB (Knowledge Base Metadata Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_KB (
    KB_ID               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID              NUMBER NOT NULL ENABLE,
    DOMAIN_ID           NUMBER,
    KB_NAME             VARCHAR2(256),
    KB_CATEGORY         NUMBER(2),
    DESCS               VARCHAR2(512),
    ENGINE              VARCHAR2(100),
    MODELS              JSON,
    DBCONF              JSON,
    KB_STATUS           NUMBER(1),
    SECURITY_LEVEL      NUMBER(1),
    PROCESS_PRIORITY    NUMBER(1),
    CREATED_BY          VARCHAR2(512),
    CREATED_TIME        DATE DEFAULT CURRENT_DATE,
    UPDATED_BY          VARCHAR2(512),
    UPDATED_TIME        DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (KB_ID) USING INDEX ENABLE,
    -- Unique constraint for (KB_NAME, DOMAIN_ID, APP_ID)
    CONSTRAINT KBOT_KB_CON UNIQUE (KB_NAME, DOMAIN_ID, APP_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_KB IS 'Knowledge Base Metadata Table - Stores core KB configuration';
-- Column comments
COMMENT ON COLUMN KBOT_MD_KB.KB_ID IS 'Unique knowledge base identifier, primary key';
COMMENT ON COLUMN KBOT_MD_KB.APP_ID IS 'Associated application ID (composite unique constraint with DOMAIN_ID and KB_NAME)';
COMMENT ON COLUMN KBOT_MD_KB.DOMAIN_ID IS 'Associated business domain ID';
COMMENT ON COLUMN KBOT_MD_KB.KB_NAME IS 'Knowledge base name (unique within the same business domain)';
COMMENT ON COLUMN KBOT_MD_KB.KB_CATEGORY IS 'Knowledge base type enumeration';
COMMENT ON COLUMN KBOT_MD_KB.DESCS IS 'Detailed knowledge base description';
COMMENT ON COLUMN KBOT_MD_KB.ENGINE IS 'Knowledge base engine: Enum:KBEngine';
COMMENT ON COLUMN KBOT_MD_KB.MODELS IS 'Knowledge base models';
COMMENT ON COLUMN KBOT_MD_KB.DBCONF IS 'Knowledge base database configuration';
COMMENT ON COLUMN KBOT_MD_KB.KB_STATUS IS 'Knowledge base status enumeration';
COMMENT ON COLUMN KBOT_MD_KB.SECURITY_LEVEL IS 'File security level enumeration';
COMMENT ON COLUMN KBOT_MD_KB.PROCESS_PRIORITY IS 'Processing priority enumeration';
COMMENT ON COLUMN KBOT_MD_KB.CREATED_BY IS 'Record creator';
COMMENT ON COLUMN KBOT_MD_KB.CREATED_TIME IS 'Record creation time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_KB.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_KB.UPDATED_TIME IS 'Last update time (default: current system time)';

-- ###########################################################################
-- 4 KBOT_MD_KB_FILES (Knowledge Base File Information Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_KB_FILES (
    FILE_ID            VARCHAR2(256) NOT NULL,
    APP_ID             NUMBER NOT NULL,
    KB_ID              NUMBER NOT NULL,
    BATCH              VARCHAR2(256),
    FILE_PATH          VARCHAR2(512),
    FILE_NAME          VARCHAR2(256),
    FILE_EXT           VARCHAR2(256),
    STATUS             NUMBER(2),
    FILE_VERSION       NUMBER,
    IS_OVERWRITE       NUMBER(1),
    SECURITY_LEVEL     NUMBER(1) DEFAULT 1,
    FILE_SIZE          NUMBER,
    CHUNK_PARSER       JSON,
    BIZ_METADATA       JSON,
    PROCESS_PRIORITY   NUMBER,
    LOG_MSG            VARCHAR2(4000),
    CREATED_BY         VARCHAR2(512),
    CREATED_TIME       DATE DEFAULT CURRENT_DATE,
    UPDATED_BY         VARCHAR2(512),
    UPDATED_TIME       DATE DEFAULT CURRENT_DATE,
    APPROVED_BY        VARCHAR2(256),
    APPROVED_TIME      DATE DEFAULT CURRENT_DATE,
    APPROVE_COMMENTS   VARCHAR2(1024),
    -- Primary key constraint
    PRIMARY KEY (FILE_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_KB_FILES IS 'Knowledge Base File Information Table - Stores status and metadata for all KB files';
-- Column comments
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_ID IS 'Unique file identifier, primary key';
COMMENT ON COLUMN KBOT_MD_KB_FILES.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_KB_FILES.KB_ID IS 'Associated knowledge base ID';
COMMENT ON COLUMN KBOT_MD_KB_FILES.BATCH IS 'Upload batch name';
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_PATH IS 'Full file storage path (including filename)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_NAME IS 'Original filename (without extension)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_EXT IS 'File extension';
COMMENT ON COLUMN KBOT_MD_KB_FILES.STATUS IS 'File status enumeration';
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_VERSION IS 'File version number (increments on each update)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.IS_OVERWRITE IS 'Overwrite flag: 1 - Yes, 0 - No';
COMMENT ON COLUMN KBOT_MD_KB_FILES.SECURITY_LEVEL IS 'File security level enumeration';
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_SIZE IS 'File size (in bytes)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.CHUNK_PARSER IS 'Data chunk parsing parameters (JSON)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.BIZ_METADATA IS 'Business metadata (JSON format)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.PROCESS_PRIORITY IS 'Processing priority enumeration';
COMMENT ON COLUMN KBOT_MD_KB_FILES.LOG_MSG IS 'Processing log information';
COMMENT ON COLUMN KBOT_MD_KB_FILES.CREATED_BY IS 'File uploader';
COMMENT ON COLUMN KBOT_MD_KB_FILES.CREATED_TIME IS 'Upload time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_KB_FILES.UPDATED_TIME IS 'Last update time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.APPROVED_BY IS 'Approver user';
COMMENT ON COLUMN KBOT_MD_KB_FILES.APPROVED_TIME IS 'Approval time';
COMMENT ON COLUMN KBOT_MD_KB_FILES.APPROVE_COMMENTS IS 'Approval comments';

-- ###########################################################################
-- 5 KBOT_MD_PROMPT (Prompt Information Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_PROMPT (
    PROMPT_ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID             NUMBER NOT NULL ENABLE,
    DOMAIN_ID          NUMBER,
    NAME               VARCHAR2(256),
    PROMPT_UNIQUE_NAME VARCHAR2(256),
    PROMPT_CATEGORY    NUMBER,
    TEMPLATE           CLOB,
    STATUS             NUMBER(1) DEFAULT 0,
    DESCS              VARCHAR2(512),
    CREATED_BY         VARCHAR2(512),
    CREATED_TIME       DATE DEFAULT CURRENT_DATE,
    UPDATED_BY         VARCHAR2(512),
    UPDATED_TIME       DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (PROMPT_ID) USING INDEX ENABLE,
    -- Unique constraint for prompt unique name
    CONSTRAINT PROMPT_UNIQUE_NAME_UK UNIQUE (PROMPT_UNIQUE_NAME)
);

-- Table comment
COMMENT ON TABLE KBOT_MD_PROMPT IS 'Prompt Information Table - Stores various prompt templates';
-- Column comments
COMMENT ON COLUMN KBOT_MD_PROMPT.PROMPT_ID IS 'Unique prompt identifier, primary key';
COMMENT ON COLUMN KBOT_MD_PROMPT.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_PROMPT.DOMAIN_ID IS 'Associated business domain ID (optional)';
COMMENT ON COLUMN KBOT_MD_PROMPT.NAME IS 'Prompt display name';
COMMENT ON COLUMN KBOT_MD_PROMPT.PROMPT_UNIQUE_NAME IS 'Unique prompt name in database (used for model calls in programs)';
COMMENT ON COLUMN KBOT_MD_PROMPT.PROMPT_CATEGORY IS 'Prompt category enumeration';
COMMENT ON COLUMN KBOT_MD_PROMPT.TEMPLATE IS 'Prompt template content (CLOB large text)';
COMMENT ON COLUMN KBOT_MD_PROMPT.STATUS IS 'Prompt status: 1 - Enabled, 0 - Disabled';
COMMENT ON COLUMN KBOT_MD_PROMPT.DESCS IS 'Detailed prompt description';
COMMENT ON COLUMN KBOT_MD_PROMPT.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_PROMPT.CREATED_TIME IS 'Creation time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_PROMPT.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_PROMPT.UPDATED_TIME IS 'Last update time (default: current system time)';

-- ###########################################################################
-- 6 KBOT_MD_MODELS (AI Model Information Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_MODELS (
    MODEL_ID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID        NUMBER NOT NULL ENABLE,
    DISPLAY_NAME  VARCHAR2(256) NOT NULL,
    MODEL_NAME    VARCHAR2(256) NOT NULL,
    CATEGORY      NUMBER NOT NULL,
    PROVIDER      VARCHAR2(256) NOT NULL,
    API_ENDPOINT  VARCHAR2(256),
    API_KEY       VARCHAR2(256),
    STATUS        NUMBER(1) DEFAULT 0,
    MODEL_PARAMS  JSON,
    DESCS         VARCHAR2(512),
    CREATED_BY    VARCHAR2(512),
    CREATED_TIME  DATE DEFAULT CURRENT_DATE,
    UPDATED_BY    VARCHAR2(512),
    UPDATED_TIME  DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (MODEL_ID) USING INDEX ENABLE,
    -- Unique constraint for (DISPLAY_NAME, APP_ID)
    CONSTRAINT KBOT_UK_APP_MODEL UNIQUE (DISPLAY_NAME, APP_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_MODELS IS 'AI Model Information Table - Stores configuration for various AI models';
-- Column comments
COMMENT ON COLUMN KBOT_MD_MODELS.MODEL_ID IS 'Unique model identifier, primary key';
COMMENT ON COLUMN KBOT_MD_MODELS.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_MODELS.DISPLAY_NAME IS 'Model display name (user-friendly)';
COMMENT ON COLUMN KBOT_MD_MODELS.MODEL_NAME IS 'Model technical name (e.g., gpt-4, text-embedding-ada-002)';
COMMENT ON COLUMN KBOT_MD_MODELS.CATEGORY IS 'Model category enumeration (MODEL_CATEGORY)';
COMMENT ON COLUMN KBOT_MD_MODELS.PROVIDER IS 'Model provider (e.g., OpenAI, Azure, Anthropic)';
COMMENT ON COLUMN KBOT_MD_MODELS.API_ENDPOINT IS 'API endpoint URL (e.g., https://api.openai.com/v1)';
COMMENT ON COLUMN KBOT_MD_MODELS.API_KEY IS 'API key (recommended to store encrypted)';
COMMENT ON COLUMN KBOT_MD_MODELS.STATUS IS 'Model status: 1 - Enabled, 0 - Disabled';
COMMENT ON COLUMN KBOT_MD_MODELS.MODEL_PARAMS IS 'Default model parameters (JSON, e.g., {"TEMPERATURE":0,"MAX_TOKENS":1024})';
COMMENT ON COLUMN KBOT_MD_MODELS.DESCS IS 'Detailed model description';
COMMENT ON COLUMN KBOT_MD_MODELS.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_MODELS.CREATED_TIME IS 'Creation time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_MODELS.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_MODELS.UPDATED_TIME IS 'Last update time (default: current system time)';


-- ###########################################################################
-- 7 KBOT_MD_SYS_CONF (System Configuration Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_SYS_CONF (
    CONF_ID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID       NUMBER NOT NULL ENABLE,
    PARAM_TYPE   NUMBER(2),
    PARAM_NAME   VARCHAR2(256),
    PARAM_VALUE  VARCHAR2(256),
    STATUS       NUMBER(1) DEFAULT 0,
    DESCS        VARCHAR2(512),
    CREATED_BY   VARCHAR2(512),
    CREATED_TIME DATE DEFAULT CURRENT_DATE,
    UPDATED_BY   VARCHAR2(512),
    UPDATED_TIME DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (CONF_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_SYS_CONF IS 'System Configuration Table - Stores various configuration parameters for the application';
-- Column comments
COMMENT ON COLUMN KBOT_MD_SYS_CONF.CONF_ID IS 'Unique configuration item identifier, primary key';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.PARAM_TYPE IS 'Parameter type enumeration';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.PARAM_NAME IS 'Parameter name (e.g., ImageToTextModel - Image to Text Model, SpeechToTextModel - Speech to Text Model)';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.PARAM_VALUE IS 'Parameter value';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.STATUS IS 'Configuration status: 1 - Enabled, 0 - Disabled';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.DESCS IS 'Detailed configuration item description';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.CREATED_TIME IS 'Creation time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.UPDATED_TIME IS 'Last update time (default: current system time)';


-- ###########################################################################
-- 8 KBOT_MD_AGENT (AI Agent Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_AGENT (
    AGENT_ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DOMAIN_ID               NUMBER,
    APP_ID                  NUMBER,
    AGENT_NAME              VARCHAR2(256),
    AGENT_DESC              VARCHAR2(512),
    WELCOME                 VARCHAR2(512),
    PROMPT_ID               NUMBER,
    MODELS                  JSON CHECK (MODELS IS JSON),
    CATEGORY                NUMBER(1,0) DEFAULT 0 NOT NULL,
    AGENT_STATUS            NUMBER(2),
    CREATED_BY              VARCHAR2(256),
    CREATED_TIME            DATE DEFAULT CURRENT_DATE,
    UPDATED_BY              VARCHAR2(256),
    UPDATED_TIME            DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (AGENT_ID) USING INDEX ENABLE
);

-- Unique index for (DOMAIN_ID, APP_ID, AGENT_NAME)
CREATE UNIQUE INDEX KBOT_MD_AGENT_UIDX ON KBOT_MD_AGENT (DOMAIN_ID, APP_ID, AGENT_NAME);

-- Table comment
COMMENT ON TABLE KBOT_MD_AGENT IS 'AI Agent Table - Stores agent configuration information';
-- Column comments
COMMENT ON COLUMN KBOT_MD_AGENT.AGENT_ID IS 'Primary key ID';
COMMENT ON COLUMN KBOT_MD_AGENT.DOMAIN_ID IS 'Associated business domain ID';
COMMENT ON COLUMN KBOT_MD_AGENT.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_AGENT.AGENT_NAME IS 'Agent name';
COMMENT ON COLUMN KBOT_MD_AGENT.AGENT_DESC IS 'Agent description';
COMMENT ON COLUMN KBOT_MD_AGENT.WELCOME IS 'Welcome message';
COMMENT ON COLUMN KBOT_MD_AGENT.PROMPT_ID IS 'Prompt ID';
COMMENT ON COLUMN KBOT_MD_AGENT.MODELS IS 'Models JSON';
COMMENT ON COLUMN KBOT_MD_AGENT.AGENT_STATUS IS 'Status: 1 - NEW, 2 - ENABLED, 3 - DISABLED, 4 - ARCHIVED';
COMMENT ON COLUMN KBOT_MD_AGENT.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_AGENT.CREATED_TIME IS 'Creation time';
COMMENT ON COLUMN KBOT_MD_AGENT.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_AGENT.UPDATED_TIME IS 'Last update time';

-- ###########################################################################
-- 9 KBOT_MD_AGENT_CONF (AI Agent KB Configuration Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_AGENT_CONF (
    CONF_ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID                 NUMBER,
    AGENT_ID               NUMBER,
    TOOL_ID                NUMBER,
    TOOL_TYPE              NUMBER(2),
    TOOL_WEIGHT            NUMBER(2,2),
    RERANKER_FLAG          NUMBER(1),
    SEARCH_TYPE            NUMBER(2),
    SEARCH_TOPK            NUMBER,
    SEARCH_SCORE_THRESHOLD NUMBER,
    CREATED_BY             VARCHAR2(256),
    CREATED_TIME           DATE DEFAULT CURRENT_DATE,
    UPDATED_BY             VARCHAR2(256),
    UPDATED_TIME           DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (CONF_ID) USING INDEX ENABLE,
    -- Unique constraint
    CONSTRAINT KBOT_MD_AGENT_CONF_CON UNIQUE (AGENT_ID, TOOL_ID, SEARCH_TYPE, APP_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_AGENT_CONF IS 'AI Agent KB Configuration Table - Stores association between agents and knowledge bases';
-- Column comments
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.CONF_ID IS 'Primary key ID';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.AGENT_ID IS 'AI agent ID';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.TOOL_ID IS 'KB ID / FUNC_ID etc.';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.TOOL_TYPE IS 'Tool type enumeration';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.TOOL_WEIGHT IS 'KB retrieval weight (0.00-1.00)';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.RERANKER_FLAG IS 'Reranking required: 1 - Yes, 0 - No';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.SEARCH_TYPE IS 'Search type enumeration';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.SEARCH_TOPK IS 'Number of search results to retrieve (TOPK)';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.SEARCH_SCORE_THRESHOLD IS 'Search similarity threshold';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.CREATED_TIME IS 'Creation time';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.UPDATED_TIME IS 'Last update time';

-- ###########################################################################
-- 10 KBOT_MD_DATA_DIC (Data Dictionary Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_DATA_DIC (
    DIC_ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID              NUMBER,
    NAME                VARCHAR2(256),
    DISPLAY_NAME        VARCHAR2(256),
    RETURN_VALUE        VARCHAR2(256),
    LANG_CODE           VARCHAR2(256),
    DISPLAY_TRAN_VALUE  VARCHAR2(256),
    STATUS              NUMBER(1) DEFAULT 0,
    IS_DEFAULT          NUMBER(1) DEFAULT 0,
    DESCS               VARCHAR2(256),
    CREATED_BY          VARCHAR2(256),
    CREATED_TIME        DATE DEFAULT CURRENT_DATE,
    UPDATED_BY          VARCHAR2(256),
    UPDATED_TIME        DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (DIC_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_DATA_DIC IS 'Data Dictionary Table - Stores key-value pairs for system enumerations and translations';
-- Column comments
COMMENT ON COLUMN KBOT_MD_DATA_DIC.DIC_ID IS 'Primary key ID';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.NAME IS 'Data dictionary name';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.DISPLAY_NAME IS 'Display name';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.RETURN_VALUE IS 'Return value';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.LANG_CODE IS 'Language code (e.g., zh-CN, en-US)';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.DISPLAY_TRAN_VALUE IS 'Multi-language display value';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.STATUS IS 'Status: 1 - Enabled, 0 - Disabled';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.IS_DEFAULT IS 'Default flag: 1 - Yes, 0 - No';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.DESCS IS 'Description';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.CREATED_TIME IS 'Creation time';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.UPDATED_TIME IS 'Last update time';

-- ###########################################################################
-- 11 KBOT_MD_RELEASE_NOTE (Release Notes Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_RELEASE_NOTE (
    RELEASE_ID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID          NUMBER,
    RELEASE_TITLE   VARCHAR2(256),
    RELEASE_CONTENT VARCHAR2(4000),
    CREATED_BY      VARCHAR2(256),
    CREATED_TIME    DATE DEFAULT CURRENT_DATE,
    UPDATED_BY      VARCHAR2(256),
    UPDATED_TIME    DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (RELEASE_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_RELEASE_NOTE IS 'Release Notes Table - Stores version release information and changelogs';
-- Column comments
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.RELEASE_ID IS 'Primary key ID';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.RELEASE_TITLE IS 'Release note title';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.RELEASE_CONTENT IS 'Release note content';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.CREATED_TIME IS 'Creation time';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.UPDATED_TIME IS 'Last update time';

-- ###########################################################################
-- 12 KBOT_MD_ACTION_RECORD (System Action Record Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_ACTION_RECORD (
    RECORD_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID       NUMBER,
    FUNC_NAME    VARCHAR2(100),
    ACTION       VARCHAR2(4000),
    CREATED_BY   VARCHAR2(256),
    CREATED_TIME DATE DEFAULT CURRENT_DATE,
    UPDATED_BY   VARCHAR2(256),
    UPDATED_TIME DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    CONSTRAINT PK_KBOT_MD_ACTION_RECORD PRIMARY KEY (RECORD_ID)
);

-- Table comment
COMMENT ON TABLE KBOT_MD_ACTION_RECORD IS 'System Action Record Table - Logs all user operations in the application';
-- Column comments
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.RECORD_ID IS 'Record ID, primary key';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.FUNC_NAME IS 'Function name related to the operation';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.ACTION IS 'Operation type (Create/Edit/Delete etc.)';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.CREATED_BY IS 'Operation executor';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.CREATED_TIME IS 'Operation time (default: current time)';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.UPDATED_TIME IS 'Last update time (default: current time)';

-- ###########################################################################
-- 13 KBOT_BIZ_TXT_EMBEDDING (Text Embedding Table)
-- ###########################################################################
CREATE TABLE KBOT_BIZ_TXT_EMBEDDING (
    CHUNK_ID        VARCHAR2(256) NOT NULL,
    KB_ID           NUMBER NOT NULL,
    FILE_ID         VARCHAR2(256) NOT NULL,
    CHUNK_NUM       NUMBER NOT NULL,
    CHUNK_TYPE      VARCHAR2(20),
    CONTENT         CLOB NOT NULL,
    HEADER          VARCHAR2(256),
    DOC_SUMMARY     VARCHAR2(4000),
    SEARCH_HELPER   VARCHAR2(4000),
    EMBEDDING       VECTOR NOT NULL,
    CHUNK_METADATA  JSON NOT NULL,
    SECURITY_LEVEL  NUMBER(1,0),
    IS_ACTIVE       NUMBER(1) DEFAULT 1,
    BIZ_METADATA    JSON,
    -- Primary key constraint
    PRIMARY KEY (CHUNK_ID) USING INDEX ENABLE
);
-- GRANT EXECUTE ON CTXSYS.CTX_DDL TO youruser;
-- BEGIN
--   CTX_DDL.CREATE_PREFERENCE('chinese_lexer', 'CHINESE_VGRAM_LEXER');
-- END;
-- /
CREATE INDEX IDX_FULLSEARCH_TXT_EMBEDDING ON  KBOT_BIZ_TXT_EMBEDDING("CONTENT") INDEXTYPE IS "CTXSYS"."CONTEXT" PARAMETERS ('lexer chinese_lexer');
CREATE INDEX IDX_FULLSEARCH_TXT_HEADER ON  KBOT_BIZ_TXT_EMBEDDING("HEADER") INDEXTYPE IS "CTXSYS"."CONTEXT" PARAMETERS ('lexer chinese_lexer');
CREATE INDEX IDX_FULLSEARCH_TXT_SEARCH_HELPER ON  KBOT_BIZ_TXT_EMBEDDING("SEARCH_HELPER") INDEXTYPE IS "CTXSYS"."CONTEXT" PARAMETERS ('lexer chinese_lexer');
-- Table comment
COMMENT ON TABLE KBOT_BIZ_TXT_EMBEDDING IS 'Text Embedding Table - Stores vectorized representations of text chunks';
-- Column comments
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.CHUNK_ID IS 'Unique vector record identifier, primary key';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.KB_ID IS 'Associated KB ID';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.FILE_ID IS 'Associated file ID';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.CHUNK_NUM IS 'Chunk number';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.CHUNK_TYPE IS 'Chunk type (text, table, picture, slide)';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.CONTENT IS 'Original text chunk content';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.HEADER IS 'Title of the text chunk';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.DOC_SUMMARY IS 'Summary of the document';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.SEARCH_HELPER IS 'Helper for search optimization';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.EMBEDDING IS 'Vector embedding of text chunk';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.CHUNK_METADATA IS 'Text chunk metadata (JSON, includes source path, file type etc.)';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.SECURITY_LEVEL IS 'File security level enumeration';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.IS_ACTIVE IS 'Embedding status: 1 - Active, 0 - Inactive';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.BIZ_METADATA IS 'Business metadata (JSON)';

-- ###########################################################################
-- API Security Related Tables
-- ###########################################################################
CREATE TABLE kbot_sys_auth (
    id              NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50) NOT NULL,
    email           VARCHAR2(100) NOT NULL,
    hashed_password VARCHAR2(255) NOT NULL,
    is_active       NUMBER(1,0) DEFAULT 1,
    is_superuser    NUMBER(1,0) DEFAULT 0,
    last_login_at   TIMESTAMP,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    -- Unique constraints
    CONSTRAINT uk_kbot_sys_auth_username UNIQUE (username),
    CONSTRAINT uk_kbot_sys_auth_email UNIQUE (email)
);

COMMENT ON TABLE kbot_sys_auth IS 'User Authentication Table - Stores user account information and credentials';
COMMENT ON COLUMN kbot_sys_auth.id IS 'User ID, primary key';
COMMENT ON COLUMN kbot_sys_auth.username IS 'Unique username (50 chars max)';
COMMENT ON COLUMN kbot_sys_auth.email IS 'Unique email address (100 chars max)';
COMMENT ON COLUMN kbot_sys_auth.hashed_password IS 'BCrypt hashed password';
COMMENT ON COLUMN kbot_sys_auth.is_active IS 'Account status: 1 - Active, 0 - Inactive';
COMMENT ON COLUMN kbot_sys_auth.is_superuser IS 'Superuser flag: 1 - Yes, 0 - No';
COMMENT ON COLUMN kbot_sys_auth.last_login_at IS 'Last login timestamp';
COMMENT ON COLUMN kbot_sys_auth.created_at IS 'Account creation timestamp';
COMMENT ON COLUMN kbot_sys_auth.updated_at IS 'Last account update timestamp';

CREATE TABLE kbot_sys_auth_token (
    id            NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti           VARCHAR2(36) NOT NULL,
    user_id       NUMBER(38,0) NOT NULL,
    device_info   VARCHAR2(200),
    ip_address    VARCHAR2(45),
    user_agent    VARCHAR2(500),
    status        VARCHAR2(20) DEFAULT 'ACTIVE',
    expires_at    TIMESTAMP NOT NULL,
    revoked_reason VARCHAR2(200),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    revoked_at    TIMESTAMP,
    -- Unique constraint
    CONSTRAINT uk_kbot_sys_auth_token_jti UNIQUE (jti)
);

-- Indexes
CREATE INDEX idx_kbot_sys_auth_token_user_status ON kbot_sys_auth_token(user_id, status, expires_at);

COMMENT ON TABLE kbot_sys_auth_token IS 'User Token Table - Stores JWT tokens for user authentication';
COMMENT ON COLUMN kbot_sys_auth_token.id IS 'Token ID, primary key';
COMMENT ON COLUMN kbot_sys_auth_token.jti IS 'JWT ID (unique token identifier)';
COMMENT ON COLUMN kbot_sys_auth_token.user_id IS 'Associated user ID';
COMMENT ON COLUMN kbot_sys_auth_token.device_info IS 'Device information (200 chars max)';
COMMENT ON COLUMN kbot_sys_auth_token.ip_address IS 'Client IP address (IPv4/IPv6 compatible)';
COMMENT ON COLUMN kbot_sys_auth_token.user_agent IS 'Client user agent string (500 chars max)';
COMMENT ON COLUMN kbot_sys_auth_token.status IS 'Token status: ACTIVE/REVOKED/EXPIRED';
COMMENT ON COLUMN kbot_sys_auth_token.expires_at IS 'Token expiration timestamp';
COMMENT ON COLUMN kbot_sys_auth_token.revoked_reason IS 'Reason for revocation (if applicable)';
COMMENT ON COLUMN kbot_sys_auth_token.created_at IS 'Token creation timestamp';
COMMENT ON COLUMN kbot_sys_auth_token.revoked_at IS 'Token revocation timestamp (if applicable)';

CREATE TABLE kbot_sys_services (
    id            NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code  VARCHAR2(50) NOT NULL,
    name          VARCHAR2(100) NOT NULL,
    description   VARCHAR2(4000),
    service_type  VARCHAR2(20) DEFAULT 'INTERNAL',
    owner         VARCHAR2(100),
    contact_email VARCHAR2(100),
    is_active     NUMBER(1,0) DEFAULT 1,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,
    -- Unique constraint
    CONSTRAINT uk_kbot_sys_services_code UNIQUE (service_code)
);

-- Indexes
CREATE INDEX idx_kbot_sys_services_type ON kbot_sys_services(service_type);
CREATE INDEX idx_kbot_sys_services_active ON kbot_sys_services(is_active, service_code);

COMMENT ON TABLE kbot_sys_services IS 'Service Table - Stores API service definitions';
COMMENT ON COLUMN kbot_sys_services.id IS 'Service ID, primary key';
COMMENT ON COLUMN kbot_sys_services.service_code IS 'Unique service code (50 chars max)';
COMMENT ON COLUMN kbot_sys_services.name IS 'Service display name (100 chars max)';
COMMENT ON COLUMN kbot_sys_services.description IS 'Detailed service description (4000 chars max)';
COMMENT ON COLUMN kbot_sys_services.service_type IS 'Service type: INTERNAL/EXTERNAL/THIRD_PARTY';
COMMENT ON COLUMN kbot_sys_services.owner IS 'Service owner name (100 chars max)';
COMMENT ON COLUMN kbot_sys_services.contact_email IS 'Service contact email (100 chars max)';
COMMENT ON COLUMN kbot_sys_services.is_active IS 'Service status: 1 - Active, 0 - Inactive';
COMMENT ON COLUMN kbot_sys_services.created_at IS 'Service creation timestamp';
COMMENT ON COLUMN kbot_sys_services.updated_at IS 'Last service update timestamp';

CREATE TABLE kbot_sys_api_keys (
    id              NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id          VARCHAR2(50) NOT NULL,
    hashed_key      VARCHAR2(255) NOT NULL,
    key_prefix      VARCHAR2(8) NOT NULL,
    name            VARCHAR2(100) NOT NULL,
    service_id      NUMBER(38,0) NOT NULL,
    scopes          VARCHAR2(4000) DEFAULT '[]',
    status          VARCHAR2(20) DEFAULT 'ACTIVE',
    expires_at      TIMESTAMP,
    last_used_at    TIMESTAMP,
    usage_count     NUMBER(38,0) DEFAULT 0,
    allowed_ips     VARCHAR2(4000) DEFAULT '[]',
    rate_limit      NUMBER(38,0) DEFAULT 0,
    created_by      VARCHAR2(50),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    revoked_reason  VARCHAR2(500),
    revoked_at      TIMESTAMP,
    -- Unique constraint
    CONSTRAINT uk_kbot_sys_api_keys_key_id UNIQUE (key_id)
);
-- Indexes
CREATE INDEX idx_kbot_sys_api_keys_active ON kbot_sys_api_keys(service_id, status, expires_at);
CREATE INDEX IDX_API_KEYS_SERVICE_ID ON kbot_sys_api_keys(service_id);

COMMENT ON TABLE kbot_sys_api_keys IS 'API Key Table - Stores API keys for service authentication';
COMMENT ON COLUMN kbot_sys_api_keys.id IS 'API key ID, primary key';
COMMENT ON COLUMN kbot_sys_api_keys.key_id IS 'Unique API key ID (50 chars max)';
COMMENT ON COLUMN kbot_sys_api_keys.hashed_key IS 'Hashed API secret key (BCrypt)';
COMMENT ON COLUMN kbot_sys_api_keys.key_prefix IS 'API key prefix (8 chars max)';
COMMENT ON COLUMN kbot_sys_api_keys.name IS 'API key display name (100 chars max)';
COMMENT ON COLUMN kbot_sys_api_keys.service_id IS 'Associated service ID';
COMMENT ON COLUMN kbot_sys_api_keys.scopes IS 'API access scopes (JSON array)';
COMMENT ON COLUMN kbot_sys_api_keys.status IS 'API key status: ACTIVE/REVOKED/EXPIRED';
COMMENT ON COLUMN kbot_sys_api_keys.expires_at IS 'API key expiration timestamp (null = never expires)';
COMMENT ON COLUMN kbot_sys_api_keys.last_used_at IS 'Last API key usage timestamp';
COMMENT ON COLUMN kbot_sys_api_keys.usage_count IS 'Total API key usage count';
COMMENT ON COLUMN kbot_sys_api_keys.allowed_ips IS 'Allowed IP addresses (JSON array, null = all IPs allowed)';
COMMENT ON COLUMN kbot_sys_api_keys.rate_limit IS 'API rate limit (requests per minute, 0 = unlimited)';
COMMENT ON COLUMN kbot_sys_api_keys.created_by IS 'API key creator username (50 chars max)';
COMMENT ON COLUMN kbot_sys_api_keys.created_at IS 'API key creation timestamp';
COMMENT ON COLUMN kbot_sys_api_keys.updated_at IS 'Last API key update timestamp';
COMMENT ON COLUMN kbot_sys_api_keys.revoked_reason IS 'Reason for revocation (500 chars max)';
COMMENT ON COLUMN kbot_sys_api_keys.revoked_at IS 'API key revocation timestamp (if applicable)';

--###########################################################################
-- KBOT Memory Related Tables
--###########################################################################
-- 1. User Profile Table
CREATE TABLE kbot_md_user_profile (
    user_id VARCHAR2(256) PRIMARY KEY,
    global_preferences JSON CHECK (global_preferences IS JSON),
    frequent_entities JSON CHECK (frequent_entities IS JSON),
    profile_summary CLOB,
    entity_relations JSON CHECK (entity_relations IS JSON),
    correction_history JSON CHECK (correction_history IS JSON),
    last_update_time TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE kbot_md_user_profile IS 'Stores long-term user characteristics and technical preferences across sessions';
COMMENT ON COLUMN kbot_md_user_profile.user_id IS 'Unique identifier for the user';
COMMENT ON COLUMN kbot_md_user_profile.global_preferences IS 'Persistent technical stack preferences';
COMMENT ON COLUMN kbot_md_user_profile.entity_relations IS 'Entity relations (e.g., project dependencies) (JSON array)';
COMMENT ON COLUMN kbot_md_user_profile.frequent_entities IS 'Frequently occurring entities (e.g., project names, IPs)';
COMMENT ON COLUMN kbot_md_user_profile.profile_summary IS 'LLM-generated user behavior summary';
COMMENT ON COLUMN kbot_md_user_profile.correction_history IS 'Correction history (JSON array)';

-- 2. Conversation Context Table
CREATE TABLE kbot_md_conv_context (
    session_id VARCHAR2(256) PRIMARY KEY,
    user_id VARCHAR2(256) NOT NULL,
    session_title VARCHAR2(256),
    app_id NUMBER(38, 0) NOT NULL,
    agent_id NUMBER NOT NULL,
    session_state JSON CHECK (session_state IS JSON),
    context_summary CLOB,
    interaction_count NUMBER DEFAULT 0,
    current_plan JSON CHECK (current_plan IS JSON),
    step_outputs JSON CHECK (step_outputs IS JSON),
    last_relevance_score NUMBER(2,1),
    active_topic VARCHAR2(512),
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_active_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE kbot_md_conv_context IS 'Manages active session states and rolling conversation summaries';
COMMENT ON COLUMN kbot_md_conv_context.session_state IS 'Current active state machine parameters';
COMMENT ON COLUMN kbot_md_conv_context.context_summary IS 'Short-to-medium term rolling summary';
COMMENT ON COLUMN kbot_md_conv_context.interaction_count IS 'Total number of interactions in this session';
COMMENT ON COLUMN kbot_md_conv_context.current_plan IS 'Current plan for this conversation';
COMMENT ON COLUMN kbot_md_conv_context.step_outputs IS 'Step outputs for this conversation';
COMMENT ON COLUMN kbot_md_conv_context.last_relevance_score IS 'Last relevance score for this conversation';
COMMENT ON COLUMN kbot_md_conv_context.active_topic IS 'Active topic for this conversation';

-- 3. Memory Entry Table
CREATE TABLE kbot_md_memory_entry (
    entry_id VARCHAR2(256) PRIMARY KEY,
    user_id VARCHAR2(256) NOT NULL,
    session_id VARCHAR2(256) NOT NULL,
    standalone_query CLOB,
    search_keywords VARCHAR2(1000),
    memory_vector VECTOR,
    memory_summary CLOB,
    turn_entities JSON CHECK (turn_entities IS JSON),
    raw_question CLOB NOT NULL,
    answer CLOB,
    thought CLOB,
    current_plan JSON CHECK (current_plan IS JSON),
    reasoning_path JSON CHECK (reasoning_path IS JSON),
    turn_type VARCHAR2(64),
    blocks JSON CHECK (blocks IS JSON),
    intent_category VARCHAR2(64),
    feedback NUMBER(1, 0) DEFAULT 0,
    request_time TIMESTAMP(6) WITH TIME ZONE,
    response_time TIMESTAMP(6) WITH TIME ZONE
);

-- Optional: Create an HNSW vector index for high-performance memory recall
-- CREATE VECTOR INDEX idx_mem_vector_hnsw ON kbot_md_memory_entry(memory_vector) 
-- ORGANIZATION INMEMORY NEIGHBOR GRAPH DISTANCE COSINE;

COMMENT ON TABLE kbot_md_memory_entry IS 'Records atomic QA interactions with semantic vectors and state snapshots';
COMMENT ON COLUMN kbot_md_memory_entry.standalone_query IS 'Context-enriched rewritten question';
COMMENT ON COLUMN kbot_md_memory_entry.search_keywords IS 'Extracted keywords and synonyms for hybrid search';
COMMENT ON COLUMN kbot_md_memory_entry.memory_vector IS 'Semantic vector of the query for long-term recall';
COMMENT ON COLUMN kbot_md_memory_entry.turn_entities IS 'Entity snapshot for this specific turn';
COMMENT ON COLUMN kbot_md_memory_entry.intent_category IS 'Intent category for this turn';
COMMENT ON COLUMN kbot_md_memory_entry.feedback IS 'User feedback for this turn, -1: bad, 0: neutral, 1: good';
COMMENT ON COLUMN kbot_md_memory_entry.thought IS 'Thought process for this turn';
COMMENT ON COLUMN kbot_md_memory_entry.current_plan IS 'Current plan for this turn';
COMMENT ON COLUMN kbot_md_memory_entry.reasoning_path IS 'Reasoning path for this turn';
COMMENT ON COLUMN kbot_md_memory_entry.turn_type IS 'Turn of the conversation, e.g., user, assistant, system';
COMMENT ON COLUMN kbot_md_memory_entry.blocks IS 'Blocks for this turn';


CREATE TABLE kbot_md_parser_conf (
    parser_conf_id NUMBER(38, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    domain_id NUMBER(38, 0),
    engine VARCHAR2(10),
    parser_params JSON,
    created_by VARCHAR2(256),
    created_time DATE DEFAULT CURRENT_DATE,
    updated_by VARCHAR2(256),
    updated_time DATE DEFAULT CURRENT_DATE,
    CONSTRAINT uk_kbot_md_parser_conf_domain_id UNIQUE (domain_id, engine)
);

-- 添加字段注释
COMMENT ON COLUMN kbot_md_parser_conf.parser_conf_id IS '自增ID，主键';
COMMENT ON COLUMN kbot_md_parser_conf.domain_id IS 'Domain ID, referencing domain table';
COMMENT ON COLUMN kbot_md_parser_conf.engine IS 'Parser engine：Enum：ParserEngine';
COMMENT ON COLUMN kbot_md_parser_conf.parser_params IS 'Parser parameters';
COMMENT ON COLUMN kbot_md_parser_conf.created_by IS 'Creator user';
COMMENT ON COLUMN kbot_md_parser_conf.created_time IS 'Creation time';
COMMENT ON COLUMN kbot_md_parser_conf.updated_by IS 'Updater user';
COMMENT ON COLUMN kbot_md_parser_conf.updated_time IS 'Update time';



-- ========================================================
-- 1. 顶点表 (KBOT_GRAPH_KNOWLEDGE_VERTICES) 
-- ========================================================
CREATE TABLE KBOT_GRAPH_KNOWLEDGE_VERTICES (
    kb_id          NUMBER(38,0) NOT NULL,
    vertex_id      VARCHAR2(64) NOT NULL,
    vertex_name    VARCHAR2(255) NOT NULL,
    vertex_type    VARCHAR2(64) NOT NULL,
    description    CLOB,
    attributes     JSON,
    name_vector    VECTOR,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT pk_kbot_graph_knowledge_vertices PRIMARY KEY (kb_id, vertex_id)
);
-- 为实体名称和类型建立索引，加速传统检索
CREATE INDEX idx_vertex_name ON KBOT_GRAPH_KNOWLEDGE_VERTICES(kb_id, vertex_name);


COMMENT ON TABLE KBOT_GRAPH_KNOWLEDGE_VERTICES IS '知识图谱顶点表（实体表）：存储从非结构化文档中抽取的业务实体、术语或概念，并支持向量消歧。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_VERTICES.kb_id IS '知识库ID，引用知识库表。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_VERTICES.vertex_id IS '顶点（实体）的唯一标识。推荐使用名称+类型的规范化哈希值（如MD5），以天然实现初级消歧。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_VERTICES.vertex_name IS '实体或概念的实际名称（如"RTX 5080"、"晶圆厚度"）。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_VERTICES.vertex_type IS '实体的业务大类分类（如：技术、设备、指标、组织、概念等）。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_VERTICES.description IS 'LLM 对该实体在上下文中提炼的简要文本定义或描述。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_VERTICES.attributes IS 'JSON 格式的动态扩展属性，用于存储 LLM 针对特定实体类型抽取的个性化非固定字段（如设备的型号、指标的单位等）。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_VERTICES.name_vector IS '基于实体名称/描述生成的原生向量嵌入（Vector Embeddings），用于支持向量相似度检索以及高级实体对齐与合并（消歧）。';


-- ========================================================
-- 2. 边表 (KBOT_GRAPH_KNOWLEDGE_EDGES) 
-- ========================================================
CREATE TABLE KBOT_GRAPH_KNOWLEDGE_EDGES (
    kb_id          NUMBER(38,0) NOT NULL,
    source_id      VARCHAR2(64) NOT NULL,
    target_id      VARCHAR2(64) NOT NULL,
    relation_type  VARCHAR2(128) NOT NULL,
    weight         NUMBER(10) DEFAULT 1,
    attributes     JSON,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT pk_graph_knowledge_edges PRIMARY KEY (kb_id, edge_id),
    CONSTRAINT fk_edge_source FOREIGN KEY (kb_id, source_id) REFERENCES KBOT_GRAPH_KNOWLEDGE_VERTICES(kb_id, vertex_id) ON DELETE CASCADE,
    CONSTRAINT fk_edge_target FOREIGN KEY (kb_id, target_id) REFERENCES KBOT_GRAPH_KNOWLEDGE_VERTICES(kb_id, vertex_id) ON DELETE CASCADE
);

CREATE INDEX idx_edge_source_target ON KBOT_GRAPH_KNOWLEDGE_EDGES(source_id, target_id);

COMMENT ON TABLE KBOT_GRAPH_KNOWLEDGE_EDGES IS '知识图谱边表（关系表）：存储实体与实体之间的有向关系，通过权重记录关系的业务强弱和提及频次。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_EDGES.kb_id IS '知识库ID，引用知识库表。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_EDGES.edge_id IS '边的唯一标识。推荐由源节点ID、目标节点ID和关系类型进行组合哈希生成。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_EDGES.source_id IS '关系的源顶点ID（起点），对应 KNOWLEDGE_VERTICES 的主键。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_EDGES.target_id IS '关系的目标顶点ID（终点），对应 KNOWLEDGE_VERTICES 的主键。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_EDGES.relation_type IS '关系的语义类型（如：属于、导致、测量、引发、集成于等动宾短语或逻辑关系）。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_EDGES.weight IS '关系权重值。若在多个切片中重复抽取到完全相同的边，则此数值递增，数值越大表示该关系在知识库中越核心或被提及越多。';
COMMENT ON COLUMN KBOT_GRAPH_KNOWLEDGE_EDGES.attributes IS 'JSON 格式的动态扩展属性，存储该条边（关系）特有的附加信息。';



-- ========================================================
-- 3. 关系-切片映射表 (KBOT_GRAPH_EDGE_CHUNK_MAP) 
-- ========================================================
CREATE TABLE KBOT_GRAPH_EDGE_CHUNK_MAP (
    kb_id          NUMBER(38,0) NOT NULL,
    edge_id        VARCHAR2(64) NOT NULL,
    chunk_id       VARCHAR2(64) NOT NULL,
    file_id        VARCHAR2(64),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT pk_graph_edge_chunk_map PRIMARY KEY (kb_id, edge_id, chunk_id),
    CONSTRAINT fk_map_edge FOREIGN KEY (kb_id, edge_id) REFERENCES KBOT_GRAPH_KNOWLEDGE_EDGES(kb_id, edge_id) ON DELETE CASCADE
);

CREATE INDEX idx_map_chunk ON KBOT_GRAPH_EDGE_CHUNK_MAP(chunk_id);

COMMENT ON TABLE KBOT_GRAPH_EDGE_CHUNK_MAP IS '图关系与文档切片映射表（中间关联表）：记录每条关系是由哪些具体的文档切片抽取得来的，是图搜索 Skill 溯源到原文 Chunk 的核心依赖。';
COMMENT ON COLUMN KBOT_GRAPH_EDGE_CHUNK_MAP.kb_id IS '知识库ID，引用知识库表。';
COMMENT ON COLUMN KBOT_GRAPH_EDGE_CHUNK_MAP.edge_id IS '边（关系）的唯一标识，对应 KBOT_GRAPH_KNOWLEDGE_EDGES 的主键。';
COMMENT ON COLUMN KBOT_GRAPH_EDGE_CHUNK_MAP.chunk_id IS '提取出该条关系的原始文档切片ID。对应 Vector DB 或系统其他业务表中的 Chunk ID，用于顺藤摸瓜检索原文。';
COMMENT ON COLUMN KBOT_GRAPH_EDGE_CHUNK_MAP.file_id IS '冗余存储的文档唯一标识，方便在用户删除或更新整个文档时进行级联数据清理。';



-- create graph
DROP PROPERTY GRAPH kbot_knowledge_rag_graph;

CREATE PROPERTY GRAPH kbot_knowledge_rag_graph
    VERTEX TABLES (
        KBOT_GRAPH_KNOWLEDGE_VERTICES
            KEY (vertex_id)
            LABEL vertex
            PROPERTIES (kb_id, vertex_id, vertex_name, vertex_type, description, attributes)
    )
    EDGE TABLES (
        KBOT_GRAPH_KNOWLEDGE_EDGES
            KEY (edge_id)
            SOURCE KEY (source_id) REFERENCES KBOT_GRAPH_KNOWLEDGE_VERTICES(vertex_id)
            DESTINATION KEY (target_id) REFERENCES KBOT_GRAPH_KNOWLEDGE_VERTICES(vertex_id)
            LABEL connects_to
            PROPERTIES (kb_id, edge_id, relation_type, weight, attributes)
    );


-- KBOT_OPS_DB_INSTANCE: 数据库实例资产配置表 (CMDB)
DROP TABLE IF EXISTS KBOT_OPS_DB_INSTANCE;
CREATE TABLE KBOT_OPS_DB_INSTANCE (
    instance_id    VARCHAR2(36) PRIMARY KEY,
    instance_name  VARCHAR2(128) NOT NULL,
    environment    VARCHAR2(16) DEFAULT 'dev',
    security_level NUMBER(1) DEFAULT 3,
    db_type        VARCHAR2(32) NOT NULL,
    version_code   NUMBER DEFAULT 0,
    charset        VARCHAR2(32) DEFAULT 'utf8mb4',
    host           VARCHAR2(256) NOT NULL,
    port           NUMBER(5) NOT NULL,
    service_name   VARCHAR2(128),
    database_name  VARCHAR2(128),
    dsn            VARCHAR2(512),
    db_role        VARCHAR2(32) DEFAULT 'primary',
    monitor_type   VARCHAR2(32) DEFAULT 'prometheus',
    prometheus_instance_label VARCHAR2(256),
    cluster_id     VARCHAR2(36),
    ops_user       VARCHAR2(64) NOT NULL,
    encrypted_password VARCHAR2(512) NOT NULL,
    secret_vault_key VARCHAR2(256),
    status         VARCHAR2(16) DEFAULT 'active',
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_instance_host_port UNIQUE (host, port),
    CONSTRAINT ck_ops_db_env CHECK (environment IN ('prod', 'stg', 'dev')),
    CONSTRAINT ck_ops_db_role CHECK (db_role IN ('primary', 'standby', 'cluster_node')),
    CONSTRAINT ck_ops_db_status CHECK (status IN ('active', 'maintenance', 'offline'))
);

COMMENT ON TABLE KBOT_OPS_DB_INSTANCE IS '智能运维线 - 物理与云端数据库实例资产配置表 (CMDB 核心表)';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.instance_id IS '运维全域唯一实例ID (UUID v7 格式)';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.instance_name IS '实例直观可读名称';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.environment IS '环境分级隔离策略: prod, stg, dev';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.security_level IS '安全控制等级, 数值越高触发变更自愈时的审批流越严格';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.db_type IS '数据库引擎内核类型: oracle, postgresql, mysql';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.version_code IS '精准内核版本数字代码, 例如: 26000000';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.host IS '物理机/虚拟机 IP 地址或高可用对外域名';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.port IS '数据库内核监听服务的物理端口号';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.db_role IS '物理角色: primary(主), standby(备), cluster_node';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.monitor_type IS '监控数据源类型: prometheus, zabbix, none';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.prometheus_instance_label IS '对应 Prometheus 采集时的 instance 标签值';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.ops_user IS '大模型运维通道专属的高权/监控账号';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.encrypted_password IS '经过强加密后的运维账号物理密码密文';
COMMENT ON COLUMN KBOT_OPS_DB_INSTANCE.status IS '生命周期状态: active, maintenance, offline';

-- KBOT_OPS_AGENT_CONF: 智能体与运维资产多对多绑定配置表
DROP TABLE IF EXISTS KBOT_OPS_AGENT_CONF;
CREATE TABLE KBOT_OPS_AGENT_CONF (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id             NUMBER NOT NULL,
    instance_id          VARCHAR2(36) NOT NULL,
    is_mutation_allowed  NUMBER(1) DEFAULT 0,
    require_approval     NUMBER(1) DEFAULT 1,
    max_daily_execution  NUMBER DEFAULT 10,
    created_by           VARCHAR2(64),
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by           VARCHAR2(64),
    updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_agent_ops UNIQUE (agent_id, instance_id),
    CONSTRAINT fk_agent_ops_agent FOREIGN KEY (agent_id) REFERENCES kbot_md_agent(agent_id),
    CONSTRAINT fk_agent_ops_instance FOREIGN KEY (instance_id) REFERENCES KBOT_OPS_DB_INSTANCE(instance_id)
);

COMMENT ON TABLE KBOT_OPS_AGENT_CONF IS '智能运维线 - 智能体与运维物理资产多对多动态绑定配置表';
COMMENT ON COLUMN KBOT_OPS_AGENT_CONF.id IS '关系配置自增 ID, 主键';
COMMENT ON COLUMN KBOT_OPS_AGENT_CONF.agent_id IS '关联的智能体 Agent ID (int, 对应 kbot_md_agent.agent_id)';
COMMENT ON COLUMN KBOT_OPS_AGENT_CONF.instance_id IS '关联的运维实例 ID (对应 KBOT_OPS_DB_INSTANCE.instance_id)';
COMMENT ON COLUMN KBOT_OPS_AGENT_CONF.is_mutation_allowed IS '是否允许执行变更动作(如 Kill/DDL)';
COMMENT ON COLUMN KBOT_OPS_AGENT_CONF.require_approval IS '是否必须触发人工审批门禁';
COMMENT ON COLUMN KBOT_OPS_AGENT_CONF.max_daily_execution IS '单日高危变更自愈动作上限频次';

