-- ==========================================
-- KBOT 3.4 HITL 人机协同 — 数据库变更脚本
-- 描述: 支持 AIOps Agent 多轮动态交互（中断-挂起-恢复）
-- 日期: 2026-07-02
-- ==========================================

-- ==========================================
-- 1. 新增表：kbot_ops_pending_request
-- ==========================================
CREATE TABLE kbot_ops_pending_request (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id          VARCHAR2(36) NOT NULL,
    session_id          VARCHAR2(64) NOT NULL,
    user_id             VARCHAR2(256) NOT NULL,
    agent_id            NUMBER NOT NULL,
    instance_id         VARCHAR2(36) NOT NULL,
    entry_id            VARCHAR2(36) NOT NULL,

    -- 挂起上下文 (给用户看的)
    suspend_reason      CLOB NOT NULL,
    user_prompt         CLOB NOT NULL,
    sql_to_run          CLOB,
    expected_fields     CLOB,

    -- 执行状态快照 (用于恢复)
    suspended_by_skill  VARCHAR2(128) NOT NULL,
    current_step_index  NUMBER DEFAULT 0,
    completed_steps     CLOB,
    accumulated_results CLOB,
    pending_variables   CLOB,
    hitl_history        CLOB,
    runtime_plan        CLOB,

    -- 生命周期管理
    status              VARCHAR2(16) DEFAULT 'pending',
    requested_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    responded_at        TIMESTAMP,
    timeout_at          TIMESTAMP,
    reminder_count      NUMBER DEFAULT 0,

    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pend_session FOREIGN KEY (session_id)
        REFERENCES kbot_md_conv_context(session_id),
    CONSTRAINT fk_pend_agent FOREIGN KEY (agent_id)
        REFERENCES kbot_md_agent(agent_id),
    CONSTRAINT fk_pend_instance FOREIGN KEY (instance_id)
        REFERENCES kbot_ops_db_instance(instance_id),
    CONSTRAINT ck_pend_status CHECK (status IN ('pending', 'answered', 'timeout', 'cancelled'))
);

CREATE INDEX idx_pend_session ON kbot_ops_pending_request(session_id, status);
CREATE INDEX idx_pend_timeout ON kbot_ops_pending_request(status, timeout_at);
CREATE INDEX idx_pend_request_id ON kbot_ops_pending_request(request_id);

COMMENT ON TABLE kbot_ops_pending_request IS 'AIOps HITL 挂起请求快照表: 存储 Agent 等待用户输入时的完整状态';
COMMENT ON COLUMN kbot_ops_pending_request.request_id IS '挂起请求唯一标识 (UUID v7)';
COMMENT ON COLUMN kbot_ops_pending_request.session_id IS '关联的会话 ID';
COMMENT ON COLUMN kbot_ops_pending_request.user_id IS '发起诊断的用户 ID';
COMMENT ON COLUMN kbot_ops_pending_request.agent_id IS '执行诊断的 Agent ID (int)';
COMMENT ON COLUMN kbot_ops_pending_request.instance_id IS '目标数据库实例 ID';
COMMENT ON COLUMN kbot_ops_pending_request.entry_id IS '原始 memory entry ID';
COMMENT ON COLUMN kbot_ops_pending_request.suspend_reason IS 'LLM 给出的挂起原因（用中文解释为什么需要用户协助）';
COMMENT ON COLUMN kbot_ops_pending_request.user_prompt IS '展示给用户的操作指引 (Markdown)';
COMMENT ON COLUMN kbot_ops_pending_request.sql_to_run IS 'LLM 生成的用户需执行的 SQL 语句（可一键复制）';
COMMENT ON COLUMN kbot_ops_pending_request.expected_fields IS 'JSON: 期望用户返回的字段列表, 前端据此动态渲染输入表单';
COMMENT ON COLUMN kbot_ops_pending_request.suspended_by_skill IS '触发挂起的 Skill 名称, 用于恢复时路由';
COMMENT ON COLUMN kbot_ops_pending_request.current_step_index IS '挂起时正在执行的步骤索引, 恢复时从此索引重新驱动 Skill';
COMMENT ON COLUMN kbot_ops_pending_request.completed_steps IS 'JSON: 已完成步骤的 execution_history';
COMMENT ON COLUMN kbot_ops_pending_request.accumulated_results IS 'JSON: 已采集的 metric/monitor/doc_results';
COMMENT ON COLUMN kbot_ops_pending_request.pending_variables IS 'JSON: ctx["variables"] 的快照';
COMMENT ON COLUMN kbot_ops_pending_request.hitl_history IS 'JSON: 完整的 HITL 多轮交互 Timeline, 恢复时注入 ctx';
COMMENT ON COLUMN kbot_ops_pending_request.runtime_plan IS 'JSON: ctx["runtime_plan"] 快照, 恢复时重建 ctx';
COMMENT ON COLUMN kbot_ops_pending_request.status IS '生命周期: pending=等待用户, answered=已处理, timeout=超时, cancelled=用户取消';
COMMENT ON COLUMN kbot_ops_pending_request.requested_at IS '挂起发起时间';
COMMENT ON COLUMN kbot_ops_pending_request.responded_at IS '用户回填时间';
COMMENT ON COLUMN kbot_ops_pending_request.timeout_at IS '超时时间（默认 +30 分钟）';
COMMENT ON COLUMN kbot_ops_pending_request.reminder_count IS '已发送催办次数';

-- ==========================================
-- 2. 表变更：kbot_md_conv_context
-- ==========================================
ALTER TABLE kbot_md_conv_context ADD (
    pending_request_id VARCHAR2(36),
    is_suspended       NUMBER(1) DEFAULT 0
);

COMMENT ON COLUMN kbot_md_conv_context.pending_request_id IS '当前活跃的挂起请求 ID, NULL = 无挂起';
COMMENT ON COLUMN kbot_md_conv_context.is_suspended IS '会话挂起标记: 0=正常运行, 1=等待用户输入中';
