-- KBot 4.0 Data Query：数据源引用平台数据库托管凭据。

CREATE TABLE KBOT_DQ_DATA_SOURCE (
    DATA_SOURCE_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    SOURCE_TYPE VARCHAR2(32 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'DRAFT' NOT NULL,
    CURRENT_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONFIGURATION_JSON JSON NOT NULL,
    CONFIGURATION_HASH VARCHAR2(64 CHAR) NOT NULL,
    CREDENTIAL_ID RAW(16) NOT NULL,
    CAPABILITIES_JSON JSON NOT NULL,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_DQ_SOURCE_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT UK_DQ_SOURCE_CRED UNIQUE (DATA_SOURCE_ID, CREDENTIAL_ID),
    CONSTRAINT CK_DQ_SOURCE_TYPE CHECK (SOURCE_TYPE IN ('ORACLE', 'POSTGRESQL', 'MYSQL')),
    CONSTRAINT CK_DQ_SOURCE_STATUS CHECK (STATUS IN ('DRAFT', 'VALIDATING', 'ACTIVE', 'FAILED', 'DISABLED')),
    CONSTRAINT CK_DQ_SOURCE_VERSION CHECK (CURRENT_VERSION >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_DQ_SOURCE_HASH CHECK (LENGTH(CONFIGURATION_HASH) = 64)
);

CREATE INDEX IX_DQ_SOURCE_SCOPE ON KBOT_DQ_DATA_SOURCE (DOMAIN_ID, STATUS, DATA_SOURCE_ID);

COMMENT ON COLUMN KBOT_DQ_DATA_SOURCE.CONFIGURATION_JSON IS
    '仅保存端点、TLS 和 Schema allowlist，不保存用户名或密码';
