-- KBot 4.0 Data Query：不可变 Schema Snapshot 与逐对象采集任务。

CREATE TABLE KBOT_DQ_SCHEMA_SNAPSHOT (
    SCHEMA_SNAPSHOT_ID RAW(16) PRIMARY KEY,
    DATA_SOURCE_ID RAW(16) NOT NULL,
    SOURCE_VERSION NUMBER(19) NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'REQUESTED' NOT NULL,
    SNAPSHOT_HASH VARCHAR2(64 CHAR) NOT NULL,
    CONNECTOR_TYPE VARCHAR2(32 CHAR) NOT NULL,
    CONNECTOR_VERSION VARCHAR2(64 CHAR) NOT NULL,
    CAPABILITIES_JSON JSON NOT NULL,
    OBJECTS_JSON JSON,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    REQUESTED_BY VARCHAR2(256 CHAR) NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_DQ_SNAPSHOT_STATUS CHECK (STATUS IN (
        'REQUESTED', 'DISCOVERING', 'WAITING_SELECTION', 'CAPTURING',
        'READY', 'PARTIAL_READY', 'FAILED', 'SUPERSEDED'
    )),
    CONSTRAINT CK_DQ_SNAPSHOT_VERSION CHECK (SOURCE_VERSION >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_DQ_SNAPSHOT_HASH CHECK (LENGTH(SNAPSHOT_HASH) = 64)
);

CREATE TABLE KBOT_DQ_SNAPSHOT_OBJECT (
    SCHEMA_SNAPSHOT_OBJECT_ID RAW(16) PRIMARY KEY,
    SCHEMA_SNAPSHOT_ID RAW(16) NOT NULL,
    SCHEMA_NAME VARCHAR2(128 CHAR) NOT NULL,
    OBJECT_NAME VARCHAR2(128 CHAR) NOT NULL,
    OBJECT_TYPE VARCHAR2(24 CHAR) NOT NULL,
    SELECTED NUMBER(1) DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'DISCOVERED' NOT NULL,
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    METADATA_SOURCE VARCHAR2(16 CHAR) DEFAULT 'AUTO' NOT NULL,
    METADATA_JSON JSON,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_DQ_SNAPSHOT_OBJECT UNIQUE (SCHEMA_SNAPSHOT_ID, SCHEMA_NAME, OBJECT_NAME),
    CONSTRAINT CK_DQ_OBJECT_TYPE CHECK (OBJECT_TYPE IN ('TABLE', 'VIEW')),
    CONSTRAINT CK_DQ_OBJECT_SELECTED CHECK (SELECTED IN (0, 1)),
    CONSTRAINT CK_DQ_OBJECT_STATUS CHECK (STATUS IN ('DISCOVERED', 'QUEUED', 'CAPTURING', 'READY', 'MANUAL', 'FAILED')),
    CONSTRAINT CK_DQ_OBJECT_ATTEMPT CHECK (ATTEMPT_COUNT BETWEEN 0 AND 3 AND ROW_VERSION >= 1)
);

CREATE INDEX IX_DQ_SNAPSHOT_SOURCE ON KBOT_DQ_SCHEMA_SNAPSHOT (DATA_SOURCE_ID, STATUS, CREATED_AT);
CREATE INDEX IX_DQ_OBJECT_CLAIM ON KBOT_DQ_SNAPSHOT_OBJECT (STATUS, UPDATED_AT);
