-- KBot 4.0 Data Query：语义模型、版本、生成任务和验证问题。

CREATE TABLE KBOT_DQ_SEMANTIC_MODEL (
    SEMANTIC_MODEL_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    ACTIVE_VERSION NUMBER(19),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_DQ_MODEL_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT CK_DQ_MODEL_VERSION CHECK (ROW_VERSION >= 1 AND (ACTIVE_VERSION IS NULL OR ACTIVE_VERSION >= 1))
);

CREATE TABLE KBOT_DQ_MODEL_VERSION (
    SEMANTIC_MODEL_VERSION_ID RAW(16) PRIMARY KEY,
    SEMANTIC_MODEL_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    DATA_SOURCE_ID RAW(16) NOT NULL,
    SCHEMA_SNAPSHOT_ID RAW(16) NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'DRAFT' NOT NULL,
    DEFINITION_JSON JSON NOT NULL,
    DEFINITION_HASH VARCHAR2(64 CHAR) NOT NULL,
    REVIEW_COMMENT CLOB,
    SUBMITTED_BY VARCHAR2(256 CHAR),
    REVIEWED_BY VARCHAR2(256 CHAR),
    PUBLISHED_BY VARCHAR2(256 CHAR),
    PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_DQ_MODEL_VERSION UNIQUE (SEMANTIC_MODEL_ID, VERSION_NO),
    CONSTRAINT CK_DQ_MODEL_V_STATUS CHECK (STATUS IN ('DRAFT', 'REVIEW', 'ACTIVE', 'REJECTED', 'RETIRED')),
    CONSTRAINT CK_DQ_MODEL_V_VERSION CHECK (VERSION_NO >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_DQ_MODEL_V_HASH CHECK (LENGTH(DEFINITION_HASH) = 64)
);

CREATE TABLE KBOT_DQ_MODEL_GEN_JOB (
    GENERATION_JOB_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    SCHEMA_SNAPSHOT_ID RAW(16) NOT NULL,
    REQUESTED_BY VARCHAR2(256 CHAR) NOT NULL,
    REQUEST_JSON JSON NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'QUEUED' NOT NULL,
    SEMANTIC_MODEL_ID RAW(16),
    SEMANTIC_MODEL_VERSION_ID RAW(16),
    ERROR_CODE VARCHAR2(128 CHAR),
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_DQ_GEN_STATUS CHECK (STATUS IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT CK_DQ_GEN_ATTEMPT CHECK (ATTEMPT_COUNT BETWEEN 0 AND 3 AND ROW_VERSION >= 1),
    CONSTRAINT CK_DQ_GEN_LEASE CHECK (
        (STATUS = 'RUNNING' AND LEASE_OWNER IS NOT NULL AND LEASE_TOKEN IS NOT NULL AND LEASE_UNTIL IS NOT NULL)
        OR (STATUS <> 'RUNNING')
    )
);

CREATE TABLE KBOT_DQ_VERIFIED_QUERY (
    VERIFIED_QUERY_ID RAW(16) PRIMARY KEY,
    SEMANTIC_MODEL_VERSION_ID RAW(16) NOT NULL,
    QUESTION CLOB NOT NULL,
    QUESTION_HASH VARCHAR2(64 CHAR) NOT NULL,
    QUERY_PLAN_JSON JSON NOT NULL,
    ASSERTION_JSON JSON NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'DRAFT' NOT NULL,
    VERIFIED_BY VARCHAR2(256 CHAR),
    VERIFIED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_DQ_VERIFIED_QUERY UNIQUE (SEMANTIC_MODEL_VERSION_ID, QUESTION_HASH),
    CONSTRAINT CK_DQ_VERIFIED_STATUS CHECK (STATUS IN ('DRAFT', 'VERIFIED', 'DISABLED')),
    CONSTRAINT CK_DQ_VERIFIED_HASH CHECK (LENGTH(QUESTION_HASH) = 64 AND ROW_VERSION >= 1)
);

CREATE INDEX IX_DQ_MODEL_SCOPE ON KBOT_DQ_SEMANTIC_MODEL (DOMAIN_ID, SEMANTIC_MODEL_ID);
CREATE INDEX IX_DQ_GEN_CLAIM ON KBOT_DQ_MODEL_GEN_JOB (STATUS, LEASE_UNTIL, CREATED_AT);
