-- KBot 4.0 Data Query：Domain 查询预算与 Agent 语义模型绑定。

CREATE TABLE KBOT_DQ_POLICY (
    POLICY_BINDING_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    SUBJECT_SELECTOR_JSON JSON NOT NULL,
    SEMANTIC_MODEL_IDS_JSON JSON NOT NULL,
    POLICY_JSON JSON NOT NULL,
    POLICY_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_DQ_POLICY_HASH UNIQUE (DOMAIN_ID, POLICY_HASH),
    CONSTRAINT CK_DQ_POLICY_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_DQ_POLICY_HASH CHECK (LENGTH(POLICY_HASH) = 64 AND ROW_VERSION >= 1)
);

CREATE TABLE KBOT_DQ_AGENT_BINDING (
    AGENT_BINDING_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    CONSUMER_APP_ID VARCHAR2(128 CHAR) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    AGENT_VERSION_ID RAW(16) NOT NULL,
    SEMANTIC_MODEL_ID RAW(16) NOT NULL,
    POLICY_BINDING_ID RAW(16) NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_DQ_BINDING_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_DQ_BINDING_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE UNIQUE INDEX UX_DQ_BINDING_ACTIVE ON KBOT_DQ_AGENT_BINDING (
    CASE WHEN STATUS = 'ACTIVE' THEN DOMAIN_ID END,
    CASE WHEN STATUS = 'ACTIVE' THEN CONSUMER_APP_ID END,
    CASE WHEN STATUS = 'ACTIVE' THEN AGENT_ID END,
    CASE WHEN STATUS = 'ACTIVE' THEN AGENT_VERSION_ID END,
    CASE WHEN STATUS = 'ACTIVE' THEN SEMANTIC_MODEL_ID END
);
CREATE INDEX IX_DQ_BINDING_AGENT ON KBOT_DQ_AGENT_BINDING (
    DOMAIN_ID, CONSUMER_APP_ID, AGENT_ID, AGENT_VERSION_ID, STATUS
);
