-- KBot 4.0 Data Query：受控查询 Run、执行租约、结果与事件。

CREATE TABLE KBOT_DQ_RUN (
    DATA_QUERY_RUN_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    CONSUMER_APP_ID VARCHAR2(128 CHAR) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    AGENT_VERSION_ID RAW(16) NOT NULL,
    PARENT_AGENT_RUN_ID RAW(16),
    PARENT_AGENT_TASK_ID RAW(16),
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    REQUEST_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
    ORIGINAL_QUESTION CLOB NOT NULL,
    STANDALONE_QUERY CLOB NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'CREATED' NOT NULL,
    PLAN_SNAPSHOT_JSON JSON,
    POLICY_SNAPSHOT_JSON JSON,
    SEMANTIC_MODEL_SNAPSHOT_JSON JSON,
    DEADLINE_AT TIMESTAMP(6) WITH TIME ZONE,
    CANCEL_REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_DQ_RUN_IDEMPOTENCY UNIQUE (DOMAIN_ID, ACTOR_ID, IDEMPOTENCY_KEY),
    CONSTRAINT CK_DQ_RUN_STATUS CHECK (STATUS IN (
        'CREATED', 'VALIDATING', 'CLARIFICATION_REQUIRED', 'PREFLIGHT', 'QUEUED',
        'EXECUTING', 'COMPLETED', 'COMPLETED_EMPTY', 'REJECTED', 'FAILED',
        'TIMED_OUT', 'CANCEL_PENDING', 'CANCELLED'
    )),
    CONSTRAINT CK_DQ_RUN_HASH CHECK (LENGTH(REQUEST_FINGERPRINT) = 64 AND ROW_VERSION >= 1)
);

CREATE TABLE KBOT_DQ_EXECUTION (
    DATA_QUERY_EXECUTION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DATA_QUERY_RUN_ID RAW(16) NOT NULL,
    ATTEMPT_NO NUMBER(10) NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'CREATED' NOT NULL,
    CONNECTOR_TYPE VARCHAR2(32 CHAR) NOT NULL,
    CONNECTOR_VERSION VARCHAR2(64 CHAR) NOT NULL,
    QUERY_PLAN_HASH VARCHAR2(64 CHAR) NOT NULL,
    COMPILED_QUERY_HASH VARCHAR2(64 CHAR),
    PREFLIGHT_JSON JSON,
    EXECUTION_SUMMARY_JSON JSON,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    HEARTBEAT_AT TIMESTAMP(6) WITH TIME ZONE,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_DQ_EXEC_ATTEMPT UNIQUE (DATA_QUERY_RUN_ID, ATTEMPT_NO),
    CONSTRAINT CK_DQ_EXEC_STATUS CHECK (STATUS IN ('CREATED', 'PREFLIGHT', 'QUEUED', 'EXECUTING', 'REPAIRING', 'SUCCEEDED', 'REJECTED', 'FAILED', 'TIMED_OUT', 'CANCEL_PENDING', 'CANCELLED')),
    CONSTRAINT CK_DQ_EXEC_ATTEMPT CHECK (ATTEMPT_NO >= 1 AND ROW_VERSION >= 1),
    CONSTRAINT CK_DQ_EXEC_LEASE CHECK (
        (STATUS = 'EXECUTING' AND LEASE_OWNER IS NOT NULL AND LEASE_TOKEN IS NOT NULL AND LEASE_UNTIL IS NOT NULL)
        OR (STATUS <> 'EXECUTING')
    )
);

CREATE TABLE KBOT_DQ_RESULT (
    DATA_QUERY_RESULT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DATA_QUERY_RUN_ID RAW(16) NOT NULL,
    COLUMNS_JSON JSON NOT NULL,
    PREVIEW_ROWS_JSON JSON NOT NULL,
    ROW_COUNT NUMBER(19) NOT NULL,
    OBSERVED_ROW_COUNT NUMBER(19) NOT NULL,
    TRUNCATED NUMBER(1) DEFAULT 0 NOT NULL,
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    STORAGE_URI VARCHAR2(2048 CHAR),
    BYTE_SIZE NUMBER(19) NOT NULL,
    AVAILABLE_UNTIL TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PURGED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_DQ_RESULT_RUN UNIQUE (DATA_QUERY_RUN_ID),
    CONSTRAINT CK_DQ_RESULT_SIZE CHECK (ROW_COUNT >= 0 AND OBSERVED_ROW_COUNT >= 0 AND BYTE_SIZE >= 0),
    CONSTRAINT CK_DQ_RESULT_TRUNC CHECK (TRUNCATED IN (0, 1)),
    CONSTRAINT CK_DQ_RESULT_HASH CHECK (LENGTH(CONTENT_HASH) = 64 AND ROW_VERSION >= 1)
);

CREATE TABLE KBOT_DQ_EVENT (
    DOMAIN_ID NUMBER(38) NOT NULL,
    DATA_QUERY_RUN_ID RAW(16) NOT NULL,
    SEQUENCE_NO NUMBER(19) NOT NULL,
    EVENT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    EVENT_KEY VARCHAR2(128 CHAR),
    VISIBILITY VARCHAR2(16 CHAR) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_DQ_EVENT PRIMARY KEY (DATA_QUERY_RUN_ID, SEQUENCE_NO),
    CONSTRAINT CK_DQ_EVENT_SEQ CHECK (SEQUENCE_NO >= 1),
    CONSTRAINT CK_DQ_EVENT_VIS CHECK (VISIBILITY IN ('PUBLIC', 'INTERNAL'))
);

CREATE INDEX IX_DQ_RUN_SCOPE ON KBOT_DQ_RUN (DOMAIN_ID, ACTOR_ID, CREATED_AT);
CREATE INDEX IX_DQ_EXEC_CLAIM ON KBOT_DQ_EXECUTION (STATUS, LEASE_UNTIL, DATA_QUERY_EXECUTION_ID);
CREATE INDEX IX_DQ_RESULT_EXPIRY ON KBOT_DQ_RESULT (AVAILABLE_UNTIL, PURGED_AT);
