-- KBot 4.0 Data Query：审计、外键、条件唯一索引与只读视图。

CREATE TABLE KBOT_DQ_AUDIT (
    AUDIT_ID RAW(16) PRIMARY KEY,
    DATA_QUERY_RUN_ID RAW(16),
    DOMAIN_ID NUMBER(38) NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR),
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    ACTION VARCHAR2(128 CHAR) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    PREVIOUS_HASH VARCHAR2(64 CHAR),
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_DQ_AUDIT_HASH CHECK (LENGTH(CONTENT_HASH) = 64 AND (PREVIOUS_HASH IS NULL OR LENGTH(PREVIOUS_HASH) = 64))
);

ALTER TABLE KBOT_DQ_DATA_SOURCE ADD CONSTRAINT FK_DQ_SOURCE_DOMAIN
    FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID);
ALTER TABLE KBOT_DQ_DATA_SOURCE ADD CONSTRAINT FK_DQ_SOURCE_CRED
    FOREIGN KEY (CREDENTIAL_ID) REFERENCES KBOT_MANAGED_CREDENTIAL (CREDENTIAL_ID);
ALTER TABLE KBOT_DQ_SCHEMA_SNAPSHOT ADD CONSTRAINT FK_DQ_SNAPSHOT_SOURCE
    FOREIGN KEY (DATA_SOURCE_ID) REFERENCES KBOT_DQ_DATA_SOURCE (DATA_SOURCE_ID);
ALTER TABLE KBOT_DQ_SNAPSHOT_OBJECT ADD CONSTRAINT FK_DQ_OBJECT_SNAPSHOT
    FOREIGN KEY (SCHEMA_SNAPSHOT_ID) REFERENCES KBOT_DQ_SCHEMA_SNAPSHOT (SCHEMA_SNAPSHOT_ID);
ALTER TABLE KBOT_DQ_SEMANTIC_MODEL ADD CONSTRAINT FK_DQ_MODEL_DOMAIN
    FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID);
ALTER TABLE KBOT_DQ_MODEL_VERSION ADD CONSTRAINT FK_DQ_VERSION_MODEL
    FOREIGN KEY (SEMANTIC_MODEL_ID) REFERENCES KBOT_DQ_SEMANTIC_MODEL (SEMANTIC_MODEL_ID);
ALTER TABLE KBOT_DQ_MODEL_VERSION ADD CONSTRAINT FK_DQ_VERSION_SOURCE
    FOREIGN KEY (DATA_SOURCE_ID) REFERENCES KBOT_DQ_DATA_SOURCE (DATA_SOURCE_ID);
ALTER TABLE KBOT_DQ_MODEL_VERSION ADD CONSTRAINT FK_DQ_VERSION_SNAPSHOT
    FOREIGN KEY (SCHEMA_SNAPSHOT_ID) REFERENCES KBOT_DQ_SCHEMA_SNAPSHOT (SCHEMA_SNAPSHOT_ID);
ALTER TABLE KBOT_DQ_MODEL_GEN_JOB ADD CONSTRAINT FK_DQ_GEN_DOMAIN
    FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID);
ALTER TABLE KBOT_DQ_MODEL_GEN_JOB ADD CONSTRAINT FK_DQ_GEN_SNAPSHOT
    FOREIGN KEY (SCHEMA_SNAPSHOT_ID) REFERENCES KBOT_DQ_SCHEMA_SNAPSHOT (SCHEMA_SNAPSHOT_ID);
ALTER TABLE KBOT_DQ_VERIFIED_QUERY ADD CONSTRAINT FK_DQ_VERIFIED_VERSION
    FOREIGN KEY (SEMANTIC_MODEL_VERSION_ID) REFERENCES KBOT_DQ_MODEL_VERSION (SEMANTIC_MODEL_VERSION_ID);
ALTER TABLE KBOT_DQ_POLICY ADD CONSTRAINT FK_DQ_POLICY_DOMAIN
    FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID);
ALTER TABLE KBOT_DQ_AGENT_BINDING ADD CONSTRAINT FK_DQ_BIND_DOMAIN
    FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID);
ALTER TABLE KBOT_DQ_AGENT_BINDING ADD CONSTRAINT FK_DQ_BIND_MODEL
    FOREIGN KEY (SEMANTIC_MODEL_ID) REFERENCES KBOT_DQ_SEMANTIC_MODEL (SEMANTIC_MODEL_ID);
ALTER TABLE KBOT_DQ_AGENT_BINDING ADD CONSTRAINT FK_DQ_BIND_POLICY
    FOREIGN KEY (POLICY_BINDING_ID) REFERENCES KBOT_DQ_POLICY (POLICY_BINDING_ID);
ALTER TABLE KBOT_DQ_RUN ADD CONSTRAINT FK_DQ_RUN_DOMAIN
    FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID);
ALTER TABLE KBOT_DQ_EXECUTION ADD CONSTRAINT FK_DQ_EXEC_RUN
    FOREIGN KEY (DATA_QUERY_RUN_ID) REFERENCES KBOT_DQ_RUN (DATA_QUERY_RUN_ID);
ALTER TABLE KBOT_DQ_RESULT ADD CONSTRAINT FK_DQ_RESULT_RUN
    FOREIGN KEY (DATA_QUERY_RUN_ID) REFERENCES KBOT_DQ_RUN (DATA_QUERY_RUN_ID);
ALTER TABLE KBOT_DQ_EVENT ADD CONSTRAINT FK_DQ_EVENT_RUN
    FOREIGN KEY (DATA_QUERY_RUN_ID) REFERENCES KBOT_DQ_RUN (DATA_QUERY_RUN_ID);
ALTER TABLE KBOT_DQ_AUDIT ADD CONSTRAINT FK_DQ_AUDIT_RUN
    FOREIGN KEY (DATA_QUERY_RUN_ID) REFERENCES KBOT_DQ_RUN (DATA_QUERY_RUN_ID);
ALTER TABLE KBOT_DQ_AUDIT ADD CONSTRAINT FK_DQ_AUDIT_DOMAIN
    FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID);

CREATE UNIQUE INDEX UX_DQ_MODEL_ACTIVE ON KBOT_DQ_MODEL_VERSION (
    CASE WHEN STATUS = 'ACTIVE' THEN SEMANTIC_MODEL_ID END
);
CREATE UNIQUE INDEX UX_DQ_EVENT_KEY ON KBOT_DQ_EVENT (
    CASE WHEN EVENT_KEY IS NOT NULL THEN DATA_QUERY_RUN_ID END,
    CASE WHEN EVENT_KEY IS NOT NULL THEN EVENT_KEY END
);
CREATE INDEX IX_DQ_AUDIT_SCOPE ON KBOT_DQ_AUDIT (DOMAIN_ID, CREATED_AT, AUDIT_ID);

CREATE OR REPLACE VIEW KBOT_V_DQ_SOURCE AS
SELECT DATA_SOURCE_ID, DOMAIN_ID, DISPLAY_NAME, SOURCE_TYPE, STATUS,
       CURRENT_VERSION, CAPABILITIES_JSON, ERROR_CODE, ROW_VERSION, UPDATED_AT
FROM KBOT_DQ_DATA_SOURCE;

CREATE OR REPLACE VIEW KBOT_V_DQ_RUN AS
SELECT DATA_QUERY_RUN_ID, DOMAIN_ID, ACTOR_ID, CONSUMER_APP_ID, AGENT_ID,
       AGENT_VERSION_ID, TRACE_ID, STATUS,
       ERROR_CODE, ROW_VERSION, CREATED_AT, COMPLETED_AT
FROM KBOT_DQ_RUN;

CREATE OR REPLACE VIEW KBOT_V_DQ_SCHEMA_VERSION AS
SELECT 'data_query' AS COMPONENT, 1 AS SCHEMA_VERSION FROM DUAL;
