-- AIOps Schema 34 -> 35 原地升级。
-- 影响范围：新增 DBA 工作项、发生记录、资源关联和审计活动；不修改既有业务数据。
-- 前置条件：当前必须是 Schema 34 / aiops-oracle-v24。

SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER SESSION SET TIME_ZONE = '+00:00';
ALTER SESSION SET DDL_LOCK_TIMEOUT = 60;

DECLARE
    l_schema_version NUMBER;
    l_contract_version VARCHAR2(64 CHAR);
BEGIN
    SELECT SCHEMA_VERSION, CONTRACT_VERSION
      INTO l_schema_version, l_contract_version
      FROM KBOT_V_OPS_SCHEMA_VERSION
     WHERE COMPONENT = 'AIOPS';
    IF l_schema_version <> 34 OR l_contract_version <> 'aiops-oracle-v24' THEN
        RAISE_APPLICATION_ERROR(-20091, '只允许从 AIOPS Schema 34 升级到 Schema 35');
    END IF;
END;
/

CREATE TABLE KBOT_OPS_WORK_ITEM (
    WORK_ITEM_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    ITEM_KEY VARCHAR2(32 CHAR) NOT NULL,
    TARGET_ID RAW(16) NOT NULL,
    WORK_TYPE VARCHAR2(32 CHAR) NOT NULL,
    SOURCE_KIND VARCHAR2(24 CHAR) NOT NULL,
    FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
    TITLE VARCHAR2(512 CHAR) NOT NULL,
    SUMMARY CLOB NOT NULL,
    SEVERITY VARCHAR2(16 CHAR) NOT NULL,
    PRIORITY VARCHAR2(4 CHAR) NOT NULL,
    STATUS VARCHAR2(32 CHAR) NOT NULL,
    PHASE VARCHAR2(24 CHAR) NOT NULL,
    WAIT_REASON VARCHAR2(256 CHAR),
    ASSIGNMENT_GROUP VARCHAR2(128 CHAR),
    ASSIGNEE_USER_ID VARCHAR2(256 CHAR),
    ACKNOWLEDGEMENT_DUE_AT TIMESTAMP(6) WITH TIME ZONE,
    RESOLUTION_DUE_AT TIMESTAMP(6) WITH TIME ZONE,
    VERIFICATION_DUE_AT TIMESTAMP(6) WITH TIME ZONE,
    FIRST_OBSERVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    LAST_OBSERVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    OCCURRENCE_COUNT NUMBER(19) DEFAULT 1 NOT NULL,
    REOPEN_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
    RESOLUTION_CODE VARCHAR2(32 CHAR),
    RESOLUTION_NOTE CLOB,
    RESOLVED_AT TIMESTAMP(6) WITH TIME ZONE,
    CLOSED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_OPS_WORK_ITEM_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_OPS_WORK_ITEM_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES KBOT_OPS_TARGET (TARGET_ID));

CREATE INDEX IX_OPS_WORK_ITEM_QUEUE ON KBOT_OPS_WORK_ITEM
    (DOMAIN_ID, STATUS, PRIORITY, UPDATED_AT);
CREATE INDEX IX_OPS_WORK_ITEM_TARGET ON KBOT_OPS_WORK_ITEM
    (TARGET_ID, STATUS, UPDATED_AT);
CREATE INDEX IX_OPS_WORK_ITEM_FINGERPRINT ON KBOT_OPS_WORK_ITEM
    (DOMAIN_ID, TARGET_ID, FINGERPRINT, STATUS);
CREATE INDEX IX_OPS_WORK_ITEM_ASSIGNEE ON KBOT_OPS_WORK_ITEM
    (DOMAIN_ID, ASSIGNEE_USER_ID, STATUS);
CREATE INDEX IX_OPS_WORK_ITEM_SLA ON KBOT_OPS_WORK_ITEM
    (DOMAIN_ID, RESOLUTION_DUE_AT, STATUS);

CREATE TABLE KBOT_OPS_WORK_ITEM_OCCURRENCE (
    OCCURRENCE_ID RAW(16) PRIMARY KEY,
    WORK_ITEM_ID RAW(16) NOT NULL,
    OPS_RUN_ID RAW(16) NOT NULL,
    SITUATION_ID RAW(16),
    FINDING_ID VARCHAR2(128 CHAR) NOT NULL,
    FINDING_TYPE VARCHAR2(64 CHAR) NOT NULL,
    SEVERITY VARCHAR2(16 CHAR) NOT NULL,
    CONFIRMATION VARCHAR2(16 CHAR) NOT NULL,
    FINDING_SNAPSHOT_JSON JSON,
    EVIDENCE_REFS_JSON JSON,
    OBSERVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_WI_OCC_ITEM FOREIGN KEY (WORK_ITEM_ID)
        REFERENCES KBOT_OPS_WORK_ITEM (WORK_ITEM_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OPS_WI_OCC_RUN FOREIGN KEY (OPS_RUN_ID)
        REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
    CONSTRAINT FK_OPS_WI_OCC_SITUATION FOREIGN KEY (SITUATION_ID)
        REFERENCES KBOT_OPS_SITUATION (SITUATION_ID));

CREATE INDEX IX_OPS_WI_OCC_ITEM ON KBOT_OPS_WORK_ITEM_OCCURRENCE
    (WORK_ITEM_ID, OBSERVED_AT);
CREATE INDEX IX_OPS_WI_OCC_RUN ON KBOT_OPS_WORK_ITEM_OCCURRENCE
    (OPS_RUN_ID, FINDING_ID);
CREATE INDEX IX_OPS_WI_OCC_SITUATION ON KBOT_OPS_WORK_ITEM_OCCURRENCE
    (SITUATION_ID);

CREATE TABLE KBOT_OPS_WORK_ITEM_LINK (
    WORK_ITEM_LINK_ID RAW(16) PRIMARY KEY,
    WORK_ITEM_ID RAW(16) NOT NULL,
    RESOURCE_KIND VARCHAR2(24 CHAR) NOT NULL,
    RESOURCE_ID RAW(16) NOT NULL,
    LINK_ROLE VARCHAR2(32 CHAR) NOT NULL,
    SNAPSHOT_JSON JSON,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_WI_LINK_ITEM FOREIGN KEY (WORK_ITEM_ID)
        REFERENCES KBOT_OPS_WORK_ITEM (WORK_ITEM_ID) ON DELETE CASCADE);

CREATE INDEX IX_OPS_WI_LINK_ITEM ON KBOT_OPS_WORK_ITEM_LINK
    (WORK_ITEM_ID, RESOURCE_KIND, CREATED_AT);
CREATE INDEX IX_OPS_WI_LINK_RESOURCE ON KBOT_OPS_WORK_ITEM_LINK
    (RESOURCE_KIND, RESOURCE_ID, LINK_ROLE);

CREATE TABLE KBOT_OPS_WORK_ITEM_ACTIVITY (
    ACTIVITY_ID RAW(16) PRIMARY KEY,
    WORK_ITEM_ID RAW(16) NOT NULL,
    ACTIVITY_TYPE VARCHAR2(32 CHAR) NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    FROM_STATUS VARCHAR2(32 CHAR),
    TO_STATUS VARCHAR2(32 CHAR),
    FROM_PHASE VARCHAR2(24 CHAR),
    TO_PHASE VARCHAR2(24 CHAR),
    DETAIL_JSON JSON,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPS_WI_ACTIVITY_ITEM FOREIGN KEY (WORK_ITEM_ID)
        REFERENCES KBOT_OPS_WORK_ITEM (WORK_ITEM_ID) ON DELETE CASCADE);

CREATE INDEX IX_OPS_WI_ACTIVITY_ITEM ON KBOT_OPS_WORK_ITEM_ACTIVITY
    (WORK_ITEM_ID, CREATED_AT);

CREATE OR REPLACE VIEW KBOT_V_OPS_SCHEMA_VERSION AS
SELECT
    'AIOPS' AS COMPONENT,
    35 AS SCHEMA_VERSION,
    'aiops-oracle-v25' AS CONTRACT_VERSION
FROM DUAL;

COMMIT;

SELECT COMPONENT, SCHEMA_VERSION, CONTRACT_VERSION
  FROM KBOT_V_OPS_SCHEMA_VERSION;
