-- AIOps Schema 32 -> 33 原地升级。
-- 影响范围：新增Target恢复目标和恢复演练表；不删除或改写既有业务行。
-- 前置条件：当前必须是Schema 32 / aiops-oracle-v22，或已部分升级到Schema 33。
-- 并发要求：执行前停止AIOps API、Worker、Scheduler和DB Executor，并完成Schema备份。

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET SQLBLANKLINES ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER SESSION SET TIME_ZONE = '+00:00';
ALTER SESSION SET DDL_LOCK_TIMEOUT = 60;

DECLARE
    l_schema_version NUMBER;
    l_contract_version VARCHAR2(64 CHAR);
BEGIN
    SELECT SCHEMA_VERSION, CONTRACT_VERSION
      INTO l_schema_version, l_contract_version
      FROM KBOT_V_OPS_SCHEMA_VERSION
     WHERE COMPONENT = 'AIOPS';
    IF NOT (
        (l_schema_version = 32 AND l_contract_version = 'aiops-oracle-v22')
        OR
        (l_schema_version = 33 AND l_contract_version = 'aiops-oracle-v23')
    ) THEN
        RAISE_APPLICATION_ERROR(
            -20091,
            '只允许从AIOPS Schema 32 / aiops-oracle-v22升级，'
            || '或续跑Schema 33 / aiops-oracle-v23'
        );
    END IF;
END;
/

DECLARE
    PROCEDURE create_table_if_missing(p_table_name VARCHAR2, p_ddl CLOB) IS
        l_count PLS_INTEGER;
    BEGIN
        SELECT COUNT(*) INTO l_count FROM USER_TABLES WHERE TABLE_NAME = p_table_name;
        IF l_count = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
            DBMS_OUTPUT.PUT_LINE('已创建表 ' || p_table_name);
        END IF;
    END;
    PROCEDURE create_index_if_missing(p_index_name VARCHAR2, p_ddl CLOB) IS
        l_count PLS_INTEGER;
    BEGIN
        SELECT COUNT(*) INTO l_count FROM USER_INDEXES WHERE INDEX_NAME = p_index_name;
        IF l_count = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
            DBMS_OUTPUT.PUT_LINE('已创建索引 ' || p_index_name);
        END IF;
    END;
BEGIN
    create_table_if_missing('KBOT_OPS_RECOVERY_PROFILE', q'~
        CREATE TABLE KBOT_OPS_RECOVERY_PROFILE (
            RECOVERY_PROFILE_ID RAW(16) PRIMARY KEY,
            TARGET_ID RAW(16) NOT NULL,
            DOMAIN_ID NUMBER(38) NOT NULL,
            VERSION_NO NUMBER(19) NOT NULL,
            RPO_SECONDS NUMBER(19) NOT NULL,
            RTO_SECONDS NUMBER(19) NOT NULL,
            REQUIRED_DRILL_INTERVAL_DAYS NUMBER(10) NOT NULL,
            REQUIRED_ASSURANCE_LEVEL VARCHAR2(32 CHAR) NOT NULL,
            RTO_CLOCK_BASIS VARCHAR2(64 CHAR) NOT NULL,
            SOURCE_NOTE VARCHAR2(1000 CHAR),
            STATUS VARCHAR2(16 CHAR) NOT NULL,
            EFFECTIVE_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            RETIRED_AT TIMESTAMP(6) WITH TIME ZONE,
            CONFIRMED_BY VARCHAR2(256 CHAR) NOT NULL,
            ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
            CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
            UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
            CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT FK_OPS_REC_PROFILE_TARGET FOREIGN KEY (TARGET_ID)
                REFERENCES KBOT_OPS_TARGET (TARGET_ID),
            CONSTRAINT FK_OPS_REC_PROFILE_DOMAIN FOREIGN KEY (DOMAIN_ID)
                REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID)
        )~');
    create_table_if_missing('KBOT_OPS_RECOVERY_DRILL', q'~
        CREATE TABLE KBOT_OPS_RECOVERY_DRILL (
            DRILL_ID RAW(16) PRIMARY KEY,
            TARGET_ID RAW(16) NOT NULL,
            DOMAIN_ID NUMBER(38) NOT NULL,
            RECOVERY_PROFILE_ID RAW(16),
            RECOVERY_PROFILE_VERSION NUMBER(19),
            DB_TYPE VARCHAR2(32 CHAR) NOT NULL,
            SCENARIO VARCHAR2(32 CHAR) NOT NULL,
            ASSURANCE_LEVEL VARCHAR2(32 CHAR) NOT NULL,
            BACKUP_SOURCE_TYPE VARCHAR2(48 CHAR) NOT NULL,
            ENVIRONMENT VARCHAR2(16 CHAR) NOT NULL,
            RESULT VARCHAR2(16 CHAR) NOT NULL,
            STATUS VARCHAR2(16 CHAR) NOT NULL,
            SIMULATED_FAILURE_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            RECOVERED_THROUGH_AT TIMESTAMP(6) WITH TIME ZONE,
            SERVICE_VALIDATED_AT TIMESTAMP(6) WITH TIME ZONE,
            ACHIEVED_RPO_SECONDS NUMBER(19),
            ACHIEVED_RTO_SECONDS NUMBER(19),
            RECOVERY_MARKER_JSON JSON NOT NULL,
            EVIDENCE_JSON JSON NOT NULL,
            SOURCE_TRUST_LEVEL VARCHAR2(32 CHAR) NOT NULL,
            SOURCE_OPS_RUN_ID RAW(16),
            REVIEWED_BY VARCHAR2(256 CHAR),
            REVIEWED_AT TIMESTAMP(6) WITH TIME ZONE,
            REVIEW_NOTE VARCHAR2(2000 CHAR),
            NOTES CLOB,
            ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
            CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
            UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
            CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT FK_OPS_REC_DRILL_TARGET FOREIGN KEY (TARGET_ID)
                REFERENCES KBOT_OPS_TARGET (TARGET_ID),
            CONSTRAINT FK_OPS_REC_DRILL_DOMAIN FOREIGN KEY (DOMAIN_ID)
                REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
            CONSTRAINT FK_OPS_REC_DRILL_PROFILE FOREIGN KEY (RECOVERY_PROFILE_ID)
                REFERENCES KBOT_OPS_RECOVERY_PROFILE (RECOVERY_PROFILE_ID),
            CONSTRAINT FK_OPS_REC_DRILL_RUN FOREIGN KEY (SOURCE_OPS_RUN_ID)
                REFERENCES KBOT_OPS_RUN (OPS_RUN_ID)
        )~');

    create_index_if_missing('IX_OPS_REC_PROFILE_TARGET',
        'CREATE INDEX IX_OPS_REC_PROFILE_TARGET ON KBOT_OPS_RECOVERY_PROFILE '
        || '(TARGET_ID, STATUS, VERSION_NO)');
    create_index_if_missing('IX_OPS_REC_PROFILE_SCOPE',
        'CREATE INDEX IX_OPS_REC_PROFILE_SCOPE ON KBOT_OPS_RECOVERY_PROFILE '
        || '(DOMAIN_ID, TARGET_ID, STATUS)');
    create_index_if_missing('IX_OPS_REC_DRILL_TARGET',
        'CREATE INDEX IX_OPS_REC_DRILL_TARGET ON KBOT_OPS_RECOVERY_DRILL '
        || '(TARGET_ID, SIMULATED_FAILURE_AT, CREATED_AT)');
    create_index_if_missing('IX_OPS_REC_DRILL_STATUS',
        'CREATE INDEX IX_OPS_REC_DRILL_STATUS ON KBOT_OPS_RECOVERY_DRILL '
        || '(DOMAIN_ID, STATUS, RESULT, SIMULATED_FAILURE_AT)');
    create_index_if_missing('IX_OPS_REC_DRILL_PROFILE',
        'CREATE INDEX IX_OPS_REC_DRILL_PROFILE ON KBOT_OPS_RECOVERY_DRILL '
        || '(RECOVERY_PROFILE_ID)');
    create_index_if_missing('IX_OPS_REC_DRILL_RUN',
        'CREATE INDEX IX_OPS_REC_DRILL_RUN ON KBOT_OPS_RECOVERY_DRILL '
        || '(SOURCE_OPS_RUN_ID)');
END;
/

CREATE OR REPLACE VIEW KBOT_V_OPS_SCHEMA_VERSION AS
SELECT
    'AIOPS' AS COMPONENT,
    33 AS SCHEMA_VERSION,
    'aiops-oracle-v23' AS CONTRACT_VERSION
FROM DUAL;

DECLARE
    l_table_count PLS_INTEGER;
    l_business_constraint_count PLS_INTEGER;
    l_schema_version NUMBER;
    l_contract_version VARCHAR2(64 CHAR);
BEGIN
    SELECT COUNT(*) INTO l_table_count FROM USER_TABLES
     WHERE TABLE_NAME IN ('KBOT_OPS_RECOVERY_PROFILE', 'KBOT_OPS_RECOVERY_DRILL');
    SELECT COUNT(*) INTO l_business_constraint_count FROM USER_CONSTRAINTS
     WHERE TABLE_NAME IN ('KBOT_OPS_RECOVERY_PROFILE', 'KBOT_OPS_RECOVERY_DRILL')
       AND ((CONSTRAINT_TYPE = 'C' AND GENERATED = 'USER NAME') OR CONSTRAINT_TYPE = 'U');
    SELECT SCHEMA_VERSION, CONTRACT_VERSION
      INTO l_schema_version, l_contract_version
      FROM KBOT_V_OPS_SCHEMA_VERSION
     WHERE COMPONENT = 'AIOPS';
    IF l_table_count <> 2
       OR l_business_constraint_count <> 0
       OR l_schema_version <> 33
       OR l_contract_version <> 'aiops-oracle-v23' THEN
        RAISE_APPLICATION_ERROR(-20092, 'AIOps Schema 33升级后验证失败');
    END IF;
    DBMS_OUTPUT.PUT_LINE('AIOps Schema已升级到33 / aiops-oracle-v23。');
END;
/

COMMIT;
