-- AIOps Schema 37 -> 38 原地升级。
-- 影响范围：新增 DBA 责任组，并把工作项责任、完成和验证过程改为正式字段。
-- 前置条件：当前必须是 Schema 37 / aiops-oracle-v27。

SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER SESSION SET TIME_ZONE = '+00:00';
ALTER SESSION SET DDL_LOCK_TIMEOUT = 60;

DECLARE
    l_schema_version NUMBER;
    l_contract_version VARCHAR2(64 CHAR);
BEGIN
    SELECT SCHEMA_VERSION, CONTRACT_VERSION
      INTO l_schema_version, l_contract_version
      FROM KBOT_V_OPS_SCHEMA_VERSION
     WHERE COMPONENT = 'AIOPS';
    IF l_schema_version <> 37 OR l_contract_version <> 'aiops-oracle-v27' THEN
        RAISE_APPLICATION_ERROR(-20091, '只允许从 AIOPS Schema 37 升级到 Schema 38');
    END IF;
END;
/

CREATE TABLE KBOT_OPS_RESPONSIBILITY_GROUP (
    RESPONSIBILITY_GROUP_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    NAME VARCHAR2(128 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    LEAD_USER_ID VARCHAR2(256 CHAR),
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_OPS_RESP_GROUP_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID));

CREATE INDEX IX_OPS_RESP_GROUP_SCOPE
    ON KBOT_OPS_RESPONSIBILITY_GROUP (DOMAIN_ID, STATUS, NAME);

CREATE TABLE KBOT_OPS_RESPONSIBILITY_GROUP_MEMBER (
    RESPONSIBILITY_GROUP_ID RAW(16) NOT NULL,
    USER_ID VARCHAR2(256 CHAR) NOT NULL,
    MEMBER_ROLE VARCHAR2(16 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (RESPONSIBILITY_GROUP_ID, USER_ID),
    CONSTRAINT FK_OPS_RESP_MEMBER_GROUP FOREIGN KEY (RESPONSIBILITY_GROUP_ID)
        REFERENCES KBOT_OPS_RESPONSIBILITY_GROUP (RESPONSIBILITY_GROUP_ID) ON DELETE CASCADE);

CREATE INDEX IX_OPS_RESP_MEMBER_USER
    ON KBOT_OPS_RESPONSIBILITY_GROUP_MEMBER (USER_ID, STATUS);

ALTER TABLE KBOT_OPS_TARGET ADD DEFAULT_RESPONSIBILITY_GROUP_ID RAW(16);
ALTER TABLE KBOT_OPS_AGENT ADD DEFAULT_RESPONSIBILITY_GROUP_ID RAW(16);
ALTER TABLE KBOT_OPS_TARGET ADD CONSTRAINT FK_OPS_TARGET_RESP_GROUP
    FOREIGN KEY (DEFAULT_RESPONSIBILITY_GROUP_ID)
    REFERENCES KBOT_OPS_RESPONSIBILITY_GROUP (RESPONSIBILITY_GROUP_ID);
ALTER TABLE KBOT_OPS_AGENT ADD CONSTRAINT FK_OPS_AGENT_RESP_GROUP
    FOREIGN KEY (DEFAULT_RESPONSIBILITY_GROUP_ID)
    REFERENCES KBOT_OPS_RESPONSIBILITY_GROUP (RESPONSIBILITY_GROUP_ID);
CREATE INDEX IX_OPS_TARGET_RESP_GROUP
    ON KBOT_OPS_TARGET (DEFAULT_RESPONSIBILITY_GROUP_ID);
CREATE INDEX IX_OPS_AGENT_RESP_GROUP
    ON KBOT_OPS_AGENT (DEFAULT_RESPONSIBILITY_GROUP_ID);

ALTER TABLE KBOT_OPS_WORK_ITEM ADD (
    RESPONSIBILITY_GROUP_ID RAW(16),
    ASSIGNMENT_SOURCE VARCHAR2(32 CHAR),
    ASSIGNED_BY VARCHAR2(256 CHAR),
    ASSIGNED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETION_NOTE CLOB,
    COMPLETED_BY VARCHAR2(256 CHAR),
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    VERIFICATION_RESULT VARCHAR2(16 CHAR),
    VERIFICATION_NOTE CLOB,
    VERIFIED_BY VARCHAR2(256 CHAR),
    VERIFIED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROUTING_DECISION_JSON JSON);

ALTER TABLE KBOT_OPS_WORK_ITEM ADD CONSTRAINT FK_OPS_WORK_ITEM_GROUP
    FOREIGN KEY (RESPONSIBILITY_GROUP_ID)
    REFERENCES KBOT_OPS_RESPONSIBILITY_GROUP (RESPONSIBILITY_GROUP_ID);
CREATE INDEX IX_OPS_WORK_ITEM_GROUP
    ON KBOT_OPS_WORK_ITEM (RESPONSIBILITY_GROUP_ID, STATUS);

-- 将旧自由文本责任组原地转换为正式责任组，确保历史工作项的责任信息不丢失。
INSERT INTO KBOT_OPS_RESPONSIBILITY_GROUP (
    RESPONSIBILITY_GROUP_ID,
    DOMAIN_ID,
    NAME,
    DESCRIPTION,
    STATUS,
    CREATED_BY,
    UPDATED_BY,
    CREATED_AT,
    UPDATED_AT,
    ROW_VERSION)
SELECT
    SYS_GUID(),
    legacy.DOMAIN_ID,
    legacy.NAME,
    '由 Schema 38 升级从历史 assignment_group 转换',
    'ACTIVE',
    'schema-upgrade-38',
    'schema-upgrade-38',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    1
FROM (
    SELECT DISTINCT DOMAIN_ID, TRIM(ASSIGNMENT_GROUP) AS NAME
      FROM KBOT_OPS_WORK_ITEM
     WHERE ASSIGNMENT_GROUP IS NOT NULL
       AND LENGTH(TRIM(ASSIGNMENT_GROUP)) > 0
) legacy;

UPDATE KBOT_OPS_WORK_ITEM item
   SET RESPONSIBILITY_GROUP_ID = (
           SELECT group_row.RESPONSIBILITY_GROUP_ID
             FROM KBOT_OPS_RESPONSIBILITY_GROUP group_row
            WHERE group_row.DOMAIN_ID = item.DOMAIN_ID
              AND group_row.NAME = TRIM(item.ASSIGNMENT_GROUP)
              AND group_row.CREATED_BY = 'schema-upgrade-38'
       ),
       ASSIGNMENT_SOURCE = 'SCHEMA_UPGRADE',
       ASSIGNED_BY = item.UPDATED_BY,
       ASSIGNED_AT = item.UPDATED_AT
 WHERE item.ASSIGNMENT_GROUP IS NOT NULL
   AND LENGTH(TRIM(item.ASSIGNMENT_GROUP)) > 0;

DECLARE
    l_unmigrated_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_unmigrated_count
      FROM KBOT_OPS_WORK_ITEM
     WHERE ASSIGNMENT_GROUP IS NOT NULL
       AND LENGTH(TRIM(ASSIGNMENT_GROUP)) > 0
       AND RESPONSIBILITY_GROUP_ID IS NULL;
    IF l_unmigrated_count <> 0 THEN
        RAISE_APPLICATION_ERROR(-20092, '历史 assignment_group 未完整转换，禁止删除旧列');
    END IF;
END;
/

ALTER TABLE KBOT_OPS_WORK_ITEM DROP COLUMN ASSIGNMENT_GROUP;

MERGE INTO KBOT_PERMISSION target
USING (
    SELECT 'aiops:work_item_handle' PERMISSION_CODE, '领取并处理 DBA 工作项' DISPLAY_NAME FROM DUAL
    UNION ALL
    SELECT 'aiops:work_item_manage', '维护责任组并跨用户管理 DBA 工作项' FROM DUAL
) source
ON (target.PERMISSION_CODE = source.PERMISSION_CODE)
WHEN NOT MATCHED THEN INSERT (PERMISSION_CODE, APP_ID, DISPLAY_NAME)
VALUES (source.PERMISSION_CODE, 'aiops', source.DISPLAY_NAME);

MERGE INTO KBOT_APP_ROLE_PERMISSION target
USING (
    SELECT 'aiops' APP_ID, 'app_admin' ROLE_CODE, 'aiops:work_item_handle' PERMISSION_CODE FROM DUAL
    UNION ALL SELECT 'aiops', 'app_admin', 'aiops:work_item_manage' FROM DUAL
    UNION ALL SELECT 'aiops', 'operator', 'aiops:work_item_handle' FROM DUAL
) source
ON (target.APP_ID = source.APP_ID AND target.ROLE_CODE = source.ROLE_CODE AND target.PERMISSION_CODE = source.PERMISSION_CODE)
WHEN NOT MATCHED THEN INSERT (APP_ID, ROLE_CODE, PERMISSION_CODE)
VALUES (source.APP_ID, source.ROLE_CODE, source.PERMISSION_CODE);

CREATE OR REPLACE VIEW KBOT_V_OPS_SCHEMA_VERSION AS
SELECT
    'AIOPS' AS COMPONENT,
    38 AS SCHEMA_VERSION,
    'aiops-oracle-v28' AS CONTRACT_VERSION
FROM DUAL;

COMMIT;

SELECT COMPONENT, SCHEMA_VERSION, CONTRACT_VERSION
  FROM KBOT_V_OPS_SCHEMA_VERSION;
