-- AIOps Schema 31 -> 32 原地升级。
-- 影响范围：新增运维知识资产、版本、范围、来源、KC索引引用和审核记录表。
-- 数据保护：不删除或改写既有业务行；新表只包含主键、外键和列级NOT NULL。
-- 前置条件：当前必须是Schema 31 / aiops-oracle-v21，或已部分升级到Schema 32。
-- 并发要求：执行前停止AIOps API、Worker、Scheduler和DB Executor，并完成Schema备份。

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET SQLBLANKLINES ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER SESSION SET TIME_ZONE = '+00:00';
ALTER SESSION SET DDL_LOCK_TIMEOUT = 60;

DECLARE
    l_schema_version NUMBER;
    l_contract_version VARCHAR2(64 CHAR);
BEGIN
    SELECT SCHEMA_VERSION, CONTRACT_VERSION
      INTO l_schema_version, l_contract_version
      FROM KBOT_V_OPS_SCHEMA_VERSION
     WHERE COMPONENT = 'AIOPS';
    IF NOT (
        (l_schema_version = 31 AND l_contract_version = 'aiops-oracle-v21')
        OR
        (l_schema_version = 32 AND l_contract_version = 'aiops-oracle-v22')
    ) THEN
        RAISE_APPLICATION_ERROR(
            -20081,
            '只允许从AIOPS Schema 31 / aiops-oracle-v21升级，'
            || '或续跑Schema 32 / aiops-oracle-v22'
        );
    END IF;
END;
/

DECLARE
    PROCEDURE create_table_if_missing(
        p_table_name VARCHAR2,
        p_ddl CLOB
    ) IS
        l_count PLS_INTEGER;
    BEGIN
        SELECT COUNT(*) INTO l_count FROM USER_TABLES
         WHERE TABLE_NAME = p_table_name;
        IF l_count = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
            DBMS_OUTPUT.PUT_LINE('已创建表 ' || p_table_name);
        END IF;
    END;
    PROCEDURE create_index_if_missing(
        p_index_name VARCHAR2,
        p_ddl CLOB
    ) IS
        l_count PLS_INTEGER;
    BEGIN
        SELECT COUNT(*) INTO l_count FROM USER_INDEXES
         WHERE INDEX_NAME = p_index_name;
        IF l_count = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
            DBMS_OUTPUT.PUT_LINE('已创建索引 ' || p_index_name);
        END IF;
    END;
    PROCEDURE add_constraint_if_missing(
        p_constraint_name VARCHAR2,
        p_ddl CLOB
    ) IS
        l_count PLS_INTEGER;
    BEGIN
        SELECT COUNT(*) INTO l_count FROM USER_CONSTRAINTS
         WHERE CONSTRAINT_NAME = p_constraint_name;
        IF l_count = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
            DBMS_OUTPUT.PUT_LINE('已创建外键 ' || p_constraint_name);
        END IF;
    END;
BEGIN
    create_table_if_missing('KBOT_OPS_KNOWLEDGE_ASSET', q'~
        CREATE TABLE KBOT_OPS_KNOWLEDGE_ASSET (
            ASSET_ID RAW(16) PRIMARY KEY,
            DOMAIN_ID NUMBER(38) NOT NULL,
            ASSET_KIND VARCHAR2(32 CHAR) NOT NULL,
            DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
            STATUS VARCHAR2(32 CHAR) NOT NULL,
            CURRENT_VERSION_ID RAW(16),
            SECURITY_LEVEL NUMBER(10) NOT NULL,
            CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
            UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
            CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
            CONSTRAINT FK_OPS_KNOW_ASSET_DOMAIN FOREIGN KEY (DOMAIN_ID)
                REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID)
        )~');
    create_table_if_missing('KBOT_OPS_KNOWLEDGE_VERSION', q'~
        CREATE TABLE KBOT_OPS_KNOWLEDGE_VERSION (
            ASSET_VERSION_ID RAW(16) PRIMARY KEY,
            ASSET_ID RAW(16) NOT NULL,
            VERSION_NO NUMBER(19) NOT NULL,
            STATUS VARCHAR2(32 CHAR) NOT NULL,
            SOURCE_HASH VARCHAR2(64 CHAR) NOT NULL,
            PROFILE_SCHEMA_VERSION VARCHAR2(64 CHAR),
            PROFILE_JSON JSON,
            EXTRACTION_WARNINGS_JSON JSON NOT NULL,
            PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE,
            RETIRED_AT TIMESTAMP(6) WITH TIME ZONE,
            CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
            CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
            CONSTRAINT FK_OPS_KNOW_VER_ASSET FOREIGN KEY (ASSET_ID)
                REFERENCES KBOT_OPS_KNOWLEDGE_ASSET (ASSET_ID)
        )~');
    add_constraint_if_missing(
        'FK_OPS_KNOW_ASSET_CUR_VER',
        'ALTER TABLE KBOT_OPS_KNOWLEDGE_ASSET ADD CONSTRAINT '
        || 'FK_OPS_KNOW_ASSET_CUR_VER FOREIGN KEY (CURRENT_VERSION_ID) '
        || 'REFERENCES KBOT_OPS_KNOWLEDGE_VERSION (ASSET_VERSION_ID)'
    );
    create_table_if_missing('KBOT_OPS_KNOWLEDGE_SCOPE', q'~
        CREATE TABLE KBOT_OPS_KNOWLEDGE_SCOPE (
            SCOPE_ID RAW(16) PRIMARY KEY,
            ASSET_VERSION_ID RAW(16) NOT NULL,
            SCOPE_KIND VARCHAR2(64 CHAR) NOT NULL,
            SCOPE_VALUE VARCHAR2(512 CHAR) NOT NULL,
            NORMALIZED_VALUE VARCHAR2(512 CHAR) NOT NULL,
            SOURCE_KIND VARCHAR2(32 CHAR) NOT NULL,
            SOURCE_LOCATOR_JSON JSON,
            CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT FK_OPS_KNOW_SCOPE_VER FOREIGN KEY (ASSET_VERSION_ID)
                REFERENCES KBOT_OPS_KNOWLEDGE_VERSION (ASSET_VERSION_ID)
        )~');
    create_table_if_missing('KBOT_OPS_KNOWLEDGE_SOURCE', q'~
        CREATE TABLE KBOT_OPS_KNOWLEDGE_SOURCE (
            SOURCE_ID RAW(16) PRIMARY KEY,
            ASSET_VERSION_ID RAW(16) NOT NULL,
            SOURCE_KIND VARCHAR2(32 CHAR) NOT NULL,
            SOURCE_REPORT_ID RAW(16),
            SOURCE_RUN_ID RAW(16),
            SOURCE_ARTIFACT_ID RAW(16),
            SOURCE_EXTERNAL_ID VARCHAR2(512 CHAR),
            CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
            SOURCE_LOCATOR_JSON JSON,
            CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT FK_OPS_KNOW_SOURCE_VER FOREIGN KEY (ASSET_VERSION_ID)
                REFERENCES KBOT_OPS_KNOWLEDGE_VERSION (ASSET_VERSION_ID),
            CONSTRAINT FK_OPS_KNOW_SOURCE_REPORT FOREIGN KEY (SOURCE_REPORT_ID)
                REFERENCES KBOT_OPS_REPORT (REPORT_ID),
            CONSTRAINT FK_OPS_KNOW_SOURCE_RUN FOREIGN KEY (SOURCE_RUN_ID)
                REFERENCES KBOT_OPS_RUN (OPS_RUN_ID),
            CONSTRAINT FK_OPS_KNOW_SOURCE_ART FOREIGN KEY (SOURCE_ARTIFACT_ID)
                REFERENCES KBOT_OPS_ARTIFACT (ARTIFACT_ID)
        )~');
    create_table_if_missing('KBOT_OPS_KNOWLEDGE_INDEX', q'~
        CREATE TABLE KBOT_OPS_KNOWLEDGE_INDEX (
            INDEX_REF_ID RAW(16) PRIMARY KEY,
            ASSET_VERSION_ID RAW(16) NOT NULL,
            COLLECTION_ID RAW(16) NOT NULL,
            BUNDLE_ID RAW(16) NOT NULL,
            BUNDLE_REVISION_ID RAW(16) NOT NULL,
            INDEX_STATUS VARCHAR2(32 CHAR) NOT NULL,
            EXPECTED_ROW_VERSION NUMBER(19),
            LAST_CHECKED_AT TIMESTAMP(6) WITH TIME ZONE,
            ERROR_CODE VARCHAR2(128 CHAR),
            ERROR_SUMMARY VARCHAR2(2000 CHAR),
            CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT FK_OPS_KNOW_INDEX_VER FOREIGN KEY (ASSET_VERSION_ID)
                REFERENCES KBOT_OPS_KNOWLEDGE_VERSION (ASSET_VERSION_ID)
        )~');
    create_table_if_missing('KBOT_OPS_KNOWLEDGE_REVIEW', q'~
        CREATE TABLE KBOT_OPS_KNOWLEDGE_REVIEW (
            REVIEW_ID RAW(16) PRIMARY KEY,
            ASSET_VERSION_ID RAW(16) NOT NULL,
            DECISION VARCHAR2(32 CHAR) NOT NULL,
            REVIEWER_ID VARCHAR2(256 CHAR) NOT NULL,
            COMMENT_TEXT VARCHAR2(2000 CHAR),
            BEFORE_STATUS VARCHAR2(32 CHAR) NOT NULL,
            AFTER_STATUS VARCHAR2(32 CHAR) NOT NULL,
            CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT FK_OPS_KNOW_REVIEW_VER FOREIGN KEY (ASSET_VERSION_ID)
                REFERENCES KBOT_OPS_KNOWLEDGE_VERSION (ASSET_VERSION_ID)
        )~');

    create_index_if_missing('IX_OPS_KNOW_ASSET_SCOPE',
        'CREATE INDEX IX_OPS_KNOW_ASSET_SCOPE ON KBOT_OPS_KNOWLEDGE_ASSET '
        || '(DOMAIN_ID, ASSET_KIND, STATUS, UPDATED_AT)');
    create_index_if_missing('IX_OPS_KNOW_VER_ASSET',
        'CREATE INDEX IX_OPS_KNOW_VER_ASSET ON KBOT_OPS_KNOWLEDGE_VERSION '
        || '(ASSET_ID, VERSION_NO)');
    create_index_if_missing('IX_OPS_KNOW_VER_STATUS',
        'CREATE INDEX IX_OPS_KNOW_VER_STATUS ON KBOT_OPS_KNOWLEDGE_VERSION '
        || '(STATUS, CREATED_AT)');
    create_index_if_missing('IX_OPS_KNOW_SCOPE_LOOKUP',
        'CREATE INDEX IX_OPS_KNOW_SCOPE_LOOKUP ON KBOT_OPS_KNOWLEDGE_SCOPE '
        || '(SCOPE_KIND, NORMALIZED_VALUE, ASSET_VERSION_ID)');
    create_index_if_missing('IX_OPS_KNOW_SCOPE_VER',
        'CREATE INDEX IX_OPS_KNOW_SCOPE_VER ON KBOT_OPS_KNOWLEDGE_SCOPE '
        || '(ASSET_VERSION_ID)');
    create_index_if_missing('IX_OPS_KNOW_SOURCE_VER',
        'CREATE INDEX IX_OPS_KNOW_SOURCE_VER ON KBOT_OPS_KNOWLEDGE_SOURCE '
        || '(ASSET_VERSION_ID)');
    create_index_if_missing('IX_OPS_KNOW_SOURCE_REPORT',
        'CREATE INDEX IX_OPS_KNOW_SOURCE_REPORT ON KBOT_OPS_KNOWLEDGE_SOURCE '
        || '(SOURCE_REPORT_ID)');
    create_index_if_missing('IX_OPS_KNOW_SOURCE_RUN',
        'CREATE INDEX IX_OPS_KNOW_SOURCE_RUN ON KBOT_OPS_KNOWLEDGE_SOURCE '
        || '(SOURCE_RUN_ID)');
    create_index_if_missing('IX_OPS_KNOW_SOURCE_ART',
        'CREATE INDEX IX_OPS_KNOW_SOURCE_ART ON KBOT_OPS_KNOWLEDGE_SOURCE '
        || '(SOURCE_ARTIFACT_ID)');
    create_index_if_missing('IX_OPS_KNOW_INDEX_VER',
        'CREATE INDEX IX_OPS_KNOW_INDEX_VER ON KBOT_OPS_KNOWLEDGE_INDEX '
        || '(ASSET_VERSION_ID)');
    create_index_if_missing('IX_OPS_KNOW_INDEX_STATUS',
        'CREATE INDEX IX_OPS_KNOW_INDEX_STATUS ON KBOT_OPS_KNOWLEDGE_INDEX '
        || '(INDEX_STATUS, UPDATED_AT)');
    create_index_if_missing('IX_OPS_KNOW_REVIEW_QUEUE',
        'CREATE INDEX IX_OPS_KNOW_REVIEW_QUEUE ON KBOT_OPS_KNOWLEDGE_REVIEW '
        || '(AFTER_STATUS, CREATED_AT)');
    create_index_if_missing('IX_OPS_KNOW_REVIEW_VER',
        'CREATE INDEX IX_OPS_KNOW_REVIEW_VER ON KBOT_OPS_KNOWLEDGE_REVIEW '
        || '(ASSET_VERSION_ID)');
END;
/

CREATE OR REPLACE VIEW KBOT_V_OPS_SCHEMA_VERSION AS
SELECT
    'AIOPS' AS COMPONENT,
    32 AS SCHEMA_VERSION,
    'aiops-oracle-v22' AS CONTRACT_VERSION
FROM DUAL;

DECLARE
    l_table_count PLS_INTEGER;
    l_business_constraint_count PLS_INTEGER;
    l_schema_version NUMBER;
    l_contract_version VARCHAR2(64 CHAR);
BEGIN
    SELECT COUNT(*) INTO l_table_count FROM USER_TABLES
     WHERE TABLE_NAME IN (
        'KBOT_OPS_KNOWLEDGE_ASSET', 'KBOT_OPS_KNOWLEDGE_VERSION',
        'KBOT_OPS_KNOWLEDGE_SCOPE', 'KBOT_OPS_KNOWLEDGE_SOURCE',
        'KBOT_OPS_KNOWLEDGE_INDEX', 'KBOT_OPS_KNOWLEDGE_REVIEW'
     );
    SELECT COUNT(*) INTO l_business_constraint_count FROM USER_CONSTRAINTS
     WHERE TABLE_NAME LIKE 'KBOT\_OPS\_KNOWLEDGE\_%' ESCAPE '\'
       AND (
            (CONSTRAINT_TYPE = 'C' AND GENERATED = 'USER NAME')
         OR CONSTRAINT_TYPE = 'U'
       );
    SELECT SCHEMA_VERSION, CONTRACT_VERSION
      INTO l_schema_version, l_contract_version
      FROM KBOT_V_OPS_SCHEMA_VERSION
     WHERE COMPONENT = 'AIOPS';
    IF l_table_count <> 6
       OR l_business_constraint_count <> 0
       OR l_schema_version <> 32
       OR l_contract_version <> 'aiops-oracle-v22' THEN
        RAISE_APPLICATION_ERROR(-20082, 'AIOps Schema 32升级后验证失败');
    END IF;
    DBMS_OUTPUT.PUT_LINE('AIOps Schema已升级到32 / aiops-oracle-v22。');
END;
/

COMMIT;
