-- AIOps Schema 22 -> 23 原地升级。
-- 影响范围：为 Oracle Target 增加预期/实测容器字段、MISCONFIGURED 状态并更新查询视图。
-- 数据保护：不删除表、不删除业务行，不修改历史运行、诊断、报告、附件或审计数据。
-- 安全收敛：既有 Oracle 直连 Target 无法从 Service Name 可靠判断 CDB/PDB；脚本会停用其
--           数据库直连和受控变更，但保留 Endpoint 与凭据引用，待人工指定容器后重新检查。
-- 前置条件：停止 AIOps API、Worker、Scheduler 和 DB Executor，避免 DDL 与运行时写入并发。
-- 恢复方式：Oracle DDL 会隐式提交；执行前必须完成 Schema 备份，失败时按备份恢复。

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET SQLBLANKLINES ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER SESSION SET TIME_ZONE = '+00:00';

DECLARE
    l_schema_version NUMBER;
    l_contract_version VARCHAR2(64 CHAR);
    l_connectivity_constraint_count PLS_INTEGER;
    l_new_column_count PLS_INTEGER;
BEGIN
    SELECT SCHEMA_VERSION, CONTRACT_VERSION
      INTO l_schema_version, l_contract_version
      FROM KBOT_V_OPS_SCHEMA_VERSION
     WHERE COMPONENT = 'AIOPS';

    IF l_schema_version <> 22
       OR l_contract_version <> 'aiops-oracle-v12' THEN
        RAISE_APPLICATION_ERROR(
            -20043,
            '只允许从 AIOPS Schema 22 / aiops-oracle-v12 升级'
        );
    END IF;

    SELECT COUNT(*)
      INTO l_connectivity_constraint_count
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'KBOT_OPS_TARGET'
       AND CONSTRAINT_NAME = 'CK_OPS_TARGET_CONNECTIVITY'
       AND CONSTRAINT_TYPE = 'C'
       AND STATUS = 'ENABLED'
       AND VALIDATED = 'VALIDATED';

    SELECT COUNT(*)
      INTO l_new_column_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'KBOT_OPS_TARGET'
       AND COLUMN_NAME IN (
           'ORACLE_CONTAINER_SCOPE',
           'ORACLE_PDB_NAME',
           'OBSERVED_ORACLE_CONTAINER_SCOPE',
           'OBSERVED_ORACLE_CONTAINER_NAME',
           'OBSERVED_ORACLE_CONTAINER_NUMBER',
           'OBSERVED_ORACLE_DATABASE_NAME'
       );

    IF l_connectivity_constraint_count <> 1 OR l_new_column_count <> 0 THEN
        RAISE_APPLICATION_ERROR(
            -20044,
            'KBOT_OPS_TARGET 不符合 Schema 22 前置条件'
        );
    END IF;

    DBMS_OUTPUT.PUT_LINE('Schema 22 前置检查通过。');
END;
/

ALTER TABLE KBOT_OPS_TARGET ADD (
    ORACLE_CONTAINER_SCOPE VARCHAR2(16 CHAR),
    ORACLE_PDB_NAME VARCHAR2(128 CHAR),
    OBSERVED_ORACLE_CONTAINER_SCOPE VARCHAR2(16 CHAR),
    OBSERVED_ORACLE_CONTAINER_NAME VARCHAR2(128 CHAR),
    OBSERVED_ORACLE_CONTAINER_NUMBER NUMBER(10),
    OBSERVED_ORACLE_DATABASE_NAME VARCHAR2(128 CHAR)
);

ALTER TABLE KBOT_OPS_TARGET DROP CONSTRAINT CK_OPS_TARGET_CONNECTIVITY;

ALTER TABLE KBOT_OPS_TARGET ADD CONSTRAINT CK_OPS_TARGET_CONNECTIVITY
    CHECK (CONNECTIVITY_STATUS IN (
        'UNKNOWN', 'CHECKING', 'CONNECTED', 'DEGRADED',
        'MISCONFIGURED', 'UNREACHABLE'
    ));

DECLARE
    l_reset_count PLS_INTEGER;
BEGIN
    UPDATE KBOT_OPS_TARGET
       SET STATUS = 'DISABLED',
           CONNECTIVITY_STATUS = 'MISCONFIGURED',
           READONLY_CONNECTION_ENABLED = 0,
           CONTROLLED_CHANGE_ENABLED = 0,
           CONNECTIVITY_CHECK_REQUEST_ID = NULL,
           CONNECTIVITY_CHECK_REQUESTED_AT = NULL,
           LAST_ERROR_CODE = 'ORACLE_CONTAINER_CONFIGURATION_REQUIRED',
           ROW_VERSION = ROW_VERSION + 1,
           CONNECTIVITY_VERSION = CONNECTIVITY_VERSION + 1,
           UPDATED_AT = SYSTIMESTAMP
     WHERE DB_TYPE = 'ORACLE'
       AND READONLY_CONNECTION_ENABLED = 1;
    l_reset_count := SQL%ROWCOUNT;
    DBMS_OUTPUT.PUT_LINE(
        '已安全停用既有 Oracle 直连 Target：' || l_reset_count
    );
END;
/

ALTER TABLE KBOT_OPS_TARGET ADD CONSTRAINT CK_OPS_TARGET_ORACLE_CONTAINER CHECK (
    (DB_TYPE = 'ORACLE' AND READONLY_CONNECTION_ENABLED = 1
     AND ORACLE_CONTAINER_SCOPE IS NOT NULL
     AND ORACLE_CONTAINER_SCOPE IN ('CDB_ROOT', 'PDB', 'NON_CDB')
     AND ((ORACLE_CONTAINER_SCOPE = 'PDB' AND ORACLE_PDB_NAME IS NOT NULL)
          OR (ORACLE_CONTAINER_SCOPE <> 'PDB' AND ORACLE_PDB_NAME IS NULL)))
    OR
    ((DB_TYPE <> 'ORACLE' OR READONLY_CONNECTION_ENABLED = 0)
     AND ORACLE_CONTAINER_SCOPE IS NULL AND ORACLE_PDB_NAME IS NULL)
);

ALTER TABLE KBOT_OPS_TARGET ADD CONSTRAINT CK_OPS_TARGET_OBS_CONTAINER CHECK (
    (OBSERVED_ORACLE_CONTAINER_SCOPE IS NULL
     AND OBSERVED_ORACLE_CONTAINER_NAME IS NULL
     AND OBSERVED_ORACLE_CONTAINER_NUMBER IS NULL
     AND OBSERVED_ORACLE_DATABASE_NAME IS NULL)
    OR
    (DB_TYPE = 'ORACLE'
     AND OBSERVED_ORACLE_CONTAINER_SCOPE IS NOT NULL
     AND OBSERVED_ORACLE_CONTAINER_SCOPE IN ('CDB_ROOT', 'PDB', 'NON_CDB')
     AND OBSERVED_ORACLE_CONTAINER_NAME IS NOT NULL
     AND OBSERVED_ORACLE_CONTAINER_NUMBER IS NOT NULL
     AND OBSERVED_ORACLE_CONTAINER_NUMBER >= 0
     AND OBSERVED_ORACLE_DATABASE_NAME IS NOT NULL)
);

CREATE OR REPLACE VIEW KBOT_V_OPS_TARGET AS
SELECT
    LOWER(
        SUBSTR(RAWTOHEX(t.TARGET_ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(t.TARGET_ID), 21, 12)
    ) AS TARGET_ID,
    t.DOMAIN_ID,
    t.DISPLAY_NAME,
    t.DB_TYPE,
    t.VERSION_CODE,
    t.ENVIRONMENT,
    t.DB_ROLE,
    t.ORACLE_CONTAINER_SCOPE,
    t.ORACLE_PDB_NAME,
    t.OBSERVED_ORACLE_CONTAINER_SCOPE,
    t.OBSERVED_ORACLE_CONTAINER_NAME,
    t.OBSERVED_ORACLE_CONTAINER_NUMBER,
    t.OBSERVED_ORACLE_DATABASE_NAME,
    t.SECURITY_LEVEL,
    t.STATUS,
    t.CONNECTIVITY_STATUS,
    t.OBSERVED_STATUS,
    t.LAST_OBSERVED_AT,
    t.LAST_CONNECTIVITY_CHECK_AT,
    t.LAST_ERROR_CODE,
    t.ROW_VERSION,
    t.CREATED_AT,
    t.UPDATED_AT,
    COUNT(tm.TARGET_SOURCE_BINDING_ID) AS SOURCE_BINDING_COUNT,
    SUM(CASE WHEN tm.HEALTH_STATUS = 'HEALTHY' THEN 1 ELSE 0 END)
        AS HEALTHY_SOURCE_BINDING_COUNT,
    SUM(CASE WHEN tm.HEALTH_STATUS IN ('DEGRADED', 'UNREACHABLE')
             THEN 1 ELSE 0 END) AS UNHEALTHY_SOURCE_BINDING_COUNT
FROM KBOT_OPS_TARGET t
LEFT JOIN KBOT_OPS_TARGET_SOURCE_BINDING tm
    ON tm.TARGET_ID = t.TARGET_ID
   AND tm.STATUS = 'ACTIVE'
GROUP BY
    t.TARGET_ID, t.DOMAIN_ID, t.DISPLAY_NAME,
    t.DB_TYPE, t.VERSION_CODE, t.ENVIRONMENT, t.DB_ROLE,
    t.ORACLE_CONTAINER_SCOPE, t.ORACLE_PDB_NAME,
    t.OBSERVED_ORACLE_CONTAINER_SCOPE, t.OBSERVED_ORACLE_CONTAINER_NAME,
    t.OBSERVED_ORACLE_CONTAINER_NUMBER, t.OBSERVED_ORACLE_DATABASE_NAME,
    t.SECURITY_LEVEL, t.STATUS, t.CONNECTIVITY_STATUS, t.OBSERVED_STATUS,
    t.LAST_OBSERVED_AT,
    t.LAST_CONNECTIVITY_CHECK_AT, t.LAST_ERROR_CODE, t.ROW_VERSION,
    t.CREATED_AT, t.UPDATED_AT;

CREATE OR REPLACE VIEW KBOT_V_OPS_SCHEMA_VERSION AS
SELECT
    'AIOPS' AS COMPONENT,
    23 AS SCHEMA_VERSION,
    'aiops-oracle-v13' AS CONTRACT_VERSION
FROM DUAL;

DECLARE
    l_schema_version NUMBER;
    l_contract_version VARCHAR2(64 CHAR);
    l_column_count PLS_INTEGER;
    l_constraint_count PLS_INTEGER;
    l_target_view_column_count PLS_INTEGER;
    l_invalid_object_count PLS_INTEGER;
    l_invalid_target_count PLS_INTEGER;
BEGIN
    SELECT SCHEMA_VERSION, CONTRACT_VERSION
      INTO l_schema_version, l_contract_version
      FROM KBOT_V_OPS_SCHEMA_VERSION
     WHERE COMPONENT = 'AIOPS';

    SELECT COUNT(*)
      INTO l_column_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'KBOT_OPS_TARGET'
       AND COLUMN_NAME IN (
           'ORACLE_CONTAINER_SCOPE',
           'ORACLE_PDB_NAME',
           'OBSERVED_ORACLE_CONTAINER_SCOPE',
           'OBSERVED_ORACLE_CONTAINER_NAME',
           'OBSERVED_ORACLE_CONTAINER_NUMBER',
           'OBSERVED_ORACLE_DATABASE_NAME'
       );

    SELECT COUNT(*)
      INTO l_constraint_count
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'KBOT_OPS_TARGET'
       AND CONSTRAINT_NAME IN (
           'CK_OPS_TARGET_CONNECTIVITY',
           'CK_OPS_TARGET_ORACLE_CONTAINER',
           'CK_OPS_TARGET_OBS_CONTAINER'
       )
       AND CONSTRAINT_TYPE = 'C'
       AND STATUS = 'ENABLED'
       AND VALIDATED = 'VALIDATED';

    SELECT COUNT(*)
      INTO l_target_view_column_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'KBOT_V_OPS_TARGET'
       AND COLUMN_NAME IN (
           'ORACLE_CONTAINER_SCOPE',
           'ORACLE_PDB_NAME',
           'OBSERVED_ORACLE_CONTAINER_SCOPE',
           'OBSERVED_ORACLE_CONTAINER_NAME',
           'OBSERVED_ORACLE_CONTAINER_NUMBER',
           'OBSERVED_ORACLE_DATABASE_NAME'
       );

    SELECT COUNT(*)
      INTO l_invalid_object_count
      FROM USER_OBJECTS
     WHERE OBJECT_NAME IN (
         'KBOT_OPS_TARGET',
         'KBOT_V_OPS_TARGET',
         'KBOT_V_OPS_SCHEMA_VERSION'
     )
       AND STATUS <> 'VALID';

    SELECT COUNT(*)
      INTO l_invalid_target_count
      FROM KBOT_OPS_TARGET
     WHERE DB_TYPE = 'ORACLE'
       AND READONLY_CONNECTION_ENABLED = 1
       AND ORACLE_CONTAINER_SCOPE IS NULL;

    IF l_schema_version <> 23
       OR l_contract_version <> 'aiops-oracle-v13'
       OR l_column_count <> 6
       OR l_constraint_count <> 3
       OR l_target_view_column_count <> 6
       OR l_invalid_object_count <> 0
       OR l_invalid_target_count <> 0 THEN
        RAISE_APPLICATION_ERROR(
            -20045,
            'Schema 23 升级校验失败，请从备份恢复并核对输出'
        );
    END IF;

    DBMS_OUTPUT.PUT_LINE(
        'AIOps Schema 已升级到 23 / aiops-oracle-v13。'
    );
END;
/
