-- 知识检索 / 多媒体创作工作台表结构原地升级。
-- 影响范围：
--   1. 知识检索 Agent 版本列从 ENABLED_CAPABILITIES_JSON 改为
--      KNOWLEDGE_CORE_ID + DATA_MODEL_IDS_JSON；
--   2. 新增 X Search 运行、事件、来源表；
--   3. 新增多媒体创作工作台绑定、Run、事件、提示词版本和资产表；
--   4. 删除已退役的智能工作台 KBOT_ASST_% 业务表，不迁移历史运行或图片元数据。
-- 数据保护：不删除知识检索既有 Agent 行；旧能力 JSON 列丢弃，问数模型绑定回填为空数组。
-- 前置条件：停止 Knowledge Retrieval、Media Studio、Main API 写入进程，并完成 Schema 备份。
--           需要已存在 KBOT_PLATFORM_DOMAIN。
-- 本脚本只改表结构，不写权限目录或初始管理员。表结构完成后依次执行：
--   conda run -n kbot4 python scripts/db/apply_oracle_schema.py --foundation-only
--   database/oracle/bootstrap/knowledge_retrieval/initial_admin.sql
--   database/oracle/bootstrap/media_studio/initial_admin.sql
-- 恢复方式：Oracle DDL 会隐式提交；失败时按备份恢复。

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET SQLBLANKLINES ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER SESSION SET TIME_ZONE = '+00:00';

DECLARE
    l_domain_count PLS_INTEGER;

    FUNCTION table_exists(p_name VARCHAR2) RETURN BOOLEAN IS
        l_count PLS_INTEGER;
    BEGIN
        SELECT COUNT(*) INTO l_count
          FROM USER_TABLES
         WHERE TABLE_NAME = p_name;
        RETURN l_count = 1;
    END;

    FUNCTION column_exists(p_table VARCHAR2, p_column VARCHAR2) RETURN BOOLEAN IS
        l_count PLS_INTEGER;
    BEGIN
        SELECT COUNT(*) INTO l_count
          FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table
           AND COLUMN_NAME = p_column;
        RETURN l_count = 1;
    END;

    PROCEDURE drop_legacy_table(p_name VARCHAR2) IS
    BEGIN
        IF table_exists(p_name) THEN
            EXECUTE IMMEDIATE
                'DROP TABLE ' || DBMS_ASSERT.SIMPLE_SQL_NAME(p_name)
                || ' CASCADE CONSTRAINTS PURGE';
            DBMS_OUTPUT.PUT_LINE('已删除 ' || p_name || '。');
        END IF;
    END;
BEGIN
    SELECT COUNT(*)
      INTO l_domain_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'KBOT_PLATFORM_DOMAIN';
    IF l_domain_count <> 1 THEN
        RAISE_APPLICATION_ERROR(-20060, '缺少 KBOT_PLATFORM_DOMAIN，不能升级产品 App 表');
    END IF;

    IF NOT table_exists('KBOT_KR_AGENT') THEN
        EXECUTE IMMEDIATE q'{
CREATE TABLE KBOT_KR_AGENT (
    AGENT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    CURRENT_VERSION_ID RAW(16),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_KR_AGENT_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_KR_AGENT_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT CK_KR_AGENT_STATUS CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED')),
    CONSTRAINT CK_KR_AGENT_ROW_VERSION CHECK (ROW_VERSION > 0)
)}';
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_KR_AGENT_SCOPE_STATUS ON KBOT_KR_AGENT (DOMAIN_ID, STATUS)';
        DBMS_OUTPUT.PUT_LINE('已创建 KBOT_KR_AGENT。');
    END IF;

    IF NOT table_exists('KBOT_KR_AGENT_VERSION') THEN
        EXECUTE IMMEDIATE q'{
CREATE TABLE KBOT_KR_AGENT_VERSION (
    AGENT_VERSION_ID RAW(16) PRIMARY KEY,
    AGENT_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    KNOWLEDGE_CORE_ID RAW(16),
    DATA_MODEL_IDS_JSON JSON NOT NULL,
    MODELS_JSON JSON NOT NULL,
    INSTRUCTION CLOB,
    CONFIG_JSON JSON NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_KR_AGENT_VERSION_AGENT FOREIGN KEY (AGENT_ID) REFERENCES KBOT_KR_AGENT (AGENT_ID) ON DELETE CASCADE,
    CONSTRAINT UK_KR_AGENT_VERSION UNIQUE (AGENT_ID, VERSION_NO)
)}';
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_KR_AGENT_VERSION_AGENT ON KBOT_KR_AGENT_VERSION (AGENT_ID)';
        DBMS_OUTPUT.PUT_LINE('已创建 KBOT_KR_AGENT_VERSION。');
    ELSE
        IF NOT column_exists('KBOT_KR_AGENT_VERSION', 'KNOWLEDGE_CORE_ID') THEN
            EXECUTE IMMEDIATE
                'ALTER TABLE KBOT_KR_AGENT_VERSION ADD (KNOWLEDGE_CORE_ID RAW(16))';
            DBMS_OUTPUT.PUT_LINE('已增加 KBOT_KR_AGENT_VERSION.KNOWLEDGE_CORE_ID。');
        END IF;

        IF NOT column_exists('KBOT_KR_AGENT_VERSION', 'DATA_MODEL_IDS_JSON') THEN
            EXECUTE IMMEDIATE
                'ALTER TABLE KBOT_KR_AGENT_VERSION ADD (DATA_MODEL_IDS_JSON JSON)';
            DBMS_OUTPUT.PUT_LINE('已增加 KBOT_KR_AGENT_VERSION.DATA_MODEL_IDS_JSON。');
        END IF;

        EXECUTE IMMEDIATE
            q'{UPDATE KBOT_KR_AGENT_VERSION
                  SET DATA_MODEL_IDS_JSON = JSON_ARRAY()
                WHERE DATA_MODEL_IDS_JSON IS NULL}';
        EXECUTE IMMEDIATE
            'ALTER TABLE KBOT_KR_AGENT_VERSION MODIFY DATA_MODEL_IDS_JSON NOT NULL';

        IF column_exists('KBOT_KR_AGENT_VERSION', 'ENABLED_CAPABILITIES_JSON') THEN
            EXECUTE IMMEDIATE
                'ALTER TABLE KBOT_KR_AGENT_VERSION DROP COLUMN ENABLED_CAPABILITIES_JSON';
            DBMS_OUTPUT.PUT_LINE('已删除 KBOT_KR_AGENT_VERSION.ENABLED_CAPABILITIES_JSON。');
        END IF;
        DBMS_OUTPUT.PUT_LINE('已收敛 KBOT_KR_AGENT_VERSION 列。');
    END IF;

    DECLARE
        l_fk_count PLS_INTEGER;
    BEGIN
        SELECT COUNT(*) INTO l_fk_count
          FROM USER_CONSTRAINTS
         WHERE TABLE_NAME = 'KBOT_KR_AGENT'
           AND CONSTRAINT_NAME = 'FK_KR_AGENT_CURRENT_VERSION';
        IF l_fk_count = 0 THEN
            EXECUTE IMMEDIATE
                'ALTER TABLE KBOT_KR_AGENT ADD CONSTRAINT FK_KR_AGENT_CURRENT_VERSION
                    FOREIGN KEY (CURRENT_VERSION_ID)
                    REFERENCES KBOT_KR_AGENT_VERSION (AGENT_VERSION_ID)';
            DBMS_OUTPUT.PUT_LINE('已补齐 FK_KR_AGENT_CURRENT_VERSION。');
        END IF;
    END;

    IF NOT table_exists('KBOT_KR_RESEARCH_RUN') THEN
        EXECUTE IMMEDIATE q'{
CREATE TABLE KBOT_KR_RESEARCH_RUN (
    RUN_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    KIND VARCHAR2(32 CHAR) NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'ACCEPTED' NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    REQUEST_ID VARCHAR2(128 CHAR) NOT NULL,
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    MODEL_ID RAW(16) NOT NULL,
    MODEL_SNAPSHOT_JSON JSON NOT NULL,
    REQUEST_JSON JSON NOT NULL,
    RESULT_JSON JSON,
    USAGE_JSON JSON,
    PROVIDER_REQUEST_ID VARCHAR2(256 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KR_RESEARCH_IDEMP UNIQUE (DOMAIN_ID, ACTOR_ID, IDEMPOTENCY_KEY),
    CONSTRAINT UK_KR_RESEARCH_SCOPE UNIQUE (RUN_ID, DOMAIN_ID),
    CONSTRAINT FK_KR_RESEARCH_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_KR_RESEARCH_KIND CHECK (KIND = 'X_SEARCH'),
    CONSTRAINT CK_KR_RESEARCH_STATUS CHECK (STATUS IN ('ACCEPTED', 'SEARCHING', 'ORGANIZING_SOURCES', 'COMPOSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT CK_KR_RESEARCH_VERSION CHECK (ROW_VERSION > 0)
)}';
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_KR_RESEARCH_DOMAIN_TIME ON KBOT_KR_RESEARCH_RUN (DOMAIN_ID, CREATED_AT)';
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_KR_RESEARCH_CLAIM ON KBOT_KR_RESEARCH_RUN (STATUS, LEASE_UNTIL)';
        DBMS_OUTPUT.PUT_LINE('已创建 KBOT_KR_RESEARCH_RUN。');
    END IF;

    IF NOT table_exists('KBOT_KR_RESEARCH_EVENT') THEN
        EXECUTE IMMEDIATE q'{
CREATE TABLE KBOT_KR_RESEARCH_EVENT (
    EVENT_ID RAW(16) PRIMARY KEY,
    RUN_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    SEQUENCE_NO NUMBER(10) NOT NULL,
    STAGE VARCHAR2(32 CHAR) NOT NULL,
    MESSAGE VARCHAR2(1000 CHAR),
    PAYLOAD_JSON JSON,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KR_RESEARCH_EVENT_SEQ UNIQUE (RUN_ID, SEQUENCE_NO),
    CONSTRAINT FK_KR_RESEARCH_EVENT_RUN FOREIGN KEY (RUN_ID, DOMAIN_ID) REFERENCES KBOT_KR_RESEARCH_RUN (RUN_ID, DOMAIN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_KR_RESEARCH_EVENT_STAGE CHECK (STAGE IN ('ACCEPTED', 'SEARCHING', 'ORGANIZING_SOURCES', 'COMPOSING', 'COMPLETED', 'FAILED'))
)}';
        DBMS_OUTPUT.PUT_LINE('已创建 KBOT_KR_RESEARCH_EVENT。');
    END IF;

    IF NOT table_exists('KBOT_KR_X_SOURCE') THEN
        EXECUTE IMMEDIATE q'{
CREATE TABLE KBOT_KR_X_SOURCE (
    SOURCE_ID RAW(16) PRIMARY KEY,
    RUN_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_ORDER NUMBER(10) NOT NULL,
    CITATION_LABEL VARCHAR2(16 CHAR) NOT NULL,
    PROVIDER_CITATION_ID VARCHAR2(256 CHAR) NOT NULL,
    CANONICAL_URL VARCHAR2(2048 CHAR) NOT NULL,
    TITLE VARCHAR2(512 CHAR),
    EXCERPT VARCHAR2(4000 CHAR),
    AUTHOR_HANDLE VARCHAR2(128 CHAR),
    PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE,
    RETRIEVED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KR_X_SOURCE_LABEL UNIQUE (RUN_ID, CITATION_LABEL),
    CONSTRAINT FK_KR_X_SOURCE_RUN FOREIGN KEY (RUN_ID, DOMAIN_ID) REFERENCES KBOT_KR_RESEARCH_RUN (RUN_ID, DOMAIN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_KR_X_SOURCE_ORDER CHECK (DISPLAY_ORDER > 0)
)}';
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_KR_X_SOURCE_RUN ON KBOT_KR_X_SOURCE (RUN_ID, DISPLAY_ORDER)';
        DBMS_OUTPUT.PUT_LINE('已创建 KBOT_KR_X_SOURCE。');
    END IF;

    IF NOT table_exists('KBOT_MEDIA_MODEL_BINDING') THEN
        EXECUTE IMMEDIATE q'{
CREATE TABLE KBOT_MEDIA_MODEL_BINDING (
    BINDING_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    ROLE VARCHAR2(32 CHAR) NOT NULL,
    MODEL_ID RAW(16) NOT NULL,
    MODEL_SNAPSHOT_JSON JSON NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MEDIA_BINDING_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_MEDIA_BINDING_ROLE UNIQUE (DOMAIN_ID, ROLE),
    CONSTRAINT CK_MEDIA_BINDING_ROLE CHECK (ROLE = 'IMAGE_GENERATION'),
    CONSTRAINT CK_MEDIA_BINDING_VERSION CHECK (ROW_VERSION > 0)
)}';
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_MEDIA_BINDING_MODEL ON KBOT_MEDIA_MODEL_BINDING (MODEL_ID)';
        DBMS_OUTPUT.PUT_LINE('已创建 KBOT_MEDIA_MODEL_BINDING。');
    END IF;

    IF NOT table_exists('KBOT_MEDIA_RUN') THEN
        EXECUTE IMMEDIATE q'{
CREATE TABLE KBOT_MEDIA_RUN (
    RUN_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    KIND VARCHAR2(32 CHAR) NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'ACCEPTED' NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    REQUEST_ID VARCHAR2(128 CHAR) NOT NULL,
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    MODEL_ID RAW(16) NOT NULL,
    MODEL_SNAPSHOT_JSON JSON NOT NULL,
    REQUEST_JSON JSON NOT NULL,
    RESULT_JSON JSON,
    USAGE_JSON JSON,
    PROVIDER_REQUEST_ID VARCHAR2(256 CHAR),
    PROMPT_REVISION_ID RAW(16),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_MEDIA_RUN_IDEMP UNIQUE (DOMAIN_ID, ACTOR_ID, IDEMPOTENCY_KEY),
    CONSTRAINT UK_MEDIA_RUN_SCOPE UNIQUE (RUN_ID, DOMAIN_ID),
    CONSTRAINT FK_MEDIA_RUN_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_MEDIA_RUN_KIND CHECK (KIND IN ('IMAGE_GENERATION', 'IMAGE_EDIT')),
    CONSTRAINT CK_MEDIA_RUN_STATUS CHECK (STATUS IN ('ACCEPTED', 'GENERATING', 'COMPLETED', 'REJECTED', 'FAILED')),
    CONSTRAINT CK_MEDIA_RUN_VERSION CHECK (ROW_VERSION > 0)
)}';
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_MEDIA_RUN_DOMAIN_TIME ON KBOT_MEDIA_RUN (DOMAIN_ID, CREATED_AT)';
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_MEDIA_RUN_CLAIM ON KBOT_MEDIA_RUN (STATUS, LEASE_UNTIL)';
        DBMS_OUTPUT.PUT_LINE('已创建 KBOT_MEDIA_RUN。');
    END IF;

    IF NOT table_exists('KBOT_MEDIA_RUN_EVENT') THEN
        EXECUTE IMMEDIATE q'{
CREATE TABLE KBOT_MEDIA_RUN_EVENT (
    EVENT_ID RAW(16) PRIMARY KEY,
    RUN_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    SEQUENCE_NO NUMBER(10) NOT NULL,
    STAGE VARCHAR2(32 CHAR) NOT NULL,
    MESSAGE VARCHAR2(1000 CHAR),
    PAYLOAD_JSON JSON,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_MEDIA_EVENT_SEQ UNIQUE (RUN_ID, SEQUENCE_NO),
    CONSTRAINT FK_MEDIA_EVENT_RUN FOREIGN KEY (RUN_ID, DOMAIN_ID) REFERENCES KBOT_MEDIA_RUN (RUN_ID, DOMAIN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MEDIA_EVENT_STAGE CHECK (STAGE IN ('ACCEPTED', 'GENERATING', 'COMPLETED', 'REJECTED', 'FAILED'))
)}';
        DBMS_OUTPUT.PUT_LINE('已创建 KBOT_MEDIA_RUN_EVENT。');
    END IF;

    IF NOT table_exists('KBOT_MEDIA_PROMPT_REVISION') THEN
        EXECUTE IMMEDIATE q'{
CREATE TABLE KBOT_MEDIA_PROMPT_REVISION (
    PROMPT_REVISION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    RUN_ID RAW(16),
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    PROMPT CLOB NOT NULL,
    ASPECT_RATIO VARCHAR2(16 CHAR) NOT NULL,
    IMAGE_COUNT NUMBER(2) DEFAULT 1 NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MEDIA_PROMPT_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_MEDIA_PROMPT_RUN FOREIGN KEY (RUN_ID) REFERENCES KBOT_MEDIA_RUN (RUN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MEDIA_PROMPT_COUNT CHECK (IMAGE_COUNT BETWEEN 1 AND 4),
    CONSTRAINT CK_MEDIA_PROMPT_VERSION CHECK (VERSION_NO > 0)
)}';
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_MEDIA_PROMPT_RUN ON KBOT_MEDIA_PROMPT_REVISION (RUN_ID)';
        DBMS_OUTPUT.PUT_LINE('已创建 KBOT_MEDIA_PROMPT_REVISION。');
    END IF;

    IF NOT table_exists('KBOT_MEDIA_ASSET') THEN
        EXECUTE IMMEDIATE q'{
CREATE TABLE KBOT_MEDIA_ASSET (
    ASSET_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    RUN_ID RAW(16) NOT NULL,
    PROMPT_REVISION_ID RAW(16),
    OBJECT_KEY VARCHAR2(1024 CHAR) NOT NULL,
    MIME_TYPE VARCHAR2(64 CHAR) NOT NULL,
    BYTE_SIZE NUMBER(19) NOT NULL,
    CONTENT_SHA256 VARCHAR2(64 CHAR) NOT NULL,
    WIDTH NUMBER(10),
    HEIGHT NUMBER(10),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'READY' NOT NULL,
    PROVIDER_ARTIFACT_ID VARCHAR2(256 CHAR),
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MEDIA_ASSET_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_MEDIA_ASSET_RUN FOREIGN KEY (RUN_ID, DOMAIN_ID) REFERENCES KBOT_MEDIA_RUN (RUN_ID, DOMAIN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MEDIA_ASSET_STATUS CHECK (STATUS IN ('READY', 'REJECTED', 'FAILED')),
    CONSTRAINT CK_MEDIA_ASSET_SIZE CHECK (BYTE_SIZE > 0)
)}';
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_MEDIA_ASSET_DOMAIN ON KBOT_MEDIA_ASSET (DOMAIN_ID, CREATED_AT)';
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_MEDIA_ASSET_RUN ON KBOT_MEDIA_ASSET (RUN_ID)';
        DBMS_OUTPUT.PUT_LINE('已创建 KBOT_MEDIA_ASSET。');
    END IF;

    drop_legacy_table('KBOT_ASST_MEDIA_ASSET');
    drop_legacy_table('KBOT_ASST_PROMPT_REVISION');
    drop_legacy_table('KBOT_ASST_X_SOURCE');
    drop_legacy_table('KBOT_ASST_RUN_EVENT');
    drop_legacy_table('KBOT_ASST_RUN');
    drop_legacy_table('KBOT_ASST_MODEL_BINDING');
    drop_legacy_table('KBOT_ASST_AGENT_VERSION');
    drop_legacy_table('KBOT_ASST_AGENT');
END;
/

DECLARE
    l_missing VARCHAR2(4000);
    l_legacy VARCHAR2(4000);
    l_kr_old_column PLS_INTEGER;
    l_kr_new_column PLS_INTEGER;
    l_invalid_object_count PLS_INTEGER;
BEGIN
    SELECT LISTAGG(required.TABLE_NAME, ', ') WITHIN GROUP (ORDER BY required.TABLE_NAME)
      INTO l_missing
      FROM (
        SELECT 'KBOT_KR_AGENT' TABLE_NAME FROM DUAL UNION ALL
        SELECT 'KBOT_KR_AGENT_VERSION' FROM DUAL UNION ALL
        SELECT 'KBOT_KR_RESEARCH_RUN' FROM DUAL UNION ALL
        SELECT 'KBOT_KR_RESEARCH_EVENT' FROM DUAL UNION ALL
        SELECT 'KBOT_KR_X_SOURCE' FROM DUAL UNION ALL
        SELECT 'KBOT_MEDIA_MODEL_BINDING' FROM DUAL UNION ALL
        SELECT 'KBOT_MEDIA_RUN' FROM DUAL UNION ALL
        SELECT 'KBOT_MEDIA_RUN_EVENT' FROM DUAL UNION ALL
        SELECT 'KBOT_MEDIA_PROMPT_REVISION' FROM DUAL UNION ALL
        SELECT 'KBOT_MEDIA_ASSET' FROM DUAL
      ) required
      LEFT JOIN USER_TABLES existing ON existing.TABLE_NAME = required.TABLE_NAME
     WHERE existing.TABLE_NAME IS NULL;

    SELECT LISTAGG(legacy.TABLE_NAME, ', ') WITHIN GROUP (ORDER BY legacy.TABLE_NAME)
      INTO l_legacy
      FROM (
        SELECT 'KBOT_ASST_AGENT' TABLE_NAME FROM DUAL UNION ALL
        SELECT 'KBOT_ASST_AGENT_VERSION' FROM DUAL UNION ALL
        SELECT 'KBOT_ASST_MODEL_BINDING' FROM DUAL UNION ALL
        SELECT 'KBOT_ASST_RUN' FROM DUAL UNION ALL
        SELECT 'KBOT_ASST_RUN_EVENT' FROM DUAL UNION ALL
        SELECT 'KBOT_ASST_X_SOURCE' FROM DUAL UNION ALL
        SELECT 'KBOT_ASST_PROMPT_REVISION' FROM DUAL UNION ALL
        SELECT 'KBOT_ASST_MEDIA_ASSET' FROM DUAL
      ) legacy
      JOIN USER_TABLES existing ON existing.TABLE_NAME = legacy.TABLE_NAME;

    SELECT COUNT(*) INTO l_kr_old_column
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'KBOT_KR_AGENT_VERSION'
       AND COLUMN_NAME = 'ENABLED_CAPABILITIES_JSON';

    SELECT COUNT(*) INTO l_kr_new_column
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'KBOT_KR_AGENT_VERSION'
       AND COLUMN_NAME IN ('KNOWLEDGE_CORE_ID', 'DATA_MODEL_IDS_JSON');

    SELECT COUNT(*)
      INTO l_invalid_object_count
      FROM USER_OBJECTS
     WHERE OBJECT_NAME IN (
         'KBOT_KR_AGENT', 'KBOT_KR_AGENT_VERSION',
         'KBOT_KR_RESEARCH_RUN', 'KBOT_KR_RESEARCH_EVENT', 'KBOT_KR_X_SOURCE',
         'KBOT_MEDIA_MODEL_BINDING', 'KBOT_MEDIA_RUN', 'KBOT_MEDIA_RUN_EVENT',
         'KBOT_MEDIA_PROMPT_REVISION', 'KBOT_MEDIA_ASSET'
     )
       AND STATUS <> 'VALID';

    IF l_missing IS NOT NULL
       OR l_legacy IS NOT NULL
       OR l_kr_old_column <> 0
       OR l_kr_new_column <> 2
       OR l_invalid_object_count <> 0 THEN
        RAISE_APPLICATION_ERROR(
            -20061,
            '知识检索 / 多媒体创作表结构校验失败：缺表='
            || NVL(l_missing, '-')
            || '，残留智能工作台表='
            || NVL(l_legacy, '-')
        );
    END IF;

    DBMS_OUTPUT.PUT_LINE('知识检索与多媒体创作工作台表结构已就绪。');
END;
/
