-- AIOps Schema 33 -> 34 原地升级。
-- 影响范围：为恢复目标增加显式必需备份来源集合；保留全部既有目标与演练。
-- 前置条件：当前必须是 Schema 33 / aiops-oracle-v23，或已部分升级到 Schema 34。

SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER SESSION SET TIME_ZONE = '+00:00';
ALTER SESSION SET DDL_LOCK_TIMEOUT = 60;

DECLARE
    l_schema_version NUMBER;
    l_contract_version VARCHAR2(64 CHAR);
    l_column_count PLS_INTEGER;
BEGIN
    SELECT SCHEMA_VERSION, CONTRACT_VERSION
      INTO l_schema_version, l_contract_version
      FROM KBOT_V_OPS_SCHEMA_VERSION
     WHERE COMPONENT = 'AIOPS';
    IF NOT (
        (l_schema_version = 33 AND l_contract_version = 'aiops-oracle-v23')
        OR
        (l_schema_version = 34 AND l_contract_version = 'aiops-oracle-v24')
    ) THEN
        RAISE_APPLICATION_ERROR(-20091, '只允许从 AIOPS Schema 33 升级或续跑 Schema 34');
    END IF;

    SELECT COUNT(*) INTO l_column_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'KBOT_OPS_RECOVERY_PROFILE'
       AND COLUMN_NAME = 'REQUIRED_BACKUP_SOURCE_TYPES_JSON';
    IF l_column_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE KBOT_OPS_RECOVERY_PROFILE '
            || 'ADD (REQUIRED_BACKUP_SOURCE_TYPES_JSON JSON)';
    END IF;
END;
/

UPDATE KBOT_OPS_RECOVERY_PROFILE profile
   SET REQUIRED_BACKUP_SOURCE_TYPES_JSON = (
       SELECT CASE target.DB_TYPE
           WHEN 'ORACLE' THEN JSON_ARRAY('ORACLE_RMAN')
           WHEN 'POSTGRESQL' THEN JSON_ARRAY('POSTGRESQL_PGBACKREST')
           WHEN 'MYSQL' THEN JSON_ARRAY('MYSQL_XTRABACKUP')
           ELSE JSON_ARRAY('THIRD_PARTY_BACKUP')
       END
         FROM KBOT_OPS_TARGET target
        WHERE target.TARGET_ID = profile.TARGET_ID
   )
 WHERE REQUIRED_BACKUP_SOURCE_TYPES_JSON IS NULL;

ALTER TABLE KBOT_OPS_RECOVERY_PROFILE
    MODIFY (REQUIRED_BACKUP_SOURCE_TYPES_JSON NOT NULL);

CREATE OR REPLACE VIEW KBOT_V_OPS_SCHEMA_VERSION AS
SELECT
    'AIOPS' AS COMPONENT,
    34 AS SCHEMA_VERSION,
    'aiops-oracle-v24' AS CONTRACT_VERSION
FROM DUAL;

COMMIT;

SELECT COMPONENT, SCHEMA_VERSION, CONTRACT_VERSION
  FROM KBOT_V_OPS_SCHEMA_VERSION;
