# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dao.metadata_service.kbot_md_sys_conf_pb2 as kbot__md__sys__conf__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kbot_md_sys_conf_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KbotMdSysConfServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/kbot_md_sys_conf.KbotMdSysConfService/Create',
                request_serializer=kbot__md__sys__conf__pb2.KbotMdSysConf.SerializeToString,
                response_deserializer=kbot__md__sys__conf__pb2.KbotMdSysConf.FromString,
                _registered_method=True)
        self.GetById = channel.unary_unary(
                '/kbot_md_sys_conf.KbotMdSysConfService/GetById',
                request_serializer=kbot__md__sys__conf__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=kbot__md__sys__conf__pb2.KbotMdSysConf.FromString,
                _registered_method=True)
        self.GetAll = channel.unary_unary(
                '/kbot_md_sys_conf.KbotMdSysConfService/GetAll',
                request_serializer=kbot__md__sys__conf__pb2.Empty.SerializeToString,
                response_deserializer=kbot__md__sys__conf__pb2.KbotMdSysConfList.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/kbot_md_sys_conf.KbotMdSysConfService/Update',
                request_serializer=kbot__md__sys__conf__pb2.KbotMdSysConf.SerializeToString,
                response_deserializer=kbot__md__sys__conf__pb2.KbotMdSysConf.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/kbot_md_sys_conf.KbotMdSysConfService/Delete',
                request_serializer=kbot__md__sys__conf__pb2.DeleteRequest.SerializeToString,
                response_deserializer=kbot__md__sys__conf__pb2.DeleteResponse.FromString,
                _registered_method=True)


class KbotMdSysConfServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KbotMdSysConfServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=kbot__md__sys__conf__pb2.KbotMdSysConf.FromString,
                    response_serializer=kbot__md__sys__conf__pb2.KbotMdSysConf.SerializeToString,
            ),
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=kbot__md__sys__conf__pb2.GetByIdRequest.FromString,
                    response_serializer=kbot__md__sys__conf__pb2.KbotMdSysConf.SerializeToString,
            ),
            'GetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=kbot__md__sys__conf__pb2.Empty.FromString,
                    response_serializer=kbot__md__sys__conf__pb2.KbotMdSysConfList.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=kbot__md__sys__conf__pb2.KbotMdSysConf.FromString,
                    response_serializer=kbot__md__sys__conf__pb2.KbotMdSysConf.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kbot__md__sys__conf__pb2.DeleteRequest.FromString,
                    response_serializer=kbot__md__sys__conf__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kbot_md_sys_conf.KbotMdSysConfService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kbot_md_sys_conf.KbotMdSysConfService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KbotMdSysConfService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kbot_md_sys_conf.KbotMdSysConfService/Create',
            kbot__md__sys__conf__pb2.KbotMdSysConf.SerializeToString,
            kbot__md__sys__conf__pb2.KbotMdSysConf.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kbot_md_sys_conf.KbotMdSysConfService/GetById',
            kbot__md__sys__conf__pb2.GetByIdRequest.SerializeToString,
            kbot__md__sys__conf__pb2.KbotMdSysConf.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kbot_md_sys_conf.KbotMdSysConfService/GetAll',
            kbot__md__sys__conf__pb2.Empty.SerializeToString,
            kbot__md__sys__conf__pb2.KbotMdSysConfList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kbot_md_sys_conf.KbotMdSysConfService/Update',
            kbot__md__sys__conf__pb2.KbotMdSysConf.SerializeToString,
            kbot__md__sys__conf__pb2.KbotMdSysConf.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kbot_md_sys_conf.KbotMdSysConfService/Delete',
            kbot__md__sys__conf__pb2.DeleteRequest.SerializeToString,
            kbot__md__sys__conf__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
