-- KBot 4.0 共享 Prompt Definition 与不可变版本。

CREATE TABLE KBOT_PLATFORM_PROMPT (
    PROMPT_ID RAW(16) PRIMARY KEY,
    PROMPT_KEY VARCHAR2(256 CHAR) NOT NULL,
    OWNER_SERVICE VARCHAR2(64 CHAR) NOT NULL,
    PURPOSE VARCHAR2(1000 CHAR) NOT NULL,
    ACTIVE_VERSION_ID RAW(16),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_PLATFORM_PROMPT_KEY UNIQUE (PROMPT_KEY),
    CONSTRAINT UK_PLATFORM_PROMPT_SCOPE UNIQUE
        (PROMPT_ID, OWNER_SERVICE),
    CONSTRAINT CK_PLATFORM_PROMPT_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_PLATFORM_PROMPT_OWNER
    ON KBOT_PLATFORM_PROMPT (OWNER_SERVICE, PROMPT_KEY);

CREATE TABLE KBOT_PLATFORM_PROMPT_VERSION (
    PROMPT_VERSION_ID RAW(16) PRIMARY KEY,
    PROMPT_ID RAW(16) NOT NULL,
    VERSION VARCHAR2(32 CHAR) NOT NULL,
    CONTENT CLOB NOT NULL,
    CONTENT_SHA256 VARCHAR2(64 CHAR) NOT NULL,
    INPUT_VARIABLES_JSON JSON NOT NULL,
    OUTPUT_SCHEMA_REF VARCHAR2(128 CHAR),
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    SOURCE VARCHAR2(16 CHAR) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_PLATFORM_PROMPT_VERSION UNIQUE (PROMPT_ID, VERSION),
    CONSTRAINT UK_PLT_PROMPT_VER_SCOPE UNIQUE
        (PROMPT_VERSION_ID, PROMPT_ID),
    CONSTRAINT FK_PLATFORM_PROMPT_VERSION_DEF FOREIGN KEY (PROMPT_ID)
        REFERENCES KBOT_PLATFORM_PROMPT (PROMPT_ID),
    CONSTRAINT CK_PLT_PROMPT_VER_STATUS CHECK
        (STATUS IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT CK_PLT_PROMPT_VER_SOURCE CHECK
        (SOURCE IN ('FILE_SEED', 'DATABASE')),
    CONSTRAINT CK_PLT_PROMPT_VER_HASH CHECK
        (LENGTH(CONTENT_SHA256) = 64)
);

CREATE INDEX IX_PLATFORM_PROMPT_VERSION_DEF
    ON KBOT_PLATFORM_PROMPT_VERSION (PROMPT_ID, STATUS, CREATED_AT);

ALTER TABLE KBOT_PLATFORM_PROMPT ADD CONSTRAINT FK_PLATFORM_PROMPT_ACTIVE
    FOREIGN KEY (ACTIVE_VERSION_ID, PROMPT_ID)
    REFERENCES KBOT_PLATFORM_PROMPT_VERSION (PROMPT_VERSION_ID, PROMPT_ID)
    DEFERRABLE INITIALLY DEFERRED;
