-- KBot 4.0 Main API 组合编排 Receipt；不复制领域实体或业务正文。

CREATE TABLE KBOT_COMPOSITION_RECEIPT (
    RECEIPT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    OPERATION VARCHAR2(80 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    REQUEST_HASH VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(32 CHAR) NOT NULL,
    RESOURCE_TYPE VARCHAR2(80 CHAR) NOT NULL,
    RESOURCE_ID VARCHAR2(256 CHAR),
    RESOURCE_VERSION VARCHAR2(128 CHAR),
    VERIFICATION_JSON JSON NOT NULL,
    ERROR_CODE VARCHAR2(128 CHAR),
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_COMPOSITION_IDEMPOTENCY UNIQUE
        (DOMAIN_ID, ACTOR_ID, OPERATION, IDEMPOTENCY_KEY),
    CONSTRAINT FK_COMPOSITION_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_COMPOSITION_STATUS CHECK (STATUS IN (
        'PRECHECKING', 'COMMAND_SUBMITTED', 'SUCCEEDED',
        'FAILED_PRECHECK', 'COMPENSATION_REQUIRED'
    )),
    CONSTRAINT CK_COMPOSITION_REQUEST_HASH CHECK (LENGTH(REQUEST_HASH) = 64),
    CONSTRAINT CK_COMPOSITION_ATTEMPT CHECK (ATTEMPT_COUNT >= 0),
    CONSTRAINT CK_COMPOSITION_VERSION CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_COMPOSITION_RESOURCE
    ON KBOT_COMPOSITION_RECEIPT
        (DOMAIN_ID, RESOURCE_TYPE, RESOURCE_ID, UPDATED_AT);

CREATE INDEX IX_COMPOSITION_RECOVERY
    ON KBOT_COMPOSITION_RECEIPT (STATUS, UPDATED_AT);
