-- KBot 4.0 统一数据库托管凭据。

CREATE TABLE KBOT_MANAGED_CREDENTIAL (
    CREDENTIAL_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    NAMESPACE VARCHAR2(64 CHAR) NOT NULL,
    CREDENTIAL_KIND VARCHAR2(64 CHAR) NOT NULL,
    EXTERNAL_KEY VARCHAR2(256 CHAR) NOT NULL,
    CIPHERTEXT BLOB NOT NULL,
    NONCE RAW(12) NOT NULL,
    KEY_VERSION VARCHAR2(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MANAGED_CREDENTIAL_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_MANAGED_CREDENTIAL_KEY UNIQUE
        (DOMAIN_ID, NAMESPACE, CREDENTIAL_KIND, EXTERNAL_KEY),
    CONSTRAINT UK_MANAGED_CREDENTIAL_SCOPE UNIQUE
        (CREDENTIAL_ID, DOMAIN_ID),
    CONSTRAINT CK_MANAGED_CREDENTIAL_STATUS
        CHECK (STATUS IN ('ACTIVE', 'DISABLED', 'REVOKED'))
);

CREATE INDEX IX_MANAGED_CREDENTIAL_SCOPE ON KBOT_MANAGED_CREDENTIAL
    (DOMAIN_ID, NAMESPACE, CREDENTIAL_KIND, STATUS);
