-- KBot 4.0 Knowledge Core：Collection、绑定与入库回执。
-- UUIDv7 由应用生成并以 RAW(16) 保存；本脚本只创建全新的 4.0 Schema。

CREATE TABLE KBOT_KC_COLLECTION (
    COLLECTION_ID RAW(16) PRIMARY KEY,
    APP_ID NUMBER(38) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    COLLECTION_KEY VARCHAR2(64 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    PARSER_LLM_MODEL_ID RAW(16) NOT NULL,
    PARSER_VLM_MODEL_ID RAW(16),
    RETRIEVAL_LLM_MODEL_ID RAW(16) NOT NULL,
    EMBEDDING_MODEL_ID RAW(16) NOT NULL,
    VISUAL_EMBEDDING_MODEL_ID RAW(16),
    STATUS VARCHAR2(24 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    DEFAULT_SECURITY_LEVEL NUMBER(3) DEFAULT 1 NOT NULL,
    METADATA_JSON JSON,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR),
    UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_COLLECTION_SCOPE_KEY UNIQUE (APP_ID, DOMAIN_ID, COLLECTION_KEY),
    CONSTRAINT CK_KC_COLLECTION_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED', 'DELETING', 'DELETION_FAILED')),
    CONSTRAINT CK_KC_COLLECTION_SECURITY CHECK (DEFAULT_SECURITY_LEVEL >= 0)
);

CREATE INDEX IX_KC_COLLECTION_SCOPE_STATUS
    ON KBOT_KC_COLLECTION (APP_ID, DOMAIN_ID, STATUS, DISPLAY_NAME);
CREATE INDEX IX_KC_COLLECTION_EMBED_MODEL
    ON KBOT_KC_COLLECTION (EMBEDDING_MODEL_ID);
CREATE INDEX IX_KC_COLLECTION_VISUAL_MODEL
    ON KBOT_KC_COLLECTION (VISUAL_EMBEDDING_MODEL_ID);

CREATE TABLE KBOT_KC_COLLECTION_BINDING (
    BINDING_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL,
    CONSUMER_TYPE VARCHAR2(32 CHAR) NOT NULL,
    CONSUMER_ID RAW(16) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    NOTE VARCHAR2(1000 CHAR),
    CREATED_BY VARCHAR2(256 CHAR),
    UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_BIND_CONSUMER_COLL UNIQUE (CONSUMER_TYPE, CONSUMER_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_BINDING_COLLECTION FOREIGN KEY (COLLECTION_ID)
        REFERENCES KBOT_KC_COLLECTION (COLLECTION_ID),
    CONSTRAINT CK_KC_BINDING_TYPE CHECK (CONSUMER_TYPE IN ('AGENT')),
    CONSTRAINT CK_KC_BINDING_STATUS CHECK (STATUS IN ('ACTIVE', 'REVOKED'))
);

CREATE INDEX IX_KC_BINDING_CONSUMER
    ON KBOT_KC_COLLECTION_BINDING (CONSUMER_TYPE, CONSUMER_ID, STATUS);
CREATE INDEX IX_KC_BINDING_COLLECTION
    ON KBOT_KC_COLLECTION_BINDING (COLLECTION_ID, STATUS);

CREATE TABLE KBOT_KC_INGESTION_RECEIPT (
    INGESTION_RECEIPT_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    REQUEST_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
    RECEIPT_STATUS VARCHAR2(24 CHAR) NOT NULL,
    BUNDLE_ID RAW(16),
    BUNDLE_REVISION_ID RAW(16),
    STAGING_MANIFEST_JSON JSON,
    FAILURE_CODE VARCHAR2(128 CHAR),
    FAILURE_MESSAGE VARCHAR2(1000 CHAR),
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR),
    UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_RECEIPT_IDEMPOTENCY UNIQUE (COLLECTION_ID, ACTOR_ID, IDEMPOTENCY_KEY),
    CONSTRAINT CK_KC_RECEIPT_RESOURCE_IDS CHECK (
        (BUNDLE_ID IS NULL AND BUNDLE_REVISION_ID IS NULL)
        OR (BUNDLE_ID IS NOT NULL AND BUNDLE_REVISION_ID IS NOT NULL)
    ),
    CONSTRAINT FK_KC_RECEIPT_COLLECTION FOREIGN KEY (COLLECTION_ID)
        REFERENCES KBOT_KC_COLLECTION (COLLECTION_ID),
    CONSTRAINT CK_KC_RECEIPT_STATUS CHECK (
        RECEIPT_STATUS IN ('RECEIVING', 'STAGED', 'COMMITTING', 'PENDING_REVIEW', 'ACCEPTED', 'REJECTED', 'CLEANUP_PENDING')
    )
);

CREATE INDEX IX_KC_RECEIPT_EXPIRY
    ON KBOT_KC_INGESTION_RECEIPT (RECEIPT_STATUS, EXPIRES_AT);
