-- KBot 4.0 Knowledge Core：不可变入库聚合。
-- 所有领域 ID 使用 UUIDv7 RAW(16)，冗余 Collection 范围通过复合外键保持一致。

CREATE TABLE KBOT_KC_BUNDLE (
    BUNDLE_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(64 CHAR) NOT NULL,
    SOURCE_TYPE VARCHAR2(64 CHAR) NOT NULL,
    SOURCE_ID VARCHAR2(256 CHAR) NOT NULL,
    CURRENT_REVISION_ID RAW(16),
    AVAILABILITY_STATUS VARCHAR2(16 CHAR) DEFAULT 'EMPTY' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR), UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_BUNDLE_SOURCE UNIQUE (COLLECTION_ID, SOURCE_SYSTEM, SOURCE_TYPE, SOURCE_ID),
    CONSTRAINT UK_KC_BUNDLE_SCOPE UNIQUE (BUNDLE_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_BUNDLE_COLLECTION FOREIGN KEY (COLLECTION_ID)
        REFERENCES KBOT_KC_COLLECTION (COLLECTION_ID),
    CONSTRAINT CK_KC_BUNDLE_AVAILABILITY CHECK (AVAILABILITY_STATUS IN ('EMPTY', 'READY', 'PARTIAL', 'FAILED', 'DELETING'))
);
CREATE INDEX IX_KC_BUNDLE_COLLECTION_STATUS ON KBOT_KC_BUNDLE (COLLECTION_ID, AVAILABILITY_STATUS);

CREATE TABLE KBOT_KC_BUNDLE_REVISION (
    BUNDLE_REVISION_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL,
    BUNDLE_ID RAW(16) NOT NULL,
    REVISION_NO NUMBER(19) NOT NULL,
    SOURCE_REVISION VARCHAR2(256 CHAR) NOT NULL,
    SNAPSHOT_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
    MANIFEST_JSON JSON NOT NULL,
    TITLE VARCHAR2(512 CHAR) NOT NULL,
    CANONICAL_URL VARCHAR2(2048 CHAR),
    SECURITY_LEVEL NUMBER(3) NOT NULL,
    FACET_JSON JSON,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    APPROVAL_STATUS VARCHAR2(16 CHAR) DEFAULT 'NOT_REQUIRED' NOT NULL,
    REVIEWED_BY VARCHAR2(256 CHAR),
    REVIEWED_AT TIMESTAMP(6) WITH TIME ZONE,
    REVIEW_COMMENT VARCHAR2(1000 CHAR),
    ACCEPTED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    FAILURE_CODE VARCHAR2(128 CHAR), FAILURE_MESSAGE VARCHAR2(1000 CHAR),
    CREATED_BY VARCHAR2(256 CHAR), UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_REVISION_NO UNIQUE (BUNDLE_ID, REVISION_NO),
    CONSTRAINT UK_KC_REVISION_SOURCE UNIQUE (BUNDLE_ID, SOURCE_REVISION),
    CONSTRAINT UK_KC_REVISION_SCOPE UNIQUE
        (BUNDLE_REVISION_ID, BUNDLE_ID, COLLECTION_ID),
    CONSTRAINT UK_KC_REVISION_COLLECTION UNIQUE
        (BUNDLE_REVISION_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_REVISION_BUNDLE FOREIGN KEY (BUNDLE_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_BUNDLE (BUNDLE_ID, COLLECTION_ID),
    CONSTRAINT CK_KC_REVISION_STATUS CHECK (STATUS IN ('ACCEPTED', 'PENDING_REVIEW', 'PROCESSING', 'READY', 'PARTIAL', 'FAILED', 'REJECTED')),
    CONSTRAINT CK_KC_REVISION_APPROVAL CHECK (APPROVAL_STATUS IN ('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT CK_KC_REVISION_SECURITY CHECK (SECURITY_LEVEL >= 0)
);
CREATE INDEX IX_KC_REVISION_BUNDLE_STATUS ON KBOT_KC_BUNDLE_REVISION (BUNDLE_ID, STATUS);
CREATE INDEX IX_KC_REVISION_COLLECTION_STATUS ON KBOT_KC_BUNDLE_REVISION (COLLECTION_ID, STATUS, ACCEPTED_AT);
CREATE INDEX IX_KC_REVISION_APPROVAL ON KBOT_KC_BUNDLE_REVISION (COLLECTION_ID, APPROVAL_STATUS, ACCEPTED_AT);

ALTER TABLE KBOT_KC_BUNDLE ADD CONSTRAINT FK_KC_BUNDLE_CURRENT_REV
    FOREIGN KEY (CURRENT_REVISION_ID, BUNDLE_ID, COLLECTION_ID)
    REFERENCES KBOT_KC_BUNDLE_REVISION
        (BUNDLE_REVISION_ID, BUNDLE_ID, COLLECTION_ID);

CREATE TABLE KBOT_KC_DOCUMENT (
    DOCUMENT_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL,
    BUNDLE_ID RAW(16) NOT NULL,
    EXTERNAL_DOCUMENT_ID VARCHAR2(256 CHAR) NOT NULL,
    DOCUMENT_STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR), UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_DOCUMENT_EXTERNAL UNIQUE (BUNDLE_ID, EXTERNAL_DOCUMENT_ID),
    CONSTRAINT UK_KC_DOCUMENT_SCOPE UNIQUE (DOCUMENT_ID, BUNDLE_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_DOCUMENT_BUNDLE FOREIGN KEY (BUNDLE_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_BUNDLE (BUNDLE_ID, COLLECTION_ID),
    CONSTRAINT CK_KC_DOCUMENT_STATUS CHECK (DOCUMENT_STATUS IN ('ACTIVE', 'RETIRED'))
);
CREATE INDEX IX_KC_DOCUMENT_BUNDLE_STATUS ON KBOT_KC_DOCUMENT (BUNDLE_ID, DOCUMENT_STATUS);

CREATE TABLE KBOT_KC_DOCUMENT_VERSION (
    DOCUMENT_VERSION_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL, BUNDLE_ID RAW(16) NOT NULL, DOCUMENT_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    STORAGE_URI VARCHAR2(2048 CHAR) NOT NULL,
    STORAGE_STATE VARCHAR2(16 CHAR) NOT NULL,
    BYTE_SIZE NUMBER(19) NOT NULL,
    DETECTED_MIME_TYPE VARCHAR2(255 CHAR) NOT NULL,
    SECURITY_LEVEL NUMBER(3) NOT NULL,
    CONTENT_METADATA_JSON JSON,
    RECEIVED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR), UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_DOCUMENT_VERSION_NO UNIQUE (DOCUMENT_ID, VERSION_NO),
    CONSTRAINT UK_KC_DOCUMENT_VERSION_HASH UNIQUE (DOCUMENT_ID, CONTENT_HASH),
    CONSTRAINT UK_KC_DOC_VERSION_SCOPE UNIQUE
        (DOCUMENT_VERSION_ID, DOCUMENT_ID, BUNDLE_ID, COLLECTION_ID),
    CONSTRAINT UK_KC_DOC_VERSION_MEMBER UNIQUE
        (DOCUMENT_VERSION_ID, DOCUMENT_ID, COLLECTION_ID),
    CONSTRAINT UK_KC_DOC_VERSION_COLLECTION UNIQUE
        (DOCUMENT_VERSION_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_DOC_VERSION_DOCUMENT
        FOREIGN KEY (DOCUMENT_ID, BUNDLE_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_DOCUMENT (DOCUMENT_ID, BUNDLE_ID, COLLECTION_ID),
    CONSTRAINT CK_KC_DOCUMENT_VERSION_STATE CHECK (STORAGE_STATE IN ('AVAILABLE', 'QUARANTINED', 'DELETED')),
    CONSTRAINT CK_KC_DOCUMENT_VERSION_SIZE CHECK (BYTE_SIZE >= 0),
    CONSTRAINT CK_KC_DOC_VER_SECURITY CHECK (SECURITY_LEVEL >= 0)
);
CREATE INDEX IX_KC_DOCUMENT_VERSION_COLLECTION_DOCUMENT ON KBOT_KC_DOCUMENT_VERSION (COLLECTION_ID, DOCUMENT_ID);
CREATE INDEX IX_KC_DOCUMENT_VERSION_STORAGE_STATE ON KBOT_KC_DOCUMENT_VERSION (STORAGE_STATE);

CREATE TABLE KBOT_KC_BUNDLE_REVISION_DOCUMENT (
    BUNDLE_REVISION_DOCUMENT_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL, BUNDLE_REVISION_ID RAW(16) NOT NULL,
    DOCUMENT_ID RAW(16) NOT NULL, DOCUMENT_VERSION_ID RAW(16),
    DOCUMENT_ROLE VARCHAR2(24 CHAR) NOT NULL, ORDINAL NUMBER(19) NOT NULL,
    REQUIRED_FLAG NUMBER(1) NOT NULL, EXTERNAL_DOCUMENT_ID VARCHAR2(256 CHAR) NOT NULL,
    DECLARED_NAME VARCHAR2(512 CHAR), DECLARED_MIME_TYPE VARCHAR2(255 CHAR), SOURCE_URL VARCHAR2(2048 CHAR),
    MEMBER_STATUS VARCHAR2(24 CHAR) NOT NULL,
    FAILURE_STAGE VARCHAR2(32 CHAR), FAILURE_CODE VARCHAR2(128 CHAR), FAILURE_MESSAGE VARCHAR2(1000 CHAR),
    RECEIVED_AT TIMESTAMP(6) WITH TIME ZONE, COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR), UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_MEMBER_DOCUMENT UNIQUE (BUNDLE_REVISION_ID, DOCUMENT_ID),
    CONSTRAINT UK_KC_MEMBER_EXTERNAL UNIQUE (BUNDLE_REVISION_ID, EXTERNAL_DOCUMENT_ID),
    CONSTRAINT UK_KC_MEMBER_SCOPE UNIQUE
        (BUNDLE_REVISION_DOCUMENT_ID, BUNDLE_REVISION_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_MEMBER_REVISION
        FOREIGN KEY (BUNDLE_REVISION_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_BUNDLE_REVISION (BUNDLE_REVISION_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_MEMBER_DOCUMENT FOREIGN KEY (DOCUMENT_ID)
        REFERENCES KBOT_KC_DOCUMENT (DOCUMENT_ID),
    CONSTRAINT FK_KC_MEMBER_VERSION
        FOREIGN KEY (DOCUMENT_VERSION_ID, DOCUMENT_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_DOCUMENT_VERSION
            (DOCUMENT_VERSION_ID, DOCUMENT_ID, COLLECTION_ID),
    CONSTRAINT CK_KC_MEMBER_ROLE CHECK (DOCUMENT_ROLE IN ('MANIFEST', 'ATTACHMENT', 'SUPPLEMENT', 'DERIVED')),
    CONSTRAINT CK_KC_MEMBER_REQUIRED CHECK (REQUIRED_FLAG IN (0, 1)),
    CONSTRAINT CK_KC_MEMBER_STATUS CHECK (MEMBER_STATUS IN ('DECLARED', 'RECEIVED', 'SOURCE_UNAVAILABLE', 'PARSING', 'INDEXING', 'READY', 'FAILED', 'CANCELLED')),
    CONSTRAINT CK_KC_MEMBER_MANIFEST_REQUIRED CHECK (DOCUMENT_ROLE <> 'MANIFEST' OR REQUIRED_FLAG = 1)
);
CREATE INDEX IX_KC_MEMBER_REVISION_ORDINAL ON KBOT_KC_BUNDLE_REVISION_DOCUMENT (BUNDLE_REVISION_ID, ORDINAL);
CREATE INDEX IX_KC_MEMBER_COLLECTION_STATUS ON KBOT_KC_BUNDLE_REVISION_DOCUMENT (COLLECTION_ID, MEMBER_STATUS);

CREATE TABLE KBOT_KC_PARSE_VIEW (
    PARSE_VIEW_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL, DOCUMENT_VERSION_ID RAW(16) NOT NULL,
    VIEW_KIND VARCHAR2(16 CHAR) NOT NULL, PARSER_NAME VARCHAR2(128 CHAR) NOT NULL,
    PARSER_VERSION VARCHAR2(128 CHAR), PARSE_CONFIG_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
    PARSE_CONFIG_JSON JSON, VIEW_STATUS VARCHAR2(16 CHAR) NOT NULL,
    QUALITY_SCORE NUMBER(8, 5), QUALITY_REPORT_JSON JSON, ARTIFACT_MANIFEST_JSON JSON,
    ACTIVATED_AT TIMESTAMP(6) WITH TIME ZONE, RETIRED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_BY VARCHAR2(256 CHAR), UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_PARSE_VIEW_INPUT UNIQUE (DOCUMENT_VERSION_ID, VIEW_KIND, PARSE_CONFIG_FINGERPRINT),
    CONSTRAINT UK_KC_PARSE_VIEW_SCOPE UNIQUE (PARSE_VIEW_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_PARSE_VIEW_VERSION
        FOREIGN KEY (DOCUMENT_VERSION_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_DOCUMENT_VERSION
            (DOCUMENT_VERSION_ID, COLLECTION_ID),
    CONSTRAINT CK_KC_PARSE_VIEW_KIND CHECK (VIEW_KIND IN ('TEXT', 'VISUAL', 'HYBRID')),
    CONSTRAINT CK_KC_PARSE_VIEW_STATUS CHECK (VIEW_STATUS IN ('PENDING', 'PARSING', 'STAGED', 'ACTIVE', 'FAILED', 'RETIRED'))
);
CREATE INDEX IX_KC_PARSE_VIEW_VERSION_STATUS ON KBOT_KC_PARSE_VIEW (DOCUMENT_VERSION_ID, VIEW_STATUS);

CREATE TABLE KBOT_KC_INGESTION_JOB (
    INGESTION_JOB_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL, BUNDLE_REVISION_ID RAW(16), DOCUMENT_VERSION_ID RAW(16), PARSE_VIEW_ID RAW(16),
    JOB_TYPE VARCHAR2(24 CHAR) NOT NULL, IDEMPOTENCY_KEY VARCHAR2(256 CHAR) NOT NULL,
    INPUT_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL, PAYLOAD_JSON JSON,
    JOB_STATUS VARCHAR2(16 CHAR) NOT NULL, PRIORITY NUMBER(8) DEFAULT 0 NOT NULL,
    AVAILABLE_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATTEMPT_COUNT NUMBER(8) DEFAULT 0 NOT NULL, MAX_ATTEMPTS NUMBER(8) DEFAULT 3 NOT NULL,
    LEASE_OWNER VARCHAR2(256 CHAR), LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE, HEARTBEAT_AT TIMESTAMP(6) WITH TIME ZONE,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE, COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    RESULT_JSON JSON, FAILURE_CLASS VARCHAR2(16 CHAR), FAILURE_CODE VARCHAR2(128 CHAR), FAILURE_MESSAGE VARCHAR2(1000 CHAR),
    TRACE_ID VARCHAR2(128 CHAR), ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR), UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_JOB_INPUT UNIQUE (COLLECTION_ID, IDEMPOTENCY_KEY, INPUT_FINGERPRINT),
    CONSTRAINT FK_KC_JOB_COLLECTION FOREIGN KEY (COLLECTION_ID)
        REFERENCES KBOT_KC_COLLECTION (COLLECTION_ID),
    CONSTRAINT FK_KC_JOB_REVISION
        FOREIGN KEY (BUNDLE_REVISION_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_BUNDLE_REVISION
            (BUNDLE_REVISION_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_JOB_VERSION
        FOREIGN KEY (DOCUMENT_VERSION_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_DOCUMENT_VERSION
            (DOCUMENT_VERSION_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_JOB_PARSE_VIEW
        FOREIGN KEY (PARSE_VIEW_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_PARSE_VIEW (PARSE_VIEW_ID, COLLECTION_ID),
    CONSTRAINT CK_KC_JOB_TYPE CHECK (JOB_TYPE IN ('PARSE', 'PROFILE', 'INDEX', 'RELATE', 'VIEW_CLEANUP', 'COLLECTION_PURGE')),
    CONSTRAINT CK_KC_JOB_STATUS CHECK (JOB_STATUS IN ('PENDING', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT CK_KC_JOB_ATTEMPTS CHECK (ATTEMPT_COUNT >= 0 AND MAX_ATTEMPTS > 0)
);
CREATE INDEX IX_KC_JOB_CLAIM ON KBOT_KC_INGESTION_JOB (JOB_STATUS, AVAILABLE_AT, PRIORITY);
CREATE INDEX IX_KC_JOB_LEASE ON KBOT_KC_INGESTION_JOB (LEASE_UNTIL, JOB_STATUS);
CREATE INDEX IX_KC_JOB_REVISION ON KBOT_KC_INGESTION_JOB (BUNDLE_REVISION_ID, JOB_TYPE, JOB_STATUS);

ALTER TABLE KBOT_KC_INGESTION_RECEIPT ADD CONSTRAINT FK_KC_RECEIPT_BUNDLE
    FOREIGN KEY (BUNDLE_ID, COLLECTION_ID)
    REFERENCES KBOT_KC_BUNDLE (BUNDLE_ID, COLLECTION_ID);
ALTER TABLE KBOT_KC_INGESTION_RECEIPT ADD CONSTRAINT FK_KC_RECEIPT_REVISION
    FOREIGN KEY (BUNDLE_REVISION_ID, BUNDLE_ID, COLLECTION_ID)
    REFERENCES KBOT_KC_BUNDLE_REVISION
        (BUNDLE_REVISION_ID, BUNDLE_ID, COLLECTION_ID);
