-- KBot 4.0 Knowledge Core：Parser Evidence 与 INDEX 检索字段。
-- Parser 写入结构化内容；INDEX 写入 Collection 唯一模型生成的向量快照。
CREATE TABLE KBOT_KC_EVIDENCE (
    EVIDENCE_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL, BUNDLE_REVISION_ID RAW(16) NOT NULL,
    BUNDLE_REVISION_DOCUMENT_ID RAW(16), DOCUMENT_ID RAW(16) NOT NULL,
    DOCUMENT_VERSION_ID RAW(16) NOT NULL, PARSE_VIEW_ID RAW(16) NOT NULL,
    EVIDENCE_KEY VARCHAR2(256 CHAR) NOT NULL, EVIDENCE_TYPE VARCHAR2(32 CHAR) NOT NULL,
    ORDINAL NUMBER(19) NOT NULL, FRAGMENT_INDEX NUMBER(19) DEFAULT 0 NOT NULL,
    PARENT_EVIDENCE_KEY VARCHAR2(256 CHAR),
    SOURCE_ITEM_REF VARCHAR2(512 CHAR), SOURCE_SPANS_JSON CLOB NOT NULL,
    HEADING_PATH_JSON CLOB, SECTION_KEY VARCHAR2(256 CHAR),
    HIERARCHY_DEPTH NUMBER(8), HEADING_LEVEL NUMBER(8),
    LOCATOR_SCHEMA_VERSION VARCHAR2(32 CHAR) NOT NULL, LOCATOR_JSON CLOB NOT NULL,
    PAYLOAD_URI VARCHAR2(2048 CHAR), PROVENANCE_JSON CLOB NOT NULL,
    CONTENT_TEXT CLOB NOT NULL, RETRIEVAL_TEXT CLOB NOT NULL, CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    PAGE_START NUMBER(19), PAGE_END NUMBER(19), LANGUAGE_CODE VARCHAR2(32 CHAR), TOKEN_COUNT NUMBER(19),
    EMBEDDING VECTOR, EMBEDDING_MODEL_ID RAW(16),
    EMBEDDING_SERVED_MODEL_NAME VARCHAR2(128 CHAR),
    EMBEDDING_CONFIG_FINGERPRINT VARCHAR2(64 CHAR),
    EMBEDDING_INPUT_HASH VARCHAR2(64 CHAR),
    INDEXED_AT TIMESTAMP(6) WITH TIME ZONE,
    QUALITY_SCORE NUMBER(8,5), STATUS VARCHAR2(16 CHAR) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR), UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_EVIDENCE_KEY UNIQUE (PARSE_VIEW_ID, EVIDENCE_KEY),
    CONSTRAINT FK_KC_EVIDENCE_REVISION
        FOREIGN KEY (BUNDLE_REVISION_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_BUNDLE_REVISION
            (BUNDLE_REVISION_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_EVIDENCE_MEMBER
        FOREIGN KEY
            (BUNDLE_REVISION_DOCUMENT_ID, BUNDLE_REVISION_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_BUNDLE_REVISION_DOCUMENT
            (BUNDLE_REVISION_DOCUMENT_ID, BUNDLE_REVISION_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_EVIDENCE_VERSION
        FOREIGN KEY (DOCUMENT_VERSION_ID, DOCUMENT_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_DOCUMENT_VERSION
            (DOCUMENT_VERSION_ID, DOCUMENT_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_EVIDENCE_PARSE_VIEW FOREIGN KEY (PARSE_VIEW_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_PARSE_VIEW (PARSE_VIEW_ID, COLLECTION_ID),
    CONSTRAINT CK_KC_EVIDENCE_TYPE CHECK (EVIDENCE_TYPE IN ('DOCUMENT', 'SECTION', 'PARAGRAPH', 'TABLE', 'TABLE_ROW', 'IMAGE', 'SHEET', 'CELL_RANGE')),
    CONSTRAINT CK_KC_EVIDENCE_STATUS CHECK (STATUS IN ('STAGED', 'ACTIVE', 'RETIRED', 'REJECTED')),
    CONSTRAINT CK_KC_EVIDENCE_FRAGMENT CHECK (FRAGMENT_INDEX >= 0),
    CONSTRAINT CK_KC_EVIDENCE_SOURCE_JSON CHECK (SOURCE_SPANS_JSON IS JSON),
    CONSTRAINT CK_KC_EVIDENCE_HEADING_JSON CHECK (HEADING_PATH_JSON IS JSON),
    CONSTRAINT CK_KC_EVIDENCE_LOCATOR_JSON CHECK (LOCATOR_JSON IS JSON),
    CONSTRAINT CK_KC_EVIDENCE_PROVENANCE_JSON CHECK (PROVENANCE_JSON IS JSON)
);
CREATE INDEX IX_KC_EVIDENCE_VIEW_STATUS ON KBOT_KC_EVIDENCE (PARSE_VIEW_ID, STATUS, ORDINAL);
CREATE INDEX IX_KC_EVIDENCE_DOCUMENT ON KBOT_KC_EVIDENCE (DOCUMENT_VERSION_ID, STATUS);
CREATE INDEX IX_KC_EVIDENCE_EMBED_MODEL
    ON KBOT_KC_EVIDENCE (COLLECTION_ID, EMBEDDING_MODEL_ID, STATUS);

COMMENT ON COLUMN KBOT_KC_EVIDENCE.EMBEDDING_MODEL_ID IS
    'Collection-bound text embedding model used by INDEX';
COMMENT ON COLUMN KBOT_KC_EVIDENCE.EMBEDDING_SERVED_MODEL_NAME IS
    'Model Serving name frozen by the INDEX job';
COMMENT ON COLUMN KBOT_KC_EVIDENCE.EMBEDDING_INPUT_HASH IS
    'SHA-256 of retrieval_text; changes force re-indexing';
