-- Bundle/Document Discovery 投影；Profile Text 不是引用正文。
CREATE TABLE KBOT_KC_DISCOVERY_OBJECT (
    DISCOVERY_OBJECT_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL, BUNDLE_ID RAW(16) NOT NULL,
    BUNDLE_REVISION_ID RAW(16) NOT NULL, BUNDLE_REVISION_DOCUMENT_ID RAW(16),
    DOCUMENT_ID RAW(16), DOCUMENT_VERSION_ID RAW(16),
    OBJECT_TYPE VARCHAR2(16 CHAR) NOT NULL, PROFILE_KEY VARCHAR2(256 CHAR) NOT NULL,
    DISPLAY_TITLE VARCHAR2(512 CHAR) NOT NULL, PROFILE_TEXT CLOB NOT NULL,
    FACET_JSON CLOB, COVERAGE_JSON CLOB NOT NULL, PROFILE_HASH VARCHAR2(64 CHAR) NOT NULL,
    PROFILE_SCHEMA_VERSION VARCHAR2(32 CHAR) NOT NULL,
    EMBEDDING VECTOR, EMBEDDING_MODEL_ID RAW(16),
    EMBEDDING_SERVED_MODEL_NAME VARCHAR2(128 CHAR),
    EMBEDDING_CONFIG_FINGERPRINT VARCHAR2(64 CHAR), EMBEDDING_INPUT_HASH VARCHAR2(64 CHAR),
    INDEXED_AT TIMESTAMP(6) WITH TIME ZONE,
    SECURITY_LEVEL NUMBER(3) NOT NULL, QUALITY_SCORE NUMBER(8,6),
    DISCOVERY_STATUS VARCHAR2(16 CHAR) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR), UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_DISCOVERY_REV_KEY UNIQUE (BUNDLE_REVISION_ID, PROFILE_KEY),
    CONSTRAINT FK_KC_DISCOVERY_BUNDLE FOREIGN KEY (BUNDLE_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_BUNDLE (BUNDLE_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_DISCOVERY_REVISION
        FOREIGN KEY (BUNDLE_REVISION_ID, BUNDLE_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_BUNDLE_REVISION
            (BUNDLE_REVISION_ID, BUNDLE_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_DISCOVERY_MEMBER
        FOREIGN KEY
            (BUNDLE_REVISION_DOCUMENT_ID, BUNDLE_REVISION_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_BUNDLE_REVISION_DOCUMENT
            (BUNDLE_REVISION_DOCUMENT_ID, BUNDLE_REVISION_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_DISCOVERY_VERSION
        FOREIGN KEY (DOCUMENT_VERSION_ID, DOCUMENT_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_DOCUMENT_VERSION
            (DOCUMENT_VERSION_ID, DOCUMENT_ID, COLLECTION_ID),
    CONSTRAINT CK_KC_DISCOVERY_TYPE CHECK (OBJECT_TYPE IN ('BUNDLE', 'DOCUMENT')),
    CONSTRAINT CK_KC_DISCOVERY_STATUS CHECK (DISCOVERY_STATUS IN ('STAGED', 'ACTIVE', 'DELETING', 'FAILED')),
    CONSTRAINT CK_KC_DISCOVERY_FACET_JSON CHECK (FACET_JSON IS JSON),
    CONSTRAINT CK_KC_DISCOVERY_COVERAGE_JSON CHECK (COVERAGE_JSON IS JSON),
    CONSTRAINT CK_KC_DISCOVERY_BUNDLE_KEY CHECK (
        (OBJECT_TYPE = 'BUNDLE' AND BUNDLE_REVISION_DOCUMENT_ID IS NULL AND DOCUMENT_ID IS NULL)
        OR (OBJECT_TYPE = 'DOCUMENT' AND BUNDLE_REVISION_DOCUMENT_ID IS NOT NULL AND DOCUMENT_ID IS NOT NULL)
    )
);
CREATE INDEX IX_KC_DISCOVERY_SCOPE_STATUS ON KBOT_KC_DISCOVERY_OBJECT (COLLECTION_ID, DISCOVERY_STATUS, SECURITY_LEVEL);
CREATE INDEX IX_KC_DISCOVERY_REV_TYPE ON KBOT_KC_DISCOVERY_OBJECT (BUNDLE_REVISION_ID, OBJECT_TYPE, DISCOVERY_STATUS);
