-- Evidence 支撑的关系限定在 Revision 内，不允许跨 Collection/Domain。
CREATE TABLE KBOT_KC_RELATION (
    RELATION_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL,
    BUNDLE_ID RAW(16) NOT NULL,
    BUNDLE_REVISION_ID RAW(16) NOT NULL,
    SUBJECT_TYPE VARCHAR2(32 CHAR) NOT NULL,
    SUBJECT_ID RAW(16) NOT NULL,
    PREDICATE VARCHAR2(48 CHAR) NOT NULL,
    OBJECT_TYPE VARCHAR2(32 CHAR) NOT NULL,
    OBJECT_ID RAW(16) NOT NULL,
    DIRECTIONALITY VARCHAR2(16 CHAR) NOT NULL,
    SUPPORT_JSON CLOB NOT NULL,
    DERIVATION_TYPE VARCHAR2(16 CHAR) NOT NULL,
    DERIVATION_KEY VARCHAR2(128 CHAR) NOT NULL,
    CONFIDENCE NUMBER(8,6),
    ATTRIBUTES_JSON CLOB,
    RELATION_STATUS VARCHAR2(16 CHAR) DEFAULT 'STAGED' NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR), UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_RELATION_DERIVATION UNIQUE
      (BUNDLE_REVISION_ID, SUBJECT_TYPE, SUBJECT_ID, PREDICATE, OBJECT_TYPE, OBJECT_ID, DERIVATION_KEY),
    CONSTRAINT FK_KC_RELATION_BUNDLE FOREIGN KEY (BUNDLE_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_BUNDLE (BUNDLE_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_RELATION_REVISION
        FOREIGN KEY (BUNDLE_REVISION_ID, BUNDLE_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_BUNDLE_REVISION
            (BUNDLE_REVISION_ID, BUNDLE_ID, COLLECTION_ID),
    CONSTRAINT CK_KC_RELATION_DIRECTION CHECK (DIRECTIONALITY IN ('DIRECTED', 'SYMMETRIC')),
    CONSTRAINT CK_KC_RELATION_DERIVATION CHECK (DERIVATION_TYPE IN ('MANIFEST', 'RULE', 'MODEL', 'MANUAL')),
    CONSTRAINT CK_KC_RELATION_STATUS CHECK (RELATION_STATUS IN ('STAGED', 'ACTIVE', 'INVALID', 'DELETING')),
    CONSTRAINT CK_KC_RELATION_CONFIDENCE CHECK (CONFIDENCE IS NULL OR (CONFIDENCE >= 0 AND CONFIDENCE <= 1)),
    CONSTRAINT CK_KC_RELATION_SUPPORT_JSON CHECK (SUPPORT_JSON IS JSON),
    CONSTRAINT CK_KC_RELATION_ATTRIBUTES_JSON CHECK (ATTRIBUTES_JSON IS JSON)
);
CREATE INDEX IX_KC_RELATION_REV_STATUS ON KBOT_KC_RELATION (COLLECTION_ID, BUNDLE_REVISION_ID, RELATION_STATUS, PREDICATE);
CREATE INDEX IX_KC_RELATION_SUBJECT ON KBOT_KC_RELATION (SUBJECT_TYPE, SUBJECT_ID, RELATION_STATUS);
CREATE INDEX IX_KC_RELATION_OBJECT ON KBOT_KC_RELATION (OBJECT_TYPE, OBJECT_ID, RELATION_STATUS);
