-- KBot 4.0 Knowledge Core：页面与局部图片的独立视觉检索索引。
CREATE TABLE KBOT_KC_VISUAL_ASSET (
    VISUAL_ASSET_ID RAW(16) PRIMARY KEY,
    COLLECTION_ID RAW(16) NOT NULL,
    BUNDLE_REVISION_ID RAW(16) NOT NULL,
    DOCUMENT_ID RAW(16) NOT NULL,
    DOCUMENT_VERSION_ID RAW(16) NOT NULL,
    PARSE_VIEW_ID RAW(16) NOT NULL,
    EVIDENCE_ID RAW(16),
    ASSET_KEY VARCHAR2(256 CHAR) NOT NULL,
    ASSET_TYPE VARCHAR2(16 CHAR) NOT NULL,
    PAGE_NO NUMBER(19),
    SOURCE_ITEM_REF VARCHAR2(512 CHAR),
    BBOX_JSON JSON,
    MIME_TYPE VARCHAR2(128 CHAR) NOT NULL,
    PAYLOAD_URI VARCHAR2(2048 CHAR) NOT NULL,
    CONTENT_HASH VARCHAR2(64 CHAR) NOT NULL,
    DESCRIPTION_TEXT CLOB,
    VISUAL_EMBEDDING VECTOR,
    VISUAL_EMBEDDING_MODEL_ID RAW(16),
    VISUAL_EMBEDDING_SERVED_MODEL_NAME VARCHAR2(128 CHAR),
    VISUAL_EMBEDDING_CONFIG_FINGERPRINT VARCHAR2(64 CHAR),
    INDEXED_AT TIMESTAMP(6) WITH TIME ZONE,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR),
    UPDATED_BY VARCHAR2(256 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KC_VISUAL_ASSET UNIQUE (PARSE_VIEW_ID, ASSET_KEY),
    CONSTRAINT FK_KC_VISUAL_ASSET_VIEW FOREIGN KEY (PARSE_VIEW_ID, COLLECTION_ID)
        REFERENCES KBOT_KC_PARSE_VIEW (PARSE_VIEW_ID, COLLECTION_ID),
    CONSTRAINT FK_KC_VISUAL_ASSET_EVIDENCE FOREIGN KEY (EVIDENCE_ID)
        REFERENCES KBOT_KC_EVIDENCE (EVIDENCE_ID),
    CONSTRAINT CK_KC_VISUAL_ASSET_TYPE
        CHECK (ASSET_TYPE IN ('PAGE', 'FIGURE')),
    CONSTRAINT CK_KC_VISUAL_ASSET_STATUS
        CHECK (STATUS IN ('STAGED', 'ACTIVE', 'RETIRED'))
);
CREATE INDEX IX_KC_VISUAL_ASSET_SEARCH
    ON KBOT_KC_VISUAL_ASSET
       (COLLECTION_ID, VISUAL_EMBEDDING_MODEL_ID, STATUS);
CREATE INDEX IX_KC_VISUAL_ASSET_DOCUMENT
    ON KBOT_KC_VISUAL_ASSET (DOCUMENT_VERSION_ID, PAGE_NO, STATUS);
