-- 智能工作台自己的 Agent 与不可变版本；KC 和问数模型继续由各自服务拥有。

CREATE TABLE KBOT_ASST_AGENT (
    AGENT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    CURRENT_VERSION_ID RAW(16),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ASST_AGENT_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_ASST_AGENT_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT CK_ASST_AGENT_STATUS
        CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED')),
    CONSTRAINT CK_ASST_AGENT_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_ASST_AGENT_SCOPE_STATUS ON KBOT_ASST_AGENT (DOMAIN_ID, STATUS);

CREATE TABLE KBOT_ASST_AGENT_VERSION (
    AGENT_VERSION_ID RAW(16) PRIMARY KEY,
    AGENT_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    KNOWLEDGE_CORE_ID RAW(16),
    DATA_MODEL_IDS_JSON JSON NOT NULL,
    MODELS_JSON JSON NOT NULL,
    INSTRUCTION CLOB,
    CONFIG_JSON JSON NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ASST_AGENT_VERSION_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES KBOT_ASST_AGENT (AGENT_ID) ON DELETE CASCADE,
    CONSTRAINT UK_ASST_AGENT_VERSION UNIQUE (AGENT_ID, VERSION_NO)
);

CREATE INDEX IX_ASST_AGENT_VERSION_AGENT ON KBOT_ASST_AGENT_VERSION (AGENT_ID);

ALTER TABLE KBOT_ASST_AGENT ADD CONSTRAINT FK_ASST_AGENT_CURRENT_VERSION
    FOREIGN KEY (CURRENT_VERSION_ID)
    REFERENCES KBOT_ASST_AGENT_VERSION (AGENT_VERSION_ID);
