-- 智能工作台 X Search 与文生图运行时：绑定、Run、事件、来源、提示词版本与图片资产元数据。
-- 图片字节不入库；对象存储键只保存在媒体资产表。

CREATE TABLE KBOT_ASST_MODEL_BINDING (
    BINDING_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    ROLE VARCHAR2(32 CHAR) NOT NULL,
    MODEL_ID RAW(16) NOT NULL,
    MODEL_SNAPSHOT_JSON JSON NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ASST_BINDING_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT UK_ASST_BINDING_ROLE UNIQUE (DOMAIN_ID, ROLE),
    CONSTRAINT CK_ASST_BINDING_ROLE CHECK (ROLE IN ('KNOWLEDGE', 'X_SEARCH', 'IMAGE_GENERATION')),
    CONSTRAINT CK_ASST_BINDING_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_ASST_BINDING_MODEL ON KBOT_ASST_MODEL_BINDING (MODEL_ID);

CREATE TABLE KBOT_ASST_RUN (
    RUN_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    KIND VARCHAR2(32 CHAR) NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'ACCEPTED' NOT NULL,
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    REQUEST_ID VARCHAR2(128 CHAR) NOT NULL,
    TRACE_ID VARCHAR2(128 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    MODEL_ID RAW(16) NOT NULL,
    MODEL_SNAPSHOT_JSON JSON NOT NULL,
    REQUEST_JSON JSON NOT NULL,
    RESULT_JSON JSON,
    USAGE_JSON JSON,
    PROVIDER_REQUEST_ID VARCHAR2(256 CHAR),
    PROMPT_REVISION_ID RAW(16),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_TOKEN RAW(16),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_ASST_RUN_IDEMP UNIQUE (DOMAIN_ID, ACTOR_ID, IDEMPOTENCY_KEY),
    CONSTRAINT UK_ASST_RUN_SCOPE UNIQUE (RUN_ID, DOMAIN_ID),
    CONSTRAINT FK_ASST_RUN_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_ASST_RUN_KIND CHECK (KIND IN ('X_SEARCH', 'IMAGE_GENERATION')),
    CONSTRAINT CK_ASST_RUN_STATUS CHECK (STATUS IN (
        'ACCEPTED', 'SEARCHING', 'ORGANIZING_SOURCES', 'COMPOSING',
        'GENERATING', 'COMPLETED', 'REJECTED', 'FAILED'
    )),
    CONSTRAINT CK_ASST_RUN_ROW_VERSION CHECK (ROW_VERSION > 0)
);

CREATE INDEX IX_ASST_RUN_DOMAIN_TIME ON KBOT_ASST_RUN (DOMAIN_ID, CREATED_AT);
CREATE INDEX IX_ASST_RUN_CLAIM ON KBOT_ASST_RUN (STATUS, LEASE_UNTIL);

CREATE TABLE KBOT_ASST_RUN_EVENT (
    EVENT_ID RAW(16) PRIMARY KEY,
    RUN_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    SEQUENCE_NO NUMBER(10) NOT NULL,
    STAGE VARCHAR2(32 CHAR) NOT NULL,
    MESSAGE VARCHAR2(1000 CHAR),
    PAYLOAD_JSON JSON,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_ASST_RUN_EVENT_SEQ UNIQUE (RUN_ID, SEQUENCE_NO),
    CONSTRAINT FK_ASST_RUN_EVENT_RUN FOREIGN KEY (RUN_ID, DOMAIN_ID)
        REFERENCES KBOT_ASST_RUN (RUN_ID, DOMAIN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_ASST_RUN_EVENT_STAGE CHECK (STAGE IN (
        'ACCEPTED', 'SEARCHING', 'ORGANIZING_SOURCES', 'COMPOSING',
        'GENERATING', 'COMPLETED', 'REJECTED', 'FAILED'
    ))
);


CREATE TABLE KBOT_ASST_X_SOURCE (
    SOURCE_ID RAW(16) PRIMARY KEY,
    RUN_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_ORDER NUMBER(10) NOT NULL,
    CITATION_LABEL VARCHAR2(16 CHAR) NOT NULL,
    PROVIDER_CITATION_ID VARCHAR2(256 CHAR) NOT NULL,
    CANONICAL_URL VARCHAR2(2048 CHAR) NOT NULL,
    TITLE VARCHAR2(512 CHAR),
    EXCERPT VARCHAR2(4000 CHAR),
    AUTHOR_HANDLE VARCHAR2(128 CHAR),
    PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE,
    RETRIEVED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_ASST_X_SOURCE_LABEL UNIQUE (RUN_ID, CITATION_LABEL),
    CONSTRAINT FK_ASST_X_SOURCE_RUN FOREIGN KEY (RUN_ID, DOMAIN_ID)
        REFERENCES KBOT_ASST_RUN (RUN_ID, DOMAIN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_ASST_X_SOURCE_ORDER CHECK (DISPLAY_ORDER > 0)
);

CREATE INDEX IX_ASST_X_SOURCE_RUN ON KBOT_ASST_X_SOURCE (RUN_ID, DISPLAY_ORDER);

CREATE TABLE KBOT_ASST_PROMPT_REVISION (
    PROMPT_REVISION_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    RUN_ID RAW(16),
    ACTOR_ID VARCHAR2(256 CHAR) NOT NULL,
    PROMPT CLOB NOT NULL,
    ASPECT_RATIO VARCHAR2(16 CHAR) NOT NULL,
    IMAGE_COUNT NUMBER(2) DEFAULT 1 NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ASST_PROMPT_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_ASST_PROMPT_RUN FOREIGN KEY (RUN_ID)
        REFERENCES KBOT_ASST_RUN (RUN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_ASST_PROMPT_COUNT CHECK (IMAGE_COUNT >= 1 AND IMAGE_COUNT <= 4),
    CONSTRAINT CK_ASST_PROMPT_VERSION CHECK (VERSION_NO > 0)
);

CREATE INDEX IX_ASST_PROMPT_RUN ON KBOT_ASST_PROMPT_REVISION (RUN_ID);

CREATE TABLE KBOT_ASST_MEDIA_ASSET (
    ASSET_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    RUN_ID RAW(16) NOT NULL,
    PROMPT_REVISION_ID RAW(16),
    OBJECT_KEY VARCHAR2(1024 CHAR) NOT NULL,
    MIME_TYPE VARCHAR2(64 CHAR) NOT NULL,
    BYTE_SIZE NUMBER(19) NOT NULL,
    CONTENT_SHA256 VARCHAR2(64 CHAR) NOT NULL,
    WIDTH NUMBER(10),
    HEIGHT NUMBER(10),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'READY' NOT NULL,
    PROVIDER_ARTIFACT_ID VARCHAR2(256 CHAR),
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ASST_MEDIA_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_ASST_MEDIA_RUN FOREIGN KEY (RUN_ID, DOMAIN_ID)
        REFERENCES KBOT_ASST_RUN (RUN_ID, DOMAIN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_ASST_MEDIA_STATUS CHECK (STATUS IN ('READY', 'REJECTED', 'FAILED')),
    CONSTRAINT CK_ASST_MEDIA_SIZE CHECK (BYTE_SIZE > 0)
);

CREATE INDEX IX_ASST_MEDIA_DOMAIN ON KBOT_ASST_MEDIA_ASSET (DOMAIN_ID, CREATED_AT);
CREATE INDEX IX_ASST_MEDIA_RUN ON KBOT_ASST_MEDIA_ASSET (RUN_ID);
