
-- ###########################################################################
-- 1 KBOT_MD_DOMAIN (Business Domain Information Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_DOMAIN (
    DOMAIN_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID       NUMBER NOT NULL ENABLE,
    NAME         VARCHAR2(256),
    STATUS       NUMBER(1) DEFAULT 0,
    DESCS        VARCHAR2(512),
    CREATED_BY   VARCHAR2(512),
    CREATED_TIME DATE DEFAULT CURRENT_DATE,
    UPDATED_BY   VARCHAR2(512),
    UPDATED_TIME DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (DOMAIN_ID) USING INDEX ENABLE,
    -- Unique constraint for (NAME, APP_ID)
    CONSTRAINT KBOT_MD_DOMAIN_CON UNIQUE (NAME, APP_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_DOMAIN IS 'Business Domain Information Table - Stores business domain configuration';
-- Column comments
COMMENT ON COLUMN KBOT_MD_DOMAIN.DOMAIN_ID IS 'Business domain ID, primary key';
COMMENT ON COLUMN KBOT_MD_DOMAIN.APP_ID IS 'Associated APP ID (composes unique index with NAME)';
COMMENT ON COLUMN KBOT_MD_DOMAIN.NAME IS 'Business domain name';
COMMENT ON COLUMN KBOT_MD_DOMAIN.STATUS IS 'Status: 1 - Enabled, 0 - Disabled (mislabeled as prompt status in original)';
COMMENT ON COLUMN KBOT_MD_DOMAIN.DESCS IS 'Business domain description';
COMMENT ON COLUMN KBOT_MD_DOMAIN.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_DOMAIN.CREATED_TIME IS 'Creation time (default: current date)';
COMMENT ON COLUMN KBOT_MD_DOMAIN.UPDATED_BY IS 'Last updater user';
COMMENT ON COLUMN KBOT_MD_DOMAIN.UPDATED_TIME IS 'Last update time (default: current date)';

-- ###########################################################################
-- 2 KBOT_MD_KB (Knowledge Base Metadata Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_KB (
    KB_ID               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID              NUMBER NOT NULL ENABLE,
    DOMAIN_ID           NUMBER,
    KB_NAME             VARCHAR2(256),
    KB_CATEGORY         NUMBER(2),
    DESCS               VARCHAR2(512),
    TXT_EMBED_MODEL_ID  NUMBER,
    IMG_EMBED_MODEL_ID  NUMBER,
    IMG2TXT_MODEL_ID    NUMBER,
    LLM_MODEL_ID        NUMBER,
    KB_STATUS           NUMBER(1),
    SECURITY_LEVEL      NUMBER(1),
    PROCESS_PRIORITY    NUMBER(1),
    CREATED_BY          VARCHAR2(512),
    CREATED_TIME        DATE DEFAULT CURRENT_DATE,
    UPDATED_BY          VARCHAR2(512),
    UPDATED_TIME        DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (KB_ID) USING INDEX ENABLE,
    -- Unique constraint for (KB_NAME, DOMAIN_ID, APP_ID)
    CONSTRAINT KBOT_KB_CON UNIQUE (KB_NAME, DOMAIN_ID, APP_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_KB IS 'Knowledge Base Metadata Table - Stores core KB configuration';
-- Column comments
COMMENT ON COLUMN KBOT_MD_KB.KB_ID IS 'Unique knowledge base identifier, primary key';
COMMENT ON COLUMN KBOT_MD_KB.APP_ID IS 'Associated application ID (composite unique constraint with DOMAIN_ID and KB_NAME)';
COMMENT ON COLUMN KBOT_MD_KB.DOMAIN_ID IS 'Associated business domain ID';
COMMENT ON COLUMN KBOT_MD_KB.KB_NAME IS 'Knowledge base name (unique within the same business domain)';
COMMENT ON COLUMN KBOT_MD_KB.KB_CATEGORY IS 'Knowledge base type enumeration';
COMMENT ON COLUMN KBOT_MD_KB.DESCS IS 'Detailed knowledge base description';
COMMENT ON COLUMN KBOT_MD_KB.TXT_EMBED_MODEL_ID IS 'Text embedding model ID';
COMMENT ON COLUMN KBOT_MD_KB.IMG_EMBED_MODEL_ID IS 'Image embedding model ID';
COMMENT ON COLUMN KBOT_MD_KB.IMG2TXT_MODEL_ID IS 'Image-to-text model ID';
COMMENT ON COLUMN KBOT_MD_KB.LLM_MODEL_ID IS 'LLM model ID';
COMMENT ON COLUMN KBOT_MD_KB.KB_STATUS IS 'Knowledge base status enumeration';
COMMENT ON COLUMN KBOT_MD_KB.SECURITY_LEVEL IS 'File security level enumeration';
COMMENT ON COLUMN KBOT_MD_KB.PROCESS_PRIORITY IS 'Processing priority enumeration';
COMMENT ON COLUMN KBOT_MD_KB.CREATED_BY IS 'Record creator';
COMMENT ON COLUMN KBOT_MD_KB.CREATED_TIME IS 'Record creation time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_KB.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_KB.UPDATED_TIME IS 'Last update time (default: current system time)';

-- ###########################################################################
-- 3 KBOT_MD_KB_BATCH (Knowledge Base Batch Information Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_KB_BATCH (
    BATCH_ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID       NUMBER NOT NULL ENABLE,
    BATCH_NAME   VARCHAR2(256) NOT NULL ENABLE,
    KB_ID        NUMBER NOT NULL ENABLE,
    CREATED_BY   VARCHAR2(512),
    CREATED_TIME DATE DEFAULT CURRENT_DATE,
    UPDATED_BY   VARCHAR2(512),
    UPDATED_TIME DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (BATCH_ID) USING INDEX ENABLE,
    -- Unique constraint for (KB_ID, BATCH_NAME, APP_ID)
    CONSTRAINT KBOT_KB_BATCH_CON UNIQUE (KB_ID, BATCH_NAME, APP_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_KB_BATCH IS 'Knowledge Base Batch Information Table - Records batch operation info for KBs';
-- Column comments
COMMENT ON COLUMN KBOT_MD_KB_BATCH.BATCH_ID IS 'Unique batch identifier, primary key';
COMMENT ON COLUMN KBOT_MD_KB_BATCH.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_KB_BATCH.BATCH_NAME IS 'Batch name (composite unique constraint with KB_ID)';
COMMENT ON COLUMN KBOT_MD_KB_BATCH.KB_ID IS 'Associated knowledge base ID';
COMMENT ON COLUMN KBOT_MD_KB_BATCH.CREATED_BY IS 'Batch creator';
COMMENT ON COLUMN KBOT_MD_KB_BATCH.CREATED_TIME IS 'Batch creation time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_KB_BATCH.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_KB_BATCH.UPDATED_TIME IS 'Last update time (default: current system time)';

-- ###########################################################################
-- 4 KBOT_MD_KB_FILES (Knowledge Base File Information Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_KB_FILES (
    FILE_ID            VARCHAR2(256) NOT NULL,
    APP_ID             NUMBER NOT NULL,
    KB_ID              NUMBER NOT NULL,
    BATCH_ID           NUMBER NOT NULL,
    FILE_PATH          VARCHAR2(512),
    FILE_NAME          VARCHAR2(256),
    FILE_EXT           VARCHAR2(256),
    STATUS             NUMBER(2),
    FILE_VERSION       NUMBER,
    IS_OVERWRITE       NUMBER(1),
    SECURITY_LEVEL     NUMBER(1) DEFAULT 1,
    FILE_SIZE          NUMBER,
    CHUNK_PARSER       JSON,
    BIZ_METADATA       JSON,
    PROCESS_PRIORITY   NUMBER,
    LOG_MSG            VARCHAR2(4000),
    CREATED_BY         VARCHAR2(512),
    CREATED_TIME       DATE DEFAULT CURRENT_DATE,
    UPDATED_BY         VARCHAR2(512),
    UPDATED_TIME       DATE DEFAULT CURRENT_DATE,
    APPROVED_BY        VARCHAR2(256),
    APPROVED_TIME      DATE DEFAULT CURRENT_DATE,
    APPROVE_COMMENTS   VARCHAR2(1024),
    -- Primary key constraint
    PRIMARY KEY (FILE_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_KB_FILES IS 'Knowledge Base File Information Table - Stores status and metadata for all KB files';
-- Column comments
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_ID IS 'Unique file identifier, primary key';
COMMENT ON COLUMN KBOT_MD_KB_FILES.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_KB_FILES.KB_ID IS 'Associated knowledge base ID';
COMMENT ON COLUMN KBOT_MD_KB_FILES.BATCH_ID IS 'Associated batch ID (optional)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_PATH IS 'Full file storage path (including filename)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_NAME IS 'Original filename (without extension)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_EXT IS 'File extension';
COMMENT ON COLUMN KBOT_MD_KB_FILES.STATUS IS 'File status enumeration';
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_VERSION IS 'File version number (increments on each update)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.IS_OVERWRITE IS 'Overwrite flag: 1 - Yes, 0 - No';
COMMENT ON COLUMN KBOT_MD_KB_FILES.SECURITY_LEVEL IS 'File security level enumeration';
COMMENT ON COLUMN KBOT_MD_KB_FILES.FILE_SIZE IS 'File size (in bytes)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.CHUNK_PARSER IS 'Data chunk parsing parameters (JSON)';COMMENT ON COLUMN KBOT_MD_KB_FILES.BIZ_METADATA IS 'Business metadata (JSON format)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.PROCESS_PRIORITY IS 'Processing priority enumeration';
COMMENT ON COLUMN KBOT_MD_KB_FILES.LOG_MSG IS 'Processing log information';
COMMENT ON COLUMN KBOT_MD_KB_FILES.CREATED_BY IS 'File uploader';
COMMENT ON COLUMN KBOT_MD_KB_FILES.CREATED_TIME IS 'Upload time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_KB_FILES.UPDATED_TIME IS 'Last update time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_KB_FILES.APPROVED_BY IS 'Approver user';
COMMENT ON COLUMN KBOT_MD_KB_FILES.APPROVED_TIME IS 'Approval time';
COMMENT ON COLUMN KBOT_MD_KB_FILES.APPROVE_COMMENTS IS 'Approval comments';

-- ###########################################################################
-- 5 KBOT_MD_PROMPT (Prompt Information Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_PROMPT (
    PROMPT_ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID             NUMBER NOT NULL ENABLE,
    DOMAIN_ID          NUMBER,
    NAME               VARCHAR2(256),
    PROMPT_UNIQUE_NAME VARCHAR2(256),
    PROMPT_CATEGORY    NUMBER,
    TEMPLATE           CLOB,
    STATUS             NUMBER(1) DEFAULT 0,
    DESCS              VARCHAR2(512),
    CREATED_BY         VARCHAR2(512),
    CREATED_TIME       DATE DEFAULT CURRENT_DATE,
    UPDATED_BY         VARCHAR2(512),
    UPDATED_TIME       DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (PROMPT_ID) USING INDEX ENABLE,
    -- Unique constraint for prompt unique name
    CONSTRAINT PROMPT_UNIQUE_NAME_UK UNIQUE (PROMPT_UNIQUE_NAME)
);
INSERT INTO KBOT_MD_PROMPT (APP_ID, NAME, PROMPT_UNIQUE_NAME, PROMPT_CATEGORY, TEMPLATE, STATUS) 
VALUES (1, 'image2text', 'SYSTEM/image2text', 1, q'[You are a professional PDF document visual understanding assistant, responsible for identifying all visual content in PDFs, including images, icons, flowcharts, architecture diagrams, schematic diagrams, etc.

Please output descriptions in accordance with the following rules:

1. Ordinary images: Describe the theme, scene, key elements and content of the picture.
2. Icons: Describe the shape, symbolic meaning, functional purpose and representative significance.
3. Flowcharts: Describe the process steps, branches, flow direction and overall logic in sequence.
4. Architecture diagrams / block diagrams: Explain module relationships, hierarchy, data flow and functions.

Requirements: Accurate and concise descriptions, clear structure, output only visible content; list multiple items separately if there are multiple figures.]', 1);

INSERT INTO KBOT_MD_PROMPT (APP_ID, NAME, PROMPT_UNIQUE_NAME, PROMPT_CATEGORY, TEMPLATE, STATUS) 
VALUES (1, 'rewrite_question', 'SYSTEM/rewrite_question', 1, q'[You are the Context and Identity Engine for the RAG system.
Your goal is to transform the user's raw input into a structured execution plan while maintaining a persistent User Profile.

### Recent Dialogue (Short-term Memory)
{chat_history}

### Context Knowledge
- **Historical Summary**: {summary} (General progress of the conversation)
- **Active Session State**: {session_state} (Volatile data: current errors, temporary IPs, active file paths)

### Task 1: Query Rewriting
1. **Pronoun Resolution**: Replace 'it', 'the error', 'there' with specific entities from History/State.
2. **Context Injection**: If the user asks "How to install?", rewrite it as "How to install [Software] on [OS from Session State]?"
3. **Keyword Extraction**: Provide 3-5 high-quality technical keywords for Full-Text Search.

### Task 2: Information Categorization (Crucial)
Distinguish between "Turn Entities" and "User Profile Updates":
- **Turn Entities**: Transient data for the CURRENT turn only (e.g., a specific process ID, a one-time error log snippet).
- **User Profile Updates**: Long-term traits that define WHO the user is or their PERMANENT environment. 
* Examples: Professional role (DBA, Developer), preferred OS (RHEL 8), Hardware specs (Xeon Gold 5520+), habitual coding language (Python), or level of expertise.

### Output Format (Strict JSON)
{{
"standalone_query": "The fully independent and contextualized question",
"search_keywords": ["keyword1", "keyword2", "keyword3"],
"turn_entities": {{
    "temp_file": "/tmp/test.log",
    "current_error_code": "ORA-00600"
}},
"user_profile_updates": {{
    "job_role": "System Architect",
    "primary_os": "Oracle Linux 8.8",
    "cpu_arch": "x86_64",
    "expertise_level": "Senior"
}},
"intent": "troubleshooting | installation | optimization | general_inquiry"
}}

User Input: {query}]', 1);

INSERT INTO KBOT_MD_PROMPT (APP_ID, NAME, PROMPT_UNIQUE_NAME, PROMPT_CATEGORY, TEMPLATE, STATUS) 
VALUES (1, 'refresh_summary', 'SYSTEM/refresh_summary', 1, q'[Analyze the following conversation and provide two types of summaries in a structured JSON format.

### Tasks:
1. **context_summary**: A technical summary of the current session. Focus on the core problem, environment (e.g., OS, versions), and verified solutions/steps.
2. **profile_summary**: A qualitative description of the user. Identify their professional role, expertise level, and communication style based on their questions and technical depth.

### Dialogue History:
{history_text}

### Output Format (Strict JSON):
{{
  "context_summary": "string",
  "profile_summary": "string"
}}]', 1);

INSERT INTO KBOT_MD_PROMPT (APP_ID, NAME, PROMPT_UNIQUE_NAME, PROMPT_CATEGORY, TEMPLATE, STATUS) 
VALUES (1, 'rag_final_render', 'SYSTEM/rag_final_render', 1, q'[{system_prompt}

### 当前环境约束 (Session State)
**[必须遵守]** 以下是当前用户的运行环境：
- {env_str}

### 对话背景摘要 (Context Summary)
**[重要上下文]** 本次会话之前的进展：
{context_summary}

### 历史相关经验 (Long-term Memory)
**[仅供参考]** 以下是过往类似场景的经验（带 ⭐ 为用户认可的方案）：
{long_term_memory}

### 核心知识库依据 (Knowledge Base)
**[主要依据]** 请根据以下权威文档回答问题：
{kb_context}

---
请综合上述背景，优先依据【核心知识库】和【环境约束】。

用户当前的问题：{user_question}
助手回答：]', 1);

INSERT INTO KBOT_MD_PROMPT (APP_ID, NAME, PROMPT_UNIQUE_NAME, PROMPT_CATEGORY, TEMPLATE, STATUS) 
VALUES (1, 'user_profile', 'SYSTEM/user_profile', 1, q'[你是一位资深的系统架构师与用户画像专家。请分析对话并输出 JSON 格式的更新记录。

### 原有画像摘要:
{old_summary}

### 最新对话片段:
Q: {question}
A: {answer}

### 任务指令:
1. 分析最新对话，提取用户的专业身份(如DevOps)、使用的技术栈(如Oracle Linux 8)、当前关注的具体项目或痛点。
2. 将新提取的信息与原有摘要进行逻辑合并。
3. 如果信息重复，则保留；如果信息冲突（如用户从 Ubuntu 换到了 RHEL），以最新对话为准。
4. 保持摘要简洁、专业，总字数不超过 300 字。
5. 直接输出更新后的摘要文本，不要包含“根据对话...”等废话。
### 额外任务：
6. 请为本次对话生成一个【记忆快照】（Memory Snapshot），用于语义搜索。
### 任务要求:
1. 更新【profile_summary】：合并新老信息，字数<300，专业简洁。如果原有摘要为默认初始化信息，请直接以本次对话内容开启新摘要。
2. 生成【memory_snapshot】：本次对话的核心事实快照，需消解指代（如“它”->“Oracle 26ai”），去除废话。

### 输出格式 (必须为纯 JSON):
{{
    "profile_summary": "更新后的完整画像摘要...",
    "memory_snapshot": "本次对话的高纯度事实快照..."
}}]', 1);

COMMIT;

-- Table comment
COMMENT ON TABLE KBOT_MD_PROMPT IS 'Prompt Information Table - Stores various prompt templates';
-- Column comments
COMMENT ON COLUMN KBOT_MD_PROMPT.PROMPT_ID IS 'Unique prompt identifier, primary key';
COMMENT ON COLUMN KBOT_MD_PROMPT.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_PROMPT.DOMAIN_ID IS 'Associated business domain ID (optional)';
COMMENT ON COLUMN KBOT_MD_PROMPT.NAME IS 'Prompt display name';
COMMENT ON COLUMN KBOT_MD_PROMPT.PROMPT_UNIQUE_NAME IS 'Unique prompt name in database (used for model calls in programs)';
COMMENT ON COLUMN KBOT_MD_PROMPT.PROMPT_CATEGORY IS 'Prompt category enumeration';
COMMENT ON COLUMN KBOT_MD_PROMPT.TEMPLATE IS 'Prompt template content (CLOB large text)';
COMMENT ON COLUMN KBOT_MD_PROMPT.STATUS IS 'Prompt status: 1 - Enabled, 0 - Disabled';
COMMENT ON COLUMN KBOT_MD_PROMPT.DESCS IS 'Detailed prompt description';
COMMENT ON COLUMN KBOT_MD_PROMPT.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_PROMPT.CREATED_TIME IS 'Creation time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_PROMPT.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_PROMPT.UPDATED_TIME IS 'Last update time (default: current system time)';

-- ###########################################################################
-- 6 KBOT_MD_MODELS (AI Model Information Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_MODELS (
    MODEL_ID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID        NUMBER NOT NULL ENABLE,
    DISPLAY_NAME  VARCHAR2(256) NOT NULL,
    MODEL_NAME    VARCHAR2(256) NOT NULL,
    CATEGORY      NUMBER NOT NULL,
    PROVIDER      VARCHAR2(256) NOT NULL,
    API_ENDPOINT  VARCHAR2(256),
    API_KEY       VARCHAR2(256),
    STATUS        NUMBER(1) DEFAULT 0,
    MODEL_PARAMS  JSON,
    DESCS         VARCHAR2(512),
    CREATED_BY    VARCHAR2(512),
    CREATED_TIME  DATE DEFAULT CURRENT_DATE,
    UPDATED_BY    VARCHAR2(512),
    UPDATED_TIME  DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (MODEL_ID) USING INDEX ENABLE,
    -- Unique constraint for (DISPLAY_NAME, APP_ID)
    CONSTRAINT KBOT_UK_APP_MODEL UNIQUE (DISPLAY_NAME, APP_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_MODELS IS 'AI Model Information Table - Stores configuration for various AI models';
-- Column comments
COMMENT ON COLUMN KBOT_MD_MODELS.MODEL_ID IS 'Unique model identifier, primary key';
COMMENT ON COLUMN KBOT_MD_MODELS.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_MODELS.DISPLAY_NAME IS 'Model display name (user-friendly)';
COMMENT ON COLUMN KBOT_MD_MODELS.MODEL_NAME IS 'Model technical name (e.g., gpt-4, text-embedding-ada-002)';
COMMENT ON COLUMN KBOT_MD_MODELS.CATEGORY IS 'Model category enumeration (MODEL_CATEGORY)';
COMMENT ON COLUMN KBOT_MD_MODELS.PROVIDER IS 'Model provider (e.g., OpenAI, Azure, Anthropic)';
COMMENT ON COLUMN KBOT_MD_MODELS.API_ENDPOINT IS 'API endpoint URL (e.g., https://api.openai.com/v1)';
COMMENT ON COLUMN KBOT_MD_MODELS.API_KEY IS 'API key (recommended to store encrypted)';
COMMENT ON COLUMN KBOT_MD_MODELS.STATUS IS 'Model status: 1 - Enabled, 0 - Disabled';
COMMENT ON COLUMN KBOT_MD_MODELS.MODEL_PARAMS IS 'Default model parameters (JSON, e.g., {"TEMPERATURE":0,"MAX_TOKENS":1024})';
COMMENT ON COLUMN KBOT_MD_MODELS.DESCS IS 'Detailed model description';
COMMENT ON COLUMN KBOT_MD_MODELS.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_MODELS.CREATED_TIME IS 'Creation time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_MODELS.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_MODELS.UPDATED_TIME IS 'Last update time (default: current system time)';


-- ###########################################################################
-- 7 KBOT_MD_SYS_CONF (System Configuration Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_SYS_CONF (
    CONF_ID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID       NUMBER NOT NULL ENABLE,
    PARAM_TYPE   NUMBER(2),
    PARAM_NAME   VARCHAR2(256),
    PARAM_VALUE  VARCHAR2(256),
    STATUS       NUMBER(1) DEFAULT 0,
    DESCS        VARCHAR2(512),
    CREATED_BY   VARCHAR2(512),
    CREATED_TIME DATE DEFAULT CURRENT_DATE,
    UPDATED_BY   VARCHAR2(512),
    UPDATED_TIME DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (CONF_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_SYS_CONF IS 'System Configuration Table - Stores various configuration parameters for the application';
-- Column comments
COMMENT ON COLUMN KBOT_MD_SYS_CONF.CONF_ID IS 'Unique configuration item identifier, primary key';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.PARAM_TYPE IS 'Parameter type enumeration';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.PARAM_NAME IS 'Parameter name (e.g., ImageToTextModel - Image to Text Model, SpeechToTextModel - Speech to Text Model)';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.PARAM_VALUE IS 'Parameter value';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.STATUS IS 'Configuration status: 1 - Enabled, 0 - Disabled';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.DESCS IS 'Detailed configuration item description';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.CREATED_TIME IS 'Creation time (default: current system time)';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_SYS_CONF.UPDATED_TIME IS 'Last update time (default: current system time)';


-- ###########################################################################
-- 8 KBOT_MD_AGENT (AI Agent Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_AGENT (
    AGENT_ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DOMAIN_ID               NUMBER,
    APP_ID                  NUMBER,
    AGENT_NAME              VARCHAR2(256),
    AGENT_DESC              VARCHAR2(512),
    WELCOME                 VARCHAR2(512),
    PROMPT_ID               NUMBER,
    LLM_ID                  NUMBER NOT NULL,
    LLM_PARAMS              JSON,
    EMBEDDING_MODEL_ID      NUMBER NOT NULL,
    FEEDBACK_SIMILARITY_FLAG NUMBER(1) DEFAULT 0,
    SYNONYM_SIMILARITY_FLAG NUMBER(1) DEFAULT 0,
    RERANKER_MODEL_ID       NUMBER,
    RERANKER_TOPK           NUMBER,
    RERANKER_SCORE_THRESHOLD NUMBER,
    AGENT_STATUS            NUMBER(2),
    CREATED_BY              VARCHAR2(256),
    CREATED_TIME            DATE DEFAULT CURRENT_DATE,
    UPDATED_BY              VARCHAR2(256),
    UPDATED_TIME            DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (AGENT_ID) USING INDEX ENABLE
);

-- Unique index for (DOMAIN_ID, APP_ID, AGENT_NAME)
CREATE UNIQUE INDEX KBOT_MD_AGENT_UIDX ON KBOT_MD_AGENT (DOMAIN_ID, APP_ID, AGENT_NAME);

-- Table comment
COMMENT ON TABLE KBOT_MD_AGENT IS 'AI Agent Table - Stores agent configuration information';
-- Column comments
COMMENT ON COLUMN KBOT_MD_AGENT.AGENT_ID IS 'Primary key ID';
COMMENT ON COLUMN KBOT_MD_AGENT.DOMAIN_ID IS 'Associated business domain ID';
COMMENT ON COLUMN KBOT_MD_AGENT.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_AGENT.AGENT_NAME IS 'Agent name';
COMMENT ON COLUMN KBOT_MD_AGENT.AGENT_DESC IS 'Agent description';
COMMENT ON COLUMN KBOT_MD_AGENT.WELCOME IS 'Welcome message';
COMMENT ON COLUMN KBOT_MD_AGENT.PROMPT_ID IS 'Prompt ID';
COMMENT ON COLUMN KBOT_MD_AGENT.LLM_ID IS 'Large Language Model ID';
COMMENT ON COLUMN KBOT_MD_AGENT.LLM_PARAMS IS 'LLM parameter configuration (JSON format)';
COMMENT ON COLUMN KBOT_MD_AGENT.EMBEDDING_MODEL_ID IS 'Embedding Model ID';
COMMENT ON COLUMN KBOT_MD_AGENT.FEEDBACK_SIMILARITY_FLAG IS 'Feedback similarity toggle: 1 - Enabled, 0 - Disabled';
COMMENT ON COLUMN KBOT_MD_AGENT.SYNONYM_SIMILARITY_FLAG IS 'Synonym similarity toggle: 1 - Enabled, 0 - Disabled';
COMMENT ON COLUMN KBOT_MD_AGENT.RERANKER_MODEL_ID IS 'Reranker model ID';
COMMENT ON COLUMN KBOT_MD_AGENT.RERANKER_TOPK IS 'Number of reranked results to retrieve';
COMMENT ON COLUMN KBOT_MD_AGENT.RERANKER_SCORE_THRESHOLD IS 'Reranker score threshold';
COMMENT ON COLUMN KBOT_MD_AGENT.AGENT_STATUS IS 'Status: 1 - NEW, 2 - ENABLED, 3 - DISABLED, 4 - ARCHIVED';
COMMENT ON COLUMN KBOT_MD_AGENT.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_AGENT.CREATED_TIME IS 'Creation time';
COMMENT ON COLUMN KBOT_MD_AGENT.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_AGENT.UPDATED_TIME IS 'Last update time';

-- ###########################################################################
-- 9 KBOT_MD_AGENT_CONF (AI Agent KB Configuration Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_AGENT_CONF (
    CONF_ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID                 NUMBER,
    AGENT_ID               NUMBER,
    TOOL_ID                NUMBER,
    TOOL_TYPE              NUMBER(2),
    TOOL_WEIGHT            NUMBER(2,2),
    RERANKER_FLAG          NUMBER(1),
    SEARCH_TYPE            NUMBER(2),
    SEARCH_TOPK            NUMBER,
    SEARCH_SCORE_THRESHOLD NUMBER,
    CREATED_BY             VARCHAR2(256),
    CREATED_TIME           DATE DEFAULT CURRENT_DATE,
    UPDATED_BY             VARCHAR2(256),
    UPDATED_TIME           DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (CONF_ID) USING INDEX ENABLE,
    -- Unique constraint
    CONSTRAINT KBOT_MD_AGENT_CONF_CON UNIQUE (AGENT_ID, TOOL_ID, SEARCH_TYPE, APP_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_AGENT_CONF IS 'AI Agent KB Configuration Table - Stores association between agents and knowledge bases';
-- Column comments
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.CONF_ID IS 'Primary key ID';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.AGENT_ID IS 'AI agent ID';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.TOOL_ID IS 'KB ID / FUNC_ID etc.';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.TOOL_TYPE IS 'Tool type enumeration';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.TOOL_WEIGHT IS 'KB retrieval weight (0.00-1.00)';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.RERANKER_FLAG IS 'Reranking required: 1 - Yes, 0 - No';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.SEARCH_TYPE IS 'Search type enumeration';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.SEARCH_TOPK IS 'Number of search results to retrieve (TOPK)';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.SEARCH_SCORE_THRESHOLD IS 'Search similarity threshold';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.CREATED_TIME IS 'Creation time';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_AGENT_CONF.UPDATED_TIME IS 'Last update time';

-- ###########################################################################
-- 10 KBOT_MD_DATA_DIC (Data Dictionary Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_DATA_DIC (
    DIC_ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID              NUMBER,
    NAME                VARCHAR2(256),
    DISPLAY_NAME        VARCHAR2(256),
    RETURN_VALUE        VARCHAR2(256),
    LANG_CODE           VARCHAR2(256),
    DISPLAY_TRAN_VALUE  VARCHAR2(256),
    STATUS              NUMBER(1) DEFAULT 0,
    IS_DEFAULT          NUMBER(1) DEFAULT 0,
    DESCS               VARCHAR2(256),
    CREATED_BY          VARCHAR2(256),
    CREATED_TIME        DATE DEFAULT CURRENT_DATE,
    UPDATED_BY          VARCHAR2(256),
    UPDATED_TIME        DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (DIC_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_DATA_DIC IS 'Data Dictionary Table - Stores key-value pairs for system enumerations and translations';
-- Column comments
COMMENT ON COLUMN KBOT_MD_DATA_DIC.DIC_ID IS 'Primary key ID';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.NAME IS 'Data dictionary name';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.DISPLAY_NAME IS 'Display name';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.RETURN_VALUE IS 'Return value';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.LANG_CODE IS 'Language code (e.g., zh-CN, en-US)';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.DISPLAY_TRAN_VALUE IS 'Multi-language display value';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.STATUS IS 'Status: 1 - Enabled, 0 - Disabled';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.IS_DEFAULT IS 'Default flag: 1 - Yes, 0 - No';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.DESCS IS 'Description';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.CREATED_TIME IS 'Creation time';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_DATA_DIC.UPDATED_TIME IS 'Last update time';

-- ###########################################################################
-- 11 KBOT_MD_RELEASE_NOTE (Release Notes Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_RELEASE_NOTE (
    RELEASE_ID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID          NUMBER,
    RELEASE_TITLE   VARCHAR2(256),
    RELEASE_CONTENT VARCHAR2(4000),
    CREATED_BY      VARCHAR2(256),
    CREATED_TIME    DATE DEFAULT CURRENT_DATE,
    UPDATED_BY      VARCHAR2(256),
    UPDATED_TIME    DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    PRIMARY KEY (RELEASE_ID) USING INDEX ENABLE
);

-- Table comment
COMMENT ON TABLE KBOT_MD_RELEASE_NOTE IS 'Release Notes Table - Stores version release information and changelogs';
-- Column comments
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.RELEASE_ID IS 'Primary key ID';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.RELEASE_TITLE IS 'Release note title';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.RELEASE_CONTENT IS 'Release note content';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.CREATED_BY IS 'Creator user';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.CREATED_TIME IS 'Creation time';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_RELEASE_NOTE.UPDATED_TIME IS 'Last update time';

-- ###########################################################################
-- 12 KBOT_MD_ACTION_RECORD (System Action Record Table)
-- ###########################################################################
CREATE TABLE KBOT_MD_ACTION_RECORD (
    RECORD_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APP_ID       NUMBER,
    FUNC_NAME    VARCHAR2(100),
    ACTION       VARCHAR2(4000),
    CREATED_BY   VARCHAR2(256),
    CREATED_TIME DATE DEFAULT CURRENT_DATE,
    UPDATED_BY   VARCHAR2(256),
    UPDATED_TIME DATE DEFAULT CURRENT_DATE,
    -- Primary key constraint
    CONSTRAINT PK_KBOT_MD_ACTION_RECORD PRIMARY KEY (RECORD_ID)
);

-- Table comment
COMMENT ON TABLE KBOT_MD_ACTION_RECORD IS 'System Action Record Table - Logs all user operations in the application';
-- Column comments
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.RECORD_ID IS 'Record ID, primary key';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.APP_ID IS 'Associated application ID';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.FUNC_NAME IS 'Function name related to the operation';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.ACTION IS 'Operation type (Create/Edit/Delete etc.)';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.CREATED_BY IS 'Operation executor';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.CREATED_TIME IS 'Operation time (default: current time)';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.UPDATED_BY IS 'Last updater';
COMMENT ON COLUMN KBOT_MD_ACTION_RECORD.UPDATED_TIME IS 'Last update time (default: current time)';

-- ###########################################################################
-- 13 KBOT_BIZ_TXT_EMBEDDING (Text Embedding Table)
-- ###########################################################################
CREATE TABLE KBOT_BIZ_TXT_EMBEDDING (
    CHUNK_ID        VARCHAR2(256) NOT NULL,
    KB_ID           NUMBER NOT NULL,
    FILE_ID         VARCHAR2(256) NOT NULL,
    CONTENT         CLOB NOT NULL,
    STRUCTURE_LEVEL NUMBER(38,0),
    PATH_NAMES      VARCHAR2(4000),
    CHUNK_TYPE      VARCHAR2(20),
    EMBEDDING       VECTOR NOT NULL,
    CHUNK_METADATA  JSON NOT NULL,
    SECURITY_LEVEL  NUMBER(1,0),
    IS_ACTIVE       NUMBER(1) DEFAULT 1,
    BIZ_METADATA    JSON,
    -- Primary key constraint
    PRIMARY KEY (CHUNK_ID) USING INDEX ENABLE
);
CREATE INDEX IDX_FULLSEARCH_TXT_EMBEDDING ON  KBOT_BIZ_TXT_EMBEDDING("CONTENT") INDEXTYPE IS "CTXSYS"."CONTEXT" PARAMETERS ('lexer chinese_lexer');
CREATE INDEX IDX_FULLSEARCH_TXT_PATH_NAMES ON  KBOT_BIZ_TXT_EMBEDDING("PATH_NAMES") INDEXTYPE IS "CTXSYS"."CONTEXT" PARAMETERS ('lexer chinese_lexer');
-- Table comment
COMMENT ON TABLE KBOT_BIZ_TXT_EMBEDDING IS 'Text Embedding Table - Stores vectorized representations of text chunks';
-- Column comments
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.CHUNK_ID IS 'Unique vector record identifier, primary key';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.KB_ID IS 'Associated KB ID';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.FILE_ID IS 'Associated file ID';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.CONTENT IS 'Original text chunk content';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.STRUCTURE_LEVEL IS 'Structure level (document depth)';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.PATH_NAMES IS 'Path names (e.g., chapter/section hierarchy)';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.CHUNK_TYPE IS 'Chunk type (text, table, picture, heading)';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.EMBEDDING IS 'Vector embedding of text chunk';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.CHUNK_METADATA IS 'Text chunk metadata (JSON, includes source path, file type etc.)';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.SECURITY_LEVEL IS 'File security level enumeration';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.IS_ACTIVE IS 'Embedding status: 1 - Active, 0 - Inactive';
COMMENT ON COLUMN KBOT_BIZ_TXT_EMBEDDING.BIZ_METADATA IS 'Business metadata (JSON)';

-- ###########################################################################
-- API Security Related Tables
-- ###########################################################################
CREATE TABLE kbot_sys_auth (
    id              NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50) NOT NULL,
    email           VARCHAR2(100) NOT NULL,
    hashed_password VARCHAR2(255) NOT NULL,
    is_active       NUMBER(1,0) DEFAULT 1,
    is_superuser    NUMBER(1,0) DEFAULT 0,
    last_login_at   TIMESTAMP,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    -- Unique constraints
    CONSTRAINT uk_kbot_sys_auth_username UNIQUE (username),
    CONSTRAINT uk_kbot_sys_auth_email UNIQUE (email)
);

COMMENT ON TABLE kbot_sys_auth IS 'User Authentication Table - Stores user account information and credentials';
COMMENT ON COLUMN kbot_sys_auth.id IS 'User ID, primary key';
COMMENT ON COLUMN kbot_sys_auth.username IS 'Unique username (50 chars max)';
COMMENT ON COLUMN kbot_sys_auth.email IS 'Unique email address (100 chars max)';
COMMENT ON COLUMN kbot_sys_auth.hashed_password IS 'BCrypt hashed password';
COMMENT ON COLUMN kbot_sys_auth.is_active IS 'Account status: 1 - Active, 0 - Inactive';
COMMENT ON COLUMN kbot_sys_auth.is_superuser IS 'Superuser flag: 1 - Yes, 0 - No';
COMMENT ON COLUMN kbot_sys_auth.last_login_at IS 'Last login timestamp';
COMMENT ON COLUMN kbot_sys_auth.created_at IS 'Account creation timestamp';
COMMENT ON COLUMN kbot_sys_auth.updated_at IS 'Last account update timestamp';

CREATE TABLE kbot_sys_auth_token (
    id            NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti           VARCHAR2(36) NOT NULL,
    user_id       NUMBER(38,0) NOT NULL,
    device_info   VARCHAR2(200),
    ip_address    VARCHAR2(45),
    user_agent    VARCHAR2(500),
    status        VARCHAR2(20) DEFAULT 'ACTIVE',
    expires_at    TIMESTAMP NOT NULL,
    revoked_reason VARCHAR2(200),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    revoked_at    TIMESTAMP,
    -- Unique constraint
    CONSTRAINT uk_kbot_sys_auth_token_jti UNIQUE (jti)
);

-- Indexes
CREATE INDEX idx_kbot_sys_auth_token_user_status ON kbot_sys_auth_token(user_id, status, expires_at);

COMMENT ON TABLE kbot_sys_auth_token IS 'User Token Table - Stores JWT tokens for user authentication';
COMMENT ON COLUMN kbot_sys_auth_token.id IS 'Token ID, primary key';
COMMENT ON COLUMN kbot_sys_auth_token.jti IS 'JWT ID (unique token identifier)';
COMMENT ON COLUMN kbot_sys_auth_token.user_id IS 'Associated user ID';
COMMENT ON COLUMN kbot_sys_auth_token.device_info IS 'Device information (200 chars max)';
COMMENT ON COLUMN kbot_sys_auth_token.ip_address IS 'Client IP address (IPv4/IPv6 compatible)';
COMMENT ON COLUMN kbot_sys_auth_token.user_agent IS 'Client user agent string (500 chars max)';
COMMENT ON COLUMN kbot_sys_auth_token.status IS 'Token status: ACTIVE/REVOKED/EXPIRED';
COMMENT ON COLUMN kbot_sys_auth_token.expires_at IS 'Token expiration timestamp';
COMMENT ON COLUMN kbot_sys_auth_token.revoked_reason IS 'Reason for revocation (if applicable)';
COMMENT ON COLUMN kbot_sys_auth_token.created_at IS 'Token creation timestamp';
COMMENT ON COLUMN kbot_sys_auth_token.revoked_at IS 'Token revocation timestamp (if applicable)';

CREATE TABLE kbot_sys_services (
    id            NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code  VARCHAR2(50) NOT NULL,
    name          VARCHAR2(100) NOT NULL,
    description   VARCHAR2(4000),
    service_type  VARCHAR2(20) DEFAULT 'INTERNAL',
    owner         VARCHAR2(100),
    contact_email VARCHAR2(100),
    is_active     NUMBER(1,0) DEFAULT 1,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,
    -- Unique constraint
    CONSTRAINT uk_kbot_sys_services_code UNIQUE (service_code)
);

-- Indexes
CREATE INDEX idx_kbot_sys_services_type ON kbot_sys_services(service_type);
CREATE INDEX idx_kbot_sys_services_active ON kbot_sys_services(is_active, service_code);

COMMENT ON TABLE kbot_sys_services IS 'Service Table - Stores API service definitions';
COMMENT ON COLUMN kbot_sys_services.id IS 'Service ID, primary key';
COMMENT ON COLUMN kbot_sys_services.service_code IS 'Unique service code (50 chars max)';
COMMENT ON COLUMN kbot_sys_services.name IS 'Service display name (100 chars max)';
COMMENT ON COLUMN kbot_sys_services.description IS 'Detailed service description (4000 chars max)';
COMMENT ON COLUMN kbot_sys_services.service_type IS 'Service type: INTERNAL/EXTERNAL/THIRD_PARTY';
COMMENT ON COLUMN kbot_sys_services.owner IS 'Service owner name (100 chars max)';
COMMENT ON COLUMN kbot_sys_services.contact_email IS 'Service contact email (100 chars max)';
COMMENT ON COLUMN kbot_sys_services.is_active IS 'Service status: 1 - Active, 0 - Inactive';
COMMENT ON COLUMN kbot_sys_services.created_at IS 'Service creation timestamp';
COMMENT ON COLUMN kbot_sys_services.updated_at IS 'Last service update timestamp';

CREATE TABLE kbot_sys_api_keys (
    id              NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id          VARCHAR2(50) NOT NULL,
    hashed_key      VARCHAR2(255) NOT NULL,
    key_prefix      VARCHAR2(8) NOT NULL,
    name            VARCHAR2(100) NOT NULL,
    service_id      NUMBER(38,0) NOT NULL,
    scopes          VARCHAR2(4000) DEFAULT '[]',
    status          VARCHAR2(20) DEFAULT 'ACTIVE',
    expires_at      TIMESTAMP,
    last_used_at    TIMESTAMP,
    usage_count     NUMBER(38,0) DEFAULT 0,
    allowed_ips     VARCHAR2(4000) DEFAULT '[]',
    rate_limit      NUMBER(38,0) DEFAULT 0,
    created_by      VARCHAR2(50),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    revoked_reason  VARCHAR2(500),
    revoked_at      TIMESTAMP,
    -- Unique constraint
    CONSTRAINT uk_kbot_sys_api_keys_key_id UNIQUE (key_id)
);
-- Indexes
CREATE INDEX idx_kbot_sys_api_keys_active ON kbot_sys_api_keys(service_id, status, expires_at);
CREATE INDEX IDX_API_KEYS_SERVICE_ID ON kbot_sys_api_keys(service_id);

COMMENT ON TABLE kbot_sys_api_keys IS 'API Key Table - Stores API keys for service authentication';
COMMENT ON COLUMN kbot_sys_api_keys.id IS 'API key ID, primary key';
COMMENT ON COLUMN kbot_sys_api_keys.key_id IS 'Unique API key ID (50 chars max)';
COMMENT ON COLUMN kbot_sys_api_keys.hashed_key IS 'Hashed API secret key (BCrypt)';
COMMENT ON COLUMN kbot_sys_api_keys.key_prefix IS 'API key prefix (8 chars max)';
COMMENT ON COLUMN kbot_sys_api_keys.name IS 'API key display name (100 chars max)';
COMMENT ON COLUMN kbot_sys_api_keys.service_id IS 'Associated service ID';
COMMENT ON COLUMN kbot_sys_api_keys.scopes IS 'API access scopes (JSON array)';
COMMENT ON COLUMN kbot_sys_api_keys.status IS 'API key status: ACTIVE/REVOKED/EXPIRED';
COMMENT ON COLUMN kbot_sys_api_keys.expires_at IS 'API key expiration timestamp (null = never expires)';
COMMENT ON COLUMN kbot_sys_api_keys.last_used_at IS 'Last API key usage timestamp';
COMMENT ON COLUMN kbot_sys_api_keys.usage_count IS 'Total API key usage count';
COMMENT ON COLUMN kbot_sys_api_keys.allowed_ips IS 'Allowed IP addresses (JSON array, null = all IPs allowed)';
COMMENT ON COLUMN kbot_sys_api_keys.rate_limit IS 'API rate limit (requests per minute, 0 = unlimited)';
COMMENT ON COLUMN kbot_sys_api_keys.created_by IS 'API key creator username (50 chars max)';
COMMENT ON COLUMN kbot_sys_api_keys.created_at IS 'API key creation timestamp';
COMMENT ON COLUMN kbot_sys_api_keys.updated_at IS 'Last API key update timestamp';
COMMENT ON COLUMN kbot_sys_api_keys.revoked_reason IS 'Reason for revocation (500 chars max)';
COMMENT ON COLUMN kbot_sys_api_keys.revoked_at IS 'API key revocation timestamp (if applicable)';

--###########################################################################
-- KBOT Memory Related Tables
--###########################################################################
-- 1. User Profile Table
CREATE TABLE kbot_md_user_profile (
    user_id VARCHAR2(256) PRIMARY KEY,
    global_preferences JSON CHECK (global_preferences IS JSON),
    frequent_entities JSON CHECK (frequent_entities IS JSON),
    profile_summary CLOB,
    last_update_time TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE kbot_md_user_profile IS 'Stores long-term user characteristics and technical preferences across sessions';
COMMENT ON COLUMN kbot_md_user_profile.user_id IS 'Unique identifier for the user';
COMMENT ON COLUMN kbot_md_user_profile.global_preferences IS 'Persistent technical stack preferences';
COMMENT ON COLUMN kbot_md_user_profile.frequent_entities IS 'Frequently occurring entities (e.g., project names, IPs)';
COMMENT ON COLUMN kbot_md_user_profile.profile_summary IS 'LLM-generated user behavior summary';

-- 2. Conversation Context Table
CREATE TABLE kbot_md_conv_context (
    session_id VARCHAR2(256) PRIMARY KEY,
    user_id VARCHAR2(256) NOT NULL,
    session_title VARCHAR2(256),
    app_id NUMBER(38, 0) NOT NULL,
    agent_id NUMBER NOT NULL,
    session_state JSON CHECK (session_state IS JSON),
    context_summary CLOB,
    interaction_count NUMBER DEFAULT 0,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_active_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE kbot_md_conv_context IS 'Manages active session states and rolling conversation summaries';
COMMENT ON COLUMN kbot_md_conv_context.session_state IS 'Current active state machine parameters';
COMMENT ON COLUMN kbot_md_conv_context.context_summary IS 'Short-to-medium term rolling summary';

-- 3. Memory Entry Table
CREATE TABLE kbot_md_memory_entry (
    entry_id VARCHAR2(256) PRIMARY KEY,
    session_id VARCHAR2(256) NOT NULL,
    standalone_query CLOB,
    search_keywords VARCHAR2(1000),
    memory_vector VECTOR,
    memory_summary CLOB,
    turn_entities JSON CHECK (turn_entities IS JSON),
    raw_question CLOB NOT NULL,
    answer CLOB,
    retrieved_chunks JSON CHECK (retrieved_chunks IS JSON),
    intent_category VARCHAR2(64),
    feedback NUMBER(1, 0) DEFAULT 0,
    request_time TIMESTAMP(6) WITH TIME ZONE,
    response_time TIMESTAMP(6) WITH TIME ZONE
);

-- Optional: Create an HNSW vector index for high-performance memory recall
-- CREATE VECTOR INDEX idx_mem_vector_hnsw ON kbot_md_memory_entry(memory_vector) 
-- ORGANIZATION INMEMORY NEIGHBOR GRAPH DISTANCE COSINE;

COMMENT ON TABLE kbot_md_memory_entry IS 'Records atomic QA interactions with semantic vectors and state snapshots';
COMMENT ON COLUMN kbot_md_memory_entry.standalone_query IS 'Context-enriched rewritten question';
COMMENT ON COLUMN kbot_md_memory_entry.search_keywords IS 'Extracted keywords and synonyms for hybrid search';
COMMENT ON COLUMN kbot_md_memory_entry.memory_vector IS 'Semantic vector of the query for long-term recall';
COMMENT ON COLUMN kbot_md_memory_entry.turn_entities IS 'Entity snapshot for this specific turn';
COMMENT ON COLUMN kbot_md_memory_entry.retrieved_chunks IS 'References used for this answer';
COMMENT ON COLUMN kbot_md_memory_entry.intent_category IS 'Intent category for this turn';
COMMENT ON COLUMN kbot_md_memory_entry.feedback IS 'User feedback for this turn, -1: bad, 0: neutral, 1: good';



# ===========================================
# v3.2 change log
# updated at 2026-03-12
# ===========================================
# update for KBOT_MD_KB_FILES
ALTER TABLE KBOT_MD_KB_FILES DROP COLUMN CHUNKS_CNT;
ALTER TABLE KBOT_MD_KB_FILES DROP COLUMN ENABLE_SUMMARY;
ALTER TABLE KBOT_MD_KB_FILES DROP COLUMN IS_IMG2TXT;
ALTER TABLE KBOT_MD_KB_FILES DROP COLUMN IS_TABLE_HEAD_FILL;
ALTER TABLE KBOT_MD_KB_FILES DROP COLUMN PARSED_METADATA;

# update for KBOT_MD_KB
ALTER TABLE KBOT_MD_KB DROP COLUMN enable_summary;
ALTER TABLE KBOT_MD_KB DROP COLUMN is_img2txt;
ALTER TABLE KBOT_MD_KB DROP COLUMN is_table_head_fill;
ALTER TABLE KBOT_MD_KB DROP COLUMN db_conn_id;
ALTER TABLE KBOT_MD_KB DROP COLUMN summary_model_id;

# v3.2 chunk type update at 2026-03-19
ALTER TABLE KBOT_BIZ_TXT_EMBEDDING MODIFY CHUNK_TYPE VARCHAR2(20);

DROP TABLE KBOT_MD_DB_CONF;
DROP TABLE KBOT_SYS_PARSER_CONF;
DROP TABLE KBOT_MD_PARSER_CONF;
DROP TABLE kbot_md_chat_references;
DROP TABLE kbot_md_chat_qa;
DROP TABLE kbot_md_agent_feedback;
DROP TABLE KBOT_BIZ_IMG_EMBEDDING;
CREATE TABLE KBOT_MD_CHAT_MEMORY;
RECREATE TABLE KBOT_BIZ_TXT_EMBEDDING;
ALTER TABLE KBOT_MD_AGENT ADD (EMBEDDING_MODEL_ID NUMBER(38,0) NOT NULL);
RECREATE TABLE KBOT_MD_MODELS; --DISPLAY_NAME 和 MODEL_NAME 2个字段改为NOT NULL, APP_ID和DISPLAY_NAME构成唯一
CREATE TABLE kbot_md_user_profile;
CREATE TABLE kbot_md_conv_context;
CREATE TABLE kbot_md_memory_entry;
DROP TABLE kbot_md_chat_session;
DROP TABLE KBOT_MD_CHAT_MEMORY;
DROP TABLE KBOT_MD_CHAT_HISTORY;
ALTER TABLE KBOT_MD_KB ADD (LLM_MODEL_ID NUMBER(38,0) NOT NULL);