from pydantic import BaseModel, Field
from typing import Any
import uuid
import time

# ==================== MCP Tool Related Model Definitions ====================

class ToolFunction(BaseModel):
    """Definition of a tool function for MCP (Model Context Protocol) integration.
    
    Represents a single function that can be called by the LLM, including its
    name, descriptive documentation, and parameter schema for validation.
    """
    name: str = Field(..., description="Name of the tool function (must be unique)")
    description: str = Field(..., description="Detailed description of what the function does")
    parameters: dict[str, Any] = Field(..., description="JSON schema defining function parameters")
    
class Tool(BaseModel):
    """Container for tool definition compatible with MCP standard.
    
    Wraps a tool function with its type identifier for LLM tool calling support.
    """
    type: str = Field("function", description="Type of tool (currently only 'function' is supported)")
    function: ToolFunction = Field(..., description="Tool function definition")

class FunctionCall(BaseModel):
    """Details of a specific function call requested by the LLM.
    
    Contains the function name and serialized arguments for execution.
    """
    name: str = Field(..., description="Name of the function to call")
    arguments: str = Field(..., description="JSON string of function arguments")

class ToolCall(BaseModel):
    """Tool call request generated by the LLM.
    
    Represents a complete tool invocation request including unique identifier
    and function call details.
    """
    id: str = Field(..., description="Unique identifier for this tool call")
    type: str = Field("function", description="Type of tool call (currently only 'function' is supported)")
    function: FunctionCall = Field(..., description="Details of the function to be called")

# ==================== Chat Request/Response Models ====================

class UsageInfo(BaseModel):
    """Token usage statistics model, compatible with OpenAI API specification.
    
    Tracks token consumption for prompt, completion, and total usage, with
    optional detailed breakdown fields for advanced usage tracking.
    """
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    # Use Any | None to accept new details field without type conversion errors
    prompt_tokens_details: Any | None = None
    completion_tokens_details: Any | None = None

class ChatResponse(BaseModel):
    """Chat completion response model (OpenAI API compatible).
    
    Standardized response format for chat completions including generated content,
    token usage statistics, and optional tool call information.
    """
    id: str = Field(default_factory=lambda: f"chatcmpl-{uuid.uuid4()}")
    object: str = "chat.completion"
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str
    choices: list[dict[str, Any]]
    # Replaced dict[str, int] with UsageInfo object for type safety
    usage: UsageInfo = Field(..., description="Token usage statistics")
    processing_time: float
    tool_calls: list[ToolCall] | None = None


class ChatRequest(BaseModel):
    """Chat completion request model.
    
    Comprehensive request model for LLM chat completions supporting both basic
    text generation and advanced features like tool calling, streaming, and
    fine-grained generation parameter control.
    """
    model_name: str = Field(..., description="Name of the LLM model to use")
    messages: list[dict[str, str]] | str = Field(..., description="List of chat messages or single prompt string")
    max_tokens: int | None = Field(None, description="Maximum number of tokens to generate")
    temperature: float | None = Field(None, description="Sampling temperature (0.0-1.0, lower=more deterministic)")
    stream: bool = Field(False, description="Whether to stream response incrementally")
    timeout: int | None = Field(None, description="Request timeout in seconds")
    top_p: float | None = Field(None, description="Top-p sampling parameter (0-1)")
    frequency_penalty: float | None = Field(None, description="Penalty for repetitive text (-2 to 2)")
    presence_penalty: float | None = Field(None, description="Penalty for introducing new topics (-2 to 2)")
    tools: list[dict[str, Any]] | None = Field(None, description="List of tools for MCP tool calling")
    tool_choice: str | None = Field(None, description="Tool selection strategy ('auto', 'none', or specific tool name)")
    enable_tool_calls: bool = Field(False, description="Whether to enable tool calling functionality")
    response_format: str | dict[str, str] | None = Field(None, description="Response format specification (e.g., 'json_object' for JSON mode)")

class ToggleModelRequest(BaseModel):
    """Request model for loading/unloading models from the model pool.
    
    Used to dynamically manage model lifecycle in the pool without restarting
    the application.
    """
    model_name: str = Field(..., description="Name of the model to operate on")
    operation: str = Field(..., description="Operation type: 'load' to load model, 'unload' to unload model")