-- KM Asset App：来源配置、Asset 快照、附件、持久任务与 App 私有 Agent。

CREATE TABLE KBOT_KM_SOURCE (
    SOURCE_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    METADB_ENDPOINT VARCHAR2(2048 CHAR) NOT NULL,
    METADB_CREDENTIAL_ID RAW(16) NOT NULL,
    SHAREPOINT_CREDENTIAL_ID RAW(16) NOT NULL,
    SHAREPOINT_SITE_PATH VARCHAR2(512 CHAR) NOT NULL,
    COLLECTION_ID RAW(16) NOT NULL,
    SEMANTIC_MODEL_ID RAW(16),
    POLICY_BINDING_ID RAW(16),
    MODEL_CATALOG_HASH VARCHAR2(64 CHAR),
    MODEL_STATUS VARCHAR2(16 CHAR) DEFAULT 'PENDING' NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    AUTO_SYNC_ENABLED NUMBER(1) DEFAULT 0 NOT NULL,
    POLL_INTERVAL_SECONDS NUMBER(10) DEFAULT 60 NOT NULL,
    BATCH_SIZE NUMBER(10) DEFAULT 100 NOT NULL,
    LAST_SYNC_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KM_SOURCE_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT FK_KM_SOURCE_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_KM_SOURCE_META_CRED FOREIGN KEY (METADB_CREDENTIAL_ID)
        REFERENCES KBOT_MANAGED_CREDENTIAL (CREDENTIAL_ID),
    CONSTRAINT FK_KM_SOURCE_SP_CRED FOREIGN KEY (SHAREPOINT_CREDENTIAL_ID)
        REFERENCES KBOT_MANAGED_CREDENTIAL (CREDENTIAL_ID),
    CONSTRAINT CK_KM_SOURCE_STATUS CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'DISABLED', 'ERROR')),
    CONSTRAINT CK_KM_SOURCE_MODEL_STATUS CHECK (MODEL_STATUS IN ('PENDING', 'READY', 'ERROR')),
    CONSTRAINT CK_KM_SOURCE_AUTO_SYNC CHECK (AUTO_SYNC_ENABLED IN (0, 1)),
    CONSTRAINT CK_KM_SOURCE_LIMITS CHECK (POLL_INTERVAL_SECONDS > 0 AND BATCH_SIZE > 0),
    CONSTRAINT CK_KM_SOURCE_VERSION CHECK (ROW_VERSION > 0)
);
CREATE INDEX IX_KM_SOURCE_SCOPE ON KBOT_KM_SOURCE (DOMAIN_ID, STATUS);

CREATE TABLE KBOT_KM_ASSET (
    KM_ASSET_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    SOURCE_ID RAW(16) NOT NULL,
    EXTERNAL_ASSET_ID VARCHAR2(256 CHAR) NOT NULL,
    SOURCE_REVISION VARCHAR2(256 CHAR),
    SNAPSHOT_HASH VARCHAR2(64 CHAR) NOT NULL,
    SOURCE_STATUS VARCHAR2(16 CHAR) NOT NULL,
    INGESTION_STATUS VARCHAR2(24 CHAR) NOT NULL,
    ASSET_TITLE VARCHAR2(512 CHAR),
    AUTHOR_MAIL VARCHAR2(512 CHAR),
    ASSET_PRODUCT VARCHAR2(512 CHAR),
    ASSET_SOLUTION VARCHAR2(1000 CHAR),
    INDUSTRY_ID VARCHAR2(512 CHAR),
    CONTENT_CATEGORY VARCHAR2(512 CHAR),
    ASSET_STATUS VARCHAR2(128 CHAR),
    PUBLISH_DATE VARCHAR2(128 CHAR),
    LAST_UPDATE_TIME VARCHAR2(128 CHAR),
    RAW_METADATA_JSON JSON NOT NULL,
    NORMALIZED_METADATA_JSON JSON NOT NULL,
    CURRENT_REVISION_ID RAW(16),
    KC_BUNDLE_ID RAW(16),
    KC_BUNDLE_REVISION_ID RAW(16),
    FAILURE_STAGE VARCHAR2(32 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    NEXT_RETRY_AT TIMESTAMP(6) WITH TIME ZONE,
    SYNCED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KM_ASSET_SOURCE UNIQUE (SOURCE_ID, EXTERNAL_ASSET_ID),
    CONSTRAINT UK_KM_ASSET_SCOPE UNIQUE (KM_ASSET_ID, DOMAIN_ID),
    CONSTRAINT FK_KM_ASSET_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_KM_ASSET_SOURCE FOREIGN KEY (SOURCE_ID)
        REFERENCES KBOT_KM_SOURCE (SOURCE_ID),
    CONSTRAINT CK_KM_ASSET_SOURCE_STATUS CHECK (SOURCE_STATUS IN ('N', 'Y', 'F', 'UNKNOWN')),
    CONSTRAINT CK_KM_ASSET_INGEST_STATUS CHECK (INGESTION_STATUS IN ('DISCOVERED', 'SYNC_PENDING', 'DOWNLOADING', 'DOWNLOAD_FAILED', 'READY_FOR_INGESTION', 'INGESTING', 'KC_ACCEPTED', 'PARSING', 'READY', 'RETRY_PENDING', 'FAILED')),
    CONSTRAINT CK_KM_ASSET_ATTEMPT CHECK (ATTEMPT_COUNT >= 0),
    CONSTRAINT CK_KM_ASSET_VERSION CHECK (ROW_VERSION > 0)
);
CREATE INDEX IX_KM_ASSET_SCOPE_STATUS ON KBOT_KM_ASSET (DOMAIN_ID, INGESTION_STATUS, SYNCED_AT);
CREATE INDEX IX_KM_ASSET_AUTHOR ON KBOT_KM_ASSET (DOMAIN_ID, AUTHOR_MAIL);

CREATE TABLE KBOT_KM_ASSET_REVISION (
    ASSET_REVISION_ID RAW(16) PRIMARY KEY,
    KM_ASSET_ID RAW(16) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    REVISION_NO NUMBER(19) NOT NULL,
    SOURCE_REVISION VARCHAR2(256 CHAR) NOT NULL,
    SNAPSHOT_HASH VARCHAR2(64 CHAR) NOT NULL,
    RAW_PAYLOAD_JSON JSON NOT NULL,
    NORMALIZED_PAYLOAD_JSON JSON NOT NULL,
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    KC_BUNDLE_REVISION_ID RAW(16),
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KM_ASSET_REV_NO UNIQUE (KM_ASSET_ID, REVISION_NO),
    CONSTRAINT UK_KM_ASSET_REV_SOURCE UNIQUE (KM_ASSET_ID, SOURCE_REVISION),
    CONSTRAINT UK_KM_ASSET_REV_SCOPE UNIQUE (ASSET_REVISION_ID, KM_ASSET_ID, DOMAIN_ID),
    CONSTRAINT FK_KM_ASSET_REV_ASSET FOREIGN KEY (KM_ASSET_ID, DOMAIN_ID)
        REFERENCES KBOT_KM_ASSET (KM_ASSET_ID, DOMAIN_ID),
    CONSTRAINT CK_KM_ASSET_REV_STATUS CHECK (STATUS IN ('DISCOVERED', 'PROCESSING', 'READY', 'FAILED'))
);
CREATE INDEX IX_KM_ASSET_REV_SCOPE ON KBOT_KM_ASSET_REVISION (DOMAIN_ID, STATUS, CREATED_AT);
ALTER TABLE KBOT_KM_ASSET ADD CONSTRAINT FK_KM_ASSET_CURRENT_REV
    FOREIGN KEY (CURRENT_REVISION_ID, KM_ASSET_ID, DOMAIN_ID)
    REFERENCES KBOT_KM_ASSET_REVISION (ASSET_REVISION_ID, KM_ASSET_ID, DOMAIN_ID)
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE KBOT_KM_ATTACHMENT (
    ATTACHMENT_ID RAW(16) PRIMARY KEY,
    ASSET_REVISION_ID RAW(16) NOT NULL,
    EXTERNAL_DOCUMENT_ID VARCHAR2(256 CHAR) NOT NULL,
    SOURCE_URL VARCHAR2(2048 CHAR) NOT NULL,
    FILE_NAME VARCHAR2(512 CHAR),
    MIME_TYPE VARCHAR2(255 CHAR),
    ORDINAL_NO NUMBER(10) NOT NULL,
    BYTE_SIZE NUMBER(19),
    CONTENT_SHA256 VARCHAR2(64 CHAR),
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KM_ATTACHMENT_SOURCE UNIQUE (ASSET_REVISION_ID, EXTERNAL_DOCUMENT_ID),
    CONSTRAINT FK_KM_ATTACHMENT_REV FOREIGN KEY (ASSET_REVISION_ID)
        REFERENCES KBOT_KM_ASSET_REVISION (ASSET_REVISION_ID),
    CONSTRAINT CK_KM_ATTACHMENT_STATUS CHECK (STATUS IN ('DECLARED', 'DOWNLOADING', 'AVAILABLE', 'FAILED')),
    CONSTRAINT CK_KM_ATTACHMENT_ORDINAL CHECK (ORDINAL_NO >= 0)
);
CREATE INDEX IX_KM_ATTACHMENT_REV_STATUS ON KBOT_KM_ATTACHMENT (ASSET_REVISION_ID, STATUS);

CREATE TABLE KBOT_KM_JOB (
    JOB_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    SOURCE_ID RAW(16),
    KM_ASSET_ID RAW(16),
    ASSET_REVISION_ID RAW(16),
    JOB_TYPE VARCHAR2(32 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(256 CHAR) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    PRIORITY NUMBER(10) DEFAULT 0 NOT NULL,
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    MAX_ATTEMPTS NUMBER(10) DEFAULT 5 NOT NULL,
    AVAILABLE_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LEASE_OWNER VARCHAR2(256 CHAR),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT UK_KM_JOB_KEY UNIQUE (DOMAIN_ID, IDEMPOTENCY_KEY),
    CONSTRAINT FK_KM_JOB_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_KM_JOB_SOURCE FOREIGN KEY (SOURCE_ID)
        REFERENCES KBOT_KM_SOURCE (SOURCE_ID),
    CONSTRAINT FK_KM_JOB_ASSET FOREIGN KEY (KM_ASSET_ID)
        REFERENCES KBOT_KM_ASSET (KM_ASSET_ID),
    CONSTRAINT FK_KM_JOB_REV FOREIGN KEY (ASSET_REVISION_ID)
        REFERENCES KBOT_KM_ASSET_REVISION (ASSET_REVISION_ID),
    CONSTRAINT CK_KM_JOB_TYPE CHECK (JOB_TYPE IN ('SOURCE_SYNC', 'ATTACHMENT_DOWNLOAD', 'KC_INGEST', 'KC_STATUS_SYNC', 'SOURCE_STATUS_UPDATE', 'RETRY')),
    CONSTRAINT CK_KM_JOB_STATUS CHECK (STATUS IN ('PENDING', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT CK_KM_JOB_ATTEMPTS CHECK (ATTEMPT_COUNT >= 0 AND MAX_ATTEMPTS > 0)
);
CREATE INDEX IX_KM_JOB_CLAIM ON KBOT_KM_JOB (STATUS, AVAILABLE_AT, PRIORITY);

CREATE TABLE KBOT_KM_AGENT (
    AGENT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    DISPLAY_NAME VARCHAR2(256 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    CURRENT_VERSION_ID RAW(16),
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KM_AGENT_NAME UNIQUE (DOMAIN_ID, DISPLAY_NAME),
    CONSTRAINT FK_KM_AGENT_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_KM_AGENT_STATUS CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED')),
    CONSTRAINT CK_KM_AGENT_VERSION CHECK (ROW_VERSION > 0)
);
CREATE INDEX IX_KM_AGENT_SCOPE ON KBOT_KM_AGENT (DOMAIN_ID, STATUS);

CREATE TABLE KBOT_KM_AGENT_VERSION (
    AGENT_VERSION_ID RAW(16) PRIMARY KEY,
    AGENT_ID RAW(16) NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    SOURCE_ID RAW(16) NOT NULL,
    COLLECTION_ID RAW(16) NOT NULL,
    SEMANTIC_MODEL_ID RAW(16) NOT NULL,
    POLICY_BINDING_ID RAW(16) NOT NULL,
    MODELS_JSON JSON NOT NULL,
    DO_RERANK NUMBER(1) DEFAULT 0 NOT NULL,
    INSTRUCTION CLOB,
    CONFIG_JSON JSON NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KM_AGENT_VERSION UNIQUE (AGENT_ID, VERSION_NO),
    CONSTRAINT FK_KM_AGENT_VER_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES KBOT_KM_AGENT (AGENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_KM_AGENT_VER_SOURCE FOREIGN KEY (SOURCE_ID)
        REFERENCES KBOT_KM_SOURCE (SOURCE_ID),
    CONSTRAINT CK_KM_AGENT_RERANK CHECK (DO_RERANK IN (0, 1))
);
CREATE INDEX IX_KM_AGENT_VER_AGENT ON KBOT_KM_AGENT_VERSION (AGENT_ID);
ALTER TABLE KBOT_KM_AGENT ADD CONSTRAINT FK_KM_AGENT_CURRENT_VER
    FOREIGN KEY (CURRENT_VERSION_ID) REFERENCES KBOT_KM_AGENT_VERSION (AGENT_VERSION_ID);

CREATE TABLE KBOT_KM_AGENT_GRANT (
    AGENT_GRANT_ID RAW(16) PRIMARY KEY,
    DOMAIN_ID NUMBER(38) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    SUBJECT_TYPE VARCHAR2(16 CHAR) NOT NULL,
    SUBJECT_ID VARCHAR2(256 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(256 CHAR) NOT NULL,
    UPDATED_BY VARCHAR2(256 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KM_AGENT_GRANT UNIQUE (AGENT_ID, SUBJECT_TYPE, SUBJECT_ID),
    CONSTRAINT FK_KM_AGENT_GRANT_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_KM_AGENT_GRANT_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES KBOT_KM_AGENT (AGENT_ID) ON DELETE CASCADE,
    CONSTRAINT CK_KM_AGENT_GRANT_TYPE CHECK (SUBJECT_TYPE IN ('USER', 'ROLE')),
    CONSTRAINT CK_KM_AGENT_GRANT_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_KM_AGENT_GRANT_VER CHECK (ROW_VERSION > 0)
);
CREATE INDEX IX_KM_AGENT_GRANT_SCOPE ON KBOT_KM_AGENT_GRANT (DOMAIN_ID, SUBJECT_TYPE, SUBJECT_ID, STATUS);

CREATE OR REPLACE VIEW KBOT_V_KM_ASSET_CURRENT AS
SELECT DOMAIN_ID, SOURCE_ID, KM_ASSET_ID, EXTERNAL_ASSET_ID AS ASSET_ID,
       SOURCE_REVISION, SOURCE_STATUS, INGESTION_STATUS, ASSET_TITLE,
       AUTHOR_MAIL, ASSET_PRODUCT, ASSET_SOLUTION, INDUSTRY_ID,
       CONTENT_CATEGORY, ASSET_STATUS, PUBLISH_DATE, LAST_UPDATE_TIME,
       KC_BUNDLE_ID, KC_BUNDLE_REVISION_ID, FAILURE_STAGE, ERROR_CODE,
       RAW_METADATA_JSON, NORMALIZED_METADATA_JSON, SYNCED_AT, COMPLETED_AT
FROM KBOT_KM_ASSET;

COMMENT ON TABLE KBOT_V_KM_ASSET_CURRENT IS 'KM Asset 当前元数据，供系统托管 Data Query 模型执行过滤、明细和聚合';
COMMENT ON COLUMN KBOT_V_KM_ASSET_CURRENT.AUTHOR_MAIL IS 'Asset 作者邮箱，可用于按用户统计 Asset 数量';
COMMENT ON COLUMN KBOT_V_KM_ASSET_CURRENT.ASSET_SOLUTION IS 'Asset 解决方案或主题';
COMMENT ON COLUMN KBOT_V_KM_ASSET_CURRENT.INGESTION_STATUS IS 'KBot 入库与解析状态';
