-- KM Asset App 拥有的 Slack Inbox、Conversation 映射与 Outbox。

CREATE TABLE KBOT_KM_SLACK_INBOX (
    INBOX_ID RAW(16) PRIMARY KEY,
    EVENT_ID VARCHAR2(128 CHAR) NOT NULL,
    MESSAGE_KEY VARCHAR2(64 CHAR) NOT NULL,
    WORKSPACE_ID VARCHAR2(64 CHAR) NOT NULL,
    EVENT_TYPE VARCHAR2(32 CHAR) NOT NULL,
    CHANNEL_ID VARCHAR2(64 CHAR) NOT NULL,
    SLACK_USER_ID VARCHAR2(64 CHAR) NOT NULL,
    EVENT_TS VARCHAR2(32 CHAR) NOT NULL,
    ROOT_THREAD_TS VARCHAR2(32 CHAR) NOT NULL,
    MESSAGE_TEXT CLOB NOT NULL,
    RAW_BODY_HASH VARCHAR2(64 CHAR) NOT NULL,
    RAW_PAYLOAD_JSON JSON NOT NULL,
    STATUS VARCHAR2(24 CHAR) DEFAULT 'RECEIVED' NOT NULL,
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    LEASE_OWNER VARCHAR2(128 CHAR),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    CONVERSATION_ID RAW(16),
    TURN_ID RAW(16),
    RUN_ID RAW(16),
    CALLBACK_SENT_AT TIMESTAMP(6) WITH TIME ZONE,
    ERROR_CODE VARCHAR2(64 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KM_SLACK_EVENT UNIQUE (EVENT_ID),
    CONSTRAINT UK_KM_SLACK_MESSAGE UNIQUE (MESSAGE_KEY),
    CONSTRAINT CK_KM_SLACK_INBOX_STATUS CHECK (
        STATUS IN ('RECEIVED', 'RUNNING', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT CK_KM_SLACK_INBOX_ATTEMPT CHECK (ATTEMPT_COUNT >= 0),
    CONSTRAINT CK_KM_SLACK_INBOX_HASH CHECK (LENGTH(RAW_BODY_HASH) = 64),
    CONSTRAINT CK_KM_SLACK_MESSAGE_KEY CHECK (LENGTH(MESSAGE_KEY) = 64)
);

CREATE INDEX IX_KM_SLACK_INBOX_CLAIM
    ON KBOT_KM_SLACK_INBOX (STATUS, LEASE_UNTIL, CREATED_AT);
CREATE INDEX IX_KM_SLACK_INBOX_RUN
    ON KBOT_KM_SLACK_INBOX (RUN_ID);

CREATE TABLE KBOT_KM_SLACK_THREAD (
    THREAD_ID RAW(16) PRIMARY KEY,
    WORKSPACE_ID VARCHAR2(64 CHAR) NOT NULL,
    CHANNEL_ID VARCHAR2(64 CHAR) NOT NULL,
    ROOT_THREAD_TS VARCHAR2(32 CHAR) NOT NULL,
    SLACK_USER_ID VARCHAR2(64 CHAR) NOT NULL,
    DOMAIN_ID NUMBER(38) NOT NULL,
    AGENT_ID RAW(16) NOT NULL,
    CONVERSATION_ID RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_ACTIVE_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_KM_SLACK_THREAD_SCOPE UNIQUE (
        WORKSPACE_ID, CHANNEL_ID, ROOT_THREAD_TS, SLACK_USER_ID
    ),
    CONSTRAINT FK_KM_SLACK_THREAD_DOMAIN FOREIGN KEY (DOMAIN_ID)
        REFERENCES KBOT_PLATFORM_DOMAIN (DOMAIN_ID)
);

CREATE INDEX IX_KM_SLACK_THREAD_CONV
    ON KBOT_KM_SLACK_THREAD (CONVERSATION_ID);

CREATE TABLE KBOT_KM_SLACK_DELIVERY (
    DELIVERY_ID RAW(16) PRIMARY KEY,
    INBOX_ID RAW(16) NOT NULL,
    WORKSPACE_ID VARCHAR2(64 CHAR) NOT NULL,
    CHANNEL_ID VARCHAR2(64 CHAR) NOT NULL,
    SLACK_USER_ID VARCHAR2(64 CHAR) NOT NULL,
    THREAD_TS VARCHAR2(32 CHAR) NOT NULL,
    DELIVERY_TYPE VARCHAR2(16 CHAR) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT 'PENDING' NOT NULL,
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    NEXT_ATTEMPT_AT TIMESTAMP(6) WITH TIME ZONE,
    LEASE_OWNER VARCHAR2(128 CHAR),
    LEASE_UNTIL TIMESTAMP(6) WITH TIME ZONE,
    SLACK_MESSAGE_TS VARCHAR2(32 CHAR),
    ERROR_CODE VARCHAR2(128 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELIVERED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT FK_KM_SLACK_DELIVERY_INBOX FOREIGN KEY (INBOX_ID)
        REFERENCES KBOT_KM_SLACK_INBOX (INBOX_ID),
    CONSTRAINT UK_KM_SLACK_DELIVERY_KIND UNIQUE (INBOX_ID, DELIVERY_TYPE),
    CONSTRAINT CK_KM_SLACK_DELIVERY_TYPE CHECK (
        DELIVERY_TYPE IN ('WAITING', 'FINAL')
    ),
    CONSTRAINT CK_KM_SLACK_DELIVERY_STATUS CHECK (
        STATUS IN ('PENDING', 'DELIVERED', 'FAILED')
    ),
    CONSTRAINT CK_KM_SLACK_DELIVERY_ATTEMPT CHECK (ATTEMPT_COUNT >= 0)
);

CREATE INDEX IX_KM_SLACK_DELIVERY_CLAIM
    ON KBOT_KM_SLACK_DELIVERY
        (STATUS, NEXT_ATTEMPT_AT, LEASE_UNTIL, CREATED_AT);
